UPDATE CLAUSUGEN SET TCLATIT = 'NOTAS TRANSPORTE HIDROCARBUROS' WHERE SCLAGEN = 4280;

UPDATE CLAUSUGEN SET TCLATIT = 'CLAUSULAS DE GARANTIA TRANSPORTE HIDROCARBUROS' WHERE SCLAGEN = 4281;

UPDATE CLAUSUGEN SET TCLATIT = 'EXCLUSIONES ESPECIFICAS PARA TRANSPORTE HIDROCARBUROS' WHERE SCLAGEN = 4282;

UPDATE CLAUSUGEN SET TCLATIT = 'Amparo: Vehiculos Propios/No Propios' WHERE SCLAGEN = 4287;

COMMIT;
/