DECLARE
BEGIN
INSERT INTO CFG_FORM_PROPERTY ( CEMPRES, CFORM, CIDCFG, CITEM, CPRPTY, CVALUE) 
VALUES ( 24, 'AXISCTR006', 806201, 'DSP_GAR_BENEF', 1, 0 );
EXCEPTION
WHEN OTHERS THEN
    p_tab_error(f_sysdate, f_user, 'Error insertando en CFG_FORM_PROPERTY', 1, 'Err insertando en CFG_FORM_PROPERTY', ' SQLERRM = ' || SQLERRM);
END;

DECLARE
BEGIN
INSERT INTO CFG_FORM_PROPERTY ( CEMPRES, CFORM, CIDCFG, CITEM, CPRPTY, CVALUE)
VALUES ( 24, 'AXISCTR006', 806301, 'DSP_GAR_BENEF', 1, 0 );
EXCEPTION
WHEN OTHERS THEN
    p_tab_error(f_sysdate, f_user, 'Error insertando en CFG_FORM_PROPERTY', 1, 'Err insertando en CFG_FORM_PROPERTY', ' SQLERRM = ' || SQLERRM);
END;

commit;