
BEGIN

PAC_SKIP_ORA.p_comprovacolumn('SIN_TRAMITA_ESTSINIESTRO','NCLASEPRO');
PAC_SKIP_ORA.p_comprovacolumn('SIN_TRAMITA_ESTSINIESTRO','NINSTPROC');
PAC_SKIP_ORA.p_comprovacolumn('SIN_TRAMITA_ESTSINIESTRO','NFALLOCP');
PAC_SKIP_ORA.p_comprovacolumn('SIN_TRAMITA_ESTSINIESTRO','NCALMOT');
PAC_SKIP_ORA.p_comprovacolumn('SIN_TRAMITA_ESTSINIESTRO','FCONTINGEN');
PAC_SKIP_ORA.p_comprovacolumn('SIN_TRAMITA_ESTSINIESTRO','TOBSFALLO');
END;
/

ALTER TABLE "SIN_TRAMITA_ESTSINIESTRO" ADD (NCLASEPRO NUMBER(2,0));
COMMENT ON COLUMN "SIN_TRAMITA_ESTSINIESTRO"."NCLASEPRO" IS 'Clase de proceso';
ALTER TABLE "SIN_TRAMITA_ESTSINIESTRO" ADD (NINSTPROC NUMBER(2,0));
COMMENT ON COLUMN "SIN_TRAMITA_ESTSINIESTRO"."NINSTPROC" IS 'Instancia del Proceso';
ALTER TABLE "SIN_TRAMITA_ESTSINIESTRO" ADD (NFALLOCP NUMBER(2,0));
COMMENT ON COLUMN "SIN_TRAMITA_ESTSINIESTRO"."NFALLOCP" IS 'Fallo';
ALTER TABLE "SIN_TRAMITA_ESTSINIESTRO" ADD (NCALMOT NUMBER(2,0));
COMMENT ON COLUMN "SIN_TRAMITA_ESTSINIESTRO"."NCALMOT" IS 'Calificación Motivos';
ALTER TABLE "SIN_TRAMITA_ESTSINIESTRO" ADD (FCONTINGEN DATE);
COMMENT ON COLUMN "SIN_TRAMITA_ESTSINIESTRO"."FCONTINGEN" IS 'Fecha';
ALTER TABLE "SIN_TRAMITA_ESTSINIESTRO" ADD (TOBSFALLO VARCHAR2(4000));
COMMENT ON COLUMN "SIN_TRAMITA_ESTSINIESTRO"."TOBSFALLO" IS 'Observación de Fallo';

/

