INSERT INTO SIN_CODCAUSA(CCAUSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, CATRIBU) VALUES(9250, 'AXIS', '05-APR-19', NULL, NULL, 7);

INSERT INTO SIN_DESCAUSA(CCAUSIN, CIDIOMA, TCAUSIN) VALUES(9250, 1, 'Mala Praxi');

INSERT INTO SIN_DESCAUSA(CCAUSIN, CIDIOMA, TCAUSIN) VALUES(9250, 2, 'Mala Praxis');

INSERT INTO SIN_DESCAUSA(CCAUSIN, CIDIOMA, TCAUSIN) VALUES(9250, 8, 'Mala Praxis');

INSERT INTO SIN_CODMOTCAU(CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, CNOPERIT)
    VALUES(9250, 0, 'AXIS_CONF', '04-AUG-16', NULL, NULL, NULL);

--PARA CLINICAS **********************************************************************************************************   

--RESPONSABILIDAD CIVIL CLINICAS
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7757, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);

--Predios Labores Operaciones / Vigencia
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7050, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--Predios Labores Operaciones / Evento	
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7030, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--Resp  Civil Patronal  /  vigencia	
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7053, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--Resp  Civil Patronal  /  Evento
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7033, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--Resp Civil Contratistas Y Subcont / Vigencia
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7054, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--Resp Civil Contratistas Y Subcont / Evento
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7034, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);

--Resp Civil Cruzada   /  Evento
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7035, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--Resp Civil Cruzada   /  vigencia
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7055, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--Gastos Médicos de Urgencia / Vigencia
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7056, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--Gastos Médicos de Urgencia / Evento
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7036, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--Resp Civil Vehículos Prop Y No Prop / Vigencia
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7057, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--Resp Civil Vehículos Prop Y No Prop / Evento
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7037, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--Daño Moral / Vigencia
--INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
--    VALUES(8063, 0, , 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--Daño Moral / Evento
--INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
--    VALUES(8063, 0, , 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);
	
--Perjuicios Patrim Lucro Cesante / Vigencia
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7051, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--Perjuicios Patrim Lucro Cesante / Evento
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8063, 0, 7031, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);
	
--PARA MEDICAS	**********************************************************************************************************

--INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
--    VALUES(8062, 0, , 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
--    VALUES(8062, 0, , 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);

--Perjuicios Patrim Lucro Cesante / Vigencia
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8062, 0, 7051, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);	

--Perjuicios Patrim Lucro Cesante / Evento
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8062, 0, 7031, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);

--R. CIVIL PROFESIONES MEDICAS
INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
    VALUES(8062, 0, 7762, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);
    
--PARA PROGESIONALES **********************************************************************************************************

--INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
--VALUES(8064, 0, 7758, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);
    
--INSERT INTO SIN_GAR_TRAMITACION(SPRODUC, CACTIVI, CTRAMIT,CGARANT)
--VALUES(8064,0,0,7758);

--INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
--VALUES(8064, 0, 7759, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);
    
--INSERT INTO SIN_GAR_TRAMITACION(SPRODUC, CACTIVI, CTRAMIT,CGARANT)
--VALUES(8064,0,0,7759);

--INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
--VALUES(8064, 0, 7760, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);
    
--INSERT INTO SIN_GAR_TRAMITACION(SPRODUC, CACTIVI, CTRAMIT,CGARANT)
--VALUES(8064,0,0,7760);

--INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
--VALUES(8064, 0, 7761, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);
    
--INSERT INTO SIN_GAR_TRAMITACION(SPRODUC, CACTIVI, CTRAMIT,CGARANT)
--VALUES(8064,0,0,7761);

--INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
--VALUES(8064, 0, 7031, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);
    
--INSERT INTO SIN_GAR_TRAMITACION(SPRODUC, CACTIVI, CTRAMIT,CGARANT)
--VALUES(8064,0,0,7031);
 
--INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
--VALUES(8064, 0, 7032, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);
    
--INSERT INTO SIN_GAR_TRAMITACION(SPRODUC, CACTIVI, CTRAMIT,CGARANT)
--VALUES(8064,0,0,7032);

--INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
--VALUES(8064, 0, 7051, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);
    
--INSERT INTO SIN_GAR_TRAMITACION(SPRODUC, CACTIVI, CTRAMIT,CGARANT)
--VALUES(8064,0,0,7051);

--INSERT INTO SIN_GAR_CAUSA(SPRODUC, CACTIVI, CGARANT, CCAUSIN, CMOTSIN, CUSUALT, FALTA, CUSUMOD, FMODIFI, NUMSINI)
--VALUES(8064, 0, 7052, 9250, 0, 'AXIS', '05-APR-19', NULL, NULL, NULL);
    
--INSERT INTO SIN_GAR_TRAMITACION(SPRODUC, CACTIVI, CTRAMIT,CGARANT)
--VALUES(8064,0,0,7052);




INSERT INTO SIN_DESMOTCAU(CCAUSIN, CMOTSIN, CIDIOMA, TMOTSIN)
    VALUES(9250, 0, 1, 'Mala Praxi');

INSERT INTO SIN_DESMOTCAU(CCAUSIN, CMOTSIN, CIDIOMA, TMOTSIN)
    VALUES(9250, 0, 2, 'Mala Praxis');

INSERT INTO SIN_DESMOTCAU(CCAUSIN, CMOTSIN, CIDIOMA, TMOTSIN)
    VALUES(9250, 0, 8, 'Mala Praxis');

COMMIT;	