CREATE TABLE TARIFA_RC_MEDICA
(
  ID_CLASIF NUMBER,
  RANGO_DESDE NUMBER,
  RANGO_HASTA NUMBER,
  PRIMA NUMBER
);

create or replace synonym AXIS00.TARIFA_RC_MEDICA for AXIS.TARIFA_RC_MEDICA; 

GRANT SELECT, INSERT, UPDATE, DELETE ON  TARIFA_RC_MEDICA TO r_axis;

GRANT SELECT, INSERT, UPDATE, DELETE ON  TARIFA_RC_MEDICA TO AXIS00;

GRANT SELECT, INSERT, UPDATE, DELETE ON  TARIFA_RC_MEDICA TO PROGRAMADORESCSI;

commit;
/
