update map_tabla mt 
set mt.tfrom = '(SELECT LINEA FROM ( SELECT LPAD(SUBSTR(OTROS,1,3),10,''0'')/*CODESCENARIO*/
|| ''|'' || ''0''||NVL(PAC_CONTA_SAP.GENERARUIDPARACOM(IDPAGO, TO_NUMBER(SUBSTR(OTROS,1,3)),PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',10,''#cmapead'')),IDPAGO) /*REFUNIPAGO*/
|| ''|'' || NVL(PAC_CONTA_SAP.GENERARUIDPARACOM(IDPAGO, TO_NUMBER(SUBSTR(OTROS,1,3)),PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',10,''#cmapead'')),IDPAGO) /*NUMUNICO*/     
|| ''|'' || TRIM(LEADING ''0'' FROM SUBSTR(OTROS,4,4) ) /*SOCIEDAD*/
|| ''|'' || DECODE(FF_BUSCADATOSINDSAP(12,LPAD(SUBSTR(OTROS,1,3),10,''0'')),0,TO_CHAR(FCONTA,''yyyy-MM-dd''),TO_CHAR(FEFEADM,''yyyy-MM-dd'')) /*FECCONTABLE*/
|| ''|'' || TO_CHAR(FCONTA,''yyyy-MM-dd'') /*FECDOC*/
|| ''|'' || TRIM(LEADING ''0'' FROM SUBSTR(OTROS,9,4) ) /*MONEDA*/
|| ''|'' || DECODE(PAC_CONTA_SAP.F_APLI_DIVISA_SAP(c.idpago),''SI'',(DECODE (PAC_ECO_TIPOCAMBIO.F_CAMBIO((SELECT EC.CMONEDA  FROM MONEDAS M, ECO_CODMONEDAS EC WHERE M.CIDIOMA = 8 AND M.CMONINT = EC.CMONEDA AND M.CMONEDA = (SELECT CMONEDA FROM CODIDIVISA WHERE CDIVISA = (SELECT CDIVISA FROM PRODUCTOS WHERE SPRODUC = (SELECT SPRODUC FROM SEGUROS WHERE SSEGURO = (SELECT SSEGURO FROM SEGUROS WHERE NPOLIZA = TRIM (LEADING ''0'' FROM SUBSTR (OTROS, 259, 19))))))), TRIM(LEADING ''0'' FROM SUBSTR(OTROS,9,4) ), FEFEADM), 1, NULL, PAC_ECO_TIPOCAMBIO.F_CAMBIO((SELECT EC.CMONEDA  FROM MONEDAS M, ECO_CODMONEDAS EC WHERE M.CIDIOMA = 8 AND M.CMONINT = EC.CMONEDA AND M.CMONEDA = (SELECT CMONEDA FROM CODIDIVISA WHERE CDIVISA = (SELECT CDIVISA FROM PRODUCTOS WHERE SPRODUC = (SELECT SPRODUC FROM SEGUROS WHERE SSEGURO = (SELECT SSEGURO FROM SEGUROS WHERE NPOLIZA = TRIM (LEADING ''0'' FROM SUBSTR (OTROS, 259, 19))))))), TRIM(LEADING ''0'' FROM SUBSTR(OTROS,9,4) ), FEFEADM))),''NO'','''') /*TASPAC*/
|| ''|'' || DECODE(PAC_CONTA_SAP.F_APLI_DIVISA_SAP(c.idpago),''SI'',(DECODE ((SELECT EC.CMONEDA  FROM MONEDAS M, ECO_CODMONEDAS EC WHERE M.CIDIOMA = PAC_MD_COMMON.F_GET_CXTIDIOMA AND M.CMONINT = EC.CMONEDA AND M.CMONEDA = (SELECT CMONEDA FROM CODIDIVISA WHERE CDIVISA = (SELECT CDIVISA FROM PRODUCTOS WHERE SPRODUC = (SELECT SPRODUC FROM SEGUROS WHERE SSEGURO = (SELECT SSEGURO FROM SEGUROS WHERE NPOLIZA = TRIM (LEADING ''0'' FROM SUBSTR (OTROS, 259, 19))))))), ''COP'', NULL, DECODE((SELECT EC.CMONEDA  FROM MONEDAS M, ECO_CODMONEDAS EC WHERE M.CIDIOMA = PAC_MD_COMMON.F_GET_CXTIDIOMA AND M.CMONINT = EC.CMONEDA AND M.CMONEDA = (SELECT CMONEDA FROM CODIDIVISA WHERE CDIVISA = (SELECT CDIVISA FROM PRODUCTOS WHERE SPRODUC = (SELECT SPRODUC FROM SEGUROS WHERE SSEGURO = (SELECT SSEGURO FROM SEGUROS WHERE NPOLIZA = TRIM (LEADING ''0'' FROM SUBSTR (OTROS, 259, 19))))))),''EUR'',''USD'',''USD''))),''NO'','''') /*MONUSD*/
|| ''|'' || TRIM(LEADING ''0'' FROM SUBSTR(OTROS,57,13)) /*ORIGEN*/
|| ''|'' || TLIBRO /*LEDGER*/ LINEA
FROM CONTAB_ASIENT_INTERF C 
WHERE (IDPAGO = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',16, ''#cmapead'') OR PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',16,''#cmapead'') IS NULL) 
AND SINTERF = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',10,''#cmapead'') AND TTIPPAG = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',14, ''#cmapead'') ORDER BY FEFEADM ) A
WHERE ROWNUM = 1)', mt.tdescrip = 'CABECERA' where mt.ctabla = 100311;

----------------------------------------------------

update map_tabla mt 
set mt.tfrom = '(SELECT REPLACE(TO_CHAR(NVL((SELECT DISTINCT T1.* FROM (SELECT FF_BUSCADATOSINDSAP(3,M.SSEGURO) LINEA 
 FROM MOVCONTASAP M,CONTAB_ASIENT_INTERF CAI
 WHERE (CAI.IDPAGO = M.NRECIBO 
 AND CAI.CCUENTA IN (''168405'',''168410'',''168415''))
 AND M.SINTERF = CAI.SINTERF
 AND M.NRECIBO = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',16,''#cmapead'')
 AND M.SINTERF = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',10,''#cmapead''))T1), '''')), '','', ''.'') LINEA FROM DUAL)',
mt.tdescrip = 'PORCENTAJES' where mt.ctabla = 100313;

----------------------------------------------------
update map_tabla mt 
set mt.tfrom = '(SELECT LINEA FROM (
SELECT ''AC'' MM, LINEA FROM (
 SELECT DISTINCT P.SPERSON_ACRE||''|''||AC.PPARTICI||''|''||DECODE(A.CTIPAGE,3,''A'',5,''A'',6,''A'',7,''A'',4,''C'')||''|''||DECODE(PR.CREGFISCAL, 2, ''S'', ''C'') LINEA
   FROM PER_PERSONAS P,PER_REGIMENFISCAL PR, AGE_CORRETAJE AC,MOVCONTASAP M,CONTAB_ASIENT_INTERF CAI,AGENTES A
  WHERE P.SPERSON = PR.SPERSON AND PR.SPERSON = A.SPERSON AND A.CAGENTE = AC.CAGENTE AND AC.SSEGURO = M.SSEGURO AND CAI.SINTERF = M.SINTERF
    AND AC.NMOVIMI = M.NMOVIMI AND CAI.IDPAGO = M.NRECIBO  AND CAI.CCUENTA IN (''168405'',''168410'',''168415'')
    AND PR.FEFECTO = (SELECT MAX(P.FEFECTO) FROM PER_REGIMENFISCAL P WHERE P.SPERSON = A.SPERSON)
    AND M.NRECIBO = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',16,''#cmapead'')
    AND M.SINTERF = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',10,''#cmapead''))
UNION
SELECT ''NO'' MM,'''' LINEA FROM DUAL
UNION
SELECT ''A'' MM, LINEA FROM (
SELECT DISTINCT P.SPERSON_ACRE||''|''||100||''|''||DECODE(A.CTIPAGE,3,''A'',5,''A'',6,''A'',7,''A'',4,''C'')||''|''||DECODE(PR.CREGFISCAL, 2, ''S'', ''C'') LINEA
 FROM PER_PERSONAS P,PER_REGIMENFISCAL PR, AGENTES A,MOVCONTASAP M,CONTAB_ASIENT_INTERF CAI
WHERE P.SPERSON = A.SPERSON
AND PR.SPERSON = A.SPERSON AND CAI.SINTERF = M.SINTERF
AND A.CAGENTE = M.CAGENTE
AND CAI.IDPAGO = M.NRECIBO  AND CAI.CCUENTA IN (''168405'',''168410'',''168415'')
AND PR.FEFECTO = (SELECT MAX(P.FEFECTO) FROM PER_REGIMENFISCAL P WHERE P.SPERSON = A.SPERSON)
AND M.NRECIBO = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',16,''#cmapead'')
AND M.SINTERF = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',10,''#cmapead''))) T1
WHERE PAC_CONTA_SAP.F_INTERMEDIARIO_SAP(PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',16,''#cmapead''),PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',10,''#cmapead'')) = T1.MM AND T1.LINEA IS NOT NULL)',
mt.tdescrip = 'INTERMEDIARIO'
where mt.ctabla = 100314;

----------------------------------------------------
update map_tabla mt 
set mt.tfrom = '(SELECT DISTINCT P.SPERSON_DEUD ||''|''|| B.PPARTICIPACION LINEA
  FROM TOMADORES A, PER_PERSONAS_REL B, PER_PERSONAS P,MOVCONTASAP M,CONTAB_ASIENT_INTERF CAI
 WHERE P.SPERSON = B.SPERSON_REL
   AND A.SPERSON = B.SPERSON
   AND M.SINTERF = CAI.SINTERF 
   AND A.CAGRUPA = B.CAGRUPA
   AND B.CAGRUPA <> 0
   AND A.SSEGURO = M.SSEGURO
   AND (CAI.IDPAGO = M.NRECIBO AND CAI.CCUENTA IN (''168405'',''168410'',''168415''))  
   AND M.NRECIBO = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',16,''#cmapead'')
   AND M.SINTERF = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',10,''#cmapead''))',
mt.tdescrip = 'CONSORCIO' where mt.ctabla = 100315;

----------------------------------------------------
update map_tabla mt 
set mt.tfrom ='(SELECT P.SPERSON_ACRE || ''|'' || B.PCESCOA LINEA
  FROM COMPANIAS A, COACEDIDO B, PER_PERSONAS P,MOVCONTASAP M,CONTAB_ASIENT_INTERF CAI
 WHERE P.SPERSON  = A.SPERSON
   AND A.CCOMPANI = B.CCOMPAN
   AND B.SSEGURO  = M.SSEGURO
   AND M.SINTERF = CAI.SINTERF 
   AND (CAI.IDPAGO = M.NRECIBO AND CAI.CCUENTA IN (''168405'',''168410'',''168415''))
   AND M.NRECIBO = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',16,''#cmapead'')
   AND M.SINTERF = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',10,''#cmapead'')  
UNION
SELECT P.SPERSON_ACRE || ''|'' || (100 - B.PLOCCOA) LINEA
  FROM COMPANIAS A, COACUADRO B, PER_PERSONAS P,MOVCONTASAP M,CONTAB_ASIENT_INTERF CAI
 WHERE P.SPERSON  = A.SPERSON
   AND A.CCOMPANI = B.CCOMPAN
   AND M.SINTERF = CAI.SINTERF   
   AND B.SSEGURO  = M.SSEGURO
   AND (CAI.IDPAGO = M.NRECIBO AND CAI.CCUENTA IN (''168405'',''168410'',''168415''))
   AND M.NRECIBO = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',16,''#cmapead'')
   AND M.SINTERF = PAC_MAP.F_VALOR_PARAMETRO(''|'',''#lineaini'',10,''#cmapead''))',
mt.tdescrip = 'COASEGURO'
where mt.ctabla = 100316;

commit;
/
