UPDATE MENU_OPCIONROL SET COPCION = 511 WHERE COPCION = 515 AND CROLMEN = 'MENU_TOTAL';
UPDATE MENU_OPCIONROL SET COPCION = 4001 WHERE COPCION = 4003 AND CROLMEN = 'MENU_TOTAL';
UPDATE MENU_OPCIONROL SET COPCION = 4002 WHERE COPCION = 4004 AND CROLMEN = 'MENU_TOTAL';
UPDATE MENU_OPCIONROL SET COPCION = 541 WHERE COPCION = 543 AND CROLMEN = 'MENU_TOTAL';
UPDATE MENU_OPCIONROL SET COPCION = 999675 WHERE COPCION = 999676 AND CROLMEN = 'MENU_TOTAL';

COMMIT;