--Cartera Produccion Delima
INSERT INTO CFG_LANZAR_INFORMES(CEMPRES, CFORM, CMAP, TEVENTO, SPRODUC, SLITERA, LPARAMS, GENERA_REPORT, CCFGFORM, LEXPORT, CTIPO, CGENREC,CAREA) 
VALUES('24', 'AXISLIST003', 'CarteraDelima', 'GENERAL', 0, 89908054, NULL, 1, 'GENERAL', 'XLSX|PDF', 1, 0, 9);

--Parametro Fecha 
INSERT INTO CFG_LANZAR_INFORMES_PARAMS ( CEMPRES, CFORM, CMAP, TEVENTO, SPRODUC, CCFGFORM, TPARAM, NORDER, SLITERA, CTIPO, NOTNULL, LVALOR) 
VALUES ( 24, 'AXISLIST003', 'CarteraDelima', 'GENERAL', 0, 'GENERAL', 'P_FEC', 2, 9908691, 3, 1, '');

--Detalle
INSERT INTO DET_LANZAR_INFORMES ( CEMPRES, CMAP, CIDIOMA, TDESCRIP, CINFORME) 
VALUES ( 24, 'CarteraDelima', 8, 'Cartera Produccion Delima', 'Delima.jasper' );


COMMIT;