/*IAXIS-2107*/

/* DELETE PAREMPRESAS CUMULO MINIMO PARA ASOCIACION DE CONTRAGARANTIA A NUEVA PRODUCCION */

DELETE FROM DESPARAM WHERE CPARAM = 'CUMULO_MINIMO';

DELETE FROM PAREMPRESAS WHERE CPARAM = 'CUMULO_MINIMO' AND CEMPRES = 24;

DELETE FROM CODPARAM WHERE CPARAM = 'CUMULO_MINIMO';


/* INSERT PAREMPRESAS CUMULO MINIMO PARA ASOCIACION DE CONTRAGARANTIA A NUEVA PRODUCCION */

INSERT INTO CODPARAM (CPARAM, CUTILI, CTIPO, CGRPPAR, NORDEN, COBLIGA, CVISIBLE) VALUES ('CUMULO_MINIMO', '5', '1', 'GEN', '1', '0', '1');

INSERT INTO PAREMPRESAS (CEMPRES, CPARAM, TVALPAR) VALUES ('24', 'CUMULO_MINIMO', '100000000');

INSERT INTO DESPARAM(CPARAM, CIDIOMA, TPARAM) VALUES ('CUMULO_MINIMO', '1', 'Cúmul mínim per associació de contragarantia a nova producció');
INSERT INTO DESPARAM(CPARAM, CIDIOMA, TPARAM) VALUES ('CUMULO_MINIMO', '2', 'Cumulo minimo para asociación de contragarantia en nueva producción');
INSERT INTO DESPARAM(CPARAM, CIDIOMA, TPARAM) VALUES ('CUMULO_MINIMO', '8', 'Cumulo minimo para asociación de contragarantia en nueva producción');






