

DELETE FROM CFG_LANZAR_INFORMES WHERE (CMAP) LIKE 'Reporte_Informe_technico_doc';
Insert into CFG_LANZAR_INFORMES (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,SLITERA,LPARAMS,GENERA_REPORT,CCFGFORM,LEXPORT,CTIPO,CGENREC,CAREA) values (24,'AXISLIST003','Reporte_Informe_technico_doc','GENERAL',0,89907000,null,1,'GENERAL','DOCX|PDF',1,0,3);


delete from DET_LANZAR_INFORMES where CMAP='Reporte_Informe_technico_doc' and CIDIOMA=8;
Insert into DET_LANZAR_INFORMES (CEMPRES,CMAP,CIDIOMA,TDESCRIP,CINFORME) values (24,'Reporte_Informe_technico_doc',8,'Informe Tecnico','Reporte_Informe_technico_doc.jasper');



delete from CFG_LANZAR_INFORMES_PARAMS where cmap='Reporte_Informe_technico_doc' and TPARAM='PSSINIES';
Insert into CFG_LANZAR_INFORMES_PARAMS (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,CCFGFORM,TPARAM,NORDER,SLITERA,CTIPO,NOTNULL,LVALOR) values (24,'AXISLIST003','Reporte_Informe_technico_doc','GENERAL',0,'GENERAL','PSSINIES',1,9909219,1,1,null);
delete from CFG_LANZAR_INFORMES_PARAMS where cmap='Reporte_Informe_technico_doc' and TPARAM='DEPLAZO';
Insert into CFG_LANZAR_INFORMES_PARAMS (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,CCFGFORM,TPARAM,NORDER,SLITERA,CTIPO,NOTNULL,LVALOR) values (24,'AXISLIST003','Reporte_Informe_technico_doc','GENERAL',0,'GENERAL','DEPLAZO',2,89906258,1,0,null);

delete from CFG_LANZAR_INFORMES_PARAMS where cmap='Reporte_Informe_technico_doc' and TPARAM='Interventor';
Insert into CFG_LANZAR_INFORMES_PARAMS (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,CCFGFORM,TPARAM,NORDER,SLITERA,CTIPO,NOTNULL,LVALOR) values (24,'AXISLIST003','Reporte_Informe_technico_doc','GENERAL',0,'GENERAL','Interventor',3,89906259,1,0,null);

delete from CFG_LANZAR_INFORMES_PARAMS where cmap='Reporte_Informe_technico_doc' and TPARAM='Supervisor';
Insert into CFG_LANZAR_INFORMES_PARAMS (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,CCFGFORM,TPARAM,NORDER,SLITERA,CTIPO,NOTNULL,LVALOR) values (24,'AXISLIST003','Reporte_Informe_technico_doc','GENERAL',0,'GENERAL','Supervisor',4,89906260,1,0,null);

delete from CFG_LANZAR_INFORMES_PARAMS where cmap='Reporte_Informe_technico_doc' and TPARAM='FELABORACION';
Insert into CFG_LANZAR_INFORMES_PARAMS (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,CCFGFORM,TPARAM,NORDER,SLITERA,CTIPO,NOTNULL,LVALOR) values (24,'AXISLIST003','Reporte_Informe_technico_doc','GENERAL',0,'GENERAL','FELABORACION',5,9909578,3,0,null);


delete from CFG_LANZAR_INFORMES_PARAMS where cmap='Reporte_Informe_technico_doc' and TPARAM='FUENTEDEINFO';
Insert into CFG_LANZAR_INFORMES_PARAMS (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,CCFGFORM,TPARAM,NORDER,SLITERA,CTIPO,NOTNULL,LVALOR) values (24,'AXISLIST003','Reporte_Informe_technico_doc','GENERAL',0,'GENERAL','FUENTEDEINFO',6,89906263,1,0,null);
DELETE FROM CFG_LANZAR_INFORMES_PARAMS WHERE (CMAP) LIKE 'Reporte_Informe_technico_doc' AND TPARAM='PSSEGURO' ;

commit;

