

DELETE FROM CFG_LANZAR_INFORMES WHERE (CMAP) LIKE 'CierreDeSiniestros';
Insert into CFG_LANZAR_INFORMES (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,SLITERA,LPARAMS,GENERA_REPORT,CCFGFORM,LEXPORT,CTIPO,CGENREC,CAREA) values (24,'AXISLIST003','CierreDeSiniestros','GENERAL',0,89908044,null,1,'GENERAL','XLSX|PDF',1,0,3);


delete from DET_LANZAR_INFORMES where CMAP='CierreDeSiniestros' and CIDIOMA=8;
Insert into DET_LANZAR_INFORMES (CEMPRES,CMAP,CIDIOMA,TDESCRIP,CINFORME) values (24,'CierreDeSiniestros',8,'Informe Tecnico','CierreDeSiniestros.jasper');



delete from CFG_LANZAR_INFORMES_PARAMS where cmap='CierreDeSiniestros' and TPARAM='VALORULEA';
delete from CFG_LANZAR_INFORMES_PARAMS where cmap='CierreDeSiniestros' and TPARAM='SPROCES';
Insert into CFG_LANZAR_INFORMES_PARAMS (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,CCFGFORM,TPARAM,NORDER,SLITERA,CTIPO,NOTNULL,LVALOR) values (24,'AXISLIST003','CierreDeSiniestros','GENERAL',0,'GENERAL','SPROCES',1,9000493,1,1,null);

commit;

