DECLARE
	v_contexto NUMBER := 0;
BEGIN

	v_contexto := pac_contexto.f_inicializarctx(pac_parametros.f_parempresa_t(24,'USER_BBDD'));

UPDATE clausugen
SET TCLATEX  = 'CLAUSULAS DE GARANTIA: EL CONTRATISTA SE COMPROMETE A REALIZAR LOS RESPECTIVOS AISLAMIENTOS DE LA OBRA Y A TOMAR LAS RESPECTIVAS MEDIDAS DE<br>SEGURIDAD COMO SON CERRAMIENTOS, MALLAS DE PROTECCIÓN, SEÑALIZACIÓN, AVISOS ETC. EL CONTRATISTA DEBE CONTAR CON UN PLAN DE MANEJO VEHICULAR DONDE SE INVOLUCREN ACTIVIDADES COMO PASOS TEMPORALES PEATONES Y VEHÍCULOS, INSTALACIÓN DE BARRICADAS, CANECAS REFLECTIVAS, CONOS LUMINOSOS, DELINEADORES DEMARCACIONES DE CALZADA ETC.'
WHERE SCLAGEN = 4243
AND CIDIOMA = 8;

UPDATE clausugen
SET TCLATEX  = 'CLAUSULAS DE GARANTIA: EL CONTRATISTA SE COMPROMETE A REALIZAR LOS RESPECTIVOS AISLAMIENTOS DE LA OBRA Y A TOMAR LAS RESPECTIVAS MEDIDAS DE SEGURIDAD COMO SON CERRAMIENTOS, MALLAS DE PROTECCIÓN, SEÑALIZACIÓN, AVISOS ETC. EN CASO DE QUE LAS PROPIEDADES ESTÉN EN UN RADIO DE INFERIOR A 100 MTS DISTANTES DE LA OBRA EL CONTRATISTA DEBE COMPROMETERSE A SUSCRIBIR TODAS LAS ACTAS DE VECINDADES DE LOS PREDIOS PREVIO INICIO DE LOS TRABAJOS. EN CASO DE AFECTAR REDES EXISTENTES EL CONTRATISTA DEBERÁ CONOCER EL DISEÑO ESTRUCTURAL DE LOS TRAZADOS DE TENDIDOS DE REDES DE SERVICIOS PÚBLICOS QUE SE VEAN AFECTADAS CON RAZÓN DE LOS TRABAJOS. LA PRESENTE POLIZA NO AMPARA LAS FALLAS O INTERRUPCIONES EN LOS SERVICIOS PUBLICOS, ASI COMO TAMPOCO LOS DAÑOS CONSECUENCIALES DERIVADOS DE DICHAS FALLAS O INTERRUPCIONES.'
WHERE SCLAGEN = 4244
AND CIDIOMA = 8;

UPDATE clausugen
SET TCLATEX  = 'NO SE AMPARAN LOS DAÑOS CAUSADOS A LA MERCANCIA TRANSPORTADA. 2) *EN CASO DE SINIESTRO EL TOMADOR/ASEGURADO DEBERA DEMOSTRAR LA RELACION QUE EXISTE ENTRE EL VEHICULO SINIESTRADO Y EL CONTRATO AMPARADO BAJO LA PRESENTE POLIZA.(CUANDO NO HAN SUMINISTRADO LA RELACION DE VEHICULOS). 3)LA PRESENTE POLIZA TIENE COBERTURA PARA VEHICULOS CON MODELO SUPERIOR A 1995'
WHERE SCLAGEN = 4246
AND CIDIOMA = 8;

UPDATE clausugen
SET TCLATEX  = 'REVOCACION DE LA POLIZA 60 DIAS , PREVIO AVISO AL MINISTERIO LA PRESENTE POLIZA AMPARA CONTABIMINACION AMBIENTAL SUBITA E IMPREVISTA, MAS NO LA PAULATINA ESTA PÓLIZA CUBRE AL CABEZOTE MAS CUALQUIER REMOLQUE QUE SE ENGANCHE A ESTE DESIGNACION DE AJUSTADORES POR MUTUO ACUERDO CON EL ASEGURADO CLAUSULA DE ARBITRAMENTO COLOMBIANA AMPLIACION DEL PLAZO PARA AVISO DE SINIESTRO A 10 DIAS'
WHERE SCLAGEN = 4283
AND CIDIOMA = 8;

    COMMIT;

END;