----- DELETE VISTA ----------
BEGIN
    PAC_SKIP_ORA.p_comprovadrop('DIM_INTERMEDIARIO','MATERIALIZED VIEW');  
END;
/

----- CREATE VISTA ----------
  CREATE MATERIALIZED VIEW "CONF_DWH"."DIM_INTERMEDIARIO" ("INTRM_ID", "INTRM_INTERMEDIARIO_TID", "INTRM_INTERMEDIARIO", "INTRM_COD_INTERMEDIARIO","INTRM_INTERMEDIARIO_NOM", "INTRM_INTERMEDIARIO_TAMAÑO",
  "INTRM_DIRECC_OFICINA", "INTRM_CIUDAD",   "INTRM_DEPARTAMENTO", "INTRM_EMAIL", "INTRM_TELEFONO_CELULAR", "INTRM_TELEFONO_OFICINA", "INTRM_NUM_EXTENSION", "INTRM_NUM_FAX", "INTRM_CIIU", 
  "INTRM_CIIU_DESC", "INTRM_SUCURSAL", "INTRM_REPRESENTE_LEGAL", "INTRM_CLAVE", "INTRM_TIPO_CANAL", 
  "FECHA_REGISTRO", "ESTADO", "START_ESTADO", "END_ESTADO", "FECHA_CONTROL", "FECHA_INICIAL", "FECHA_FIN", "INTRM_CATTRIBUTARIA", "INTRM_TIPPER", "INTRM_ESTADO", "INTRM_GIRO_COM", "INTRM_BANCO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CONF_DWH"   NO INMEMORY 
BUILD IMMEDIATE
USING INDEX 
REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
USING DEFAULT LOCAL ROLLBACK SEGMENT
USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT INTRM_ID.NEXTVAL@BODEGA INTRM_ID,
         AC.CTIPINT INTRM_INTERMEDIARIO_TID,
         P.NNUMIDE INTRM_INTERMEDIARIO,
		 P.NNUMIDE INTRM_COD_INTERMEDIARIO,
         AXIS.F_DESAGENTE_T(A.CAGENTE)INTRM_INTERMEDIARIO_NOM,
         ' ' INTRM_INTERMEDIARIO_TAMAÑO,
         NVL(AXIS.PAC_ISQLFOR.F_DIRECCION(A.SPERSON, 1), ' ') INTRM_DIRECC_OFICINA,
         NVL(AXIS.PAC_ISQLFOR.F_POBLACION(A.SPERSON, 1), ' ') INTRM_CIUDAD,
         NVL(AXIS.PAC_ISQLFOR.F_PROVINCIA(A.SPERSON, 1), ' ') INTRM_DEPARTAMENTO,
         NVL(AXIS.PAC_ISQLFOR.F_PER_CONTACTOS(A.SPERSON, 3), ' ') INTRM_EMAIL,
         NVL(AXIS.PAC_ISQLFOR.F_PER_CONTACTOS(A.SPERSON, 6), ' ') INTRM_TELEFONO_CELULAR,
         NVL(AXIS.PAC_ISQLFOR.F_PER_CONTACTOS(A.SPERSON, 1), ' ') INTRM_TELEFONO_OFICINA,
         ' 'INTRM_NUM_EXTENSION,
         NVL(AXIS.PAC_ISQLFOR.F_PER_CONTACTOS(A.SPERSON, 2), ' ') INTRM_NUM_FAX,
         FIN.CCIIU INTRM_CIIU,
         FIN.TATRIBU INTRM_CIIU_DESC,
         AXIS.PAC_AGENTES.f_get_cageliq(24, 2, p.cagente) INTRM_SUCURSAL,
         AXIS.PAC_ISQLFOR_CONF.F_PER_RELACIONADAS(1,1,P.CAGENTE) INTRM_REPRESENTE_LEGAL,
         P.CAGENTE INTRM_CLAVE,
         d.tatribu INTRM_TIPO_CANAL,
         AXIS.F_SYSDATE FECHA_REGISTRO, 
         'ACTIVO' ESTADO, 
         TO_DATE('01/01/1986') START_ESTADO,
         AXIS.F_SYSDATE END_ESTADO, 
         AXIS.F_SYSDATE FECHA_CONTROL,
         TRUNC(AXIS.F_SYSDATE, 'month') FECHA_INICIAL,
         TRUNC(LAST_DAY(SYSDATE)) FECHA_FIN,
		 '0' INTRM_CATTRIBUTARIA, 
		 AXIS.FF_DESVALORFIJO(85, 8, P.CTIPPER) INTRM_TIPPER, 
		 '0' INTRM_ESTADO,
		 '0' INTRM_GIRO_COM,
		 '0' INTRM_BANCO
    FROM 
         AXIS.AGENTES A,
         AXIS.AGENTES_COMP AC,
         AXIS.PER_PERSONAS P,
         (SELECT FIN.SPERSON, FIN.CCIIU, DV.TATRIBU
          FROM AXIS.FIN_GENERAL FIN,
               AXIS.DETVALORES DV
          WHERE DV.CVALOR= 8001072 
             AND DV.CIDIOMA=8
             AND FIN.CCIIU=DV.CATRIBU) FIN,
          (SELECT d.tatribu, d.catribu
            FROM AXIS.DETVALORES d
            WHERE d.CIDIOMA = 8
              AND d.CVALOR = 1062) D      
         WHERE AC.CAGENTE       =   A.CAGENTE
           AND A.SPERSON        =   P.SPERSON
           AND FIN.SPERSON(+)   =   P.SPERSON
           AND D.CATRIBU(+)     =   A.CTIPMED
           AND AXIS.PAC_CONTEXTO.f_inicializarctx(AXIS.PAC_PARAMETROS.f_parempresa_t(24,'USER_BBDD'))=0;

   COMMENT ON MATERIALIZED VIEW "CONF_DWH"."DIM_INTERMEDIARIO"  IS 'snapshot table for snapshot DWH_CONF.DIM_INTERMEDIARIO';
