----- DELETE VISTA ----------
BEGIN
    PAC_SKIP_ORA.p_comprovadrop('DIM_TIPO_DOCUMENTO','MATERIALIZED VIEW');  
END;
/

----- CREATE VISTA ----------
  CREATE MATERIALIZED VIEW "CONF_DWH"."DIM_TIPO_DOCUMENTO" ("TDO_ID", "TDO_TIPO_DOC", "TDO_TIPO_DOC_DESC", "FECHA_REGISTRO", "ESTADO", "START_ESTADO", "END_ESTADO", "FECHA_CONTROL", "FECHA_INICIAL", "FECHA_FIN")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CONF_DWH"   NO INMEMORY 
BUILD IMMEDIATE
USING INDEX 
REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
USING DEFAULT LOCAL ROLLBACK SEGMENT
USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select 
SEQ_TDO_ID.NEXTVAL@BODEGA TDO_ID,
D.CATRIBU TDO_TIPO_DOC,
D.TATRIBU TDO_TIPO_DOC_DESC,
AXIS.F_SYSDATE FECHA_REGISTRO,
'ACTIVO' ESTADO,
TO_DATE('01/01/1986') START_ESTADO,
' ' END_ESTADO,
AXIS.F_SYSDATE FECHA_CONTROL,
TRUNC(AXIS.F_SYSDATE, 'month') FECHA_INICIAL,
TRUNC(LAST_DAY(AXIS.F_SYSDATE))FECHA_FIN
FROM AXIS.detvalores D
where D.cvalor = 672--800049
  and D.cidioma = 8;

   COMMENT ON MATERIALIZED VIEW "CONF_DWH"."DIM_TIPO_DOCUMENTO"  IS 'snapshot table for snapshot DWH_CONF.DIM_TIPO_DOCUMENTO';
