----- DELETE VISTA ----------
BEGIN
    PAC_SKIP_ORA.p_comprovadrop('DIM_CONTRAGARANTIA','MATERIALIZED VIEW');  
END;
/

----- CREATE VISTA ----------
  CREATE MATERIALIZED VIEW "CONF_DWH"."DIM_CONTRAGARANTIA" ("CNTRG_ID", "CNTRG_CODIGO", "CNTRG_PERSONA", "CNTRG_PERSONA_NOMBRE", "CNTRG_ESTADO", "CNTRG_ESTADO_DESC", 
  "CNTRG_TIPO", "CNTRG_TIPO_DESC", "CNTRG_CLASE", "CNTRG_CLASE_DESC", "CNTRG_UBICACION", "CNTRG_POLIZA", "CNTRG_VALORGARANTIA", "CNTRG_VALORCERRADO", "CNTRG_USUARIOCUSTODIA", 
  "CNTRG_FECHAEMISION", "CNTRG_FECHAVENCIMIENTO", "CNTRG_FECHARADICACION", "CNTRG_FECHACERRADA",  "FECHA_REGISTRO", "ESTADO", "START_ESTADO", "END_ESTADO", 
  "FECHA_CONTROL", "FECHA_INICIAL", "FECHA_FIN", "DESCRIPCION")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CONF_DWH"   NO INMEMORY 
BUILD IMMEDIATE
USING INDEX 
REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
USING DEFAULT LOCAL ROLLBACK SEGMENT
USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT CNTRG_ID.NEXTVAL@BODEGA CNTRG_ID,
        C.SCONTGAR CNTRG_CODIGO, 
        P.NNUMIDE CNTRG_PERSONA, 
        INITCAP(AXIS.PAC_ISQLFOR.F_DADES_PERSONA(P.SPERSON, 4, 5, 'POL') || ' ' || AXIS.PAC_ISQLFOR.F_DADES_PERSONA(P.SPERSON, 5, 5, 'POL')) CNTRG_PERSONA_NOMBRE,
        C.CESTADO CNTRG_ESTADO,
        AXIS.FF_DESVALORFIJO(8001038, AXIS.PAC_MD_COMMON.F_GET_CXTIDIOMA, C.CESTADO) CNTRG_ESTADO_DESC,
        C.CTIPO CNTRG_TIPO,
        AXIS.FF_DESVALORFIJO(8001035, AXIS.PAC_MD_COMMON.F_GET_CXTIDIOMA, C.CTIPO) CNTRG_TIPO_DESC, 
        C.CCLASE CNTRG_CLASE,
        AXIS.FF_DESVALORFIJO(8001036, AXIS.PAC_MD_COMMON.F_GET_CXTIDIOMA, C.CCLASE) CNTRG_CLASE_DESC,
        AXIS.PAC_ISQLFOR.f_domicilio(P.SPERSON,1) CNTRG_UBICACION,
        S.NPOLIZA CNTRG_POLIZA,
        C.IVALOR CNTRG_VALORGARANTIA,
        C.IVALOR CNTRG_VALORCERRADO,
        CC.TATRIBU CNTRG_USUARIOCUSTODIA,
        C.FALTA CNTRG_FECHAEMISION,
        C.FVENCIMI CNTRG_FECHAVENCIMIENTO,
        C.FCREA CNTRG_FECHARADICACION,
        ' ' CNTRG_FECHACERRADA,
        --c.SCONTGAR CNTRG_NUMERODOCUMENTO,
		TO_DATE('01/01/1986')FECHA_REGISTRO,
        'ACTIVO' ESTADO,
        TO_DATE('01/01/1986') START_ESTADO,
        AXIS.F_SYSDATE END_ESTADO,
        AXIS.F_SYSDATE FECHA_CONTROL,
        TRUNC(AXIS.F_SYSDATE, 'month') FECHA_INICIAL,
        TRUNC(LAST_DAY(SYSDATE)) FECHA_FIN, 
		'null' DESCRIPCION
    FROM AXIS.CTGAR_CONTRAGARANTIA C,
         AXIS.PER_CONTRAGARANTIA PC,
         AXIS.PER_PERSONAS P,
         AXIS.CTGAR_SEGURO CS,
         AXIS.SEGUROS S,
         AXIS.TOMADORES T,

         (SELECT DISTINCT  DV.TATRIBU, CC.SCONTGAR
          FROM AXIS.CTGAR_CONTRAGARANTIA CC, AXIS.DETVALORES DV
        WHERE DV.CVALOR=8001037 
          AND DV.CATRIBU=CC.CTENEDOR
          AND DV.CIDIOMA=8
          )CC
    WHERE C.SCONTGAR      = CS.SCONTGAR
          AND CS.SCONTGAR = PC.SCONTGAR
          AND S.SSEGURO   = CS.SSEGURO
          AND P.SPERSON   = PC.SPERSON
          AND P.SPERSON   = T.SPERSON
          --
          AND T.SSEGURO   = S.SSEGURO
          AND CC.SCONTGAR = C.SCONTGAR
          --
          AND AXIS.PAC_CONTEXTO.f_inicializarctx(AXIS.PAC_PARAMETROS.f_parempresa_t(24,'USER_BBDD'))=0
          AND NVL((SELECT NVALPAR FROM AXIS.PER_PARPERSONAS PARP WHERE PARP.CPARAM='PER_EXCENTO_CONTGAR' AND PARP.SPERSON=P.SPERSON),0)=0
          AND C.NMOVIMI = (SELECT MAX(NMOVIMI)
                            FROM AXIS.CTGAR_CONTRAGARANTIA
                          WHERE SCONTGAR = C.SCONTGAR);


   COMMENT ON MATERIALIZED VIEW "CONF_DWH"."DIM_CONTRAGARANTIA"  IS 'snapshot table for snapshot DWH_CONF.DIM_CONTRAGARANTIA';
   
   
 