----- DELETE VISTA ----------
BEGIN
    PAC_SKIP_ORA.p_comprovadrop('FACT_RECAUDO','MATERIALIZED VIEW');  
END;
/

----- CREATE VISTA ----------
CREATE MATERIALIZED VIEW "CONF_DWH"."FACT_RECAUDO" ("FREC_ID", "FREC_NUM_POLIZA", "FREC_NUM_CERTIFICADO", "FREC_NUMDOC", "FREC_NROCTA", 
"FREC_NUMCRU", "FREC_CTACRU", "FREC_CONSEC", "FREC_MADUREZ", "FREC_PRIM_DIRECTA", "FREC_PRIM_CEDIDA", "FREC_PRIM_ACEPTADA", "FREC_VLR_RECAUDO", 
"FECHA_REGISTRO", "ESTADO", "START_ESTADO", "END_ESTADO", "FECHA_CONTROL", "FECHA_INICIAL", "FECHA_FIN", "FREC_FK_SUCURSAL", "FREC_FK_ORIGEN", "FREC_FK_TIPDOC", "FREC_FK_TIPCRU",
 "FREC_FK_FECHA_REC", "FREC_FK_FECHA_COLOCACION", "FREC_FK_FECHA_CAM", "FREC_FK_CLIENTE", "FREC_FK_AGENTE", "FREC_FK_MONEDA", "FREC_FK_TIPO_COASEGURO", "FREC_FK_USUARIO","FREC_FK_ORICRU")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CONF_DWH"   NO INMEMORY 
BUILD IMMEDIATE
USING INDEX 
REFRESH COMPLETE ON DEMAND START WITH SYSDATE+0 NEXT SYSDATE + 1
USING DEFAULT LOCAL ROLLBACK SEGMENT
USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS
  SELECT SEQ_FREC_ID.NEXTVAL@BODEGA FREC_ID, 
S.NPOLIZA FREC_NUM_POLIZA,
RDM.NCERTDIAN FREC_NUM_CERTIFICADO, 
R.NRECIBO FREC_NUMDOC,
' ' FREC_NROCTA, 
' ' FREC_NUMCRU,
' ' FREC_CTACRU, 
' ' FREC_CONSEC, 
TRUNC(DMR.FMOVIMI)-TRUNC(R.FEMISIO) FREC_MADUREZ,
VDR.IPRIDEV FREC_PRIM_DIRECTA,
VDR.ICEDNET FREC_PRIM_CEDIDA,
VDR.IPRINET FREC_PRIM_ACEPTADA,
VDR.ITOTPRI FREC_VLR_RECAUDO,
R.FEFECTO FECHA_REGISTRO,  
'ACTIVO' ESTADO,
TO_DATE('01/01/1986') START_ESTADO,
AXIS.F_SYSDATE END_ESTADO,
AXIS.F_SYSDATE FECHA_CONTROL,
TRUNC(AXIS.F_SYSDATE, 'MONTH') FECHA_INICIAL,
TRUNC(LAST_DAY(AXIS.F_SYSDATE)) FECHA_FIN,
AXIS.PAC_AGENTES.F_GET_CAGELIQ(24, RC.CTIPAGE, RC.CAGENTE) FREC_FK_SUCURSAL,
1  FREC_FK_ORIGEN,
1 FREC_FK_TIPDOC, 
1 FREC_FK_TIPCRU,
MV.FMOVINI FREC_FK_FECHA_REC,
MS.FMOVIMI FREC_FK_FECHA_COLOCACION,
' ' FREC_FK_FECHA_CAM,
MS.FEMISIO FREC_FK_CLIENTE,
S.CAGENTE FREC_FK_AGENTE, 
1 FREC_FK_MONEDA,
1 FREC_FK_TIPO_COASEGURO,
1 FREC_FK_USUARIO,
1 FREC_FK_ORICRU
FROM AXIS.SEGUROS S,
AXIS.RECIBOS R,
AXIS.DETMOVRECIBO DMR,
AXIS.VDETRECIBOS VDR,
AXIS.REDCOMERCIAL RC, 
AXIS.MOVRECIBO MV, 
AXIS.MOVSEGURO MS, 
AXIS.RANGO_DIAN_MOVSEGURO RDM
WHERE S.SSEGURO     =   R.SSEGURO
AND R.NRECIBO = DMR.NRECIBO
AND VDR.NRECIBO = DMR.NRECIBO
AND RC.CAGENTE = S.CAGENTE
AND MV.NRECIBO = R.NRECIBO
AND MV.SMOVAGR = (SELECT MAX(MM.SMOVAGR) FROM AXIS.MOVRECIBO MM WHERE MM.NRECIBO = R.NRECIBO)
AND MS.SSEGURO = S.SSEGURO
AND MS.NMOVIMI = (SELECT MAX(MOS.NMOVIMI) FROM AXIS.MOVSEGURO MOS WHERE MOS.SSEGURO = S.SSEGURO)
AND MS.SSEGURO = RDM.SSEGURO(+)
AND MS.NMOVIMI = RDM.NMOVIMI(+) 
;

COMMENT ON MATERIALIZED VIEW "CONF_DWH"."FACT_RECAUDO"  IS 'SNAPSHOT TABLE FOR SNAPSHOT DWH_CONF.FACT_RECAUDO';