--------------------------------------------------------
--  DDL for Materialized View VFACT_POLIZA
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "CONF_DWH"."VFACT_POLIZA" ("FPOL_ID", "FPOL_NUM_POLIZA", "FPOL_NUM_CERTIFICADO", "FPOL_NUM_CERTIFICADO_ANT", "FPOL_VAL_PRIMA", "FPOL_FK_SUCURSAL", "FPOL_FK_FECHA_INI", "FPOL_FK_FECHA_TER", "FPOL_FK_FECHA_EXP", "FPOL_FK_FECHA_CREA", "FPOL_FK_USUARIO", "FPOL_FK_TIPO_CERTIFICADO", "FPOL_FK_ESTADO_VIGENCIA_POLIZA", "FECHA_REGISTRO", "ESTADO", "START_ESTADO", "END_ESTADO", "FECHA_CONTROL", "FECHA_INICIAL", "FECHA_FIN")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 0 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CONF_DWH" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT rownum FPOL_ID,
	s.npoliza FPOL_NUM_POLIZA,
	r.NCERTDIAN FPOL_NUM_CERTIFICADO,
	' ' FPOL_NUM_CERTIFICADO_ANT,
	s.IPRIANU FPOL_VAL_PRIMA,
	' ' FPOL_FK_SUCURSAL,
	f_sysdate FPOL_FK_FECHA_INI,
	f_sysdate FPOL_FK_FECHA_TER,
	f_sysdate FPOL_FK_FECHA_EXP,
	f_sysdate FPOL_FK_FECHA_CREA,
	M.CUSUMOV FPOL_FK_USUARIO,
	M.CMOTMOV FPOL_FK_TIPO_CERTIFICADO,
	S.CSITUAC FPOL_FK_ESTADO_VIGENCIA_POLIZA,
	s.femisio FECHA_REGISTRO,
	'ACTIVO' ESTADO,
	TO_DATE('01/01/1986') START_ESTADO,
	' ' END_ESTADO,
	F_SYSDATE FECHA_CONTROL,
	TRUNC(F_SYSDATE, 'month') FECHA_INICIAL,
	TRUNC(LAST_DAY(F_SYSDATE)) FECHA_FIN
FROM seguros s, movseguro m, rango_dian_movseguro r
where s.sseguro = M.SSEGURO
and s.sseguro = R.SSEGURO
and R.NMOVIMI = M.NMOVIMI
and m.sseguro = R.SSEGURO;

   COMMENT ON MATERIALIZED VIEW "CONF_DWH"."VFACT_POLIZA"  IS 'snapshot table for snapshot CONF_DWH.VFACT_POLIZA';
