
DELETE FROM cfg_form WHERE CEMPRES=24 AND CFORM='AXISPER047' AND CMODO = 'NUEVO_SARLAFT' AND CCFGFORM = 'CFG_CENTRAL' AND SPRODUC = 0;
DELETE FROM cfg_cod_modo c WHERE c.cmodo = 'NUEVO_SARLAFT';
INSERT INTO cfg_cod_modo (CMODO, TMODO, CDEFECTO) VALUES ('NUEVO_SARLAFT', 'Modo nuevo sarlaft', 0);
INSERT INTO cfg_form (CEMPRES, CFORM, CMODO, CCFGFORM, SPRODUC, CIDCFG, CUSUALT, FALTA, CUSUMOD, FMODIFI)
VALUES (24, 'AXISPER047', 'NUEVO_SARLAFT', 'CFG_CENTRAL', 0, 1, f_user, TRUNC(SYSDATE), null, null);
--
COMMIT;

/
