/*SE AGREGA LA OPCIÓN Configuración personal A TODOS LOS USUARIOS*/
--SE LE ELIMINA LA OPCION A LOS USUARIOS QUE YA LA TIENEN PARA EVITAR ERROR POR DUPLICIDAD
DELETE FROM MENU_OPCIONROL WHERE COPCION = 525;
DELETE FROM MENU_OPCIONROL WHERE COPCION = 990000;
--SE AGREGA OPCION A TODOS LOS USUARIOS
insert into MENU_OPCIONROL (crolmen, copcion)
   select DISTINCT(crolmen), 525 from MENU_OPCIONROL;
insert into MENU_OPCIONROL (crolmen, copcion)
   select DISTINCT(crolmen), 990000 from MENU_OPCIONROL;
   
/
commit;