DROP TABLE ESCENARIOSAPVF;
--

create table ESCENARIOSAPVF
(
  codescenario NUMBER not null,
  codcuenta    NUMBER not null,
  producto     NUMBER not null
);
-- Create/Recreate primary, unique and foreign key constraints 
alter table ESCENARIOSAPVF
  add constraint ESCENARIOSAPVF_PK primary key (CODESCENARIO, PRODUCTO, CODCUENTA);
alter table ESCENARIOSAPVF
  add constraint ESCENARIOSAPVF_FK foreign key (CODCUENTA)
  references CUENTASSAP (CODCUENTA) on delete cascade;

GRANT SELECT, INSERT, UPDATE, DELETE ON AXIS.ESCENARIOSAPVF TO AXIS00;
create or replace synonym AXIS.ESCENARIOSAPVF for AXIS00.ESCENARIOSAPVF; 
/

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (206, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (206, 57, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (206, 58, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (206, 59, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (206, 60, 807);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (206, 61, 808);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (206, 62, 809);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (206, 63, 811);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (206, 64, 814);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (206, 65, 815);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (206, 57, 80180008);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (207, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (207, 57, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (207, 58, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (207, 59, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (207, 60, 807);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (207, 61, 808);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (207, 62, 809);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (207, 63, 811);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (207, 64, 814);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (207, 65, 815);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (207, 57, 80180008);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (208, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (208, 57, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (208, 58, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (208, 59, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (208, 60, 807);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (208, 61, 808);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (208, 62, 809);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (208, 63, 811);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (208, 64, 814);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (208, 65, 815);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (208, 57, 80180008);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (209, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (209, 57, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (209, 58, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (209, 59, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (209, 60, 807);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (209, 61, 808);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (209, 62, 809);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (209, 63, 811);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (209, 64, 814);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (209, 65, 815);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (209, 57, 80180008);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (210, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (210, 48, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (210, 49, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (210, 50, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (210, 51, 807);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (210, 52, 808);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (210, 53, 809);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (210, 54, 811);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (210, 55, 814);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (210, 56, 815);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (210, 48, 80180007);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (211, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (211, 48, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (211, 49, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (211, 50, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (211, 51, 807);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (211, 52, 808);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (211, 53, 809);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (211, 54, 811);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (211, 55, 814);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (211, 56, 815);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (211, 48, 80180007);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (212, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (212, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (214, 66, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (214, 67, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (215, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (215, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (218, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (218, 48, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (218, 49, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (218, 50, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (218, 51, 807);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (218, 52, 808);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (218, 53, 809);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (218, 54, 811);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (218, 55, 814);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (218, 56, 815);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (218, 48, 80180007);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (219, 66, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (219, 67, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (220, 1, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (220, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (220, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (225, 1, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (225, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (225, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (226, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (226, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (232, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (232, 48, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (232, 49, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (232, 50, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (232, 51, 807);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (232, 52, 808);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (232, 53, 809);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (232, 54, 811);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (232, 55, 814);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (232, 56, 815);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (232, 48, 80180007);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (233, 66, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (233, 67, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (235, 1, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (235, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (235, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (236, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (236, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (239, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (239, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (240, 1, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (240, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (240, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (241, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (241, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (246, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (246, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (248, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (248, 48, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (248, 49, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (248, 50, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (248, 51, 807);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (248, 52, 808);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (248, 53, 809);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (248, 54, 811);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (248, 55, 814);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (248, 56, 815);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (248, 48, 80180007);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (249, 66, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (249, 67, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (250, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (250, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (251, 1, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (251, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (251, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (252, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (252, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (253, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (253, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (255, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (255, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (256, 1, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (256, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (256, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (257, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (257, 13, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (263, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (263, 48, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (263, 49, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (263, 50, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (263, 51, 807);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (263, 52, 808);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (263, 53, 809);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (263, 54, 811);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (263, 55, 814);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (263, 56, 815);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (263, 48, 80180007);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (265, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (265, 57, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (265, 58, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (265, 59, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (265, 60, 807);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (265, 61, 808);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (265, 62, 809);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (265, 63, 811);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (265, 64, 814);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (265, 65, 815);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (265, 57, 80180008);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (266, 10, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (266, 57, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (266, 58, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (266, 59, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (266, 60, 807);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (266, 61, 808);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (266, 62, 809);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (266, 63, 811);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (266, 64, 814);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (266, 65, 815);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (266, 57, 80180008);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (333, 2, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (333, 14, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (333, 3, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (333, 4, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (334, 2, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (334, 14, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (334, 3, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (334, 4, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (335, 15, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (335, 47, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (335, 23, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (335, 26, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (335, 28, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (335, 24, 80180007);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (336, 15, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (336, 47, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (336, 23, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (336, 26, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (336, 28, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (336, 24, 80180007);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (337, 2, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (337, 14, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (337, 3, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (337, 4, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (338, 2, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (338, 14, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (338, 3, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (338, 4, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (339, 15, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (339, 47, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (339, 23, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (339, 26, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (339, 28, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (339, 24, 80180007);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (340, 15, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (340, 47, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (340, 23, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (340, 26, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (340, 28, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (340, 24, 80180007);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (341, 2, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (341, 14, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (341, 3, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (341, 4, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (342, 2, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (342, 14, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (342, 3, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (342, 4, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (343, 15, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (343, 47, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (343, 23, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (343, 26, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (343, 28, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (343, 24, 80180007);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (344, 15, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (344, 47, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (344, 23, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (344, 26, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (344, 28, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (344, 24, 80180007);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (345, 2, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (345, 6, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (345, 12, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (345, 14, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (345, 3, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (345, 4, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (346, 2, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (346, 6, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (346, 12, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (346, 14, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (346, 3, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (346, 4, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (347, 2, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (347, 6, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (347, 12, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (347, 14, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (347, 3, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (347, 4, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (348, 2, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (348, 6, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (348, 12, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (348, 14, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (348, 3, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (348, 4, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (349, 2, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (349, 6, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (349, 12, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (349, 14, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (349, 3, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (349, 4, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (350, 2, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (350, 6, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (350, 12, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (350, 14, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (350, 3, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (350, 4, 1);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (351, 5, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (351, 16, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (352, 5, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (352, 16, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (353, 17, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (353, 18, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (353, 19, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (353, 20, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (354, 17, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (354, 18, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (354, 19, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (354, 20, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (355, 5, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (355, 16, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (356, 5, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (356, 16, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (357, 17, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (357, 18, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (357, 19, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (357, 20, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (358, 17, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (358, 18, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (358, 19, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (358, 20, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (359, 5, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (359, 16, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (360, 5, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (360, 16, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (361, 17, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (361, 18, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (361, 19, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (361, 20, 803);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (362, 17, 0);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (362, 18, 801);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (362, 19, 802);

insert into ESCENARIOSAPVF (CODESCENARIO, CODCUENTA, PRODUCTO)
values (362, 20, 803);

commit;
/
