--------------------------------------------------------
--  DDL for Index CODCTACTES_IMP_R04
--------------------------------------------------------

  CREATE INDEX "AXIS"."CODCTACTES_IMP_R04" ON "AXIS"."CODCTACTES_IMP" ("CCONCTA_IMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
