--------------------------------------------------------
--  DDL for Index DET_PROD_PRIM_MIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AXIS"."DET_PROD_PRIM_MIN_PK" ON "AXIS"."DET_PROD_PRIM_MIN" ("SPRODUC", "CACTIVI", "CNIVEL", "CPOSICION", "FFECINI", "NORDEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
