--------------------------------------------------------
--  DDL for Index FK_MOTRETEN_REV
--------------------------------------------------------

  CREATE INDEX "AXIS"."FK_MOTRETEN_REV" ON "AXIS"."MOTRETEN_REV" ("SSEGURO", "NRIESGO", "NMOVIMI", "CMOTRET", "NMOTRET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
