--------------------------------------------------------
--  DDL for Index FK_PDS_SUPL_PDS_SUPL__PDS_SUPL
--------------------------------------------------------

  CREATE INDEX "AXIS"."FK_PDS_SUPL_PDS_SUPL__PDS_SUPL" ON "AXIS"."PDS_SUPL_ORDEN_FORM" ("CCONFIG", "TFORM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
