--------------------------------------------------------
--  DDL for Index FK_PDS_CONF_FK_ACCION_PDS_CONF
--------------------------------------------------------

  CREATE INDEX "AXIS"."FK_PDS_CONF_FK_ACCION_PDS_CONF" ON "AXIS"."PDS_CONFIG_ACCION" ("CCONACC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
