--------------------------------------------------------
--  DDL for Index HIS_COMCONVENIOS_MOD
--------------------------------------------------------

  CREATE UNIQUE INDEX "AXIS"."HIS_COMCONVENIOS_MOD" ON "AXIS"."HIS_COMCONVENIOS_MOD" ("CEMPRES", "SCOMCONV", "FINIVIG", "CMODCOM", "FHIST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."HIS_COMCONVENIOS_MOD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_COMCONVENIOS_MOD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_COMCONVENIOS_MOD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_COMCONVENIOS_MOD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_COMCONVENIOS_MOD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_COMCONVENIOS_MOD" TO "PROGRAMADORESCSI";
