--------------------------------------------------------
--  DDL for Index MIG_COACEDIDO
--------------------------------------------------------

  CREATE INDEX "AXIS"."MIG_COACEDIDO" ON "AXIS"."MIG_COACEDIDO" ("NCARGA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."MIG_COACEDIDO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_COACEDIDO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_COACEDIDO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_COACEDIDO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_COACEDIDO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_COACEDIDO" TO "PROGRAMADORESCSI";
