--------------------------------------------------------
--  DDL for Index SCAUMOT_CNV_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AXIS"."SCAUMOT_CNV_PK" ON "AXIS"."SCAUMOT_CNV" ("CCAUSIN_OLD", "CMOTSIN_OLD", "CCAUSIN_NEW", "CMOTSIN_NEW") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
