--------------------------------------------------------
--  DDL for Index SIN_GARREG_PREGUNTA_FK
--------------------------------------------------------

  CREATE INDEX "AXIS"."SIN_GARREG_PREGUNTA_FK" ON "AXIS"."SIN_GAR_PREGUNTA" ("CPREGUN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
