--------------------------------------------------------
--  DDL for Index TMPPER2_NUK_2
--------------------------------------------------------

  CREATE INDEX "AXIS"."TMPPER2_NUK_2" ON "AXIS"."TMP_PERSONES_2" ("SPERSON", "PERHOST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS_IND" ;
