DELETE FROM AXIS_LITERALES WHERE SLITERA = 89906305;
DELETE FROM AXIS_CODLITERALES WHERE SLITERA = 89906305;

INSERT INTO AXIS_CODLITERALES(SLITERA, CLITERA) VALUES (89906305, 4);
INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (1, 89906305, 'No hi ha informació financera per a l usuari.');
INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (2, 89906305, 'No existe información financiera para el usuario.');
INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (8, 89906305, 'No existe información financiera para el usuario.');

COMMIT;
/