 -- bug 4714 tema de deducibles
 DELETE FROM AXIS_LITERALES WHERE SLITERA= 89907047;
 DELETE FROM AXIS_CODLITERALES WHERE SLITERA= 89907047;
 DELETE FROM AXIS_LITERALES WHERE SLITERA= 89907041;
 DELETE FROM AXIS_CODLITERALES WHERE SLITERA= 89907041;
 INSERT INTO AXIS_CODLITERALES (SLITERA, CLITERA) VALUES ( 89907041, 2);

 INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (1, 89907041, 'Imp. en pesos');
 INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (2, 89907041, 'Imp. en pesos');
 INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (8, 89907041, 'Imp. en pesos');
 
 INSERT INTO AXIS_CODLITERALES (SLITERA, CLITERA) VALUES ( 89907047, 2);
 
 INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (1, 89907047, 'A la fecha no hay tasa para obtener el Deducible');
 INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (2, 89907047, 'A la fecha no hay tasa para obtener el Deducible');
 INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (8, 89907047, 'A la fecha no hay tasa para obtener el Deducible');
 
 COMMIT;