--CLEAN
DELETE FROM CFG_FORM WHERE CEMPRES = 24 AND CFORM = 'AXISPRO055' AND CMODO = 'ALTA' AND CIDCFG = '999995';
DELETE FROM CFG_FORM_PROPERTY WHERE CEMPRES = '24' AND CIDCFG = '999995' AND CFORM = 'AXISPRO055' AND (CITEM = 'CPROVISI' OR CITEM = 'CANIADIROP');
DELETE FROM DETVALORES WHERE CVALOR = '8001175' AND CIDIOMA = '8' AND TATRIBU = 'Otros';

--MODO
INSERT INTO CFG_FORM (CEMPRES, CFORM, CMODO, CCFGFORM, SPRODUC, CIDCFG, CUSUALT, FALTA) VALUES ('24', 'AXISPRO055', 'ALTA', 'CFG_CENTRAL', '0', '999995', 'AXIS_CONF', TO_DATE('2017-09-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
--PROPERTIES INVISIBLES
INSERT INTO CFG_FORM_PROPERTY (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES ('24', '999995', 'AXISPRO055', 'CPROVISI', '1', '0');
INSERT INTO CFG_FORM_PROPERTY (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES(24, 999995, 'AXISPRO055', 'CANIADIROP', 1, 0);
--VALOR OTRO LISTA FORM
INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8001175', '8', '4', 'Otros');
COMMIT
/