
    --insert in det_lanzar    
    Insert into DET_LANZAR_INFORMES (CEMPRES,CMAP,CIDIOMA,TDESCRIP,CINFORME) 
    values (24,'Reporte_Produccion_Primas',8,'REPORTE DE PRODUCCION – PRIMAS','Reporte_Produccion_Primas.jasper');
    
    --insert into AXIS_LITERALES
    Insert into AXIS_CODLITERALES (SLITERA,CLITERA) VALUES (89907097,2);
    Insert into AXIS_LITERALES (CIDIOMA,SLITERA,TLITERA) values (1,89907097,'REPORTE DE PRODUCCION – PRIMAS');
    Insert into AXIS_LITERALES (CIDIOMA,SLITERA,TLITERA) values (2,89907097,'REPORTE DE PRODUCCION – PRIMAS');
    Insert into AXIS_LITERALES (CIDIOMA,SLITERA,TLITERA) values (8,89907097,'REPORTE DE PRODUCCION – PRIMAS');

    --insert in CFG_LANZAR_INFORMES
     Insert into CFG_LANZAR_INFORMES (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,SLITERA,LPARAMS,GENERA_REPORT,CCFGFORM,LEXPORT,CTIPO,CGENREC,CAREA)
     values (24,'AXISLIST003','Reporte_Produccion_Primas','GENERAL',0,89907097,null,1,'GENERAL','XLSX',1,0,9);

    --insert in CFG_LANZAR_INFORMES_PARAMS
     Insert into CFG_LANZAR_INFORMES_PARAMS (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,CCFGFORM,TPARAM,NORDER,SLITERA,CTIPO,NOTNULL,LVALOR) 
     values (24,'AXISLIST003','Reporte_Produccion_Primas','GENERAL',0,'GENERAL','FECHA_DESDE',1,9902360,3,1,null);
     
     Insert into CFG_LANZAR_INFORMES_PARAMS (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,CCFGFORM,TPARAM,NORDER,SLITERA,CTIPO,NOTNULL,LVALOR) 
     values (24,'AXISLIST003','Reporte_Produccion_Primas','GENERAL',0,'GENERAL','FECHA_HASTA',2,9902361,3,1,null);

    Commit;
    /