CREATE OR REPLACE PROCEDURE P_CANCELACION_ADM IS
  V_DEV     DEVBANRECIBOS.SDEVOLU%TYPE;
  V_PRO     PROCESOSCAB.SPROCES%TYPE;
  V_TXTPROC VARCHAR2(1000);
  VERROR    NUMBER;
  E_SALIDA  EXCEPTION;
  V_IDIOMA  NUMBER := 8;
BEGIN
  IF V_DEV IS NULL THEN
    SELECT NVL(MAX(SDEVOLU), 0) INTO V_DEV FROM DEVBANPRESENTADORES;
  END IF;

  V_TXTPROC := 'PAC_DEVOLU.TRATAR_DEVOLUCIONES';
  VERROR    := PAC_DEVOLU.TRATAR_DEVOLUCIONES(V_IDIOMA, V_DEV, V_PRO);

  P_TAB_ERROR(F_SYSDATE,
              F_USER,
              'P_CANCELACION_ADM',
              V_DEV,
              V_IDIOMA,
              V_TXTPROC || ':' || VERROR);

  IF NVL(VERROR, 0) <> 0 THEN
    RAISE E_SALIDA;
  END IF;
  COMMIT;

  V_TXTPROC := 'PAC_DEVOLU.F_DEVOL_AUTOMATICO';
  VERROR    := PAC_DEVOLU.F_DEVOL_AUTOMATICO(0, 99, V_IDIOMA, V_PRO);

  P_TAB_ERROR(F_SYSDATE,
              F_USER,
              'P_CANCELACION_ADM',
              V_DEV,
              V_IDIOMA,
              V_TXTPROC || ':' || VERROR);

  IF NVL(VERROR, 0) <> 0 THEN
    RAISE E_SALIDA;
  END IF;
  COMMIT;

EXCEPTION
  WHEN E_SALIDA THEN
    P_TAB_ERROR(F_SYSDATE,
                F_USER,
                'P_CANCELACION_ADM',
                V_DEV,
                V_IDIOMA,
                'P_CANCELACION_ADM EXECPTION :' || SQLERRM);
  
END P_CANCELACION_ADM;
/

GRANT EXECUTE ON "AXIS"."P_CANCELACION_ADM" TO "R_AXIS";
GRANT EXECUTE ON "AXIS"."P_CANCELACION_ADM" TO "CONF_DWH";
GRANT EXECUTE ON "AXIS"."P_CANCELACION_ADM" TO "PROGRAMADORESCSI";


