DELETE FROM CFG_FORM_PROPERTY WHERE CITEM IN('FEFEPLAZO','PEJECUCION','FVENCPLAZO','icon_FVENCPLAZO','icon_FVENCPLAZO2','DSP_DATOS_ECONOMICOS') AND CPRPTY = 1 AND CIDCFG = 915001 AND CFORM = 'AXISCTR004';

DELETE FROM CFG_FORM_PROPERTY WHERE CITEM IN('FFINVIG','FINIVIG') AND CPRPTY = 2 AND CIDCFG = 915001 AND CFORM = 'AXISCTR207';

INSERT INTO CFG_FORM_PROPERTY(CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES ('24', '915001', 'AXISCTR004', 'FEFEPLAZO', '1', '0');

INSERT INTO CFG_FORM_PROPERTY(CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES ('24', '915001', 'AXISCTR004', 'PEJECUCION', '1', '0');

INSERT INTO CFG_FORM_PROPERTY(CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES ('24', '915001', 'AXISCTR004', 'FVENCPLAZO', '1', '0');

INSERT INTO CFG_FORM_PROPERTY(CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES ('24', '915001', 'AXISCTR004', 'icon_FVENCPLAZO', '1', '0');

INSERT INTO CFG_FORM_PROPERTY(CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES ('24', '915001', 'AXISCTR004', 'icon_FVENCPLAZO2', '1', '0');

INSERT INTO CFG_FORM_PROPERTY(CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES ('24', '915001', 'AXISCTR004', 'DSP_DATOS_ECONOMICOS', '1', '0');

INSERT INTO CFG_FORM_PROPERTY(CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES ('24', '915001', 'AXISCTR207', 'FINIVIG', '2', '0');

INSERT INTO CFG_FORM_PROPERTY(CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES ('24', '915001', 'AXISCTR207', 'FFINVIG', '2', '0');

UPDATE CFG_FORM_PROPERTY SET CVALUE = 0 WHERE CIDCFG = 915001 AND CFORM = 'AXISCTR004' AND CITEM = 'DSP_REASEGURO' AND CPRPTY = 1;

UPDATE CFG_FORM_PROPERTY SET CVALUE = 0 WHERE CIDCFG = 915001 AND CFORM = 'AXISCTR207' AND CITEM = 'DSP_PREGUNTASRIESGO' AND CPRPTY = 2;

update PREGUNPRO set CPREOBL = 0 where sproduc = 8063 and CPREGUN in (9902,9901,9906,9905,9904,9903,9900,6585);

COMMIT;