DECLARE
  v_contexto NUMBER := 0;
BEGIN

  v_contexto := pac_contexto.f_inicializarctx(pac_parametros.f_parempresa_t(24,'USER_BBDD'));
  
    DELETE CFG_FORM_PROPERTY WHERE CEMPRES=24  AND CIDCFG = 1007 AND CFORM = 'AXISPER010' AND CITEM = 'SWRUT' AND CPRPTY = 1 AND CVALUE = 0;
    DELETE CFG_FORM_PROPERTY WHERE CEMPRES=24  AND CIDCFG = 1007 AND CFORM = 'AXISPER010' AND CITEM = 'FJUBILA' AND CPRPTY = 1 AND CVALUE = 0;
    DELETE CFG_FORM_PROPERTY WHERE CEMPRES=24  AND CIDCFG = 3001 AND CFORM = 'AXISPER008' AND CITEM = 'BT_HOST' AND CPRPTY = 1 AND CVALUE = 0;
    DELETE CFG_FORM_PROPERTY WHERE CEMPRES=24  AND CIDCFG = 1001 AND CFORM = 'AXISPER008' AND CITEM = 'BT_HOST' AND CPRPTY = 1 AND CVALUE = 0;
    DELETE CFG_FORM_PROPERTY WHERE CEMPRES=24  AND CIDCFG = 1 AND CFORM = 'AXISPER008' AND CITEM = 'BT_HOST' AND CPRPTY = 1 AND CVALUE = 0;
    DELETE DETVALORES_DEP WHERE CEMPRES = 24 AND CVALOR = 85 AND CATRIBU = 1 AND CVALORDEP = 672 AND CATRIBUDEP = 98;
    DELETE DETVALORES_DEP WHERE CEMPRES = 24 AND CVALOR = 85 AND CATRIBU = 2 AND CVALORDEP = 672 AND CATRIBUDEP = 98;  
  
    INSERT INTO CFG_FORM_PROPERTY (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES (24, 1007, 'AXISPER010', 'SWRUT', 1, 0);
    INSERT INTO CFG_FORM_PROPERTY (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES (24, 1007, 'AXISPER010', 'FJUBILA', 1, 0);
    INSERT INTO CFG_FORM_PROPERTY (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES (24, 3001, 'AXISPER008', 'BT_HOST', 1, 0);
    INSERT INTO CFG_FORM_PROPERTY (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES (24, 1001, 'AXISPER008', 'BT_HOST', 1, 0);
    INSERT INTO CFG_FORM_PROPERTY (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES (24, 1, 'AXISPER008', 'BT_HOST', 1, 0);
    INSERT INTO DETVALORES_DEP (CEMPRES,CVALOR,CATRIBU,CVALORDEP,CATRIBUDEP) VALUES (24,85,1,672,98);
    INSERT INTO DETVALORES_DEP (CEMPRES,CVALOR,CATRIBU,CVALORDEP,CATRIBUDEP) VALUES (24,85,2,672,98);
    
    UPDATE CFG_FORM_PROPERTY C SET CVALUE = 0 WHERE C.CITEM = 'SWRUT_COLM' AND C.CEMPRES = 24 AND C.CIDCFG = 1007 AND C.CFORM = 'AXISPER010';
    UPDATE CFG_FORM_PROPERTY C SET CVALUE = 0 WHERE C.CITEM = 'CVIAVP' AND C.CEMPRES = 24 AND C.CIDCFG = 1007 AND C.CFORM = 'AXISPER010';
    UPDATE CFG_FORM_PROPERTY C SET CVALUE = 0 WHERE C.CITEM = 'FNACIMI' AND C.CEMPRES = 24 AND C.CIDCFG = 1007 AND C.CFORM = 'AXISPER010';
  
  COMMIT;
  
END;
/