--------------------------------------------------------
--  DDL for Function F_BUSCTACTE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "AXIS"."F_BUSCTACTE" (EMPRESA IN NUMBER, AGRUP IN NUMBER, CTA IN OUT VARCHAR2,
  DELEGACION IN NUMBER, ENTIDAD IN NUMBER)
  RETURN NUMBER authid current_user IS
/***********************************************************************
	F_BUSCTACTE: RETORNA EL NUMERO DE CUENTA CORRIENTE DE LA DELEGACIÓN
	ALLIBADM
	MODIFICACION DEL PLANTEAMIENTO DE LA TABLA
              DE CUENTA DE CARGO, PODRA VENIR DE DIFERENTES NIVELES, EL
              MINIMO SERA EMPRESA Y EL MAXIMO EMPRESA,DELEGACION,AGRUPACION,
              RAMO
	SE CAMBIAN CAMPOS DE LA TABLA
	SE CONTROLA SI DEVUELVE MÁS DE UNA FILA.
***********************************************************************/
BEGIN
	BEGIN
		SELECT DISTINCT(CCTACTE)
		INTO CTA
		FROM CTACARGO
		WHERE CEMPRES = EMPRESA
		  AND CAGRPRO = AGRUP
		  AND CENTIDA = ENTIDAD
		  AND (CDELEGA = DELEGACION OR DELEGACION IS NULL)
		  AND FVIGINI <= TRUNC(f_SYSDATE)
		  AND (FVIGFIN > TRUNC(f_SYSDATE) OR FVIGFIN IS NULL);
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
			RETURN 102413;  -- NO HAY NÚMERO DE CUENTA
		WHEN TOO_MANY_ROWS THEN
			RETURN 99;   -- ERROR DE CONTROL (HAY DELEGACIONES CON DISTINTO
					 -- NÚMERO DE CUENTA
	END;
	RETURN 0;
END;
 
 

/

  GRANT EXECUTE ON "AXIS"."F_BUSCTACTE" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."F_BUSCTACTE" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."F_BUSCTACTE" TO "PROGRAMADORESCSI";
