--------------------------------------------------------
--  DDL for Function F_MODTALON
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "AXIS"."F_MODTALON" (EMPRESA IN NUMBER,AGENTE IN NUMBER,USUARIO IN VARCHAR2,PROCESO IN NUMBER,
		TALON IN NUMBER,DELEGACION IN NUMBER, DESTINO IN NUMBER,ENTIDAD IN NUMBER,
		TTEXTO IN VARCHAR2,AGRUPACION IN NUMBER, PSMEDPAG IN NUMBER DEFAULT NULL,
		CARTA IN NUMBER DEFAULT NULL)RETURN NUMBER authid current_user IS
/***********************************************************************
	F_MODTALON: MODIFICA UN TALON EN LA TABLA MEDPAGO QUE ESTE PENDIENTE
                  DE EMITIR.
	ALLIBADM
************************************************************************/
  CURSOR CUR_TALON IS
    SELECT SMEDPAG
    FROM MEDPAGO M
    WHERE M.CEMPRES = EMPRESA
      AND (M.CAGENTE = AGENTE OR AGENTE IS NULL)
      AND (M.CDELEGA = DELEGACION OR DELEGACION IS NULL)
      AND M.CAGRPRO = AGRUPACION
      AND M.CENTIDA = ENTIDAD
      AND M.NDESTIN = DESTINO
      AND (M.CUSUARI = USUARIO OR USUARIO IS NULL)
      AND  M.CESTADO = 1
      AND (M.CTIPCAR = CARTA OR CARTA IS NULL)
      AND (M.SMEDPAG = PSMEDPAG OR PSMEDPAG IS NULL)
    ORDER BY CAGENTE;
  TALON_AUX  NUMBER := TALON;
  ERROR      NUMBER;
  PROLIN   NUMBER;
  EXISTE   NUMBER := 0;
BEGIN
  FOR VALOR IN CUR_TALON LOOP
    UPDATE MEDPAGO
       SET NTALON = TALON_AUX,
           FGENERA = SYSDATE,
           CESTADO = 2,
           SPROCES = PROCESO
       WHERE SMEDPAG = VALOR.SMEDPAG;
     TALON_AUX := TALON_AUX + 1;
     PROLIN := NULL;
     ERROR := F_PROCESLIN(PROCESO,TTEXTO,VALOR.SMEDPAG,PROLIN);
     EXISTE := 1;
  END LOOP;
  IF EXISTE= 1 THEN
    RETURN 0;
  ELSE
    RETURN 105731;  -- NO HAY TALONES PARA GENERAR
  END IF;
END;
 
 

/

  GRANT EXECUTE ON "AXIS"."F_MODTALON" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."F_MODTALON" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."F_MODTALON" TO "PROGRAMADORESCSI";
