--------------------------------------------------------
--  DDL for Function F_PROVMAPROD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "AXIS"."F_PROVMAPROD" (PSPRODUC IN NUMBER,
	   	  		  		   				 PFFIN IN DATE,
										 PCGII OUT NUMBER,
										 PCGEE OUT NUMBER,
										 PCGEI OUT NUMBER)
RETURN NUMBER IS
	   TOTAL NUMBER DEFAULT 0;
	   VCANTIDAD NUMBER DEFAULT 0;
	   VGCII NUMBER;
	   VGCEE NUMBER;
	   VGCEI NUMBER;
	   PSESION NUMBER;
	   VRAMO NUMBER;
	   VMODALI NUMBER;
	   VTIPSEG NUMBER;
	   VCOLECT NUMBER;
	   CURSOR PRODUCTE IS
	   		  SELECT CRAMO,CMODALI,CTIPSEG,CCOLECT
			  FROM PRODUCTOS
			  WHERE SPRODUC=PSPRODUC;
	   CURSOR POLIZAS IS
	   		  SELECT SSEGURO
			  FROM SEGUROS
			  WHERE CRAMO=VRAMO AND CMODALI=VMODALI
			  AND CTIPSEG=VTIPSEG AND CCOLECT=VCOLECT;
	   CURSOR GASTOS IS
	   		  SELECT PGASINT,PGAEXEX,PGAEXIN
			  FROM PRODUCTOS
			  WHERE SPRODUC=PSPRODUC;
/************************************************************************
	F_PROVMAPROD		Calcula el capital a aplicar sobre las
				        provisiones matemáticas
*************************************************************************/
BEGIN
	OPEN PRODUCTE;
	FETCH PRODUCTE INTO VRAMO,VMODALI,VTIPSEG,VCOLECT;
	CLOSE PRODUCTE;
	SELECT SGT_SESIONES.NEXTVAL INTO PSESION FROM DUAL;
	FOR pol IN POLIZAS LOOP
		--VCANTIDAD:=F_PROVMAT(PSESION,pol.sseguro,PFFIN);
		TOTAL:=TOTAL + VCANTIDAD;
	END LOOP;
	OPEN GASTOS;
	FETCH GASTOS INTO VGCII,VGCEE,VGCEI;
	CLOSE GASTOS;
	IF VGCII IS NULL THEN
	   PCGII:=0;
	ELSE
	   PCGII:=TOTAL * VGCII;
	END IF;
	IF VGCEE IS NULL THEN
	   PCGEE:=0;
	ELSE
	   PCGEE:=TOTAL * VGCEE;
	END IF;
	IF VGCEI IS NULL THEN
	   PCGEI:=0;
	ELSE
	   PCGEI:=TOTAL * VGCEI;
	END IF;
	RETURN 0;
 EXCEPTION
     WHEN OTHERS THEN
	   IF GASTOS%ISOPEN THEN
	   	  CLOSE GASTOS;
	   END IF;
	   IF PRODUCTE%ISOPEN THEN
	   	  CLOSE PRODUCTE;
	   END IF;
	   IF POLIZAS%ISOPEN THEN
	   	  CLOSE POLIZAS;
	   END IF;
       RETURN 1;
END F_PROVMAPROD;

 
 

/

  GRANT EXECUTE ON "AXIS"."F_PROVMAPROD" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."F_PROVMAPROD" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."F_PROVMAPROD" TO "PROGRAMADORESCSI";
