--------------------------------------------------------
--  DDL for Function F_TRASP_HIST_AUTORI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "AXIS"."F_TRASP_HIST_AUTORI" (PSAUTPSR IN NUMBER) RETURN NUMBER IS
  X_SHISTAUT NUMBER;
BEGIN
  SELECT SHISTAUT.NEXTVAL
    INTO X_SHISTAUT
    FROM DUAL;
  INSERT INTO HISTAUTORIZACIONES (SHISTAUT,SAUTPSR,SSEGURO,NRIESGO,NMOVIMI,CUSUPET,FPETICI,TMSGPET,CPERFEXG,
                                  CUSUAUT,FAUTORI,TMSGAUT,SSOLICIT,F_TRAHIS,CESTAUT)
            SELECT X_SHISTAUT,SAUTPSR,SSEGURO,NRIESGO,NMOVIMI,CUSUPET,FPETICI,TMSGPET,CPERFEXG,
                                CUSUAUT,FAUTORI,TMSGAUT,SSOLICIT,F_SYSDATE,CESTAUT
            FROM AUTORIZACIONES
            WHERE SAUTPSR = PSAUTPSR;
  INSERT INTO HISTDETAUTORIZACIONES(SHISTAUT,SAUTPSR,CREGLA,SASOCIA,SCONDREG,CPERFEXG,
                                      CRESPUE)
            SELECT X_SHISTAUT,SAUTPSR,CREGLA,SASOCIA,SCONDREG,CPERFEXG ,CRESPUE
   FROM DETAUTORIZACIONES
            WHERE SAUTPSR = PSAUTPSR;

  RETURN 0;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN SQLCODE;
END;

 
 

/

  GRANT EXECUTE ON "AXIS"."F_TRASP_HIST_AUTORI" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."F_TRASP_HIST_AUTORI" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."F_TRASP_HIST_AUTORI" TO "PROGRAMADORESCSI";
