--------------------------------------------------------
--  DDL for Function F_TRAMO_SOLAPADO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "AXIS"."F_TRAMO_SOLAPADO" (PTRAM NUMBER, PORDEN NUMBER, PDESDE NUMBER, PHASTA NUMBER)
 RETURN NUMBER authid current_user IS
SOLAPAT NUMBER:=0; -- 0->no solapat; <>0 solapat
BEGIN
FOR REG IN (SELECT *
		FROM SGT_DET_TRAMOS
		WHERE TRAMO = PTRAM AND ORDEN <> PORDEN)
loop
	IF PDESDE BETWEEN REG.DESDE AND REG.HASTA OR
	   PHASTA BETWEEN REG.DESDE AND REG.HASTA THEN
		SOLAPAT:=1;
		EXIT;
	END IF;
end loop;
RETURN SOLAPAT;
END;

 
 

/

  GRANT EXECUTE ON "AXIS"."F_TRAMO_SOLAPADO" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."F_TRAMO_SOLAPADO" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."F_TRAMO_SOLAPADO" TO "PROGRAMADORESCSI";
