--------------------------------------------------------
--  DDL for Function F_USUARIO_DATOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "AXIS"."F_USUARIO_DATOS" (PUSER IN VARCHAR2, PCIDIOMA OUT NUMBER,PCDELEGA OUT VARCHAR2, PFBAJA OUT DATE, PEJECUCION OUT NUMBER)
RETURN NUMBER IS
/****************************************************************************
	F_USUARIO_DATOS: DEVUELVE LOS DATOS DEL USUARIO QUE ESTAN EN LA TABLA USUARIOS
	DATOS DE ENTRADA: CODIGO DE USUARIOS.
	DATOS DE SALIDA:  IDIOMA, CODIGO DE DELEGACION, FECHA DE BAJA,
	24-11-2003  AMG
    12-01-2004 SLS Modo de ejecución del usuario
****************************************************************************/

BEGIN
	SELECT CIDIOMA,CDELEGA,FBAJA,EJECUCION
	INTO PCIDIOMA,PCDELEGA,PFBAJA,PEJECUCION
	FROM USUARIOS
	WHERE upper(CUSUARI) = UPPER(PUSER);
	RETURN 0;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
     RETURN 1;
  WHEN OTHERS THEN
     RETURN 2;
END; 
 
 

/

  GRANT EXECUTE ON "AXIS"."F_USUARIO_DATOS" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."F_USUARIO_DATOS" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."F_USUARIO_DATOS" TO "PROGRAMADORESCSI";
