--------------------------------------------------------
--  DDL for Function FRESFRAC
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "AXIS"."FRESFRAC" (F1 IN DATE, F2 IN DATE, FP IN CHAR)
RETURN NUMBER authid current_user IS
	M1	NUMBER:=0;M2	NUMBER:=0;A1	NUMBER:=0;A2	NUMBER:=0;
	DM	NUMBER:=0;COF	NUMBER:=0;NPER	NUMBER:=0;M2A	NUMBER:=0;
	A1A	NUMBER:=0;MF	NUMBER:=0;AF	NUMBER:=0;
	F1R	DATE;F2R	DATE;FF	DATE;
--F1 Es la Fecha de Efecto.
--F2 Es la Fecha de Valoraci¢n.
BEGIN
	IF FP='A' THEN COF:=12;
	ELSIF FP='S' THEN COF:=6;
	ELSIF FP='T' THEN COF:=3;
	ELSIF FP='M' THEN COF:=1;
	ELSIF FP='U' THEN RETURN 0;
	END IF;
	M1:=TO_NUMBER(TO_CHAR(F1,'MM'));
	M2:=TO_NUMBER(TO_CHAR(F2,'MM'));
	A1:=TO_NUMBER(TO_CHAR(F1,'YYYY'));
	A2:=TO_NUMBER(TO_CHAR(F2,'YYYY'));
	IF M2 < M1 THEN
		M2A := M2 + 12;
		A1A := A1 + 1;
	ELSE
		M2A := M2;
		A1A := A1;
	END IF;
	IF TO_NUMBER(TO_CHAR(F2,'DD'))<TO_NUMBER(TO_CHAR(F1,'DD')) THEN
		DM:=M2A-M1+12*(A2-A1A)-1;
	ELSE
		DM:=M2A-M1+12*(A2-A1A);
	END IF;
	NPER:=TRUNC(DM/COF);
	IF MOD(M1+(NPER+1)*COF,12)=0 THEN
		MF:=12;
		AF:=TRUNC((M1+(NPER+1)*COF)/12)+A1-1;
	ELSE
		MF:=MOD(M1+(NPER+1)*COF,12);
		AF:=TRUNC((M1+(NPER+1)*COF)/12)+A1;
	END IF;
	FF:=TO_DATE(LPAD(TO_CHAR(F1),2,'0')||'/'||LPAD(TO_CHAR(MF),2,'0')
		||'/'||TO_CHAR(AF),'DD/MM/YYYY');
--FF=CTOD(STR(DAY(F1),2)+"-"+STR(MF,2)+"-"+STR(AF,4))
	RETURN ((FF-F2)/365);
END;

 
 

/

  GRANT EXECUTE ON "AXIS"."FRESFRAC" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."FRESFRAC" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."FRESFRAC" TO "PROGRAMADORESCSI";
