Insert into CODIPLANTILLAS (CCODPLAN,IDCONSULTA,GEDOX,IDCAT,CGENFICH,CGENPDF,CGENREP,CTIPODOC,CFDIGITAL) values ('CONF800110',0,'S',1,1,1,2,null,'1');
Insert into DETPLANTILLAS (CCODPLAN,CIDIOMA,TDESCRIP,CINFORME,CPATH,CMAPEAD,CFIRMA,TCONFFIRMA) values ('CONF800110',8,'Cupon','CONFCupon.jasper','.',null,0,null);


Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8038,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8039,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8042,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8046,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8062,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8063,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80038,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80039,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80040,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80041,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80042,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80043,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80044,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);

Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80001,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80004,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80009,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80010,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80011,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80012,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);

Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80007,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80008,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);

Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80006,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80005,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80003,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80002,0,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);




Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8038,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8039,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8042,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8046,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8062,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8063,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80038,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80039,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80040,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80041,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80042,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80043,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80044,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);

Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80001,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80004,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80009,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80010,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80011,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80012,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);

Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80007,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80008,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);

Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80006,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80005,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80003,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (80002,8,'CONF800110',1,to_date('02-OCT-19','DD-MON-RR'),null,null,0,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);






Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,2,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,2,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,2,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,2,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,2,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,2,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,2,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,2,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,2,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,2,11,11);

Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,3,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,3,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,3,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,3,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,3,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,3,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,3,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,3,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,3,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,3,11,11);

Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,4,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,4,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,4,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,4,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,4,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,4,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,4,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,4,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,4,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,4,11,11);

Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,5,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,5,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,5,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,5,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,5,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,5,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,5,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,5,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,5,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80044,5,11,11);

Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,0,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,0,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,0,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,0,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,0,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,0,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,0,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,0,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,0,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,0,11,11);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,1,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,1,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,1,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,1,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,1,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,1,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,1,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,1,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,1,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80043,1,11,11);


Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,0,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,0,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,0,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,0,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,0,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,0,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,0,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,0,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,0,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,0,11,11);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,1,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,1,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,1,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,1,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,1,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,1,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,1,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,1,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,1,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80042,1,11,11);

Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,0,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,0,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,0,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,0,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,0,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,0,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,0,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,0,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,0,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,0,11,11);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,1,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,1,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,1,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,1,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,1,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,1,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,1,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,1,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,1,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80041,1,11,11);


Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,0,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,0,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,0,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,0,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,0,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,0,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,0,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,0,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,0,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,0,11,11);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,1,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,1,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,1,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,1,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,1,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,1,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,1,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,1,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,1,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80040,1,11,11);


Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8046,0,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8046,0,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8046,0,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8046,0,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8046,0,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8046,0,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8046,0,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8046,0,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8046,0,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8046,0,11,11);

Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8042,0,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8042,0,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8042,0,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8042,0,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8042,0,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8042,0,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8042,0,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8042,0,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8042,0,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8042,0,11,11);

Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8039,0,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8039,0,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8039,0,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8039,0,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8039,0,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8039,0,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8039,0,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8039,0,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8039,0,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8039,0,11,11);

Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8038,0,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8038,0,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8038,0,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8038,0,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8038,0,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8038,0,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8038,0,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8038,0,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8038,0,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8038,0,11,11);


Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8063,8,'CONF800101',1,to_date('02-OCT-19','DD-MON-RR'),null,null,1,null,null,null,null,null,null,'AXIS_CONF',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8063,8,'CONF800102',1,to_date('02-OCT-19','DD-MON-RR'),null,null,1,null,null,null,null,null,null,'AXIS',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8063,13,'CONF800101',1,to_date('02-OCT-19','DD-MON-RR'),null,null,1,null,null,null,null,null,null,'AXIS',to_date('02-OCT-19','DD-MON-RR'),null,null);
Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) values (8063,106,'CONF800103',1,to_date('02-OCT-19','DD-MON-RR'),null,null,1,null,null,null,null,null,null,'AXIS',to_date('02-OCT-19','DD-MON-RR'),null,null);

COMMIT;