/* *******************************************************************************************************************
Versión	Descripción
ACL
01.		Este script inserta en las tablas CFG_FORM_PROPERTY y CFG_FORM_DEP.          
********************************************************************************************************************** */

DELETE FROM CFG_FORM_PROPERTY
WHERE CIDCFG IN (0, 992223)
AND CEMPRES = 24
AND CFORM = 'AXISCGA002'
AND CITEM = 'CAREA'
AND CPRPTY = 4
AND CVALUE = 99840295;

DELETE FROM CFG_FORM_PROPERTY
WHERE CIDCFG IN (0, 992223)
AND CEMPRES = 24
AND CFORM = 'AXISCGA002'
AND CITEM = 'CMODO'
AND CPRPTY = 4
AND CVALUE = 99840295;

DELETE FROM CFG_FORM_DEP
WHERE CCFGDEP = 99840295
AND CITORIG = 'CAREA'
AND CITDEST IN ('CTIPO', 'CCLASE'); 

DELETE FROM CFG_FORM_DEP
WHERE CCFGDEP = 99840295
AND CITORIG = 'CMODO'
AND CITDEST = 'CAREA'; 

DELETE FROM CFG_FORM_DEP
WHERE CCFGDEP = 99840207
AND CITORIG = 'CCLASE'
AND CITDEST = 'MODELO'; 

DELETE FROM CFG_FORM_DEP
WHERE CCFGDEP = 99840292
AND CITORIG = 'CTENEDOR'
AND CITDEST IN ('CORIGEN', 'TCAUSA')
AND TVALORIG IN ('11', '12'); 

INSERT INTO CFG_FORM_PROPERTY (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE)
VALUES (24, 992223, 'AXISCGA002', 'CAREA', 4, 99840295);

INSERT INTO CFG_FORM_PROPERTY (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE)
VALUES (24, 0, 'AXISCGA002', 'CAREA', 4, 99840295);


INSERT INTO CFG_FORM_PROPERTY (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE)
VALUES (24, 992223, 'AXISCGA002', 'CMODO', 4, 99840295);

INSERT INTO CFG_FORM_PROPERTY (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE)
VALUES (24, 0, 'AXISCGA002', 'CMODO', 4, 99840295);

Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840295','CAREA','1','CTIPO','2','1');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840295','CAREA','2','CTIPO','2','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840295','CAREA','3','CTIPO','2','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840295','CAREA','4','CTIPO','2','0');

Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840295','CAREA','1','CCLASE','2','1');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840295','CAREA','2','CCLASE','2','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840295','CAREA','3','CCLASE','2','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840295','CAREA','4','CCLASE','2','0');

Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840207','CCLASE','NULL','MODELO','1','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840207','CCLASE','1','MODELO','1','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840207','CCLASE','100','MODELO','1','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840207','CCLASE','101','MODELO','1','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840207','CCLASE','102','MODELO','1','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840207','CCLASE','103','MODELO','1','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840207','CCLASE','104','MODELO','1','1');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840207','CCLASE','105','MODELO','1','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840207','CCLASE','106','MODELO','1','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840207','CCLASE','2','MODELO','1','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840207','CCLASE','3','MODELO','1','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840207','CCLASE','4','MODELO','1','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840207','CCLASE','5','MODELO','1','0');

Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840295','CMODO','CONSULTA','CAREA','2','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840295','CMODO','GENERAL','CAREA','2','0');

Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840292','CTENEDOR','11','CORIGEN','1','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840292','CTENEDOR','12','CORIGEN','1','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840292','CTENEDOR','11','TCAUSA','1','0');
Insert into CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values ('24','99840292','CTENEDOR','12','TCAUSA','1','0');


COMMIT;
/