select pac_contexto.f_inicializarctx(pac_parametros.f_parempresa_t(24,'USER_BBDD')) FROM dual;
/
declare

begin
 
delete FROM  PROD_PLANT_CAB
where sproduc  in (80044, 80040, 80039, 80038, 80043, 80042, 80041, 8062, 8063)
AND CCODPLAN = 'CONF800102'
and ctipo = 0;

delete FROM  PROD_PLANT_CAB p
where p.sproduc in (80043, 80042, 80041)
AND CCODPLAN = 'CONF000003';

DELETE prod_plant_cab
WHERE ctipo = 0
AND ccodplan = 'CONF800110'
AND FDESDE = '25-SEP-2019';

--Clausulado ANI para RC cuando la actividad sea Estatal la respuesta sea 24

Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI)
values (80038,0,'SU-OD-51-01',1,F_SYSDATE,null,null,1,null,null,null,null,null,null,'AXIS_CONF',F_SYSDATE,null,null);

Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) 
values (80039,0,'SU-OD-51-01',1,F_SYSDATE,null,null,1,null,null,null,null,null,null,'AXIS_CONF',F_SYSDATE,null,null);

Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) 
values (80040,0,'SU-OD-51-01',1,F_SYSDATE,null,null,1,null,null,null,null,null,null,'AXIS_CONF',F_SYSDATE,null,null);

Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) 
values (80041,0,'SU-OD-51-01',1,F_SYSDATE,null,null,1,null,null,null,null,null,null,'AXIS_CONF',F_SYSDATE,null,null);

Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) 
values (80042,0,'SU-OD-51-01',1,F_SYSDATE,null,null,1,null,null,null,null,null,null,'AXIS_CONF',F_SYSDATE,null,null);

Insert into PROD_PLANT_CAB (SPRODUC,CTIPO,CCODPLAN,IMP_DEST,FDESDE,FHASTA,CGARANT,CDUPLICA,NORDEN,CLAVE,NRESPUE,TCOPIAS,CCATEGORIA,CDIFERIDO,CUSUALT,FALTA,CUSUMOD,FMODIFI) 
values (80043,0,'SU-OD-51-01',1,F_SYSDATE,null,null,1,null,null,null,null,null,null,'AXIS_CONF',F_SYSDATE,null,null);


DELETE FROM CODIPLANTILLAS
WHERE CCODPLAN = 'SU-OD-11-02';

DELETE FROM DETPLANTILLAS   
WHERE CCODPLAN = 'SU-OD-11-02';

Insert into DETPLANTILLAS (CCODPLAN,CIDIOMA,TDESCRIP,CINFORME,CPATH,CMAPEAD,CFIRMA,TCONFFIRMA) 
values ('SU-OD-11-03',1,'SU-OD-11-03 Anexo RC Profesional para Clinicas, Hospitales','SU-OD-11-03.pdf','.',null,0,null);

Insert into DETPLANTILLAS (CCODPLAN,CIDIOMA,TDESCRIP,CINFORME,CPATH,CMAPEAD,CFIRMA,TCONFFIRMA) 
values ('SU-OD-11-03',2,'SU-OD-11-03 Anexo RC Profesional para Clinicas, Hospitales','SU-OD-11-03.pdf','.',null,0,null);

Insert into DETPLANTILLAS (CCODPLAN,CIDIOMA,TDESCRIP,CINFORME,CPATH,CMAPEAD,CFIRMA,TCONFFIRMA) 
values ('SU-OD-11-03',8,'SU-OD-11-03 Anexo RC Profesional para Clinicas, Hospitales','SU-OD-11-03.pdf','.',null,0,null);

   
 commit;
 
end;


