 DELETE FROM AXIS_LITERALES  WHERE SLITERA = 9903367;
 DELETE FROM AXIS_LITERALES  WHERE SLITERA = 9909260;
 DELETE FROM AXIS_LITERALES WHERE SLITERA IN (9905563,9905565,9905564,9905576,9905566,9905577) AND cidioma = 8;
 DELETE FROM DETVALORES  WHERE CVALOR = 2001116;
 DELETE FROM DETVALORES WHERE CVALOR=8001120 AND CATRIBU = 4;
 
 
 INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES ('1', '9903367', 'Valor reclamat');
 INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES ('2', '9903367', 'Valor reclamado');
 INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES ('8', '9903367', 'Valor reclamado');
 
 INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES ('1', '9909260', 'Valor reclamat total');
 INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES ('2', '9909260', 'Valor reclamado total');
 INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES ('8', '9909260', 'Valor reclamado total');
 
  
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','8','1','CONTRALORIA DEPARTAMENTAL COLEGIADA');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','8','2','CONTRALORIA DEPARTAMENTAL');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','8','3','CONTRALORIA DELEGADA');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','8','4','CONTRALORIA DISTRITAL');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','8','5','CONTRALORIA GENERAL DE LA REPUBLICA');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','8','6','CONTRALORIA MUNICIPAL');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','8','7','OTRA');
  
  
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','2','1','CONTRALORIA DEPARTAMENTAL COLEGIADA');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','2','2','CONTRALORIA DEPARTAMENTAL');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','2','3','CONTRALORIA DELEGADA');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','2','4','CONTRALORIA DISTRITAL');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','2','5','CONTRALORIA GENERAL DE LA REPUBLICA');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','2','6','CONTRALORIA MUNICIPAL');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','2','7','OTRA');
  
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','1','1','CONTRALORIA DEPARTAMENTAL COLEGIADA');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','1','2','CONTRALORIA DEPARTAMENTAL');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','1','3','CONTRALORIA DELEGADA');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','1','4','CONTRALORIA DISTRITAL');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','1','5','CONTRALORIA GENERAL DE LA REPUBLICA');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','1','6','CONTRALORIA MUNICIPAL');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('2001116','1','7','OTRA');
  
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('8001120','8','4','REPOSICION/APELACION');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('8001120','1','4','REPOSICION/APELACION');
  INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES('8001120','2','4','REPOSICION/APELACION');
  
  insert into AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) values (8, 9905563, 'Letra predio');
  insert into AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) values (8, 9905564, 'Bis Letra');
  insert into AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) values (8, 9905565, 'Número de via generadora');
  insert into AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) values (8, 9905566, 'Letra via generadora');
  insert into AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) values (8, 9905576, 'Número de predio');
  insert into AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) values (8, 9905577, 'Bis letra vía generadora');
  
  
 COMMIT;