--Reporte Colocaciones Facultativas
DELETE FROM AXIS_LITERALES WHERE SLITERA = 89908025;

DELETE FROM AXIS_CODLITERALES WHERE SLITERA = 89908025;

INSERT INTO AXIS_CODLITERALES (SLITERA, CLITERA) VALUES (89908025,2);

INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (1, 89908025, 'Informe Colocaciones Facultatives');

INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (2, 89908025, 'Reporte Colocaciones Facultativas');

INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (8, 89908025, 'Reporte Colocaciones Facultativas'); 

COMMIT;