DELETE FROM PREGUNPRO WHERE cpregun = 6500 and sproduc = 8063;
DELETE FROM PREGUNPRO WHERE cpregun = 6563 and sproduc = 8063;

DELETE FROM PREGUNPRO WHERE cpregun = 6500 and sproduc = 8064;
DELETE FROM PREGUNPRO WHERE cpregun = 6563 and sproduc = 8064;

DELETE FROM PREGUNPRO WHERE cpregun = 6500 and sproduc = 8062;
DELETE FROM PREGUNPRO WHERE cpregun = 6563 and sproduc = 8062;


UPDATE CFG_WIZARD_FORMS SET CFORM_SIG = 'AXISCTR006' WHERE CIDCFG = 806301 AND CEMPRES = 24 AND CFORM_ACT = 'AXISCTR026' and CCAMPO_ACT = '*';

UPDATE CFG_WIZARD_FORMS SET CFORM_ANT = 'AXISCTR026' WHERE CIDCFG = 806301 AND CEMPRES = 24 AND CFORM_ACT = 'AXISCTR006' and CCAMPO_ACT = '*';

UPDATE CFG_WIZARD_FORMS SET CFORM_SIG = 'AXISCTR040' WHERE CIDCFG = 806301 AND CEMPRES = 24 AND CFORM_ACT = 'AXISCTR006' and CCAMPO_ACT = '*';

UPDATE CFG_WIZARD_FORMS SET CFORM_ANT = 'AXISCTR006' WHERE CIDCFG = 806301 AND CEMPRES = 24 AND CFORM_ACT = 'AXISCTR040' and CCAMPO_ACT = '*';

UPDATE CFG_WIZARD_FORMS SET CFORM_ANT = 'AXISCTR006' WHERE CIDCFG = 806301 AND CEMPRES = 24 AND CFORM_ACT = 'AXISCTR040' and CCAMPO_ACT = '*';

UPDATE CFG_WIZARD_FORMS SET CFORM_SIG = 'AXISCTR008' WHERE CIDCFG = 806301 AND CEMPRES = 24 AND CFORM_ACT = 'AXISCTR207' and CCAMPO_ACT = '*';

UPDATE CFG_WIZARD_FORMS SET CFORM_ANT = 'AXISCTR207' WHERE CIDCFG = 806301 AND CEMPRES = 24 AND CFORM_ACT = 'AXISCTR008' and CCAMPO_ACT = '*';

DELETE FROM CFG_AVISOS WHERE CFORM = 'AXISCTR004' AND SPRODUC = 8063 and CIDREL = 733708;

DELETE FROM CFG_AVISOS WHERE CFORM = 'AXISCTR207' AND SPRODUC = 8063 and CIDREL = 733706;

DELETE FROM PREGUNTAS WHERE CPREGUN = 9899;

DELETE FROM PREGUNPRO WHERE CPREGUN = 9899;

DELETE FROM CODIPREGUN WHERE CPREGUN = 9899;

Insert into CODIPREGUN (CPREGUN,CTIPPRE,CTIPPOR,CTIPGRU,TCONSULTA,TIMAGEN) values ('9899','5',null,'0',null,null);

Insert into PREGUNTAS (CPREGUN,CIDIOMA,TPREGUN) values ('9899','1','Vigencia de la póliza');
Insert into PREGUNTAS (CPREGUN,CIDIOMA,TPREGUN) values ('9899','2','Vigencia de la póliza');
Insert into PREGUNTAS (CPREGUN,CIDIOMA,TPREGUN) values ('9899','8','Vigencia de la póliza');

Insert into PREGUNPRO (CPREGUN,CMODALI,CCOLECT,CRAMO,CTIPSEG,SPRODUC,CPRETIP,NPREORD,TPREFOR,CPREOBL,NPREIMP,CRESDEF,COFERSN,CTABLA,TVALFOR,CMODO,CNIVEL,CTARPOL,CVISIBLE,ESCCERO,VISIBLECOL,VISIBLECERT,CRECARG,CCALCULAR,TMODALIDAD,CTIPCONV) values ('9899','1','0','802','3','8063','1','4',null,'0','4','1','0',null,null,'T','P','0','2','0','1','1','0',null,null,null);

UPDATE CFG_FORM_PROPERTY SET CVALUE = 0 WHERE CFORM = 'AXISCTR004' AND CIDCFG = 992222 AND CITEM = 'CFORPAG' AND CPRPTY = 2;

COMMIT;
/