DECLARE 
   V_EMPRESA             SEGUROS.CEMPRES%TYPE := 24;
   v_contexto            NUMBER; 

BEGIN

SELECT pac_contexto.f_inicializarctx(pac_parametros.f_parempresa_t(v_empresa, 'USER_BBDD')) INTO v_contexto FROM DUAL;

DELETE FROM PSUCONTROLSEG WHERE CCONTROL = 80247;
DELETE FROM PSU_CONTROLPRO WHERE CCONTROL = 80247 and sproduc = 8063 and cgarant = 0;
DELETE FROM PSU_DESCONTROL WHERE CCONTROL = 80247;
DELETE FROM PSU_DESRESULTADO WHERE CCONTROL = 80247 and sproduc = 8063;
DELETE FROM PSU_NIVEL_CONTROL WHERE CCONTROL = 80247 and sproduc = 8063;
DELETE FROM PSU_USUAGRU_NIVEL WHERE sproduc = 8063;
DELETE FROM PSU_CODCONTROL WHERE CCONTROL = 80247;


Insert into PSU_CODCONTROL (CCONTROL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('80247','AXIS_CONF',to_date('13/03/17','DD/MM/RR'),null,null);

Insert into PSU_CONTROLPRO (CCONTROL,SPRODUC,CTRATAR,CGARANT,PRODUCCI,RENOVACI,SUPLEMEN,COTIZACI,AUTMANUAL,ESTABLOQUEA,ORDENBLOQUEA,AUTORIPREV,CRETENPOR,CFORMULA,CUSUALT,FALTA,CUSUMOD,FMODIFI,CUSUBAJA,FBAJA,CCRITICO,PSUEXT,PSUAGE,TEVENTO,CCAMBIO) values ('80247','8063','3','0','1','1','1','1','A','E',null,'S','3','802290','AXIS',to_date('03/04/17','DD/MM/RR'),'AXIS',to_date('26/02/18','DD/MM/RR'),null,null,'1','0','0',null,null);

Insert into PSU_DESCONTROL (CCONTROL,CIDIOMA,TCONTROL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('80247','1','Vig¿ncia supera Nivell de Delegaci¿','AXIS_CONF',to_date('13/03/17','DD/MM/RR'),null,null);
Insert into PSU_DESCONTROL (CCONTROL,CIDIOMA,TCONTROL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('80247','2','Vigencia supera Nivel de Delegaci¿n','AXIS_CONF',to_date('13/03/17','DD/MM/RR'),null,null);
Insert into PSU_DESCONTROL (CCONTROL,CIDIOMA,TCONTROL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('80247','8','Vigencia supera Nivel de Delegaci¿n','AXIS_CONF',to_date('13/03/17','DD/MM/RR'),null,null);

Insert into PSU_DESRESULTADO (CCONTROL,SPRODUC,CNIVEL,CIDIOMA,TDESNIV,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('80247','8063','0','1','Correcte','AXIS',to_date('03/04/17','DD/MM/RR'),null,null);
Insert into PSU_DESRESULTADO (CCONTROL,SPRODUC,CNIVEL,CIDIOMA,TDESNIV,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('80247','8063','0','2','Correcto','AXIS',to_date('03/04/17','DD/MM/RR'),null,null);
Insert into PSU_DESRESULTADO (CCONTROL,SPRODUC,CNIVEL,CIDIOMA,TDESNIV,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('80247','8063','0','8','Correcto','AXIS',to_date('03/04/17','DD/MM/RR'),null,null);
Insert into PSU_DESRESULTADO (CCONTROL,SPRODUC,CNIVEL,CIDIOMA,TDESNIV,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('80247','8063','2900','1','Vig¿ncia supera Nivell Delegaci¿','AXIS',to_date('03/04/17','DD/MM/RR'),null,null);
Insert into PSU_DESRESULTADO (CCONTROL,SPRODUC,CNIVEL,CIDIOMA,TDESNIV,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('80247','8063','2900','2','Vigencia supera Nivel Delegaci¿n','AXIS',to_date('03/04/17','DD/MM/RR'),null,null);
Insert into PSU_DESRESULTADO (CCONTROL,SPRODUC,CNIVEL,CIDIOMA,TDESNIV,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('80247','8063','2900','8','Vigencia supera Nivel Delegaci¿n','AXIS',to_date('03/04/17','DD/MM/RR'),null,null);

Insert into PSU_NIVEL_CONTROL (CCONTROL,SPRODUC,NVALINF,NVALSUP,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('80247','8063','0','0','0','AXIS',to_date('03/04/17','DD/MM/RR'),null,null);
Insert into PSU_NIVEL_CONTROL (CCONTROL,SPRODUC,NVALINF,NVALSUP,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('80247','8063','1','1','2900','AXIS',to_date('03/04/17','DD/MM/RR'),null,null);

Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('1','8063','2880','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('11','8063','2900','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('13','8063','2890','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('16','8063','2790','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('17','8063','2780','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('18','8063','2830','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('19','8063','2820','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('20','8063','2810','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('21','8063','2800','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('22','8063','2770','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('23','8063','2690','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('24','8063','2680','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('25','8063','2840','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('26','8063','2760','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('27','8063','2670','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('28','8063','2850','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('29','8063','2750','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('30','8063','2740','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('31','8063','2730','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('32','8063','2660','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('33','8063','2610','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('34','8063','2650','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('35','8063','2720','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('36','8063','2640','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('37','8063','2630','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('38','8063','2710','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('39','8063','2620','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('40','8063','2700','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('42','8063','2910','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('43','8063','2910','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),'AXIS',to_date('05/02/18','DD/MM/RR'));
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('7','8063','2870','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);
Insert into PSU_USUAGRU_NIVEL (CUSUAGRU,SPRODUC,CNIVEL,CUSUALT,FALTA,CUSUMOD,FMODIFI) values ('8','8063','2860','AXIS_CONF',to_date('27/03/17','DD/MM/RR'),null,null);

commit;

END;
/

