delete from CON_HOMOLOGA_CONVI;
commit;
/


insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03500', 1, 0, 'INSERT INTO S03500:PARAM1
(CODIGO,SIGLA,NOMBRE,NIT,TIPPER,SUCREA,SUCMOD,FECREA,FECMOD,CLAIDE,CODCIA,SUCUR,FECNACIMIENTO,SEXO,CATTRIBUTARIA,DIGITO,PRIMERAPELLIDO,SEGUNDOAPELLIDO,PRIMERNOMBRE,SEGUNDONOMBRE,NOMBREPPAL,NOMBRECTARIO,CODIGOPPAL,CODIGOCTARIO)
(SELECT A.SPERSON,SUBSTR(PAC_CONVIVENCIA.F_GET_NOMBRE(:PSPERSON), 1, 20),SUBSTR(PAC_CONVIVENCIA.F_GET_NOMBRE(:PSPERSON), 1, 250),A.NNUMIDE,
 PAC_CONVIVENCIA.F_CONVIVENCIA_OSIRIS(A.SPERSON, 1), A.CUSUALT,A.CUSUARI,A.FALTA,A.FMOVIMI,'''','''','''', A.FNACIMI,CASE WHEN A.CTIPPER = 1 THEN DECODE(A.CSEXPER, 1, 2, 2, 1, 0) ELSE NULL END,
 1,A.TDIGITOIDE,B.TAPELLI1,B.TAPELLI2,B.TNOMBRE1,B.TNOMBRE2,'''','''','''','''' FROM PER_PERSONAS A, PER_DETPER B WHERE A.SPERSON = B.SPERSON AND A.SPERSON = :PSPERSON)', null, 1, null, 'S03500', null);

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03500', 1, 1, null, 'UPDATE S03500:PARAM1 U
   SET U.SUCMOD          = '':PSUCMOD'',
       U.FECMOD          = '':PFECMOD'',
       U.SIGLA           = '':PSIGLA'',
       U.NOMBRE          = '':PNOMBRE'',
       U.PRIMERAPELLIDO  = '':PPRIMERAPELLIDO'',
       U.SEGUNDOAPELLIDO = '':PSEGUNDOAPELLIDO'',
       U.PRIMERNOMBRE    = '':PPRIMERNOMBRE'',
       U.SEGUNDONOMBRE   = '':PSEGUNDONOMBRE''
 WHERE U.CODIGO = '':PSPERSON''', 1, null, 'S03500', null);

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03500', 2, 0, 'INSERT INTO S03500:PARAM1
(CODIGO,SIGLA,NOMBRE,NIT,TIPPER,SUCREA,SUCMOD,FECREA,FECMOD,CLAIDE,CODCIA,SUCUR,FECNACIMIENTO,SEXO,CATTRIBUTARIA,DIGITO,PRIMERAPELLIDO,SEGUNDOAPELLIDO,PRIMERNOMBRE,SEGUNDONOMBRE,NOMBREPPAL,NOMBRECTARIO,CODIGOPPAL,CODIGOCTARIO)
(SELECT A.SPERSON,SUBSTR(B.TAPELLI1, 1, 20),SUBSTR(B.TAPELLI1, 1, 250),DECODE(A.CTIPIDE,37,SUBSTR(A.NNUMIDE, 1, LENGTH(A.NNUMIDE) - 1),A.NNUMIDE),
 PAC_CONVIVENCIA.F_CONVIVENCIA_OSIRIS(A.SPERSON, 1), A.CUSUALT,A.CUSUARI,A.FALTA,A.FMOVIMI,'''','''','''', A.FNACIMI,CASE WHEN A.CTIPPER = 1 THEN DECODE(A.CSEXPER, 1, 2, 2, 1, 0) ELSE 0 END,
 1,A.TDIGITOIDE,null,null,null,null,'''','''','''','''' FROM PER_PERSONAS A, PER_DETPER B WHERE A.SPERSON = B.SPERSON AND A.SPERSON = :PSPERSON)', null, 1, null, 'S03500', null);

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03500', 2, 1, null, 'UPDATE S03500:PARAM1 U
   SET U.SIGLA           = '':PSIGLA'',
       U.NOMBRE          = '':PNOMBRE'',
       U.SUCMOD          = '':PSUCMOD'',
       U.FECMOD          = '':PFECMOD''
 WHERE U.CODIGO = '':PSPERSON''', 1, null, 'S03500', null);

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03501', 0, 0, 'INSERT INTO S03501B:PARAM_DB (CODIGO, CODVIN, ESTADO, FECESTADO, SUCREA) VALUES ('':PARAM_CODIGO'', :PARAM_VINCULO, :PARAM_ESTADO, F_SYSDATE, F_USER)', null, 1, null, 'V_INS_S03501B', null);

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03501', 0, 0, 'INSERT INTO S03501:PARAM1
  (CODIGO, CODVIN, ESTADO, FECESTADO, SUCREA)
  (SELECT '':OSI_CODIGO'', :PCODVIN, :PESTADO, F_SYSDATE, F_USER
     FROM PER_PERSONAS A
    WHERE A.SPERSON = :PSPERSON)', null, 1, null, 'V_INS_S03501', null);

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03501', 0, 1, null, 'UPDATE S03501:PARAM_DB S SET S.ESTADO = 0, S.FECESTADO = F_SYSDATE, S.SUCREA = F_USER WHERE S.CODIGO = '':PARAM_CODIGO'' AND S.CODVIN = :PARAM_VINCULO AND S.ESTADO = :PARAM_ESTADO', null, null, 'V_UPD_S03501_E_NOT_0', null);

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03501', 0, 2, null, null, 1, 'SELECT COUNT(*) FROM S03501:PARAM_DB S WHERE S.CODIGO = '':PARAM_CODIGO'' AND S.CODVIN = :PARAM_VINCULO AND S.ESTADO = :PARAM_ESTADO', 'V_SEL_S03501', null);

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03501', 0, 1, null, 'UPDATE S03501:PARAM_DB S SET S.ESTADO = :PARAM_ESTADO, S.FECESTADO = F_SYSDATE, S.SUCREA = F_USER WHERE S.CODIGO = '':PARAM_CODIGO'' AND S.CODVIN = :PARAM_VINCULO AND S.ESTADO = 0', 1, null, 'V_UPD_S03501_E_0', null);

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03501', 0, 3, null, 'DELETE FROM S03501:PARAM_DB S WHERE S.CODIGO = '':PARAM_CODIGO'' AND S.CODVIN = :PARAM_VINCULO AND S.ESTADO = :PARAM_ESTADO AND ROWNUM = 1', 1, null, 'V_DEL_S03501', null);

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 17, 'SELECT CBANCAR FROM PER_CCC WHERE SPERSON = :PSPERSON AND CNORDBAN = 1', '00000120', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 15, 'SELECT TO_NUMBER(SUBSTR(CSUCURSAL, 4)) FROM DATSARLATF WHERE SPERSON = :PSPERSON AND SSARLAFT=(SELECT MAX(SSARLAFT) FROM DATSARLATF WHERE SPERSON = :PSPERSON)', '00000080', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 31, 'SELECT DECODE(CMANRECPUB, 1, ''NO'', 0, ''SI'') FROM DATSARLATF WHERE SPERSON = :PSPERSON AND SSARLAFT=(SELECT MAX(SSARLAFT) FROM DATSARLATF WHERE SPERSON = :PSPERSON)', '00002421', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 16, 'SELECT TCIUDADSUC FROM DATSARLATF WHERE SPERSON = :PSPERSON AND SSARLAFT=(SELECT MAX(SSARLAFT) FROM DATSARLATF WHERE SPERSON = :PSPERSON)', '00000090', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 13, 'SELECT DECODE(CAUTTRADAT,1,''01'',2,''02'',3,''03'') FROM DATSARLATF WHERE SPERSON = :PSPERSON AND SSARLAFT=(SELECT MAX(SSARLAFT) FROM DATSARLATF WHERE SPERSON = :PSPERSON)', '00000051', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 2, 0, null, null, 22, 'SELECT MAX(FCUPO) FROM FIN_INDICADORES WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON) AND FINDICAD = (SELECT MAX(FINDICAD) FROM FIN_INDICADORES WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON))', '00002068', 'DATE');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 18, 'SELECT DECODE(CTIPCC, ''3'', ''02'', NULL, NULL, ''01'' ) FROM TIPOS_CUENTA WHERE CTIPBAN = (SELECT CTIPBAN FROM PER_CCC WHERE SPERSON = :PSPERSON AND CNORDBAN = 1)', '00000121', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 21, 'SELECT TCUPOR FROM FIN_INDICADORES WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON) AND FINDICAD = (SELECT MAX(FINDICAD) FROM FIN_INDICADORES WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON))', '00002064', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 2, 0, null, null, 23, 'SELECT MAX(ICUPOG) FROM FIN_INDICADORES WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON) AND FINDICAD = (SELECT MAX(FINDICAD) FROM FIN_INDICADORES WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON))', '00002090', 'NUMBER');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 30, 'SELECT DECODE(CVINPERPUB, 1, ''NO'', 0, ''SI'') FROM DATSARLATF WHERE SPERSON = :PSPERSON AND SSARLAFT=(SELECT MAX(SSARLAFT) FROM DATSARLATF WHERE SPERSON = :PSPERSON)', '00002420', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 26, 'SELECT TVIGENC FROM FIN_GENERAL WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON) AND SPERSON = :PSPERSON', '00002354', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 2, 0, null, null, 24, 'SELECT MAX(ICUPOS) FROM FIN_INDICADORES WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON) AND FINDICAD = (SELECT MAX(FINDICAD) FROM FIN_INDICADORES WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON))', '00002092', 'NUMBER');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 27, 'SELECT SPERSON_DEUD FROM PER_PERSONAS WHERE SPERSON = :PSPERSON', '00002378', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 28, 'SELECT SPERSON_ACRE FROM PER_PERSONAS WHERE SPERSON = :PSPERSON', '00002379', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 25, 'SELECT DECODE(NVALPAR, 1, ''NO'',2,''SI'', NULL) FROM PER_PARPERSONAS WHERE CPARAM = ''PER_APLICA_Q3'' AND SPERSON = :PSPERSON', '00002349', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 34, 'SELECT CPOBLAC FROM FIN_GENERAL WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON) AND SPERSON = :PSPERSON', '10101046', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 32, 'SELECT DECODE(CRECPUB, 1, ''NO'', 0, ''SI'') FROM DATSARLATF WHERE SPERSON = :PSPERSON AND SSARLAFT=(SELECT MAX(SSARLAFT) FROM DATSARLATF WHERE SPERSON = :PSPERSON)', '00002422', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 29, 'SELECT DECODE(CSUJETOOBLIFACION, 1, ''01'', 0, ''02'') FROM DATSARLATF WHERE SPERSON = :PSPERSON AND SSARLAFT=(SELECT MAX(SSARLAFT) FROM DATSARLATF WHERE SPERSON = :PSPERSON)', '00002403', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 33, 'SELECT TRIM(TO_CHAR(CTIPSOCI,''00'')) CTIPSOCI FROM FIN_GENERAL WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON) AND SPERSON = :PSPERSON', '02152', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 5, 'SELECT TVALCON FROM PER_CONTACTOS WHERE CTIPCON = 3 AND CMODCON = (SELECT MAX(CMODCON) FROM PER_CONTACTOS WHERE CTIPCON = 3 AND SPERSON = :PSPERSON) AND SPERSON = :PSPERSON', '00000020', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 1, 'SELECT REPLACE(TDOMICI,'''''''') FROM PER_DIRECCIONES WHERE SPERSON = :PSPERSON AND CDOMICI = 1', '00000010', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 1, 0, null, null, 38, 'SELECT MAX(FCONSULTA) FROM FIN_ENDEUDAMIENTO WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON) AND FCONSULTA = (SELECT MAX(FCONSULTA) FROM FIN_ENDEUDAMIENTO WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON))', '00002068', 'DATE');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 3, 'SELECT REPLACE(TDOMICI,'''''''') FROM PER_DIRECCIONES WHERE SPERSON = :PSPERSON AND CDOMICI = 2', '00000011', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 2, 'SELECT CPAIS FROM PER_DETPER WHERE SPERSON = :PSPERSON', '00000013', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 10, 'SELECT TVALCON FROM PER_CONTACTOS WHERE CTIPCON = 1 AND CDOMICI = 1 AND CMODCON = (SELECT MAX(CMODCON) FROM PER_CONTACTOS WHERE CTIPCON = 1 AND CDOMICI = 1 AND SPERSON = :PSPERSON) AND SPERSON = :PSPERSON', '00000043', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 11, 'SELECT TVALCON FROM PER_CONTACTOS WHERE CTIPCON =2 AND CDOMICI = 1 AND CMODCON = (SELECT MAX(CMODCON) FROM PER_CONTACTOS WHERE CTIPCON = 2 AND CDOMICI = 1 AND SPERSON = :PSPERSON) AND SPERSON = :PSPERSON', '00000050', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 12, 'SELECT CASE WHEN LENGTH(CCIIU) > 4 THEN TO_CHAR(CCIIU) ELSE TRIM(TO_CHAR(CCIIU, ''0000'')) END CCIIU FROM FIN_GENERAL WHERE SPERSON = :PSPERSON AND SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON)', '00000055', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 4, 'SELECT PAC_ISQLFOR.F_POBLACION(SPERSON, 1) FROM PER_DIRECCIONES WHERE SPERSON = :PSPERSON AND CDOMICI = 1', '00000012', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 36, 'SELECT lpad(CPROVIN,2,''0'') FROM PER_DIRECCIONES WHERE SPERSON = :PSPERSON AND CDOMICI = 1', '00000111', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 37, 'SELECT lpad(CPROVIN,2,''0'')||lpad(CPOBLAC,3,''0'') FROM PER_DIRECCIONES WHERE SPERSON = :PSPERSON AND CDOMICI = 1', '00000095', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 8, 'SELECT TVALCON FROM PER_CONTACTOS WHERE CTIPCON = 1 AND CDOMICI = 2 AND CMODCON = (SELECT MAX(CMODCON) FROM PER_CONTACTOS WHERE CTIPCON = 1 AND CDOMICI = 2 AND SPERSON = :PSPERSON) AND SPERSON = :PSPERSON', '00000041', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 19, 'SELECT DECODE(NVALPAR, 1, ''01'', 2, ''02'') FROM PER_PARPERSONAS WHERE CPARAM = ''EXEN_CIRCULAR'' AND SPERSON = :PSPERSON', '00002061', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 20, 'SELECT DECODE(NVALPAR, 1, ''01'',2,''02'', NULL) FROM PER_PARPERSONAS WHERE CPARAM = ''PER_EXCENTO_CONTGAR'' AND SPERSON = :PSPERSON', '00002063', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 9, 'SELECT TVALCON FROM PER_CONTACTOS WHERE CTIPCON = 1 AND CDOMICI = 3 AND CMODCON = (SELECT MAX(CMODCON) FROM PER_CONTACTOS WHERE CTIPCON = 1 AND CDOMICI = 3 AND SPERSON = :PSPERSON) AND SPERSON = :PSPERSON', '00000042', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 1, 0, null, null, 39, 'SELECT MAX(ICUPOG) FROM FIN_ENDEUDAMIENTO WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON) AND FCONSULTA = (SELECT MAX(FCONSULTA) FROM FIN_ENDEUDAMIENTO WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON))', '00002090', 'NUMBER');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 1, 0, null, null, 40, 'SELECT MAX(ICUPOS) FROM FIN_ENDEUDAMIENTO WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON) AND FCONSULTA = (SELECT MAX(FCONSULTA) FROM FIN_ENDEUDAMIENTO WHERE SFINANCI = (SELECT MAX(SFINANCI) FROM FIN_GENERAL WHERE SPERSON = :PSPERSON))', '00002092', 'NUMBER');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 6, 'SELECT TVALCON FROM PER_CONTACTOS WHERE CTIPCON = 6 AND CDOMICI = 1 AND CMODCON = (SELECT MAX(CMODCON) FROM PER_CONTACTOS WHERE CTIPCON = 6 AND CDOMICI = 1 AND SPERSON = :PSPERSON) AND SPERSON = :PSPERSON', '00000030', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03502', 0, 0, null, null, 7, 'SELECT TVALCON FROM PER_CONTACTOS WHERE CTIPCON = 1 AND CDOMICI = 1 AND CMODCON = (SELECT MAX(CMODCON) FROM PER_CONTACTOS WHERE CTIPCON = 1 AND CDOMICI = 1 AND SPERSON = :PSPERSON) AND SPERSON = :PSPERSON', '00000040', 'VARCHAR');

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03512', 0, 1, null, 'UPDATE S03512:PARAM1 S512
   SET S512.FECHADOCUMENTO = '':FDILIGENCIA'',
       S512.FECHARADICADA  = '':FRADICA''
 WHERE S512.NUMRADICACION = '':PSSARLAFT''
   AND S512.PERSONA = '':PSPERSON''', 1, null, 'S03512', null);

insert into CON_HOMOLOGA_CONVI (TOSIRIS, TIPPERSONA, FLAG, INSERT_QUERY, UPDATE_QUERY, NORDEN, SELECT_QUERY, OSIRIS_CODIGO, TIPVALOR_OSI)
values ('S03512', 0, 0, 'INSERT INTO S03512:PARAM1
(PERSONA,TIPODOCUMENTO,FECHADOCUMENTO,SUCUR,CODIGOENTIDADEMISORA,DESCRIPCION,FECHARADICADA,FECHAVENCIMIENTO,NUMRADICACION,COMENTARIOS,CALIFICACION,USUARIOCUSTODIA,UBICACIONSTD,CAUSADEVUELTA,SUCREA,SUCMOD,   FECREA,FECMOD)
(SELECT SPERSON,5,FDILIGENCIA,SUBSTR(CSUCURSAL, 3),NULL,NULL,FRADICA,NULL,TO_CHAR(SSARLAFT),NULL,NULL,NULL,NULL,0,CUSER,
CUSER,FALTA,FALTA FROM DATSARLATF WHERE SPERSON = :PSPERSON)', null, 1, null, 'S03512', null);

commit;
/
