  CREATE  TABLE "PER_PAGADOR_ALT" 
   ("SPERSON" NUMBER(10,0) NOT NULL ENABLE,
	"SPERSON_REL" NUMBER(10,0) NOT NULL ENABLE, 
	"CTIPPAGALT" NUMBER(2,0) NOT NULL ENABLE,
    "CESTADO" NUMBER(2,0) NOT NULL ENABLE,
	"CUSUALT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FUSUALT" DATE NOT NULL ENABLE, 
	"CUSUBAJ" VARCHAR2(20 BYTE), 
	"FUSUBAJ" DATE, 
  CONSTRAINT "PER_PAGADOR_ALT_PK" PRIMARY KEY ("SPERSON","SPERSON_REL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ) ;

   COMMENT ON COLUMN "PER_PAGADOR_ALT"."SPERSON" IS 'Secuencia unica de identificacion de una persona';
   COMMENT ON COLUMN "PER_PAGADOR_ALT"."SPERSON_REL" IS 'Código de persona de la persona relacionada';
   COMMENT ON COLUMN "PER_PAGADOR_ALT"."CTIPPAGALT" IS 'Tipo de pagador alternativo (V.F. 8002010)';
   COMMENT ON COLUMN "PER_PAGADOR_ALT"."CESTADO" IS 'Código de estado 0 INACTIVO 1 ACTIVO';
   COMMENT ON COLUMN "PER_PAGADOR_ALT"."CUSUALT" IS 'Código usuario Alta del registro';
   COMMENT ON COLUMN "PER_PAGADOR_ALT"."FUSUALT" IS 'Fecha Alta del registro';
   COMMENT ON COLUMN "PER_PAGADOR_ALT"."CUSUBAJ" IS 'Código usuario Baja del registro';
   COMMENT ON COLUMN "PER_PAGADOR_ALT"."FUSUALT" IS 'Fecha Baja del registro';
   COMMENT ON TABLE "PER_PAGADOR_ALT"  IS 'Tabla de pagador Alternativo';

  CREATE INDEX "PER_PAGADOR_ALT_PERS_FK2" ON "PER_PAGADOR_ALT" ("SPERSON_REL") ;
/
CREATE OR REPLACE SYNONYM axis00.per_pagador_alt FOR per_pagador_alt;
GRANT SELECT, INSERT, UPDATE, DELETE ON per_pagador_alt TO r_axis;