GRANT EXECUTE ON AXIS.OB_IAX_IMPUESTOS TO AXIS00;
GRANT EXECUTE ON AXIS.T_IAX_ IMPUESTOS TO AXIS00;
create synonym AXIS00.OB_IAX_IMPUESTOS  for AXIS.OB_IAX_IMPUESTOS;
create synonym AXIS00.T_IAX_IMPUESTOS for AXIS.T_IAX_IMPUESTOS;

ALTER TYPE OB_IAX_PERSONAS ADD ATTRIBUTE (impuestos T_IAX_IMPUESTOS) CASCADE;  
