
alter table cuentassap add DESCRIP VARCHAR2(2000); -- Existing

delete from CUENTASSAP;

alter table cuentassap drop column tipo_importe;

alter table cuentassap add tipo_importe VARCHAR2(200);
alter table cuentassap add aplicable_indica VARCHAR2(2);
alter table cuentassap add ctipind NUMBER;
commit;

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (1630400100, 1, 16, 'IVA DESC DIR. SOBRE COMISIONES (DB)', '4', 'SI', 69);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (1684050100, 2, 1, 'PRIMAS NETAS POR RECAUDAR NEGOCIOS DIRECTOS', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (1684050200, 3, 3, 'PRIMAS NETAS IVA POR RECAUDAR', '4', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (1684050300, 4, 4, 'GASTOS DE EMISION DE PRIMAS POR RECAUDAR', '8', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (1684100100, 5, 7, 'PRIMAS POR RECAUDAR COASEGURO ACEPTADO', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (1684150100, 6, 9, 'PRIMA NETA PARTE COASEGURO CEDIDO', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (1684200100, 7, null, 'PRIMA NETA A RECAUDAR CANCELACION PRIMA', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (1684200200, 8, null, 'PRIMA NETA A RECAUDAR CANCELACION IVA', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (1684200300, 9, null, 'PRIMA NETA POR RECAUDAR CANCELACION GASTOS DE EXPE', '8', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (1925150100, 10, 14, 'GTOS PAG X ANT COMISIONES A INTERMEDIARIOS', '11', 'SI', 69);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (2503400100, 11, 1137, 'SOBRE PRIMAS EMITIDAS', '4', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (2590700100, 12, 10, 'PRIMAS POR RECAUDAR COASEGURO CEDIDO', '0', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (2820050200, 13, 15, 'PROVISIONES, OBLIGACIONES A FAVOR INTERMEDIARIOS S', '11|4', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (2907950200, 14, 1041, 'PRIMAS DE VIG FUTURAS-PRODUCCIÓN', '0|8', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (2907950300, 15, 1042, 'AMORTIZACIÓN VIG FUTURAS-PRODUCCIÓN', '0|8', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (2907950400, 16, 1210, 'PRIMAS COASEGURO ACEPTADO VIG FUTURAS-PRODUCCIÓN', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (2907950500, 17, 1211, 'AMORTIZACIÓN COASEGURO ACEPTADO VIG FUTURAS-PRODUC', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121050101, 21, 2, 'PRIMAS EMITIDAS CUMPLIMIENTO', '0', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121050102, 22, 3, 'PRIMAS EMITIDAS CUMPLIMIENTO-JUDICIALES', '0', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121050103, 23, 1165, 'VF PRIMAS EMITIDAS CUMPLIMIENTO', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121050104, 24, 1166, 'VF PRIMAS EMITIDAS CUMPLIMIENTO-JUDICIALES', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121050200, 25, 30, 'PRIMAS EMITIDAS RESPONSABILIDAD CIVIL', '0', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121050201, 26, 1167, 'VF PRIMAS EMITIDAS RESPONSABILIDAD CIVIL', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121050300, 27, 40, 'PRIMAS EMITIDAS TODO RIESGO CONTRUCCION', '0', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121050301, 28, 1168, 'VF PRIMAS EMITIDAS TODO RIESGO CONTRUCCION', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121050700, 29, 1110, 'PRIMAS EMITIDAS INCENDIO', '0', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121050800, 30, 1111, 'PRIMAS EMITIDAS TERREMOTO', '0', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121050900, 31, 1112, 'PRIMAS EMITIDAS SUSTRACCION', '0', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121051100, 32, 1113, 'PRIMAS EMITIDAS CORRIENTE DEBIL', '0', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121051400, 33, 1114, 'PRIMAS EMITIDAS LUCRO CESANTE', '0', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121051500, 34, 1115, 'MONTAJE Y ROTURA DE MAQUINARIA', '0', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121400101, 35, 8, 'COASEGURO ACEPTADO CUMPLIMIENTO', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121400102, 36, 221, 'CUMPLIMIENTO-JUDICIALES', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121400103, 18, 1212, 'VF COASEGURO ACEPTADO CUMPLIMIENTO', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121400205, 19, null, 'VF COASEGURO ACEPTADO RESPONSABILIDAD CIVIL', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121400301, 20, null, 'VF COASEGURO ACEPTADO TODO RIESGO', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121400200, 37, 32, 'COASEGURO ACEPTADO RESPON', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121400300, 38, 42, 'COASEGURO ACEPTADO TODO R', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121400700, 39, 1116, 'INCENDIO', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121400800, 40, 1117, 'TERREMOTO', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121400900, 41, 1118, 'SUSTRACCION', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121401100, 42, 1119, 'CORRIENTE DEBIL', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121401400, 43, 1120, 'LUCRO CESANTE', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121401500, 44, 1121, 'MONTAJE Y ROTURA DE MAQUI', '0', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4121550101, 45, null, 'CANCELACIONES Y/O ANULACI', '0', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4195950100, 46, 5, 'GASTOS DE EXPEDICION', '8', 'SI', 369);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (4195950190, 47, 1122, 'VF GASTOS DE EXPEDICION', '8', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152100100, 48, 13, 'REMUNERACION A FAVOR DE I', '11', 'SI', 69);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152100200, 49, 34, 'REMUNERACION A FAVOR DE I', '11', 'SI', 69);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152100300, 50, 44, 'REMUNERACION A FAVOR DE I', '11', 'SI', 69);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152100700, 51, 1123, 'INCENDIO', '11', 'SI', 69);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152100800, 52, 1124, 'TERREMOTO', '11', 'SI', 69);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152100900, 53, 1125, 'SUSTRACCION', '11', 'SI', 69);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152101100, 54, 1126, 'CORRIENTE DEBIL', '11', 'SI', 69);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152101400, 55, 1127, 'LUCRO CESANTE', '11', 'SI', 69);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152101500, 56, 1128, 'MONTAJE Y ROTURA DE MAQUI', '11', 'SI', 69);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152250100, 57, 231, 'DE COASEGURO ACEPTADO CUM', '11', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152250200, 58, 1129, 'DE COASEGURO ACEPTADO RES', '11', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152250300, 59, 1130, 'DE COASEGURO ACEPTADO TOD', '11', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152250700, 60, 1131, 'INCENDIO', '11', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152250800, 61, 1132, 'TERREMOTO', '11', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152250900, 62, 1133, 'SUSTRACCION', '11', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152251100, 63, 1134, 'CORRIENTE DEBIL', '11', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152251400, 64, 1135, 'LUCRO CESANTE', '11', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (5152251500, 65, 1136, 'MONTAJE Y ROTURA DE MAQUI', '11', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (8195950100, 66, 1012, 'COMISIONES COASEGURO CEDIDO', '11', 'NO', null);

insert into CUENTASSAP (CCUENTA, CODCUENTA, LINEA, DESCRIP, TIPO_IMPORTE, APLICABLE_INDICA, CTIPIND)
values (8305050100, 67, 1111, 'DEUDORA POR CONTA (CR)', '11', 'NO', null);

commit;