              
DELETE FROM CFG_LANZAR_INFORMES_PARAMS C
 WHERE C.CMAP = 'reporteFichaInterm'
   AND C.TPARAM = 'PCSUCURSAL';
   
UPDATE CFG_LANZAR_INFORMES_PARAMS C
  SET C.NORDER = 5
WHERE C.CMAP = 'reporteFichaInterm'
  AND C.TPARAM = 'P_NIT';
COMMIT;  
  

DELETE FROM CFG_LANZAR_INFORMES_PARAMS C
 WHERE C.CMAP = 'reporteFichaIntermpre'
   AND C.TPARAM = 'P_AGENTE';
DELETE FROM CFG_LANZAR_INFORMES_PARAMS C
 WHERE C.CMAP = 'reporteFichaIntermpre'
   AND C.TPARAM = 'PCSUCURSAL';   
COMMIT;

INSERT INTO CFG_LANZAR_INFORMES_PARAMS (CEMPRES, CFORM, CMAP, TEVENTO, SPRODUC, CCFGFORM, TPARAM, NORDER, SLITERA, CTIPO, NOTNULL, LVALOR)
VALUES (24, 'AXISLIST003', 'reporteFichaIntermpre', 'GENERAL', 0, 'GENERAL', 'AGENTE', 3, 100584, 4, 0, NULL);

INSERT INTO CFG_LANZAR_INFORMES_PARAMS (CEMPRES, CFORM, CMAP, TEVENTO, SPRODUC, CCFGFORM, TPARAM, NORDER, SLITERA, CTIPO, NOTNULL, LVALOR)
VALUES (24, 'AXISLIST003', 'reporteFichaIntermpre', 'GENERAL', 0, 'GENERAL', 'P_AGENTE', 4, 100584, 2, 0, NULL);

INSERT INTO CFG_LANZAR_INFORMES_PARAMS (CEMPRES, CFORM, CMAP, TEVENTO, SPRODUC, CCFGFORM, TPARAM, NORDER, SLITERA, CTIPO, NOTNULL, LVALOR)
VALUES (24, 'AXISLIST003', 'reporteFichaIntermpre', 'GENERAL', 0, 'GENERAL', 'P_NIT', 5, 9910198, 2, 0, NULL);
COMMIT;

UPDATE CFG_LANZAR_INFORMES_PARAMS C
  SET C.NOTNULL = 1
WHERE C.CMAP = 'reporteFichaIntermpre'
  AND C.TPARAM = 'F_FINICIO';
  
UPDATE CFG_LANZAR_INFORMES_PARAMS C
  SET C.NOTNULL = 1
WHERE C.CMAP = 'reporteFichaIntermpre'
  AND C.TPARAM = 'F_FINAL';
COMMIT;