DECLARE
BEGIN

--Codigo
INSERT INTO CODICLAUSUGEN ( SCLAGEN) 
VALUES ( (select max(sclagen)+1 from CODICLAUSUGEN) );

--Clausula
INSERT INTO CLAUSUGEN ( CIDIOMA, SCLAGEN, TCLATEX, TCLATIT) 
VALUES ( 8,
 (select max(sclagen) from CODICLAUSUGEN),
 '"EXCLUSIONES PARTICULARES:
RESPONSABILIDAD CIVIL CONTRACTUAL
RESPONSABILIDAD CIVIL ARRENDATARIO
DAÑOS A LOS BIENES/PRODUCTOS/MERCANC�?AS TRANSPORTADAS AS�? COMO TAMBIÉN A LOS MEDIOS DE TRANSPORTE; TODO TIPO DE COBERTURA ASEGURABLE BAJO EL RAMO DE TRANSPORTES/MARINE
RC DERIVADA DEL TRANSPORTE DE Y/O DEL MANEJO DE MERCANC�?A PELIGROSA INFLAMABLE Y/O TÓXICA.
RESPONSABILIDAD CIVIL CONTRATISTAS Y/O SUB-CONTRATISTAS DEL ASEGURADO
RECLAMACIONES PROVENIENTES DEL EXTERIOR
PÉRDIDAS CONSECUENCIALES QUE NO PROVENGAN DE UN DAÑO MATERIAL O LESIÓN CORPORAL.
RECLAMACIONES DERIVADAS DEL INCUMPLIMIENTO TOTAL O PARCIAL O POR MORA DE LA OBLIGACIÓN PRINCIPAL DE CONVENIOS Y CONTRATOS
BIENES BAJO CUSTODIA, TENENCIA Y CONTROL DAÑOS A LA OBRA TRABAJADA Y/O A LAS HERRAMIENTAS Y/O A LA MAQUINARIA USADA
HUNDIMIENTO DE TERRENO, DERRUMBES Y/O DESLIZAMIENTO DE TIERRA, ASENTAMIENTO, VIBRACIONES Y/O INUNDACIONES
(CAUSADAS POR ACTIVIDADES DEL ASEGURADO)
DAÑOS MATERIALES Y CONSECUENCIALES TANTO A LAS OBRAS CIVILES, COMO A LA INSTALACIÓN MEC�?NICA Y TODO LO RELACIONADO CON OBRAS DE CONSTRUCCIÓN Y/O MONTAJE.
CONTAMINACIÓN GRADUAL/PAULATINA
DAÑOS AL MEDIO AMBIENTE O AL ECOSISTEMA. DESCONTAMINACIÓN DE SUELOS DAÑOS A SIEMBRAS, BOSQUES Y/O CUALQUIER CLASE DE CULTIVO; PÉRDIDA Y ESCAPE DE GANADO, TODO ASEGURABLE BAJO EL RAMO DE SEGURO AGROPECUARIO
GASTOS QUE DEMANDE LA LIMPIEZA Y/O REMEDIACIÓN DE LAS �?REAS AFECTADAS POR CONTAMINACIÓN SÚBITA Y ACCIDENTAL, LOS GASTOS PARA EVITAR O DISMINUIR EL AGRAVAMIENTO DE LOS DAÑOS; Y, OTROS GASTOS RELACIONADOS CON ESTOS EVENTOS
DAÑOS Y PERJUICIOS DE CUALQUIER TIPO A POZOS PETROLEROS, TANQUES PETROLEROS Y SUS PÉRDIDAS CONSECUENCIALES, BLOW OUT, CRATERIZACIÓN Y PÉRDIDA DE CONTROL, DAÑOS DE CUALQUIER TIPO AL PETRÓLEO, CRUDO O CUALQUIER OTRO DERIVADO DEL PETRÓLEO.
RIESGOS OFF-SHORE.
DAÑOS COMO CONSECUENCIA DE INCUMPLIMIENTO DE LOS REQUISITOS LEGALES ADMINISTRATIVOS Y/O VIOLACIÓN DE MEDIDAS DE SEGURIDAD IMPUESTA POR LAS AUTORIDADES QUE RIGEN ESTA ACTIVIDAD.
RC PRODUCTOS
R.C. PROFESIONAL DE TODO TIPO
ASBESTOS, PLOMO, TABACO Y PRODUCTOS DEL TABACO, LATEX, MOHO Y/O TOXIC MOLD 
UREA DE FORMALDEHIDE, PCBS, PCNB’S, HIDROCARBUROS Y HIDROGENOS CLORINADOS, CLORO FLUORO CARBONOS, ORGANOCLORADOS, ASKARELES, IOXINAS, CIANURO, DIMETIL, TEREFTALATOS, ISOCIANATOS, AMIANTO, PHEN-FEN, MTE (METIL TERBUTIL ÉTER) DEPOSITOS, RESIDUOS HOSPITALARIOS, VERTEDEROS.
GUERRA Y GUERRA CIVIL, MOT�?N, HUELGA, ALBORROTO POPULAR, LOCK-OUT, PARO, CONMOCIÓN CIVIL, ACTOS DE TERRORISMO,
CONFISCACIÓN, SABOTAJE.
CULPA GRAVE DE LA V�?CTIMA, CULPA GRAVE, DOLO Y ACTOS MALINTENCIONADOS
DAÑOS PREVISIBLES O CAUSADOS POR CASO FORTUITO O FUERZA MAYOR
- LA COBERTURA DE LA PÓLIZA EST�? LIMITADA ÚNICA Y EXCLUSIVAMENTE A LOS DAÑOS QUE SE CAUSEN DURANTE LA EJECUCIÓN DE LOS TRABAJOS A CARGO DEL ASEGURADO Y SE REFIERE EXCLUSIVAMENTE AL DESARROLLO DEL OBJETO PREVISTO EN LA PÓLIZA."
',
 'ACTIVIDADES PETROLERAS PERFORACION DE POZOS:' );

--Productos
--RC CLINICA
--Parametros vccolect:0, vcramo: 802, vctipseg: 3, vmodalidad: 1
--INSERT INTO CLAUSUPRO ( CCAPITU, CCLAUCOLEC, CCOLECT, CMODALI, CRAMO, CTIPCLA,CTIPSEG, MULTIPLE, NORDEN, SCLAGEN, SCLAPRO, TIMAGEN) 
--VALUES ( 1, NULL, 0, 1, 802, 1, 3, NULL, 60, (select max(sclagen) from CODICLAUSUGEN), (SELECT MAX(SCLAPRO)+1 FROM CLAUSUPRO), NULL );

--RC MEDICA
--Parametros vccolect:0, vcramo: 802, vctipseg: 2, vmodalidad: 1
--INSERT INTO CLAUSUPRO ( CCAPITU, CCLAUCOLEC, CCOLECT, CMODALI, CRAMO, CTIPCLA, CTIPSEG, MULTIPLE, NORDEN, SCLAGEN, SCLAPRO, TIMAGEN) 
--VALUES ( 1, NULL, 0, 1, 802, 1, 2, NULL, 60, (select max(sclagen) from CODICLAUSUGEN), (SELECT MAX(SCLAPRO)+1 FROM CLAUSUPRO), NULL );

--RC GENERAL
--Parametros vccolect:0, vcramo: 802, vctipseg: 1, vmodalidad: 9
--INSERT INTO CLAUSUPRO ( CCAPITU, CCLAUCOLEC, CCOLECT, CMODALI, CRAMO, CTIPCLA,CTIPSEG, MULTIPLE, NORDEN, SCLAGEN, SCLAPRO, TIMAGEN) 
--VALUES ( 1, NULL, 0, 9, 802, 1, 1, NULL, 60, (select max(sclagen) from CODICLAUSUGEN), (SELECT MAX(SCLAPRO)+1 FROM CLAUSUPRO), NULL );

--RC DERIVADA DE CONTRATO
--PESOS
--Parametros vccolect:0, vcramo: 802, vctipseg: 1, vmodalidad: 5
INSERT INTO CLAUSUPRO ( CCAPITU, CCLAUCOLEC, CCOLECT, CMODALI, CRAMO, CTIPCLA,CTIPSEG, MULTIPLE, NORDEN, SCLAGEN, SCLAPRO, TIMAGEN) 
VALUES ( 1, NULL, 0, 5, 802, 1, 1, NULL, 60, (select max(sclagen) from CODICLAUSUGEN), (SELECT MAX(SCLAPRO)+1 FROM CLAUSUPRO), NULL );

--DOLAR
--Parametros vccolect:0, vcramo: 802, vctipseg: 1, vmodalidad: 6
INSERT INTO CLAUSUPRO ( CCAPITU, CCLAUCOLEC, CCOLECT, CMODALI, CRAMO, CTIPCLA,CTIPSEG, MULTIPLE, NORDEN, SCLAGEN, SCLAPRO, TIMAGEN) 
VALUES ( 1, NULL, 0, 6, 802, 1, 1, NULL, 60, (select max(sclagen) from CODICLAUSUGEN), (SELECT MAX(SCLAPRO)+1 FROM CLAUSUPRO), NULL );

--EURO
--Parametros vccolect:0, vcramo: 802, vctipseg: 2, vmodalidad: 6
INSERT INTO CLAUSUPRO ( CCAPITU, CCLAUCOLEC, CCOLECT, CMODALI, CRAMO, CTIPCLA,CTIPSEG, MULTIPLE, NORDEN, SCLAGEN, SCLAPRO, TIMAGEN) 
VALUES ( 1, NULL, 0, 6, 802, 1, 2, NULL, 60, (select max(sclagen) from CODICLAUSUGEN), (SELECT MAX(SCLAPRO)+1 FROM CLAUSUPRO), NULL );

COMMIT;
 
EXCEPTION
WHEN OTHERS THEN
    p_tab_error(f_sysdate, f_user, 'Error insertando', 60, 'Err insertando', ' SQLERRM = ' || SQLERRM);
END;