DECLARE
BEGIN

--Codigo
INSERT INTO CODICLAUSUGEN ( SCLAGEN) 
VALUES ( (select max(sclagen)+1 from CODICLAUSUGEN) );

--Clausula
INSERT INTO CLAUSUGEN ( CIDIOMA, SCLAGEN, TCLATEX, TCLATIT) 
VALUES ( 8,
 (select max(sclagen) from CODICLAUSUGEN),
 '"QUEDA ENTENDIDO Y CONVENIDO POR LA PRESENTE CLAUSULA QUE, COMO CONDICIÓN PRECEDENTE A TODA OBLIGACIÓN DEL ASEGURADOR A MANTENER INDEMNE AL ASEGURADO, ESTE SE COMPROMETE Y GARANTIZA PREVER, EFECTUAR, INSTALAR, Y MANTENER CADA UNA DE LAS SIGUIENTES MEDIDAS PREVENTIVAS Y DE SEGURIDAD EN LOS SITIOS DE LA OBRA.
1. ACORDONAR Y/O VALLAR CON ELEMENTOS DE FACIL VISUALIZACIÓN DIURNA Y NOCTURNA, TODO EL PERÍMETRO DE LA OBRA, GUARDANDO UNA DISTANCIA RAZONABLEMENTE DE TODA ABERTURA Y/O EXCAVACIÓN EN EL TERRENO (SEA ESTE SUELO, PAVIMENTOS, VEREDAS PÚBLICOS O PRIVADOS), Y/O CUALESQUIERA ELEMENTOS PELIGROSOS O QUE PUDIEREN RESULTARLO, SITUADOS EN LOS SITIOS DE LA OBRA (TALES COMO PERO NO LIMITADOS A: MAQUINARIAS, HERRAMIENTAS, MATERIALES DE CONTRUCCIÓN, PARTES Y/O ELEMENTOS DE INSTALACIÓN O A SER INSTALADOS, MONTÍCULOS DE TIERRA U OTRO MATERIAL PRODUCTO DE LAS EXCAVACIONES).
2. SEÑALIZACIÓN CON CARTELES Y/O LETREROS INDICADORES QUE LLAMEN LA ATENCIÓN DEL TRANSITO VEHICULAR Y/O PEATONAL EN TODOS LOS SENTIDOS DE CIRCULACIÓN, DE CONSTRUCCIÓN METÁLICA, PINTADOS EN COLORES LLAMATIVOS Y PROPIEDAD REFLECTORA, UBICADOS EN LOS SITIOS DE LA OBRA Y A DISTANCIA COMO ADVERTENCIA.
3. SEÑALIZACIÓN NOCTURNA LUMINOSA CON BALIZAS, CUYA FUENTE DE ENERGÍA SEA CONSTANTE E INDEPENDIENTE DE LA RED PÚBLICA, INSTALADO EN LOS SITIOS DE LA OBRA. ASIMISMO DEBERA PREVERSE EL ACCIONAMIENTO DE LA SEÑALIZACIÓN EN HORARIO DIURNO DE POCA VISIBILIDAD PARA EL TRÁNSITO.
4. PERSONAL DE BANDERILLEROS, CUYA FUNCIÓN SERA LA DE PREVENIR Y SEÑALIZAR AL TRANSITO VEHICULAR, MANIOBRAS TENDIENTES A SORTEAR OBSTACULOS, REDUCCIÓN DE CALZADA, DISMINUICIÓN DE VELOCIDAD Y/O CUALESQUIERA OTRAS QUE FUERE PRUDENTE EFECTUAR.
5. TAPAR Y/O CUBRIR Y/O PROTEGER EN FORMA ADECUADA TODA ABERTURA Y/O EXCAVACIÓN EN EL TERRENO (SEA ESTE SUELO, PAVIMENTOS, VEREDAS PÚBLICOS O PRIVADOS), EN TODO LUGAR, DONDE NECESARIAMENTE DEBA CONTINUAR EL TRANSITO VEHICULAR Y/O PEATONAL.
6. TODA INSTALACIÓN Y/O CONEXIÓN ELECTRICA O DE GAS UTILIZADOS EN Y PARA LOS TRABAJOS A EFECTUARSE EN LA OBRA, O YA EXISTENTES EN LUGAR, DEBERAN SER PROTEGIDOS Y/O AISLADOS ADECUADAMENTE CON EL OBJETO DE EVITAR TODA EXPOSICIÓN HACIA BIENES O PERSONAS.
7. PREVER SISTEMAS E INSTALAR ELEMENTOS DE CONTENCIÓN DE MATERIALES Y/O SUSTANCIAS QUE PUEDAN DISPERSARSE, DEPOSITARSE, FILTRARSE O VOLCARSE FUERA DEL PERÍMETRO DE LA OBRA, Y QUE PUEDIEREN EN CONSECUENCIA SER CAUSANTES DE ""TERRENO RESBALADIZO"", TANTO PARA EL TRANSITO VEHICULAR COMO PEATONAL (SEAN ESTOS SUELOS, PAVIMENTOS, VEREDAS PÚBLICAS O PRIVADOS).
"
',
 'COBERTURA DE RESPONSABILIDAD CIVIL COMO CONSECUENCIA DE TRABAJOS EN LA VIA PUBLICA - INCLUYENDO EXCAVACION :' );

--Productos
--RC CLINICA
--Parametros vccolect:0, vcramo: 802, vctipseg: 3, vmodalidad: 1
--INSERT INTO CLAUSUPRO ( CCAPITU, CCLAUCOLEC, CCOLECT, CMODALI, CRAMO, CTIPCLA,CTIPSEG, MULTIPLE, NORDEN, SCLAGEN, SCLAPRO, TIMAGEN) 
--VALUES ( 1, NULL, 0, 1, 802, 1, 3, NULL, 26, (select max(sclagen) from CODICLAUSUGEN), (SELECT MAX(SCLAPRO)+1 FROM CLAUSUPRO), NULL );

--RC MEDICA
--Parametros vccolect:0, vcramo: 802, vctipseg: 2, vmodalidad: 1
--INSERT INTO CLAUSUPRO ( CCAPITU, CCLAUCOLEC, CCOLECT, CMODALI, CRAMO, CTIPCLA, CTIPSEG, MULTIPLE, NORDEN, SCLAGEN, SCLAPRO, TIMAGEN) 
--VALUES ( 1, NULL, 0, 1, 802, 1, 2, NULL, 26, (select max(sclagen) from CODICLAUSUGEN), (SELECT MAX(SCLAPRO)+1 FROM CLAUSUPRO), NULL );

--RC GENERAL
--Parametros vccolect:0, vcramo: 802, vctipseg: 1, vmodalidad: 9
--INSERT INTO CLAUSUPRO ( CCAPITU, CCLAUCOLEC, CCOLECT, CMODALI, CRAMO, CTIPCLA,CTIPSEG, MULTIPLE, NORDEN, SCLAGEN, SCLAPRO, TIMAGEN) 
--VALUES ( 1, NULL, 0, 9, 802, 1, 1, NULL, 26, (select max(sclagen) from CODICLAUSUGEN), (SELECT MAX(SCLAPRO)+1 FROM CLAUSUPRO), NULL );

--RC DERIVADA DE CONTRATO
--PESOS
--Parametros vccolect:0, vcramo: 802, vctipseg: 1, vmodalidad: 5
INSERT INTO CLAUSUPRO ( CCAPITU, CCLAUCOLEC, CCOLECT, CMODALI, CRAMO, CTIPCLA,CTIPSEG, MULTIPLE, NORDEN, SCLAGEN, SCLAPRO, TIMAGEN) 
VALUES ( 1, NULL, 0, 5, 802, 1, 1, NULL, 20, (select max(sclagen) from CODICLAUSUGEN), (SELECT MAX(SCLAPRO)+1 FROM CLAUSUPRO), NULL );

--DOLAR
--Parametros vccolect:0, vcramo: 802, vctipseg: 1, vmodalidad: 6
INSERT INTO CLAUSUPRO ( CCAPITU, CCLAUCOLEC, CCOLECT, CMODALI, CRAMO, CTIPCLA,CTIPSEG, MULTIPLE, NORDEN, SCLAGEN, SCLAPRO, TIMAGEN) 
VALUES ( 1, NULL, 0, 6, 802, 1, 1, NULL, 20, (select max(sclagen) from CODICLAUSUGEN), (SELECT MAX(SCLAPRO)+1 FROM CLAUSUPRO), NULL );

--EURO
--Parametros vccolect:0, vcramo: 802, vctipseg: 2, vmodalidad: 6
INSERT INTO CLAUSUPRO ( CCAPITU, CCLAUCOLEC, CCOLECT, CMODALI, CRAMO, CTIPCLA,CTIPSEG, MULTIPLE, NORDEN, SCLAGEN, SCLAPRO, TIMAGEN) 
VALUES ( 1, NULL, 0, 6, 802, 1, 2, NULL, 20, (select max(sclagen) from CODICLAUSUGEN), (SELECT MAX(SCLAPRO)+1 FROM CLAUSUPRO), NULL );

COMMIT;
 
EXCEPTION
WHEN OTHERS THEN
    p_tab_error(f_sysdate, f_user, 'Error insertando', 20, 'Err insertando', ' SQLERRM = ' || SQLERRM);
END;