--SE ELIMINAN LOS FORMULARIOS DEL USUARIO Y REGISTROS EXISTENTES QUE SE INSERTARÁN POSTERIORMENTE
UPDATE CFG_USER SET CCFGFORM = 'CFG_CENTRAL' WHERE CUSER = 'AXIS_CLIENTES_AN';
DELETE FROM CFG_FORM WHERE CCFGFORM LIKE 'CFG_CLIENTES_%';
DELETE FROM CFG_COD_FORM WHERE CFORM IN ('AXISFIC001', 'AXISFIC004', 'AXISFIC005', 'AXISFIC007');
DELETE FROM CFG_FORM_PROPERTY WHERE CIDCFG = 50;
DELETE FROM CFG_COD_CFGFORM_DET WHERE CCFGFORM = 'CFG_CLIENTES_AN'; 
DELETE FROM CFG_COD_CFGFORM WHERE CCFGFORM = 'CFG_CLIENTES_AN'; 

--SE CREA USUARIO CFG_CLIENTES_AN
Insert into CFG_COD_CFGFORM (CEMPRES,CCFGFORM,TDESC) values (24,'CFG_CLIENTES_AN','Configuración de pantallas para Análisis de Clientes Analista');
Insert into CFG_COD_CFGFORM_DET (CEMPRES,CCFGFORM,CIDIOMA,TCFGFORM) values (24,'CFG_CLIENTES_AN',1,'Configuración de pantallas para Análisis de Clientes Analista');
Insert into CFG_COD_CFGFORM_DET (CEMPRES,CCFGFORM,CIDIOMA,TCFGFORM) values (24,'CFG_CLIENTES_AN',2,'Configuración de pantallas para Análisis de Clientes Analista');
Insert into CFG_COD_CFGFORM_DET (CEMPRES,CCFGFORM,CIDIOMA,TCFGFORM) values (24,'CFG_CLIENTES_AN',8,'Configuración de pantallas para Análisis de Clientes Analista');

--SE COPIA CONFIGURACION DEL USUARIO CFG_CENTRAL PARA PERSONALIZAR POSTERIORMENTE SEGÚN ESPECIFICACIONES DEL CFG_CLIENTES_AN
INSERT INTO CFG_FORM (CEMPRES, CFORM, CMODO, CCFGFORM, SPRODUC, CIDCFG)
SELECT F.CEMPRES, F.CFORM, F.CMODO, 'CFG_CLIENTES_AN' CCFGFORM, F.SPRODUC, F.CIDCFG FROM
CFG_FORM F
JOIN CFG_COD_FORM CF ON F.CFORM = CF.CFORM
WHERE F.CCFGFORM = 'CFG_CENTRAL';
--SE COPIAN PROPIEDADES DE CONFIGURACIÓN INICIALES
INSERT INTO CFG_FORM_PROPERTY (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE)
SELECT '24' CEMPRES, '50' CIDCFG, CFORM, CITEM, CPRPTY, CVALUE FROM CFG_FORM_PROPERTY WHERE CIDCFG = 3 AND (CFORM LIKE 'AXISFIC%' OR CFORM LIKE 'AXISPER%')
UNION 
SELECT '24' CEMPRES, '50' CIDCFG, CFORM, CITEM, CPRPTY, CVALUE FROM CFG_FORM_PROPERTY WHERE CIDCFG = 1001 AND (CFORM LIKE 'AXISFIC%' OR CFORM LIKE 'AXISPER%')
UNION 
SELECT '24' CEMPRES, '50' CIDCFG, CFORM, CITEM, CPRPTY, CVALUE FROM CFG_FORM_PROPERTY WHERE CIDCFG = 1007 AND (CFORM LIKE 'AXISFIC%' OR CFORM LIKE 'AXISPER%')
UNION 
SELECT '24' CEMPRES, '50' CIDCFG, CFORM, CITEM, CPRPTY, CVALUE FROM CFG_FORM_PROPERTY WHERE CIDCFG = 1 AND (CFORM LIKE 'AXISPER017');
--SE CREA CONFIGURACIÓN PARA LA PAGINA FICHA TÉCNICA Y ENDEUDAMIENTO FINANCIERO
Insert into CFG_COD_FORM (CFORM,TFORM) values ('AXISFIC001','Ficha Tecnica');
Insert into CFG_COD_FORM (CFORM,TFORM) values ('AXISFIC004','Endeudamiento sector financiero');
Insert into CFG_COD_FORM (CFORM,TFORM) values ('AXISFIC005','Indicadores Financieros');
Insert into CFG_COD_FORM (CFORM,TFORM) values ('AXISFIC007','Editor de Textos');
--SE CREA NUEVA CONFIGURACIÓN DE FORMULARIOS
Insert into CFG_FORM (CEMPRES,CFORM,CMODO,CCFGFORM,SPRODUC,CIDCFG) values (24,'AXISPER008','MANTTO_PER','CFG_CLIENTES_AN',0,50);
Insert into CFG_FORM (CEMPRES,CFORM,CMODO,CCFGFORM,SPRODUC,CIDCFG) values (24,'AXISPER009','MANTTO_PER','CFG_CLIENTES_AN',0,50);
Insert into CFG_FORM (CEMPRES,CFORM,CMODO,CCFGFORM,SPRODUC,CIDCFG) values (24,'AXISFIC004','MANTTO_PER','CFG_CLIENTES_AN',0,50);
Insert into CFG_FORM (CEMPRES,CFORM,CMODO,CCFGFORM,SPRODUC,CIDCFG) values (24,'AXISFIC001','MANTTO_PER','CFG_CLIENTES_AN',0,50);
Insert into CFG_FORM (CEMPRES,CFORM,CMODO,CCFGFORM,SPRODUC,CIDCFG) values (24,'AXISPER014','MANTTO_PER','CFG_CLIENTES_AN',0,50);
Insert into CFG_FORM (CEMPRES,CFORM,CMODO,CCFGFORM,SPRODUC,CIDCFG) values (24,'AXISPER004','MANTTO_PER','CFG_CLIENTES_AN',0,50);
Insert into CFG_FORM (CEMPRES,CFORM,CMODO,CCFGFORM,SPRODUC,CIDCFG) values (24,'AXISPER010','MANTTO_PER','CFG_CLIENTES_AN',0,50);
Insert into CFG_FORM (CEMPRES,CFORM,CMODO,CCFGFORM,SPRODUC,CIDCFG) values (24,'AXISPER017','MANTTO_PER','CFG_CLIENTES_AN',0,50);
Insert into CFG_FORM (CEMPRES,CFORM,CMODO,CCFGFORM,SPRODUC,CIDCFG) values (24,'AXISFIC005','MANTTO_PER','CFG_CLIENTES_AN',0,50);
Insert into CFG_FORM (CEMPRES,CFORM,CMODO,CCFGFORM,SPRODUC,CIDCFG) values (24,'AXISFIC007','MANTTO_PER','CFG_CLIENTES_AN',0,50);

--SE PERSONALIZA CONFIGURACIÓN PARA EL USUARIO
DELETE FROM CFG_FORM_PROPERTY WHERE CFORM = 'AXISPER009' AND CITEM = 'BT_EDIDATOSPER' AND CIDCFG = 50  AND CPRPTY = 1;
DELETE FROM CFG_FORM_PROPERTY WHERE CFORM = 'AXISPER009' AND CITEM = 'BT_EDIDATOSPER2' AND CIDCFG = 50  AND CPRPTY = 1;
DELETE FROM CFG_FORM_PROPERTY WHERE CFORM = 'AXISFIC001' AND CITEM = 'BT_MODIFDOCUM' AND CIDCFG = 50  AND CPRPTY = 1;
DELETE FROM CFG_FORM_PROPERTY WHERE CFORM = 'AXISFIC001' AND CITEM = 'BT_NVDOCU' AND CIDCFG = 50  AND CPRPTY = 1;
DELETE FROM CFG_FORM_PROPERTY WHERE CFORM = 'AXISPER009' AND CITEM = 'BT_NVREGFISC' AND CIDCFG = 50  AND CPRPTY = 1;

Insert into CFG_FORM_PROPERTY (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) values (24,50,'AXISPER009','BT_EDIDATOSPER',1,0);
Insert into CFG_FORM_PROPERTY (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) values (24,50,'AXISPER009','BT_EDIDATOSPER2',1,0);
Insert into CFG_FORM_PROPERTY (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) values (24,50,'AXISFIC001','BT_MODIFDOCUM',1,0);
Insert into CFG_FORM_PROPERTY (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) values (24,50,'AXISFIC001','BT_NVDOCU',1,0);
Insert into CFG_FORM_PROPERTY (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) values (24,50,'AXISPER009','BT_NVREGFISC',1,0);


--SE RELACION EL USUARIO CON SU CFG_USER PERSONALIZADO
UPDATE CFG_USER SET CCFGFORM = 'CFG_CLIENTES_AN' WHERE CUSER = 'AXIS_CLIENTES_AN';
COMMIT;