DELETE FROM PARCONTRATOS WHERE SPARCNT = 'REA_MANTIENE_SUPL' AND SCONTRA = 815 AND NVERSIO = 23 AND SPRODUC = 80001;
INSERT INTO PARCONTRATOS(SCONTRA, NVERSIO, SPARCNT, SPRODUC, CVALPAR, TVALPAR, FVALPAR)
    VALUES(815, 23, 'REA_MANTIENE_SUPL', 80001, 1, NULL, NULL);  
    
DELETE FROM PARCONTRATOS WHERE SPARCNT = 'REA_MANTIENE_SUPL' AND SCONTRA = 815 AND NVERSIO = 23 AND SPRODUC = 80002;
INSERT INTO PARCONTRATOS(SCONTRA, NVERSIO, SPARCNT, SPRODUC, CVALPAR, TVALPAR, FVALPAR)
    VALUES(815, 23, 'REA_MANTIENE_SUPL', 80002, 1, NULL, NULL);   
    
DELETE FROM PARCONTRATOS WHERE SPARCNT = 'REA_MANTIENE_SUPL' AND SCONTRA = 815 AND NVERSIO = 23 AND SPRODUC = 80003;
INSERT INTO PARCONTRATOS(SCONTRA, NVERSIO, SPARCNT, SPRODUC, CVALPAR, TVALPAR, FVALPAR)
    VALUES(815, 23, 'REA_MANTIENE_SUPL', 80003, 1, NULL, NULL);     

DELETE FROM PARCONTRATOS WHERE SPARCNT = 'REA_MANTIENE_SUPL' AND SCONTRA = 815 AND NVERSIO = 23 AND SPRODUC = 80004;
INSERT INTO PARCONTRATOS(SCONTRA, NVERSIO, SPARCNT, SPRODUC, CVALPAR, TVALPAR, FVALPAR)
    VALUES(815, 23, 'REA_MANTIENE_SUPL', 80004, 1, NULL, NULL);  
    
DELETE FROM PARCONTRATOS WHERE SPARCNT = 'REA_MANTIENE_SUPL' AND SCONTRA = 815 AND NVERSIO = 23 AND SPRODUC = 80005;
INSERT INTO PARCONTRATOS(SCONTRA, NVERSIO, SPARCNT, SPRODUC, CVALPAR, TVALPAR, FVALPAR)
    VALUES(815, 23, 'REA_MANTIENE_SUPL', 80005, 1, NULL, NULL);      

DELETE FROM PARCONTRATOS WHERE SPARCNT = 'REA_MANTIENE_SUPL' AND SCONTRA = 815 AND NVERSIO = 23 AND SPRODUC = 80006;
INSERT INTO PARCONTRATOS(SCONTRA, NVERSIO, SPARCNT, SPRODUC, CVALPAR, TVALPAR, FVALPAR)
    VALUES(815, 23, 'REA_MANTIENE_SUPL', 80006, 1, NULL, NULL);  
    
DELETE FROM PARCONTRATOS WHERE SPARCNT = 'REA_MANTIENE_SUPL' AND SCONTRA = 815 AND NVERSIO = 23 AND SPRODUC = 80007;
INSERT INTO PARCONTRATOS(SCONTRA, NVERSIO, SPARCNT, SPRODUC, CVALPAR, TVALPAR, FVALPAR)
    VALUES(815, 23, 'REA_MANTIENE_SUPL', 80007, 1, NULL, NULL);     

DELETE FROM PARCONTRATOS WHERE SPARCNT = 'REA_MANTIENE_SUPL' AND SCONTRA = 815 AND NVERSIO = 23 AND SPRODUC = 80008;
INSERT INTO PARCONTRATOS(SCONTRA, NVERSIO, SPARCNT, SPRODUC, CVALPAR, TVALPAR, FVALPAR)
    VALUES(815, 23, 'REA_MANTIENE_SUPL', 80008, 1, NULL, NULL);  
    
DELETE FROM PARCONTRATOS WHERE SPARCNT = 'REA_MANTIENE_SUPL' AND SCONTRA = 815 AND NVERSIO = 23 AND SPRODUC = 80009;
INSERT INTO PARCONTRATOS(SCONTRA, NVERSIO, SPARCNT, SPRODUC, CVALPAR, TVALPAR, FVALPAR)
    VALUES(815, 23, 'REA_MANTIENE_SUPL', 80009, 1, NULL, NULL);      

DELETE FROM PARCONTRATOS WHERE SPARCNT = 'REA_MANTIENE_SUPL' AND SCONTRA = 815 AND NVERSIO = 23 AND SPRODUC = 80010;
INSERT INTO PARCONTRATOS(SCONTRA, NVERSIO, SPARCNT, SPRODUC, CVALPAR, TVALPAR, FVALPAR)
    VALUES(815, 23, 'REA_MANTIENE_SUPL', 80010, 1, NULL, NULL);
    
DELETE FROM PARCONTRATOS WHERE SPARCNT = 'REA_MANTIENE_SUPL' AND SCONTRA = 815 AND NVERSIO = 23 AND SPRODUC = 80011;
INSERT INTO PARCONTRATOS(SCONTRA, NVERSIO, SPARCNT, SPRODUC, CVALPAR, TVALPAR, FVALPAR)
    VALUES(815, 23, 'REA_MANTIENE_SUPL', 80011, 1, NULL, NULL);    

DELETE FROM PARCONTRATOS WHERE SPARCNT = 'REA_MANTIENE_SUPL' AND SCONTRA = 815 AND NVERSIO = 23 AND SPRODUC = 80012;
INSERT INTO PARCONTRATOS(SCONTRA, NVERSIO, SPARCNT, SPRODUC, CVALPAR, TVALPAR, FVALPAR)
    VALUES(815, 23, 'REA_MANTIENE_SUPL', 80012, 1, NULL, NULL);  
    
COMMIT;
/