DECLARE
	v_contexto NUMBER := 0;
BEGIN

	v_contexto := pac_contexto.f_inicializarctx(pac_parametros.f_parempresa_t(24,'USER_BBDD'));

	DELETE pargaranpro WHERE cpargar = 'CONTRATADA_DEFECTO' AND cgarant IN (7037, 7057) AND sproduc BETWEEN 80038 AND 80043;

	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,5,1,0,0,7037,'CONTRATADA_DEFECTO',1,80038,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,5,1,0,0,7057,'CONTRATADA_DEFECTO',1,80038,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,6,1,0,0,7037,'CONTRATADA_DEFECTO',1,80039,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,6,1,0,0,7057,'CONTRATADA_DEFECTO',1,80039,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,6,2,0,0,7037,'CONTRATADA_DEFECTO',1,80040,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,6,2,0,0,7057,'CONTRATADA_DEFECTO',1,80040,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,7,1,0,0,7037,'CONTRATADA_DEFECTO',1,80041,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,7,1,0,0,7057,'CONTRATADA_DEFECTO',1,80041,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,8,1,0,0,7037,'CONTRATADA_DEFECTO',1,80042,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,8,1,0,0,7057,'CONTRATADA_DEFECTO',1,80042,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,8,2,0,0,7037,'CONTRATADA_DEFECTO',1,80043,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,8,2,0,0,7057,'CONTRATADA_DEFECTO',1,80043,null,null);

	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,5,1,0,1,7037,'CONTRATADA_DEFECTO',0,80038,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,5,1,0,1,7057,'CONTRATADA_DEFECTO',0,80038,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,6,1,0,1,7037,'CONTRATADA_DEFECTO',0,80039,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,6,1,0,1,7057,'CONTRATADA_DEFECTO',0,80039,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,6,2,0,1,7037,'CONTRATADA_DEFECTO',0,80040,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,6,2,0,1,7057,'CONTRATADA_DEFECTO',0,80040,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,7,1,0,1,7037,'CONTRATADA_DEFECTO',0,80041,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,7,1,0,1,7057,'CONTRATADA_DEFECTO',0,80041,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,8,1,0,1,7037,'CONTRATADA_DEFECTO',0,80042,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,8,1,0,1,7057,'CONTRATADA_DEFECTO',0,80042,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,8,2,0,1,7037,'CONTRATADA_DEFECTO',0,80043,null,null);
	INSERT INTO PARGARANPRO (CRAMO,CMODALI,CTIPSEG,CCOLECT,CACTIVI,CGARANT,CPARGAR,CVALPAR,SPRODUC,TVALPAR,FVALPAR) VALUES (802,8,2,0,1,7057,'CONTRATADA_DEFECTO',0,80043,null,null);


	UPDATE pargaranpro
	SET cvalpar = 0
	WHERE sproduc BETWEEN 80038 AND 80043
	AND cactivi = 1
	AND cpargar = 'CONTRATADA_DEFECTO'
	AND cgarant IN (7031, 7032, 7033, 7034, 7051, 7052, 7053, 7054);
	
	COMMIT;
	
END;
/
