DECLARE
	v_contexto NUMBER := 0;
BEGIN

	v_contexto := pac_contexto.f_inicializarctx(pac_parametros.f_parempresa_t(24,'USER_BBDD'));
	
	DELETE FROM PRODMOTMOV WHERE CMOTMOV = 141 AND SPRODUC BETWEEN 80038 AND 80043;

	DELETE FROM PDS_SUPL_COD_CONFIG WHERE CCONFIG = 'conf_141_80038_suplemento_tf';
	DELETE FROM PDS_SUPL_COD_CONFIG WHERE CCONFIG = 'conf_141_80039_suplemento_tf';
	DELETE FROM PDS_SUPL_COD_CONFIG WHERE CCONFIG = 'conf_141_80040_suplemento_tf';
	DELETE FROM PDS_SUPL_COD_CONFIG WHERE CCONFIG = 'conf_141_80041_suplemento_tf';
	DELETE FROM PDS_SUPL_COD_CONFIG WHERE CCONFIG = 'conf_141_80042_suplemento_tf';
	DELETE FROM PDS_SUPL_COD_CONFIG WHERE CCONFIG = 'conf_141_80043_suplemento_tf';

	DELETE FROM PDS_SUPL_FORM WHERE CCONFIG = 'conf_141_80038_suplemento_tf';
	DELETE FROM PDS_SUPL_FORM WHERE CCONFIG = 'conf_141_80039_suplemento_tf';
	DELETE FROM PDS_SUPL_FORM WHERE CCONFIG = 'conf_141_80040_suplemento_tf';
	DELETE FROM PDS_SUPL_FORM WHERE CCONFIG = 'conf_141_80041_suplemento_tf';
	DELETE FROM PDS_SUPL_FORM WHERE CCONFIG = 'conf_141_80042_suplemento_tf';
	DELETE FROM PDS_SUPL_FORM WHERE CCONFIG = 'conf_141_80043_suplemento_tf';

	DELETE FROM PDS_SUPL_VALIDACIO WHERE CCONFIG = 'conf_141_80038_suplemento_tf';
	DELETE FROM PDS_SUPL_VALIDACIO WHERE CCONFIG = 'conf_141_80039_suplemento_tf';
	DELETE FROM PDS_SUPL_VALIDACIO WHERE CCONFIG = 'conf_141_80040_suplemento_tf';
	DELETE FROM PDS_SUPL_VALIDACIO WHERE CCONFIG = 'conf_141_80041_suplemento_tf';
	DELETE FROM PDS_SUPL_VALIDACIO WHERE CCONFIG = 'conf_141_80042_suplemento_tf';
	DELETE FROM PDS_SUPL_VALIDACIO WHERE CCONFIG = 'conf_141_80043_suplemento_tf';

	DELETE FROM PDS_SUPL_CONFIG WHERE CCONFIG = 'conf_141_80038_suplemento_tf';
	DELETE FROM PDS_SUPL_CONFIG WHERE CCONFIG = 'conf_141_80039_suplemento_tf';
	DELETE FROM PDS_SUPL_CONFIG WHERE CCONFIG = 'conf_141_80040_suplemento_tf';
	DELETE FROM PDS_SUPL_CONFIG WHERE CCONFIG = 'conf_141_80041_suplemento_tf';
	DELETE FROM PDS_SUPL_CONFIG WHERE CCONFIG = 'conf_141_80042_suplemento_tf';
	DELETE FROM PDS_SUPL_CONFIG WHERE CCONFIG = 'conf_141_80043_suplemento_tf';
	
    
    COMMIT;
	
END;
/