DECLARE
	v_contexto NUMBER := 0;
BEGIN

	v_contexto := pac_contexto.f_inicializarctx(pac_parametros.f_parempresa_t(24,'USER_BBDD'));
	
	UPDATE riesgo_defecto
	SET tnatrie = 'INDEMNIZAR LOS DAÑOS Y/O PERJUICIOS PATRIMONIALES Y EXTRAPATRIMONIALES SIEMPRE QUE DERIVEN DE UN DAÑO FÍSICO Y/O MATERIAL IMPUTABLES AL TOMADOR Y/O ASEGURADO DE LA PÓLIZA, Y CAUSADOS POR LESIONES, MUERTE Y/O DAÑOS A LA PROPIEDAD DE TERCEROS Y DERIVADOS DE LA EJECUCIÓN'
	WHERE sproduc IN (80038, 80039, 80040, 80041, 80042, 80043)	;

	UPDATE riesgo_defecto
	SET tnatrie = 'INDEMNIZAR LOS DAÑOS Y/O PERJUICIOS PATRIMONIALES Y EXTRAPATRIMONIALES SIEMPRE QUE DERIVEN DE UN DAÑO FÍSICO Y/O MATERIAL ATRIBUIBLE A LOS ASEGURADOS, POR LESIONES, MUERTE Y/O DAÑOS A LA PROPIEDAD DE TERCEROS '
	WHERE sproduc = 80044;


	COMMIT;
	
END;
/