DELETE FROM DETVALORES   WHERE CVALOR = 8001090 AND CATRIBU='18';
INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8001090', '8', '18', 'Proceso Penal'); 
INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8001090', '2', '18', 'Proceso Penal'); 
INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8001090', '1', '18', 'Proceso Penal'); 

DELETE FROM DETVALORES   WHERE CVALOR = 8001090 AND CATRIBU='19';
INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8001090', '8', '19', 'Recurso Revisión'); 
INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8001090', '2', '19', 'Recurso Revisión'); 
INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8001090', '1', '19', 'Recurso Revisión');

DELETE FROM DETVALORES   WHERE CVALOR = 8001090 AND CATRIBU='20';
INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8001090', '8', '20', 'Repetición - Acción de Repetición'); 
INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8001090', '2', '20', 'Repetición - Acción de Repetición'); 
INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8001090', '1', '20', 'Repetición - Acción de Repetición');
commit;