GRANT EXECUTE ON AXIS.OB_IAX_CONTACTOS_PER TO AXIS00;
GRANT EXECUTE ON AXIS.T_IAX_CONTACTOS_PER TO AXIS00;
create synonym AXIS00.OB_IAX_CONTACTOS_PER for AXIS.OB_IAX_CONTACTOS_PER;
create synonym AXIS00.T_IAX_CONTACTOS_PER for AXIS.T_IAX_CONTACTOS_PER;