--------------------------------------------------------
--  DDL for Table DGXPARGEDOX
--------------------------------------------------------

  CREATE TABLE "GEDOX"."DGXPARGEDOX" 
   (	"IDDOC" NUMBER(10,0), 
	"CPARCAT" VARCHAR2(30 BYTE), 
	"CVALPAR" NUMBER(15,0), 
	"TVALPAR" VARCHAR2(60 BYTE), 
	"FVALPAR" DATE, 
	"CUSUALTA" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GEDOX" ;

   COMMENT ON COLUMN "GEDOX"."DGXPARGEDOX"."IDDOC" IS 'Identificador único interno del documentos.';
   COMMENT ON COLUMN "GEDOX"."DGXPARGEDOX"."CPARCAT" IS 'Código del parámetro de categoría.';
   COMMENT ON COLUMN "GEDOX"."DGXPARGEDOX"."CVALPAR" IS 'Valor tipo numérico del parámetro.';
   COMMENT ON COLUMN "GEDOX"."DGXPARGEDOX"."TVALPAR" IS 'Valor tipo alfanumérico del parámetro.';
   COMMENT ON COLUMN "GEDOX"."DGXPARGEDOX"."FVALPAR" IS 'Valor tipo fecha del parámetro.';
   COMMENT ON COLUMN "GEDOX"."DGXPARGEDOX"."CUSUALTA" IS 'Código usuario de alta.';
   COMMENT ON COLUMN "GEDOX"."DGXPARGEDOX"."FALTA" IS 'Fecha de alta.';
   COMMENT ON COLUMN "GEDOX"."DGXPARGEDOX"."CUSUMOD" IS 'Código usuario última modificación.';
   COMMENT ON COLUMN "GEDOX"."DGXPARGEDOX"."FMODIFI" IS 'Fecha última modificación.';
   COMMENT ON TABLE "GEDOX"."DGXPARGEDOX"  IS 'Parámetros asignados a documentos.';
