--------------------------------------------------------
--  DDL for Table GDXREPCATEGOR
--------------------------------------------------------

  CREATE TABLE "GEDOX"."GDXREPCATEGOR" 
   (	"CFORM" VARCHAR2(50 BYTE), 
	"CNOMDOC" VARCHAR2(50 BYTE), 
	"IDCAT" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GEDOX" ;

   COMMENT ON COLUMN "GEDOX"."GDXREPCATEGOR"."CFORM" IS 'Nombre del formulario';
   COMMENT ON COLUMN "GEDOX"."GDXREPCATEGOR"."CNOMDOC" IS 'Nombre del informe sin extensión';
   COMMENT ON COLUMN "GEDOX"."GDXREPCATEGOR"."IDCAT" IS 'Categoria donde se pondrán los documentos';
