--------------------------------------------------------
--  DDL for Table GDXUSUARIOS
--------------------------------------------------------

  CREATE TABLE "GEDOX"."GDXUSUARIOS" 
   (	"CUSUARI" VARCHAR2(20 BYTE), 
	"CIDIOMA" NUMBER(2,0), 
	"TUSUNOM" VARCHAR2(70 BYTE), 
	"TPCPATH" VARCHAR2(30 BYTE), 
	"FBAJA" DATE, 
	"COPCION" NUMBER(6,0), 
	"TPWD" VARCHAR2(40 BYTE), 
	"PATHCATAUTO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GEDOX" ;

   COMMENT ON COLUMN "GEDOX"."GDXUSUARIOS"."CUSUARI" IS 'Código de usuario.';
   COMMENT ON COLUMN "GEDOX"."GDXUSUARIOS"."TUSUNOM" IS 'Nombre de usuario';
   COMMENT ON COLUMN "GEDOX"."GDXUSUARIOS"."TPCPATH" IS 'Path dónde se ubicaran los ficheros generados';
   COMMENT ON COLUMN "GEDOX"."GDXUSUARIOS"."COPCION" IS 'Opción de inicio del menú del usuario';
   COMMENT ON TABLE "GEDOX"."GDXUSUARIOS"  IS 'Usuario';
