--------------------------------------------------------
--  DDL for Table GEDOXPARAMOPCIONES
--------------------------------------------------------

  CREATE TABLE "GEDOX"."GEDOXPARAMOPCIONES" 
   (	"COPCION" NUMBER(6,0), 
	"TNOMPAR" VARCHAR2(15 BYTE), 
	"CTIPPAR" VARCHAR2(1 BYTE), 
	"TVALPAR" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GEDOX" ;

   COMMENT ON COLUMN "GEDOX"."GEDOXPARAMOPCIONES"."COPCION" IS 'Id de la opción';
   COMMENT ON COLUMN "GEDOX"."GEDOXPARAMOPCIONES"."TNOMPAR" IS 'Nombre del parámetro';
   COMMENT ON COLUMN "GEDOX"."GEDOXPARAMOPCIONES"."CTIPPAR" IS 'Tipo de parametro: [D] - Data Parameter [T]-Text parameter';
   COMMENT ON COLUMN "GEDOX"."GEDOXPARAMOPCIONES"."TVALPAR" IS 'Valor del parámetro';
   COMMENT ON TABLE "GEDOX"."GEDOXPARAMOPCIONES"  IS 'Tabla de lista de parametros';
