UPDATE CLAUSUGEN SET TCLATEX = 'INDENMIZAR LOS PERJUICIOS PATRIMONIALES (DAÑO EMERGENTE LUCRO CESANTE) DERIVADOS DE LA RESPONSABILIDAD CIVIL PROFESIONAL MEDICA EN QUE PUDIERE INCURRIR AL ASEGURADO A CONSECUENCIA DE NEGLIGENCIA, IMPRUDENCIA O IMPERICIA EN EL EJERCICIO DE SU PROFESION MEDICA, SI EL SINIESTRO REFERENTE INCURRIESE DENTRO DEL PERIODO DE LA VIGENCIA DEL RIESGO.' WHERE SCLAGEN = 4437;

delete from CLAUSUPRO where SCLAPRO = 89743;

INSERT INTO CLAUSUPRO (SCLAPRO, CCOLECT, CRAMO, CTIPSEG, CMODALI, CTIPCLA, SCLAGEN, NORDEN, CCAPITU) VALUES ('89743', '0', '802', '2', '1', '2', '4437', '1', '1');


commit;
/
