BEGIN
  PAC_SKIP_ORA.p_comprovacolumn('GCA_CONCILIACIONDET','VRSALDO_FIC');
END;
/
BEGIN
  PAC_SKIP_ORA.p_comprovacolumn('GCA_CONCILIACIONDET','NCERTIF_FIC');
END;
/
BEGIN
  PAC_SKIP_ORA.p_comprovacolumn('GCA_CONCILIACIONDET','NNUMIDE_FIC');
END;
/	
-- Add/modify columns 
alter table GCA_CONCILIACIONDET add VRSALDO_FIC VARCHAR2(150);
alter table GCA_CONCILIACIONDET add NCERTIF_FIC VARCHAR2(150);
alter table GCA_CONCILIACIONDET add NNUMIDE_FIC VARCHAR2(150);
-- Add comments to the columns 
comment on column GCA_CONCILIACIONDET.vrsaldo_fic
  is 'VALOR SALDO FICHERO';
comment on column GCA_CONCILIACIONDET.NCERTIF_FIC
  is 'NÚMERO DE CERTIFICADO';
comment on column GCA_CONCILIACIONDET.NNUMIDE_FIC
  is 'NÚMERO DE IDENTIFICACION';
