DELETE FROM PARPRODUCTOS WHERE  CPARPRO = 'APLICA_PRORRATEAR';
DELETE FROM DESPARAM WHERE CPARAM = 'APLICA_PRORRATEAR';
DELETE FROM CODPARAM WHERE CPARAM = 'APLICA_PRORRATEAR';

INSERT INTO CODPARAM(CPARAM, CUTILI, CTIPO, CGRPPAR, NORDEN, COBLIGA, TDEFECTO, CVISIBLE)
VALUES('APLICA_PRORRATEAR', 1, 2, 'GEN', 1, 0, NULL, 1);

INSERT INTO DESPARAM(CPARAM, CIDIOMA, TPARAM) VALUES('APLICA_PRORRATEAR', 1, 'Si s ha d aplicar el prorrateig');
INSERT INTO DESPARAM(CPARAM, CIDIOMA, TPARAM) VALUES('APLICA_PRORRATEAR', 2, 'Indica si se debe aplicar el prorrateo');
INSERT INTO DESPARAM(CPARAM, CIDIOMA, TPARAM) VALUES('APLICA_PRORRATEAR', 8, 'Indica si se debe aplicar el prorrateo');

INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80001, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80002, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80003, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80004, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80005, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80006, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80007, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80008, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80009, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80010, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80011, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80012, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80038, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80039, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80040, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80041, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80042, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80043, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);
INSERT INTO PARPRODUCTOS(SPRODUC, CPARPRO, CVALPAR, NAGRUPA, TVALPAR, FVALPAR) VALUES(80044, 'APLICA_PRORRATEAR', 1, NULL, NULL, NULL);

COMMIT;
/