--PARA QUITAR OPCIONES ANTIGUAS
UPDATE SIN_CODTRAMITADOR SET FBAJA = SYSDATE - 1 WHERE CTRAMITAD IN ('SI00');

DELETE FROM SIN_REDTRAMITADOR WHERE CTRAMITAD IN ('RE01', 'JU00');
DELETE FROM SIN_CODTRAMITADOR WHERE CTRAMITAD IN ('RE01', 'JU00');

--INSERT SIN_CODTRAMITADOR
INSERT INTO SIN_CODTRAMITADOR(CTRAMITAD, CUSUARI, CTIPTRAMIT, CACTIVO, FBAJA, CEMPRES, CNIVPER, TTRAMITAD, CUSUALT, FALTA, CUSUMOD, FMODIFI, CAUTORI, CCONVEN)
VALUES('RE01', 'AXIS_CONF', 2, 1, NULL, 24, 1, 'Área Reclamos', 'AXIS_CONF', '12-DEC-16',NULL, NULL, NULL, NULL);

INSERT INTO SIN_CODTRAMITADOR(CTRAMITAD, CUSUARI, CTIPTRAMIT, CACTIVO, FBAJA, CEMPRES, CNIVPER, TTRAMITAD, CUSUALT, FALTA, CUSUMOD, FMODIFI, CAUTORI, CCONVEN)
VALUES('JU00', 'AXIS_CONF', 2, 1, NULL, 24, 1, 'Área Procesos Judiciales', 'AXIS_CONF', '12-DEC-16',NULL, NULL, NULL, NULL);

UPDATE SIN_CODTRAMITADOR SET TTRAMITAD = 'Área Apoyo Técnico' WHERE CTRAMITAD = 'AI00';

--INSERT SIN_REDTRAMITADOR
INSERT INTO SIN_REDTRAMITADOR(CEMPRES, CTRAMITAD, FMOVINI, FMOVFIN, CTIPTRAMIT, CTRAMITPAD, CUSUALT, FALTA, CUSUMOD, FMODIFI)
VALUES(24, 'RE01', '05-JAN-17', NULL, 2, 'C000', 'AXIS_CONF', '05-JAN-17', NULL, NULL);

INSERT INTO SIN_REDTRAMITADOR(CEMPRES, CTRAMITAD, FMOVINI, FMOVFIN, CTIPTRAMIT, CTRAMITPAD, CUSUALT, FALTA, CUSUMOD, FMODIFI)
VALUES(24, 'JU00', '05-JAN-17', NULL, 2, 'C000', 'AXIS_CONF', '05-JAN-17', NULL, NULL);

COMMIT;
/