delete from CFG_LANZAR_INFORMES_PARAMS where cmap='AGENDACITACION' and TPARAM='CRAMO';
commit;
Insert into CFG_LANZAR_INFORMES_PARAMS (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,CCFGFORM,TPARAM,NORDER,SLITERA,CTIPO,NOTNULL,LVALOR) values (24,'AXISLIST003','AGENDACITACION','GENERAL',0,'GENERAL','CRAMO',6,100784,2,1,'SELECT:select 0 V, ''TODOS'' D FROM DUAL UNION select CRAMO v, tramo d from ramos where cidioma = 8 order by V');
COMMIT;