DECLARE
	v_contexto NUMBER := 0;
BEGIN

	v_contexto := pac_contexto.f_inicializarctx(pac_parametros.f_parempresa_t(24,'USER_BBDD'));
    
delete producto_texto_jspr where sproduc = 80011;
        
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80011,0,1,1);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80011,0,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80011,0,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80011,0,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80011,0,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80011,0,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80011,0,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80011,0,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80011,0,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (80011,0,11,10);

UPDATE texto_jspr
SET TEXTO = 'LA PRESENTE GARANTÍA NO EXPIRARÁ POR FALTA DE PAGO DE LA PRIMA DE LA PÓLIZA O DE LOS CERTIFICADOS O ANEXOS QUE SE EXPIDA CON FUNDAMENTO EN ELLA O POR REVOCACIÓN UNILATERAL POR PARTE DEL TOMADOR O DE LA COMPAÑIA, DE CONFORMIDAD CON LO PREVISTO EN EL NUMERAL 19 DEL ARTICULO 25 DE LA LEY 80 DE 1993.'
where id = 10;

Insert into producto_texto_jspr (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8063,0,1,1);
Insert into producto_texto_jspr (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8063,0,2,2);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8063,0,3,3);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8063,0,4,4);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8063,0,5,5);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8063,0,6,6);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8063,0,7,7);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8063,0,8,8);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8063,0,9,9);
Insert into PRODUCTO_TEXTO_JSPR (SPRODUC,CACTIVI,ID_TEXTO,ORDEN) values (8063,0,11,11);

delete from prod_plant_cab 
where sproduc = 80005
and ccodplan = 'SU-OD-06-05';

    COMMIT;

END;