UPDATE DETVALORES SET TATRIBU = 'Agencias repre/Propia' WHERE cvalor = 30 AND cidioma = 8 and catribu = 3;
UPDATE DETVALORES SET TATRIBU = 'Corredor' WHERE cvalor = 30 AND cidioma = 8 and catribu = 4;
UPDATE DETVALORES SET TATRIBU = 'Agencias' WHERE cvalor = 30 AND cidioma = 8 and catribu = 5;
UPDATE DETVALORES SET TATRIBU = 'Agente' WHERE cvalor = 30 AND cidioma = 8 and catribu = 6;

DELETE FROM DETVALORES WHERE CVALOR = 30 AND CATRIBU = 7;


INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('30', '8', '7', 'Agencia Representante');
INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('30', '2', '7', 'Agencia Representante');
INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('30', '1', '7', 'Agencia Representante');


UPDATE eco_desmonedas SET TMONEDA = 'Tope anual de régimen simplificado' WHERE CMONEDA = 'TPS' AND CIDIOMA = 2;
UPDATE eco_desmonedas SET TMONEDA = 'Tope anual de régimen simplificado' WHERE CMONEDA = 'TPS' AND CIDIOMA = 8;

DELETE FROM CFG_FORM_DEP WHERE CEMPRES = 24 AND CCFGDEP = 990013 AND CITORIG = 'MONORIG' AND TVALORIG = 'TPS' AND CITDEST = 'FCAMBIO' AND CPRPTY =  2;

DELETE FROM cfg_form_property WHERE CEMPRES = 24 AND CIDCFG = 990013 AND CPRPTY = 4 AND CITEM = 'MONORIG' AND CFORM = 'AXISFINV008';


insert into cfg_form_property (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) values (24, 990013, 'AXISFINV008', 'MONORIG', 4, 990013);

Insert into cfg_form_dep (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) values (24,'990013','MONORIG','TPS','FCAMBIO','2','1');

COMMIT;
/