DELETE FROM AXIS_LITERALES WHERE SLITERA = 89907018;
DELETE FROM AXIS_CODLITERALES WHERE SLITERA = 89907018;
INSERT INTO AXIS_CODLITERALES (SLITERA, CLITERA) VALUES (89907018,2);
INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (1, 89907018, 'Llistes Prima Mínima de Diposito');
INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (2, 89907018, 'Listados Prima Mínima de Deposito');
INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (8, 89907018, 'Listados Prima Mínima de Deposito');
DELETE FROM CFG_LANZAR_INFORMES WHERE CMAP = 'ListadosPMD';
INSERT INTO CFG_LANZAR_INFORMES (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,SLITERA,LPARAMS,GENERA_REPORT,CCFGFORM,LEXPORT,CTIPO,CGENREC,CAREA) values (24,'AXISLIST003','ListadosPMD','GENERAL',0,89907018,null,1,'GENERAL','XLSX|PDF',1,0,4);
DELETE FROM DET_LANZAR_INFORMES WHERE CMAP='ListadosPMD' AND CIDIOMA=8;
INSERT INTO DET_LANZAR_INFORMES (CEMPRES,CMAP,CIDIOMA,TDESCRIP,CINFORME) VALUES (24,'ListadosPMD',8,'Listados Prima Mínima de Deposito','ListadosPMD.jasper');
/
COMMIT;
