--CODIGO RESERVADO 89908042
DELETE FROM AXIS_LITERALES WHERE SLITERA = 89908042;
DELETE FROM AXIS_CODLITERALES WHERE SLITERA = 89908042;

-- AXIS_CODLITERALES
INSERT INTO AXIS_CODLITERALES (SLITERA,CLITERA) VALUES (89908042, 3);

-- AXIS_LITERALES
INSERT INTO AXIS_LITERALES (CIDIOMA,SLITERA,TLITERA) VALUES (1,89908042,'Pre-validador de primes cedides');
INSERT INTO AXIS_LITERALES (CIDIOMA,SLITERA,TLITERA) VALUES (2,89908042,'Pre-validador de primas cedidas');
INSERT INTO AXIS_LITERALES (CIDIOMA,SLITERA,TLITERA) VALUES (8,89908042,'Pre-validador de primas cedidas');

-- CFG_LANZAR_INFORMES
DELETE FROM CFG_LANZAR_INFORMES WHERE CMAP = 'PreValPrimasCedidas';
INSERT INTO cfg_lanzar_informes (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,SLITERA,LPARAMS,GENERA_REPORT,CCFGFORM,LEXPORT,CTIPO,CGENREC,CAREA) VALUES 
(24,'AXISLIST003','PreValPrimasCedidas','GENERAL',0,89908042,NULL,1,'GENERAL','XLSX',1,0,9);

-- DET_LANZAR_INFORMES
DELETE FROM DET_LANZAR_INFORMES WHERE CMAP = 'PreValPrimasCedidas';
INSERT INTO DET_LANZAR_INFORMES (CEMPRES,CMAP,CIDIOMA,TDESCRIP,CINFORME) VALUES 
(24,'PreValPrimasCedidas',1,'Pre-validador de primes cedides','prevalidador_primas_cedidas_reaseguro.jasper');
INSERT INTO DET_LANZAR_INFORMES (CEMPRES,CMAP,CIDIOMA,TDESCRIP,CINFORME) VALUES
(24,'PreValPrimasCedidas',2,'Pre-validador de primes cedides','prevalidador_primas_cedidas_reaseguro.jasper');
INSERT INTO DET_LANZAR_INFORMES (CEMPRES,CMAP,CIDIOMA,TDESCRIP,CINFORME) VALUES
(24,'PreValPrimasCedidas',8,'Pre-validador de primes cedides','prevalidador_primas_cedidas_reaseguro.jasper');

-- CFG_LANZAR_INFORMES_PARAMS
DELETE FROM CFG_LANZAR_INFORMES_PARAMS WHERE CMAP = 'PreValPrimasCedidas';
INSERT INTO CFG_LANZAR_INFORMES_PARAMS (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,CCFGFORM,TPARAM,NORDER,SLITERA,CTIPO,NOTNULL,LVALOR) VALUES 
(24,'AXISLIST003','PreValPrimasCedidas','GENERAL',0,'GENERAL','SPROCES',13,9000493,2,1,NULL);

COMMIT;
