--------------------------------------------------------
--  DDL for Trigger BI_TMP_TARJETAS_CASER_CORR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AXIS"."BI_TMP_TARJETAS_CASER_CORR" 
BEFORE INSERT ON TMP_TARJETAS_CASER_CORR
FOR EACH ROW
DECLARE
BEGIN
	IF :NEW.STMPCASER IS NULL THEN
		SELECT STMPCASER_CORR.NEXTVAL
		INTO :NEW.STMPCASER
		FROM DUAL;
	END IF;
END BI_TMP_TARJETAS_CASER_CORR;









/
ALTER TRIGGER "AXIS"."BI_TMP_TARJETAS_CASER_CORR" ENABLE;
