--------------------------------------------------------
--  DDL for Trigger TRG_HIS_PRODUCTO_REN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AXIS"."TRG_HIS_PRODUCTO_REN" 
   BEFORE UPDATE OR DELETE
   ON PRODUCTO_REN
   FOR EACH ROW
   DECLARE
       vaccion VARCHAR2(2);
BEGIN
   IF UPDATING THEN
       vaccion := 'U';
   ELSE
       vaccion := 'D';
   END IF;

      -- crear registro histórico
      INSERT INTO his_PRODUCTO_REN(
SPRODUC,
CTIPREN,
CCLAREN,
NNUMREN,
CPARBEN,
CLIGACT,
CPA1REN,
NPA1REN,
NRECREN,
CMUNREC,
CESTMRE,
CPCTREV,
NPCTREV,
NPCTREVMIN,
NPCTREVMAX,
NMESEXTRA,
CMODEXTRA,
CPCTFALL,
NPCTFALL,
NPCTFALLMIN,
NPCTFALLMAX,
IMESEXTRA,
CUSUALT,
FALTA,
CUSUMOD,
FMODIFI,
CUSUHIST,FCREAHIST,ACCION)
VALUES(
:OLD.SPRODUC,
:OLD.CTIPREN,
:OLD.CCLAREN,
:OLD.NNUMREN,
:OLD.CPARBEN,
:OLD.CLIGACT,
:OLD.CPA1REN,
:OLD.NPA1REN,
:OLD.NRECREN,
:OLD.CMUNREC,
:OLD.CESTMRE,
:OLD.CPCTREV,
:OLD.NPCTREV,
:OLD.NPCTREVMIN,
:OLD.NPCTREVMAX,
:OLD.NMESEXTRA,
:OLD.CMODEXTRA,
:OLD.CPCTFALL,
:OLD.NPCTFALL,
:OLD.NPCTFALLMIN,
:OLD.NPCTFALLMAX,
:OLD.IMESEXTRA,
:OLD.CUSUALT,
:OLD.FALTA,
:OLD.CUSUMOD,
:OLD.FMODIFI,
f_user, f_sysdate, ''||vaccion||'');
EXCEPTION
   WHEN OTHERS THEN
      p_tab_error(f_sysdate, f_user, 'TRIGGER trg_his_PRODUCTO_REN', 1, SQLCODE, SQLERRM);
      RAISE;
END trg_his_PRODUCTO_REN;





/
ALTER TRIGGER "AXIS"."TRG_HIS_PRODUCTO_REN" ENABLE;
