--------------------------------------------------------
--  DDL for Trigger TRG_HIS_SIN_PRO_PREGUNTA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AXIS"."TRG_HIS_SIN_PRO_PREGUNTA" 
   BEFORE UPDATE OR DELETE
   ON SIN_PRO_PREGUNTA
   FOR EACH ROW
   DECLARE
       vaccion VARCHAR2(2);
BEGIN
   IF UPDATING THEN
       vaccion := 'U';
   ELSE
       vaccion := 'D';
   END IF;

      -- crear registro histórico
      INSERT INTO his_SIN_PRO_PREGUNTA(
SPRODUC,
CACTIVI,
CTRAMIT,
CPREGUN,
CPRETIP,
NPREORD,
TPREFOR,
TVALFOR,
CUSUALT,
FALTA,
CUSUMOD,
FMODIFI,
NBLOQUE,
COBLIGA,
SEQPREG,
CCAUSIN,
CMOTSIN,
NVALDEF,
CMODIFI,
CUSUHIST,FCREAHIST,ACCION)
VALUES(
:OLD.SPRODUC,
:OLD.CACTIVI,
:OLD.CTRAMIT,
:OLD.CPREGUN,
:OLD.CPRETIP,
:OLD.NPREORD,
:OLD.TPREFOR,
:OLD.TVALFOR,
:OLD.CUSUALT,
:OLD.FALTA,
:OLD.CUSUMOD,
:OLD.FMODIFI,
:OLD.NBLOQUE,
:OLD.COBLIGA,
:OLD.SEQPREG,
:OLD.CCAUSIN,
:OLD.CMOTSIN,
:OLD.NVALDEF,
:OLD.CMODIFI,
f_user, f_sysdate, ''||vaccion||'');
EXCEPTION
   WHEN OTHERS THEN
      p_tab_error(f_sysdate, f_user, 'TRIGGER trg_his_SIN_PRO_PREGUNTA', 1, SQLCODE, SQLERRM);
      RAISE;
END trg_his_SIN_PRO_PREGUNTA;





/
ALTER TRIGGER "AXIS"."TRG_HIS_SIN_PRO_PREGUNTA" ENABLE;
