--------------------------------------------------------
--  DDL for Trigger TRG_HIS_PDS_SUPLFECHARECIBO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AXIS"."TRG_HIS_PDS_SUPLFECHARECIBO" 
   BEFORE UPDATE OR DELETE
   ON PDS_SUPLFECHARECIBO
   FOR EACH ROW
   DECLARE
       vaccion VARCHAR2(2);
BEGIN
   IF UPDATING THEN
       vaccion := 'U';
   ELSE
       vaccion := 'D';
   END IF;

      -- crear registro histórico
      INSERT INTO his_PDS_SUPLFECHARECIBO(
CMOTMOV,
SPRODUC,
CTIPO,
TFECREC,
CUSUALT,
FALTA,
CUSUMOD,
FMODIFI,
CUSUHIST,FCREAHIST,ACCION)
VALUES(
:OLD.CMOTMOV,
:OLD.SPRODUC,
:OLD.CTIPO,
:OLD.TFECREC,
:OLD.CUSUALT,
:OLD.FALTA,
:OLD.CUSUMOD,
:OLD.FMODIFI,
f_user, f_sysdate, ''||vaccion||'');
EXCEPTION
   WHEN OTHERS THEN
      p_tab_error(f_sysdate, f_user, 'TRIGGER trg_his_PDS_SUPLFECHARECIBO', 1, SQLCODE, SQLERRM);
      RAISE;
END trg_his_PDS_SUPLFECHARECIBO;





/
ALTER TRIGGER "AXIS"."TRG_HIS_PDS_SUPLFECHARECIBO" ENABLE;
