--------------------------------------------------------
--  DDL for Trigger TRG_HIS_FPRESTAPROD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AXIS"."TRG_HIS_FPRESTAPROD" 
   BEFORE UPDATE OR DELETE
   ON FPRESTAPROD
   FOR EACH ROW
   DECLARE
       vaccion VARCHAR2(2);
BEGIN
   IF UPDATING THEN
       vaccion := 'U';
   ELSE
       vaccion := 'D';
   END IF;

      -- crear registro histórico
      INSERT INTO his_FPRESTAPROD(
SPRODUC,
CTIPPRES,
CDEFECTO,
CCAUSIN,
CMOTSIN,
CGARANT,
SFPRESTA,
CUSUALT,
FALTA,
CUSUMOD,
FMODIFI,
CUSUHIST,FCREAHIST,ACCION)
VALUES(
:OLD.SPRODUC,
:OLD.CTIPPRES,
:OLD.CDEFECTO,
:OLD.CCAUSIN,
:OLD.CMOTSIN,
:OLD.CGARANT,
:OLD.SFPRESTA,
:OLD.CUSUALT,
:OLD.FALTA,
:OLD.CUSUMOD,
:OLD.FMODIFI,
f_user, f_sysdate, ''||vaccion||'');
EXCEPTION
   WHEN OTHERS THEN
      p_tab_error(f_sysdate, f_user, 'TRIGGER trg_his_FPRESTAPROD', 1, SQLCODE, SQLERRM);
      RAISE;
END trg_his_FPRESTAPROD;





/
ALTER TRIGGER "AXIS"."TRG_HIS_FPRESTAPROD" ENABLE;
