--------------------------------------------------------
--  DDL for Trigger TRG_HIS_DOCUMENTPRO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AXIS"."TRG_HIS_DOCUMENTPRO" 
   BEFORE UPDATE OR DELETE
   ON DOCUMENTPRO
   FOR EACH ROW
   DECLARE
       vaccion VARCHAR2(2);
BEGIN
   IF UPDATING THEN
       vaccion := 'U';
   ELSE
       vaccion := 'D';
   END IF;

      -- crear registro histórico
      INSERT INTO his_DOCUMENTPRO(
CDOCUMENT,
NVERSION,
NORDEN,
CRAMO,
CMODALI,
CTIPSEG,
CCOLECT,
CMOTMOV,
FALTA,
CUSUALTA,
FBAJA,
CUSUBAJA,
CTIPDOC,
CUSUMOD,
FMODIFI,
CUSUHIST,FCREAHIST,ACCION)
VALUES(
:OLD.CDOCUMENT,
:OLD.NVERSION,
:OLD.NORDEN,
:OLD.CRAMO,
:OLD.CMODALI,
:OLD.CTIPSEG,
:OLD.CCOLECT,
:OLD.CMOTMOV,
:OLD.FALTA,
:OLD.CUSUALTA,
:OLD.FBAJA,
:OLD.CUSUBAJA,
:OLD.CTIPDOC,
:OLD.CUSUMOD,
:OLD.FMODIFI,
f_user, f_sysdate, ''||vaccion||'');
EXCEPTION
   WHEN OTHERS THEN
      p_tab_error(f_sysdate, f_user, 'TRIGGER trg_his_DOCUMENTPRO', 1, SQLCODE, SQLERRM);
      RAISE;
END trg_his_DOCUMENTPRO;





/
ALTER TRIGGER "AXIS"."TRG_HIS_DOCUMENTPRO" ENABLE;
