--------------------------------------------------------
--  DDL for Trigger TRG_HIS_DOC_DOCUREQUERIDA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AXIS"."TRG_HIS_DOC_DOCUREQUERIDA" 
   BEFORE UPDATE OR DELETE
   ON DOC_DOCUREQUERIDA
   FOR EACH ROW
   DECLARE
       vaccion VARCHAR2(2);
BEGIN
   IF UPDATING THEN
       vaccion := 'U';
   ELSE
       vaccion := 'D';
   END IF;

      -- crear registro histórico
      INSERT INTO his_DOC_DOCUREQUERIDA(
CDOCUME,
SPRODUC,
CACTIVI,
NORDEN,
CTIPDOC,
CCLASE,
TFUNCIO,
CMOTMOV,
COBLIGEDOX,
CTIPDEST,
CUSUALT,
FALTA,
CUSUMOD,
FMODIFI,
CUSUHIST,FCREAHIST,ACCION)
VALUES(
:OLD.CDOCUME,
:OLD.SPRODUC,
:OLD.CACTIVI,
:OLD.NORDEN,
:OLD.CTIPDOC,
:OLD.CCLASE,
:OLD.TFUNCIO,
:OLD.CMOTMOV,
:OLD.COBLIGEDOX,
:OLD.CTIPDEST,
:OLD.CUSUALT,
:OLD.FALTA,
:OLD.CUSUMOD,
:OLD.FMODIFI,
f_user, f_sysdate, ''||vaccion||'');
EXCEPTION
   WHEN OTHERS THEN
      p_tab_error(f_sysdate, f_user, 'TRIGGER trg_his_DOC_DOCUREQUERIDA', 1, SQLCODE, SQLERRM);
      RAISE;
END trg_his_DOC_DOCUREQUERIDA;





/
ALTER TRIGGER "AXIS"."TRG_HIS_DOC_DOCUREQUERIDA" ENABLE;
