--------------------------------------------------------
--  DDL for Trigger TRG_HIS_COMISIONGAR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AXIS"."TRG_HIS_COMISIONGAR" 
   BEFORE UPDATE OR DELETE
   ON COMISIONGAR
   FOR EACH ROW
   DECLARE
       vaccion VARCHAR2(2);
BEGIN
   IF UPDATING THEN
       vaccion := 'U';
   ELSE
       vaccion := 'D';
   END IF;

      -- crear registro histórico
      INSERT INTO his_COMISIONGAR(
CRAMO,
CMODALI,
CTIPSEG,
CCOLECT,
CACTIVI,
CGARANT,
CCOMISI,
CMODCOM,
PCOMISI,
SPRODUC,
FINIVIG,
FALTA,
CUSUALTA,
FMODIFI,
CUSUMOD,
NINIALT,
NFINALT,
CCRITERIO,
NDESDE,
NHASTA,
CUSUHIST,FCREAHIST,ACCION)
VALUES(
:OLD.CRAMO,
:OLD.CMODALI,
:OLD.CTIPSEG,
:OLD.CCOLECT,
:OLD.CACTIVI,
:OLD.CGARANT,
:OLD.CCOMISI,
:OLD.CMODCOM,
:OLD.PCOMISI,
:OLD.SPRODUC,
:OLD.FINIVIG,
:OLD.FALTA,
:OLD.CUSUALTA,
:OLD.FMODIFI,
:OLD.CUSUMOD,
:OLD.NINIALT,
:OLD.NFINALT,
:OLD.CCRITERIO,
:OLD.NDESDE,
:OLD.NHASTA,
f_user, f_sysdate, ''||vaccion||'');
EXCEPTION
   WHEN OTHERS THEN
      p_tab_error(f_sysdate, f_user, 'TRIGGER trg_his_COMISIONGAR', 1, SQLCODE, SQLERRM);
      RAISE;
END trg_his_COMISIONGAR;





/
ALTER TRIGGER "AXIS"."TRG_HIS_COMISIONGAR" ENABLE;
