--------------------------------------------------------
--  DDL for Trigger TRG_HIS_PRODUCTOS_ULK
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AXIS"."TRG_HIS_PRODUCTOS_ULK" 
   BEFORE UPDATE OR DELETE
   ON PRODUCTOS_ULK
   FOR EACH ROW
   DECLARE
       vaccion VARCHAR2(2);
BEGIN
   IF UPDATING THEN
       vaccion := 'U';
   ELSE
       vaccion := 'D';
   END IF;

      -- crear registro histórico
      INSERT INTO his_PRODUCTOS_ULK(
CRAMO,
CMODALI,
CTIPSEG,
CCOLECT,
CCODFON,
NDIARIA,
PSALCUE,
ISALCUE,
CCAPDEF,
NCAPDEF,
NPOLHOS,
NCERHOS,
CMONEDA,
NDIACAR,
CPRORAT,
CANURES,
CPROVAL,
ISALMIN,
CUSUALT,
FALTA,
CUSUMOD,
FMODIFI,
CUSUHIST,FCREAHIST,ACCION)
VALUES(
:OLD.CRAMO,
:OLD.CMODALI,
:OLD.CTIPSEG,
:OLD.CCOLECT,
:OLD.CCODFON,
:OLD.NDIARIA,
:OLD.PSALCUE,
:OLD.ISALCUE,
:OLD.CCAPDEF,
:OLD.NCAPDEF,
:OLD.NPOLHOS,
:OLD.NCERHOS,
:OLD.CMONEDA,
:OLD.NDIACAR,
:OLD.CPRORAT,
:OLD.CANURES,
:OLD.CPROVAL,
:OLD.ISALMIN,
:OLD.CUSUALT,
:OLD.FALTA,
:OLD.CUSUMOD,
:OLD.FMODIFI,
f_user, f_sysdate, ''||vaccion||'');
EXCEPTION
   WHEN OTHERS THEN
      p_tab_error(f_sysdate, f_user, 'TRIGGER trg_his_PRODUCTOS_ULK', 1, SQLCODE, SQLERRM);
      RAISE;
END trg_his_PRODUCTOS_ULK;





/
ALTER TRIGGER "AXIS"."TRG_HIS_PRODUCTOS_ULK" ENABLE;
