--------------------------------------------------------
--  DDL for Trigger TRG_HIS_PARPGCF
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AXIS"."TRG_HIS_PARPGCF" 
   BEFORE UPDATE OR DELETE
   ON PARPGCF
   FOR EACH ROW
   DECLARE
       vaccion VARCHAR2(2);
BEGIN
   IF UPDATING THEN
       vaccion := 'U';
   ELSE
       vaccion := 'D';
   END IF;

      -- crear registro histórico
      INSERT INTO his_PARPGCF(
CEMPRES,
CRAMO,
CPRODUC,
CMODALI,
CGARAT,
CCESTA,
CDIVISA,
CCODFON,
CDIVISA2,
FINICIO,
FFIN,
NPARACT,
IUNIACT,
PASICST,
PCESTA,
FINIVIG,
FFINVIG,
CTIPSEG,
CCOLECT,
CUSUALT,
FALTA,
CUSUMOD,
FMODIFI,
CUSUHIST,FCREAHIST,ACCION)
VALUES(
:OLD.CEMPRES,
:OLD.CRAMO,
:OLD.CPRODUC,
:OLD.CMODALI,
:OLD.CGARAT,
:OLD.CCESTA,
:OLD.CDIVISA,
:OLD.CCODFON,
:OLD.CDIVISA2,
:OLD.FINICIO,
:OLD.FFIN,
:OLD.NPARACT,
:OLD.IUNIACT,
:OLD.PASICST,
:OLD.PCESTA,
:OLD.FINIVIG,
:OLD.FFINVIG,
:OLD.CTIPSEG,
:OLD.CCOLECT,
:OLD.CUSUALT,
:OLD.FALTA,
:OLD.CUSUMOD,
:OLD.FMODIFI,
f_user, f_sysdate, ''||vaccion||'');
EXCEPTION
   WHEN OTHERS THEN
      p_tab_error(f_sysdate, f_user, 'TRIGGER trg_his_PARPGCF', 1, SQLCODE, SQLERRM);
      RAISE;
END trg_his_PARPGCF;





/
ALTER TRIGGER "AXIS"."TRG_HIS_PARPGCF" ENABLE;
