DECLARE
	v_contexto NUMBER := 0;
BEGIN
	
	v_contexto := pac_contexto.f_inicializarctx(pac_parametros.f_parempresa_t(24,'USER_BBDD'));
    
	
    UPDATE codipregun
	SET tconsulta = 'SELECT DISTINCT DP.CCODCONTRATO||DP.CCLACONTRATO, DP.TDESCRIPCION
		  FROM DETCLASECONTRATO DP, SECTORESPROD PP, PRODUCTOS PR, CODIRAM CO
		 WHERE DP.CIDIOMA = :PMT_IDIOMA
		   AND PR.SPRODUC = :PMT_SPRODUC
		   AND PP.CCODCONTRATO = DP.CCODCONTRATO
		   AND PP.CCLACONTRATO = DP.CCLACONTRATO
		   AND PP.CRAMO = PR.CRAMO
		   AND PP.CMODALI = PR.CMODALI
		   AND PP.CTIPSEG = PR.CTIPSEG
		   AND PP.CCOLECT = PR.CCOLECT
		   AND pp.csector = (CASE WHEN (SELECT COUNT(0) FROM (SELECT R.CRESPUE FROM ESTPREGUNPOLSEG R WHERE SSEGURO = :PMT_SSEGURO AND CPREGUN = 2879 AND NMOVIMI = (SELECT MAX(NMOVIMI)
			   FROM ESTPREGUNPOLSEG P2 WHERE P2.SSEGURO = :PMT_SSEGURO AND P2.CPREGUN = 2879))) > 0 THEN (SELECT R.CRESPUE
			   FROM ESTPREGUNPOLSEG R WHERE SSEGURO = :PMT_SSEGURO
			   AND CPREGUN = 2879 AND NMOVIMI = (SELECT MAX(NMOVIMI) FROM ESTPREGUNPOLSEG P2 WHERE P2.SSEGURO = :PMT_SSEGURO
			   AND P2.CPREGUN = 2879)) ELSE (SELECT R.CRESPUE FROM PREGUNPOLSEG R WHERE SSEGURO = (SELECT sseguro FROM seguros WHERE npoliza = :PMT_NPOLIZA) AND CPREGUN = 2879
			   AND NMOVIMI = (SELECT MAX(NMOVIMI) FROM PREGUNPOLSEG P2 WHERE P2.SSEGURO = (SELECT sseguro FROM seguros WHERE npoliza = :PMT_NPOLIZA)
			   AND P2.CPREGUN = 2879) UNION SELECT R.CRESPUE FROM ESTPREGUNPOLSEG R WHERE SSEGURO = :PMT_SSEGURO
			   AND CPREGUN = 2879 AND NMOVIMI = (SELECT MAX(NMOVIMI) FROM ESTPREGUNPOLSEG P2
			   WHERE P2.SSEGURO = :PMT_SSEGURO AND P2.CPREGUN = 2879)) END)
		  AND CO.CRAMO = PR.CRAMO
		  AND PP.CEMPRES = CO.CEMPRES
	ORDER BY DP.TDESCRIPCION'
	WHERE cpregun = 2880;
	
	
	COMMIT;
	
END;
/