BEGIN

INSERT INTO CFG_FORM_PROPERTY (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) VALUES('24', '1007', 'AXISPER010', 'CTIPIDEcerca', '4', '99840290');
INSERT INTO CFG_FORM_DEP (CEMPRES,CCFGDEP,CITORIG,TVALORIG,CITDEST,CPRPTY,TVALUE) VALUES ('24','99840290','CTIPIDEcerca','36','SWRUT','7','1');
COMMIT;

	BEGIN
	Insert into LOG_INSTALACION (CODIGO,FECHA,USUARIO,ERROR,MODULOS, TITULO) 
	values ('01_PROPERTY_V01',f_sysdate,f_user,null,'Creacion de Personas','CFG_FORM_PROPERTY, CFG_FORM_DEP, AXISPER010.jsp');
	COMMIT;
	EXCEPTION WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR LOG_INSTALACION');
	END;

EXCEPTION WHEN OTHERS THEN
	DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR CFG_FORM_PROPERTY, CFG_FORM_DEP');
END;
/