--------------------------------------------------------
--  DDL for View DIS_DOCS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "AXIS"."DIS_DOCS" ("DOCUMENT_ID", "OWNER", "DOCUMENT_NAME", "COMMENTS", "CREATE_DATE", "MODIFIED_DATE", "MODIFIED_BY", "DOC_LENGTH", "DOCUMENT", "BATCH") AS 
  SELECT "DOCUMENT_ID" ,  "OWNER" ,  "DOCUMENT_NAME" ,  "COMMENTS" ,  "CREATE_DATE" ,  "MODIFIED_DATE" ,  "MODIFIED_BY" ,  "DOC_LENGTH" ,  "DOCUMENT" ,  "BATCH" FROM DIS_DOCS_ WHERE OWNER = F_USER WITH CHECK OPTION
 
 
;
  GRANT UPDATE ON "AXIS"."DIS_DOCS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIS_DOCS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DIS_DOCS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DIS_DOCS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIS_DOCS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DIS_DOCS" TO "PROGRAMADORESCSI";
