--------------------------------------------------------
--  DDL for View PRIMAS_APORTADAS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "AXIS"."PRIMAS_APORTADAS" ("SSEGURO", "NNUMLIN", "FVALMOV", "IPRIMA", "CMOVIMI") AS 
  SELECT SSEGURO, NNUMLIN, FVALMOV, IMOVIMI, CMOVIMI
  FROM CTASEGURO
 WHERE cmovimi IN (1, 2, 4, 8)
 AND NVL(cmovanu, 0) = 0
 AND imovimi > 0
 and nvl(f_cestrec_mv(nrecibo,null),1) = 1 
 
 
;
  GRANT UPDATE ON "AXIS"."PRIMAS_APORTADAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRIMAS_APORTADAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PRIMAS_APORTADAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PRIMAS_APORTADAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRIMAS_APORTADAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PRIMAS_APORTADAS" TO "PROGRAMADORESCSI";
