--------------------------------------------------------
--  DDL for View VISTA_PRODUCTOS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "AXIS"."VISTA_PRODUCTOS" ("CTIPSEG", "CCOLECT", "CRAMO", "CMODALI", "CAGRPRO", "CSUBPRO", "CACTIVO", "CTIPREB", "CTIPGES", "CRECCOB", "CTIPPAG", "CPAGDEF", "CDURACI", "CTEMPOR", "CTARMAN", "CTIPEFE", "CGARSIN", "CVALMAN", "CTIPRIE", "CVALFIN", "COBJASE", "CPROTEC", "SCLABEN", "NEDAMIC", "NEDAMAC", "NEDAMAR", "PINTTEC", "PGASINT", "PGASEXT", "IPRIMIN", "NDURCOB", "CRECFRA", "CRETENI", "CIMPPRI", "CIMPTAX", "CIMPCON", "CCUESTI", "CTIPCAL", "CIMPEFE", "CMODELO", "CCALCOM", "CREASEG", "PREVALI", "IREVALI", "CREVALI", "CRAMDGS", "CTIPIMP", "CREVFPG", "CMOVDOM") AS 
  select "CTIPSEG","CCOLECT","CRAMO","CMODALI","CAGRPRO","CSUBPRO","CACTIVO","CTIPREB","CTIPGES","CRECCOB","CTIPPAG","CPAGDEF","CDURACI","CTEMPOR","CTARMAN","CTIPEFE","CGARSIN","CVALMAN","CTIPRIE","CVALFIN","COBJASE","CPROTEC","SCLABEN","NEDAMIC","NEDAMAC","NEDAMAR","PINTTEC","PGASINT","PGASEXT","IPRIMIN","NDURCOB","CRECFRA","CRETENI","CIMPPRI","CIMPTAX","CIMPCON","CCUESTI","CTIPCAL","CIMPEFE","CMODELO","CCALCOM","CREASEG","PREVALI","IREVALI","CREVALI","CRAMDGS","CTIPIMP","CREVFPG","CMOVDOM" from productos where  (cramo, cmodali, ctipseg, ccolect ) in
	(select p.cramo, p.cmodali, p.ctipseg, p.ccolect
	 from productos p, usu_prod u
	 where p.cramo   = u.cramo
	   and p.cmodali = u.cmodali
	   and p.ctipseg = u.ctipseg
	   and p.ccolect = u.ccolect
	   and u.cusuari = F_USER )
 
 
;
  GRANT UPDATE ON "AXIS"."VISTA_PRODUCTOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."VISTA_PRODUCTOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."VISTA_PRODUCTOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."VISTA_PRODUCTOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."VISTA_PRODUCTOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."VISTA_PRODUCTOS" TO "PROGRAMADORESCSI";
