--------------------------------------------------------
--  DDL for View VISTA_VDETRECIBOS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "AXIS"."VISTA_VDETRECIBOS" ("NRECIBO", "IPRINET", "IRECEXT", "ICONSOR", "IRECCON", "IIPS", "IDGS", "IARBITR", "IFNG", "IRECFRA", "IDTOTEC", "IDTOCOM", "ICOMBRU", "ICOMRET", "IDTOOM", "IPRIDEV", "ITOTPRI", "ITOTDTO", "ITOTCON", "ITOTIMP", "ITOTALR", "IDERREG", "ITOTREC", "ICOMDEV", "IRETDEV", "ICEDNET", "ICEDREX", "ICEDCON", "ICEDRCO", "ICEDIPS", "ICEDDGS", "ICEDARB", "ICEDFNG", "ICEDRFR", "ICEDDTE", "ICEDDCO", "ICEDCBR", "ICEDCRT", "ICEDDOM", "ICEDPDV", "ICEDREG", "ICEDCDV", "ICEDRDV", "IT1PRI", "IT1DTO", "IT1CON", "IT1IMP", "IT1REC", "IT1TOTR", "IT2PRI", "IT2DTO", "IT2CON", "IT2IMP", "IT2REC", "IT2TOTR") AS 
  select "NRECIBO","IPRINET","IRECEXT","ICONSOR","IRECCON","IIPS","IDGS","IARBITR","IFNG","IRECFRA","IDTOTEC","IDTOCOM","ICOMBRU","ICOMRET","IDTOOM","IPRIDEV","ITOTPRI","ITOTDTO","ITOTCON","ITOTIMP","ITOTALR","IDERREG","ITOTREC","ICOMDEV","IRETDEV","ICEDNET","ICEDREX","ICEDCON","ICEDRCO","ICEDIPS","ICEDDGS","ICEDARB","ICEDFNG","ICEDRFR","ICEDDTE","ICEDDCO","ICEDCBR","ICEDCRT","ICEDDOM","ICEDPDV","ICEDREG","ICEDCDV","ICEDRDV","IT1PRI","IT1DTO","IT1CON","IT1IMP","IT1REC","IT1TOTR","IT2PRI","IT2DTO","IT2CON","IT2IMP","IT2REC","IT2TOTR" from vdetrecibos where nrecibo in
( SELECT nrecibo FROM recibosredcom sr, usuarios u
  WHERE u.cusuari = F_USER AND sr.cagente = u.cdelega )
 
 
;
  GRANT UPDATE ON "AXIS"."VISTA_VDETRECIBOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."VISTA_VDETRECIBOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."VISTA_VDETRECIBOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."VISTA_VDETRECIBOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."VISTA_VDETRECIBOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."VISTA_VDETRECIBOS" TO "PROGRAMADORESCSI";
