--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_59MOVPAGOS_CTATEC
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONF_DWH"."SYS_C_SNAP$_59MOVPAGOS_CTATEC" ON "CONF_DWH"."DIM_MOVPAGOS_CTATEC_COA" ("SMOVPAGCOA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CONF_DWH" ;
