--------------------------------------------------------
--  DDL for Table ACTIVIPROF
--------------------------------------------------------

  CREATE TABLE "AXIS"."ACTIVIPROF" 
   (	"CACTPRO" NUMBER(4,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TACTPRO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ACTIVIPROF"."CACTPRO" IS 'Código actividad';
   COMMENT ON COLUMN "AXIS"."ACTIVIPROF"."CIDIOMA" IS 'Código de Idioma';
   COMMENT ON COLUMN "AXIS"."ACTIVIPROF"."TACTPRO" IS 'Descripción de actividad del profesional';
  GRANT UPDATE ON "AXIS"."ACTIVIPROF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ACTIVIPROF" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ACTIVIPROF" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ACTIVIPROF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ACTIVIPROF" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ACTIVIPROF" TO "PROGRAMADORESCSI";
