--------------------------------------------------------
--  DDL for Table ACTIONS_UNDW
--------------------------------------------------------

  CREATE TABLE "AXIS"."ACTIONS_UNDW" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"CEMPRES" NUMBER(5,0), 
	"SORDEN" NUMBER, 
	"NORDEN" NUMBER, 
	"ACTION" VARCHAR2(2000 BYTE), 
	"NASEG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ACTIONS_UNDW"."SSEGURO" IS 'Secuencia seguro';
   COMMENT ON COLUMN "AXIS"."ACTIONS_UNDW"."NRIESGO" IS 'Numero de riesgo';
   COMMENT ON COLUMN "AXIS"."ACTIONS_UNDW"."NMOVIMI" IS 'Numero de movimiento';
   COMMENT ON COLUMN "AXIS"."ACTIONS_UNDW"."CEMPRES" IS 'Codigo de la empresa';
   COMMENT ON COLUMN "AXIS"."ACTIONS_UNDW"."SORDEN" IS 'Case id';
   COMMENT ON COLUMN "AXIS"."ACTIONS_UNDW"."NORDEN" IS 'Numero de orden';
   COMMENT ON COLUMN "AXIS"."ACTIONS_UNDW"."ACTION" IS 'Accion (AIS MANUAL UNDW)';
   COMMENT ON COLUMN "AXIS"."ACTIONS_UNDW"."NASEG" IS 'Numero de asegurado.';
  GRANT UPDATE ON "AXIS"."ACTIONS_UNDW" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ACTIONS_UNDW" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ACTIONS_UNDW" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ACTIONS_UNDW" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ACTIONS_UNDW" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ACTIONS_UNDW" TO "PROGRAMADORESCSI";
