--------------------------------------------------------
--  DDL for Table ACTIVOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."ACTIVOS" 
   (	"SACTIVO" NUMBER(6,0), 
	"CACTIVO" VARCHAR2(15 BYTE), 
	"TACTIVO" VARCHAR2(40 BYTE), 
	"IPREADQ" NUMBER(9,6), 
	"FCOMPRA" DATE, 
	"ICOMPRA" NUMBER, 
	"CDIVISA" NUMBER(2,0), 
	"FCIERRE" DATE, 
	"POLISSA_INI" VARCHAR2(15 BYTE), 
	"POLISSA_FI" VARCHAR2(15 BYTE), 
	"CAGRUPA" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ACTIVOS"."SACTIVO" IS 'Clave del Activo';
   COMMENT ON COLUMN "AXIS"."ACTIVOS"."CACTIVO" IS 'Código del Activo';
   COMMENT ON COLUMN "AXIS"."ACTIVOS"."TACTIVO" IS 'Descripción del Activo';
   COMMENT ON COLUMN "AXIS"."ACTIVOS"."IPREADQ" IS 'Importe del Precio de Adquisición';
   COMMENT ON COLUMN "AXIS"."ACTIVOS"."FCOMPRA" IS 'Fecha de Compra del Activo';
   COMMENT ON COLUMN "AXIS"."ACTIVOS"."ICOMPRA" IS 'Importe del Precio de Compra';
   COMMENT ON COLUMN "AXIS"."ACTIVOS"."CDIVISA" IS 'Codigo de la Divisa';
   COMMENT ON COLUMN "AXIS"."ACTIVOS"."FCIERRE" IS 'Fecha de Cierre del Activo';
   COMMENT ON COLUMN "AXIS"."ACTIVOS"."POLISSA_INI" IS 'Número certificado inicial de HOST';
   COMMENT ON COLUMN "AXIS"."ACTIVOS"."POLISSA_FI" IS 'Número certificado final de HOST';
   COMMENT ON COLUMN "AXIS"."ACTIVOS"."CAGRUPA" IS 'Código de Agrupación.(PARPRODUCTOS-AGRACTIVOS)';
   COMMENT ON TABLE "AXIS"."ACTIVOS"  IS 'Definición de Activos';
  GRANT UPDATE ON "AXIS"."ACTIVOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ACTIVOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ACTIVOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ACTIVOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ACTIVOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ACTIVOS" TO "PROGRAMADORESCSI";
