--------------------------------------------------------
--  DDL for Table ACTVALORES
--------------------------------------------------------

  CREATE TABLE "AXIS"."ACTVALORES" 
   (	"CACTVAL" NUMBER(3,0), 
	"TACTVAL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ACTVALORES"."CACTVAL" IS 'Código';
   COMMENT ON COLUMN "AXIS"."ACTVALORES"."TACTVAL" IS 'Descripción';
  GRANT UPDATE ON "AXIS"."ACTVALORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ACTVALORES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ACTVALORES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ACTVALORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ACTVALORES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ACTVALORES" TO "PROGRAMADORESCSI";
