--------------------------------------------------------
--  DDL for Table ADM_LIQUIDA_MOV
--------------------------------------------------------

  CREATE TABLE "AXIS"."ADM_LIQUIDA_MOV" 
   (	"SPROLIQ" NUMBER, 
	"CCOMPANI" NUMBER(8,0), 
	"NMOVLIQ" NUMBER(3,0), 
	"CESTLIQ" NUMBER(2,0), 
	"CMONLIQ" VARCHAR2(3 BYTE), 
	"ITOTLIQ" NUMBER, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ADM_LIQUIDA_MOV"."SPROLIQ" IS 'Secuencial Proceso Liquidación';
   COMMENT ON COLUMN "AXIS"."ADM_LIQUIDA_MOV"."CCOMPANI" IS 'Compañia que vamos a liquidar';
   COMMENT ON COLUMN "AXIS"."ADM_LIQUIDA_MOV"."NMOVLIQ" IS 'Número Movimiento Liquidación';
   COMMENT ON COLUMN "AXIS"."ADM_LIQUIDA_MOV"."CESTLIQ" IS 'Código Estado Liquidación';
   COMMENT ON COLUMN "AXIS"."ADM_LIQUIDA_MOV"."CMONLIQ" IS 'Código Moneda Liquidación';
   COMMENT ON COLUMN "AXIS"."ADM_LIQUIDA_MOV"."ITOTLIQ" IS 'Importe Total Liquidación';
   COMMENT ON COLUMN "AXIS"."ADM_LIQUIDA_MOV"."CUSUALT" IS 'Código Usuario Alta';
   COMMENT ON COLUMN "AXIS"."ADM_LIQUIDA_MOV"."FALTA" IS 'Fecha Alta';
   COMMENT ON TABLE "AXIS"."ADM_LIQUIDA_MOV"  IS 'Movimientos Proceso liquidación';
  GRANT UPDATE ON "AXIS"."ADM_LIQUIDA_MOV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ADM_LIQUIDA_MOV" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ADM_LIQUIDA_MOV" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ADM_LIQUIDA_MOV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ADM_LIQUIDA_MOV" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ADM_LIQUIDA_MOV" TO "PROGRAMADORESCSI";
