--------------------------------------------------------
--  DDL for Table AGD_CODIROLOBS
--------------------------------------------------------

  CREATE TABLE "AXIS"."AGD_CODIROLOBS" 
   (	"CEMPRES" NUMBER(2,0), 
	"CROLOBS" NUMBER(9,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."AGD_CODIROLOBS"."CEMPRES" IS 'Empresa';
   COMMENT ON COLUMN "AXIS"."AGD_CODIROLOBS"."CROLOBS" IS 'Codi del Rol';
   COMMENT ON COLUMN "AXIS"."AGD_CODIROLOBS"."CUSUALT" IS 'Usuario de Alta';
   COMMENT ON COLUMN "AXIS"."AGD_CODIROLOBS"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."AGD_CODIROLOBS"."CUSUMOD" IS 'Usuario de la modificación';
   COMMENT ON COLUMN "AXIS"."AGD_CODIROLOBS"."FMODIFI" IS 'Fecha de modificación';
   COMMENT ON TABLE "AXIS"."AGD_CODIROLOBS"  IS 'Codi Roles de Agenda';
  GRANT UPDATE ON "AXIS"."AGD_CODIROLOBS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGD_CODIROLOBS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AGD_CODIROLOBS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AGD_CODIROLOBS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGD_CODIROLOBS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AGD_CODIROLOBS" TO "PROGRAMADORESCSI";
