--------------------------------------------------------
--  DDL for Table AGD_CHAT
--------------------------------------------------------

  CREATE TABLE "AXIS"."AGD_CHAT" 
   (	"IDAGENDA" NUMBER(8,0), 
	"IDAPUNTE" NUMBER, 
	"NMOVAGD" NUMBER(6,0), 
	"NMOVCHAT" NUMBER(6,0), 
	"TTEXTO" VARCHAR2(4000 BYTE), 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"CGRUPO" VARCHAR2(40 BYTE), 
	"TGRUPO" VARCHAR2(40 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"CTIPRES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."AGD_CHAT"."IDAGENDA" IS 'Identificador Agenda';
   COMMENT ON COLUMN "AXIS"."AGD_CHAT"."IDAPUNTE" IS 'Identificador Apunte';
   COMMENT ON COLUMN "AXIS"."AGD_CHAT"."NMOVAGD" IS 'Movimiento de la agenda(asignación) ';
   COMMENT ON COLUMN "AXIS"."AGD_CHAT"."NMOVCHAT" IS 'Movimiento del chat';
   COMMENT ON COLUMN "AXIS"."AGD_CHAT"."TTEXTO" IS 'Texto del chat';
   COMMENT ON COLUMN "AXIS"."AGD_CHAT"."CUSUARI" IS 'Código Usuario realiza asignación';
   COMMENT ON COLUMN "AXIS"."AGD_CHAT"."CGRUPO" IS 'Código Grupo  realiza asignación';
   COMMENT ON COLUMN "AXIS"."AGD_CHAT"."TGRUPO" IS 'Valor Grupo  realiza asignación';
   COMMENT ON COLUMN "AXIS"."AGD_CHAT"."CUSUALT" IS 'Código Usuario Alta';
   COMMENT ON COLUMN "AXIS"."AGD_CHAT"."FALTA" IS 'Fecha Alta';
   COMMENT ON COLUMN "AXIS"."AGD_CHAT"."CUSUMOD" IS 'Usuario modificación';
   COMMENT ON COLUMN "AXIS"."AGD_CHAT"."FMODIFI" IS 'Fecha Modificación';
   COMMENT ON COLUMN "AXIS"."AGD_CHAT"."CTIPRES" IS 'Código tipo de respuesta';
   COMMENT ON TABLE "AXIS"."AGD_CHAT"  IS 'Chat de la agenda relacionado con los movimientos de asignaciones';
  GRANT UPDATE ON "AXIS"."AGD_CHAT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGD_CHAT" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AGD_CHAT" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AGD_CHAT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGD_CHAT" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AGD_CHAT" TO "PROGRAMADORESCSI";
