--------------------------------------------------------
--  DDL for Table AGD_GRUPOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."AGD_GRUPOS" 
   (	"CEMPRES" NUMBER(2,0), 
	"CGRUPO" VARCHAR2(50 BYTE), 
	"CIDIOMA" NUMBER(6,0), 
	"TDESC" VARCHAR2(250 BYTE), 
	"TMAIL" VARCHAR2(250 BYTE), 
	"CSUBGRUP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."AGD_GRUPOS"."CEMPRES" IS 'Código de la empresa';
   COMMENT ON COLUMN "AXIS"."AGD_GRUPOS"."CGRUPO" IS 'Id del grupo';
   COMMENT ON COLUMN "AXIS"."AGD_GRUPOS"."CIDIOMA" IS 'Idioma de la descripción';
   COMMENT ON COLUMN "AXIS"."AGD_GRUPOS"."TDESC" IS 'Descripción del grupo';
   COMMENT ON COLUMN "AXIS"."AGD_GRUPOS"."TMAIL" IS 'E-mail del grupo';
   COMMENT ON COLUMN "AXIS"."AGD_GRUPOS"."CSUBGRUP" IS 'Subgrupo del grupo de la redcomercial';
   COMMENT ON TABLE "AXIS"."AGD_GRUPOS"  IS 'Grupos de la agenda';
  GRANT UPDATE ON "AXIS"."AGD_GRUPOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGD_GRUPOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AGD_GRUPOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AGD_GRUPOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGD_GRUPOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AGD_GRUPOS" TO "PROGRAMADORESCSI";
