--------------------------------------------------------
--  DDL for Table AGD_APUNTE
--------------------------------------------------------

  CREATE TABLE "AXIS"."AGD_APUNTE" 
   (	"IDAPUNTE" NUMBER(8,0), 
	"CCONAPU" NUMBER(2,0), 
	"CTIPAPU" NUMBER(1,0), 
	"TTITAPU" VARCHAR2(100 BYTE), 
	"TAPUNTE" VARCHAR2(2000 BYTE), 
	"FAPUNTE" DATE, 
	"FRECORDATORIO" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."AGD_APUNTE"."IDAPUNTE" IS 'Identificador Apunte';
   COMMENT ON COLUMN "AXIS"."AGD_APUNTE"."CCONAPU" IS 'Código Concepto Apunte';
   COMMENT ON COLUMN "AXIS"."AGD_APUNTE"."CTIPAPU" IS 'Código Tipo Apunte V.F.323';
   COMMENT ON COLUMN "AXIS"."AGD_APUNTE"."TTITAPU" IS 'Título Apunte';
   COMMENT ON COLUMN "AXIS"."AGD_APUNTE"."TAPUNTE" IS 'Descripción Apunte';
   COMMENT ON COLUMN "AXIS"."AGD_APUNTE"."FAPUNTE" IS 'Fecha Aviso Apunte';
   COMMENT ON COLUMN "AXIS"."AGD_APUNTE"."FRECORDATORIO" IS 'Fecha Recordatorio';
   COMMENT ON COLUMN "AXIS"."AGD_APUNTE"."CUSUALT" IS 'Código Usuario Alta';
   COMMENT ON COLUMN "AXIS"."AGD_APUNTE"."FALTA" IS 'Fecha Alta';
   COMMENT ON TABLE "AXIS"."AGD_APUNTE"  IS 'Apuntes';
  GRANT UPDATE ON "AXIS"."AGD_APUNTE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGD_APUNTE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AGD_APUNTE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AGD_APUNTE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGD_APUNTE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AGD_APUNTE" TO "PROGRAMADORESCSI";
