--------------------------------------------------------
--  DDL for Table AGD_HIS_OBS_CFG
--------------------------------------------------------

  CREATE TABLE "AXIS"."AGD_HIS_OBS_CFG" 
   (	"CEMPRES" NUMBER(2,0), 
	"CTIPAGD" NUMBER(2,0), 
	"CCONOBS" NUMBER(8,0), 
	"CROLPROP" VARCHAR2(200 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."AGD_HIS_OBS_CFG"."CEMPRES" IS 'Empresa';
   COMMENT ON COLUMN "AXIS"."AGD_HIS_OBS_CFG"."CTIPAGD" IS 'Tipo de agenda : Póliza, recibo, agentes, siniestros...';
   COMMENT ON COLUMN "AXIS"."AGD_HIS_OBS_CFG"."CCONOBS" IS 'Valor fijo utilizado para el tipo de concepto por agenda de póliza, recibo...';
   COMMENT ON COLUMN "AXIS"."AGD_HIS_OBS_CFG"."CROLPROP" IS 'Rol propietario de la agenda, siempre verá los datos de este tipo de agenda';
   COMMENT ON COLUMN "AXIS"."AGD_HIS_OBS_CFG"."CUSUALT" IS 'USUARIO QUE DA DE ALTA EL REGISTRO';
   COMMENT ON COLUMN "AXIS"."AGD_HIS_OBS_CFG"."FALTA" IS 'FECHA DE ALTA DEL REGISTRO';
   COMMENT ON COLUMN "AXIS"."AGD_HIS_OBS_CFG"."CUSUMOD" IS 'USUARIO QUE MODIFICA EL REGISTRO';
   COMMENT ON COLUMN "AXIS"."AGD_HIS_OBS_CFG"."FMODIFI" IS 'FECHA DE MOFICIACIÓN DEL REGISTRO';
   COMMENT ON TABLE "AXIS"."AGD_HIS_OBS_CFG"  IS 'Historico Configuración de las agendas';
  GRANT UPDATE ON "AXIS"."AGD_HIS_OBS_CFG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGD_HIS_OBS_CFG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AGD_HIS_OBS_CFG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AGD_HIS_OBS_CFG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGD_HIS_OBS_CFG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AGD_HIS_OBS_CFG" TO "PROGRAMADORESCSI";
