--------------------------------------------------------
--  DDL for Table AGD_MOVAPUNTE
--------------------------------------------------------

  CREATE TABLE "AXIS"."AGD_MOVAPUNTE" 
   (	"IDAPUNTE" NUMBER(8,0), 
	"NMOVAPU" NUMBER(3,0), 
	"CESTAPU" NUMBER(1,0), 
	"FESTAPU" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."AGD_MOVAPUNTE"."IDAPUNTE" IS 'Identificador Apunte';
   COMMENT ON COLUMN "AXIS"."AGD_MOVAPUNTE"."NMOVAPU" IS 'Número Movimiento Apunte';
   COMMENT ON COLUMN "AXIS"."AGD_MOVAPUNTE"."CESTAPU" IS 'Código Estado Apunte';
   COMMENT ON COLUMN "AXIS"."AGD_MOVAPUNTE"."FESTAPU" IS 'Fecha Estado Apunte';
   COMMENT ON COLUMN "AXIS"."AGD_MOVAPUNTE"."CUSUALT" IS 'Código Usuario Alta';
   COMMENT ON COLUMN "AXIS"."AGD_MOVAPUNTE"."FALTA" IS 'Fecha Alta';
   COMMENT ON TABLE "AXIS"."AGD_MOVAPUNTE"  IS 'Movimientos Apuntes';
  GRANT UPDATE ON "AXIS"."AGD_MOVAPUNTE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGD_MOVAPUNTE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AGD_MOVAPUNTE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AGD_MOVAPUNTE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGD_MOVAPUNTE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AGD_MOVAPUNTE" TO "PROGRAMADORESCSI";
