--------------------------------------------------------
--  DDL for Table AGE_REFERENCIAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."AGE_REFERENCIAS" 
   (	"CAGENTE" NUMBER, 
	"NORDREFERENCIA" NUMBER, 
	"TREFERENCIA" VARCHAR2(200 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FMOVIMI" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."AGE_REFERENCIAS"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."AGE_REFERENCIAS"."NORDREFERENCIA" IS 'Número de orden de referencia';
   COMMENT ON COLUMN "AXIS"."AGE_REFERENCIAS"."TREFERENCIA" IS 'Descripción de la referencia';
   COMMENT ON COLUMN "AXIS"."AGE_REFERENCIAS"."CUSUALT" IS 'Código usuario alta del registro';
   COMMENT ON COLUMN "AXIS"."AGE_REFERENCIAS"."FALTA" IS 'Fecha de alta del registro';
   COMMENT ON COLUMN "AXIS"."AGE_REFERENCIAS"."CUSUARI" IS 'Código usuario modificación del registro';
   COMMENT ON COLUMN "AXIS"."AGE_REFERENCIAS"."FMOVIMI" IS 'Fecha modificación del registro';
   COMMENT ON TABLE "AXIS"."AGE_REFERENCIAS"  IS 'Otras referencias del agente';
  GRANT UPDATE ON "AXIS"."AGE_REFERENCIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGE_REFERENCIAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AGE_REFERENCIAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AGE_REFERENCIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGE_REFERENCIAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AGE_REFERENCIAS" TO "PROGRAMADORESCSI";
