--------------------------------------------------------
--  DDL for Table AGENTES
--------------------------------------------------------

  CREATE TABLE "AXIS"."AGENTES" 
   (	"CAGENTE" NUMBER, 
	"CRETENC" NUMBER(2,0), 
	"CTIPIVA" NUMBER(2,0), 
	"SPERSON" NUMBER(10,0), 
	"CCOMISI" NUMBER, 
	"CTIPAGE" NUMBER(2,0), 
	"CACTIVO" NUMBER(3,0), 
	"CDOMICI" NUMBER, 
	"CBANCAR" VARCHAR2(50 BYTE), 
	"NCOLEGI" VARCHAR2(10 BYTE), 
	"FBAJAGE" DATE, 
	"CSOPREC" NUMBER(2,0), 
	"CMEDIOP" NUMBER(2,0), 
	"CCUACOA" NUMBER(1,0), 
	"TOBSERV" VARCHAR2(70 BYTE), 
	"NMESCOB" NUMBER(2,0), 
	"CRETLIQ" NUMBER(1,0), 
	"CPSEUDO" NUMBER(6,0), 
	"CCODCON" VARCHAR2(20 BYTE), 
	"CTIPBAN" NUMBER(3,0), 
	"CSOBRECOMISI" NUMBER, 
	"TALIAS" VARCHAR2(100 BYTE), 
	"CLIQUIDO" NUMBER(3,0), 
	"CCOMISI_INDIRECT" NUMBER, 
	"CTIPMED" NUMBER(3,0), 
	"TNOMCOM" VARCHAR2(200 BYTE), 
	"CDOMCOM" NUMBER(2,0), 
	"CTIPRETRIB" NUMBER(3,0), 
	"CMOTBAJA" NUMBER(3,0), 
	"CBLOQUEO" NUMBER(3,0), 
	"NREGDGS" VARCHAR2(100 BYTE), 
	"FINSDGS" DATE, 
	"CREBCONTDGS" NUMBER(3,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FUSUMOD" DATE, 
	"CENLACE" NUMBER DEFAULT NULL, 
	"CPREAVISO" NUMBER(1,0), 
	"COBLCCC" NUMBER(2,0), 
	"CLAVEINTER" VARCHAR2(10 BYTE), 
	"CDESCRIIVA" VARCHAR2(200 BYTE), 
	"DESCRICRETENC" VARCHAR2(200 BYTE), 
	"DESCRIFUENTE" VARCHAR2(100 BYTE), 
	"CDESCRIICA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."AGENTES"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CRETENC" IS 'Código de retención';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CTIPIVA" IS 'Código tipo de IVA';
   COMMENT ON COLUMN "AXIS"."AGENTES"."SPERSON" IS 'Identificador único de la Personas';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CCOMISI" IS 'Código comisión';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CTIPAGE" IS 'Tipo de agente.';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CACTIVO" IS 'Agente activo (VF:31)';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CDOMICI" IS 'Código del domicilio que utiliza';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CBANCAR" IS 'Cuenta domiciliación';
   COMMENT ON COLUMN "AXIS"."AGENTES"."NCOLEGI" IS 'Número de colegiado';
   COMMENT ON COLUMN "AXIS"."AGENTES"."FBAJAGE" IS 'Fecha baja del agente';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CSOPREC" IS 'Tipo de soporte de los recibos (null = papel)';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CCODCON" IS 'Código contable del agente';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CTIPBAN" IS 'Tipo de cuenta ( iban o cuenta bancaria). [tabla maestra: TIPOS_CUENTA]';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CSOBRECOMISI" IS 'Código sobrecomisión';
   COMMENT ON COLUMN "AXIS"."AGENTES"."TALIAS" IS 'Nombre corto del agente';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CLIQUIDO" IS 'Indica si el Intermediario tiene autorización para descontarse directamente las comisiones. V.F. 372';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CCOMISI_INDIRECT" IS 'Código comisión indirecta';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CTIPMED" IS 'Tipo de mediador (VF:1062)';
   COMMENT ON COLUMN "AXIS"."AGENTES"."TNOMCOM" IS 'Nombre comercial';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CDOMCOM" IS 'Dirección comercial del agente';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CTIPRETRIB" IS 'Tipo de retribución (VF:1063)';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CMOTBAJA" IS 'Motivo de baja agente (VF:1066)';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CBLOQUEO" IS 'Bloqueo agente  (VF:1067)';
   COMMENT ON COLUMN "AXIS"."AGENTES"."NREGDGS" IS 'Nº de registros DGS';
   COMMENT ON COLUMN "AXIS"."AGENTES"."FINSDGS" IS 'Fecha de inscripción DGS';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CREBCONTDGS" IS 'Contrato recibido: 0-No, 1-Si.';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CUSUALT" IS 'Código usuario alta del registro';
   COMMENT ON COLUMN "AXIS"."AGENTES"."FALTA" IS 'Fecha de alta del registro';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CUSUMOD" IS 'Código usuario modificación del registro';
   COMMENT ON COLUMN "AXIS"."AGENTES"."FUSUMOD" IS 'Fecha modificación del registro';
   COMMENT ON COLUMN "AXIS"."AGENTES"."CPREAVISO" IS 'Tiene preaviso (0.-No/1.-Si)';
   COMMENT ON COLUMN "AXIS"."AGENTES"."COBLCCC" IS 'Obligatoriedad domiciliación bancaria - Opcional. Check, por defecto aparece marcado';
   COMMENT ON TABLE "AXIS"."AGENTES"  IS 'Agentes - Elementos de la Red Comercial';
  GRANT UPDATE ON "AXIS"."AGENTES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGENTES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AGENTES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AGENTES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGENTES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AGENTES" TO "PROGRAMADORESCSI";
