--------------------------------------------------------
--  DDL for Table AGENTESCIA
--------------------------------------------------------

  CREATE TABLE "AXIS"."AGENTESCIA" 
   (	"CCOMPANI" NUMBER, 
	"CAGENTE" NUMBER, 
	"CAGECOMP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."AGENTESCIA"."CCOMPANI" IS 'Código compañia';
   COMMENT ON COLUMN "AXIS"."AGENTESCIA"."CAGENTE" IS 'Código agente';
   COMMENT ON COLUMN "AXIS"."AGENTESCIA"."CAGECOMP" IS 'Código agente compañia';
   COMMENT ON TABLE "AXIS"."AGENTESCIA"  IS 'Conversión códigos agentes compañía';
  GRANT UPDATE ON "AXIS"."AGENTESCIA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGENTESCIA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AGENTESCIA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AGENTESCIA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGENTESCIA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AGENTESCIA" TO "PROGRAMADORESCSI";
