--------------------------------------------------------
--  DDL for Table AGR_CONTRATOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."AGR_CONTRATOS" 
   (	"SCONTRA" NUMBER(6,0), 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CACTIVI" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0), 
	"NVERSIO" NUMBER(2,0), 
	"ILIMSUB" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."AGR_CONTRATOS"."CRAMO" IS 'Código ramo';
   COMMENT ON COLUMN "AXIS"."AGR_CONTRATOS"."CMODALI" IS 'Código modalidad';
   COMMENT ON COLUMN "AXIS"."AGR_CONTRATOS"."CCOLECT" IS 'Código de colectividad';
   COMMENT ON COLUMN "AXIS"."AGR_CONTRATOS"."CTIPSEG" IS 'Código tipo de seguro';
   COMMENT ON COLUMN "AXIS"."AGR_CONTRATOS"."CACTIVI" IS 'Código actividad del seguro';
   COMMENT ON COLUMN "AXIS"."AGR_CONTRATOS"."CGARANT" IS 'Código de garantía';
   COMMENT ON COLUMN "AXIS"."AGR_CONTRATOS"."NVERSIO" IS 'Número versión contrato reas.';
   COMMENT ON COLUMN "AXIS"."AGR_CONTRATOS"."ILIMSUB" IS 'Límite de subscripción';
  GRANT UPDATE ON "AXIS"."AGR_CONTRATOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGR_CONTRATOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AGR_CONTRATOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AGR_CONTRATOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AGR_CONTRATOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AGR_CONTRATOS" TO "PROGRAMADORESCSI";
