--------------------------------------------------------
--  DDL for Table ANUBENESPSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."ANUBENESPSEG" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"CGARANT" NUMBER(4,0), 
	"NMOVIMI" NUMBER(4,0), 
	"SPERSON" NUMBER(10,0), 
	"SPERSON_TIT" NUMBER(10,0), 
	"FINIBEN" DATE, 
	"FFINBEN" DATE, 
	"CTIPBEN" NUMBER(2,0), 
	"CPAREN" NUMBER(2,0), 
	"PPARTICIP" NUMBER(5,2), 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FMOVIMI" DATE, 
	"CTIPOCON" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ANUBENESPSEG"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente.';
   COMMENT ON COLUMN "AXIS"."ANUBENESPSEG"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."ANUBENESPSEG"."CGARANT" IS 'Código de garantía';
   COMMENT ON COLUMN "AXIS"."ANUBENESPSEG"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."ANUBENESPSEG"."SPERSON" IS 'Código de persona beneficiario';
   COMMENT ON COLUMN "AXIS"."ANUBENESPSEG"."SPERSON_TIT" IS 'Código de persona beneficiario titular';
   COMMENT ON COLUMN "AXIS"."ANUBENESPSEG"."FINIBEN" IS 'Fecha inicio beneficiario';
   COMMENT ON COLUMN "AXIS"."ANUBENESPSEG"."FFINBEN" IS 'Fecha fin beneficiario';
   COMMENT ON COLUMN "AXIS"."ANUBENESPSEG"."CTIPBEN" IS 'Código de tipo de beneficiario. Vf.:1053';
   COMMENT ON COLUMN "AXIS"."ANUBENESPSEG"."CPAREN" IS 'Código de parentesco del beneficiario. Vf.: 1054';
   COMMENT ON COLUMN "AXIS"."ANUBENESPSEG"."PPARTICIP" IS 'Porcentaje de participación';
   COMMENT ON COLUMN "AXIS"."ANUBENESPSEG"."CUSUARI" IS 'Código usuario modificación registro';
   COMMENT ON COLUMN "AXIS"."ANUBENESPSEG"."FMOVIMI" IS 'Fecha modificación registro    ';
   COMMENT ON COLUMN "AXIS"."ANUBENESPSEG"."CTIPOCON" IS 'Tipo de contingencia en la que se afecta el beneficiario (VF 8001024)';
   COMMENT ON TABLE "AXIS"."ANUBENESPSEG"  IS 'Tabla de beneficiarios especiales de la póliza';
  GRANT UPDATE ON "AXIS"."ANUBENESPSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUBENESPSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ANUBENESPSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ANUBENESPSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUBENESPSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ANUBENESPSEG" TO "PROGRAMADORESCSI";
