--------------------------------------------------------
--  DDL for Table ANUCLAUBENSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."ANUCLAUBENSEG" 
   (	"FINICLAU" DATE, 
	"SCLABEN" NUMBER(4,0), 
	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"FFINCLAU" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ANUCLAUBENSEG"."FINICLAU" IS 'Fecha inicio cláusula';
   COMMENT ON COLUMN "AXIS"."ANUCLAUBENSEG"."SCLABEN" IS 'Secuencia cláusula de beneficiario';
   COMMENT ON COLUMN "AXIS"."ANUCLAUBENSEG"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente.';
   COMMENT ON COLUMN "AXIS"."ANUCLAUBENSEG"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."ANUCLAUBENSEG"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."ANUCLAUBENSEG"."FFINCLAU" IS 'Fecha fin cláusula';
   COMMENT ON TABLE "AXIS"."ANUCLAUBENSEG"  IS 'Información clausulas beneficiarios, guardada antes de anular movimiento';
  GRANT UPDATE ON "AXIS"."ANUCLAUBENSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUCLAUBENSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ANUCLAUBENSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ANUCLAUBENSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUCLAUBENSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ANUCLAUBENSEG" TO "PROGRAMADORESCSI";
