--------------------------------------------------------
--  DDL for Table ANUDETGARANSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."ANUDETGARANSEG" 
   (	"CGARANT" NUMBER(4,0), 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"SSEGURO" NUMBER, 
	"FINIEFE" DATE, 
	"NDETGAR" NUMBER(4,0), 
	"FEFECTO" DATE, 
	"FVENCIM" DATE, 
	"NDURCOB" NUMBER(3,0), 
	"CTARIFA" NUMBER(2,0), 
	"PINTTEC" NUMBER(6,2), 
	"FTARIFA" DATE, 
	"CREVALI" NUMBER(2,0), 
	"PREVALI" NUMBER(8,5), 
	"IREVALI" NUMBER, 
	"ICAPITAL" NUMBER, 
	"IPRIANU" NUMBER, 
	"PRECARG" NUMBER(8,4), 
	"IRECARG" NUMBER, 
	"CPARBEN" VARCHAR2(2 BYTE), 
	"CPREPOST" NUMBER(1,0), 
	"FFINCOB" DATE, 
	"IPRITAR" NUMBER, 
	"PROVMAT0" NUMBER, 
	"FPROVMAT0" DATE, 
	"PROVMAT1" NUMBER, 
	"FPROVMAT1" DATE, 
	"PINTMIN" NUMBER(6,2), 
	"PDTOCOM" NUMBER(6,2), 
	"IDTOCOM" NUMBER, 
	"CTARMAN" NUMBER(2,0), 
	"IPRIPUR" NUMBER, 
	"IPRIINV" NUMBER, 
	"ITARREA" NUMBER(24,12), 
	"CAGENTE" NUMBER, 
	"CUNICA" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."CGARANT" IS 'Código Garantia';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."SSEGURO" IS 'Número de secuencia de seguro';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."FINIEFE" IS 'Fecha inicio de efecto';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."NDETGAR" IS 'Número de detalle de garantia';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."FVENCIM" IS 'Fecha vencimiento garantia';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."CREVALI" IS 'Código Revalorización VF 62';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."PREVALI" IS 'Porcentaje de revalorizacion';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."IREVALI" IS 'Importe de revalorización';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."ICAPITAL" IS 'Importe garantía';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."IPRIANU" IS 'Importe prima manual';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."PRECARG" IS 'Porcentaje de recargo';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."IRECARG" IS 'Importe del recargo';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."FFINCOB" IS 'Fecha Fin de cobro de la prima';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."IPRITAR" IS 'Importe tarifa';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."PROVMAT0" IS 'Provisión T0';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."FPROVMAT0" IS 'Fecha provisión T0';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."PROVMAT1" IS 'Provisión T1';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."FPROVMAT1" IS 'Fecha provisión T1';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."PINTMIN" IS 'Interés mínimo garantizado';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."PDTOCOM" IS 'Porcentaje descuento comercial';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."IDTOCOM" IS 'Importe descuento comercial';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."CTARMAN" IS 'Tipo de tarifa manual';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."IPRIPUR" IS 'Importe prima pura';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."ITARREA" IS 'Tarifa reaseguro';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."CAGENTE" IS 'Agente vigente asociado al detalle de garantía';
   COMMENT ON COLUMN "AXIS"."ANUDETGARANSEG"."CUNICA" IS 'Indicador de forma de pago única (Única/Extra)';
   COMMENT ON TABLE "AXIS"."ANUDETGARANSEG"  IS 'Detalle Garantias';
  GRANT UPDATE ON "AXIS"."ANUDETGARANSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUDETGARANSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ANUDETGARANSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ANUDETGARANSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUDETGARANSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ANUDETGARANSEG" TO "PROGRAMADORESCSI";
