--------------------------------------------------------
--  DDL for Table ANUDETMOVSEGURO
--------------------------------------------------------

  CREATE TABLE "AXIS"."ANUDETMOVSEGURO" 
   (	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER(4,0), 
	"CMOTMOV" NUMBER(3,0), 
	"NRIESGO" NUMBER(6,0), 
	"CGARANT" NUMBER, 
	"TVALORA" VARCHAR2(1000 BYTE), 
	"TVALORD" VARCHAR2(1000 BYTE), 
	"CPREGUN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ANUDETMOVSEGURO"."SSEGURO" IS 'Id del estseguro';
   COMMENT ON COLUMN "AXIS"."ANUDETMOVSEGURO"."CMOTMOV" IS 'Código del motivo de movimiento';
   COMMENT ON COLUMN "AXIS"."ANUDETMOVSEGURO"."NRIESGO" IS 'Id.del riesgo';
   COMMENT ON COLUMN "AXIS"."ANUDETMOVSEGURO"."CGARANT" IS 'Código de la garantia';
   COMMENT ON COLUMN "AXIS"."ANUDETMOVSEGURO"."TVALORA" IS 'Valor antes del suplemento';
   COMMENT ON COLUMN "AXIS"."ANUDETMOVSEGURO"."TVALORD" IS 'Valor despues del suplemento';
   COMMENT ON COLUMN "AXIS"."ANUDETMOVSEGURO"."CPREGUN" IS 'Código de la pregunta';
   COMMENT ON TABLE "AXIS"."ANUDETMOVSEGURO"  IS 'Información detalle movimiento, guardada antes de anular movimiento';
  GRANT UPDATE ON "AXIS"."ANUDETMOVSEGURO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUDETMOVSEGURO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ANUDETMOVSEGURO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ANUDETMOVSEGURO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUDETMOVSEGURO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ANUDETMOVSEGURO" TO "PROGRAMADORESCSI";
