--------------------------------------------------------
--  DDL for Table ANUGARANSEG_SBPRI
--------------------------------------------------------

  CREATE TABLE "AXIS"."ANUGARANSEG_SBPRI" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"CGARANT" NUMBER(4,0), 
	"NMOVIMI" NUMBER(4,0), 
	"FINIEFE" DATE, 
	"NORDEN" NUMBER(3,0), 
	"CTIPSBR" NUMBER(2,0), 
	"CCALSBR" NUMBER(2,0), 
	"PVALOR" NUMBER(6,2), 
	"NCOMISI" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ANUGARANSEG_SBPRI"."SSEGURO" IS 'Código Seguro';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEG_SBPRI"."NRIESGO" IS 'Número Riesgo';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEG_SBPRI"."CGARANT" IS 'Código Garantía';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEG_SBPRI"."NMOVIMI" IS 'Número Movimiento';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEG_SBPRI"."FINIEFE" IS 'Fecha inicio efecto';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEG_SBPRI"."NORDEN" IS 'Número Orden';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEG_SBPRI"."CTIPSBR" IS 'Tipo Sobreprima, valores posibles de la tabla de valores fijos: 838.';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEG_SBPRI"."CCALSBR" IS 'Tipo de Cálculo Sobreprima, valores posibles de la tabla valores fijos: 839.';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEG_SBPRI"."PVALOR" IS 'Valor de la sobreprima';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEG_SBPRI"."NCOMISI" IS 'Indicador sobre que valor se aplica el porcentaje de gastos. VF=307';
   COMMENT ON TABLE "AXIS"."ANUGARANSEG_SBPRI"  IS 'Garantías Seguros Gastos';
  GRANT UPDATE ON "AXIS"."ANUGARANSEG_SBPRI" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUGARANSEG_SBPRI" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ANUGARANSEG_SBPRI" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ANUGARANSEG_SBPRI" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUGARANSEG_SBPRI" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ANUGARANSEG_SBPRI" TO "PROGRAMADORESCSI";
