--------------------------------------------------------
--  DDL for Table ANUGARANSEGGAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."ANUGARANSEGGAS" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"CGARANT" NUMBER(4,0), 
	"NMOVIMI" NUMBER(4,0), 
	"FINIEFE" DATE, 
	"CGASTOS" NUMBER(2,0), 
	"PVALOR" NUMBER(5,2), 
	"PVALRES" NUMBER(5,2), 
	"NPRIMA" NUMBER(1,0), 
	"CMATCH" NUMBER(1,0), 
	"TDESMAT" VARCHAR2(75 BYTE), 
	"PINTFIN" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ANUGARANSEGGAS"."SSEGURO" IS 'Código Seguro';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEGGAS"."NRIESGO" IS 'Número Riesgo';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEGGAS"."CGARANT" IS 'Código Garantía';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEGGAS"."NMOVIMI" IS 'Número Movimiento';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEGGAS"."FINIEFE" IS 'Fecha inicio efecto';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEGGAS"."CGASTOS" IS 'Código Gasto';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEGGAS"."PVALOR" IS 'Porcentaje Gastos - Primera Anualidad';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEGGAS"."PVALRES" IS 'Porcentaje Gastos - Resto Anualidades';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEGGAS"."NPRIMA" IS 'Indicador sobre que valor se aplica el porcentaje de gastos. VF=837';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEGGAS"."CMATCH" IS 'Indicador de si se permite maching';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEGGAS"."TDESMAT" IS 'Descripción de la inversión';
   COMMENT ON COLUMN "AXIS"."ANUGARANSEGGAS"."PINTFIN" IS 'Porcentaje de Interés Financiero de la Inversión';
   COMMENT ON TABLE "AXIS"."ANUGARANSEGGAS"  IS 'Garantías Seguros Gastos';
  GRANT UPDATE ON "AXIS"."ANUGARANSEGGAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUGARANSEGGAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ANUGARANSEGGAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ANUGARANSEGGAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUGARANSEGGAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ANUGARANSEGGAS" TO "PROGRAMADORESCSI";
