--------------------------------------------------------
--  DDL for Table ANUINTERTECSEGGAR
--------------------------------------------------------

  CREATE TABLE "AXIS"."ANUINTERTECSEGGAR" 
   (	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER(6,0), 
	"CGARANT" NUMBER(4,0), 
	"CTIPO" NUMBER(1,0), 
	"NRIESGO" NUMBER(6,0), 
	"FEFEMOV" DATE, 
	"PINTTEC" NUMBER(12,8), 
	"NDESDE" NUMBER, 
	"NHASTA" NUMBER, 
	"NINNTEC" NUMBER(7,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ANUINTERTECSEGGAR"."SSEGURO" IS 'IDENTIFICADOR ÚNICO DEL SEGURO';
   COMMENT ON COLUMN "AXIS"."ANUINTERTECSEGGAR"."NMOVIMI" IS 'NÚMERO DE MOVIMIENTO DE SEGURO';
   COMMENT ON COLUMN "AXIS"."ANUINTERTECSEGGAR"."CGARANT" IS 'IDENTIFICADOR ÚNICO DE LA GARANTÍA';
   COMMENT ON COLUMN "AXIS"."ANUINTERTECSEGGAR"."CTIPO" IS 'CÓDIGO TIPO DE INTERÉS VF.848';
   COMMENT ON COLUMN "AXIS"."ANUINTERTECSEGGAR"."NRIESGO" IS 'NÚMERO DE RIESGO';
   COMMENT ON COLUMN "AXIS"."ANUINTERTECSEGGAR"."PINTTEC" IS 'PORCENTAJE DE INTERÉS TÉCNICO.SOLO ESTARÁ INFORMADO SI ES DIFERENTE AL DEL PRODUCTO';
   COMMENT ON COLUMN "AXIS"."ANUINTERTECSEGGAR"."NDESDE" IS 'Inicio tramo';
   COMMENT ON COLUMN "AXIS"."ANUINTERTECSEGGAR"."NHASTA" IS 'Fin tramo';
   COMMENT ON COLUMN "AXIS"."ANUINTERTECSEGGAR"."NINNTEC" IS 'Porcentaje de interés parametrizado en el momento de la inserción.';
   COMMENT ON TABLE "AXIS"."ANUINTERTECSEGGAR"  IS 'INTERÉS TÉCNICO ASOCIADO A LA GARANTÍA DE LA PROMOCIÓN EN LA PÓLIZA';
  GRANT UPDATE ON "AXIS"."ANUINTERTECSEGGAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUINTERTECSEGGAR" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ANUINTERTECSEGGAR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ANUINTERTECSEGGAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUINTERTECSEGGAR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ANUINTERTECSEGGAR" TO "PROGRAMADORESCSI";
