--------------------------------------------------------
--  DDL for Table ANUPLANRENTASIRREG
--------------------------------------------------------

  CREATE TABLE "AXIS"."ANUPLANRENTASIRREG" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"MES" NUMBER(2,0), 
	"ANYO" NUMBER(4,0), 
	"IMPORTE" NUMBER(14,3), 
	"ESTADO" NUMBER, 
	"SRECREN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ANUPLANRENTASIRREG"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente.';
   COMMENT ON COLUMN "AXIS"."ANUPLANRENTASIRREG"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."ANUPLANRENTASIRREG"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."ANUPLANRENTASIRREG"."MES" IS 'Mes de la renta irregular';
   COMMENT ON COLUMN "AXIS"."ANUPLANRENTASIRREG"."ANYO" IS 'Año de la renta irregular';
   COMMENT ON COLUMN "AXIS"."ANUPLANRENTASIRREG"."IMPORTE" IS 'Importe de la renta irregular';
   COMMENT ON COLUMN "AXIS"."ANUPLANRENTASIRREG"."ESTADO" IS 'Estado de la renta';
   COMMENT ON COLUMN "AXIS"."ANUPLANRENTASIRREG"."SRECREN" IS 'Número de pago';
  GRANT UPDATE ON "AXIS"."ANUPLANRENTASIRREG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUPLANRENTASIRREG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ANUPLANRENTASIRREG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ANUPLANRENTASIRREG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ANUPLANRENTASIRREG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ANUPLANRENTASIRREG" TO "PROGRAMADORESCSI";
