--------------------------------------------------------
--  DDL for Table ASEGURADORAS_PLANES
--------------------------------------------------------

  CREATE TABLE "AXIS"."ASEGURADORAS_PLANES" 
   (	"CCODASEG" VARCHAR2(15 BYTE), 
	"CCODIGO" NUMBER(7,0), 
	"TNOMBRE" VARCHAR2(100 BYTE), 
	"CODDGS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ASEGURADORAS_PLANES"."CCODASEG" IS 'Código Aseguradora';
   COMMENT ON COLUMN "AXIS"."ASEGURADORAS_PLANES"."CCODIGO" IS 'Código del Plan P.';
   COMMENT ON COLUMN "AXIS"."ASEGURADORAS_PLANES"."TNOMBRE" IS 'Nombre del Plan P.';
   COMMENT ON COLUMN "AXIS"."ASEGURADORAS_PLANES"."CODDGS" IS 'Código de la DGS';
  GRANT UPDATE ON "AXIS"."ASEGURADORAS_PLANES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ASEGURADORAS_PLANES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ASEGURADORAS_PLANES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ASEGURADORAS_PLANES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ASEGURADORAS_PLANES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ASEGURADORAS_PLANES" TO "PROGRAMADORESCSI";
