--------------------------------------------------------
--  DDL for Table ASEGURADOSMES
--------------------------------------------------------

  CREATE TABLE "AXIS"."ASEGURADOSMES" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER, 
	"NMOVIMI" NUMBER, 
	"NMES" NUMBER(2,0), 
	"NANYO" NUMBER(4,0) DEFAULT 0, 
	"FREGUL" DATE, 
	"NASEG" NUMBER, 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ASEGURADOSMES"."SSEGURO" IS 'Identificador de poliza (SEGUROS)';
   COMMENT ON COLUMN "AXIS"."ASEGURADOSMES"."NRIESGO" IS 'Nro de riesgo (RIESGOS)';
   COMMENT ON COLUMN "AXIS"."ASEGURADOSMES"."NMOVIMI" IS 'Nro de movimiento (MOVSEGURO)';
   COMMENT ON COLUMN "AXIS"."ASEGURADOSMES"."NMES" IS 'Mes regularización  (Defecto 0)';
   COMMENT ON COLUMN "AXIS"."ASEGURADOSMES"."NANYO" IS 'Año regularización  (Defecto 0)';
   COMMENT ON COLUMN "AXIS"."ASEGURADOSMES"."FREGUL" IS 'Fecha de Regularización';
   COMMENT ON COLUMN "AXIS"."ASEGURADOSMES"."NASEG" IS 'Nro asegurados en el mes (Defecto 0)';
   COMMENT ON COLUMN "AXIS"."ASEGURADOSMES"."FALTA" IS 'Fecha Alta';
   COMMENT ON COLUMN "AXIS"."ASEGURADOSMES"."CUSUALT" IS 'Usuario Alta';
   COMMENT ON COLUMN "AXIS"."ASEGURADOSMES"."CUSUMOD" IS 'Usuario Modificación';
   COMMENT ON COLUMN "AXIS"."ASEGURADOSMES"."FMODIFI" IS 'Fecha Modificación';
   COMMENT ON TABLE "AXIS"."ASEGURADOSMES"  IS 'Asegurados(innominados) por mes en la regularización';
  GRANT UPDATE ON "AXIS"."ASEGURADOSMES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ASEGURADOSMES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ASEGURADOSMES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ASEGURADOSMES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ASEGURADOSMES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ASEGURADOSMES" TO "PROGRAMADORESCSI";
