--------------------------------------------------------
--  DDL for Table AUT_PROD_PESOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."AUT_PROD_PESOS" 
   (	"SPRODUC" NUMBER(6,0), 
	"CPESO" NUMBER(3,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TPESO" VARCHAR2(100 BYTE), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."AUT_PROD_PESOS"."SPRODUC" IS 'Secuencia del producto';
   COMMENT ON COLUMN "AXIS"."AUT_PROD_PESOS"."CPESO" IS 'Código de Peso';
   COMMENT ON COLUMN "AXIS"."AUT_PROD_PESOS"."CIDIOMA" IS 'Código de Idioma';
   COMMENT ON COLUMN "AXIS"."AUT_PROD_PESOS"."TPESO" IS 'Descripción Peso';
   COMMENT ON COLUMN "AXIS"."AUT_PROD_PESOS"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."AUT_PROD_PESOS"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."AUT_PROD_PESOS"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."AUT_PROD_PESOS"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON TABLE "AXIS"."AUT_PROD_PESOS"  IS 'Peso Autos';
  GRANT UPDATE ON "AXIS"."AUT_PROD_PESOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AUT_PROD_PESOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AUT_PROD_PESOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AUT_PROD_PESOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AUT_PROD_PESOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AUT_PROD_PESOS" TO "PROGRAMADORESCSI";
