--------------------------------------------------------
--  DDL for Table AUT_DESTIPVEH
--------------------------------------------------------

  CREATE TABLE "AXIS"."AUT_DESTIPVEH" 
   (	"CTIPVEH" VARCHAR2(3 BYTE), 
	"CIDIOMA" NUMBER(2,0), 
	"TTIPVEH" VARCHAR2(100 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"FBAJA" DATE, 
	"CEMPRES" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."AUT_DESTIPVEH"."CTIPVEH" IS 'Código del tipo de vehículo';
   COMMENT ON COLUMN "AXIS"."AUT_DESTIPVEH"."CIDIOMA" IS 'Código del idioma';
   COMMENT ON COLUMN "AXIS"."AUT_DESTIPVEH"."TTIPVEH" IS 'Descripción del tipo de vehículo';
   COMMENT ON COLUMN "AXIS"."AUT_DESTIPVEH"."CUSUALT" IS 'Usuario que da de alta el registro';
   COMMENT ON COLUMN "AXIS"."AUT_DESTIPVEH"."FALTA" IS 'Fecha de alta del registro';
   COMMENT ON COLUMN "AXIS"."AUT_DESTIPVEH"."CUSUMOD" IS 'Usuario de la última modificación del registro';
   COMMENT ON COLUMN "AXIS"."AUT_DESTIPVEH"."FMODIFI" IS 'Fecha de la última modificación del registro';
   COMMENT ON COLUMN "AXIS"."AUT_DESTIPVEH"."FBAJA" IS 'Fecha de baja del registro';
   COMMENT ON COLUMN "AXIS"."AUT_DESTIPVEH"."CEMPRES" IS 'Codigo de empresa';
  GRANT UPDATE ON "AXIS"."AUT_DESTIPVEH" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AUT_DESTIPVEH" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AUT_DESTIPVEH" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AUT_DESTIPVEH" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AUT_DESTIPVEH" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AUT_DESTIPVEH" TO "PROGRAMADORESCSI";
