--------------------------------------------------------
--  DDL for Table AUT_CODTIPVEH
--------------------------------------------------------

  CREATE TABLE "AXIS"."AUT_CODTIPVEH" 
   (	"CTIPVEH" VARCHAR2(3 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"FBAJA" DATE, 
	"NCATEGO" NUMBER(3,0), 
	"CEMPRES" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."AUT_CODTIPVEH"."CTIPVEH" IS 'Código del tipo de vehículo';
   COMMENT ON COLUMN "AXIS"."AUT_CODTIPVEH"."CUSUALT" IS 'Usuario que da de alta el registro';
   COMMENT ON COLUMN "AXIS"."AUT_CODTIPVEH"."FALTA" IS 'Fecha de alta del registro';
   COMMENT ON COLUMN "AXIS"."AUT_CODTIPVEH"."CUSUMOD" IS 'Usuario de la última modificación del registro';
   COMMENT ON COLUMN "AXIS"."AUT_CODTIPVEH"."FMODIFI" IS 'Fecha de la última modificación del registro';
   COMMENT ON COLUMN "AXIS"."AUT_CODTIPVEH"."FBAJA" IS 'Fecha de baja del registro';
   COMMENT ON COLUMN "AXIS"."AUT_CODTIPVEH"."NCATEGO" IS 'Categoría del vehículo. Valor fijo = 294';
   COMMENT ON COLUMN "AXIS"."AUT_CODTIPVEH"."CEMPRES" IS 'Codigo de empresa';
  GRANT UPDATE ON "AXIS"."AUT_CODTIPVEH" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AUT_CODTIPVEH" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AUT_CODTIPVEH" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AUT_CODTIPVEH" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AUT_CODTIPVEH" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AUT_CODTIPVEH" TO "PROGRAMADORESCSI";
