--------------------------------------------------------
--  DDL for Table AUT_USOSUBUSO_PROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."AUT_USOSUBUSO_PROD" 
   (	"CCLAVEH" VARCHAR2(5 BYTE), 
	"CTIPVEH" VARCHAR2(3 BYTE), 
	"CUSO" VARCHAR2(2 BYTE), 
	"CSUBUSO" VARCHAR2(2 BYTE), 
	"SPRODUC" NUMBER(6,0), 
	"CACTIVI" NUMBER(4,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"FBAJA" DATE, 
	"CEMPRES" NUMBER(2,0), 
	"CRETEN" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."AUT_USOSUBUSO_PROD"."CCLAVEH" IS 'Código de la clase';
   COMMENT ON COLUMN "AXIS"."AUT_USOSUBUSO_PROD"."CTIPVEH" IS 'Código del tipo de vehículo';
   COMMENT ON COLUMN "AXIS"."AUT_USOSUBUSO_PROD"."CUSO" IS 'Código del uso';
   COMMENT ON COLUMN "AXIS"."AUT_USOSUBUSO_PROD"."CSUBUSO" IS 'Código del sub-uso';
   COMMENT ON COLUMN "AXIS"."AUT_USOSUBUSO_PROD"."SPRODUC" IS 'Código del producto';
   COMMENT ON COLUMN "AXIS"."AUT_USOSUBUSO_PROD"."CACTIVI" IS 'Código de la actividad';
   COMMENT ON COLUMN "AXIS"."AUT_USOSUBUSO_PROD"."CUSUALT" IS 'Usuario que da de alta el registro';
   COMMENT ON COLUMN "AXIS"."AUT_USOSUBUSO_PROD"."FALTA" IS 'Fecha de alta del registro';
   COMMENT ON COLUMN "AXIS"."AUT_USOSUBUSO_PROD"."CUSUMOD" IS 'Usuario de la última modificación del registro';
   COMMENT ON COLUMN "AXIS"."AUT_USOSUBUSO_PROD"."FMODIFI" IS 'Fecha de la última modificación del registro';
   COMMENT ON COLUMN "AXIS"."AUT_USOSUBUSO_PROD"."FBAJA" IS 'Fecha de baja del registro';
   COMMENT ON COLUMN "AXIS"."AUT_USOSUBUSO_PROD"."CEMPRES" IS 'Codigo de empresa';
   COMMENT ON COLUMN "AXIS"."AUT_USOSUBUSO_PROD"."CRETEN" IS 'Indica si se retiene la póliza al emitir (v.f. 8000915)';
  GRANT UPDATE ON "AXIS"."AUT_USOSUBUSO_PROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AUT_USOSUBUSO_PROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AUT_USOSUBUSO_PROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AUT_USOSUBUSO_PROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AUT_USOSUBUSO_PROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AUT_USOSUBUSO_PROD" TO "PROGRAMADORESCSI";
