--------------------------------------------------------
--  DDL for Table AUTOMATA
--------------------------------------------------------

  CREATE TABLE "AXIS"."AUTOMATA" 
   (	"MENSAJE" VARCHAR2(10 BYTE), 
	"SEGMENTO" VARCHAR2(10 BYTE), 
	"CAMINO" NUMBER(3,0), 
	"PREVIA" VARCHAR2(30 BYTE), 
	"CONDICION" VARCHAR2(30 BYTE), 
	"ORIGEN" VARCHAR2(10 BYTE), 
	"DESTINO" VARCHAR2(10 BYTE), 
	"COND_SALTO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."AUTOMATA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AUTOMATA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."AUTOMATA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."AUTOMATA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."AUTOMATA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."AUTOMATA" TO "PROGRAMADORESCSI";
