--------------------------------------------------------
--  DDL for Table BENEFPRESTAPLAN
--------------------------------------------------------

  CREATE TABLE "AXIS"."BENEFPRESTAPLAN" 
   (	"SPRESTAPLAN" NUMBER(6,0), 
	"SPERSON" NUMBER(10,0), 
	"NPARPLA" NUMBER(25,6), 
	"CTIPCAP" NUMBER(1,0), 
	"NPORCEN" NUMBER, 
	"NPARFIN" NUMBER(25,6), 
	"NPARPOS2006" NUMBER(25,6), 
	"NPARANT2007" NUMBER(25,6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."BENEFPRESTAPLAN"."SPRESTAPLAN" IS 'Id prestación';
   COMMENT ON COLUMN "AXIS"."BENEFPRESTAPLAN"."SPERSON" IS 'Persona';
   COMMENT ON COLUMN "AXIS"."BENEFPRESTAPLAN"."NPARPLA" IS 'Participaciones a cobrar';
   COMMENT ON COLUMN "AXIS"."BENEFPRESTAPLAN"."CTIPCAP" IS 'Tipo de capital seleccionado';
   COMMENT ON COLUMN "AXIS"."BENEFPRESTAPLAN"."NPORCEN" IS 'Portentaje de Rentas';
   COMMENT ON COLUMN "AXIS"."BENEFPRESTAPLAN"."NPARFIN" IS 'PArticipaciones finales';
   COMMENT ON COLUMN "AXIS"."BENEFPRESTAPLAN"."NPARPOS2006" IS 'Participaciones de aportaciones posteriores a 2006';
   COMMENT ON COLUMN "AXIS"."BENEFPRESTAPLAN"."NPARANT2007" IS 'Participaciones de aportaciones anteriores a 2007';
  GRANT UPDATE ON "AXIS"."BENEFPRESTAPLAN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."BENEFPRESTAPLAN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."BENEFPRESTAPLAN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."BENEFPRESTAPLAN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."BENEFPRESTAPLAN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."BENEFPRESTAPLAN" TO "PROGRAMADORESCSI";
