--------------------------------------------------------
--  DDL for Table BF_DESGRUP
--------------------------------------------------------

  CREATE TABLE "AXIS"."BF_DESGRUP" 
   (	"CEMPRES" NUMBER(6,0), 
	"CGRUP" NUMBER(6,0), 
	"CVERSION" NUMBER(6,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TGRUP" VARCHAR2(200 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."BF_DESGRUP"."CEMPRES" IS 'Código de Empresa';
   COMMENT ON COLUMN "AXIS"."BF_DESGRUP"."CGRUP" IS 'Código de Grupo de Bonus/Franquícias';
   COMMENT ON COLUMN "AXIS"."BF_DESGRUP"."CVERSION" IS 'Código de Versión';
   COMMENT ON COLUMN "AXIS"."BF_DESGRUP"."CIDIOMA" IS 'Código del Idioma';
   COMMENT ON COLUMN "AXIS"."BF_DESGRUP"."TGRUP" IS 'Descripción del Grupo de Bonus/Franquícias';
   COMMENT ON COLUMN "AXIS"."BF_DESGRUP"."CUSUALT" IS 'Usuario creación';
   COMMENT ON COLUMN "AXIS"."BF_DESGRUP"."FALTA" IS 'Fecha creación';
   COMMENT ON COLUMN "AXIS"."BF_DESGRUP"."CUSUMOD" IS 'Usuario modificación';
   COMMENT ON COLUMN "AXIS"."BF_DESGRUP"."FMODIFI" IS 'Fecha modificación';
   COMMENT ON TABLE "AXIS"."BF_DESGRUP"  IS 'Descripción de los Grupos de Bonus/Franquícias';
  GRANT UPDATE ON "AXIS"."BF_DESGRUP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."BF_DESGRUP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."BF_DESGRUP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."BF_DESGRUP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."BF_DESGRUP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."BF_DESGRUP" TO "PROGRAMADORESCSI";
