--------------------------------------------------------
--  DDL for Table BF_LISTLIBRE
--------------------------------------------------------

  CREATE TABLE "AXIS"."BF_LISTLIBRE" 
   (	"CEMPRES" NUMBER(6,0), 
	"ID_LISTLIBRE" NUMBER(6,0), 
	"CVALOR" NUMBER(8,0), 
	"CATRIBU" NUMBER(3,0), 
	"ID_LISTLIBRE_2" NUMBER(6,0), 
	"ID_LISTLIBRE_MIN" NUMBER(6,0), 
	"ID_LISTLIBRE_MAX" NUMBER(6,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."BF_LISTLIBRE"."CEMPRES" IS 'Código de Empresa';
   COMMENT ON COLUMN "AXIS"."BF_LISTLIBRE"."ID_LISTLIBRE" IS 'Código de lista para CVALOR1';
   COMMENT ON COLUMN "AXIS"."BF_LISTLIBRE"."CVALOR" IS 'Código de VALORES';
   COMMENT ON COLUMN "AXIS"."BF_LISTLIBRE"."CATRIBU" IS 'Código de ATRIBUTO de DETVALORES a mostrar';
   COMMENT ON COLUMN "AXIS"."BF_LISTLIBRE"."ID_LISTLIBRE_2" IS 'Código de lista para CVALOR2';
   COMMENT ON COLUMN "AXIS"."BF_LISTLIBRE"."ID_LISTLIBRE_MIN" IS 'Código de lista para CIMPMIN';
   COMMENT ON COLUMN "AXIS"."BF_LISTLIBRE"."ID_LISTLIBRE_MAX" IS 'Código de lista para CIMPMAX';
   COMMENT ON COLUMN "AXIS"."BF_LISTLIBRE"."CUSUALT" IS 'Usu alta';
   COMMENT ON COLUMN "AXIS"."BF_LISTLIBRE"."FALTA" IS 'Data alta';
   COMMENT ON COLUMN "AXIS"."BF_LISTLIBRE"."CUSUMOD" IS 'Usu mod';
   COMMENT ON COLUMN "AXIS"."BF_LISTLIBRE"."FMODIFI" IS 'Data mod';
   COMMENT ON TABLE "AXIS"."BF_LISTLIBRE"  IS 'Identificador de código de lista de valores a mostrar (LIBRES)';
  GRANT UPDATE ON "AXIS"."BF_LISTLIBRE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."BF_LISTLIBRE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."BF_LISTLIBRE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."BF_LISTLIBRE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."BF_LISTLIBRE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."BF_LISTLIBRE" TO "PROGRAMADORESCSI";
