--------------------------------------------------------
--  DDL for Table BF_VERSIONGRUP
--------------------------------------------------------

  CREATE TABLE "AXIS"."BF_VERSIONGRUP" 
   (	"CEMPRES" NUMBER(5,0), 
	"CGRUP" NUMBER(6,0), 
	"CVERSION" NUMBER(6,0), 
	"FDESDE" DATE, 
	"FHASTA" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."BF_VERSIONGRUP"."CEMPRES" IS 'Código de Empresa';
   COMMENT ON COLUMN "AXIS"."BF_VERSIONGRUP"."CGRUP" IS 'Código de Grupo de Bonus/Franquícias';
   COMMENT ON COLUMN "AXIS"."BF_VERSIONGRUP"."CVERSION" IS 'Código de Versión';
   COMMENT ON COLUMN "AXIS"."BF_VERSIONGRUP"."CUSUALT" IS 'Usuario creación';
   COMMENT ON COLUMN "AXIS"."BF_VERSIONGRUP"."FALTA" IS 'Fecha creación';
   COMMENT ON COLUMN "AXIS"."BF_VERSIONGRUP"."CUSUMOD" IS 'Usuario modificación';
   COMMENT ON COLUMN "AXIS"."BF_VERSIONGRUP"."FMODIFI" IS 'Fecha modificación';
   COMMENT ON TABLE "AXIS"."BF_VERSIONGRUP"  IS 'Versiones Grupo de Bonus/Franquícias';
  GRANT UPDATE ON "AXIS"."BF_VERSIONGRUP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."BF_VERSIONGRUP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."BF_VERSIONGRUP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."BF_VERSIONGRUP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."BF_VERSIONGRUP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."BF_VERSIONGRUP" TO "PROGRAMADORESCSI";
