--------------------------------------------------------
--  DDL for Table BONIFICAPROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."BONIFICAPROD" 
   (	"SPRODUC" NUMBER(6,0), 
	"NANUDES" NUMBER(3,0), 
	"NANUHAS" NUMBER(3,0), 
	"PBONIFI" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."BONIFICAPROD"."SPRODUC" IS 'Código de producto ';
   COMMENT ON COLUMN "AXIS"."BONIFICAPROD"."NANUDES" IS 'Desde la anualidad ';
   COMMENT ON COLUMN "AXIS"."BONIFICAPROD"."NANUHAS" IS 'Hasta la anualidad ';
   COMMENT ON COLUMN "AXIS"."BONIFICAPROD"."PBONIFI" IS 'Porcentaje de bonificación ';
   COMMENT ON TABLE "AXIS"."BONIFICAPROD"  IS 'Porcentajes de bonificación por producto';
  GRANT UPDATE ON "AXIS"."BONIFICAPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."BONIFICAPROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."BONIFICAPROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."BONIFICAPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."BONIFICAPROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."BONIFICAPROD" TO "PROGRAMADORESCSI";
