--------------------------------------------------------
--  DDL for Table CALCOMISION
--------------------------------------------------------

  CREATE TABLE "AXIS"."CALCOMISION" 
   (	"CCOMISI" NUMBER, 
	"CCONCEPT" NUMBER(3,0), 
	"CCOMINDT" NUMBER(1,0), 
	"CCOMDEVN" NUMBER(1,0), 
	"CTIPCOMI" NUMBER(3,0), 
	"CAGTECOB" NUMBER(1,0), 
	"CCONDEPT" NUMBER(3,0), 
	"COPNMESE" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."CALCOMISION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CALCOMISION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CALCOMISION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CALCOMISION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CALCOMISION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CALCOMISION" TO "PROGRAMADORESCSI";
