--------------------------------------------------------
--  DDL for Table CAMPSALUT
--------------------------------------------------------

  CREATE TABLE "AXIS"."CAMPSALUT" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER, 
	"NEMPLEADO" NUMBER, 
	"IIMPORT" NUMBER, 
	"FPAG" DATE, 
	"FALTARISC" DATE, 
	"FANULARISC" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CAMPSALUT"."SSEGURO" IS 'Número de seguro';
   COMMENT ON COLUMN "AXIS"."CAMPSALUT"."NRIESGO" IS 'Número de asegurado de la poliza';
   COMMENT ON COLUMN "AXIS"."CAMPSALUT"."NEMPLEADO" IS 'Numero de empleado que actua como agente';
   COMMENT ON COLUMN "AXIS"."CAMPSALUT"."IIMPORT" IS 'Importe de la poliza';
   COMMENT ON COLUMN "AXIS"."CAMPSALUT"."FPAG" IS 'Fecha de contrato póliza';
   COMMENT ON COLUMN "AXIS"."CAMPSALUT"."FALTARISC" IS 'Data d''alta del risc';
   COMMENT ON TABLE "AXIS"."CAMPSALUT"  IS 'Incentivo para empleados de polizas Salud';
  GRANT UPDATE ON "AXIS"."CAMPSALUT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CAMPSALUT" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CAMPSALUT" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CAMPSALUT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CAMPSALUT" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CAMPSALUT" TO "PROGRAMADORESCSI";
