--------------------------------------------------------
--  DDL for Table CAP_CARREGA_COL
--------------------------------------------------------

  CREATE TABLE "AXIS"."CAP_CARREGA_COL" 
   (	"SPROCES" NUMBER, 
	"TNOMFITX" VARCHAR2(30 BYTE), 
	"PATHFITX" VARCHAR2(100 BYTE), 
	"SEP" VARCHAR2(1 BYTE), 
	"CEMPRES" NUMBER(2,0), 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"SPERSON" NUMBER(10,0), 
	"CDOMICI" NUMBER, 
	"NPOLIZA" NUMBER, 
	"FEFECTO" DATE, 
	"FVENCIM" DATE, 
	"CCOBRAR" NUMBER(1,0), 
	"CACTIVI" NUMBER(4,0), 
	"COFICIN" NUMBER(6,0), 
	"CAGENTE" NUMBER, 
	"TNATRIE" VARCHAR2(300 BYTE), 
	"CPROCESSAT" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."CAP_CARREGA_COL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CAP_CARREGA_COL" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CAP_CARREGA_COL" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CAP_CARREGA_COL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CAP_CARREGA_COL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CAP_CARREGA_COL" TO "PROGRAMADORESCSI";
