--------------------------------------------------------
--  DDL for Table CAPITALMIN
--------------------------------------------------------

  CREATE TABLE "AXIS"."CAPITALMIN" 
   (	"SPRODUC" NUMBER, 
	"CACTIVI" NUMBER, 
	"CFORPAG" NUMBER, 
	"CGARANT" NUMBER, 
	"ICAPMIN" NUMBER, 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CAPITALMIN"."SPRODUC" IS 'Id del producte';
   COMMENT ON COLUMN "AXIS"."CAPITALMIN"."CACTIVI" IS 'Codi d''activitat';
   COMMENT ON COLUMN "AXIS"."CAPITALMIN"."CFORPAG" IS 'Id. de la forma de pagament';
   COMMENT ON COLUMN "AXIS"."CAPITALMIN"."CGARANT" IS 'Id. de la garantía';
   COMMENT ON COLUMN "AXIS"."CAPITALMIN"."ICAPMIN" IS 'Capital mínim de conractació per garantía i forma pagaament';
   COMMENT ON COLUMN "AXIS"."CAPITALMIN"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."CAPITALMIN"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."CAPITALMIN"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."CAPITALMIN"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON TABLE "AXIS"."CAPITALMIN"  IS 'Capital mínim per garantía';
  GRANT UPDATE ON "AXIS"."CAPITALMIN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CAPITALMIN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CAPITALMIN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CAPITALMIN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CAPITALMIN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CAPITALMIN" TO "PROGRAMADORESCSI";
