--------------------------------------------------------
--  DDL for Table CARENCIATAB
--------------------------------------------------------

  CREATE TABLE "AXIS"."CARENCIATAB" 
   (	"CEMPRES" NUMBER(1,0), 
	"CMARCO" NUMBER(1,0), 
	"NEDAD" NUMBER(3,0), 
	"CSEXO" NUMBER(1,0), 
	"NDURACI" NUMBER(6,0), 
	"PINTERES" NUMBER(8,2), 
	"ITASPURM" NUMBER(17,8), 
	"ITASINVM" NUMBER(17,8), 
	"ITASTARM" NUMBER(17,8), 
	"ITASPURI" NUMBER(17,8), 
	"ITASINVI" NUMBER(17,8), 
	"ITASTARI" NUMBER(17,8), 
	"FFINEFE" DATE, 
	"FINIEFE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CARENCIATAB"."CEMPRES" IS 'Código empresa';
   COMMENT ON COLUMN "AXIS"."CARENCIATAB"."CMARCO" IS 'Código marco';
   COMMENT ON COLUMN "AXIS"."CARENCIATAB"."NEDAD" IS 'Edad en años';
   COMMENT ON COLUMN "AXIS"."CARENCIATAB"."CSEXO" IS 'Sexo (1 Hombre, 2 Mujer)';
   COMMENT ON COLUMN "AXIS"."CARENCIATAB"."NDURACI" IS 'Duración en meses';
   COMMENT ON COLUMN "AXIS"."CARENCIATAB"."PINTERES" IS 'Porcentaje de interés';
   COMMENT ON COLUMN "AXIS"."CARENCIATAB"."ITASPURM" IS 'Importe Prima Pura Fallecimiento';
   COMMENT ON COLUMN "AXIS"."CARENCIATAB"."ITASINVM" IS 'Importe Prima Inventario Fallecimiento';
   COMMENT ON COLUMN "AXIS"."CARENCIATAB"."ITASTARM" IS 'Importe Prima Tarifa Fallecimiento';
   COMMENT ON COLUMN "AXIS"."CARENCIATAB"."ITASPURI" IS 'Importe Prima Pura Invalidez';
   COMMENT ON COLUMN "AXIS"."CARENCIATAB"."ITASINVI" IS 'Importe Prima Inventario Invalidez';
   COMMENT ON COLUMN "AXIS"."CARENCIATAB"."ITASTARI" IS 'Importe Prima Tarifa Invalidez';
   COMMENT ON TABLE "AXIS"."CARENCIATAB"  IS 'Tabla de tarifas de carènica para primas únicas';
  GRANT UPDATE ON "AXIS"."CARENCIATAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CARENCIATAB" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CARENCIATAB" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CARENCIATAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CARENCIATAB" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CARENCIATAB" TO "PROGRAMADORESCSI";
