--------------------------------------------------------
--  DDL for Table CARENCIAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."CARENCIAS" 
   (	"CCAREN" NUMBER(6,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TCAREN" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CARENCIAS"."CCAREN" IS 'Código de acto médico';
   COMMENT ON COLUMN "AXIS"."CARENCIAS"."CIDIOMA" IS 'Código del idioma 1.- Català 2.- Castellano';
   COMMENT ON COLUMN "AXIS"."CARENCIAS"."TCAREN" IS 'Texto - Descripción Carencia';
   COMMENT ON TABLE "AXIS"."CARENCIAS"  IS 'Descripción de las carencias';
  GRANT UPDATE ON "AXIS"."CARENCIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CARENCIAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CARENCIAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CARENCIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CARENCIAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CARENCIAS" TO "PROGRAMADORESCSI";
