--------------------------------------------------------
--  DDL for Table CARTERAAUX
--------------------------------------------------------

  CREATE TABLE "AXIS"."CARTERAAUX" 
   (	"SPROCES" NUMBER, 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CACTIVI" NUMBER, 
	"NPOLIZA" NUMBER, 
	"NCERTIF" NUMBER(6,0), 
	"CBLOQUEO" NUMBER(2,0) DEFAULT 0, 
	"FCARTERA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CARTERAAUX"."SPROCES" IS 'Número de proceso que genera el registro';
   COMMENT ON COLUMN "AXIS"."CARTERAAUX"."CRAMO" IS 'Código de ramo';
   COMMENT ON COLUMN "AXIS"."CARTERAAUX"."CMODALI" IS 'Código de modalidad';
   COMMENT ON COLUMN "AXIS"."CARTERAAUX"."CTIPSEG" IS 'Código de tipo seguro';
   COMMENT ON COLUMN "AXIS"."CARTERAAUX"."CCOLECT" IS 'Código de colectividad';
   COMMENT ON COLUMN "AXIS"."CARTERAAUX"."CACTIVI" IS 'Código de actividad';
   COMMENT ON COLUMN "AXIS"."CARTERAAUX"."NPOLIZA" IS 'Número de poliza';
   COMMENT ON COLUMN "AXIS"."CARTERAAUX"."NCERTIF" IS 'Número de certificado para pólizas colectivas';
   COMMENT ON COLUMN "AXIS"."CARTERAAUX"."CBLOQUEO" IS 'Indica si esta el proceso bloqueado';
   COMMENT ON COLUMN "AXIS"."CARTERAAUX"."FCARTERA" IS 'Fecha de ejecución de la cartera.';
   COMMENT ON TABLE "AXIS"."CARTERAAUX"  IS 'Tabla auxiliar para la cartera';
  GRANT UPDATE ON "AXIS"."CARTERAAUX" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CARTERAAUX" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CARTERAAUX" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CARTERAAUX" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CARTERAAUX" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CARTERAAUX" TO "PROGRAMADORESCSI";
