--------------------------------------------------------
--  DDL for Table CAUSASINI
--------------------------------------------------------

  CREATE TABLE "AXIS"."CAUSASINI" 
   (	"CIDIOMA" NUMBER(2,0), 
	"CCAUSIN" NUMBER(4,0), 
	"TCAUSIN" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CAUSASINI"."CIDIOMA" IS 'Código de Idioma';
   COMMENT ON COLUMN "AXIS"."CAUSASINI"."CCAUSIN" IS 'Código causa siniestro';
   COMMENT ON COLUMN "AXIS"."CAUSASINI"."TCAUSIN" IS 'Descripción causa del siniestro';
  GRANT UPDATE ON "AXIS"."CAUSASINI" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CAUSASINI" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CAUSASINI" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CAUSASINI" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CAUSASINI" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CAUSASINI" TO "PROGRAMADORESCSI";
