--------------------------------------------------------
--  DDL for Table CFG_COD_FORM
--------------------------------------------------------

  CREATE TABLE "AXIS"."CFG_COD_FORM" 
   (	"CFORM" VARCHAR2(50 BYTE), 
	"TFORM" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON TABLE "AXIS"."CFG_COD_FORM"  IS 'Tabla con los formularios existentes en AXIS web';
  GRANT UPDATE ON "AXIS"."CFG_COD_FORM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_COD_FORM" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CFG_COD_FORM" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CFG_COD_FORM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_COD_FORM" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CFG_COD_FORM" TO "PROGRAMADORESCSI";
