--------------------------------------------------------
--  DDL for Table CFG_LANZAR_INFORMES_PARAMS
--------------------------------------------------------

  CREATE TABLE "AXIS"."CFG_LANZAR_INFORMES_PARAMS" 
   (	"CEMPRES" NUMBER(2,0), 
	"CFORM" VARCHAR2(50 BYTE), 
	"CMAP" VARCHAR2(50 BYTE), 
	"TEVENTO" VARCHAR2(400 BYTE), 
	"SPRODUC" NUMBER(6,0), 
	"CCFGFORM" VARCHAR2(100 BYTE), 
	"TPARAM" VARCHAR2(50 BYTE), 
	"NORDER" NUMBER(3,0), 
	"SLITERA" NUMBER(8,0), 
	"CTIPO" NUMBER(2,0), 
	"NOTNULL" NUMBER(1,0), 
	"LVALOR" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CFG_LANZAR_INFORMES_PARAMS"."CEMPRES" IS 'Empresa';
   COMMENT ON COLUMN "AXIS"."CFG_LANZAR_INFORMES_PARAMS"."CFORM" IS 'Pantalla que se parametriza';
   COMMENT ON COLUMN "AXIS"."CFG_LANZAR_INFORMES_PARAMS"."CMAP" IS 'Map a lanzar';
   COMMENT ON COLUMN "AXIS"."CFG_LANZAR_INFORMES_PARAMS"."TEVENTO" IS 'Define desde donde se llama';
   COMMENT ON COLUMN "AXIS"."CFG_LANZAR_INFORMES_PARAMS"."CCFGFORM" IS 'Código de configuracion';
   COMMENT ON COLUMN "AXIS"."CFG_LANZAR_INFORMES_PARAMS"."TPARAM" IS 'Nombre del parámetro';
   COMMENT ON COLUMN "AXIS"."CFG_LANZAR_INFORMES_PARAMS"."NORDER" IS 'Orden del parámetro';
   COMMENT ON COLUMN "AXIS"."CFG_LANZAR_INFORMES_PARAMS"."SLITERA" IS 'Literal del parámetro';
   COMMENT ON COLUMN "AXIS"."CFG_LANZAR_INFORMES_PARAMS"."CTIPO" IS 'Tipo de valor del parámetro: 1.- Texto, 2.- Numérico, 3.- Fecha';
   COMMENT ON COLUMN "AXIS"."CFG_LANZAR_INFORMES_PARAMS"."NOTNULL" IS 'Número certificado final de HOST';
   COMMENT ON COLUMN "AXIS"."CFG_LANZAR_INFORMES_PARAMS"."LVALOR" IS 'Origen de datos "LISTA:...", "SELECT:..."';
   COMMENT ON TABLE "AXIS"."CFG_LANZAR_INFORMES_PARAMS"  IS 'Configuración de parámetros de informes';
  GRANT UPDATE ON "AXIS"."CFG_LANZAR_INFORMES_PARAMS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_LANZAR_INFORMES_PARAMS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CFG_LANZAR_INFORMES_PARAMS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CFG_LANZAR_INFORMES_PARAMS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_LANZAR_INFORMES_PARAMS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CFG_LANZAR_INFORMES_PARAMS" TO "PROGRAMADORESCSI";
