--------------------------------------------------------
--  DDL for Table CFG_ACCION_RECIBO
--------------------------------------------------------

  CREATE TABLE "AXIS"."CFG_ACCION_RECIBO" 
   (	"CEMPRES" NUMBER, 
	"CESTREC" NUMBER, 
	"CACCION" VARCHAR2(100 BYTE), 
	"CCFGACC" VARCHAR2(50 BYTE), 
	"SPRODUC" NUMBER, 
	"CFORM" VARCHAR2(50 BYTE), 
	"TFORM" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CFG_ACCION_RECIBO"."CEMPRES" IS 'Empresa';
   COMMENT ON COLUMN "AXIS"."CFG_ACCION_RECIBO"."CESTREC" IS 'Códi estat del rebut';
   COMMENT ON COLUMN "AXIS"."CFG_ACCION_RECIBO"."CACCION" IS 'Codi de l''acció permesa';
   COMMENT ON COLUMN "AXIS"."CFG_ACCION_RECIBO"."CCFGACC" IS 'Codi de la configuració d''accions';
   COMMENT ON COLUMN "AXIS"."CFG_ACCION_RECIBO"."CFORM" IS 'Id. del formulari';
   COMMENT ON COLUMN "AXIS"."CFG_ACCION_RECIBO"."TFORM" IS 'Descripció del formulari';
   COMMENT ON TABLE "AXIS"."CFG_ACCION_RECIBO"  IS 'taula amb la relació d''accions de gestió de rebut permeses per configuració d''accions i estat de rebut';
  GRANT UPDATE ON "AXIS"."CFG_ACCION_RECIBO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_ACCION_RECIBO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CFG_ACCION_RECIBO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CFG_ACCION_RECIBO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_ACCION_RECIBO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CFG_ACCION_RECIBO" TO "PROGRAMADORESCSI";
