--------------------------------------------------------
--  DDL for Table CFG_COD_CFGDOC
--------------------------------------------------------

  CREATE TABLE "AXIS"."CFG_COD_CFGDOC" 
   (	"CEMPRES" NUMBER(2,0), 
	"CCFGDOC" VARCHAR2(50 BYTE), 
	"TDESC" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CFG_COD_CFGDOC"."CEMPRES" IS 'Código de Empresa';
   COMMENT ON COLUMN "AXIS"."CFG_COD_CFGDOC"."CCFGDOC" IS 'Id. del tipo de configuración de documento';
   COMMENT ON COLUMN "AXIS"."CFG_COD_CFGDOC"."TDESC" IS 'Descripción del tipo de configuración de documento';
   COMMENT ON TABLE "AXIS"."CFG_COD_CFGDOC"  IS 'Tabla con los tipos configuraciones de documentos para usuarios existentes en el aplicativo';
  GRANT UPDATE ON "AXIS"."CFG_COD_CFGDOC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_COD_CFGDOC" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CFG_COD_CFGDOC" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CFG_COD_CFGDOC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_COD_CFGDOC" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CFG_COD_CFGDOC" TO "PROGRAMADORESCSI";
