--------------------------------------------------------
--  DDL for Table CFG_WIZARD_SKIP
--------------------------------------------------------

  CREATE TABLE "AXIS"."CFG_WIZARD_SKIP" 
   (	"CEMPRES" NUMBER(2,0), 
	"CIDCFG" NUMBER, 
	"CFORM" VARCHAR2(50 BYTE), 
	"TCOND" VARCHAR2(2000 BYTE), 
	"CTIPCOND" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CFG_WIZARD_SKIP"."CEMPRES" IS 'Código de la empresa';
   COMMENT ON COLUMN "AXIS"."CFG_WIZARD_SKIP"."CIDCFG" IS 'Id. de la configuración de navegación';
   COMMENT ON COLUMN "AXIS"."CFG_WIZARD_SKIP"."CFORM" IS 'Id. del formulario';
   COMMENT ON COLUMN "AXIS"."CFG_WIZARD_SKIP"."TCOND" IS 'Condición que si se evalua a CIERTO, implica que debe ocultarse el formulario en el flujo de navegación (no mostrarlo y pasar directamente al formulario siguiente)';
   COMMENT ON COLUMN "AXIS"."CFG_WIZARD_SKIP"."CTIPCOND" IS 'Tipo de la condición a evaluar (OP -> sobre el objeto persistente póliza, S -> SELECT)';
  GRANT UPDATE ON "AXIS"."CFG_WIZARD_SKIP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_WIZARD_SKIP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CFG_WIZARD_SKIP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CFG_WIZARD_SKIP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_WIZARD_SKIP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CFG_WIZARD_SKIP" TO "PROGRAMADORESCSI";
