--------------------------------------------------------
--  DDL for Table CFG_PLANTILLAS_TIPOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."CFG_PLANTILLAS_TIPOS" 
   (	"CTIPO" NUMBER(3,0), 
	"TTIPO" VARCHAR2(20 BYTE), 
	"TDESCRIP" VARCHAR2(300 BYTE), 
	"CDUPLICA" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CFG_PLANTILLAS_TIPOS"."CTIPO" IS 'ID Tipo de plantilla';
   COMMENT ON COLUMN "AXIS"."CFG_PLANTILLAS_TIPOS"."TTIPO" IS 'Texto Tipo de plantilla, se usa desde java para llamar a las impresiones';
   COMMENT ON COLUMN "AXIS"."CFG_PLANTILLAS_TIPOS"."TDESCRIP" IS 'Descripción del tipo de plantilla';
   COMMENT ON COLUMN "AXIS"."CFG_PLANTILLAS_TIPOS"."CDUPLICA" IS 'El tipo de impresión es un duplicado? 0/1 No/Si';
   COMMENT ON TABLE "AXIS"."CFG_PLANTILLAS_TIPOS"  IS 'Tipos de plantillas que se llaman desde pantalla Java';
  GRANT UPDATE ON "AXIS"."CFG_PLANTILLAS_TIPOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_PLANTILLAS_TIPOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CFG_PLANTILLAS_TIPOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CFG_PLANTILLAS_TIPOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_PLANTILLAS_TIPOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CFG_PLANTILLAS_TIPOS" TO "PROGRAMADORESCSI";
