--------------------------------------------------------
--  DDL for Table CFG_TIPOSBAJAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."CFG_TIPOSBAJAS" 
   (	"CEMPRES" NUMBER(2,0), 
	"SPRODUC" NUMBER(6,0), 
	"CTIPBAJA" NUMBER(3,0), 
	"CCFGACC" VARCHAR2(50 BYTE), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CFG_TIPOSBAJAS"."CEMPRES" IS 'código de empresa';
   COMMENT ON COLUMN "AXIS"."CFG_TIPOSBAJAS"."SPRODUC" IS 'código de producto';
   COMMENT ON COLUMN "AXIS"."CFG_TIPOSBAJAS"."CTIPBAJA" IS 'tipo de baja. Se corresponde a los valores del valor fijo 553';
   COMMENT ON COLUMN "AXIS"."CFG_TIPOSBAJAS"."CCFGACC" IS 'Codi de la configuració d''accions';
   COMMENT ON COLUMN "AXIS"."CFG_TIPOSBAJAS"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."CFG_TIPOSBAJAS"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."CFG_TIPOSBAJAS"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."CFG_TIPOSBAJAS"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON TABLE "AXIS"."CFG_TIPOSBAJAS"  IS 'Tipos de baja de póliza por producto y por configuración de acciones de usuario';
  GRANT UPDATE ON "AXIS"."CFG_TIPOSBAJAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_TIPOSBAJAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CFG_TIPOSBAJAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CFG_TIPOSBAJAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_TIPOSBAJAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CFG_TIPOSBAJAS" TO "PROGRAMADORESCSI";
