--------------------------------------------------------
--  DDL for Table CFG_CONFIG_FORM
--------------------------------------------------------

  CREATE TABLE "AXIS"."CFG_CONFIG_FORM" 
   (	"CFORM" VARCHAR2(50 BYTE), 
	"CITEM" VARCHAR2(50 BYTE), 
	"CPRPTY" NUMBER(8,0), 
	"CVALUE" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CFG_CONFIG_FORM"."CFORM" IS 'Id. del formulario';
   COMMENT ON COLUMN "AXIS"."CFG_CONFIG_FORM"."CITEM" IS 'Nombre del campo';
   COMMENT ON COLUMN "AXIS"."CFG_CONFIG_FORM"."CPRPTY" IS 'Id. de la propiedad del item del formulario (5 -> Longitud, 6 -> Tipus)';
   COMMENT ON COLUMN "AXIS"."CFG_CONFIG_FORM"."CVALUE" IS 'Valor de la propiedad del item del formulario.';
  GRANT UPDATE ON "AXIS"."CFG_CONFIG_FORM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_CONFIG_FORM" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CFG_CONFIG_FORM" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CFG_CONFIG_FORM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CFG_CONFIG_FORM" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CFG_CONFIG_FORM" TO "PROGRAMADORESCSI";
