--------------------------------------------------------
--  DDL for Table CLASACTIVIPROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."CLASACTIVIPROD" 
   (	"SPRODUC" NUMBER(8,0), 
	"CACTIVI" NUMBER(4,0), 
	"CCLASACT" NUMBER(15,0), 
	"CVAL1" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CLASACTIVIPROD"."SPRODUC" IS 'Codigo del producto';
   COMMENT ON COLUMN "AXIS"."CLASACTIVIPROD"."CACTIVI" IS 'Codigo de la actividad';
   COMMENT ON COLUMN "AXIS"."CLASACTIVIPROD"."CCLASACT" IS 'llave foranea a la tabla desclasactivi';
   COMMENT ON COLUMN "AXIS"."CLASACTIVIPROD"."CVAL1" IS 'Valor adicional';
   COMMENT ON TABLE "AXIS"."CLASACTIVIPROD"  IS 'Clasificacion de actividades contra productos';
  GRANT UPDATE ON "AXIS"."CLASACTIVIPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CLASACTIVIPROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CLASACTIVIPROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CLASACTIVIPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CLASACTIVIPROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CLASACTIVIPROD" TO "PROGRAMADORESCSI";
