--------------------------------------------------------
--  DDL for Table CLAUSULAS_REAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."CLAUSULAS_REAS" 
   (	"CCODIGO" NUMBER(5,0), 
	"CIDIOMA" NUMBER(3,0), 
	"TDESCRIPCION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CLAUSULAS_REAS"."CCODIGO" IS 'Código de cláusula';
   COMMENT ON COLUMN "AXIS"."CLAUSULAS_REAS"."CIDIOMA" IS 'Idioma';
   COMMENT ON COLUMN "AXIS"."CLAUSULAS_REAS"."TDESCRIPCION" IS 'Descripción';
   COMMENT ON TABLE "AXIS"."CLAUSULAS_REAS"  IS 'Descripción según el idioma del código de cláusula';
  GRANT UPDATE ON "AXIS"."CLAUSULAS_REAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CLAUSULAS_REAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CLAUSULAS_REAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CLAUSULAS_REAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CLAUSULAS_REAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CLAUSULAS_REAS" TO "PROGRAMADORESCSI";
