--------------------------------------------------------
--  DDL for Table CLAUSUBEN
--------------------------------------------------------

  CREATE TABLE "AXIS"."CLAUSUBEN" 
   (	"SCLABEN" NUMBER(4,0), 
	"TCLABEN" VARCHAR2(600 BYTE), 
	"CIDIOMA" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CLAUSUBEN"."SCLABEN" IS 'Secuencia cláusula de beneficiario';
   COMMENT ON COLUMN "AXIS"."CLAUSUBEN"."TCLABEN" IS 'Descripción de la cláusula de beneficiario';
   COMMENT ON COLUMN "AXIS"."CLAUSUBEN"."CIDIOMA" IS 'Código de Idioma';
  GRANT UPDATE ON "AXIS"."CLAUSUBEN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CLAUSUBEN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CLAUSUBEN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CLAUSUBEN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CLAUSUBEN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CLAUSUBEN" TO "PROGRAMADORESCSI";
