--------------------------------------------------------
--  DDL for Table CNV_CONV_EMP
--------------------------------------------------------

  CREATE TABLE "AXIS"."CNV_CONV_EMP" 
   (	"IDCONV" NUMBER, 
	"CPAIS" NUMBER, 
	"CCAA" NUMBER, 
	"CPROVIN" NUMBER, 
	"TCODCONV" VARCHAR2(20 BYTE), 
	"TDESCRI" VARCHAR2(200 BYTE), 
	"CORGANISMO" NUMBER, 
	"CPERFIL" NUMBER, 
	"CESTADO" NUMBER, 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CNV_CONV_EMP"."IDCONV" IS 'Identificador de Convenio';
   COMMENT ON COLUMN "AXIS"."CNV_CONV_EMP"."CPAIS" IS 'Código País del Convenio (Tabla Países)';
   COMMENT ON COLUMN "AXIS"."CNV_CONV_EMP"."CCAA" IS 'Código Comunidad Autónoma (Tabla CCAA)';
   COMMENT ON COLUMN "AXIS"."CNV_CONV_EMP"."CPROVIN" IS 'Código Provincia (Tabla Provincias)';
   COMMENT ON COLUMN "AXIS"."CNV_CONV_EMP"."TCODCONV" IS 'Código de Convenio';
   COMMENT ON COLUMN "AXIS"."CNV_CONV_EMP"."TDESCRI" IS 'Descripción del Convenio';
   COMMENT ON COLUMN "AXIS"."CNV_CONV_EMP"."CORGANISMO" IS 'Código Organismo (detvalores 8001000)';
   COMMENT ON COLUMN "AXIS"."CNV_CONV_EMP"."CPERFIL" IS 'Tipo perfil los valores de la tabla de perfiles de convenio.';
   COMMENT ON COLUMN "AXIS"."CNV_CONV_EMP"."CESTADO" IS 'Estado del convenio (detvalores 8001001)';
   COMMENT ON COLUMN "AXIS"."CNV_CONV_EMP"."FALTA" IS 'Fecha Alta';
   COMMENT ON COLUMN "AXIS"."CNV_CONV_EMP"."CUSUALT" IS 'Usuario Alta';
   COMMENT ON COLUMN "AXIS"."CNV_CONV_EMP"."CUSUMOD" IS 'Usuario Modificación';
   COMMENT ON COLUMN "AXIS"."CNV_CONV_EMP"."FMODIFI" IS 'Fecha Modificación';
  GRANT UPDATE ON "AXIS"."CNV_CONV_EMP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CNV_CONV_EMP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CNV_CONV_EMP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CNV_CONV_EMP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CNV_CONV_EMP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CNV_CONV_EMP" TO "PROGRAMADORESCSI";
