--------------------------------------------------------
--  DDL for Table CNVCOMPANIAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."CNVCOMPANIAS" 
   (	"SISTEMA" VARCHAR2(2 BYTE), 
	"EMPRESA" VARCHAR2(4 BYTE), 
	"SPERSON" NUMBER(10,0), 
	"CCOMPANI" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."CNVCOMPANIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CNVCOMPANIAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CNVCOMPANIAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CNVCOMPANIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CNVCOMPANIAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CNVCOMPANIAS" TO "PROGRAMADORESCSI";
