--------------------------------------------------------
--  DDL for Table CNVDIRECCIONES
--------------------------------------------------------

  CREATE TABLE "AXIS"."CNVDIRECCIONES" 
   (	"SISTEMA" VARCHAR2(2 BYTE), 
	"CODI_AUXILIAR" VARCHAR2(2 BYTE), 
	"CODI_ORIGEN" VARCHAR2(15 BYTE), 
	"PRODUCTE" VARCHAR2(4 BYTE), 
	"APLICA" NUMBER(4,0), 
	"CORREL" NUMBER(3,0), 
	"SPERSON" NUMBER(10,0), 
	"CDOMICI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."CNVDIRECCIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CNVDIRECCIONES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CNVDIRECCIONES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CNVDIRECCIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CNVDIRECCIONES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CNVDIRECCIONES" TO "PROGRAMADORESCSI";
