--------------------------------------------------------
--  DDL for Table CNVHIST
--------------------------------------------------------

  CREATE TABLE "AXIS"."CNVHIST" 
   (	"NHISTORIA" NUMBER(8,0), 
	"SPERSON" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."CNVHIST" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CNVHIST" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CNVHIST" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CNVHIST" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CNVHIST" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CNVHIST" TO "PROGRAMADORESCSI";
