--------------------------------------------------------
--  DDL for Table CNVPRODUCTOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."CNVPRODUCTOS" 
   (	"CRAMO" NUMBER(8,0), 
	"CMODAL" NUMBER(2,0), 
	"RAM_HP" NUMBER(2,0), 
	"MODA_HP" NUMBER(2,0), 
	"PRODUCTE" VARCHAR2(4 BYTE), 
	"PRODUCTE_MU" VARCHAR2(4 BYTE), 
	"CCOLECT" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"NPOLINI" NUMBER, 
	"NPOLFIN" NUMBER, 
	"SISTEMA" VARCHAR2(4 BYTE), 
	"CMONEDA" NUMBER(1,0) DEFAULT 2, 
	"CRAMO_E" NUMBER(2,0), 
	"CMODALI_E" NUMBER(2,0), 
	"CTIPSEG_E" NUMBER(2,0), 
	"CCOLECT_E" NUMBER(2,0), 
	"CIA" VARCHAR2(4 BYTE), 
	"NUMPOL" VARCHAR2(15 BYTE), 
	"CEMPLE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CNVPRODUCTOS"."CRAMO_E" IS 'Ramo para producto en Euros';
   COMMENT ON COLUMN "AXIS"."CNVPRODUCTOS"."CMODALI_E" IS 'Modalidad para producto en Euros';
   COMMENT ON COLUMN "AXIS"."CNVPRODUCTOS"."CTIPSEG_E" IS 'Tipo seguro para producto en Euros';
   COMMENT ON COLUMN "AXIS"."CNVPRODUCTOS"."CCOLECT_E" IS 'Colectivo para producto en Euros';
   COMMENT ON COLUMN "AXIS"."CNVPRODUCTOS"."CIA" IS 'Compañía aseguradora';
   COMMENT ON COLUMN "AXIS"."CNVPRODUCTOS"."NUMPOL" IS 'Número de Póliza del producto';
   COMMENT ON COLUMN "AXIS"."CNVPRODUCTOS"."CEMPLE" IS 'Indicador de si es empleado o no';
  GRANT UPDATE ON "AXIS"."CNVPRODUCTOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CNVPRODUCTOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CNVPRODUCTOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CNVPRODUCTOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CNVPRODUCTOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CNVPRODUCTOS" TO "PROGRAMADORESCSI";
