--------------------------------------------------------
--  DDL for Table CODEXCLUSIONES_UDW
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODEXCLUSIONES_UDW" 
   (	"CEMPRES" NUMBER, 
	"CEXCLUS" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."CODEXCLUSIONES_UDW" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODEXCLUSIONES_UDW" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODEXCLUSIONES_UDW" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODEXCLUSIONES_UDW" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODEXCLUSIONES_UDW" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODEXCLUSIONES_UDW" TO "PROGRAMADORESCSI";
