--------------------------------------------------------
--  DDL for Table CODGRPPARAM
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODGRPPARAM" 
   (	"CGRPPAR" VARCHAR2(4 BYTE), 
	"CUTILI" NUMBER(4,0), 
	"NORDEN" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODGRPPARAM"."CGRPPAR" IS 'Código de agrupación';
   COMMENT ON COLUMN "AXIS"."CODGRPPARAM"."CUTILI" IS 'Indicador de dónde se utiliza el parámetro (Productos, garantías, ….) VF. 281';
   COMMENT ON COLUMN "AXIS"."CODGRPPARAM"."NORDEN" IS 'Orden de visualización de la agrupación';
  GRANT UPDATE ON "AXIS"."CODGRPPARAM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODGRPPARAM" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODGRPPARAM" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODGRPPARAM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODGRPPARAM" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODGRPPARAM" TO "PROGRAMADORESCSI";
