--------------------------------------------------------
--  DDL for Table CODGRUPODIAN
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODGRUPODIAN" 
   (	"CGRUPO" VARCHAR2(10 BYTE), 
	"TGRUPO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODGRUPODIAN"."CGRUPO" IS 'Codigo grupo';
   COMMENT ON COLUMN "AXIS"."CODGRUPODIAN"."TGRUPO" IS 'Descripcion grupo';
  GRANT UPDATE ON "AXIS"."CODGRUPODIAN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODGRUPODIAN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODGRUPODIAN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODGRUPODIAN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODGRUPODIAN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODGRUPODIAN" TO "PROGRAMADORESCSI";
