--------------------------------------------------------
--  DDL for Table CODICLARIE
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODICLARIE" 
   (	"CCLARIE" NUMBER(2,0), 
	"CCLASEL" NUMBER(1,0), 
	"NCLAORD" NUMBER(2,0), 
	"CTIPCLA" NUMBER(2,0), 
	"IVALNOR" NUMBER(19,12), 
	"IVALRED" NUMBER(19,12)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODICLARIE"."CCLARIE" IS 'Códogo de la Clase de Riesgo';
   COMMENT ON COLUMN "AXIS"."CODICLARIE"."CCLASEL" IS 'Ind. seleccionable';
   COMMENT ON COLUMN "AXIS"."CODICLARIE"."NCLAORD" IS 'Orden de visualización en listas';
   COMMENT ON COLUMN "AXIS"."CODICLARIE"."CTIPCLA" IS 'Tipo de clase de riesgo';
   COMMENT ON COLUMN "AXIS"."CODICLARIE"."IVALNOR" IS 'Tasa "normal"';
   COMMENT ON COLUMN "AXIS"."CODICLARIE"."IVALRED" IS 'Tasa "reducida"';
  GRANT UPDATE ON "AXIS"."CODICLARIE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODICLARIE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODICLARIE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODICLARIE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODICLARIE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODICLARIE" TO "PROGRAMADORESCSI";
