--------------------------------------------------------
--  DDL for Table CODICAUSIN
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODICAUSIN" 
   (	"CCAUSIN" NUMBER(4,0), 
	"CRAMO" NUMBER(8,0), 
	"CATRIBU" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODICAUSIN"."CCAUSIN" IS 'Código causa siniestro';
   COMMENT ON COLUMN "AXIS"."CODICAUSIN"."CRAMO" IS 'Código de ramo ';
   COMMENT ON COLUMN "AXIS"."CODICAUSIN"."CATRIBU" IS 'Código de concepto de la transferencia asociada; cvalor = 701';
  GRANT UPDATE ON "AXIS"."CODICAUSIN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODICAUSIN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODICAUSIN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODICAUSIN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODICAUSIN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODICAUSIN" TO "PROGRAMADORESCSI";
