--------------------------------------------------------
--  DDL for Table CODIRESPUESTAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODIRESPUESTAS" 
   (	"CPREGUN" NUMBER(4,0), 
	"CRESPUE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODIRESPUESTAS"."CPREGUN" IS 'Código de la pregunta';
   COMMENT ON COLUMN "AXIS"."CODIRESPUESTAS"."CRESPUE" IS 'Código respuesta';
  GRANT UPDATE ON "AXIS"."CODIRESPUESTAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODIRESPUESTAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODIRESPUESTAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODIRESPUESTAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODIRESPUESTAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODIRESPUESTAS" TO "PROGRAMADORESCSI";
