--------------------------------------------------------
--  DDL for Table CODINORMA_CONF
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODINORMA_CONF" 
   (	"CNORMA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODINORMA_CONF"."CNORMA" IS 'Norma o código';
  GRANT UPDATE ON "AXIS"."CODINORMA_CONF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODINORMA_CONF" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODINORMA_CONF" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODINORMA_CONF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODINORMA_CONF" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODINORMA_CONF" TO "PROGRAMADORESCSI";
