--------------------------------------------------------
--  DDL for Table CODICONTRATOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODICONTRATOS" 
   (	"SCONTRA" NUMBER(6,0), 
	"SPLENO" NUMBER(6,0), 
	"CEMPRES" NUMBER(2,0), 
	"CTIPREA" NUMBER(2,0), 
	"FINICTR" DATE, 
	"FFINCTR" DATE, 
	"NCONREL" NUMBER(6,0), 
	"SCONAGR" NUMBER(6,0), 
	"CVIDAGA" NUMBER(1,0), 
	"CVIDAIR" NUMBER(1,0), 
	"CTIPCUM" NUMBER(1,0), 
	"CVALID" NUMBER(1,0), 
	"CRETIRA" NUMBER(1,0), 
	"CMONEDA" VARCHAR2(3 BYTE), 
	"TDESCRIPCION" VARCHAR2(100 BYTE), 
	"CDEVENTO" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODICONTRATOS"."SPLENO" IS 'Identificador del Pleno';
   COMMENT ON COLUMN "AXIS"."CODICONTRATOS"."CEMPRES" IS 'Código de Empresa';
   COMMENT ON COLUMN "AXIS"."CODICONTRATOS"."CTIPREA" IS 'Tipo de contrato de Reaseguro VF:106';
   COMMENT ON COLUMN "AXIS"."CODICONTRATOS"."CTIPCUM" IS 'Tipo Cumulo V.F 225';
   COMMENT ON COLUMN "AXIS"."CODICONTRATOS"."CVALID" IS 'Código de contratos con nueva versión validada para proceso de ajuste de cesiones';
   COMMENT ON COLUMN "AXIS"."CODICONTRATOS"."CRETIRA" IS 'Retirada de Cartera (0-No 1-Si)';
   COMMENT ON COLUMN "AXIS"."CODICONTRATOS"."CMONEDA" IS 'Código Moneda (Tabla ECO_CODMONEDAS)';
   COMMENT ON COLUMN "AXIS"."CODICONTRATOS"."TDESCRIPCION" IS 'Descripción del contrato';
   COMMENT ON COLUMN "AXIS"."CODICONTRATOS"."CDEVENTO" IS 'Indica si al contrato aplica reaseguro por eventos (0:No, 1:Si, 2:Ambos)';
  GRANT UPDATE ON "AXIS"."CODICONTRATOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODICONTRATOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODICONTRATOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODICONTRATOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODICONTRATOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODICONTRATOS" TO "PROGRAMADORESCSI";
