--------------------------------------------------------
--  DDL for Table CODIGRPFRANQ
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODIGRPFRANQ" 
   (	"NGRPFRA" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODIGRPFRANQ"."NGRPFRA" IS 'Codigo de grupo de Franquicias';
   COMMENT ON TABLE "AXIS"."CODIGRPFRANQ"  IS 'Tabla formal codigo de Franquicias';
  GRANT UPDATE ON "AXIS"."CODIGRPFRANQ" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODIGRPFRANQ" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODIGRPFRANQ" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODIGRPFRANQ" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODIGRPFRANQ" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODIGRPFRANQ" TO "PROGRAMADORESCSI";
