--------------------------------------------------------
--  DDL for Table CODIDESC
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODIDESC" 
   (	"CDESC" NUMBER(2,0), 
	"CTIPO" NUMBER(2,0), 
	"FALTA" DATE, 
	"CUSUALTA" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODIDESC"."CDESC" IS 'Código descuento';
   COMMENT ON COLUMN "AXIS"."CODIDESC"."CTIPO" IS 'Tipo descuento';
   COMMENT ON COLUMN "AXIS"."CODIDESC"."FALTA" IS 'Fecha alta descuento';
   COMMENT ON COLUMN "AXIS"."CODIDESC"."CUSUALTA" IS 'Usuario alta descuento';
   COMMENT ON COLUMN "AXIS"."CODIDESC"."FMODIFI" IS 'Fecha modificación descuento';
   COMMENT ON COLUMN "AXIS"."CODIDESC"."CUSUMOD" IS 'Usuario modificación descuento';
   COMMENT ON TABLE "AXIS"."CODIDESC"  IS 'Codigos descuento';
  GRANT UPDATE ON "AXIS"."CODIDESC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODIDESC" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODIDESC" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODIDESC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODIDESC" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODIDESC" TO "PROGRAMADORESCSI";
