--------------------------------------------------------
--  DDL for Table CODIPREGUN
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODIPREGUN" 
   (	"CPREGUN" NUMBER(4,0), 
	"CTIPPRE" NUMBER(1,0), 
	"CTIPPOR" NUMBER(2,0), 
	"CTIPGRU" NUMBER(2,0), 
	"TCONSULTA" VARCHAR2(4000 BYTE), 
	"TIMAGEN" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODIPREGUN"."CPREGUN" IS 'Código de la pregunta';
   COMMENT ON COLUMN "AXIS"."CODIPREGUN"."CTIPPRE" IS 'Tipo de pregunta (detvalores.cvalor = 78)';
   COMMENT ON COLUMN "AXIS"."CODIPREGUN"."CTIPPOR" IS 'Tipo de porcentaje';
   COMMENT ON COLUMN "AXIS"."CODIPREGUN"."CTIPGRU" IS 'Tipo de grupo de preguntas (detvalores.cvalor = 309)';
   COMMENT ON COLUMN "AXIS"."CODIPREGUN"."TIMAGEN" IS 'Nombre del fichero que estara en /IMAGENES';
  GRANT UPDATE ON "AXIS"."CODIPREGUN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODIPREGUN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODIPREGUN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODIPREGUN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODIPREGUN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODIPREGUN" TO "PROGRAMADORESCSI";
