--------------------------------------------------------
--  DDL for Table CODIEXCLUSIONES
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODIEXCLUSIONES" 
   (	"CEXCLU" VARCHAR2(6 BYTE), 
	"CTIPICD9" NUMBER(1,0), 
	"NBAREMO" NUMBER(6,3), 
	"CMARDIA" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODIEXCLUSIONES"."CEXCLU" IS 'Código exclusión';
   COMMENT ON TABLE "AXIS"."CODIEXCLUSIONES"  IS 'Código ID de las exclusiones';
  GRANT UPDATE ON "AXIS"."CODIEXCLUSIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODIEXCLUSIONES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODIEXCLUSIONES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODIEXCLUSIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODIEXCLUSIONES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODIEXCLUSIONES" TO "PROGRAMADORESCSI";
