--------------------------------------------------------
--  DDL for Table CODIMOTMOV
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODIMOTMOV" 
   (	"CMOTMOV" NUMBER(3,0), 
	"CGENREC" NUMBER(1,0), 
	"CIMPRES" NUMBER(1,0), 
	"CACTIVO" NUMBER(1,0) DEFAULT 1, 
	"CMOVSEG" NUMBER(2,0) DEFAULT 0, 
	"CGESMOV" NUMBER(1,0) DEFAULT 0, 
	"CTIPVAL" NUMBER(2,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODIMOTMOV"."CMOTMOV" IS 'Código motivo de movimiento';
   COMMENT ON COLUMN "AXIS"."CODIMOTMOV"."CGENREC" IS 'El movimiento genera recibo o no';
   COMMENT ON COLUMN "AXIS"."CODIMOTMOV"."CACTIVO" IS 'Tipo de suplemento del movimiento: 1 es activo';
   COMMENT ON COLUMN "AXIS"."CODIMOTMOV"."CGESMOV" IS 'Tipo de gestión de movimiento, 1 es manual';
   COMMENT ON COLUMN "AXIS"."CODIMOTMOV"."CTIPVAL" IS 'Tipo de Validación (0.-No es un movmiento propio se validan todos los movimientos, 1.-Movimiento propio solo se valida el mismo)';
  GRANT UPDATE ON "AXIS"."CODIMOTMOV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODIMOTMOV" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODIMOTMOV" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODIMOTMOV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODIMOTMOV" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODIMOTMOV" TO "PROGRAMADORESCSI";
