--------------------------------------------------------
--  DDL for Table CODIAUTCLAVEH
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODIAUTCLAVEH" 
   (	"CCLAVEH" VARCHAR2(2 BYTE), 
	"CTIPVEH" VARCHAR2(3 BYTE), 
	"SCLAVEH" NUMBER, 
	"CCLADEF" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODIAUTCLAVEH"."CCLAVEH" IS 'Código de la Clase de Vehículo';
   COMMENT ON COLUMN "AXIS"."CODIAUTCLAVEH"."CTIPVEH" IS 'Codigo del tipo de vehiculo';
   COMMENT ON TABLE "AXIS"."CODIAUTCLAVEH"  IS 'Tabla los Códigos de Clases de Vehículos';
  GRANT UPDATE ON "AXIS"."CODIAUTCLAVEH" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODIAUTCLAVEH" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODIAUTCLAVEH" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODIAUTCLAVEH" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODIAUTCLAVEH" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODIAUTCLAVEH" TO "PROGRAMADORESCSI";
