--------------------------------------------------------
--  DDL for Table CODLITERALES_AXIS
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODLITERALES_AXIS" 
   (	"SLITERA" NUMBER(6,0), 
	"CLITERA" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODLITERALES_AXIS"."SLITERA" IS 'Secuencia del literal';
   COMMENT ON COLUMN "AXIS"."CODLITERALES_AXIS"."CLITERA" IS 'Tipo de literal';
  GRANT UPDATE ON "AXIS"."CODLITERALES_AXIS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODLITERALES_AXIS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODLITERALES_AXIS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODLITERALES_AXIS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODLITERALES_AXIS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODLITERALES_AXIS" TO "PROGRAMADORESCSI";
