--------------------------------------------------------
--  DDL for Table CODMORPAR_GARANPRO
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODMORPAR_GARANPRO" 
   (	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CACTIVI" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0), 
	"SCODMORPAR" NUMBER, 
	"FINI_VIG" DATE, 
	"FFIN_VIG" DATE, 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIF" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODMORPAR_GARANPRO"."CRAMO" IS 'Código ramo';
   COMMENT ON COLUMN "AXIS"."CODMORPAR_GARANPRO"."CMODALI" IS 'Código modalidad';
   COMMENT ON COLUMN "AXIS"."CODMORPAR_GARANPRO"."CTIPSEG" IS 'Código tipo de seguro';
   COMMENT ON COLUMN "AXIS"."CODMORPAR_GARANPRO"."CCOLECT" IS 'Código de colectividad';
   COMMENT ON COLUMN "AXIS"."CODMORPAR_GARANPRO"."CACTIVI" IS 'Código de actividad';
   COMMENT ON COLUMN "AXIS"."CODMORPAR_GARANPRO"."CGARANT" IS 'Código de garantía';
   COMMENT ON COLUMN "AXIS"."CODMORPAR_GARANPRO"."SCODMORPAR" IS 'Sequence fk de CodMortalidad_par';
   COMMENT ON COLUMN "AXIS"."CODMORPAR_GARANPRO"."FINI_VIG" IS 'Fecha inicio vigencia';
   COMMENT ON COLUMN "AXIS"."CODMORPAR_GARANPRO"."FFIN_VIG" IS 'Fecha fin vigencia';
   COMMENT ON COLUMN "AXIS"."CODMORPAR_GARANPRO"."CUSUALT" IS 'Código usuario de alta del registro';
   COMMENT ON COLUMN "AXIS"."CODMORPAR_GARANPRO"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."CODMORPAR_GARANPRO"."CUSUMOD" IS 'Código usuario que modifica el registro';
   COMMENT ON COLUMN "AXIS"."CODMORPAR_GARANPRO"."FMODIF" IS 'Fecha de modificación';
   COMMENT ON TABLE "AXIS"."CODMORPAR_GARANPRO"  IS 'Parámetros de Mortalidad asociadas a la garantia del producto. Relaciona GaranPro y CodMortalidad_Par';
  GRANT UPDATE ON "AXIS"."CODMORPAR_GARANPRO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODMORPAR_GARANPRO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODMORPAR_GARANPRO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODMORPAR_GARANPRO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODMORPAR_GARANPRO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODMORPAR_GARANPRO" TO "PROGRAMADORESCSI";
