--------------------------------------------------------
--  DDL for Table CODTIPIMP
--------------------------------------------------------

  CREATE TABLE "AXIS"."CODTIPIMP" 
   (	"CTIPIMP" NUMBER(1,0), 
	"CPROGRA" VARCHAR2(100 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"CIMPSOL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CODTIPIMP"."CTIPIMP" IS 'Codi del tipus impresió';
   COMMENT ON COLUMN "AXIS"."CODTIPIMP"."CPROGRA" IS 'Nom del report a emprar';
  GRANT UPDATE ON "AXIS"."CODTIPIMP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODTIPIMP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CODTIPIMP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CODTIPIMP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODTIPIMP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODTIPIMP" TO "PROGRAMADORESCSI";
