--------------------------------------------------------
--  DDL for Table COMCONVENIOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."COMCONVENIOS" 
   (	"CEMPRES" NUMBER(5,0), 
	"SCOMCONV" NUMBER(8,0), 
	"TCONVENIO" VARCHAR2(100 BYTE), 
	"CAGENTE" NUMBER, 
	"FANUL" DATE, 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."COMCONVENIOS"."CEMPRES" IS 'Código de empresa';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS"."SCOMCONV" IS 'Código sobrecomisión convenio';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS"."TCONVENIO" IS 'Descripción sobrecomisión convenio';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS"."FANUL" IS 'Fecha de anulación';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS"."FMODIFI" IS 'Fecha de modificación';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS"."CUSUMOD" IS 'Usuario de modificación';
   COMMENT ON TABLE "AXIS"."COMCONVENIOS"  IS 'Sobrecomisiones convenio';
  GRANT UPDATE ON "AXIS"."COMCONVENIOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."COMCONVENIOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."COMCONVENIOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."COMCONVENIOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."COMCONVENIOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."COMCONVENIOS" TO "PROGRAMADORESCSI";
