--------------------------------------------------------
--  DDL for Table COMCONVENIOS_PROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."COMCONVENIOS_PROD" 
   (	"CEMPRES" NUMBER(5,0), 
	"SCOMCONV" NUMBER(8,0), 
	"SPRODUC" VARCHAR2(100 BYTE), 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_PROD"."CEMPRES" IS 'Código de empresa';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_PROD"."SCOMCONV" IS 'Código sobrecomisión convenio';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_PROD"."SPRODUC" IS 'Código de producto';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_PROD"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_PROD"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_PROD"."FMODIFI" IS 'Fecha de modificación';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_PROD"."CUSUMOD" IS 'Usuario de modificación';
   COMMENT ON TABLE "AXIS"."COMCONVENIOS_PROD"  IS 'Sobrecomisiones convenio - productos';
  GRANT UPDATE ON "AXIS"."COMCONVENIOS_PROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."COMCONVENIOS_PROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."COMCONVENIOS_PROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."COMCONVENIOS_PROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."COMCONVENIOS_PROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."COMCONVENIOS_PROD" TO "PROGRAMADORESCSI";
