--------------------------------------------------------
--  DDL for Table COMCONVENIOS_FEC
--------------------------------------------------------

  CREATE TABLE "AXIS"."COMCONVENIOS_FEC" 
   (	"CEMPRES" NUMBER(5,0), 
	"SCOMCONV" NUMBER(8,0), 
	"FINIVIG" DATE, 
	"FFINVIG" DATE, 
	"IMPORTE" NUMBER, 
	"CESTADO" NUMBER(1,0) DEFAULT 0, 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_FEC"."CEMPRES" IS 'Código de empresa';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_FEC"."SCOMCONV" IS 'Código sobrecomisión convenio';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_FEC"."FINIVIG" IS 'Fecha inicio vigencia convenio';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_FEC"."FFINVIG" IS 'Fecha fin vigencia convenio';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_FEC"."IMPORTE" IS 'Importe producción convenio';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_FEC"."CESTADO" IS 'Indica el estado de la vigencia: 0 - Modificable, 1 - No modificable';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_FEC"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_FEC"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_FEC"."FMODIFI" IS 'Fecha de modificación';
   COMMENT ON COLUMN "AXIS"."COMCONVENIOS_FEC"."CUSUMOD" IS 'Usuario de modificación';
   COMMENT ON TABLE "AXIS"."COMCONVENIOS_FEC"  IS 'Sobrecomisiones convenio - Fechas';
  GRANT UPDATE ON "AXIS"."COMCONVENIOS_FEC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."COMCONVENIOS_FEC" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."COMCONVENIOS_FEC" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."COMCONVENIOS_FEC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."COMCONVENIOS_FEC" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."COMCONVENIOS_FEC" TO "PROGRAMADORESCSI";
