--------------------------------------------------------
--  DDL for Table COMISIONCAMP
--------------------------------------------------------

  CREATE TABLE "AXIS"."COMISIONCAMP" 
   (	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CACTIVI" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0), 
	"CCAMPANYA" NUMBER(3,0), 
	"NVERSION" NUMBER(3,0), 
	"CCOMISI" NUMBER, 
	"CMODCOM" NUMBER(1,0), 
	"PCOMISI" NUMBER(6,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."COMISIONCAMP"."CRAMO" IS 'Código de Ramo';
   COMMENT ON COLUMN "AXIS"."COMISIONCAMP"."CMODALI" IS 'Código de Modalidad';
   COMMENT ON COLUMN "AXIS"."COMISIONCAMP"."CTIPSEG" IS 'Código de Tipo de Seguro';
   COMMENT ON COLUMN "AXIS"."COMISIONCAMP"."CCOLECT" IS 'Código de Colectividad';
   COMMENT ON COLUMN "AXIS"."COMISIONCAMP"."CACTIVI" IS 'Código de Actividad';
   COMMENT ON COLUMN "AXIS"."COMISIONCAMP"."CGARANT" IS 'Código de Garantía';
   COMMENT ON COLUMN "AXIS"."COMISIONCAMP"."CCAMPANYA" IS 'Código de Campaña';
   COMMENT ON COLUMN "AXIS"."COMISIONCAMP"."NVERSION" IS 'Versión Campaña';
   COMMENT ON COLUMN "AXIS"."COMISIONCAMP"."CCOMISI" IS 'Código de Comisión';
   COMMENT ON COLUMN "AXIS"."COMISIONCAMP"."CMODCOM" IS 'Modalidad de la Comisión. CVALOR: 67';
   COMMENT ON COLUMN "AXIS"."COMISIONCAMP"."PCOMISI" IS 'Porcentaje de Comisión';
   COMMENT ON TABLE "AXIS"."COMISIONCAMP"  IS 'Comisiones a nivel de Campaña';
  GRANT UPDATE ON "AXIS"."COMISIONCAMP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."COMISIONCAMP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."COMISIONCAMP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."COMISIONCAMP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."COMISIONCAMP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."COMISIONCAMP" TO "PROGRAMADORESCSI";
