--------------------------------------------------------
--  DDL for Table COMIDEF
--------------------------------------------------------

  CREATE TABLE "AXIS"."COMIDEF" 
   (	"CTIPO" NUMBER(1,0), 
	"NDESDE" NUMBER(3,0), 
	"NHASTA" NUMBER(3,0), 
	"PCOMISI" NUMBER(5,2), 
	"CFORPAG" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."COMIDEF"."CTIPO" IS 'Tipo de garantía';
   COMMENT ON COLUMN "AXIS"."COMIDEF"."NDESDE" IS 'Edad en la contratación inicial';
   COMMENT ON COLUMN "AXIS"."COMIDEF"."NHASTA" IS 'Edad de contratación final';
   COMMENT ON COLUMN "AXIS"."COMIDEF"."PCOMISI" IS 'Porcentaje a aplicar';
   COMMENT ON COLUMN "AXIS"."COMIDEF"."CFORPAG" IS 'Forma de pago (prima periodica.  Prima única)';
   COMMENT ON TABLE "AXIS"."COMIDEF"  IS 'Tabla de parametrización de comisiones';
  GRANT UPDATE ON "AXIS"."COMIDEF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."COMIDEF" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."COMIDEF" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."COMIDEF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."COMIDEF" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."COMIDEF" TO "PROGRAMADORESCSI";
