--------------------------------------------------------
--  DDL for Table COMRECIBO
--------------------------------------------------------

  CREATE TABLE "AXIS"."COMRECIBO" 
   (	"NRECIBO" NUMBER, 
	"NNUMCOM" NUMBER(6,0), 
	"CAGENTE" NUMBER, 
	"CESTREC" NUMBER(1,0), 
	"FMOVDIA" DATE, 
	"FCONTAB" DATE, 
	"ICOMBRU" NUMBER, 
	"ICOMRET" NUMBER, 
	"ICOMDEV" NUMBER, 
	"IRETDEV" NUMBER, 
	"NMOVIMI" NUMBER(4,0), 
	"ICOMBRU_MONCIA" NUMBER, 
	"ICOMRET_MONCIA" NUMBER, 
	"ICOMDEV_MONCIA" NUMBER, 
	"IRETDEV_MONCIA" NUMBER, 
	"FCAMBIO" DATE, 
	"CGARANT" NUMBER(4,0), 
	"ICOMCEDIDA" NUMBER, 
	"ICOMCEDIDA_MONCIA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."COMRECIBO"."NRECIBO" IS 'Número de recibo';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."NNUMCOM" IS 'Número calculo comision recibo';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."CESTREC" IS 'Estado del recibo';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."FMOVDIA" IS 'Fecha día que se hace el movimiento';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."FCONTAB" IS 'Fecha contable';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."ICOMBRU" IS 'Comisión bruta';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."ICOMRET" IS 'Retención s/Comisión';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."ICOMDEV" IS 'Comisión devengada';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."IRETDEV" IS 'Retención devengada';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."NMOVIMI" IS 'Número del movimiento que lo genera';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."ICOMBRU_MONCIA" IS 'Comisión bruta en la moneda de la empresa';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."ICOMRET_MONCIA" IS 'Retención s/comisión en la moneda de la empresa';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."ICOMDEV_MONCIA" IS 'Comisión devengada en la moneda de la empresa';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."IRETDEV_MONCIA" IS 'Retención s/comisión devengada en la moneda de la empresa';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."FCAMBIO" IS 'Fecha empleada para el cálculo de los contravalores';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."CGARANT" IS 'Código de la garantía';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."ICOMCEDIDA" IS 'Comisión cedida';
   COMMENT ON COLUMN "AXIS"."COMRECIBO"."ICOMCEDIDA_MONCIA" IS 'Comisión cedida moneda de la empresa';
   COMMENT ON TABLE "AXIS"."COMRECIBO"  IS 'Comisiones del recibo';
  GRANT UPDATE ON "AXIS"."COMRECIBO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."COMRECIBO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."COMRECIBO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."COMRECIBO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."COMRECIBO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."COMRECIBO" TO "PROGRAMADORESCSI";
