--------------------------------------------------------
--  DDL for Table CON_HOMOLOGA_OSIAX
--------------------------------------------------------

  CREATE TABLE "AXIS"."CON_HOMOLOGA_OSIAX" 
   (	"NORDEN" NUMBER, 
	"TOSIRIS" VARCHAR2(100 BYTE), 
	"LABEL_CAMPO_OSI" VARCHAR2(1000 BYTE), 
	"CAMPO_OSI" VARCHAR2(1000 BYTE), 
	"TIPVALOR_OSI" VARCHAR2(1000 BYTE), 
	"TIPCAMPO_OSI" VARCHAR2(1000 BYTE), 
	"TIAXIS" VARCHAR2(1000 BYTE), 
	"LABEL_CAMPO_IAX" VARCHAR2(1000 BYTE), 
	"CAMPO_IAX" VARCHAR2(1000 BYTE), 
	"TIPVALOR_IAX" VARCHAR2(1000 BYTE), 
	"TIPCAMPO_IAX" VARCHAR2(1000 BYTE), 
	"QUERY_INSERT" VARCHAR2(4000 BYTE), 
	"CAMPO_EXTRA" VARCHAR2(4000 BYTE), 
	"QUERY_SELECT" VARCHAR2(4000 BYTE), 
	"CAMPO_EXTRA1" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CON_HOMOLOGA_OSIAX"."TOSIRIS" IS 'Nombre tabla Osiris Ej: S03500';
   COMMENT ON COLUMN "AXIS"."CON_HOMOLOGA_OSIAX"."LABEL_CAMPO_OSI" IS 'Label del campo o del detalle';
   COMMENT ON COLUMN "AXIS"."CON_HOMOLOGA_OSIAX"."CAMPO_OSI" IS 'Nombre campo tabla o valor del detalle Ej: Nombre / 000010';
   COMMENT ON COLUMN "AXIS"."CON_HOMOLOGA_OSIAX"."TIPVALOR_OSI" IS 'Number, Varchar, Date';
   COMMENT ON COLUMN "AXIS"."CON_HOMOLOGA_OSIAX"."TIPCAMPO_OSI" IS ' 1 -> Campo Tabla , 2-> Detalle';
   COMMENT ON COLUMN "AXIS"."CON_HOMOLOGA_OSIAX"."TIAXIS" IS 'Nombre tabla Osiris Ej: Per_Persona';
   COMMENT ON COLUMN "AXIS"."CON_HOMOLOGA_OSIAX"."LABEL_CAMPO_IAX" IS 'Label del campo o del detalle';
   COMMENT ON COLUMN "AXIS"."CON_HOMOLOGA_OSIAX"."CAMPO_IAX" IS 'Nombre campo tabla o valor del detalle Ej: Nombre / 000010';
   COMMENT ON COLUMN "AXIS"."CON_HOMOLOGA_OSIAX"."TIPVALOR_IAX" IS 'Number, Varchar, Date';
   COMMENT ON COLUMN "AXIS"."CON_HOMOLOGA_OSIAX"."TIPCAMPO_IAX" IS ' 1 -> Campo Tabla , 2-> Detalle';
   COMMENT ON COLUMN "AXIS"."CON_HOMOLOGA_OSIAX"."QUERY_SELECT" IS 'Query Select del valor en iAxis para pasar a Osiris';
  GRANT UPDATE ON "AXIS"."CON_HOMOLOGA_OSIAX" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CON_HOMOLOGA_OSIAX" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CON_HOMOLOGA_OSIAX" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CON_HOMOLOGA_OSIAX" TO "R_AXIS";
