--------------------------------------------------------
--  DDL for Table CONDICIONADOPROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."CONDICIONADOPROD" 
   (	"SPRODUC" NUMBER, 
	"FINIEFE" DATE, 
	"NVERSIO" NUMBER, 
	"FFINEFE" DATE, 
	"CCLAUSU" VARCHAR2(255 BYTE), 
	"TVERSION" VARCHAR2(1000 BYTE), 
	"TDESCRIP" VARCHAR2(50 BYTE), 
	"CCONDICIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CONDICIONADOPROD"."SPRODUC" IS 'Inicio de la vigencia del condicionado';
   COMMENT ON COLUMN "AXIS"."CONDICIONADOPROD"."FINIEFE" IS 'Fecha de inicio del condicionado';
   COMMENT ON COLUMN "AXIS"."CONDICIONADOPROD"."NVERSIO" IS 'Versión del condicionado';
   COMMENT ON COLUMN "AXIS"."CONDICIONADOPROD"."FFINEFE" IS 'Fecha final del condicionado';
   COMMENT ON COLUMN "AXIS"."CONDICIONADOPROD"."CCLAUSU" IS 'Codigo de condicionado';
   COMMENT ON COLUMN "AXIS"."CONDICIONADOPROD"."TVERSION" IS 'Select para indicar si aplica la version del condicionado.Si garantias, si exlcusiones, si...';
   COMMENT ON COLUMN "AXIS"."CONDICIONADOPROD"."TDESCRIP" IS 'Descripció única del condicionat';
   COMMENT ON TABLE "AXIS"."CONDICIONADOPROD"  IS 'Identificador del producto ->productos.sproduc';
  GRANT UPDATE ON "AXIS"."CONDICIONADOPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONDICIONADOPROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CONDICIONADOPROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CONDICIONADOPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONDICIONADOPROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CONDICIONADOPROD" TO "PROGRAMADORESCSI";
