--------------------------------------------------------
--  DDL for Table CONDICIONADOPRODDET
--------------------------------------------------------

  CREATE TABLE "AXIS"."CONDICIONADOPRODDET" 
   (	"CIDIOMA" NUMBER, 
	"TTTITULO" VARCHAR2(400 BYTE), 
	"CCONDICIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CONDICIONADOPRODDET"."CIDIOMA" IS 'Idioma -> idiomas.cidioma';
   COMMENT ON TABLE "AXIS"."CONDICIONADOPRODDET"  IS 'Condicionados generales , descripcion';
  GRANT UPDATE ON "AXIS"."CONDICIONADOPRODDET" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONDICIONADOPRODDET" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CONDICIONADOPRODDET" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CONDICIONADOPRODDET" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONDICIONADOPRODDET" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CONDICIONADOPRODDET" TO "PROGRAMADORESCSI";
