--------------------------------------------------------
--  DDL for Table CONTAB_MANU_DIA
--------------------------------------------------------

  CREATE TABLE "AXIS"."CONTAB_MANU_DIA" 
   (	"CEMPRES" NUMBER(2,0), 
	"FCONTA" DATE, 
	"NASIENT" NUMBER(8,0), 
	"NLINEA" NUMBER(6,0), 
	"CCUENTA" VARCHAR2(50 BYTE), 
	"CPROCES" NUMBER, 
	"FEFEADM" DATE, 
	"CPAIS" NUMBER(3,0), 
	"TAPUNTE" VARCHAR2(1 BYTE), 
	"IAPUNTE" NUMBER(17,2), 
	"TDESCRI" VARCHAR2(200 BYTE), 
	"FTRASPASO" DATE, 
	"CENLACE" VARCHAR2(20 BYTE), 
	"CLAVEASI" VARCHAR2(20 BYTE), 
	"TIPODIARIO" VARCHAR2(20 BYTE), 
	"FASIENTO" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."CEMPRES" IS 'Código de Empresa';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."FCONTA" IS 'Fecha en la que se envía a contabilidad';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."NASIENT" IS 'Nº de asiento. Corresponde a la secuencia del módulo contable';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."NLINEA" IS 'Nº de línea en este asiento';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."CCUENTA" IS 'Código de cuenta';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."CPROCES" IS 'Identificador del proceso que lo ha generado';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."FEFEADM" IS 'Fecha administración';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."CPAIS" IS 'Pais de residencia';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."TAPUNTE" IS 'Tipo de apunte (D= Debe; H= Haber)';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."IAPUNTE" IS 'Importe del apunte';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."TDESCRI" IS 'Descripción de la cuenta';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."FTRASPASO" IS 'Fecha en que se ha traspasado a contabilidad. Puede ser nulo.';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."CENLACE" IS 'Clave Enlace';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."CLAVEASI" IS 'Clave Asiento';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."TIPODIARIO" IS 'Tipo Diario';
   COMMENT ON COLUMN "AXIS"."CONTAB_MANU_DIA"."FASIENTO" IS 'Fecha que se informará al sistema contable como fecha en la que se contabiliza.';
   COMMENT ON TABLE "AXIS"."CONTAB_MANU_DIA"  IS 'Contabilidad diaria';
  GRANT UPDATE ON "AXIS"."CONTAB_MANU_DIA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONTAB_MANU_DIA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CONTAB_MANU_DIA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CONTAB_MANU_DIA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONTAB_MANU_DIA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CONTAB_MANU_DIA" TO "PROGRAMADORESCSI";
