--------------------------------------------------------
--  DDL for Table CONTROLSAN_USER
--------------------------------------------------------

  CREATE TABLE "AXIS"."CONTROLSAN_USER" 
   (	"CUSUARI" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CONTROLSAN_USER"."CUSUARI" IS 'Código usuario';
   COMMENT ON TABLE "AXIS"."CONTROLSAN_USER"  IS 'Contiene la lista de usuarios que tienen la consideración de perfil gestión compañia';
  GRANT UPDATE ON "AXIS"."CONTROLSAN_USER" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONTROLSAN_USER" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CONTROLSAN_USER" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CONTROLSAN_USER" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONTROLSAN_USER" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CONTROLSAN_USER" TO "PROGRAMADORESCSI";
