--------------------------------------------------------
--  DDL for Table CONTRATOSAGE
--------------------------------------------------------

  CREATE TABLE "AXIS"."CONTRATOSAGE" 
   (	"CEMPRES" NUMBER(2,0), 
	"CAGENTE" NUMBER, 
	"NCONTRATO" NUMBER, 
	"FFIRCON" DATE, 
	"IOBJETI" NUMBER, 
	"CCONTFIR" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CONTRATOSAGE"."CEMPRES" IS 'Código de Empresa';
   COMMENT ON COLUMN "AXIS"."CONTRATOSAGE"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."CONTRATOSAGE"."NCONTRATO" IS 'Número de contrato';
   COMMENT ON COLUMN "AXIS"."CONTRATOSAGE"."FFIRCON" IS 'Fecha de firma del contrato';
  GRANT UPDATE ON "AXIS"."CONTRATOSAGE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONTRATOSAGE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CONTRATOSAGE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CONTRATOSAGE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONTRATOSAGE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CONTRATOSAGE" TO "PROGRAMADORESCSI";
