--------------------------------------------------------
--  DDL for Table CONTROLSAN_EXCEP
--------------------------------------------------------

  CREATE TABLE "AXIS"."CONTROLSAN_EXCEP" 
   (	"CCONTROL" VARCHAR2(4 BYTE), 
	"CAMBITO" VARCHAR2(4 BYTE), 
	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CONTROLSAN_EXCEP"."CCONTROL" IS 'Código de control/validación';
   COMMENT ON COLUMN "AXIS"."CONTROLSAN_EXCEP"."CAMBITO" IS 'Código de ámbito: REEMB, FACT';
  GRANT UPDATE ON "AXIS"."CONTROLSAN_EXCEP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONTROLSAN_EXCEP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CONTROLSAN_EXCEP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CONTROLSAN_EXCEP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONTROLSAN_EXCEP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CONTROLSAN_EXCEP" TO "PROGRAMADORESCSI";
