--------------------------------------------------------
--  DDL for Table CONTACTOS_CORREO
--------------------------------------------------------

  CREATE TABLE "AXIS"."CONTACTOS_CORREO" 
   (	"SCORREO" NUMBER(7,0), 
	"SPERSON" NUMBER(10,0), 
	"TDIRECCION" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CONTACTOS_CORREO"."SCORREO" IS 'Identificador del correo';
   COMMENT ON COLUMN "AXIS"."CONTACTOS_CORREO"."SPERSON" IS 'Oficina (persona), de la que es contacto';
   COMMENT ON COLUMN "AXIS"."CONTACTOS_CORREO"."TDIRECCION" IS 'Dirección de envio, en caso de ser fija';
   COMMENT ON COLUMN "AXIS"."CONTACTOS_CORREO"."DESCRIPCION" IS 'Descripcion del destinatario';
   COMMENT ON TABLE "AXIS"."CONTACTOS_CORREO"  IS 'Destinatario del correo';
  GRANT UPDATE ON "AXIS"."CONTACTOS_CORREO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONTACTOS_CORREO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CONTACTOS_CORREO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CONTACTOS_CORREO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONTACTOS_CORREO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CONTACTOS_CORREO" TO "PROGRAMADORESCSI";
