--------------------------------------------------------
--  DDL for Table CONVENIOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."CONVENIOS" 
   (	"FINIVIG" DATE, 
	"FFINVI" DATE, 
	"TCONVENIO" VARCHAR2(100 BYTE), 
	"CCODCONV" VARCHAR2(7 BYTE), 
	"CIDIOMA" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CONVENIOS"."FINIVIG" IS 'Fecha inicio vigencia';
   COMMENT ON COLUMN "AXIS"."CONVENIOS"."FFINVI" IS 'Fecha fin vigencia';
   COMMENT ON COLUMN "AXIS"."CONVENIOS"."TCONVENIO" IS 'Nombre del convenio';
   COMMENT ON TABLE "AXIS"."CONVENIOS"  IS 'Tabla de convenios';
  GRANT UPDATE ON "AXIS"."CONVENIOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONVENIOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CONVENIOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CONVENIOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CONVENIOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CONVENIOS" TO "PROGRAMADORESCSI";
