--------------------------------------------------------
--  DDL for Table COPY_MIG_BF_BONFRANSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."COPY_MIG_BF_BONFRANSEG" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"MIG_FK2" VARCHAR2(50 BYTE), 
	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER, 
	"NRIESGO" NUMBER, 
	"CGARAN" NUMBER(4,0), 
	"CGRUP" NUMBER(6,0), 
	"CSUBGRUP" NUMBER(6,0), 
	"CNIVEL" NUMBER(6,0), 
	"CVERSION" NUMBER(6,0), 
	"FINIEFE" DATE, 
	"CTIPGRUP" VARCHAR2(1 BYTE), 
	"CVALOR1" NUMBER(2,0), 
	"IMPVALOR1" NUMBER, 
	"CVALOR2" NUMBER(2,0), 
	"IMPVALOR2" NUMBER, 
	"CIMPMIN" NUMBER(2,0), 
	"IMPMIN" NUMBER, 
	"CIMPMAX" NUMBER(2,0), 
	"IMPMAX" NUMBER, 
	"FFINEFE" DATE, 
	"CUSUAUT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"CNIVELDEFECTO" NUMBER(6,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;
  GRANT DELETE ON "AXIS"."COPY_MIG_BF_BONFRANSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."COPY_MIG_BF_BONFRANSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."COPY_MIG_BF_BONFRANSEG" TO "R_AXIS";
  GRANT UPDATE ON "AXIS"."COPY_MIG_BF_BONFRANSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."COPY_MIG_BF_BONFRANSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."COPY_MIG_BF_BONFRANSEG" TO "PROGRAMADORESCSI";
