--------------------------------------------------------
--  DDL for Table CTACTES
--------------------------------------------------------

  CREATE TABLE "AXIS"."CTACTES" 
   (	"CAGENTE" NUMBER, 
	"NNUMLIN" NUMBER(6,0), 
	"CDEBHAB" NUMBER(1,0), 
	"CCONCTA" NUMBER(2,0), 
	"CESTADO" NUMBER(1,0), 
	"NDOCUME" VARCHAR2(10 BYTE), 
	"FFECMOV" DATE, 
	"IIMPORT" NUMBER, 
	"TDESCRIP" VARCHAR2(100 BYTE), 
	"CMANUAL" NUMBER(1,0), 
	"CEMPRES" NUMBER(2,0), 
	"NRECIBO" NUMBER, 
	"NSINIES" NUMBER(8,0), 
	"SSEGURO" NUMBER, 
	"FVALOR" DATE, 
	"SPROCES" NUMBER, 
	"CFISCAL" NUMBER(1,0), 
	"NNUMLIN_DEPEN" NUMBER(6,0), 
	"SPRODUC" NUMBER(8,0) DEFAULT 0, 
	"CCOMPANI" NUMBER(2,0) DEFAULT 0, 
	"CTIPOLIQ" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CTACTES"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."CTACTES"."NNUMLIN" IS 'Número de línea';
   COMMENT ON COLUMN "AXIS"."CTACTES"."CDEBHAB" IS 'Código DEBE o HABER';
   COMMENT ON COLUMN "AXIS"."CTACTES"."CCONCTA" IS 'Código concepto cta. corriente.';
   COMMENT ON COLUMN "AXIS"."CTACTES"."CESTADO" IS 'Estado del apunte.  0 :Liquidado, 1:pendiente,';
   COMMENT ON COLUMN "AXIS"."CTACTES"."NDOCUME" IS 'Número de documento';
   COMMENT ON COLUMN "AXIS"."CTACTES"."FFECMOV" IS 'Fecha de movimiento';
   COMMENT ON COLUMN "AXIS"."CTACTES"."IIMPORT" IS 'Importe';
   COMMENT ON COLUMN "AXIS"."CTACTES"."TDESCRIP" IS 'Texto';
   COMMENT ON COLUMN "AXIS"."CTACTES"."CMANUAL" IS 'Manual o no';
   COMMENT ON COLUMN "AXIS"."CTACTES"."CEMPRES" IS 'Código Empresa';
   COMMENT ON COLUMN "AXIS"."CTACTES"."NRECIBO" IS 'Número de recibo';
   COMMENT ON COLUMN "AXIS"."CTACTES"."NSINIES" IS 'Núemro de siniestro';
   COMMENT ON COLUMN "AXIS"."CTACTES"."SSEGURO" IS 'Código de la póliza';
   COMMENT ON COLUMN "AXIS"."CTACTES"."FVALOR" IS 'Fecha valor';
   COMMENT ON COLUMN "AXIS"."CTACTES"."SPROCES" IS 'Sproces de la liquidación (tabla cierres)';
   COMMENT ON COLUMN "AXIS"."CTACTES"."CFISCAL" IS 'Apunte manual fiscal o no / Detvalores 800017';
   COMMENT ON COLUMN "AXIS"."CTACTES"."NNUMLIN_DEPEN" IS 'Línea de la cual depende el concepto automático';
   COMMENT ON COLUMN "AXIS"."CTACTES"."SPRODUC" IS 'Sproduc de agrupamiento, default 0';
   COMMENT ON COLUMN "AXIS"."CTACTES"."CCOMPANI" IS 'Código de la compania';
   COMMENT ON COLUMN "AXIS"."CTACTES"."CTIPOLIQ" IS 'Tipo de liquidación Vf.:1038';
  GRANT UPDATE ON "AXIS"."CTACTES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CTACTES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CTACTES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CTACTES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CTACTES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CTACTES" TO "PROGRAMADORESCSI";
