--------------------------------------------------------
--  DDL for Table CTASEGURO_DETALLE_PREVIO
--------------------------------------------------------

  CREATE TABLE "AXIS"."CTASEGURO_DETALLE_PREVIO" 
   (	"SSEGURO" NUMBER, 
	"NNUMLIN" NUMBER(6,0), 
	"FCONTAB" DATE, 
	"CCAMPO" VARCHAR2(8 BYTE), 
	"VALOR" NUMBER, 
	"SPROCES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CTASEGURO_DETALLE_PREVIO"."SSEGURO" IS 'Identificador del seguro';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_DETALLE_PREVIO"."NNUMLIN" IS 'Número de línea de ctaseguro';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_DETALLE_PREVIO"."FCONTAB" IS 'Fecha contable';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_DETALLE_PREVIO"."CCAMPO" IS 'Concepto de desglose';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_DETALLE_PREVIO"."VALOR" IS 'Valor del campo';
   COMMENT ON TABLE "AXIS"."CTASEGURO_DETALLE_PREVIO"  IS 'Previo del Desglose de información en CTASEGURO';
  GRANT UPDATE ON "AXIS"."CTASEGURO_DETALLE_PREVIO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CTASEGURO_DETALLE_PREVIO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CTASEGURO_DETALLE_PREVIO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CTASEGURO_DETALLE_PREVIO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CTASEGURO_DETALLE_PREVIO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CTASEGURO_DETALLE_PREVIO" TO "PROGRAMADORESCSI";
