--------------------------------------------------------
--  DDL for Table CTASEGURO_PREVIO_SHW
--------------------------------------------------------

  CREATE TABLE "AXIS"."CTASEGURO_PREVIO_SHW" 
   (	"SSEGURO" NUMBER, 
	"FCONTAB" DATE, 
	"NNUMLIN" NUMBER(6,0), 
	"FFECMOV" DATE, 
	"FVALMOV" DATE, 
	"CMOVIMI" NUMBER(2,0), 
	"IMOVIMI" NUMBER, 
	"CCALINT" NUMBER(15,0), 
	"IMOVIM2" NUMBER, 
	"NRECIBO" NUMBER, 
	"NSINIES" VARCHAR2(14 BYTE), 
	"CMOVANU" NUMBER(1,0), 
	"SMOVREC" NUMBER, 
	"CESTA" NUMBER(3,0), 
	"NUNIDAD" NUMBER(15,6), 
	"CESTADO" VARCHAR2(1 BYTE), 
	"FASIGN" DATE, 
	"NPARPLA" NUMBER(15,6), 
	"CESTPAR" VARCHAR2(1 BYTE), 
	"IEXCESO" NUMBER, 
	"SPERMIN" NUMBER(10,0), 
	"SIDEPAG" NUMBER(8,0), 
	"SPROCES" NUMBER, 
	"SRECREN" NUMBER(8,0), 
	"NSIN1" VARCHAR2(14 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."SSEGURO" IS 'Identificador del seguro';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."FCONTAB" IS 'Fecha contable';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."NNUMLIN" IS 'Número de línea de ctaseguro';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."FFECMOV" IS 'Fecha de efecto del movimiento';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."FVALMOV" IS 'Fecha valor del movimiento';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."CMOVIMI" IS 'Código de movimiento';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."IMOVIMI" IS 'Importe movimiento';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."CCALINT" IS 'Indicador cálculo de intereses (Deprecated). Agrupaciones de movimientos en CTASEGURO. Sequence: SCAGRCTA';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."IMOVIM2" IS 'Importe movimiento 2';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."NRECIBO" IS 'Número de recibo';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."NSINIES" IS 'Número de siniestro';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."CMOVANU" IS 'Indicador movimiento anulado';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."IEXCESO" IS 'Exceso planes pensiones';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."SPROCES" IS 'Código de proceso del previo';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."SRECREN" IS 'Identificador pago renta';
   COMMENT ON COLUMN "AXIS"."CTASEGURO_PREVIO_SHW"."NSIN1" IS 'Copia de nsines por seguridad';
   COMMENT ON TABLE "AXIS"."CTASEGURO_PREVIO_SHW"  IS 'SE UTILIZARÁ EN EL CIERRE PREVIO DE AHORRO';
  GRANT UPDATE ON "AXIS"."CTASEGURO_PREVIO_SHW" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CTASEGURO_PREVIO_SHW" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CTASEGURO_PREVIO_SHW" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CTASEGURO_PREVIO_SHW" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CTASEGURO_PREVIO_SHW" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CTASEGURO_PREVIO_SHW" TO "PROGRAMADORESCSI";
