--------------------------------------------------------
--  DDL for Table CTATECNICA
--------------------------------------------------------

  CREATE TABLE "AXIS"."CTATECNICA" 
   (	"CCOMPANI" NUMBER(3,0), 
	"NVERSIO" NUMBER(2,0), 
	"SCONTRA" NUMBER(6,0), 
	"CTRAMO" NUMBER(2,0), 
	"NCTATEC" NUMBER(4,0), 
	"CFRECUL" NUMBER(2,0), 
	"CESTADO" NUMBER(2,0), 
	"FESTADO" DATE, 
	"FULTIMP" DATE, 
	"FCIERRE" DATE, 
	"CEMPRES" NUMBER(2,0), 
	"SPRODUC" NUMBER(6,0), 
	"CCORRED" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CTATECNICA"."CCOMPANI" IS 'Código de compañia';
   COMMENT ON COLUMN "AXIS"."CTATECNICA"."NVERSIO" IS 'Número versión contrato reas.';
   COMMENT ON COLUMN "AXIS"."CTATECNICA"."CTRAMO" IS 'Código del tramo';
   COMMENT ON COLUMN "AXIS"."CTATECNICA"."NCTATEC" IS 'Número de la Cuenta Técnica';
   COMMENT ON COLUMN "AXIS"."CTATECNICA"."CFRECUL" IS 'Código de frecuencia de liquidación';
   COMMENT ON COLUMN "AXIS"."CTATECNICA"."CESTADO" IS 'Código del estado de la cuenta técnica';
   COMMENT ON COLUMN "AXIS"."CTATECNICA"."FESTADO" IS 'Fecha de bloqueo cuenta técnica';
   COMMENT ON COLUMN "AXIS"."CTATECNICA"."FULTIMP" IS 'Fecha última impresión';
   COMMENT ON COLUMN "AXIS"."CTATECNICA"."FCIERRE" IS 'Fecha cierre ';
   COMMENT ON COLUMN "AXIS"."CTATECNICA"."CEMPRES" IS 'Código de Empresa';
   COMMENT ON COLUMN "AXIS"."CTATECNICA"."SPRODUC" IS 'Secuencia del producto';
   COMMENT ON COLUMN "AXIS"."CTATECNICA"."CCORRED" IS 'Código de Corredor/Broker';
  GRANT UPDATE ON "AXIS"."CTATECNICA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CTATECNICA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CTATECNICA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CTATECNICA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CTATECNICA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CTATECNICA" TO "PROGRAMADORESCSI";
