--------------------------------------------------------
--  DDL for Table CTGAR_INMUEBLE
--------------------------------------------------------

  CREATE TABLE "AXIS"."CTGAR_INMUEBLE" 
   (	"SINMUEBLE" NUMBER, 
	"NNUMESCR" NUMBER, 
	"FESCRITURA" DATE, 
	"TDESCRIPCION" VARCHAR2(1000 BYTE), 
	"TDIRECCION" VARCHAR2(1000 BYTE), 
	"CPAIS" NUMBER(3,0), 
	"CPROVIN" NUMBER, 
	"CPOBLAC" NUMBER, 
	"FCERTLIB" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CTGAR_INMUEBLE"."SINMUEBLE" IS 'Identificador único / Secuencia del inmueble';
   COMMENT ON COLUMN "AXIS"."CTGAR_INMUEBLE"."NNUMESCR" IS 'Numero de la escritura publica';
   COMMENT ON COLUMN "AXIS"."CTGAR_INMUEBLE"."FESCRITURA" IS 'Fecha de la escritura';
   COMMENT ON COLUMN "AXIS"."CTGAR_INMUEBLE"."TDESCRIPCION" IS 'Descripción general';
   COMMENT ON COLUMN "AXIS"."CTGAR_INMUEBLE"."TDIRECCION" IS 'Dirección del inmueble';
   COMMENT ON COLUMN "AXIS"."CTGAR_INMUEBLE"."CPAIS" IS 'Pais';
   COMMENT ON COLUMN "AXIS"."CTGAR_INMUEBLE"."CPROVIN" IS 'Codigo de Provincia';
   COMMENT ON COLUMN "AXIS"."CTGAR_INMUEBLE"."CPOBLAC" IS 'Municipio';
   COMMENT ON COLUMN "AXIS"."CTGAR_INMUEBLE"."FCERTLIB" IS 'Certificado libertad';
  GRANT UPDATE ON "AXIS"."CTGAR_INMUEBLE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CTGAR_INMUEBLE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CTGAR_INMUEBLE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CTGAR_INMUEBLE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CTGAR_INMUEBLE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CTGAR_INMUEBLE" TO "PROGRAMADORESCSI";
