--------------------------------------------------------
--  DDL for Table CTRL_PROVIS
--------------------------------------------------------

  CREATE TABLE "AXIS"."CTRL_PROVIS" 
   (	"CEMPRES" NUMBER(2,0), 
	"FCALCUL" DATE, 
	"FMODIFI" DATE, 
	"CPROVIS" NUMBER(2,0), 
	"SPROCES" NUMBER, 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"CERROR" NUMBER(1,0), 
	"FCONTAB" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."CTRL_PROVIS"."FCONTAB" IS 'Fecha contable';
  GRANT UPDATE ON "AXIS"."CTRL_PROVIS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CTRL_PROVIS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."CTRL_PROVIS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."CTRL_PROVIS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CTRL_PROVIS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CTRL_PROVIS" TO "PROGRAMADORESCSI";
