--------------------------------------------------------
--  DDL for Table DELPER_IDENTIFICADOR
--------------------------------------------------------

  CREATE TABLE "AXIS"."DELPER_IDENTIFICADOR" 
   (	"CUSUARIDEL" VARCHAR2(40 BYTE), 
	"FDEL" DATE, 
	"SPERSON" NUMBER(10,0), 
	"CAGENTE" NUMBER, 
	"CTIPIDE" NUMBER(3,0), 
	"NNUMIDE" VARCHAR2(50 BYTE), 
	"SWIDEPRI" NUMBER(1,0), 
	"FEMISIO" DATE, 
	"FCADUCA" DATE, 
	"CPAISEXP" NUMBER(5,0), 
	"CDEPARTEXP" NUMBER(10,0), 
	"CCIUDADEXP" NUMBER(5,0), 
	"FECHADEXP" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DELPER_IDENTIFICADOR"."SPERSON" IS 'Identificador de Persona';
   COMMENT ON COLUMN "AXIS"."DELPER_IDENTIFICADOR"."CTIPIDE" IS 'Código del tipo de identificador (v.f. 672)';
   COMMENT ON COLUMN "AXIS"."DELPER_IDENTIFICADOR"."NNUMIDE" IS 'Número de Identificador';
   COMMENT ON COLUMN "AXIS"."DELPER_IDENTIFICADOR"."SWIDEPRI" IS 'Indica si el identificador es el principal';
   COMMENT ON COLUMN "AXIS"."DELPER_IDENTIFICADOR"."FEMISIO" IS 'Fecha de emisión';
   COMMENT ON COLUMN "AXIS"."DELPER_IDENTIFICADOR"."FCADUCA" IS 'Fecha de caducidad';
   COMMENT ON COLUMN "AXIS"."DELPER_IDENTIFICADOR"."CPAISEXP" IS 'Pais de Expedicion';
   COMMENT ON COLUMN "AXIS"."DELPER_IDENTIFICADOR"."CDEPARTEXP" IS 'Departamenteo de Expedicion';
   COMMENT ON COLUMN "AXIS"."DELPER_IDENTIFICADOR"."CCIUDADEXP" IS 'Ciudad de Expedicion';
   COMMENT ON COLUMN "AXIS"."DELPER_IDENTIFICADOR"."FECHADEXP" IS 'Fecha de Expedicion';
   COMMENT ON TABLE "AXIS"."DELPER_IDENTIFICADOR"  IS 'Tabla que guarda los diferentes identificadores que puede tener una persona';
  GRANT UPDATE ON "AXIS"."DELPER_IDENTIFICADOR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DELPER_IDENTIFICADOR" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DELPER_IDENTIFICADOR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DELPER_IDENTIFICADOR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DELPER_IDENTIFICADOR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DELPER_IDENTIFICADOR" TO "PROGRAMADORESCSI";
