--------------------------------------------------------
--  DDL for Table DESCVIG
--------------------------------------------------------

  CREATE TABLE "AXIS"."DESCVIG" 
   (	"CDESC" NUMBER(2,0), 
	"FINIVIG" DATE, 
	"FFINVIG" DATE, 
	"CESTADO" NUMBER(2,0), 
	"FALTA" DATE, 
	"CUSUALTA" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DESCVIG"."CDESC" IS 'Código descuento';
   COMMENT ON COLUMN "AXIS"."DESCVIG"."FINIVIG" IS 'Fecha inicio vigencia';
   COMMENT ON COLUMN "AXIS"."DESCVIG"."FFINVIG" IS 'Fecha fin vigencia';
   COMMENT ON COLUMN "AXIS"."DESCVIG"."CESTADO" IS 'Estado';
   COMMENT ON COLUMN "AXIS"."DESCVIG"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."DESCVIG"."CUSUALTA" IS 'Usuario alta';
   COMMENT ON COLUMN "AXIS"."DESCVIG"."FMODIFI" IS 'Fecha modificacion';
   COMMENT ON COLUMN "AXIS"."DESCVIG"."CUSUMOD" IS 'Usuario de modificacion';
   COMMENT ON TABLE "AXIS"."DESCVIG"  IS 'Vigencias de Descuentos';
  GRANT UPDATE ON "AXIS"."DESCVIG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESCVIG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DESCVIG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DESCVIG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESCVIG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DESCVIG" TO "PROGRAMADORESCSI";
