--------------------------------------------------------
--  DDL for Table DESCUENTA
--------------------------------------------------------

  CREATE TABLE "AXIS"."DESCUENTA" 
   (	"CCUENTA" VARCHAR2(50 BYTE), 
	"TDESCRI" VARCHAR2(100 BYTE), 
	"TCONDIC" VARCHAR2(200 BYTE), 
	"SLITERA" NUMBER, 
	"CGROUP" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DESCUENTA"."CCUENTA" IS 'Cuenta contable';
   COMMENT ON COLUMN "AXIS"."DESCUENTA"."TDESCRI" IS 'Descripción de la cuenta contable';
   COMMENT ON COLUMN "AXIS"."DESCUENTA"."TCONDIC" IS 'Condició que se ha de añadir al calcular el apunte';
   COMMENT ON COLUMN "AXIS"."DESCUENTA"."CGROUP" IS 'Indica si se agrupa (1) o no (0) por producto, o por otro (2)';
  GRANT UPDATE ON "AXIS"."DESCUENTA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESCUENTA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DESCUENTA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DESCUENTA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESCUENTA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DESCUENTA" TO "PROGRAMADORESCSI";
