--------------------------------------------------------
--  DDL for Table DESCUMULOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."DESCUMULOS" 
   (	"SCUMULO" NUMBER(6,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TDESCRI" VARCHAR2(40 BYTE), 
	"TOBSERV" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DESCUMULOS"."SCUMULO" IS 'Identificador de un cúmulo';
   COMMENT ON COLUMN "AXIS"."DESCUMULOS"."CIDIOMA" IS 'Código de Idioma';
   COMMENT ON COLUMN "AXIS"."DESCUMULOS"."TDESCRI" IS 'Descripción cúmulo';
   COMMENT ON COLUMN "AXIS"."DESCUMULOS"."TOBSERV" IS 'Observaciones cúmulo';
  GRANT UPDATE ON "AXIS"."DESCUMULOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESCUMULOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DESCUMULOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DESCUMULOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESCUMULOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DESCUMULOS" TO "PROGRAMADORESCSI";
