--------------------------------------------------------
--  DDL for Table DESC_PRIM_MIN
--------------------------------------------------------

  CREATE TABLE "AXIS"."DESC_PRIM_MIN" 
   (	"IDPM" NUMBER(6,0), 
	"CIDIOMA" NUMBER(6,0), 
	"TDESC" VARCHAR2(200 BYTE), 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DESC_PRIM_MIN"."IDPM" IS 'Identificador de Prima Mínima';
   COMMENT ON COLUMN "AXIS"."DESC_PRIM_MIN"."CIDIOMA" IS 'Idioma';
   COMMENT ON COLUMN "AXIS"."DESC_PRIM_MIN"."TDESC" IS 'Descripción';
   COMMENT ON COLUMN "AXIS"."DESC_PRIM_MIN"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."DESC_PRIM_MIN"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."DESC_PRIM_MIN"."FMODIFI" IS 'Fecha de modificación';
   COMMENT ON COLUMN "AXIS"."DESC_PRIM_MIN"."CUSUMOD" IS 'Usuario de modificación';
   COMMENT ON TABLE "AXIS"."DESC_PRIM_MIN"  IS 'Indica las descripciones de los diferentes tipos de prima mínima';
  GRANT UPDATE ON "AXIS"."DESC_PRIM_MIN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESC_PRIM_MIN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DESC_PRIM_MIN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DESC_PRIM_MIN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESC_PRIM_MIN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DESC_PRIM_MIN" TO "PROGRAMADORESCSI";
