--------------------------------------------------------
--  DDL for Table DESCOMISIONCONTRA
--------------------------------------------------------

  CREATE TABLE "AXIS"."DESCOMISIONCONTRA" 
   (	"CCOMREA" NUMBER(2,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TDESCRI" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DESCOMISIONCONTRA"."CCOMREA" IS 'Código de comisión en contratos de reaseguro';
   COMMENT ON COLUMN "AXIS"."DESCOMISIONCONTRA"."CIDIOMA" IS 'Código del idioma';
   COMMENT ON COLUMN "AXIS"."DESCOMISIONCONTRA"."TDESCRI" IS 'Descripción comisión';
  GRANT UPDATE ON "AXIS"."DESCOMISIONCONTRA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESCOMISIONCONTRA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DESCOMISIONCONTRA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DESCOMISIONCONTRA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESCOMISIONCONTRA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DESCOMISIONCONTRA" TO "PROGRAMADORESCSI";
