--------------------------------------------------------
--  DDL for Table DESDESC
--------------------------------------------------------

  CREATE TABLE "AXIS"."DESDESC" 
   (	"CIDIOMA" NUMBER(2,0), 
	"CDESC" NUMBER(2,0), 
	"TDESC" VARCHAR2(100 BYTE), 
	"FALTA" DATE, 
	"CUSUALTA" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DESDESC"."CIDIOMA" IS 'Código de Idioma';
   COMMENT ON COLUMN "AXIS"."DESDESC"."CDESC" IS 'Código descuento';
   COMMENT ON COLUMN "AXIS"."DESDESC"."TDESC" IS 'Descripción descuento';
   COMMENT ON COLUMN "AXIS"."DESDESC"."FALTA" IS 'Fecha alta descuento';
   COMMENT ON COLUMN "AXIS"."DESDESC"."CUSUALTA" IS 'Usuario alta descuento';
   COMMENT ON COLUMN "AXIS"."DESDESC"."FMODIFI" IS 'Fecha modificación descuento';
   COMMENT ON COLUMN "AXIS"."DESDESC"."CUSUMOD" IS 'Usuario modificación descuento';
   COMMENT ON TABLE "AXIS"."DESDESC"  IS 'Descuento Descripcion';
  GRANT UPDATE ON "AXIS"."DESDESC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESDESC" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DESDESC" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DESDESC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESDESC" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DESDESC" TO "PROGRAMADORESCSI";
