--------------------------------------------------------
--  DDL for Table DESFRANQUICIAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."DESFRANQUICIAS" 
   (	"CFRANQ" NUMBER(6,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TFRANQ" VARCHAR2(100 BYTE), 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CACTIVI" NUMBER(4,0), 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FBAJA" DATE, 
	"CUSUBAJ" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DESFRANQUICIAS"."CFRANQ" IS 'Codigo de FRANQUICIAS';
   COMMENT ON COLUMN "AXIS"."DESFRANQUICIAS"."CIDIOMA" IS 'Codigo idioma';
   COMMENT ON COLUMN "AXIS"."DESFRANQUICIAS"."TFRANQ" IS 'Descripcion de FRANQUICIAS';
   COMMENT ON COLUMN "AXIS"."DESFRANQUICIAS"."CRAMO" IS 'Codigo Ramo';
   COMMENT ON COLUMN "AXIS"."DESFRANQUICIAS"."CMODALI" IS 'Codigo Modalidad';
   COMMENT ON COLUMN "AXIS"."DESFRANQUICIAS"."CTIPSEG" IS 'Codigo tipo seguro';
   COMMENT ON COLUMN "AXIS"."DESFRANQUICIAS"."CCOLECT" IS 'Codigo Colectivo';
   COMMENT ON COLUMN "AXIS"."DESFRANQUICIAS"."FALTA" IS 'Fecha alta';
   COMMENT ON COLUMN "AXIS"."DESFRANQUICIAS"."CUSUALT" IS 'Usuario alta';
   COMMENT ON COLUMN "AXIS"."DESFRANQUICIAS"."FBAJA" IS 'Fecha baja';
   COMMENT ON COLUMN "AXIS"."DESFRANQUICIAS"."CUSUBAJ" IS 'Usuario baja';
   COMMENT ON TABLE "AXIS"."DESFRANQUICIAS"  IS 'Tabla maestra descripcion de FRANQUICIAS';
  GRANT UPDATE ON "AXIS"."DESFRANQUICIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESFRANQUICIAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DESFRANQUICIAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DESFRANQUICIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESFRANQUICIAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DESFRANQUICIAS" TO "PROGRAMADORESCSI";
