--------------------------------------------------------
--  DDL for Table DESGRPPARAM
--------------------------------------------------------

  CREATE TABLE "AXIS"."DESGRPPARAM" 
   (	"CGRPPAR" VARCHAR2(4 BYTE), 
	"CUTILI" NUMBER(4,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TGRPPAR" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DESGRPPARAM"."CGRPPAR" IS 'Código de agrupación';
   COMMENT ON COLUMN "AXIS"."DESGRPPARAM"."CUTILI" IS 'Indicador de dónde se utiliza el parámetro (Productos, garantías, ….) VF. 281';
   COMMENT ON COLUMN "AXIS"."DESGRPPARAM"."CIDIOMA" IS 'Código de idioma';
   COMMENT ON COLUMN "AXIS"."DESGRPPARAM"."TGRPPAR" IS 'Descripción de la agrupación';
  GRANT UPDATE ON "AXIS"."DESGRPPARAM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESGRPPARAM" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DESGRPPARAM" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DESGRPPARAM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESGRPPARAM" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DESGRPPARAM" TO "PROGRAMADORESCSI";
