--------------------------------------------------------
--  DDL for Table DESMODALI
--------------------------------------------------------

  CREATE TABLE "AXIS"."DESMODALI" 
   (	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TMODALI" VARCHAR2(800 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DESMODALI"."CRAMO" IS 'Código ramo';
   COMMENT ON COLUMN "AXIS"."DESMODALI"."CMODALI" IS 'Código modalidad';
   COMMENT ON COLUMN "AXIS"."DESMODALI"."CIDIOMA" IS 'Código de Idioma';
   COMMENT ON COLUMN "AXIS"."DESMODALI"."TMODALI" IS 'Descripción de modalidad';
   COMMENT ON TABLE "AXIS"."DESMODALI"  IS 'Descripción de Modalidad';
  GRANT UPDATE ON "AXIS"."DESMODALI" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESMODALI" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DESMODALI" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DESMODALI" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESMODALI" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DESMODALI" TO "PROGRAMADORESCSI";
