--------------------------------------------------------
--  DDL for Table DESMENSAJE_CORREO
--------------------------------------------------------

  CREATE TABLE "AXIS"."DESMENSAJE_CORREO" 
   (	"SCORREO" NUMBER(7,0), 
	"CIDIOMA" NUMBER, 
	"ASUNTO" VARCHAR2(250 BYTE), 
	"CUERPO" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DESMENSAJE_CORREO"."SCORREO" IS 'Identificador del correo';
   COMMENT ON COLUMN "AXIS"."DESMENSAJE_CORREO"."CIDIOMA" IS 'Idioma del correo';
   COMMENT ON COLUMN "AXIS"."DESMENSAJE_CORREO"."ASUNTO" IS 'Asunto del mail';
   COMMENT ON COLUMN "AXIS"."DESMENSAJE_CORREO"."CUERPO" IS 'Cuerpo del mail';
   COMMENT ON TABLE "AXIS"."DESMENSAJE_CORREO"  IS 'Tabla de correo electronicos';
  GRANT UPDATE ON "AXIS"."DESMENSAJE_CORREO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESMENSAJE_CORREO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DESMENSAJE_CORREO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DESMENSAJE_CORREO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESMENSAJE_CORREO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DESMENSAJE_CORREO" TO "PROGRAMADORESCSI";
