--------------------------------------------------------
--  DDL for Table DESNIVELAGE
--------------------------------------------------------

  CREATE TABLE "AXIS"."DESNIVELAGE" 
   (	"CTIPAGE" NUMBER, 
	"CEMPRES" NUMBER(2,0), 
	"CIDIOMA" NUMBER, 
	"DESCRIP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DESNIVELAGE"."CTIPAGE" IS 'Código de nivel (máx. 12)';
   COMMENT ON COLUMN "AXIS"."DESNIVELAGE"."CEMPRES" IS 'Código de la empresa';
   COMMENT ON COLUMN "AXIS"."DESNIVELAGE"."CIDIOMA" IS 'Código de idioma';
   COMMENT ON COLUMN "AXIS"."DESNIVELAGE"."DESCRIP" IS 'Descripción del nivel';
   COMMENT ON TABLE "AXIS"."DESNIVELAGE"  IS 'Descripción niveles de agentes en una empresa';
  GRANT UPDATE ON "AXIS"."DESNIVELAGE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESNIVELAGE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DESNIVELAGE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DESNIVELAGE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESNIVELAGE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DESNIVELAGE" TO "PROGRAMADORESCSI";
