--------------------------------------------------------
--  DDL for Table DESPLANBENEF
--------------------------------------------------------

  CREATE TABLE "AXIS"."DESPLANBENEF" 
   (	"CPLAN" NUMBER(6,0), 
	"TPLAN" VARCHAR2(200 BYTE), 
	"CIDIOMA" NUMBER(2,0), 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DESPLANBENEF"."CPLAN" IS 'Código del plan';
   COMMENT ON COLUMN "AXIS"."DESPLANBENEF"."TPLAN" IS 'Descripción del plan';
   COMMENT ON COLUMN "AXIS"."DESPLANBENEF"."CIDIOMA" IS 'Código de Idioma';
   COMMENT ON COLUMN "AXIS"."DESPLANBENEF"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."DESPLANBENEF"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."DESPLANBENEF"."FMODIFI" IS 'Fecha de modificación';
   COMMENT ON COLUMN "AXIS"."DESPLANBENEF"."CUSUMOD" IS 'Usuario de modificación';
   COMMENT ON TABLE "AXIS"."DESPLANBENEF"  IS 'Descripción plan de beneficios';
  GRANT SELECT ON "AXIS"."DESPLANBENEF" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DESPLANBENEF" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DESPLANBENEF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESPLANBENEF" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DESPLANBENEF" TO "PROGRAMADORESCSI";
  GRANT UPDATE ON "AXIS"."DESPLANBENEF" TO "R_AXIS";
