--------------------------------------------------------
--  DDL for Table DESZONAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."DESZONAS" 
   (	"SZONA" NUMBER(7,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TZONA" VARCHAR2(40 BYTE), 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FMODIF" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DESZONAS"."SZONA" IS 'Identificador de zona';
   COMMENT ON COLUMN "AXIS"."DESZONAS"."CIDIOMA" IS 'Idioma';
   COMMENT ON COLUMN "AXIS"."DESZONAS"."TZONA" IS 'Descripción zona';
   COMMENT ON COLUMN "AXIS"."DESZONAS"."FALTA" IS 'Fecha alta';
   COMMENT ON COLUMN "AXIS"."DESZONAS"."CUSUALT" IS 'Usuario alta';
   COMMENT ON COLUMN "AXIS"."DESZONAS"."FMODIF" IS 'Fecha modificación';
   COMMENT ON COLUMN "AXIS"."DESZONAS"."CUSUMOD" IS 'Usuario modificación';
   COMMENT ON TABLE "AXIS"."DESZONAS"  IS 'Descripción de zonas';
  GRANT UPDATE ON "AXIS"."DESZONAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESZONAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DESZONAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DESZONAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DESZONAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DESZONAS" TO "PROGRAMADORESCSI";
