--------------------------------------------------------
--  DDL for Table DETAUTORIZACIONES
--------------------------------------------------------

  CREATE TABLE "AXIS"."DETAUTORIZACIONES" 
   (	"SAUTPSR" NUMBER(11,0), 
	"CREGLA" NUMBER(6,0), 
	"SASOCIA" NUMBER(6,0), 
	"SCONDREG" NUMBER(4,0), 
	"CPERFEXG" NUMBER(4,0), 
	"CRESPUE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DETAUTORIZACIONES"."SAUTPSR" IS 'Clave de autorizaciones';
   COMMENT ON COLUMN "AXIS"."DETAUTORIZACIONES"."CREGLA" IS 'Código de Regla';
   COMMENT ON COLUMN "AXIS"."DETAUTORIZACIONES"."SASOCIA" IS 'Secuencial de Asociación';
   COMMENT ON COLUMN "AXIS"."DETAUTORIZACIONES"."SCONDREG" IS 'Secuencial de condición';
   COMMENT ON COLUMN "AXIS"."DETAUTORIZACIONES"."CPERFEXG" IS 'Código perfil necesario';
   COMMENT ON COLUMN "AXIS"."DETAUTORIZACIONES"."CRESPUE" IS 'Valor respuesta';
   COMMENT ON TABLE "AXIS"."DETAUTORIZACIONES"  IS 'Detalle autorizaciones';
  GRANT UPDATE ON "AXIS"."DETAUTORIZACIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETAUTORIZACIONES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DETAUTORIZACIONES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DETAUTORIZACIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETAUTORIZACIONES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DETAUTORIZACIONES" TO "PROGRAMADORESCSI";
