--------------------------------------------------------
--  DDL for Table DETARTICULO_CONF
--------------------------------------------------------

  CREATE TABLE "AXIS"."DETARTICULO_CONF" 
   (	"CCODARTICULO" NUMBER, 
	"CIDIOMA" NUMBER, 
	"TDESCRIPCION" VARCHAR2(200 BYTE), 
	"NORDEN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DETARTICULO_CONF"."CCODARTICULO" IS 'Código del articulo';
   COMMENT ON COLUMN "AXIS"."DETARTICULO_CONF"."CIDIOMA" IS 'Idioma';
   COMMENT ON COLUMN "AXIS"."DETARTICULO_CONF"."TDESCRIPCION" IS 'Descripción del articulo';
   COMMENT ON COLUMN "AXIS"."DETARTICULO_CONF"."NORDEN" IS 'Número de orden del artículo';
  GRANT UPDATE ON "AXIS"."DETARTICULO_CONF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETARTICULO_CONF" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DETARTICULO_CONF" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DETARTICULO_CONF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETARTICULO_CONF" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DETARTICULO_CONF" TO "PROGRAMADORESCSI";
