--------------------------------------------------------
--  DDL for Table DETCTAEMPLEADOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."DETCTAEMPLEADOS" 
   (	"CPROMOC" NUMBER(4,0), 
	"SPERSON" NUMBER(10,0), 
	"NNUMLIM" NUMBER(4,0), 
	"NLINDET" NUMBER(4,0), 
	"SPERTIT" NUMBER(10,0), 
	"SSEGURO" NUMBER, 
	"CGARANT" NUMBER(4,0), 
	"NPUNTOS" NUMBER(6,0), 
	"CINVALID" NUMBER(1,0), 
	"CTIPDET" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DETCTAEMPLEADOS"."CPROMOC" IS 'Código de promoción';
   COMMENT ON COLUMN "AXIS"."DETCTAEMPLEADOS"."SPERSON" IS 'Código de personas del empleado';
   COMMENT ON COLUMN "AXIS"."DETCTAEMPLEADOS"."NNUMLIM" IS 'Número de movimiento de la cabecera';
   COMMENT ON COLUMN "AXIS"."DETCTAEMPLEADOS"."NLINDET" IS 'Número de movimiento del detalle';
   COMMENT ON COLUMN "AXIS"."DETCTAEMPLEADOS"."SPERTIT" IS 'Código de persona del titular';
   COMMENT ON COLUMN "AXIS"."DETCTAEMPLEADOS"."SSEGURO" IS 'Código SEGURO';
   COMMENT ON COLUMN "AXIS"."DETCTAEMPLEADOS"."CGARANT" IS 'Código de garantia';
   COMMENT ON COLUMN "AXIS"."DETCTAEMPLEADOS"."NPUNTOS" IS 'Puntos';
   COMMENT ON COLUMN "AXIS"."DETCTAEMPLEADOS"."CINVALID" IS 'Registro invalido 1-Si 0-No';
   COMMENT ON COLUMN "AXIS"."DETCTAEMPLEADOS"."CTIPDET" IS 'Tipus de moviment que genera el punt';
   COMMENT ON TABLE "AXIS"."DETCTAEMPLEADOS"  IS 'Detalle por póliza o garantia de puntos de la cuenta del empleado';
  GRANT UPDATE ON "AXIS"."DETCTAEMPLEADOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETCTAEMPLEADOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DETCTAEMPLEADOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DETCTAEMPLEADOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETCTAEMPLEADOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DETCTAEMPLEADOS" TO "PROGRAMADORESCSI";
