--------------------------------------------------------
--  DDL for Table DETEMBARCRIESGOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."DETEMBARCRIESGOS" 
   (	"NRIESGO" NUMBER(6,0), 
	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER(4,0), 
	"TDESACC" VARCHAR2(50 BYTE), 
	"IVALACC" NUMBER, 
	"IREVAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DETEMBARCRIESGOS"."NRIESGO" IS 'Numero de riesgo';
   COMMENT ON COLUMN "AXIS"."DETEMBARCRIESGOS"."SSEGURO" IS 'Secuencial de seguro';
   COMMENT ON COLUMN "AXIS"."DETEMBARCRIESGOS"."NMOVIMI" IS 'Número de Movimiento';
   COMMENT ON COLUMN "AXIS"."DETEMBARCRIESGOS"."TDESACC" IS 'Descripción de los accesorios';
   COMMENT ON COLUMN "AXIS"."DETEMBARCRIESGOS"."IVALACC" IS 'Importe del accesorio';
   COMMENT ON COLUMN "AXIS"."DETEMBARCRIESGOS"."IREVAL" IS 'Importe de revalorización accesorio';
   COMMENT ON TABLE "AXIS"."DETEMBARCRIESGOS"  IS 'Tabla de DETEMBARCRIESGOS';
  GRANT UPDATE ON "AXIS"."DETEMBARCRIESGOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETEMBARCRIESGOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DETEMBARCRIESGOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DETEMBARCRIESGOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETEMBARCRIESGOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DETEMBARCRIESGOS" TO "PROGRAMADORESCSI";
