--------------------------------------------------------
--  DDL for Table DETFACTURA
--------------------------------------------------------

  CREATE TABLE "AXIS"."DETFACTURA" 
   (	"NFACT" VARCHAR2(40 BYTE), 
	"NORDEN" NUMBER, 
	"CCONCEPTO" NUMBER(3,0), 
	"IIMPORTE" NUMBER, 
	"IIRPF" NUMBER, 
	"IIMPNETO" NUMBER, 
	"IIMPCTA" NUMBER, 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE), 
	"CAGENTE" NUMBER, 
	"NRECIBO" NUMBER(9,0), 
	"SMOVREC" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DETFACTURA"."NFACT" IS 'Nº de Factura';
   COMMENT ON COLUMN "AXIS"."DETFACTURA"."NORDEN" IS 'Orden de los conceptos de la factura';
   COMMENT ON COLUMN "AXIS"."DETFACTURA"."CCONCEPTO" IS 'Código del concepto (v.f. 1100)';
   COMMENT ON COLUMN "AXIS"."DETFACTURA"."IIMPORTE" IS 'Importe del concepto';
   COMMENT ON COLUMN "AXIS"."DETFACTURA"."IIRPF" IS 'IRPF del concepto';
   COMMENT ON COLUMN "AXIS"."DETFACTURA"."IIMPNETO" IS 'Importe neto del concepto';
   COMMENT ON COLUMN "AXIS"."DETFACTURA"."IIMPCTA" IS 'Importe del ingreso a cuenta';
   COMMENT ON COLUMN "AXIS"."DETFACTURA"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."DETFACTURA"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."DETFACTURA"."FMODIFI" IS 'Fecha de modificación';
   COMMENT ON COLUMN "AXIS"."DETFACTURA"."CUSUMOD" IS 'Usuario de modificación';
   COMMENT ON COLUMN "AXIS"."DETFACTURA"."NRECIBO" IS 'Número recibo';
   COMMENT ON COLUMN "AXIS"."DETFACTURA"."SMOVREC" IS 'Movimiento recibo';
   COMMENT ON TABLE "AXIS"."DETFACTURA"  IS 'Detalle de una Factura';
  GRANT UPDATE ON "AXIS"."DETFACTURA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETFACTURA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DETFACTURA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DETFACTURA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETFACTURA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DETFACTURA" TO "PROGRAMADORESCSI";
