--------------------------------------------------------
--  DDL for Table DETFORMULAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."DETFORMULAS" 
   (	"IDFORMULA" NUMBER(7,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TDESCRIP" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DETFORMULAS"."IDFORMULA" IS 'Id de la fórmula';
   COMMENT ON COLUMN "AXIS"."DETFORMULAS"."CIDIOMA" IS 'Idioma';
   COMMENT ON COLUMN "AXIS"."DETFORMULAS"."TDESCRIP" IS 'Descripción de la fórmula';
   COMMENT ON TABLE "AXIS"."DETFORMULAS"  IS 'Detalle de las formulas';
  GRANT UPDATE ON "AXIS"."DETFORMULAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETFORMULAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DETFORMULAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DETFORMULAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETFORMULAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DETFORMULAS" TO "PROGRAMADORESCSI";
