--------------------------------------------------------
--  DDL for Table DETGARANFORMULA_PAC
--------------------------------------------------------

  CREATE TABLE "AXIS"."DETGARANFORMULA_PAC" 
   (	"SPRODUC" NUMBER(6,0), 
	"CGARANT" NUMBER(4,0), 
	"CCONCEP" VARCHAR2(8 BYTE), 
	"CGRABA" NUMBER(1,0), 
	"CTRATA" NUMBER(1,0), 
	"VALORDEF" NUMBER, 
	"NORDEN" NUMBER(4,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DETGARANFORMULA_PAC"."SPRODUC" IS 'Código de producto';
   COMMENT ON COLUMN "AXIS"."DETGARANFORMULA_PAC"."CGARANT" IS 'Garantía';
   COMMENT ON COLUMN "AXIS"."DETGARANFORMULA_PAC"."CGRABA" IS '1 = GRABA el CCONCEP en DETPRIMAS; 0 = NO GRABA';
   COMMENT ON COLUMN "AXIS"."DETGARANFORMULA_PAC"."CTRATA" IS '1 = CALCULA el CCONCEP en DETPRIMAS; 0 = NO APLICA';
   COMMENT ON COLUMN "AXIS"."DETGARANFORMULA_PAC"."VALORDEF" IS 'Valor a devolver cuando CTRATAR = 0';
   COMMENT ON COLUMN "AXIS"."DETGARANFORMULA_PAC"."NORDEN" IS 'Orden de ejecución para SPRODUC/CGARANT';
   COMMENT ON COLUMN "AXIS"."DETGARANFORMULA_PAC"."CUSUALT" IS 'Usuario Grabación';
   COMMENT ON COLUMN "AXIS"."DETGARANFORMULA_PAC"."FALTA" IS 'Fecha creación';
   COMMENT ON COLUMN "AXIS"."DETGARANFORMULA_PAC"."CUSUMOD" IS 'Usuario Modificación';
   COMMENT ON COLUMN "AXIS"."DETGARANFORMULA_PAC"."FMODIFI" IS 'Fecha Modificación';
   COMMENT ON TABLE "AXIS"."DETGARANFORMULA_PAC"  IS 'Conceptos por Producto/Garantía para tarificar DETPRIMAS';
  GRANT UPDATE ON "AXIS"."DETGARANFORMULA_PAC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETGARANFORMULA_PAC" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DETGARANFORMULA_PAC" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DETGARANFORMULA_PAC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETGARANFORMULA_PAC" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DETGARANFORMULA_PAC" TO "PROGRAMADORESCSI";
