--------------------------------------------------------
--  DDL for Table DETGASTOS_ULK
--------------------------------------------------------

  CREATE TABLE "AXIS"."DETGASTOS_ULK" 
   (	"CGASTO" NUMBER(3,0), 
	"FINIVIG" DATE, 
	"CTIPO" NUMBER(3,0), 
	"FFINVIG" DATE, 
	"PGASTO" NUMBER(12,9), 
	"IMAXIMO" NUMBER(12,3), 
	"IMINIMO" NUMBER(12,3), 
	"CDEFECT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DETGASTOS_ULK"."CGASTO" IS 'Código Gasto ';
   COMMENT ON COLUMN "AXIS"."DETGASTOS_ULK"."FINIVIG" IS 'Fecha inicio';
   COMMENT ON COLUMN "AXIS"."DETGASTOS_ULK"."CTIPO" IS 'Valor 273 (Table VALORES). Código del tipo de gasto. 1-Gestión 2-Redistribución';
   COMMENT ON COLUMN "AXIS"."DETGASTOS_ULK"."FFINVIG" IS 'Fecha fin';
   COMMENT ON COLUMN "AXIS"."DETGASTOS_ULK"."PGASTO" IS 'Porcentaje gastos';
   COMMENT ON COLUMN "AXIS"."DETGASTOS_ULK"."IMAXIMO" IS 'Importe máximo';
   COMMENT ON COLUMN "AXIS"."DETGASTOS_ULK"."IMINIMO" IS 'Importe mínimo';
   COMMENT ON COLUMN "AXIS"."DETGASTOS_ULK"."CDEFECT" IS 'Identificación de tipo tarifa usado por defecto 1-Por defecto ';
  GRANT UPDATE ON "AXIS"."DETGASTOS_ULK" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETGASTOS_ULK" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DETGASTOS_ULK" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DETGASTOS_ULK" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETGASTOS_ULK" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DETGASTOS_ULK" TO "PROGRAMADORESCSI";
