--------------------------------------------------------
--  DDL for Table DETIMPLIBRETA
--------------------------------------------------------

  CREATE TABLE "AXIS"."DETIMPLIBRETA" 
   (	"SESION" NUMBER(8,0), 
	"SSEGURO" NUMBER, 
	"FCONTAB" DATE, 
	"NNUMLIN" NUMBER(3,0), 
	"NIDLIN" NUMBER(8,0), 
	"CAGRUP" VARCHAR2(3 BYTE), 
	"NLINPAG" NUMBER(3,0), 
	"NPOSCOL" NUMBER(3,0), 
	"TEXTO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS"  ENABLE ROW MOVEMENT ;

   COMMENT ON COLUMN "AXIS"."DETIMPLIBRETA"."SESION" IS 'Identificador de la sesión';
   COMMENT ON COLUMN "AXIS"."DETIMPLIBRETA"."SSEGURO" IS 'Id. del contrato del Ctaseguro Libreta';
   COMMENT ON COLUMN "AXIS"."DETIMPLIBRETA"."FCONTAB" IS 'Fecha Contable del Ctaseguro Libreta';
   COMMENT ON COLUMN "AXIS"."DETIMPLIBRETA"."NNUMLIN" IS 'Número de linea del Ctaseguro Libreta';
   COMMENT ON COLUMN "AXIS"."DETIMPLIBRETA"."NIDLIN" IS 'Identificador de linea a enviar a la impresión';
   COMMENT ON COLUMN "AXIS"."DETIMPLIBRETA"."CAGRUP" IS 'Agrupación de las lineas POR-Portada PAD-Portada Adicional CAB-Cabecera DAT-Datos PIE-Pie';
   COMMENT ON COLUMN "AXIS"."DETIMPLIBRETA"."NLINPAG" IS 'Número de linea a imprimir';
   COMMENT ON COLUMN "AXIS"."DETIMPLIBRETA"."NPOSCOL" IS 'Pósición  de inicio de escritura dentro de la línea';
   COMMENT ON COLUMN "AXIS"."DETIMPLIBRETA"."TEXTO" IS 'Texto a imprimir';
  GRANT UPDATE ON "AXIS"."DETIMPLIBRETA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETIMPLIBRETA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DETIMPLIBRETA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DETIMPLIBRETA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETIMPLIBRETA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DETIMPLIBRETA" TO "PROGRAMADORESCSI";
