--------------------------------------------------------
--  DDL for Table DETMOVSEGUROCOL
--------------------------------------------------------

  CREATE TABLE "AXIS"."DETMOVSEGUROCOL" 
   (	"SSEGURO_0" NUMBER, 
	"NMOVIMI_0" NUMBER(4,0), 
	"SSEGURO_CERT" NUMBER, 
	"NMOVIMI_CERT" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DETMOVSEGUROCOL"."SSEGURO_0" IS 'Identificador del seguro del certificado 0';
   COMMENT ON COLUMN "AXIS"."DETMOVSEGUROCOL"."NMOVIMI_0" IS 'Número de movimiento del seguro del certificado 0';
   COMMENT ON COLUMN "AXIS"."DETMOVSEGUROCOL"."SSEGURO_CERT" IS 'Identificador del seguro del certificado';
   COMMENT ON COLUMN "AXIS"."DETMOVSEGUROCOL"."NMOVIMI_CERT" IS 'Número de movimiento del seguro del certificado';
   COMMENT ON TABLE "AXIS"."DETMOVSEGUROCOL"  IS 'Tabla con los detalles de los movimientos de las pólizas colectivas administradas';
  GRANT UPDATE ON "AXIS"."DETMOVSEGUROCOL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETMOVSEGUROCOL" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DETMOVSEGUROCOL" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DETMOVSEGUROCOL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETMOVSEGUROCOL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DETMOVSEGUROCOL" TO "PROGRAMADORESCSI";
