--------------------------------------------------------
--  DDL for Table DETMODIF
--------------------------------------------------------

  CREATE TABLE "AXIS"."DETMODIF" 
   (	"SMODCON" NUMBER(2,0), 
	"SMODIFI" NUMBER(8,0), 
	"CMODIFI" NUMBER(2,0), 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"CREVISI" NUMBER(1,0), 
	"FREVISI" DATE, 
	"CUSUREV" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."DETMODIF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETMODIF" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DETMODIF" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DETMODIF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETMODIF" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DETMODIF" TO "PROGRAMADORESCSI";
