--------------------------------------------------------
--  DDL for Table DETSARLATF_ACT
--------------------------------------------------------

  CREATE TABLE "AXIS"."DETSARLATF_ACT" 
   (	"NACTIVI" NUMBER, 
	"SPERSON" NUMBER, 
	"SSARLAFT" NUMBER, 
	"CTIPOPROD" NUMBER, 
	"CIDNUMPROD" VARCHAR2(150 BYTE), 
	"TENTIDAD" VARCHAR2(150 BYTE), 
	"CMONTO" VARCHAR2(150 BYTE), 
	"CCIUDAD" NUMBER, 
	"CPAIS" NUMBER, 
	"CMONEDA" VARCHAR2(150 BYTE), 
	"SCPAIS" VARCHAR2(150 BYTE), 
	"STDEPB" VARCHAR2(150 BYTE), 
	"SCCIUDAD" VARCHAR2(150 BYTE), 
	"TDEPB" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DETSARLATF_ACT"."TDEPB" IS 'Codigo de departamento';
  GRANT UPDATE ON "AXIS"."DETSARLATF_ACT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETSARLATF_ACT" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DETSARLATF_ACT" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DETSARLATF_ACT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETSARLATF_ACT" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DETSARLATF_ACT" TO "PROGRAMADORESCSI";
