--------------------------------------------------------
--  DDL for Table DETZONAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."DETZONAS" 
   (	"SDETZON" NUMBER(8,0), 
	"SZONA" NUMBER(7,0), 
	"CPROVIN" NUMBER, 
	"CPOBLAC" NUMBER, 
	"CPOSTAL" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FMODIF" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DETZONAS"."SDETZON" IS 'Identificador detalle zonas';
   COMMENT ON COLUMN "AXIS"."DETZONAS"."SZONA" IS 'Identificador de zona';
   COMMENT ON COLUMN "AXIS"."DETZONAS"."CPROVIN" IS 'Provincia';
   COMMENT ON COLUMN "AXIS"."DETZONAS"."CPOBLAC" IS 'Población';
   COMMENT ON COLUMN "AXIS"."DETZONAS"."CPOSTAL" IS 'Código Postal';
   COMMENT ON COLUMN "AXIS"."DETZONAS"."FALTA" IS 'Fecha alta';
   COMMENT ON COLUMN "AXIS"."DETZONAS"."CUSUALT" IS 'Usuario alta';
   COMMENT ON COLUMN "AXIS"."DETZONAS"."FMODIF" IS 'Fecha modificación';
   COMMENT ON COLUMN "AXIS"."DETZONAS"."CUSUMOD" IS 'Usuario modificación';
   COMMENT ON TABLE "AXIS"."DETZONAS"  IS 'Detalle de zonas';
  GRANT UPDATE ON "AXIS"."DETZONAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETZONAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DETZONAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DETZONAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DETZONAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DETZONAS" TO "PROGRAMADORESCSI";
