--------------------------------------------------------
--  DDL for Table DEVBANPRESENTADORES
--------------------------------------------------------

  CREATE TABLE "AXIS"."DEVBANPRESENTADORES" 
   (	"SDEVOLU" NUMBER(6,0), 
	"CEMPRES" NUMBER(2,0), 
	"CDOMENT" NUMBER(4,0), 
	"CDOMSUC" NUMBER(4,0), 
	"FSOPORT" DATE, 
	"NNUMNIF" VARCHAR2(50 BYTE), 
	"TSUFIJO" VARCHAR2(3 BYTE), 
	"TPRENOM" VARCHAR2(40 BYTE), 
	"FCARGA" DATE, 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"TFICHER" VARCHAR2(200 BYTE), 
	"NPREREG" NUMBER(10,0), 
	"IPRETOT_R" NUMBER, 
	"IPRETOT_T" NUMBER, 
	"NPRETOT_R" NUMBER(10,0), 
	"NPRETOT_T" NUMBER(10,0), 
	"SPROCES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."SDEVOLU" IS 'Identificador del proceso de carga de devoluciones';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."CEMPRES" IS 'Código de Empresa';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."CDOMENT" IS 'Entidad en la que se presentó el soporte y lo devuelve';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."CDOMSUC" IS 'Oficina en la que se presentó el soporte y ahora lo devuelve';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."FSOPORT" IS 'Fecha de confección del soporte';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."NNUMNIF" IS 'NIF presentador';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."TSUFIJO" IS 'Sufijo del presentador';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."TPRENOM" IS 'Nombre del presentador';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."FCARGA" IS 'Fecha en la que se carga el soporte';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."CUSUARI" IS 'Usuario que realiza la carga';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."TFICHER" IS 'Nombre del fichero que se carga';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."NPREREG" IS 'Número total de registros en el soporte';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."IPRETOT_R" IS 'Total importes devolución reales';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."IPRETOT_T" IS 'Total importes devolución reales teóricos';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."NPRETOT_R" IS 'Número total de devoluciones reales';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."NPRETOT_T" IS 'Número total de devoluciones teóricos';
   COMMENT ON COLUMN "AXIS"."DEVBANPRESENTADORES"."SPROCES" IS 'Identificador del procès on consten els errors';
  GRANT UPDATE ON "AXIS"."DEVBANPRESENTADORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DEVBANPRESENTADORES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DEVBANPRESENTADORES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DEVBANPRESENTADORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DEVBANPRESENTADORES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DEVBANPRESENTADORES" TO "PROGRAMADORESCSI";
