--------------------------------------------------------
--  DDL for Table DIARIOTRAMITACION
--------------------------------------------------------

  CREATE TABLE "AXIS"."DIARIOTRAMITACION" 
   (	"NSINIES" NUMBER(8,0), 
	"NTRAMIT" NUMBER(4,0), 
	"NLINTRA" NUMBER(6,0), 
	"FLINTRA" DATE, 
	"CLINTRA" NUMBER(3,0), 
	"TLINTRA" VARCHAR2(500 BYTE), 
	"SASIGNA" NUMBER(3,0), 
	"NLOCALI" NUMBER(3,0), 
	"SPERSON" NUMBER(10,0), 
	"CTIPDES" NUMBER(2,0), 
	"CGARANT" NUMBER(4,0), 
	"NVALORA" NUMBER(2,0), 
	"SIDEPAG" NUMBER(8,0), 
	"NLINPRO" NUMBER(6,0), 
	"CESTADO" NUMBER(3,0), 
	"NDANO" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DIARIOTRAMITACION"."NSINIES" IS 'Numero de siniestro';
   COMMENT ON COLUMN "AXIS"."DIARIOTRAMITACION"."NTRAMIT" IS 'Numero de tramitacion';
   COMMENT ON COLUMN "AXIS"."DIARIOTRAMITACION"."NLINTRA" IS 'Numero de linea';
   COMMENT ON COLUMN "AXIS"."DIARIOTRAMITACION"."FLINTRA" IS 'Fecha de alta de linea';
   COMMENT ON COLUMN "AXIS"."DIARIOTRAMITACION"."CLINTRA" IS 'Codigo de tipo de linea';
   COMMENT ON COLUMN "AXIS"."DIARIOTRAMITACION"."TLINTRA" IS 'Texto de linea';
   COMMENT ON TABLE "AXIS"."DIARIOTRAMITACION"  IS 'Tramitaciones de Siniestro';
  GRANT UPDATE ON "AXIS"."DIARIOTRAMITACION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIARIOTRAMITACION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DIARIOTRAMITACION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DIARIOTRAMITACION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIARIOTRAMITACION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DIARIOTRAMITACION" TO "PROGRAMADORESCSI";
