--------------------------------------------------------
--  DDL for Table DIF_PREVI
--------------------------------------------------------

  CREATE TABLE "AXIS"."DIF_PREVI" 
   (	"TIPODIF" VARCHAR2(1 BYTE), 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"POLISSA" NUMBER(8,0), 
	"NOM_CLI" VARCHAR2(80 BYTE), 
	"CONTINENT" NUMBER, 
	"CONTINENT_F" NUMBER, 
	"CONTINGUT" NUMBER, 
	"CONTINGUT_F" NUMBER, 
	"AVMAQUI" NUMBER, 
	"AVMAQUI_F" NUMBER, 
	"DETALIME" NUMBER, 
	"DETALIME_F" NUMBER, 
	"DEFEC" DATE, 
	"DEFEC_F" DATE, 
	"DVENCIM" DATE, 
	"DVENCIM_F" DATE, 
	"PNETA" NUMBER, 
	"PNETA_F" NUMBER, 
	"PBRUTA" NUMBER, 
	"PBRUTA_F" NUMBER, 
	"COMIS" NUMBER, 
	"COMIS_F" NUMBER, 
	"BONIFICA" NUMBER, 
	"SSEGURO" NUMBER, 
	"SPROCES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."DIF_PREVI" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIF_PREVI" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DIF_PREVI" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DIF_PREVI" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIF_PREVI" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DIF_PREVI" TO "PROGRAMADORESCSI";
