--------------------------------------------------------
--  DDL for Table DIFCLAUPARESP
--------------------------------------------------------

  CREATE TABLE "AXIS"."DIFCLAUPARESP" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"SCLAGEN" NUMBER(4,0), 
	"NPARAME" NUMBER(2,0), 
	"CCLAESP" NUMBER(1,0), 
	"NORDCLA" NUMBER(5,0), 
	"CTIPPAR" NUMBER(1,0), 
	"TVALOR" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DIFCLAUPARESP"."SSEGURO" IS 'Identificador del seguro';
   COMMENT ON COLUMN "AXIS"."DIFCLAUPARESP"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."DIFCLAUPARESP"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."DIFCLAUPARESP"."SCLAGEN" IS 'Identificador claúsula';
   COMMENT ON COLUMN "AXIS"."DIFCLAUPARESP"."NPARAME" IS 'Número de parámetro';
   COMMENT ON COLUMN "AXIS"."DIFCLAUPARESP"."CCLAESP" IS 'Tipo de claúsula';
   COMMENT ON COLUMN "AXIS"."DIFCLAUPARESP"."NORDCLA" IS 'Orden (especial)';
   COMMENT ON COLUMN "AXIS"."DIFCLAUPARESP"."CTIPPAR" IS 'Tipo de parámetro';
   COMMENT ON COLUMN "AXIS"."DIFCLAUPARESP"."TVALOR" IS 'Valor del parámetro';
   COMMENT ON TABLE "AXIS"."DIFCLAUPARESP"  IS 'Parámetros claúsulas riesgo';
  GRANT UPDATE ON "AXIS"."DIFCLAUPARESP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIFCLAUPARESP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DIFCLAUPARESP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DIFCLAUPARESP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIFCLAUPARESP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DIFCLAUPARESP" TO "PROGRAMADORESCSI";
