--------------------------------------------------------
--  DDL for Table DIFCLAUSUSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."DIFCLAUSUSEG" 
   (	"NMOVIMI" NUMBER(4,0), 
	"SSEGURO" NUMBER, 
	"SCLAGEN" NUMBER(4,0), 
	"FINICLAU" DATE, 
	"FFINCLAU" DATE, 
	"TIMAGEN" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DIFCLAUSUSEG"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."DIFCLAUSUSEG"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente.';
   COMMENT ON COLUMN "AXIS"."DIFCLAUSUSEG"."SCLAGEN" IS 'Identificador de cláusula';
   COMMENT ON COLUMN "AXIS"."DIFCLAUSUSEG"."FINICLAU" IS 'Fecha inicio cláusula';
   COMMENT ON COLUMN "AXIS"."DIFCLAUSUSEG"."FFINCLAU" IS 'Fecha fin cláusula';
  GRANT UPDATE ON "AXIS"."DIFCLAUSUSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIFCLAUSUSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DIFCLAUSUSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DIFCLAUSUSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIFCLAUSUSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DIFCLAUSUSEG" TO "PROGRAMADORESCSI";
