--------------------------------------------------------
--  DDL for Table DIFGARANSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."DIFGARANSEG" 
   (	"CGARANT" NUMBER(4,0), 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"SSEGURO" NUMBER, 
	"FINIEFE" DATE, 
	"NORDEN" NUMBER(4,0), 
	"CREVALI" NUMBER(2,0), 
	"CTARIFA" NUMBER(5,0), 
	"ICAPITAL" NUMBER, 
	"PRECARG" NUMBER(6,2), 
	"IEXTRAP" NUMBER(19,12), 
	"IPRIANU" NUMBER, 
	"FFINEFE" DATE, 
	"CFORMUL" NUMBER(4,0), 
	"CTIPFRA" NUMBER(1,0), 
	"IFRANQU" NUMBER, 
	"IRECARG" NUMBER, 
	"IPRITAR" NUMBER, 
	"PDTOCOM" NUMBER(6,2), 
	"IDTOCOM" NUMBER, 
	"PREVALI" NUMBER(5,2), 
	"IREVALI" NUMBER, 
	"ITARIFA" NUMBER(19,12), 
	"ITARREA" NUMBER(24,12), 
	"IPRITOT" NUMBER, 
	"ICAPTOT" NUMBER, 
	"FTARIFA" DATE, 
	"CREVALCAR" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."CGARANT" IS 'Código de garantía';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente.';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."FINIEFE" IS 'fecha inicio de efecto';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."NORDEN" IS 'Número de orden.';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."CREVALI" IS 'Tipo de revalorizacion';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."CTARIFA" IS 'Código de tarifa';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."ICAPITAL" IS 'Importe garantía';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."PRECARG" IS 'Porcentaje de recargo';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."IEXTRAP" IS 'Extraprima';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."IPRIANU" IS 'Importe prima anual';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."FFINEFE" IS 'fecha fin de efecto';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."CFORMUL" IS 'Fórmula utilizada en la tarifa';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."CTIPFRA" IS 'Tipo de franquicia';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."IFRANQU" IS 'Importe franquicia';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."IRECARG" IS 'Importe del recargo';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."IPRITAR" IS 'Importe tarifa';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."PDTOCOM" IS 'Porcentaje descuento comercial';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."IDTOCOM" IS 'Importe descuento comercial';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."PREVALI" IS 'Porcentaje de revalorizacion';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."IREVALI" IS 'Importe de revalorización';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."ITARIFA" IS 'Tarifa + extraprima';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."ITARREA" IS 'Tarifa reaseguro';
   COMMENT ON COLUMN "AXIS"."DIFGARANSEG"."CREVALCAR" IS '0.- No revaloritza a la cartera, 1.- Si revaloriza a la cartera';
  GRANT UPDATE ON "AXIS"."DIFGARANSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIFGARANSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DIFGARANSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DIFGARANSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIFGARANSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DIFGARANSEG" TO "PROGRAMADORESCSI";
