--------------------------------------------------------
--  DDL for Table DIFSITRIESGO
--------------------------------------------------------

  CREATE TABLE "AXIS"."DIFSITRIESGO" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"TDOMICI" VARCHAR2(200 BYTE), 
	"CPROVIN" NUMBER, 
	"CPOSTAL" VARCHAR2(30 BYTE), 
	"CPOBLAC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DIFSITRIESGO"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente.';
   COMMENT ON COLUMN "AXIS"."DIFSITRIESGO"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."DIFSITRIESGO"."TDOMICI" IS 'Domicilio';
   COMMENT ON COLUMN "AXIS"."DIFSITRIESGO"."CPROVIN" IS 'Código de provincia';
   COMMENT ON COLUMN "AXIS"."DIFSITRIESGO"."CPOSTAL" IS 'Código postal';
   COMMENT ON COLUMN "AXIS"."DIFSITRIESGO"."CPOBLAC" IS 'Código de población';
  GRANT UPDATE ON "AXIS"."DIFSITRIESGO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIFSITRIESGO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DIFSITRIESGO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DIFSITRIESGO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIFSITRIESGO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DIFSITRIESGO" TO "PROGRAMADORESCSI";
