--------------------------------------------------------
--  DDL for Table DIR_CALLES
--------------------------------------------------------

  CREATE TABLE "AXIS"."DIR_CALLES" 
   (	"IDCALLE" NUMBER(10,0), 
	"IDLOCAL" NUMBER(8,0), 
	"TCALLE" VARCHAR2(100 BYTE), 
	"CTIPVIA" NUMBER(8,0), 
	"CFUENTE" NUMBER(8,0), 
	"TCALBUS" VARCHAR2(100 BYTE), 
	"CVALCAL" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DIR_CALLES"."IDCALLE" IS 'Id Calle';
   COMMENT ON COLUMN "AXIS"."DIR_CALLES"."IDLOCAL" IS 'Id Localidad';
   COMMENT ON COLUMN "AXIS"."DIR_CALLES"."TCALLE" IS 'Nombre de la calle';
   COMMENT ON COLUMN "AXIS"."DIR_CALLES"."CTIPVIA" IS 'Tipo de calle';
   COMMENT ON COLUMN "AXIS"."DIR_CALLES"."CFUENTE" IS 'Indica la fuente de procedencia (TeleAtlas, Correos, Manual, etc)';
   COMMENT ON COLUMN "AXIS"."DIR_CALLES"."TCALBUS" IS 'Descripción optimizada para búsquedas';
   COMMENT ON COLUMN "AXIS"."DIR_CALLES"."CVALCAL" IS 'Indica si la calle está validada';
   COMMENT ON TABLE "AXIS"."DIR_CALLES"  IS 'Calles';
  GRANT UPDATE ON "AXIS"."DIR_CALLES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIR_CALLES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DIR_CALLES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DIR_CALLES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DIR_CALLES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DIR_CALLES" TO "PROGRAMADORESCSI";
