--------------------------------------------------------
--  DDL for Table DOC_PRO_DOCUMENTO
--------------------------------------------------------

  CREATE TABLE "AXIS"."DOC_PRO_DOCUMENTO" 
   (	"SPRODUC" NUMBER(6,0), 
	"CACTIVI" NUMBER(4,0), 
	"CDOCUME" NUMBER(6,0), 
	"CMODUL" NUMBER(1,0), 
	"COBLIGA" NUMBER(1,0), 
	"CGARANT" NUMBER(4,0), 
	"CMOTMOV" NUMBER(3,0), 
	"CCAUSIN" NUMBER(4,0), 
	"CMOTSIN" NUMBER(4,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"NORDEN" NUMBER(4,0), 
	"CACCION" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."SPRODUC" IS 'Secuencia Producto';
   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."CACTIVI" IS 'Código Actividad';
   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."CDOCUME" IS 'Código Documento';
   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."CMODUL" IS 'Código Módulo (0.Producción/1.Siniestros)';
   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."COBLIGA" IS 'Código Documento Obligatorio (0.No/1.Sí)';
   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."CGARANT" IS 'Código Garantía';
   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."CMOTMOV" IS 'Código Motivo Movimiento';
   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."CCAUSIN" IS 'Código Causa Siniestro';
   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."CMOTSIN" IS 'Código Motivo Siniestro';
   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."CUSUALT" IS 'Código Usuario Alta';
   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."FALTA" IS 'Fecha Alta';
   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."CUSUMOD" IS 'Código Usuario Modificación';
   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."FMODIFI" IS 'Fecha Modificación';
   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."NORDEN" IS 'Número de orden';
   COMMENT ON COLUMN "AXIS"."DOC_PRO_DOCUMENTO"."CACCION" IS 'Documento modificable. (0/null)-->Sí modificable | 1--> No modificable';
   COMMENT ON TABLE "AXIS"."DOC_PRO_DOCUMENTO"  IS 'Producto documento siniestro';
  GRANT UPDATE ON "AXIS"."DOC_PRO_DOCUMENTO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DOC_PRO_DOCUMENTO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DOC_PRO_DOCUMENTO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DOC_PRO_DOCUMENTO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DOC_PRO_DOCUMENTO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DOC_PRO_DOCUMENTO" TO "PROGRAMADORESCSI";
