--------------------------------------------------------
--  DDL for Table DOCREQUERIDA_BENESPSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."DOCREQUERIDA_BENESPSEG" 
   (	"SEQDOCU" NUMBER(10,0), 
	"CDOCUME" NUMBER(6,0), 
	"SPRODUC" NUMBER(6,0), 
	"CACTIVI" NUMBER(4,0), 
	"NORDEN" NUMBER(3,0), 
	"CTIPDOC" NUMBER(3,0), 
	"CCLASE" NUMBER(3,0), 
	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER(4,0), 
	"NRIESGO" NUMBER(6,0), 
	"TFILENAME" VARCHAR2(200 BYTE), 
	"TDESCRIP" VARCHAR2(1000 BYTE), 
	"ADJUNTADO" NUMBER(1,0) DEFAULT 1, 
	"IDDOCGEDOX" NUMBER(8,0), 
	"SPERSON" NUMBER(10,0), 
	"CTIPBEN" NUMBER(2,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."SEQDOCU" IS 'Número secuencial de documento';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."CDOCUME" IS 'Código de documento';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."SPRODUC" IS 'Código de producto';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."CACTIVI" IS 'Código de actividad';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."NORDEN" IS 'Número de orden';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."CTIPDOC" IS 'Tipo de documento (VF. 1031)';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."CCLASE" IS 'Clase de parametrización (VF. 1032)';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."SSEGURO" IS 'Número secuencial de seguro';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."TFILENAME" IS 'Nombre del fichero';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."TDESCRIP" IS 'Descripción';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."ADJUNTADO" IS 'Indicador de si se ha adjuntado el documento';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."IDDOCGEDOX" IS 'Identificador del GEDOX';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."SPERSON" IS 'Identificador de la persona beneficiaria';
   COMMENT ON COLUMN "AXIS"."DOCREQUERIDA_BENESPSEG"."CTIPBEN" IS 'Tipo de beneficiario';
   COMMENT ON TABLE "AXIS"."DOCREQUERIDA_BENESPSEG"  IS 'Tabla temporal de documentación requerida de beneficiarios';
  GRANT UPDATE ON "AXIS"."DOCREQUERIDA_BENESPSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DOCREQUERIDA_BENESPSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DOCREQUERIDA_BENESPSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DOCREQUERIDA_BENESPSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DOCREQUERIDA_BENESPSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DOCREQUERIDA_BENESPSEG" TO "PROGRAMADORESCSI";
