--------------------------------------------------------
--  DDL for Table DOCUMMOVSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."DOCUMMOVSEG" 
   (	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER(4,0), 
	"IDDOCGEDOX" NUMBER(8,0), 
	"CORIGEN" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DOCUMMOVSEG"."CORIGEN" IS 'Origen fichero 0 Automático, 1 Manual';
  GRANT UPDATE ON "AXIS"."DOCUMMOVSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DOCUMMOVSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DOCUMMOVSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DOCUMMOVSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DOCUMMOVSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DOCUMMOVSEG" TO "PROGRAMADORESCSI";
