--------------------------------------------------------
--  DDL for Table DOMICILIACIONES_CAB
--------------------------------------------------------

  CREATE TABLE "AXIS"."DOMICILIACIONES_CAB" 
   (	"SPROCES" NUMBER, 
	"CCOBBAN" NUMBER(3,0), 
	"CEMPRES" NUMBER(2,0), 
	"FEFECTO" DATE, 
	"TFILEENV" VARCHAR2(50 BYTE), 
	"TFILEDEV" VARCHAR2(50 BYTE), 
	"CESTDOM" NUMBER, 
	"CREMBAN" VARCHAR2(50 BYTE), 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FUSUMOD" DATE, 
	"SDEVOLU" NUMBER(6,0), 
	"SPROCIE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES_CAB"."SPROCES" IS 'Proceso';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES_CAB"."CCOBBAN" IS 'Código de cobrador bancario';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES_CAB"."CEMPRES" IS 'Empresa';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES_CAB"."FEFECTO" IS 'Fecha remesa (lote)';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES_CAB"."TFILEENV" IS 'Nombre del fichero envíado al banco';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES_CAB"."TFILEDEV" IS 'Nombre del fichero recibido del banco';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES_CAB"."CESTDOM" IS 'Estado de la domiciliación (remesa bancaria). Valor Fijo 800079 (0-Cerrado, 1-Abierto, 2-Retrocedida)';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES_CAB"."CREMBAN" IS 'Número de remesa interna de la entidad bancaria';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES_CAB"."CUSUMOD" IS 'Usuario que modifica el registro';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES_CAB"."FUSUMOD" IS 'Fecha en la cual se modifica el registro';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES_CAB"."SDEVOLU" IS 'Identificador del proceso de carga de devoluciones relacionado';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES_CAB"."SPROCIE" IS 'Secuencia del proceso del cierre de la remesa (PROCESOSCAB.SPROCES)';
   COMMENT ON TABLE "AXIS"."DOMICILIACIONES_CAB"  IS 'Cabecera de domiciliaciones bancarias (tabla CABECERA)';
  GRANT UPDATE ON "AXIS"."DOMICILIACIONES_CAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DOMICILIACIONES_CAB" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DOMICILIACIONES_CAB" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DOMICILIACIONES_CAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DOMICILIACIONES_CAB" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DOMICILIACIONES_CAB" TO "PROGRAMADORESCSI";
