--------------------------------------------------------
--  DDL for Table DOMICILIACIONES
--------------------------------------------------------

  CREATE TABLE "AXIS"."DOMICILIACIONES" 
   (	"NRECIBO" NUMBER, 
	"SPROCES" NUMBER, 
	"CCOBBAN" NUMBER(3,0), 
	"CEMPRES" NUMBER(2,0), 
	"FEFECTO" DATE, 
	"TSUFIJO" VARCHAR2(4 BYTE), 
	"CDOMENT" NUMBER(4,0), 
	"CDOMSUC" NUMBER(4,0), 
	"SMOVREC" NUMBER, 
	"CERROR" NUMBER(8,0), 
	"CAGENTE" NUMBER, 
	"CAGRPRO" NUMBER(2,0), 
	"CCOMPANI" NUMBER(3,0), 
	"CTIPEMP" NUMBER(2,0), 
	"SSEGURO" NUMBER, 
	"CTIPREC" NUMBER(2,0), 
	"CBANCAR" VARCHAR2(50 BYTE), 
	"NMOVIMI" NUMBER(4,0), 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"PGASINT" NUMBER(9,6), 
	"PGASEXT" NUMBER(9,6), 
	"CFECCOB" NUMBER(1,0), 
	"FEFECREC" DATE, 
	"CTIPBAN" NUMBER(3,0), 
	"CDOMEST" NUMBER(1,0), 
	"CDOMERR" VARCHAR2(4 BYTE), 
	"IDNOTIF" NUMBER(10,0), 
	"TFILEENV" VARCHAR2(50 BYTE), 
	"TFILEDEV" VARCHAR2(50 BYTE), 
	"FDEBITO" DATE, 
	"IDNOTIF2" VARCHAR2(100 BYTE), 
	"IVALORDB" NUMBER, 
	"IVALCOM" NUMBER, 
	"IVALIVA" NUMBER, 
	"FIDENOTIF2" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS"  ENABLE ROW MOVEMENT ;

   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."NRECIBO" IS 'Número de recibo.';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."SPROCES" IS 'Proceso';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CCOBBAN" IS 'Código de cobrador bancario';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CEMPRES" IS 'Empresa';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."FEFECTO" IS 'Fecha remesa (lote)';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."TSUFIJO" IS 'Sufijo ordenante en el soporte';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CERROR" IS 'Código de error';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CAGRPRO" IS 'Agrupación de producto';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CCOMPANI" IS 'Compañía aseguradora';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CTIPEMP" IS 'Tipo de empresa';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."SSEGURO" IS 'Número de seguro';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CTIPREC" IS 'Tipo de recibo';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CBANCAR" IS 'Cuenta bancària';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."NMOVIMI" IS 'Num.movimiento de seguro';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CRAMO" IS 'Código de ramo';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CMODALI" IS 'Código de modalida';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CTIPSEG" IS 'Código de tiposeguro';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CCOLECT" IS 'Código de colectividad';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CTIPBAN" IS 'Tipo de cuenta ( iban o cuenta bancaria). [tabla maestra: TIPOS_CUENTA]';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CDOMEST" IS 'Estado devuelto de la domiciliación (0-> OK, 1->KO)';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."CDOMERR" IS 'Error devuelto de la domiciliación (si CDOMEST=0-->KO)';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."IDNOTIF" IS 'Id de la notificación de la domiciliación';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."TFILEENV" IS 'Nombre del fichero envíado al banco';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."TFILEDEV" IS 'Nombre del fichero recibido del banco';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."FDEBITO" IS 'Fecha de debito facilitada por el banco';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."IDNOTIF2" IS 'Id. por el que identificamos la notificación. Código de matrícula que se envía al banco (varchar -> para que conserve el formato exacto). Esta referencia se captura en RECFION en el campo "Referencia Código de Usuario';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."IVALORDB" IS 'Valor debitado por el banco';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."IVALCOM" IS 'Costo de la transacción';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."IVALIVA" IS 'Valor IVA de la comisión';
   COMMENT ON COLUMN "AXIS"."DOMICILIACIONES"."FIDENOTIF2" IS 'Fecha en la que se firma el mandato';
  GRANT UPDATE ON "AXIS"."DOMICILIACIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DOMICILIACIONES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DOMICILIACIONES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DOMICILIACIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DOMICILIACIONES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DOMICILIACIONES" TO "PROGRAMADORESCSI";
