--------------------------------------------------------
--  DDL for Table DSICENTRO
--------------------------------------------------------

  CREATE TABLE "AXIS"."DSICENTRO" 
   (	"CCENTRO" NUMBER(2,0), 
	"TNOMBRE" VARCHAR2(50 BYTE), 
	"TPERSON" VARCHAR2(60 BYTE), 
	"TTELEF" VARCHAR2(20 BYTE), 
	"CNATUR" NUMBER(1,0), 
	"FBAJA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DSICENTRO"."CCENTRO" IS 'Código del centro';
   COMMENT ON COLUMN "AXIS"."DSICENTRO"."TNOMBRE" IS 'Nombre del centro';
   COMMENT ON COLUMN "AXIS"."DSICENTRO"."TPERSON" IS 'Nombre persona de contacto';
   COMMENT ON COLUMN "AXIS"."DSICENTRO"."TTELEF" IS 'Teléfono de contacto';
   COMMENT ON COLUMN "AXIS"."DSICENTRO"."CNATUR" IS 'Tipo de centro';
   COMMENT ON COLUMN "AXIS"."DSICENTRO"."FBAJA" IS 'Fecha de baja del centro o cliente';
   COMMENT ON TABLE "AXIS"."DSICENTRO"  IS 'Tabla de clientes / centros';
  GRANT UPDATE ON "AXIS"."DSICENTRO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DSICENTRO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DSICENTRO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DSICENTRO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DSICENTRO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DSICENTRO" TO "PROGRAMADORESCSI";
