--------------------------------------------------------
--  DDL for Table DURCOBROPROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."DURCOBROPROD" 
   (	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"NDURCOB" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DURCOBROPROD"."CRAMO" IS 'Código ramo';
   COMMENT ON COLUMN "AXIS"."DURCOBROPROD"."CMODALI" IS 'Código modalidad';
   COMMENT ON COLUMN "AXIS"."DURCOBROPROD"."CTIPSEG" IS 'Código tipo de seguro';
   COMMENT ON COLUMN "AXIS"."DURCOBROPROD"."CCOLECT" IS 'Código de colectividad';
   COMMENT ON COLUMN "AXIS"."DURCOBROPROD"."NDURCOB" IS 'Duraciones de cobro permitidas';
   COMMENT ON TABLE "AXIS"."DURCOBROPROD"  IS 'Duraciones de cobro permitidas por producto';
  GRANT UPDATE ON "AXIS"."DURCOBROPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DURCOBROPROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DURCOBROPROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DURCOBROPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DURCOBROPROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DURCOBROPROD" TO "PROGRAMADORESCSI";
