--------------------------------------------------------
--  DDL for Table DURFORPAGREN
--------------------------------------------------------

  CREATE TABLE "AXIS"."DURFORPAGREN" 
   (	"SPRODUC" NUMBER(6,0), 
	"CDURACI" NUMBER(3,0), 
	"CFORPAG" NUMBER(2,0), 
	"CTIPOPAG" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."DURFORPAGREN"."SPRODUC" IS 'Código producto';
   COMMENT ON COLUMN "AXIS"."DURFORPAGREN"."CDURACI" IS 'Duración a la cual esta asociada la forma de pago';
   COMMENT ON COLUMN "AXIS"."DURFORPAGREN"."CFORPAG" IS 'Forma de pago renta/prima';
   COMMENT ON COLUMN "AXIS"."DURFORPAGREN"."CTIPOPAG" IS 'Tipo = 1 = Forma de pago prima / Tipo = 2 = Forma de pago renta';
  GRANT UPDATE ON "AXIS"."DURFORPAGREN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DURFORPAGREN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."DURFORPAGREN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."DURFORPAGREN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."DURFORPAGREN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."DURFORPAGREN" TO "PROGRAMADORESCSI";
