--------------------------------------------------------
--  DDL for Table ECO_CODMONEDAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."ECO_CODMONEDAS" 
   (	"CMONEDA" VARCHAR2(3 BYTE), 
	"CTIPMONEDA" VARCHAR2(1 BYTE) DEFAULT 1, 
	"NDECIMA" NUMBER(4,0) DEFAULT 0, 
	"CISO4217X" VARCHAR2(3 BYTE), 
	"CISO4217N" NUMBER(3,0), 
	"CGENERO" VARCHAR2(1 BYTE), 
	"NORDEN" NUMBER(3,2), 
	"BVISUALIZA" NUMBER(1,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"CUSUBAJ" VARCHAR2(20 BYTE), 
	"FBAJA" DATE, 
	"BDEFECTO" NUMBER(1,0) DEFAULT 0, 
	"PATRON" VARCHAR2(30 BYTE) DEFAULT '###,##0.00'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."CMONEDA" IS 'Código de la moneda, según ISO 4217';
   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."CTIPMONEDA" IS 'Tipo moneda: 1 - Moneda y 2 - Unidad Monetaria (por defecto 1)';
   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."NDECIMA" IS 'Número de decimales (por defecto 0)';
   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."CISO4217X" IS 'Código ISO - 4217X';
   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."CISO4217N" IS 'Código ISO - 4217N';
   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."CGENERO" IS 'Género de la moneda: M- Masculino y F - Femenino';
   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."NORDEN" IS 'Orden de visualización en las listas';
   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."BVISUALIZA" IS 'Indica si se visualiza o no: 1 - Verdadero (visualiza) y 0 - Falso (No visualiza)';
   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."CUSUALT" IS 'Código usuario de alta';
   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."CUSUMOD" IS 'Código usuario última modificación';
   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."FMODIFI" IS 'Fecha última modificación';
   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."CUSUBAJ" IS 'Código usuario baja lógica';
   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."FBAJA" IS 'Fecha baja lógica';
   COMMENT ON COLUMN "AXIS"."ECO_CODMONEDAS"."PATRON" IS 'Patrón definido para la moneda del registro. Ej : ###,##0.00';
   COMMENT ON TABLE "AXIS"."ECO_CODMONEDAS"  IS 'Códigos de moneda (ISO-4217)';
  GRANT UPDATE ON "AXIS"."ECO_CODMONEDAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ECO_CODMONEDAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ECO_CODMONEDAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ECO_CODMONEDAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ECO_CODMONEDAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ECO_CODMONEDAS" TO "PROGRAMADORESCSI";
