--------------------------------------------------------
--  DDL for Table ESTASEGURADOSMES
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTASEGURADOSMES" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER, 
	"NMOVIMI" NUMBER, 
	"NMES" NUMBER(2,0), 
	"NANYO" NUMBER(4,0) DEFAULT 0, 
	"FREGUL" DATE, 
	"NASEG" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTASEGURADOSMES"."SSEGURO" IS 'Identificador de poliza (SEGUROS)';
   COMMENT ON COLUMN "AXIS"."ESTASEGURADOSMES"."NRIESGO" IS 'Nro de riesgo (RIESGOS)';
   COMMENT ON COLUMN "AXIS"."ESTASEGURADOSMES"."NMOVIMI" IS 'Nro de movimiento (MOVSEGURO)';
   COMMENT ON COLUMN "AXIS"."ESTASEGURADOSMES"."NMES" IS 'Mes regularización  (Defecto 0)';
   COMMENT ON COLUMN "AXIS"."ESTASEGURADOSMES"."NANYO" IS 'Año regularización  (Defecto 0)';
   COMMENT ON COLUMN "AXIS"."ESTASEGURADOSMES"."FREGUL" IS 'Fecha de Regularización';
   COMMENT ON COLUMN "AXIS"."ESTASEGURADOSMES"."NASEG" IS 'Nro asegurados en el mes (Defecto 0)';
   COMMENT ON TABLE "AXIS"."ESTASEGURADOSMES"  IS 'Asegurados(innominados) por mes en la regularización EST';
  GRANT UPDATE ON "AXIS"."ESTASEGURADOSMES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTASEGURADOSMES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTASEGURADOSMES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTASEGURADOSMES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTASEGURADOSMES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTASEGURADOSMES" TO "PROGRAMADORESCSI";
