--------------------------------------------------------
--  DDL for Table ESTADOS_CORREO
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTADOS_CORREO" 
   (	"SCORREO" NUMBER(7,0), 
	"ESTADO" NUMBER, 
	"FECHA" DATE, 
	"MENSAJE_ERROR" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."ESTADOS_CORREO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTADOS_CORREO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTADOS_CORREO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTADOS_CORREO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTADOS_CORREO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTADOS_CORREO" TO "PROGRAMADORESCSI";
