--------------------------------------------------------
--  DDL for Table ESTAUTDISRIESGOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTAUTDISRIESGOS" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"CVERSION" VARCHAR2(11 BYTE), 
	"CDISPOSITIVO" VARCHAR2(10 BYTE), 
	"CPROPDISP" VARCHAR2(8 BYTE), 
	"IVALDISP" NUMBER, 
	"FINICONTRATO" DATE, 
	"FFINCONTRATO" DATE, 
	"NCONTRATO" NUMBER(15,0), 
	"TDESCDISP" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTAUTDISRIESGOS"."SSEGURO" IS 'Secuencial de seguro';
   COMMENT ON COLUMN "AXIS"."ESTAUTDISRIESGOS"."NRIESGO" IS 'Numero de riesgo';
   COMMENT ON COLUMN "AXIS"."ESTAUTDISRIESGOS"."NMOVIMI" IS 'Numero de movimiento';
   COMMENT ON COLUMN "AXIS"."ESTAUTDISRIESGOS"."CVERSION" IS 'Codigo de la version del vehiculo';
   COMMENT ON COLUMN "AXIS"."ESTAUTDISRIESGOS"."CDISPOSITIVO" IS 'Codigo Dispositivo';
   COMMENT ON COLUMN "AXIS"."ESTAUTDISRIESGOS"."CPROPDISP" IS 'Propietario dispositivo';
   COMMENT ON COLUMN "AXIS"."ESTAUTDISRIESGOS"."IVALDISP" IS 'Valor dispositivo';
   COMMENT ON COLUMN "AXIS"."ESTAUTDISRIESGOS"."FINICONTRATO" IS 'Fecha inicio contrato';
   COMMENT ON COLUMN "AXIS"."ESTAUTDISRIESGOS"."FFINCONTRATO" IS 'Fecha fin contrato';
   COMMENT ON COLUMN "AXIS"."ESTAUTDISRIESGOS"."NCONTRATO" IS 'n. contrato';
   COMMENT ON COLUMN "AXIS"."ESTAUTDISRIESGOS"."TDESCDISP" IS 'Desc dispositivo';
   COMMENT ON TABLE "AXIS"."ESTAUTDISRIESGOS"  IS 'Almacena los dispositivos de seguridad que tiene una póliza de autos';
  GRANT UPDATE ON "AXIS"."ESTAUTDISRIESGOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTAUTDISRIESGOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTAUTDISRIESGOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTAUTDISRIESGOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTAUTDISRIESGOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTAUTDISRIESGOS" TO "PROGRAMADORESCSI";
