--------------------------------------------------------
--  DDL for Table ESTBASEQUESTION_UNDW
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTBASEQUESTION_UNDW" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"CEMPRES" NUMBER(5,0), 
	"SORDEN" NUMBER, 
	"CODE" VARCHAR2(2000 BYTE), 
	"POSITION" NUMBER, 
	"CATEGORY" VARCHAR2(2000 BYTE), 
	"NORDEN" NUMBER, 
	"QUESTION" VARCHAR2(2000 BYTE), 
	"ANSWER" VARCHAR2(4000 BYTE), 
	"NASEG" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."ESTBASEQUESTION_UNDW" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTBASEQUESTION_UNDW" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTBASEQUESTION_UNDW" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTBASEQUESTION_UNDW" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTBASEQUESTION_UNDW" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTBASEQUESTION_UNDW" TO "PROGRAMADORESCSI";
