--------------------------------------------------------
--  DDL for Table ESTCASOS_BPMSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTCASOS_BPMSEG" 
   (	"SSEGURO" NUMBER, 
	"CEMPRES" NUMBER(5,0), 
	"NNUMCASO" NUMBER, 
	"CACTIVO" NUMBER(1,0), 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTCASOS_BPMSEG"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente';
   COMMENT ON COLUMN "AXIS"."ESTCASOS_BPMSEG"."CEMPRES" IS 'Código de empresa';
   COMMENT ON COLUMN "AXIS"."ESTCASOS_BPMSEG"."NNUMCASO" IS 'Número de caso';
   COMMENT ON COLUMN "AXIS"."ESTCASOS_BPMSEG"."CACTIVO" IS 'Indica si el caso está activo para el movimiento de seguro o no (1-0)';
   COMMENT ON COLUMN "AXIS"."ESTCASOS_BPMSEG"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."ESTCASOS_BPMSEG"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."ESTCASOS_BPMSEG"."FMODIFI" IS 'Fecha de modificación';
   COMMENT ON COLUMN "AXIS"."ESTCASOS_BPMSEG"."CUSUMOD" IS 'Usuario de modificación';
   COMMENT ON TABLE "AXIS"."ESTCASOS_BPMSEG"  IS 'Tabla que relaciona el caso BPM con el movimiento del seguro';
  GRANT UPDATE ON "AXIS"."ESTCASOS_BPMSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTCASOS_BPMSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTCASOS_BPMSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTCASOS_BPMSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTCASOS_BPMSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTCASOS_BPMSEG" TO "PROGRAMADORESCSI";
