--------------------------------------------------------
--  DDL for Table ESTGARANSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTGARANSEG" 
   (	"CGARANT" NUMBER(4,0), 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"SSEGURO" NUMBER, 
	"FINIEFE" DATE, 
	"NORDEN" NUMBER(4,0), 
	"CREVALI" NUMBER(2,0), 
	"CTARIFA" NUMBER(5,0), 
	"ICAPITAL" NUMBER, 
	"PRECARG" NUMBER(6,2), 
	"IEXTRAP" NUMBER(19,12), 
	"IPRIANU" NUMBER, 
	"FFINEFE" DATE, 
	"CFORMUL" NUMBER(4,0), 
	"CTIPFRA" NUMBER(1,0), 
	"IFRANQU" NUMBER, 
	"IRECARG" NUMBER, 
	"IPRITAR" NUMBER, 
	"PDTOCOM" NUMBER(6,2), 
	"IDTOCOM" NUMBER, 
	"PREVALI" NUMBER(5,2), 
	"IREVALI" NUMBER, 
	"ITARIFA" NUMBER(19,12), 
	"ITARREA" NUMBER(24,12), 
	"IPRITOT" NUMBER, 
	"ICAPTOT" NUMBER, 
	"FTARIFA" DATE, 
	"CREVALCAR" NUMBER(1,0), 
	"CGASGAR" NUMBER(1,0), 
	"PGASADQ" NUMBER(5,2), 
	"PGASADM" NUMBER(5,2), 
	"PDTOINT" NUMBER(5,2), 
	"IDTOINT" NUMBER, 
	"FEPREV" DATE, 
	"FPPREV" DATE, 
	"PERCRE" NUMBER(2,0), 
	"CMATCH" NUMBER(1,0), 
	"TDESMAT" VARCHAR2(75 BYTE), 
	"PINTFIN" NUMBER(5,2), 
	"CREF" NUMBER(1,0), 
	"CINTREF" NUMBER(3,0), 
	"PDIF" NUMBER(5,2), 
	"PINTTEC" NUMBER(5,2), 
	"NPARBEN" NUMBER(1,0), 
	"NBNS" NUMBER(1,0), 
	"TMGARAN" NUMBER, 
	"CDERREG" NUMBER(1,0), 
	"CCAMPANYA" NUMBER(3,0), 
	"NVERSIO" NUMBER(3,0), 
	"NMOVIMA" NUMBER(4,0) DEFAULT 1, 
	"CAGEVEN" NUMBER(6,0), 
	"NFACTOR" NUMBER, 
	"NLINEA" NUMBER(3,0), 
	"CFRANQ" NUMBER(6,0), 
	"NFRAVER" NUMBER(6,0), 
	"NGRPFRA" NUMBER(6,0), 
	"NGRPGARA" NUMBER(6,0), 
	"NORDFRA" NUMBER(6,0), 
	"PDTOFRA" NUMBER(7,4), 
	"CMOTMOV" NUMBER(3,0), 
	"FINIDER" DATE, 
	"FALTA" DATE, 
	"CTARMAN" NUMBER(2,0), 
	"COBLIGA" NUMBER(1,0), 
	"CTIPGAR" NUMBER(1,0), 
	"ITOTANU" NUMBER, 
	"PDTOTEC" NUMBER(6,2), 
	"PRECCOM" NUMBER(6,2), 
	"IDTOTEC" NUMBER, 
	"IRECCOM" NUMBER, 
	"ICAPRECOMEND" NUMBER, 
	"IPRICOM" NUMBER, 
	"FINIVIG" DATE, 
	"FFINVIG" DATE, 
	"CCOBPRIMA" NUMBER, 
	"IPRIDEV" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."IEXTRAP" IS 'Factor Extraprima';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."CREVALCAR" IS '0.- No revaloritza a la cartera, 1.- Si revaloriza a la cartera';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."CFRANQ" IS 'Código de franquicia';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."NFRAVER" IS 'Número versión de franquicia';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."NGRPFRA" IS 'Código de grupo de franquicias';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."NGRPGARA" IS 'Código de grupo de garantias para franquicia';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."NORDFRA" IS 'Orden Franquicia (pk detfranquicias)';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."PDTOFRA" IS 'Porcentaje de descuento de la franquicia';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."CMOTMOV" IS 'Código motivo de movimiento, solo informado en las garantías que se ha producido un cambio de producto';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."FINIDER" IS 'Fecha Inicio de Derechos.';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."FALTA" IS 'Fecha en que se dio de alta la Garantía';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."CTARMAN" IS 'Tipo de tarifa manual';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."COBLIGA" IS ' Indica si está contratada (1) o no (0)';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."CTIPGAR" IS ' Tipo de garantía';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."ITOTANU" IS 'Total prima anualizada';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."PDTOTEC" IS 'Porcentaje descuento técnico';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."PRECCOM" IS 'Porcentaje recargo comercial';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."IDTOTEC" IS 'Importe descuento técnico';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."IRECCOM" IS 'Importe recargo comercial';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."ICAPRECOMEND" IS 'Capital recomendado';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."IPRICOM" IS 'Importe sobre el que se ha de calcular la comisión';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."FINIVIG" IS 'Fecha inicio vigencia cobertura';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."FFINVIG" IS 'Fecha fin vigencia cobertura';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."CCOBPRIMA" IS 'Cobra Prima';
   COMMENT ON COLUMN "AXIS"."ESTGARANSEG"."IPRIDEV" IS 'Prima Devengada';
  GRANT UPDATE ON "AXIS"."ESTGARANSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTGARANSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTGARANSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTGARANSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTGARANSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTGARANSEG" TO "PROGRAMADORESCSI";
