--------------------------------------------------------
--  DDL for Table ESTMOTRETEN_REV
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTMOTRETEN_REV" 
   (	"NMOTRET" NUMBER, 
	"NMOTREV" NUMBER, 
	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER, 
	"NMOVIMI" NUMBER, 
	"CMOTRET" NUMBER, 
	"CUSUAUTO" VARCHAR2(40 BYTE), 
	"FUSUAUTO" DATE, 
	"CRESULTA" NUMBER, 
	"TOBSERVA" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."ESTMOTRETEN_REV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTMOTRETEN_REV" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTMOTRETEN_REV" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTMOTRETEN_REV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTMOTRETEN_REV" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTMOTRETEN_REV" TO "PROGRAMADORESCSI";
