--------------------------------------------------------
--  DDL for Table ESTMOTRETENCION
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTMOTRETENCION" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER, 
	"NMOVIMI" NUMBER, 
	"CMOTRET" NUMBER, 
	"CUSURET" VARCHAR2(40 BYTE), 
	"FRETEN" DATE, 
	"NMOTRET" NUMBER, 
	"CESTGEST" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTMOTRETENCION"."SSEGURO" IS 'código del seguro';
   COMMENT ON COLUMN "AXIS"."ESTMOTRETENCION"."NRIESGO" IS 'número del riesgo';
   COMMENT ON COLUMN "AXIS"."ESTMOTRETENCION"."NMOVIMI" IS 'número del movimiento';
   COMMENT ON COLUMN "AXIS"."ESTMOTRETENCION"."CMOTRET" IS 'código del motivo de retención (1.- Cuestionario Salud, 2.- Límites Capital)';
   COMMENT ON COLUMN "AXIS"."ESTMOTRETENCION"."CUSURET" IS 'código del usuario que retiene la póliza';
   COMMENT ON COLUMN "AXIS"."ESTMOTRETENCION"."FRETEN" IS 'fecha/hora de la retención de la póliza';
   COMMENT ON COLUMN "AXIS"."ESTMOTRETENCION"."NMOTRET" IS 'Numero de linea';
   COMMENT ON COLUMN "AXIS"."ESTMOTRETENCION"."CESTGEST" IS 'Estado gestión de la retención. VF (800016)';
   COMMENT ON TABLE "AXIS"."ESTMOTRETENCION"  IS 'En esta tabla se informarán los motivos de la retención de una póliza.';
  GRANT UPDATE ON "AXIS"."ESTMOTRETENCION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTMOTRETENCION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTMOTRETENCION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTMOTRETENCION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTMOTRETENCION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTMOTRETENCION" TO "PROGRAMADORESCSI";
