--------------------------------------------------------
--  DDL for Table ESTPER_AUTCARNET
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTPER_AUTCARNET" 
   (	"SPERSON" NUMBER(10,0), 
	"CAGENTE" NUMBER, 
	"CTIPCAR" VARCHAR2(4 BYTE), 
	"FCARNET" DATE, 
	"CDEFECTO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTPER_AUTCARNET"."SPERSON" IS 'Codigo de persona';
   COMMENT ON COLUMN "AXIS"."ESTPER_AUTCARNET"."CAGENTE" IS 'Codigo de Agente';
   COMMENT ON COLUMN "AXIS"."ESTPER_AUTCARNET"."CTIPCAR" IS 'codigo tipo de carnet';
   COMMENT ON COLUMN "AXIS"."ESTPER_AUTCARNET"."FCARNET" IS 'Fecha de carnet';
   COMMENT ON COLUMN "AXIS"."ESTPER_AUTCARNET"."CDEFECTO" IS 'Fecha de carnet defecto';
   COMMENT ON TABLE "AXIS"."ESTPER_AUTCARNET"  IS 'Tabla de PER_AUTCARNET';
  GRANT UPDATE ON "AXIS"."ESTPER_AUTCARNET" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTPER_AUTCARNET" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTPER_AUTCARNET" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTPER_AUTCARNET" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTPER_AUTCARNET" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTPER_AUTCARNET" TO "PROGRAMADORESCSI";
