--------------------------------------------------------
--  DDL for Table ESTPRESTTITULARES
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTPRESTTITULARES" 
   (	"CTAPRES" VARCHAR2(50 BYTE), 
	"NORDEN" NUMBER(2,0), 
	"SNIP" VARCHAR2(15 BYTE), 
	"PPORCEN" NUMBER(5,2), 
	"SSEGURO" NUMBER, 
	"FALTA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTPRESTTITULARES"."CTAPRES" IS 'Código del préstamo';
   COMMENT ON COLUMN "AXIS"."ESTPRESTTITULARES"."NORDEN" IS 'Número de orden del titular';
   COMMENT ON COLUMN "AXIS"."ESTPRESTTITULARES"."SNIP" IS 'SIP del titular';
   COMMENT ON COLUMN "AXIS"."ESTPRESTTITULARES"."PPORCEN" IS 'Porcent. sobre el prestamo';
   COMMENT ON COLUMN "AXIS"."ESTPRESTTITULARES"."SSEGURO" IS 'sseguro de las tablas de estudio';
   COMMENT ON COLUMN "AXIS"."ESTPRESTTITULARES"."FALTA" IS 'Fecha de alta del préstamo';
   COMMENT ON TABLE "AXIS"."ESTPRESTTITULARES"  IS 'Titulares del préstamo';
  GRANT UPDATE ON "AXIS"."ESTPRESTTITULARES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTPRESTTITULARES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTPRESTTITULARES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTPRESTTITULARES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTPRESTTITULARES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTPRESTTITULARES" TO "PROGRAMADORESCSI";
