--------------------------------------------------------
--  DDL for Table ESTPSU_RETENIDAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTPSU_RETENIDAS" 
   (	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER(4,0), 
	"FMOVIMI" DATE, 
	"CMOTRET" NUMBER(4,0), 
	"CNIVELBPM" NUMBER(6,0), 
	"CUSURET" VARCHAR2(20 BYTE), 
	"FFECRET" DATE, 
	"CUSUAUT" VARCHAR2(20 BYTE), 
	"FFECAUT" DATE, 
	"OBSERV" VARCHAR2(4000 BYTE), 
	"POSTPPER" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"PERPOST" NUMBER DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTPSU_RETENIDAS"."SSEGURO" IS 'Identificativo Seguros';
   COMMENT ON COLUMN "AXIS"."ESTPSU_RETENIDAS"."NMOVIMI" IS 'Movimiento de Movseguro';
   COMMENT ON COLUMN "AXIS"."ESTPSU_RETENIDAS"."FMOVIMI" IS 'Fecha Movseguro';
   COMMENT ON COLUMN "AXIS"."ESTPSU_RETENIDAS"."CMOTRET" IS '0 = Autorizada, 1 = Pendiente Continuar,
                                                 2 = Pendiente Autorizar, 3 = Bloqueada,
                                                 4 = Rechazada, 5 = No Aplica por Cambio';
   COMMENT ON COLUMN "AXIS"."ESTPSU_RETENIDAS"."CNIVELBPM" IS 'Nivel del usuario a los cuales se les
                                                 enviará la incidencia PSU';
   COMMENT ON COLUMN "AXIS"."ESTPSU_RETENIDAS"."CUSURET" IS 'Usuario grabador';
   COMMENT ON COLUMN "AXIS"."ESTPSU_RETENIDAS"."FFECRET" IS 'Fecha retención';
   COMMENT ON COLUMN "AXIS"."ESTPSU_RETENIDAS"."CUSUAUT" IS 'Usuario autoriza/rechaza';
   COMMENT ON COLUMN "AXIS"."ESTPSU_RETENIDAS"."FFECAUT" IS 'Fecha autorización/rechazo';
   COMMENT ON COLUMN "AXIS"."ESTPSU_RETENIDAS"."OBSERV" IS 'Observaciones';
   COMMENT ON COLUMN "AXIS"."ESTPSU_RETENIDAS"."POSTPPER" IS 'Periodo pospuesto de la propuesta V.F. 8001026.';
   COMMENT ON TABLE "AXIS"."ESTPSU_RETENIDAS"  IS 'Cabecera de los Controles PSU por póliza';
  GRANT UPDATE ON "AXIS"."ESTPSU_RETENIDAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTPSU_RETENIDAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTPSU_RETENIDAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTPSU_RETENIDAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTPSU_RETENIDAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTPSU_RETENIDAS" TO "PROGRAMADORESCSI";
