--------------------------------------------------------
--  DDL for Table ESTPER_DIRECCIONES
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTPER_DIRECCIONES" 
   (	"SPERSON" NUMBER(10,0), 
	"CAGENTE" NUMBER, 
	"CDOMICI" NUMBER, 
	"CTIPDIR" NUMBER(2,0), 
	"CSIGLAS" NUMBER(2,0), 
	"TNOMVIA" VARCHAR2(200 BYTE), 
	"NNUMVIA" NUMBER(5,0), 
	"TCOMPLE" VARCHAR2(100 BYTE), 
	"TDOMICI" VARCHAR2(1000 BYTE), 
	"CPOSTAL" VARCHAR2(30 BYTE), 
	"CPOBLAC" NUMBER, 
	"CPROVIN" NUMBER, 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FMOVIMI" DATE, 
	"CORIGEN" VARCHAR2(3 BYTE), 
	"TRECIBIDO" VARCHAR2(2000 BYTE), 
	"CVIAVP" NUMBER(2,0), 
	"CLITVP" NUMBER(2,0), 
	"CBISVP" NUMBER(2,0), 
	"CORVP" NUMBER(2,0), 
	"NVIAADCO" NUMBER(5,0), 
	"CLITCO" NUMBER(2,0), 
	"CORCO" NUMBER(2,0), 
	"NPLACACO" NUMBER(5,0), 
	"COR2CO" NUMBER(2,0), 
	"CDET1IA" NUMBER(2,0), 
	"TNUM1IA" VARCHAR2(100 BYTE), 
	"CDET2IA" NUMBER(2,0), 
	"TNUM2IA" VARCHAR2(100 BYTE), 
	"CDET3IA" NUMBER(2,0), 
	"TNUM3IA" VARCHAR2(100 BYTE), 
	"LOCALIDAD" VARCHAR2(3000 BYTE), 
	"FDEFECTO" NUMBER, 
	"TALIAS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."SPERSON" IS 'Secuencia unica de identificacion de una persona';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CAGENTE" IS 'Código agente';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CDOMICI" IS 'Código domicilio';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CTIPDIR" IS 'Tipo de dirección';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CSIGLAS" IS 'Código siglas';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."TNOMVIA" IS 'Nombre vía';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."NNUMVIA" IS 'Número vía';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."TCOMPLE" IS 'Descripción complementaria';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."TDOMICI" IS 'Descripción dirección no normalizada';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CPOSTAL" IS 'Código postal';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CPOBLAC" IS 'Código población';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CPROVIN" IS 'Código província';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CUSUARI" IS 'Código usuario modificación registro';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."FMOVIMI" IS 'Fecha modificación registro';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CVIAVP" IS 'Código de via predio - via principal';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CLITVP" IS 'Código de literal predio - via principal';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CBISVP" IS 'Código BIS predio - via principal';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CORVP" IS 'Código orientación predio - via principal';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."NVIAADCO" IS 'Número de via adyacente predio - coordenada';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CLITCO" IS 'Código de literal predio - coordenada';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CORCO" IS 'Código orientación predio - coordenada';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."NPLACACO" IS 'Número consecutivo placa predio - ccordenada';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."COR2CO" IS 'Código orientación predio 2 - coordenada';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CDET1IA" IS 'Código detalle 1 - información adicional';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."TNUM1IA" IS 'Número predio 1 - informacion adicional';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CDET2IA" IS 'Código detalle 2 - información adicional';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."TNUM2IA" IS 'Número predio 2 - informacion adicional';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."CDET3IA" IS 'Código detalle 3 - información adicional';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."TNUM3IA" IS 'Número predio 3 - informacion adicional';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."LOCALIDAD" IS 'Localidad';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."FDEFECTO" IS 'Dirección fiscal por defecto';
   COMMENT ON COLUMN "AXIS"."ESTPER_DIRECCIONES"."TALIAS" IS 'Alias - NIT Unico';
   COMMENT ON TABLE "AXIS"."ESTPER_DIRECCIONES"  IS 'Tabla con la dirección de la persona';
  GRANT UPDATE ON "AXIS"."ESTPER_DIRECCIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTPER_DIRECCIONES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTPER_DIRECCIONES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTPER_DIRECCIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTPER_DIRECCIONES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTPER_DIRECCIONES" TO "PROGRAMADORESCSI";
