--------------------------------------------------------
--  DDL for Table ESTPER_IRPF
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTPER_IRPF" 
   (	"SPERSON" NUMBER(10,0), 
	"CSITFAM" NUMBER(1,0), 
	"CNIFCON" VARCHAR2(10 BYTE), 
	"CGRADO" NUMBER(1,0), 
	"CAYUDA" NUMBER(1,0), 
	"IPENSION" NUMBER(25,10), 
	"IANUHIJOS" NUMBER, 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FMOVIMI" DATE, 
	"PROLON" NUMBER(2,0), 
	"RMOVGEO" NUMBER(2,0), 
	"IGASTOCONV" NUMBER, 
	"ITOTALRENTA" NUMBER, 
	"IRENDTRAB" NUMBER, 
	"PAPLICABLE" NUMBER, 
	"IEXENTO" NUMBER, 
	"NANO" NUMBER(4,0), 
	"CAGENTE" NUMBER, 
	"FMOVGEO" DATE, 
	"CPAGO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."SPERSON" IS 'Código de único de persona';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."CSITFAM" IS 'Código situación Familiar. Valor fijo 883';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."CNIFCON" IS 'Nif conyuge';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."CGRADO" IS 'Grado minusvalia. Valor fijo 688';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."CAYUDA" IS 'Como trabajador precisa la ayuda de terceras personas para desplazarse a su lugar de trabajo. ';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."IPENSION" IS 'Pensión compensatoria al conyuge.';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."IANUHIJOS" IS 'Anualidades de hijos.';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."CUSUARI" IS 'Usuario alta';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."FMOVIMI" IS 'Fecha alta';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."PROLON" IS 'Prolongación de actividad laboral';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."RMOVGEO" IS 'Reducción por movilidad geografica.';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."IGASTOCONV" IS 'Importe gastos convenio especial';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."ITOTALRENTA" IS 'Importe total rentas del año';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."IRENDTRAB" IS 'Importe rendimiento trabajo';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."PAPLICABLE" IS '% aplicable';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."IEXENTO" IS 'Exento';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."NANO" IS 'Número de año';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."FMOVGEO" IS 'Fecha de movilidad geografica';
   COMMENT ON COLUMN "AXIS"."ESTPER_IRPF"."CPAGO" IS 'Indica si hay pagos por adquisición o rehabilitación de vivienda 0-No 1-Si';
  GRANT UPDATE ON "AXIS"."ESTPER_IRPF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTPER_IRPF" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTPER_IRPF" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTPER_IRPF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTPER_IRPF" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTPER_IRPF" TO "PROGRAMADORESCSI";
