--------------------------------------------------------
--  DDL for Table ESTRESULSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTRESULSEG" 
   (	"CLAVE" NUMBER(6,0), 
	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0), 
	"FINIEFE" DATE, 
	"NRESULT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTRESULSEG"."CLAVE" IS 'IDENTIFICADOR DE LA FORMULA USADA';
   COMMENT ON COLUMN "AXIS"."ESTRESULSEG"."SSEGURO" IS 'IDENTIFICADOR DEL SEGURO';
   COMMENT ON COLUMN "AXIS"."ESTRESULSEG"."NRIESGO" IS 'IDENTIFICADOR DEL RIESGO';
   COMMENT ON COLUMN "AXIS"."ESTRESULSEG"."NMOVIMI" IS 'IDENTIFICADOR DEL MOVIMIENTO';
   COMMENT ON COLUMN "AXIS"."ESTRESULSEG"."CGARANT" IS 'IDENTIFICADOR DE LA GARANTIA';
   COMMENT ON COLUMN "AXIS"."ESTRESULSEG"."FINIEFE" IS 'FECHA INICIO EFECTO';
   COMMENT ON COLUMN "AXIS"."ESTRESULSEG"."NRESULT" IS 'RESULTADO DE LA FORMULA SOBRE LA GARANTIA';
   COMMENT ON TABLE "AXIS"."ESTRESULSEG"  IS 'RESULTADO DE LAS FORMULAS DE SGT - TABLAS DE ESTUDIOS';
  GRANT UPDATE ON "AXIS"."ESTRESULSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTRESULSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTRESULSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTRESULSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTRESULSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTRESULSEG" TO "PROGRAMADORESCSI";
