--------------------------------------------------------
--  DDL for Table ESTSUSPENSIONSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTSUSPENSIONSEG" 
   (	"SSEGURO" NUMBER, 
	"FINICIO" DATE, 
	"FFINAL" DATE, 
	"TTEXTO" VARCHAR2(1000 BYTE), 
	"CMOTMOV" NUMBER(3,0), 
	"NMOVIMI" NUMBER(4,0), 
	"FVIGENCIA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTSUSPENSIONSEG"."SSEGURO" IS 'C¿digo del seguro';
   COMMENT ON COLUMN "AXIS"."ESTSUSPENSIONSEG"."FINICIO" IS 'Fecha de inicio de la suspensi¿n/reinicio';
   COMMENT ON COLUMN "AXIS"."ESTSUSPENSIONSEG"."FFINAL" IS 'Fecha de fin de la suspensi¿n/reinicio';
   COMMENT ON COLUMN "AXIS"."ESTSUSPENSIONSEG"."TTEXTO" IS 'Motivo de la suspensi¿n/reinicio';
   COMMENT ON COLUMN "AXIS"."ESTSUSPENSIONSEG"."CMOTMOV" IS 'Motivo del movimiento que corresponde al tipo de suspension/reinicio ( 261.- Suspemsi¿n, 262.- Reinicio )';
   COMMENT ON COLUMN "AXIS"."ESTSUSPENSIONSEG"."NMOVIMI" IS 'N¿mero del movimiento al que corresponde la suspensi¿n/reinicio';
   COMMENT ON COLUMN "AXIS"."ESTSUSPENSIONSEG"."FVIGENCIA" IS 'Fecha fin de vigencia una vez reiniciada (s¿lo para reinicios)';
   COMMENT ON TABLE "AXIS"."ESTSUSPENSIONSEG"  IS 'Suspensi¿n/reinicio de seguros';
  GRANT UPDATE ON "AXIS"."ESTSUSPENSIONSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTSUSPENSIONSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTSUSPENSIONSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTSUSPENSIONSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTSUSPENSIONSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTSUSPENSIONSEG" TO "PROGRAMADORESCSI";
