--------------------------------------------------------
--  DDL for Table ESTSEG_CBANCAR
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTSEG_CBANCAR" 
   (	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER, 
	"FINIEFE" DATE, 
	"FFINEFE" DATE, 
	"CBANCAR" VARCHAR2(50 BYTE), 
	"CBANCOB" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTSEG_CBANCAR"."SSEGURO" IS 'Id del seguro';
   COMMENT ON COLUMN "AXIS"."ESTSEG_CBANCAR"."NMOVIMI" IS 'Id. del movimiento de alta de la cuenta bancaria';
   COMMENT ON COLUMN "AXIS"."ESTSEG_CBANCAR"."FINIEFE" IS 'Fecha de inicio de efecto de la cuenta';
   COMMENT ON COLUMN "AXIS"."ESTSEG_CBANCAR"."FFINEFE" IS 'Fecha fin del uso de la cuenta bancaria';
   COMMENT ON COLUMN "AXIS"."ESTSEG_CBANCAR"."CBANCAR" IS 'Cuenta de cargo';
  GRANT UPDATE ON "AXIS"."ESTSEG_CBANCAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTSEG_CBANCAR" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTSEG_CBANCAR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTSEG_CBANCAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTSEG_CBANCAR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTSEG_CBANCAR" TO "PROGRAMADORESCSI";
