--------------------------------------------------------
--  DDL for Table ESTSALDODEUTORSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTSALDODEUTORSEG" 
   (	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER(4,0), 
	"ICAPMAX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTSALDODEUTORSEG"."SSEGURO" IS 'Identificador del seguro';
   COMMENT ON COLUMN "AXIS"."ESTSALDODEUTORSEG"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."ESTSALDODEUTORSEG"."ICAPMAX" IS 'Importe Capital máximo por pólizas';
   COMMENT ON TABLE "AXIS"."ESTSALDODEUTORSEG"  IS 'Información del Saldo Deutor por póliza';
  GRANT UPDATE ON "AXIS"."ESTSALDODEUTORSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTSALDODEUTORSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTSALDODEUTORSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTSALDODEUTORSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTSALDODEUTORSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTSALDODEUTORSEG" TO "PROGRAMADORESCSI";
