--------------------------------------------------------
--  DDL for Table ESTVALIDACARGAPREGTAB
--------------------------------------------------------

  CREATE TABLE "AXIS"."ESTVALIDACARGAPREGTAB" 
   (	"CPREGUN" NUMBER, 
	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER, 
	"NRIESGO" NUMBER, 
	"CGARANT" NUMBER, 
	"NORDEN" NUMBER, 
	"SPROCES" NUMBER, 
	"CVALIDA" NUMBER, 
	"CUSUARI" VARCHAR2(50 BYTE), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ESTVALIDACARGAPREGTAB"."CPREGUN" IS 'Código de pregunta';
   COMMENT ON COLUMN "AXIS"."ESTVALIDACARGAPREGTAB"."SSEGURO" IS 'Código de seguro';
   COMMENT ON COLUMN "AXIS"."ESTVALIDACARGAPREGTAB"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."ESTVALIDACARGAPREGTAB"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."ESTVALIDACARGAPREGTAB"."CGARANT" IS 'Garantia';
   COMMENT ON COLUMN "AXIS"."ESTVALIDACARGAPREGTAB"."NORDEN" IS 'Número de orden';
   COMMENT ON COLUMN "AXIS"."ESTVALIDACARGAPREGTAB"."SPROCES" IS 'Código de proceso';
   COMMENT ON COLUMN "AXIS"."ESTVALIDACARGAPREGTAB"."CVALIDA" IS 'Estado de la carga 0-Ok 1-Ko';
   COMMENT ON COLUMN "AXIS"."ESTVALIDACARGAPREGTAB"."CUSUARI" IS 'Usuario que autoriza la carga';
   COMMENT ON COLUMN "AXIS"."ESTVALIDACARGAPREGTAB"."FECHA" IS 'Fecha de la autorización';
   COMMENT ON TABLE "AXIS"."ESTVALIDACARGAPREGTAB"  IS 'Tabla para validar cargas de preguntas tipo tabla';
  GRANT UPDATE ON "AXIS"."ESTVALIDACARGAPREGTAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTVALIDACARGAPREGTAB" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ESTVALIDACARGAPREGTAB" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ESTVALIDACARGAPREGTAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ESTVALIDACARGAPREGTAB" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ESTVALIDACARGAPREGTAB" TO "PROGRAMADORESCSI";
