--------------------------------------------------------
--  DDL for Table EXCLUSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."EXCLUSEG" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0), 
	"NMOVIMI" NUMBER(6,0), 
	"FINIEFE" DATE, 
	"NMOVIMA" NUMBER(4,0) DEFAULT 1, 
	"CEXCLU" VARCHAR2(6 BYTE), 
	"NDURACI" NUMBER(5,2), 
	"CIZQDER" VARCHAR2(1 BYTE), 
	"NPROEXT" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."EXCLUSEG"."SSEGURO" IS 'Número de Seguro';
   COMMENT ON COLUMN "AXIS"."EXCLUSEG"."NRIESGO" IS 'Número de Riesgo';
   COMMENT ON COLUMN "AXIS"."EXCLUSEG"."CGARANT" IS 'Código Garantia';
   COMMENT ON COLUMN "AXIS"."EXCLUSEG"."NMOVIMI" IS 'NÚmero de movimiento';
   COMMENT ON COLUMN "AXIS"."EXCLUSEG"."FINIEFE" IS 'Fecha Efecto del movimiento';
   COMMENT ON COLUMN "AXIS"."EXCLUSEG"."NMOVIMA" IS 'NÚmero de movimiento de alta';
   COMMENT ON COLUMN "AXIS"."EXCLUSEG"."CEXCLU" IS 'Código de exclusión';
   COMMENT ON COLUMN "AXIS"."EXCLUSEG"."NDURACI" IS 'Meses de duración';
   COMMENT ON COLUMN "AXIS"."EXCLUSEG"."CIZQDER" IS 'Lado afectado (Izquierda - Derecha - Ambos) CVALOR: 852';
   COMMENT ON COLUMN "AXIS"."EXCLUSEG"."NPROEXT" IS 'Centros propios o externos. CVALOR: 851';
   COMMENT ON TABLE "AXIS"."EXCLUSEG"  IS 'Exclusiones por garantía, seguro, riesgo y movimiento';
  GRANT UPDATE ON "AXIS"."EXCLUSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."EXCLUSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."EXCLUSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."EXCLUSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."EXCLUSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."EXCLUSEG" TO "PROGRAMADORESCSI";
