--------------------------------------------------------
--  DDL for Table EXTBSTRAMOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."EXTBSTRAMOS" 
   (	"CGRUPO" VARCHAR2(2 BYTE), 
	"CTRAMINI" NUMBER(10,0), 
	"CTRAMMAX" NUMBER(10,0), 
	"NAVEMAQ" NUMBER(8,4), 
	"NCOMPLE" NUMBER(8,4), 
	"CTARGRU" VARCHAR2(2 BYTE), 
	"FVIGINI" DATE, 
	"FVIGFIN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."EXTBSTRAMOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."EXTBSTRAMOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."EXTBSTRAMOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."EXTBSTRAMOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."EXTBSTRAMOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."EXTBSTRAMOS" TO "PROGRAMADORESCSI";
