--------------------------------------------------------
--  DDL for Table FATCAREPORT
--------------------------------------------------------

  CREATE TABLE "AXIS"."FATCAREPORT" 
   (	"SPROCES" NUMBER, 
	"NORDEN" NUMBER, 
	"SLINEA" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."FATCAREPORT"."SPROCES" IS 'Código del Proceso';
   COMMENT ON COLUMN "AXIS"."FATCAREPORT"."NORDEN" IS 'Numero de orden';
   COMMENT ON COLUMN "AXIS"."FATCAREPORT"."SLINEA" IS 'Linea';
  GRANT UPDATE ON "AXIS"."FATCAREPORT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FATCAREPORT" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."FATCAREPORT" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."FATCAREPORT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FATCAREPORT" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."FATCAREPORT" TO "PROGRAMADORESCSI";
