--------------------------------------------------------
--  DDL for Table FIC_BLOQUES_DATOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."FIC_BLOQUES_DATOS" 
   (	"TGESTOR" VARCHAR2(20 BYTE), 
	"TFORMAT" VARCHAR2(20 BYTE), 
	"TBLQDAT" NUMBER(4,0), 
	"TNOMBRE" VARCHAR2(100 BYTE), 
	"TDESCRI" VARCHAR2(100 BYTE), 
	"NNUMCOL" NUMBER(4,0), 
	"FFECREA" DATE, 
	"FMOVIMI" DATE, 
	"CUSALTA" VARCHAR2(20 BYTE), 
	"CUSUARI" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."FIC_BLOQUES_DATOS"."TGESTOR" IS 'código del informe';
   COMMENT ON COLUMN "AXIS"."FIC_BLOQUES_DATOS"."TFORMAT" IS 'código del formato';
   COMMENT ON COLUMN "AXIS"."FIC_BLOQUES_DATOS"."TBLQDAT" IS 'codigo del bloque de dato o unidad de captura';
   COMMENT ON COLUMN "AXIS"."FIC_BLOQUES_DATOS"."TNOMBRE" IS 'nombre del bloque de dato o unidad de captura';
   COMMENT ON COLUMN "AXIS"."FIC_BLOQUES_DATOS"."TDESCRI" IS 'descripcion bloque de dato o unidad de captura';
   COMMENT ON COLUMN "AXIS"."FIC_BLOQUES_DATOS"."NNUMCOL" IS 'numero de columnas bloque de dato o unidad de captura';
   COMMENT ON TABLE "AXIS"."FIC_BLOQUES_DATOS"  IS 'Esta tabla permite configurar cada uno de los bloques de datos o unidades de captura';
  GRANT UPDATE ON "AXIS"."FIC_BLOQUES_DATOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FIC_BLOQUES_DATOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."FIC_BLOQUES_DATOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."FIC_BLOQUES_DATOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FIC_BLOQUES_DATOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."FIC_BLOQUES_DATOS" TO "PROGRAMADORESCSI";
