--------------------------------------------------------
--  DDL for Table FIN_PARAMETROS
--------------------------------------------------------

  CREATE TABLE "AXIS"."FIN_PARAMETROS" 
   (	"SFINANCI" NUMBER, 
	"NMOVIMI" NUMBER, 
	"CPARAM" VARCHAR2(20 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIF" DATE, 
	"FVALPAR" DATE, 
	"NVALPAR" NUMBER, 
	"TVALPAR" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."FIN_PARAMETROS"."SFINANCI" IS 'Codigo ficha financiera';
   COMMENT ON COLUMN "AXIS"."FIN_PARAMETROS"."CPARAM" IS 'Codigo del parametro';
   COMMENT ON COLUMN "AXIS"."FIN_PARAMETROS"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."FIN_PARAMETROS"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."FIN_PARAMETROS"."CUSUMOD" IS 'Usuario de modificacion';
   COMMENT ON COLUMN "AXIS"."FIN_PARAMETROS"."FMODIF" IS 'Fecha de modificacion';
   COMMENT ON COLUMN "AXIS"."FIN_PARAMETROS"."FVALPAR" IS 'Valor fecha parametro';
   COMMENT ON COLUMN "AXIS"."FIN_PARAMETROS"."NVALPAR" IS 'valor numero parametro';
  GRANT UPDATE ON "AXIS"."FIN_PARAMETROS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FIN_PARAMETROS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."FIN_PARAMETROS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."FIN_PARAMETROS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FIN_PARAMETROS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."FIN_PARAMETROS" TO "PROGRAMADORESCSI";
