--------------------------------------------------------
--  DDL for Table FIN_INDICA_SECTOR
--------------------------------------------------------

  CREATE TABLE "AXIS"."FIN_INDICA_SECTOR" 
   (	"CCIIU" NUMBER, 
	"NMOVIMI" NUMBER, 
	"IMARGEN" NUMBER, 
	"ICAPTRAB" NUMBER, 
	"TRAZCOR" VARCHAR2(2000 BYTE), 
	"TPRBACI" VARCHAR2(2000 BYTE), 
	"IENDUADA" NUMBER, 
	"NDIACAR" NUMBER, 
	"NROTPRO" NUMBER, 
	"NROTINV" NUMBER, 
	"NDIACICL" NUMBER, 
	"IRENTAB" NUMBER, 
	"IOBLCP" NUMBER, 
	"IOBLLP" NUMBER, 
	"IGASTFIN" NUMBER, 
	"IVALPT" NUMBER, 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."CCIIU" IS 'Codigo CCIIU V.F. 8001072';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."NMOVIMI" IS 'Movimiento Indicador';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."IMARGEN" IS 'Margen operacional';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."ICAPTRAB" IS 'Capital trabajo';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."TRAZCOR" IS 'Raz¿n corriente';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."TPRBACI" IS 'Prueba acida';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."IENDUADA" IS 'Endeudamiento total';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."NDIACAR" IS 'Rotaci¿n Cartera(D¿as)';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."NROTPRO" IS 'Rotaci¿n proveedores';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."NROTINV" IS 'Rotaci¿n de inventarios';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."NDIACICL" IS 'Ciclo de efectivo(D¿as)';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."IRENTAB" IS 'Rentabilidad';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."IOBLCP" IS 'Obliga. Fin. CP/Ventas';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."IOBLLP" IS 'Obliga. Fin. LP/Ventas';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."IGASTFIN" IS 'Gastos. Fin. /UOP';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."IVALPT" IS 'Valoraci¿n /PT';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."FIN_INDICA_SECTOR"."CUSUALT" IS 'Usuario de alta';
  GRANT UPDATE ON "AXIS"."FIN_INDICA_SECTOR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FIN_INDICA_SECTOR" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."FIN_INDICA_SECTOR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."FIN_INDICA_SECTOR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FIN_INDICA_SECTOR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."FIN_INDICA_SECTOR" TO "PROGRAMADORESCSI";
