--------------------------------------------------------
--  DDL for Table FIS_MODHACIENDA
--------------------------------------------------------

  CREATE TABLE "AXIS"."FIS_MODHACIENDA" 
   (	"CRAMO" NUMBER(8,0), 
	"MODHACIENDA" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."FIS_MODHACIENDA"."CRAMO" IS 'Ramo';
   COMMENT ON COLUMN "AXIS"."FIS_MODHACIENDA"."MODHACIENDA" IS 'Modelo de fiscalidad';
   COMMENT ON TABLE "AXIS"."FIS_MODHACIENDA"  IS 'Tabla de modelos de fiscalidad';
  GRANT UPDATE ON "AXIS"."FIS_MODHACIENDA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FIS_MODHACIENDA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."FIS_MODHACIENDA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."FIS_MODHACIENDA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FIS_MODHACIENDA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."FIS_MODHACIENDA" TO "PROGRAMADORESCSI";
