--------------------------------------------------------
--  DDL for Table FIS_DETCIERREPAGO_TMP
--------------------------------------------------------

  CREATE TABLE "AXIS"."FIS_DETCIERREPAGO_TMP" 
   (	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"PFISCAL" NUMBER(6,0), 
	"NNUMPET" NUMBER, 
	"SSEGURO" NUMBER, 
	"SPERSONP" NUMBER(10,0), 
	"NNUMNIFP" VARCHAR2(14 BYTE), 
	"TIDENTIP" NUMBER(1,0), 
	"CDOMICIP" NUMBER, 
	"SPERSON1" NUMBER(10,0), 
	"NNUMNIF1" VARCHAR2(14 BYTE), 
	"TIDENTI1" NUMBER(1,0), 
	"CDOMICI1" NUMBER, 
	"CTIPO" CHAR(3 BYTE), 
	"NDOCUM" NUMBER(9,0), 
	"CESTREC" NUMBER(1,0), 
	"FPAGO" DATE, 
	"IBRUTO" NUMBER, 
	"IRESRCM" NUMBER, 
	"IRESRED" NUMBER, 
	"IBASE" NUMBER, 
	"PRETENC" NUMBER(5,3), 
	"IRETENC" NUMBER, 
	"INETO" NUMBER, 
	"CPAISRET" NUMBER(3,0), 
	"CSUBTIPO" NUMBER(4,0), 
	"CSIGBASE" CHAR(1 BYTE), 
	"CERROR" NUMBER(6,0), 
	"CPROVIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."FIS_DETCIERREPAGO_TMP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FIS_DETCIERREPAGO_TMP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."FIS_DETCIERREPAGO_TMP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."FIS_DETCIERREPAGO_TMP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FIS_DETCIERREPAGO_TMP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."FIS_DETCIERREPAGO_TMP" TO "PROGRAMADORESCSI";
