--------------------------------------------------------
--  DDL for Table FIS_MODELOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."FIS_MODELOS" 
   (	"CMODELO" VARCHAR2(10 BYTE), 
	"CIDIOMA" NUMBER(2,0), 
	"TMODELO" VARCHAR2(200 BYTE), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."FIS_MODELOS"."CMODELO" IS 'Identificador de modelo';
   COMMENT ON COLUMN "AXIS"."FIS_MODELOS"."CIDIOMA" IS 'Idioma';
   COMMENT ON COLUMN "AXIS"."FIS_MODELOS"."TMODELO" IS 'Descripcion del modelo';
   COMMENT ON COLUMN "AXIS"."FIS_MODELOS"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."FIS_MODELOS"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."FIS_MODELOS"."CUSUMOD" IS 'Usuario de modificación';
   COMMENT ON COLUMN "AXIS"."FIS_MODELOS"."FMODIFI" IS 'Fecha de modificación';
   COMMENT ON TABLE "AXIS"."FIS_MODELOS"  IS 'Tabla de todos los modelos fiscales disponibles';
  GRANT UPDATE ON "AXIS"."FIS_MODELOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FIS_MODELOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."FIS_MODELOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."FIS_MODELOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FIS_MODELOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."FIS_MODELOS" TO "PROGRAMADORESCSI";
