--------------------------------------------------------
--  DDL for Table FIS_MOD188
--------------------------------------------------------

  CREATE TABLE "AXIS"."FIS_MOD188" 
   (	"SFISCAB" NUMBER(8,0), 
	"NANYO" NUMBER(4,0), 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CTIPO" CHAR(3 BYTE), 
	"NNIFDEC" VARCHAR2(9 BYTE), 
	"SPERSONP" NUMBER(10,0), 
	"NNIFPER" VARCHAR2(9 BYTE), 
	"SPERSONR" NUMBER(10,0), 
	"NNIFREP" VARCHAR2(9 BYTE), 
	"TNOMPER" VARCHAR2(40 BYTE), 
	"CPROVIN" NUMBER, 
	"CSIGREN" VARCHAR2(1 BYTE), 
	"IRENTAS" NUMBER, 
	"CSIGRED" VARCHAR2(1 BYTE), 
	"IREDUC1" NUMBER, 
	"IREDUC2" NUMBER, 
	"CSIGBAS" VARCHAR2(1 BYTE), 
	"IBASE" NUMBER, 
	"PRETENC" NUMBER(4,2), 
	"IRETENC" NUMBER, 
	"CERROR" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."SFISCAB" IS 'Secuencia de la cabecera';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."NANYO" IS 'Año Fiscal YYYYMM';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."CTIPO" IS 'Tipo de Registro VTO,SIN,RPA,RTO,REN,PRE';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."NNIFDEC" IS 'Numero de nif del declarante';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."SPERSONP" IS 'Clave albor personas del perceptor';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."NNIFPER" IS 'Numero de nif del perceptor';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."SPERSONR" IS 'Clave albor personas del representante';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."NNIFREP" IS 'Numero de nif del representante';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."TNOMPER" IS 'Nombre y apellidos del perceptor';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."CPROVIN" IS 'Codigo de Provincia del perceptor';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."CSIGREN" IS 'Signo de Rentas o rendimientos';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."IRENTAS" IS 'Importe de Rentas o Rendimientos';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."CSIGRED" IS 'Signo de las Reducciones';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."IREDUC1" IS 'Importe de la 1ra. Reducción';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."IREDUC2" IS 'Importe de la 2da. Reducción';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."CSIGBAS" IS 'Signo de la Base';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."IBASE" IS 'Importe de la base de Retención';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."PRETENC" IS '% de Retención';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."IRETENC" IS 'Importe de la Retención';
   COMMENT ON COLUMN "AXIS"."FIS_MOD188"."CERROR" IS 'Código de Error, si se ha producido';
   COMMENT ON TABLE "AXIS"."FIS_MOD188"  IS 'Tabla de Modelo 188';
  GRANT DELETE ON "AXIS"."FIS_MOD188" TO "R_AXIS";
  GRANT UPDATE ON "AXIS"."FIS_MOD188" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FIS_MOD188" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."FIS_MOD188" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FIS_MOD188" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."FIS_MOD188" TO "PROGRAMADORESCSI";
