--------------------------------------------------------
--  DDL for Table FORPAGPRO
--------------------------------------------------------

  CREATE TABLE "AXIS"."FORPAGPRO" 
   (	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CFORPAG" NUMBER(2,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."FORPAGPRO"."CRAMO" IS 'Código ramo';
   COMMENT ON COLUMN "AXIS"."FORPAGPRO"."CMODALI" IS 'Código modalidad';
   COMMENT ON COLUMN "AXIS"."FORPAGPRO"."CTIPSEG" IS 'Código tipo de seguro';
   COMMENT ON COLUMN "AXIS"."FORPAGPRO"."CCOLECT" IS 'Código de colectividad';
   COMMENT ON COLUMN "AXIS"."FORPAGPRO"."CFORPAG" IS 'Forma de pago';
   COMMENT ON COLUMN "AXIS"."FORPAGPRO"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."FORPAGPRO"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."FORPAGPRO"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."FORPAGPRO"."FMODIFI" IS 'Fecha en que se modifica el registro';
  GRANT UPDATE ON "AXIS"."FORPAGPRO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FORPAGPRO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."FORPAGPRO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."FORPAGPRO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FORPAGPRO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."FORPAGPRO" TO "PROGRAMADORESCSI";
