--------------------------------------------------------
--  DDL for Table FORPAGRECPROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."FORPAGRECPROD" 
   (	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CFORPAG" NUMBER(2,0), 
	"PRECARG" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."FORPAGRECPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FORPAGRECPROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."FORPAGRECPROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."FORPAGRECPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FORPAGRECPROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."FORPAGRECPROD" TO "PROGRAMADORESCSI";
