--------------------------------------------------------
--  DDL for Table FSTML_DETALLE
--------------------------------------------------------

  CREATE TABLE "AXIS"."FSTML_DETALLE" 
   (	"CFICHERO" NUMBER(5,0), 
	"CCAMPO" NUMBER(5,0), 
	"POS_IN" NUMBER(4,0), 
	"VISIBLE" NUMBER(1,0), 
	"POS_OUT" NUMBER(4,0), 
	"ALIGN" CHAR(1 BYTE), 
	"LONGITUD" NUMBER(2,0), 
	"ETIQUETA" VARCHAR2(20 BYTE), 
	"RUPTURA" NUMBER(1,0), 
	"NUMERICO" NUMBER(1,0), 
	"DIVIDIR" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."FSTML_DETALLE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FSTML_DETALLE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."FSTML_DETALLE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."FSTML_DETALLE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FSTML_DETALLE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."FSTML_DETALLE" TO "PROGRAMADORESCSI";
