--------------------------------------------------------
--  DDL for Table FSTML_FICHERO
--------------------------------------------------------

  CREATE TABLE "AXIS"."FSTML_FICHERO" 
   (	"CFICHERO" NUMBER(5,0), 
	"TFICHERO" VARCHAR2(100 BYTE), 
	"TABREV" VARCHAR2(20 BYTE), 
	"SEPARADOR" CHAR(1 BYTE), 
	"LINXPAG" NUMBER(3,0), 
	"CARXLIN" NUMBER(3,0), 
	"POSCAB" NUMBER(3,0), 
	"FICH_OUT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."FSTML_FICHERO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FSTML_FICHERO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."FSTML_FICHERO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."FSTML_FICHERO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FSTML_FICHERO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."FSTML_FICHERO" TO "PROGRAMADORESCSI";
