--------------------------------------------------------
--  DDL for Table FSTML_CABECERA
--------------------------------------------------------

  CREATE TABLE "AXIS"."FSTML_CABECERA" 
   (	"CFICHERO" NUMBER(5,0), 
	"NORDEN" NUMBER(1,0), 
	"TEXTO" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."FSTML_CABECERA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FSTML_CABECERA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."FSTML_CABECERA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."FSTML_CABECERA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FSTML_CABECERA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."FSTML_CABECERA" TO "PROGRAMADORESCSI";
