--------------------------------------------------------
--  DDL for Table FUSIONBENESPSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."FUSIONBENESPSEG" 
   (	"SSEGUROORI" NUMBER, 
	"NRIESGOORI" NUMBER(6,0), 
	"CGARANTORI" NUMBER(4,0), 
	"NMOVIMIORI" NUMBER(4,0), 
	"SPERSONORI" NUMBER(10,0), 
	"SPERSON_TITORI" NUMBER(10,0), 
	"SPERSONDES" NUMBER(10,0), 
	"SPERSON_TITDES" NUMBER(10,0), 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FMOVIMI" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."FUSIONBENESPSEG"."SSEGUROORI" IS 'Identificador del seguro origen';
   COMMENT ON COLUMN "AXIS"."FUSIONBENESPSEG"."SPERSONORI" IS 'Persona origen';
   COMMENT ON COLUMN "AXIS"."FUSIONBENESPSEG"."SPERSONDES" IS 'Persona des destino';
   COMMENT ON COLUMN "AXIS"."FUSIONBENESPSEG"."CUSUARI" IS 'Código usuario modificación registro';
   COMMENT ON COLUMN "AXIS"."FUSIONBENESPSEG"."FMOVIMI" IS 'Fecha modificación registro';
   COMMENT ON TABLE "AXIS"."FUSIONBENESPSEG"  IS 'Tabla con los benespseg que se han fusionado';
  GRANT UPDATE ON "AXIS"."FUSIONBENESPSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FUSIONBENESPSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."FUSIONBENESPSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."FUSIONBENESPSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."FUSIONBENESPSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."FUSIONBENESPSEG" TO "PROGRAMADORESCSI";
