--------------------------------------------------------
--  DDL for Table GARANPRO_SBPRI
--------------------------------------------------------

  CREATE TABLE "AXIS"."GARANPRO_SBPRI" 
   (	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CACTIVI" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0), 
	"CTIPSPR" NUMBER(2,0), 
	"FINI" DATE, 
	"FFIN" DATE, 
	"CCALSPR" NUMBER(2,0), 
	"NVALOR" NUMBER(8,5), 
	"NCOMISI" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."GARANPRO_SBPRI"."CTIPSPR" IS 'Tipo Sobreprima, valores posibles de la tabla de valores fijos: 838.';
   COMMENT ON COLUMN "AXIS"."GARANPRO_SBPRI"."FINI" IS 'Fecha Inicio Vigéncia';
   COMMENT ON COLUMN "AXIS"."GARANPRO_SBPRI"."FFIN" IS 'Fecha Fin Vigéncia';
   COMMENT ON COLUMN "AXIS"."GARANPRO_SBPRI"."CCALSPR" IS 'Tipo de Cálculo Sobreprima, valores posibles de la tabla valores fijos: 839.';
   COMMENT ON COLUMN "AXIS"."GARANPRO_SBPRI"."NVALOR" IS 'Valor de la sobreprima';
   COMMENT ON COLUMN "AXIS"."GARANPRO_SBPRI"."NCOMISI" IS 'Indicador de si se aplica comisión a esta sobreprima';
   COMMENT ON TABLE "AXIS"."GARANPRO_SBPRI"  IS 'Asignació Sobreprimes a la professió';
  GRANT UPDATE ON "AXIS"."GARANPRO_SBPRI" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."GARANPRO_SBPRI" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."GARANPRO_SBPRI" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."GARANPRO_SBPRI" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."GARANPRO_SBPRI" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."GARANPRO_SBPRI" TO "PROGRAMADORESCSI";
