--------------------------------------------------------
--  DDL for Table GARANPROGAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."GARANPROGAS" 
   (	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CACTIVI" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0), 
	"CGASTO" NUMBER(2,0), 
	"FINI" DATE, 
	"FFIN" DATE, 
	"PMIN" NUMBER(5,2), 
	"PMAX" NUMBER(5,2), 
	"PVALOR" NUMBER(5,2), 
	"NPRIMA" NUMBER(2,0), 
	"NMOD" NUMBER(2,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIF" DATE, 
	"PMINRES" NUMBER(5,2), 
	"PMAXRES" NUMBER(5,2), 
	"PVALRES" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."GARANPROGAS"."FINI" IS 'Fecha Inicio Vigencia';
   COMMENT ON COLUMN "AXIS"."GARANPROGAS"."FFIN" IS 'Fecha Fin Vigencia';
   COMMENT ON COLUMN "AXIS"."GARANPROGAS"."PMIN" IS 'Porcentaje Mínimo';
   COMMENT ON COLUMN "AXIS"."GARANPROGAS"."PMAX" IS 'Porcentaje Máximo';
   COMMENT ON COLUMN "AXIS"."GARANPROGAS"."PVALOR" IS 'Porcentaje por Defecto';
   COMMENT ON COLUMN "AXIS"."GARANPROGAS"."NPRIMA" IS 'Indicador de sobre que valor se aplica al porcentaje de gastos. Valores Fijos=837';
   COMMENT ON COLUMN "AXIS"."GARANPROGAS"."NMOD" IS 'Indicador de si se puede modificar en producción. Valores Fijos=307';
   COMMENT ON COLUMN "AXIS"."GARANPROGAS"."CUSUALT" IS 'Código Usuario de alta del registro';
   COMMENT ON COLUMN "AXIS"."GARANPROGAS"."FALTA" IS 'Fecha de Alta';
   COMMENT ON COLUMN "AXIS"."GARANPROGAS"."CUSUMOD" IS 'Código usuario que modifica el registro';
   COMMENT ON COLUMN "AXIS"."GARANPROGAS"."FMODIF" IS 'Fecha de Modificación';
   COMMENT ON COLUMN "AXIS"."GARANPROGAS"."PMINRES" IS 'Resto Anualidades Mínimas';
   COMMENT ON COLUMN "AXIS"."GARANPROGAS"."PMAXRES" IS 'Resto Anualidades Máximas';
   COMMENT ON COLUMN "AXIS"."GARANPROGAS"."PVALRES" IS 'Resto Anualidades Por Defecto';
   COMMENT ON TABLE "AXIS"."GARANPROGAS"  IS 'Asignación Gastos';
  GRANT UPDATE ON "AXIS"."GARANPROGAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."GARANPROGAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."GARANPROGAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."GARANPROGAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."GARANPROGAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."GARANPROGAS" TO "PROGRAMADORESCSI";
