--------------------------------------------------------
--  DDL for Table GARANGEN
--------------------------------------------------------

  CREATE TABLE "AXIS"."GARANGEN" 
   (	"CIDIOMA" NUMBER(2,0), 
	"CGARANT" NUMBER(4,0), 
	"TGARANT" VARCHAR2(120 BYTE), 
	"TROTGAR" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."GARANGEN"."CIDIOMA" IS 'Código de Idioma';
   COMMENT ON COLUMN "AXIS"."GARANGEN"."CGARANT" IS 'Código de garantía';
   COMMENT ON COLUMN "AXIS"."GARANGEN"."TGARANT" IS 'Descripción de garantía';
   COMMENT ON COLUMN "AXIS"."GARANGEN"."TROTGAR" IS 'Rótulo de garantía';
  GRANT UPDATE ON "AXIS"."GARANGEN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."GARANGEN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."GARANGEN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."GARANGEN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."GARANGEN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."GARANGEN" TO "PROGRAMADORESCSI";
