--------------------------------------------------------
--  DDL for Table GEST_LIQUIDALIN
--------------------------------------------------------

  CREATE TABLE "AXIS"."GEST_LIQUIDALIN" 
   (	"SLIQUIDA" NUMBER, 
	"COUTSOUR" NUMBER(3,0), 
	"NRECIBO" NUMBER, 
	"IMPORTE" NUMBER DEFAULT 0, 
	"IVA" NUMBER DEFAULT 0, 
	"RETEIVA" NUMBER DEFAULT 0, 
	"RTEFTE" NUMBER DEFAULT 0, 
	"ICA" NUMBER DEFAULT 0, 
	"TOTALIMP" NUMBER DEFAULT 0, 
	"FALTA" DATE, 
	"CUSER" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."GEST_LIQUIDALIN"."SLIQUIDA" IS 'N¿mero de liquidaci¿n';
   COMMENT ON COLUMN "AXIS"."GEST_LIQUIDALIN"."COUTSOUR" IS 'C¿digo de outsourcing';
   COMMENT ON COLUMN "AXIS"."GEST_LIQUIDALIN"."NRECIBO" IS 'N¿mero de recibo.';
   COMMENT ON COLUMN "AXIS"."GEST_LIQUIDALIN"."IMPORTE" IS 'Importe liquidado';
   COMMENT ON COLUMN "AXIS"."GEST_LIQUIDALIN"."IVA" IS 'Impuestos';
   COMMENT ON COLUMN "AXIS"."GEST_LIQUIDALIN"."RETEIVA" IS 'ReteIVA';
   COMMENT ON COLUMN "AXIS"."GEST_LIQUIDALIN"."RTEFTE" IS 'Retefuente';
   COMMENT ON COLUMN "AXIS"."GEST_LIQUIDALIN"."ICA" IS 'Retenci¿n ICA';
   COMMENT ON COLUMN "AXIS"."GEST_LIQUIDALIN"."TOTALIMP" IS 'Total importe';
   COMMENT ON COLUMN "AXIS"."GEST_LIQUIDALIN"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."GEST_LIQUIDALIN"."CUSER" IS 'Usuario';
   COMMENT ON TABLE "AXIS"."GEST_LIQUIDALIN"  IS 'Detalle de liquidaciones de gestores de OUTSOURCING';
  GRANT UPDATE ON "AXIS"."GEST_LIQUIDALIN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."GEST_LIQUIDALIN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."GEST_LIQUIDALIN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."GEST_LIQUIDALIN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."GEST_LIQUIDALIN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."GEST_LIQUIDALIN" TO "PROGRAMADORESCSI";
