--------------------------------------------------------
--  DDL for Table GFI_FUNCIONES
--------------------------------------------------------

  CREATE TABLE "AXIS"."GFI_FUNCIONES" 
   (	"CFORMULA" VARCHAR2(30 BYTE), 
	"CCLAVE" NUMBER(6,0), 
	"TPROCESO" VARCHAR2(200 BYTE), 
	"REFRESCA" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."GFI_FUNCIONES"."CFORMULA" IS 'Código de la fórmula';
   COMMENT ON COLUMN "AXIS"."GFI_FUNCIONES"."CCLAVE" IS 'Clave de la fórmula';
   COMMENT ON COLUMN "AXIS"."GFI_FUNCIONES"."TPROCESO" IS 'Proceso que utiliza esta fórmula';
   COMMENT ON COLUMN "AXIS"."GFI_FUNCIONES"."REFRESCA" IS 'Indica que la fórmula se tendría que refrescar';
  GRANT UPDATE ON "AXIS"."GFI_FUNCIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."GFI_FUNCIONES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."GFI_FUNCIONES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."GFI_FUNCIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."GFI_FUNCIONES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."GFI_FUNCIONES" TO "PROGRAMADORESCSI";
