--------------------------------------------------------
--  DDL for Table HIR_INSPECCIONES_DOC
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIR_INSPECCIONES_DOC" 
   (	"CEMPRES" NUMBER(5,0), 
	"SORDEN" NUMBER, 
	"NINSPECCION" NUMBER, 
	"NDOCUME" NUMBER(6,0), 
	"CDOCUME" NUMBER(6,0), 
	"CGENERADO" NUMBER(1,0), 
	"COBLIGA" NUMBER(1,0), 
	"CADJUNTADO" NUMBER(1,0), 
	"IDDOCGEDOX" NUMBER(10,0), 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE), 
	"FHIST" DATE, 
	"CUSUHIST" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."CEMPRES" IS 'Código de empresa';
   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."SORDEN" IS 'Número consecutivo de orden de inspección asignado automáticamente';
   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."NINSPECCION" IS 'Número consecutivo de inspección, para cada orden de inspección';
   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."NDOCUME" IS 'Número secuencial de documento';
   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."CDOCUME" IS 'Código de documento';
   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."CGENERADO" IS 'Indica si se ha generado por la aplicación o no (1-0)';
   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."COBLIGA" IS 'Indica si es obligatorio o no (1-0)';
   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."CADJUNTADO" IS 'Indica si se ha adjuntado o no (1-0)';
   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."IDDOCGEDOX" IS 'Identificador del documento GEDOX';
   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."FMODIFI" IS 'Fecha de modificacion';
   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."CUSUMOD" IS 'Usuario de modificacion';
   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."FHIST" IS 'Fecha de paso a histórico';
   COMMENT ON COLUMN "AXIS"."HIR_INSPECCIONES_DOC"."CUSUHIST" IS 'Usuario de paso a histórico';
   COMMENT ON TABLE "AXIS"."HIR_INSPECCIONES_DOC"  IS 'Tabla de documentos de la inspección';
  GRANT UPDATE ON "AXIS"."HIR_INSPECCIONES_DOC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIR_INSPECCIONES_DOC" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIR_INSPECCIONES_DOC" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIR_INSPECCIONES_DOC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIR_INSPECCIONES_DOC" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIR_INSPECCIONES_DOC" TO "PROGRAMADORESCSI";
