--------------------------------------------------------
--  DDL for Table HIS_AUT_USOSUBUSO_PROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_AUT_USOSUBUSO_PROD" 
   (	"CCLAVEH" VARCHAR2(5 BYTE), 
	"CTIPVEH" VARCHAR2(3 BYTE), 
	"CUSO" VARCHAR2(2 BYTE), 
	"CSUBUSO" VARCHAR2(2 BYTE), 
	"SPRODUC" NUMBER(22,0), 
	"CACTIVI" NUMBER(22,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"FBAJA" DATE, 
	"CEMPRES" NUMBER(22,0), 
	"CRETEN" NUMBER(22,0), 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."CCLAVEH" IS 'Código de la clase';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."CTIPVEH" IS 'Código del tipo de vehículo';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."CUSO" IS 'Código del uso';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."CSUBUSO" IS 'Código del sub-uso';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."SPRODUC" IS 'Código del producto';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."CACTIVI" IS 'Código de la actividad';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."CUSUALT" IS 'Usuario que da de alta el registro';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."FALTA" IS 'Fecha de alta del registro';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."CUSUMOD" IS 'Usuario de la última modificación del registro';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."FMODIFI" IS 'Fecha de la última modificación del registro';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."FBAJA" IS 'Fecha de baja del registro';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."CEMPRES" IS 'Codigo de empresa';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."CRETEN" IS 'Indica si se retiene la póliza al emitir (v.f. 8000915)';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_AUT_USOSUBUSO_PROD"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_AUT_USOSUBUSO_PROD"  IS 'Histórico de la tabla AUT_USOSUBUSO_PROD';
  GRANT UPDATE ON "AXIS"."HIS_AUT_USOSUBUSO_PROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_AUT_USOSUBUSO_PROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_AUT_USOSUBUSO_PROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_AUT_USOSUBUSO_PROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_AUT_USOSUBUSO_PROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_AUT_USOSUBUSO_PROD" TO "PROGRAMADORESCSI";
