--------------------------------------------------------
--  DDL for Table HIS_PDS_SUPL_CONFIG
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_PDS_SUPL_CONFIG" 
   (	"CCONFIG" VARCHAR2(50 BYTE), 
	"CMOTMOV" NUMBER(22,0), 
	"SPRODUC" NUMBER(22,0), 
	"CMODO" VARCHAR2(50 BYTE), 
	"CTIPFEC" NUMBER(22,0), 
	"TFECREC" VARCHAR2(100 BYTE), 
	"SUPLCOLEC" NUMBER(22,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_CONFIG"."CCONFIG" IS 'Id. de la configuració del suplement';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_CONFIG"."CMOTMOV" IS 'Motivo del suplemento';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_CONFIG"."SPRODUC" IS 'Id. del producto';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_CONFIG"."CMODO" IS 'Modo de ejecución';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_CONFIG"."CTIPFEC" IS '0 No importa fecha o no hay, 1-debe ser una concreta';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_CONFIG"."TFECREC" IS 'función que nos devuelve la fecha del recibo para el supl.';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_CONFIG"."SUPLCOLEC" IS 'Suplemento colec (v.f. 8000918)';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_CONFIG"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_CONFIG"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_CONFIG"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_CONFIG"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_CONFIG"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_CONFIG"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_CONFIG"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_PDS_SUPL_CONFIG"  IS 'Histórico de la tabla PDS_SUPL_CONFIG';
  GRANT UPDATE ON "AXIS"."HIS_PDS_SUPL_CONFIG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PDS_SUPL_CONFIG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_PDS_SUPL_CONFIG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_PDS_SUPL_CONFIG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PDS_SUPL_CONFIG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_PDS_SUPL_CONFIG" TO "PROGRAMADORESCSI";
