--------------------------------------------------------
--  DDL for Table HIS_PDS_DESHABILITAR
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_PDS_DESHABILITAR" 
   (	"CMOTMOV" NUMBER(22,0), 
	"SPRODUC" NUMBER(22,0), 
	"TFORM" VARCHAR2(30 BYTE), 
	"CCAMPDES" VARCHAR2(50 BYTE), 
	"CCAMPVAL" VARCHAR2(50 BYTE), 
	"TTABLVAL" VARCHAR2(50 BYTE), 
	"VALOR" VARCHAR2(2000 BYTE), 
	"CMODO" VARCHAR2(20 BYTE), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."CMOTMOV" IS 'Motivo de suplemento';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."SPRODUC" IS 'Id. del producto';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."TFORM" IS 'Form a que afecta de suplemento';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."CCAMPDES" IS 'Campo a deshabilitar';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."CCAMPVAL" IS 'Campo a consultar valor';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."TTABLVAL" IS 'Tabla del campo a consultar (seguros, riesgos...)';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."VALOR" IS 'Valor que tiene que tener el campo para deshabilitar';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."CMODO" IS 'Modo: SUPLEMENTO, SUPL_CENTRAL,....';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_DESHABILITAR"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_PDS_DESHABILITAR"  IS 'Histórico de la tabla PDS_DESHABILITAR';
  GRANT UPDATE ON "AXIS"."HIS_PDS_DESHABILITAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PDS_DESHABILITAR" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_PDS_DESHABILITAR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_PDS_DESHABILITAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PDS_DESHABILITAR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_PDS_DESHABILITAR" TO "PROGRAMADORESCSI";
