--------------------------------------------------------
--  DDL for Table HIS_EDADMARPROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_EDADMARPROD" 
   (	"SPRODUC" NUMBER(22,0), 
	"NEDAMAR" NUMBER(22,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_EDADMARPROD"."SPRODUC" IS 'Secuencia del producto';
   COMMENT ON COLUMN "AXIS"."HIS_EDADMARPROD"."NEDAMAR" IS 'Edad Máx. de renovación';
   COMMENT ON COLUMN "AXIS"."HIS_EDADMARPROD"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_EDADMARPROD"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_EDADMARPROD"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_EDADMARPROD"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_EDADMARPROD"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_EDADMARPROD"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_EDADMARPROD"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_EDADMARPROD"  IS 'Histórico de la tabla EDADMARPROD';
  GRANT UPDATE ON "AXIS"."HIS_EDADMARPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_EDADMARPROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_EDADMARPROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_EDADMARPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_EDADMARPROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_EDADMARPROD" TO "PROGRAMADORESCSI";
