--------------------------------------------------------
--  DDL for Table HIS_PRODCARTERA
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_PRODCARTERA" 
   (	"CEMPRES" NUMBER(22,0), 
	"SPRODUC" NUMBER(22,0), 
	"FCARANT" DATE, 
	"FCARPRO" DATE, 
	"CRAMO" NUMBER(22,0), 
	"CMODALI" NUMBER(22,0), 
	"CTIPSEG" NUMBER(22,0), 
	"CCOLECT" NUMBER(22,0), 
	"FGENREN" DATE, 
	"AUTMANUAL" VARCHAR2(1 BYTE), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."CEMPRES" IS 'Clave Empresa';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."SPRODUC" IS 'Clave Producto';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."FCARANT" IS 'Fecha anterior Cartera del producto';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."FCARPRO" IS 'Fecha proxima Cartera del producto';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."CRAMO" IS 'Código de ramo';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."CMODALI" IS 'Código de modalidad';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."CTIPSEG" IS 'Código de tipo seguro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."CCOLECT" IS 'Código de colectividad';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."FGENREN" IS 'Fecha de próxima generación de rentas';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."AUTMANUAL" IS 'Cartera Automática/Manual';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCARTERA"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_PRODCARTERA"  IS 'Histórico de la tabla PRODCARTERA';
  GRANT UPDATE ON "AXIS"."HIS_PRODCARTERA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PRODCARTERA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_PRODCARTERA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_PRODCARTERA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PRODCARTERA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_PRODCARTERA" TO "PROGRAMADORESCSI";
