--------------------------------------------------------
--  DDL for Table HIS_RECIBOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_RECIBOS" 
   (	"NRECIBO" NUMBER, 
	"CAGENTE" NUMBER, 
	"CEMPRES" NUMBER(2,0), 
	"NMOVIMI" NUMBER(4,0), 
	"SSEGURO" NUMBER, 
	"FEMISIO" DATE, 
	"FEFECTO" DATE, 
	"FVENCIM" DATE, 
	"CTIPREC" NUMBER(2,0), 
	"CDELEGA" NUMBER, 
	"CCOBBAN" NUMBER(3,0), 
	"CESTAUX" NUMBER(2,0), 
	"NANUALI" NUMBER(2,0), 
	"NFRACCI" NUMBER(2,0), 
	"CESTIMP" NUMBER(2,0), 
	"NRIESGO" NUMBER(6,0), 
	"CFORPAG" NUMBER(2,0), 
	"CBANCAR" VARCHAR2(50 BYTE), 
	"NMOVANU" NUMBER(4,0), 
	"CRETENC" NUMBER(2,0), 
	"PRETENC" NUMBER(5,2), 
	"NCUACOA" NUMBER, 
	"CTIPCOA" NUMBER(1,0), 
	"CESTSOP" NUMBER(1,0), 
	"CMANUAL" NUMBER(1,0), 
	"NPERVEN" NUMBER(6,0), 
	"CTRANSF" VARCHAR2(1 BYTE) DEFAULT 0, 
	"CGESCOB" NUMBER(1,0), 
	"CTIPBAN" NUMBER(3,0), 
	"FESTIMP" DATE, 
	"ESCCERO" NUMBER(1,0), 
	"CTIPCOB" NUMBER(3,0), 
	"CRECCIA" VARCHAR2(50 BYTE), 
	"CVALIDADO" NUMBER(1,0), 
	"SHISREC" NUMBER(9,0), 
	"FHIST" DATE, 
	"CUSUHIST" VARCHAR2(60 BYTE), 
	"NCUOTAR" NUMBER(3,0), 
	"CGESCAR" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."NRECIBO" IS 'Número de recibo.';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CEMPRES" IS 'Código de Empresa';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente.';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."FEMISIO" IS 'Fecha de emisión del ecibo';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."FEFECTO" IS 'Fecha de efecto del recibo.';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."FVENCIM" IS 'Fecha de vencimiento del recibo.';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CTIPREC" IS 'Tipo de recibo';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CDELEGA" IS 'Delegación asociada';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CCOBBAN" IS 'Código de cobrador bancario';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CESTAUX" IS 'Código subestado recibo';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."NANUALI" IS 'Número de anualidad.';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."NFRACCI" IS 'Número de fracción en la anualidad.';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CESTIMP" IS 'Estado impresión del recibo';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."NRIESGO" IS 'Número de riesgo si sólo afecta a uno';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CFORPAG" IS 'Forma de pago';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CBANCAR" IS 'Codi bancari';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CTIPBAN" IS 'Tipo de cuenta ( iban o cuenta bancaria). [tabla maestra: TIPOS_CUENTA]';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."FESTIMP" IS 'Fecha estado impresión.';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."ESCCERO" IS 'Indica si el Recibo es Cero.';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CTIPCOB" IS 'Tipo de Cobrador del recibo';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CRECCIA" IS 'Compañia del recibo';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CVALIDADO" IS 'Indica si el Recibo esta validado 1-Si/0-No';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."SHISREC" IS 'Código de la secuencia del recibo';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."FHIST" IS 'Fecha en la que se ha pasado al histórico.';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CUSUHIST" IS 'Usuario que lo ha pasado al histórico';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."NCUOTAR" IS 'Número cuotas de tarjeta';
   COMMENT ON COLUMN "AXIS"."HIS_RECIBOS"."CGESCAR" IS 'Indica si la gesti¿n de cartera se realiz¿ por OUTSOURCING (2) o DIRECTA(1) (8001111)';
  GRANT UPDATE ON "AXIS"."HIS_RECIBOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_RECIBOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_RECIBOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_RECIBOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_RECIBOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_RECIBOS" TO "PROGRAMADORESCSI";
