--------------------------------------------------------
--  DDL for Table HIS_DETCARENCIAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_DETCARENCIAS" 
   (	"CSEXO" NUMBER(22,0), 
	"NMESCAR" NUMBER(22,0), 
	"CGARANT" NUMBER(22,0), 
	"CCAREN" NUMBER(22,0), 
	"SPRODUC" NUMBER(22,0), 
	"CACTIVI" NUMBER(22,0), 
	"CRAMO" NUMBER(22,0), 
	"CMODALI" NUMBER(22,0), 
	"CTIPSEG" NUMBER(22,0), 
	"CCOLECT" NUMBER(22,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."CSEXO" IS 'A que sexo afecta la carencia 1-hombre 2-mujer Nulo-Los dos ( CVALOR: 216 )';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."NMESCAR" IS 'Meses de carencia';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."CGARANT" IS 'Garantia que afeca la carencia';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."CCAREN" IS 'Código de carencia';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."SPRODUC" IS 'Producto';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."CACTIVI" IS 'Actividad';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."CRAMO" IS 'Ramo';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."CMODALI" IS 'Modalidad';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."CTIPSEG" IS 'Tipo de seguridad';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."CCOLECT" IS 'Colectivo';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_DETCARENCIAS"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_DETCARENCIAS"  IS 'Histórico de la tabla DETCARENCIAS';
  GRANT UPDATE ON "AXIS"."HIS_DETCARENCIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_DETCARENCIAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_DETCARENCIAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_DETCARENCIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_DETCARENCIAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_DETCARENCIAS" TO "PROGRAMADORESCSI";
