--------------------------------------------------------
--  DDL for Table HIS_MODINVFONDO
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_MODINVFONDO" 
   (	"CCODFON" NUMBER(22,0), 
	"PINVERS" NUMBER(22,0), 
	"CRAMO" NUMBER(22,0), 
	"CMODALI" NUMBER(22,0), 
	"CTIPSEG" NUMBER(22,0), 
	"CCOLECT" NUMBER(22,0), 
	"CMODINV" NUMBER(22,0), 
	"PMAXCONT" NUMBER(22,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_MODINVFONDO"."CCODFON" IS 'Código del fondo';
   COMMENT ON COLUMN "AXIS"."HIS_MODINVFONDO"."PINVERS" IS '% del fondo en el modelo de inversión';
   COMMENT ON COLUMN "AXIS"."HIS_MODINVFONDO"."CMODINV" IS 'Código de modelo de inversión';
   COMMENT ON COLUMN "AXIS"."HIS_MODINVFONDO"."PMAXCONT" IS 'Porcentaje máximo contratable de un fondo para el modelo de inversión.';
   COMMENT ON COLUMN "AXIS"."HIS_MODINVFONDO"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_MODINVFONDO"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_MODINVFONDO"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_MODINVFONDO"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_MODINVFONDO"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_MODINVFONDO"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_MODINVFONDO"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_MODINVFONDO"  IS 'Histórico de la tabla MODINVFONDO';
  GRANT UPDATE ON "AXIS"."HIS_MODINVFONDO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_MODINVFONDO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_MODINVFONDO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_MODINVFONDO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_MODINVFONDO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_MODINVFONDO" TO "PROGRAMADORESCSI";
