--------------------------------------------------------
--  DDL for Table HIS_CONTABLE
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_CONTABLE" 
   (	"CEMPRES" NUMBER(2,0), 
	"FCONTA" DATE, 
	"CCUENTA" VARCHAR2(50 BYTE), 
	"TDESCRI" VARCHAR2(100 BYTE), 
	"DEBE" NUMBER, 
	"HABER" NUMBER, 
	"CPAIS" NUMBER(3,0), 
	"OTROS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_CONTABLE"."CEMPRES" IS 'Código de Empresa';
   COMMENT ON COLUMN "AXIS"."HIS_CONTABLE"."FCONTA" IS 'Fecha en la que se envia a contabilidad';
   COMMENT ON COLUMN "AXIS"."HIS_CONTABLE"."CCUENTA" IS 'Código de cuenta';
   COMMENT ON COLUMN "AXIS"."HIS_CONTABLE"."TDESCRI" IS 'Descripción de la cuenta';
   COMMENT ON COLUMN "AXIS"."HIS_CONTABLE"."DEBE" IS 'Importe en el Debe';
   COMMENT ON COLUMN "AXIS"."HIS_CONTABLE"."HABER" IS 'Importe en el Haber';
   COMMENT ON COLUMN "AXIS"."HIS_CONTABLE"."CPAIS" IS 'Pais de residencia';
   COMMENT ON COLUMN "AXIS"."HIS_CONTABLE"."OTROS" IS 'Contenido de variable específica para cada cuenta';
  GRANT UPDATE ON "AXIS"."HIS_CONTABLE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_CONTABLE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_CONTABLE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_CONTABLE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_CONTABLE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_CONTABLE" TO "PROGRAMADORESCSI";
