--------------------------------------------------------
--  DDL for Table HIS_MENU_USERCODIROL
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_MENU_USERCODIROL" 
   (	"CUSER" VARCHAR2(50 BYTE), 
	"CROLMEN" VARCHAR2(20 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_MENU_USERCODIROL"."CUSER" IS 'Usuario';
   COMMENT ON COLUMN "AXIS"."HIS_MENU_USERCODIROL"."CROLMEN" IS 'Rol de menú';
   COMMENT ON COLUMN "AXIS"."HIS_MENU_USERCODIROL"."CUSUALT" IS 'USUARIO QUE DA DE ALTA EL REGISTRO';
   COMMENT ON COLUMN "AXIS"."HIS_MENU_USERCODIROL"."FALTA" IS 'FECHA DE ALTA DEL REGISTRO';
   COMMENT ON COLUMN "AXIS"."HIS_MENU_USERCODIROL"."CUSUMOD" IS 'USUARIO QUE MODIFICA EL REGISTRO';
   COMMENT ON COLUMN "AXIS"."HIS_MENU_USERCODIROL"."FMODIFI" IS 'FECHA DE MOFICIACIÓN DEL REGISTRO';
   COMMENT ON TABLE "AXIS"."HIS_MENU_USERCODIROL"  IS 'Roles de menu por usuario';
  GRANT UPDATE ON "AXIS"."HIS_MENU_USERCODIROL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_MENU_USERCODIROL" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_MENU_USERCODIROL" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_MENU_USERCODIROL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_MENU_USERCODIROL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_MENU_USERCODIROL" TO "PROGRAMADORESCSI";
