--------------------------------------------------------
--  DDL for Table HIS_COMISIONPROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_COMISIONPROD" 
   (	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CCOMISI" NUMBER, 
	"CMODCOM" NUMBER(1,0), 
	"PCOMISI" NUMBER(5,2), 
	"SPRODUC" NUMBER(6,0), 
	"FINIVIG" DATE DEFAULT TO_DATE('01/01/1900','dd/mm/yyyy'), 
	"FALTA" DATE, 
	"CUSUALTA" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"NINIALT" NUMBER, 
	"NFINALT" NUMBER, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."CRAMO" IS 'Código ramo';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."CMODALI" IS 'Código modalidad';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."CTIPSEG" IS 'Código tipo de seguro';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."CCOLECT" IS 'Código de colectividad';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."CCOMISI" IS 'Código comisión';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."CMODCOM" IS 'Modalidad de comisión';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."PCOMISI" IS 'Porcentaje de comisión';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."SPRODUC" IS 'Codi producte';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."FINIVIG" IS 'Fecha inicio vigencia comisión';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."FALTA" IS 'Fecha alta comisión';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."CUSUALTA" IS 'Codigo usuario alta comisión';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."FMODIFI" IS 'Fecha modificación comision';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."CUSUMOD" IS 'Código usuario modificación comisión';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."NINIALT" IS 'Inicio de la altura';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."NFINALT" IS 'Fin de la altura';
   COMMENT ON COLUMN "AXIS"."HIS_COMISIONPROD"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_COMISIONPROD"  IS 'Historico de comisiones produccion';
  GRANT SELECT ON "AXIS"."HIS_COMISIONPROD" TO "PROGRAMADORESCSI";
  GRANT UPDATE ON "AXIS"."HIS_COMISIONPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_COMISIONPROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_COMISIONPROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_COMISIONPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_COMISIONPROD" TO "CONF_DWH";
