--------------------------------------------------------
--  DDL for Table HIS_PROD_PLANT_CAB
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_PROD_PLANT_CAB" 
   (	"SPRODUC" NUMBER(22,0), 
	"CTIPO" NUMBER(22,0), 
	"CCODPLAN" VARCHAR2(20 BYTE), 
	"IMP_DEST" NUMBER(22,0), 
	"FDESDE" DATE, 
	"FHASTA" DATE, 
	"CGARANT" NUMBER(22,0), 
	"CDUPLICA" NUMBER(22,0), 
	"NORDEN" NUMBER(22,0), 
	"CLAVE" NUMBER(22,0), 
	"NRESPUE" NUMBER(22,0), 
	"TCOPIAS" VARCHAR2(250 BYTE), 
	"CCATEGORIA" NUMBER(22,0), 
	"CDIFERIDO" NUMBER(22,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."SPRODUC" IS 'CLAVE DEL PRODUCTO';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."CTIPO" IS 'Tipo de impresion VF 317';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."CCODPLAN" IS 'CODIGO DE PLANTILLA';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."IMP_DEST" IS 'DESTINO IMPRESION (1=PANTALLA, 2=IMPRESORA)';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."FDESDE" IS 'FECHA A PARTIR DE LA CUAL LA PLANTILLA TIENE VIGENCIA';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."FHASTA" IS 'FECHA HASTA LA CUAL LA PLANTILLA TIENE VIGENCIA';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."CGARANT" IS 'Identificador de garantias';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."CDUPLICA" IS '1 .- imprimir en duplicado, 2.- imprimir dupl. recibo';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."NORDEN" IS 'Orden de impresion';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."CLAVE" IS 'Código de clave';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."NRESPUE" IS 'Numero de Respuesta';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."TCOPIAS" IS 'Número de copias a generar para una plantilla';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."CCATEGORIA" IS 'Categoría de la impresión';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."CDIFERIDO" IS 'Tipo del documento diferido (VF:1131)';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PROD_PLANT_CAB"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_PROD_PLANT_CAB"  IS 'Histórico de la tabla PROD_PLANT_CAB';
  GRANT UPDATE ON "AXIS"."HIS_PROD_PLANT_CAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PROD_PLANT_CAB" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_PROD_PLANT_CAB" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_PROD_PLANT_CAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PROD_PLANT_CAB" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_PROD_PLANT_CAB" TO "PROGRAMADORESCSI";
