--------------------------------------------------------
--  DDL for Table HIS_PRODCAUMOTSIN
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_PRODCAUMOTSIN" 
   (	"SPRCAMOSIN" NUMBER(22,0), 
	"CRAMO" NUMBER(22,0), 
	"CMODALI" NUMBER(22,0), 
	"CTIPSEG" NUMBER(22,0), 
	"CCOLECT" NUMBER(22,0), 
	"CACTIVI" NUMBER(22,0), 
	"CGARANT" NUMBER(22,0), 
	"CCAUSIN" NUMBER(22,0), 
	"CMOTSIN" NUMBER(22,0), 
	"CMOVIMI" NUMBER(22,0), 
	"CMOTMOV" NUMBER(22,0), 
	"SPRODUC" NUMBER(22,0), 
	"CMOTFIN" NUMBER(22,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."SPRCAMOSIN" IS 'Secuencia clave del registro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."CACTIVI" IS 'Código actividad del seguro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."CGARANT" IS 'Codigo de Garantia';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."CCAUSIN" IS 'Causa Siniestro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."CMOTSIN" IS 'Motivo del Siniestro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."CMOVIMI" IS 'Cod. Movto en Ctaseguro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."CMOTMOV" IS 'Motivo en Movseguro al abrir el siniestro.';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."CMOTFIN" IS 'Motivo en Movseguro al finalizar el siniestro.';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PRODCAUMOTSIN"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_PRODCAUMOTSIN"  IS 'Histórico de la tabla PRODCAUMOTSIN';
  GRANT UPDATE ON "AXIS"."HIS_PRODCAUMOTSIN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PRODCAUMOTSIN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_PRODCAUMOTSIN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_PRODCAUMOTSIN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PRODCAUMOTSIN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_PRODCAUMOTSIN" TO "PROGRAMADORESCSI";
