--------------------------------------------------------
--  DDL for Table HIS_GARANPROCAP
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_GARANPROCAP" 
   (	"CRAMO" NUMBER(22,0), 
	"CMODALI" NUMBER(22,0), 
	"CTIPSEG" NUMBER(22,0), 
	"CCOLECT" NUMBER(22,0), 
	"CGARANT" NUMBER(22,0), 
	"CACTIVI" NUMBER(22,0), 
	"NORDEN" NUMBER(22,0), 
	"ICAPITAL" NUMBER(22,0), 
	"CDEFECTO" NUMBER(22,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."CRAMO" IS 'Código ramo';
   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."CMODALI" IS 'Código modalidad';
   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."CCOLECT" IS 'Código de colectividad';
   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."CGARANT" IS 'Código de garantía';
   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."CACTIVI" IS 'Codigo de actividad';
   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."NORDEN" IS 'Número de orden';
   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."ICAPITAL" IS 'Importe del Capital';
   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."CDEFECTO" IS 'Indicador de Valor por Defecto: 1=Si, 0=No';
   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_GARANPROCAP"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_GARANPROCAP"  IS 'Histórico de la tabla GARANPROCAP';
  GRANT UPDATE ON "AXIS"."HIS_GARANPROCAP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_GARANPROCAP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_GARANPROCAP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_GARANPROCAP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_GARANPROCAP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_GARANPROCAP" TO "PROGRAMADORESCSI";
