--------------------------------------------------------
--  DDL for Table HIS_PDS_SUPL_AUTOMATIC
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_PDS_SUPL_AUTOMATIC" 
   (	"CMOTMOV" NUMBER(22,0), 
	"SPRODUC" NUMBER(22,0), 
	"NORDEN" NUMBER(22,0), 
	"FVALFUN" VARCHAR2(2000 BYTE), 
	"NORDENSUP" NUMBER(22,0), 
	"SDESCRIP" NUMBER(22,0), 
	"CBLOQUEA" NUMBER(22,0), 
	"CEMITE" NUMBER(22,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_AUTOMATIC"."CMOTMOV" IS 'Código de movimiento';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_AUTOMATIC"."SPRODUC" IS 'Identificador de producto';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_AUTOMATIC"."NORDEN" IS 'Orden de suplemento automático';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_AUTOMATIC"."FVALFUN" IS 'Función de validación a cierto de realización del suplemento';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_AUTOMATIC"."NORDENSUP" IS 'Orden de lanzamiento de suplementos para un mismo producto';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_AUTOMATIC"."CBLOQUEA" IS 'Se bloquea la cartera de la póliza (0.No;1.Sí)';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_AUTOMATIC"."CEMITE" IS 'Se emite la póliza (0.No;1.Sí)';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_AUTOMATIC"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_AUTOMATIC"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_AUTOMATIC"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_AUTOMATIC"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_AUTOMATIC"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_AUTOMATIC"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPL_AUTOMATIC"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_PDS_SUPL_AUTOMATIC"  IS 'Histórico de la tabla PDS_SUPL_AUTOMATIC';
  GRANT UPDATE ON "AXIS"."HIS_PDS_SUPL_AUTOMATIC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PDS_SUPL_AUTOMATIC" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_PDS_SUPL_AUTOMATIC" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_PDS_SUPL_AUTOMATIC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PDS_SUPL_AUTOMATIC" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_PDS_SUPL_AUTOMATIC" TO "PROGRAMADORESCSI";
