--------------------------------------------------------
--  DDL for Table HIS_SIN_CONPAG_PROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_SIN_CONPAG_PROD" 
   (	"CCONPAG" NUMBER(22,0), 
	"SPRODUC" NUMBER(22,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_SIN_CONPAG_PROD"."CCONPAG" IS 'Concepto de pago. VF 803 ';
   COMMENT ON COLUMN "AXIS"."HIS_SIN_CONPAG_PROD"."SPRODUC" IS 'Clave de productos';
   COMMENT ON COLUMN "AXIS"."HIS_SIN_CONPAG_PROD"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_SIN_CONPAG_PROD"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_SIN_CONPAG_PROD"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_SIN_CONPAG_PROD"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_SIN_CONPAG_PROD"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_SIN_CONPAG_PROD"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_SIN_CONPAG_PROD"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_SIN_CONPAG_PROD"  IS 'Histórico de la tabla SIN_CONPAG_PROD';
  GRANT UPDATE ON "AXIS"."HIS_SIN_CONPAG_PROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_SIN_CONPAG_PROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_SIN_CONPAG_PROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_SIN_CONPAG_PROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_SIN_CONPAG_PROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_SIN_CONPAG_PROD" TO "PROGRAMADORESCSI";
