--------------------------------------------------------
--  DDL for Table HIS_ULPREDE
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_ULPREDE" 
   (	"CRAMO" NUMBER(22,0), 
	"CMODALI" NUMBER(22,0), 
	"CTIPSEG" NUMBER(22,0), 
	"CCOLECT" NUMBER(22,0), 
	"FINICIO" DATE, 
	"NDURACI" NUMBER(22,0), 
	"NPERMAN" NUMBER(22,0), 
	"PREDUC" NUMBER(22,0), 
	"CACTIVI" NUMBER(22,0), 
	"CGARANT" NUMBER(22,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."CRAMO" IS 'Ramo del Producto';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."CMODALI" IS 'Modalidad del Producto';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."CTIPSEG" IS 'Tipo del Producto';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."CCOLECT" IS 'Colectivo del Producto';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."FINICIO" IS 'Fecha entra en vigor';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."NDURACI" IS 'Rango Inicial';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."NPERMAN" IS 'Rango Final';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."PREDUC" IS 'Porcentaje de Reducción';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."CACTIVI" IS 'Actividad de la póliza';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."CGARANT" IS 'Código de Garantía';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_ULPREDE"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_ULPREDE"  IS 'Histórico de la tabla ULPREDE';
  GRANT UPDATE ON "AXIS"."HIS_ULPREDE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_ULPREDE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_ULPREDE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_ULPREDE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_ULPREDE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_ULPREDE" TO "PROGRAMADORESCSI";
