--------------------------------------------------------
--  DDL for Table HIS_PDS_SUPLINCOMPATIBLE
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_PDS_SUPLINCOMPATIBLE" 
   (	"CMOTMOV" NUMBER(22,0), 
	"SPRODUC" NUMBER(22,0), 
	"CMOTINC" NUMBER(22,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPLINCOMPATIBLE"."CMOTMOV" IS 'Motivo que se está realizando';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPLINCOMPATIBLE"."SPRODUC" IS 'Identificador del producto';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPLINCOMPATIBLE"."CMOTINC" IS 'Motivos incompatibles con el que se está realizando';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPLINCOMPATIBLE"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPLINCOMPATIBLE"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPLINCOMPATIBLE"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPLINCOMPATIBLE"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPLINCOMPATIBLE"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPLINCOMPATIBLE"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_SUPLINCOMPATIBLE"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_PDS_SUPLINCOMPATIBLE"  IS 'Histórico de la tabla PDS_SUPLINCOMPATIBLE';
  GRANT UPDATE ON "AXIS"."HIS_PDS_SUPLINCOMPATIBLE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PDS_SUPLINCOMPATIBLE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_PDS_SUPLINCOMPATIBLE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_PDS_SUPLINCOMPATIBLE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PDS_SUPLINCOMPATIBLE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_PDS_SUPLINCOMPATIBLE" TO "PROGRAMADORESCSI";
