--------------------------------------------------------
--  DDL for Table HIS_PRODBASESTECNICAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_PRODBASESTECNICAS" 
   (	"SPRODUC" NUMBER(22,0), 
	"CTIPO" NUMBER(22,0), 
	"TFUNCION" VARCHAR2(200 BYTE), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_PRODBASESTECNICAS"."SPRODUC" IS 'Secuencia del producto';
   COMMENT ON COLUMN "AXIS"."HIS_PRODBASESTECNICAS"."CTIPO" IS 'Código del tipo de Base Técnica (v.f.351)';
   COMMENT ON COLUMN "AXIS"."HIS_PRODBASESTECNICAS"."TFUNCION" IS 'Función a ejecutar para buscar los valores de la Base Técnica';
   COMMENT ON COLUMN "AXIS"."HIS_PRODBASESTECNICAS"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODBASESTECNICAS"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODBASESTECNICAS"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODBASESTECNICAS"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PRODBASESTECNICAS"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PRODBASESTECNICAS"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PRODBASESTECNICAS"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_PRODBASESTECNICAS"  IS 'Histórico de la tabla PRODBASESTECNICAS';
  GRANT UPDATE ON "AXIS"."HIS_PRODBASESTECNICAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PRODBASESTECNICAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_PRODBASESTECNICAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_PRODBASESTECNICAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PRODBASESTECNICAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_PRODBASESTECNICAS" TO "PROGRAMADORESCSI";
