--------------------------------------------------------
--  DDL for Table HIS_PDS_CONFIG_ACCION
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_PDS_CONFIG_ACCION" 
   (	"CCONACC" VARCHAR2(50 BYTE), 
	"CACCION" VARCHAR2(50 BYTE), 
	"CREALIZA" NUMBER(22,0), 
	"SPRODUC" NUMBER(22,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_PDS_CONFIG_ACCION"."CCONACC" IS 'Id. de las acciones';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_CONFIG_ACCION"."CACCION" IS 'Acciones a realizar';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_CONFIG_ACCION"."CREALIZA" IS 'Opción al realizar la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_CONFIG_ACCION"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_CONFIG_ACCION"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_CONFIG_ACCION"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_CONFIG_ACCION"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_CONFIG_ACCION"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_CONFIG_ACCION"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PDS_CONFIG_ACCION"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_PDS_CONFIG_ACCION"  IS 'Histórico de la tabla PDS_CONFIG_ACCION';
  GRANT UPDATE ON "AXIS"."HIS_PDS_CONFIG_ACCION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PDS_CONFIG_ACCION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_PDS_CONFIG_ACCION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_PDS_CONFIG_ACCION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PDS_CONFIG_ACCION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_PDS_CONFIG_ACCION" TO "PROGRAMADORESCSI";
