--------------------------------------------------------
--  DDL for Table HIS_PARMOTMOV
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_PARMOTMOV" 
   (	"CMOTMOV" NUMBER(22,0), 
	"CPARMOT" VARCHAR2(50 BYTE), 
	"CVALPAR" NUMBER(22,0), 
	"SPRODUC" NUMBER(22,0), 
	"TVALPAR" VARCHAR2(50 BYTE), 
	"FVALPAR" DATE, 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_PARMOTMOV"."CMOTMOV" IS 'codi de motivo de movimiento';
   COMMENT ON COLUMN "AXIS"."HIS_PARMOTMOV"."CPARMOT" IS 'codigo de parametro por motivo';
   COMMENT ON COLUMN "AXIS"."HIS_PARMOTMOV"."CVALPAR" IS 'valor del parametro';
   COMMENT ON COLUMN "AXIS"."HIS_PARMOTMOV"."SPRODUC" IS 'Producto, opcional si es generico de la instlación el producto es nulo';
   COMMENT ON COLUMN "AXIS"."HIS_PARMOTMOV"."TVALPAR" IS 'Valor Texto del parámetro';
   COMMENT ON COLUMN "AXIS"."HIS_PARMOTMOV"."FVALPAR" IS 'Valor Fecha del parámetro';
   COMMENT ON COLUMN "AXIS"."HIS_PARMOTMOV"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PARMOTMOV"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PARMOTMOV"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PARMOTMOV"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_PARMOTMOV"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PARMOTMOV"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_PARMOTMOV"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_PARMOTMOV"  IS 'Histórico de la tabla PARMOTMOV';
  GRANT UPDATE ON "AXIS"."HIS_PARMOTMOV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PARMOTMOV" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_PARMOTMOV" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_PARMOTMOV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PARMOTMOV" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_PARMOTMOV" TO "PROGRAMADORESCSI";
