--------------------------------------------------------
--  DDL for Table HIS_AGE_ENTIDADESASEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_AGE_ENTIDADESASEG" 
   (	"CAGENTE" NUMBER, 
	"CTIPENTIDADASEG" NUMBER, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FUSUMOD" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_AGE_ENTIDADESASEG"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."HIS_AGE_ENTIDADESASEG"."CTIPENTIDADASEG" IS 'Código tipo entidad aseguradora (v.f. 800077)';
   COMMENT ON COLUMN "AXIS"."HIS_AGE_ENTIDADESASEG"."CUSUALT" IS 'Código usuario alta del registro';
   COMMENT ON COLUMN "AXIS"."HIS_AGE_ENTIDADESASEG"."FALTA" IS 'Fecha de alta del registro';
   COMMENT ON COLUMN "AXIS"."HIS_AGE_ENTIDADESASEG"."CUSUMOD" IS 'Código usuario creación del registro';
   COMMENT ON COLUMN "AXIS"."HIS_AGE_ENTIDADESASEG"."FUSUMOD" IS 'Fecha de creación del registro';
   COMMENT ON TABLE "AXIS"."HIS_AGE_ENTIDADESASEG"  IS 'Histórico Otras entidades aseguradoras del agente';
  GRANT UPDATE ON "AXIS"."HIS_AGE_ENTIDADESASEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_AGE_ENTIDADESASEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_AGE_ENTIDADESASEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_AGE_ENTIDADESASEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_AGE_ENTIDADESASEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_AGE_ENTIDADESASEG" TO "PROGRAMADORESCSI";
