--------------------------------------------------------
--  DDL for Table HIS_GASTOSPROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_GASTOSPROD" 
   (	"SPRODUC" NUMBER(22,0), 
	"FINIVIG" DATE, 
	"FFINVIG" DATE, 
	"PGASTOS" NUMBER(22,0), 
	"CTIPAPL" NUMBER(22,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"FCREAHIST" DATE, 
	"ACCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_GASTOSPROD"."FINIVIG" IS 'Fecha inicio vigencia';
   COMMENT ON COLUMN "AXIS"."HIS_GASTOSPROD"."FFINVIG" IS 'Fecha fin vigencia';
   COMMENT ON COLUMN "AXIS"."HIS_GASTOSPROD"."PGASTOS" IS 'Porcentaje de gastos del producto';
   COMMENT ON COLUMN "AXIS"."HIS_GASTOSPROD"."CTIPAPL" IS 'Tipo de aplicación de gastos';
   COMMENT ON COLUMN "AXIS"."HIS_GASTOSPROD"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_GASTOSPROD"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_GASTOSPROD"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."HIS_GASTOSPROD"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON COLUMN "AXIS"."HIS_GASTOSPROD"."CUSUHIST" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_GASTOSPROD"."FCREAHIST" IS 'Fecha en que se realiza la acción';
   COMMENT ON COLUMN "AXIS"."HIS_GASTOSPROD"."ACCION" IS 'Acción realizada';
   COMMENT ON TABLE "AXIS"."HIS_GASTOSPROD"  IS 'Histórico de la tabla GASTOSPROD';
  GRANT UPDATE ON "AXIS"."HIS_GASTOSPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_GASTOSPROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_GASTOSPROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_GASTOSPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_GASTOSPROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_GASTOSPROD" TO "PROGRAMADORESCSI";
