--------------------------------------------------------
--  DDL for Table HIS_PRESTAMOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_PRESTAMOS" 
   (	"SHISPRES" NUMBER, 
	"CTAPRES" VARCHAR2(50 BYTE), 
	"ICAPINI" NUMBER, 
	"CTIPAMORT" NUMBER(2,0), 
	"CTIPINT" NUMBER(2,0), 
	"CTIPPRES" NUMBER(3,0), 
	"FALTA" DATE, 
	"FBAJA" DATE, 
	"FCARPRO" DATE, 
	"ILIMITE" NUMBER, 
	"CESTADO" NUMBER(2,0), 
	"ITASA" NUMBER(5,2), 
	"CTIPBAN" NUMBER(3,0), 
	"CBANCAR" VARCHAR2(34 BYTE), 
	"CFORPAG" NUMBER(2,0), 
	"FCONTAB" DATE, 
	"ICAPINI_MONCIA" NUMBER, 
	"FCAMBIO" DATE, 
	"CUSUHIS" VARCHAR2(20 BYTE), 
	"FALTAHIS" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."CTAPRES" IS 'Código del préstamo';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."ICAPINI" IS 'Capital inicial del préstamo';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."CTIPAMORT" IS 'Tipo de amortización (valor fijo 710)';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."CTIPINT" IS 'Tipo de interés (valor fijo 711)';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."CTIPPRES" IS 'Tipo de préstamo (valor fijo 712)';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."FALTA" IS 'Fecha de alta del préstamo';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."FBAJA" IS 'Fecha de baja del préstamo';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."FCARPRO" IS 'Fecha de cartera';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."ILIMITE" IS 'Importe límite  en la cuenta';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."CESTADO" IS 'Estado del préstamo (VF. 1058)';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."ITASA" IS '% de intereses del préstamo';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."CTIPBAN" IS 'Tipo de cuenta (IBAN o Cuenta Bancaria). [tabla maestra: TIPOS_CUENTA]';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."CBANCAR" IS 'Código IBAN o de Cuenta Bancaria';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."CFORPAG" IS 'Medio por el que se le abonara el prestamos al tomador';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."FCONTAB" IS 'Fecha de Contabilidad';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."ICAPINI_MONCIA" IS 'Capital inicial del préstamo (Moneda Cia)';
   COMMENT ON COLUMN "AXIS"."HIS_PRESTAMOS"."FCAMBIO" IS 'Fecha Cambio';
   COMMENT ON TABLE "AXIS"."HIS_PRESTAMOS"  IS 'Préstamos';
  GRANT UPDATE ON "AXIS"."HIS_PRESTAMOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PRESTAMOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_PRESTAMOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_PRESTAMOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_PRESTAMOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_PRESTAMOS" TO "PROGRAMADORESCSI";
