--------------------------------------------------------
--  DDL for Table HIS_AGE_REFERENCIAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."HIS_AGE_REFERENCIAS" 
   (	"CAGENTE" NUMBER, 
	"NORDREFERENCIA" NUMBER, 
	"TREFERENCIA" VARCHAR2(200 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FUSUMOD" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HIS_AGE_REFERENCIAS"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."HIS_AGE_REFERENCIAS"."NORDREFERENCIA" IS 'Número de orden de referencia';
   COMMENT ON COLUMN "AXIS"."HIS_AGE_REFERENCIAS"."TREFERENCIA" IS 'Descripción de la referencia';
   COMMENT ON COLUMN "AXIS"."HIS_AGE_REFERENCIAS"."CUSUALT" IS 'Código usuario alta del registro';
   COMMENT ON COLUMN "AXIS"."HIS_AGE_REFERENCIAS"."FALTA" IS 'Fecha de alta del registro';
   COMMENT ON COLUMN "AXIS"."HIS_AGE_REFERENCIAS"."CUSUMOD" IS 'Código usuario creación del registro';
   COMMENT ON COLUMN "AXIS"."HIS_AGE_REFERENCIAS"."FUSUMOD" IS 'Fecha de creación del registro';
   COMMENT ON TABLE "AXIS"."HIS_AGE_REFERENCIAS"  IS 'Histórico Otras referencias del agente';
  GRANT UPDATE ON "AXIS"."HIS_AGE_REFERENCIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_AGE_REFERENCIAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HIS_AGE_REFERENCIAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HIS_AGE_REFERENCIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HIS_AGE_REFERENCIAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HIS_AGE_REFERENCIAS" TO "PROGRAMADORESCSI";
