--------------------------------------------------------
--  DDL for Table HISCNV_CONV_EMP_VERS
--------------------------------------------------------

  CREATE TABLE "AXIS"."HISCNV_CONV_EMP_VERS" 
   (	"IDVERSION" NUMBER, 
	"NLIN" NUMBER, 
	"IDCONV" NUMBER, 
	"NVERSION" NUMBER, 
	"FEFECTO" DATE, 
	"FVENCIM" DATE, 
	"CVIDA" NUMBER, 
	"CTASAVIDA" NUMBER, 
	"EDAD_PROM" NUMBER, 
	"CNIVELR" NUMBER, 
	"CESTADO" NUMBER, 
	"TLUGAR_PUBL" VARCHAR2(50 BYTE), 
	"TOBSERV" VARCHAR2(2000 BYTE), 
	"FPUBLIC" DATE, 
	"PDTO" NUMBER, 
	"FINIVIG" DATE, 
	"FFINVIG" DATE, 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"CUSUHIST" VARCHAR2(20 BYTE), 
	"CACCION" VARCHAR2(2 BYTE), 
	"FCREAHIST" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."IDVERSION" IS 'Línea de historico';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."IDCONV" IS 'Identificador de Convenio';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."NVERSION" IS 'Numero versión';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."FEFECTO" IS 'Fecha efecto versión';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."FVENCIM" IS 'Fecha vencimiento versión';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."CVIDA" IS 'Indicador de garantías de vida. DETVALORES 8001002';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."CTASAVIDA" IS 'Indicador tasa vida. DETVALORES 8001003';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."EDAD_PROM" IS 'Edad promedio del convenio';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."CNIVELR" IS 'Nivel de Riesgo (subtablas)';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."CESTADO" IS 'Estado de la versión. DETVALORES 8001004';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."TLUGAR_PUBL" IS 'Texto con lugar de publicación';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."TOBSERV" IS 'Observaciones de la versión';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."FPUBLIC" IS 'Fecha de publicación';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."PDTO" IS '% Descuento de la versión';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."FINIVIG" IS 'Fecha inicio Vigencia';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."FFINVIG" IS 'Fecha final Vigencia';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."FALTA" IS 'Fecha de Alta';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."CUSUALT" IS 'Usuario Alta';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."CUSUMOD" IS 'Usuario Modificación';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."FMODIFI" IS 'Fecha modificación';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."CUSUHIST" IS 'Usuario crea historico';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."CACCION" IS 'Acción';
   COMMENT ON COLUMN "AXIS"."HISCNV_CONV_EMP_VERS"."FCREAHIST" IS 'Fecha Creación Historico';
  GRANT UPDATE ON "AXIS"."HISCNV_CONV_EMP_VERS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISCNV_CONV_EMP_VERS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HISCNV_CONV_EMP_VERS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HISCNV_CONV_EMP_VERS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISCNV_CONV_EMP_VERS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HISCNV_CONV_EMP_VERS" TO "PROGRAMADORESCSI";
