--------------------------------------------------------
--  DDL for Table HISINQUIAVAL
--------------------------------------------------------

  CREATE TABLE "AXIS"."HISINQUIAVAL" 
   (	"SSEGURO" NUMBER, 
	"SPERSON" NUMBER(10,0), 
	"NRIESGO" NUMBER(5,0), 
	"NMOVIMI" NUMBER(2,0), 
	"CTIPFIG" NUMBER(5,0), 
	"CDOMICI" NUMBER, 
	"IINGRMEN" NUMBER, 
	"IINGRANUAL" NUMBER, 
	"FFECINI" DATE, 
	"FFECFIN" DATE, 
	"CTIPCONTRATO" NUMBER(3,0), 
	"CSITLABORAL" NUMBER(3,0), 
	"CSUPFILTRO" NUMBER(1,0) DEFAULT 0, 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FMODIF" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente';
   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."SPERSON" IS 'Identificador único de la Personas';
   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."NRIESGO" IS 'Numero de riesgo';
   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."CTIPFIG" IS 'TIPO DE FIGURA. DETVALOR 800099';
   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."CDOMICI" IS 'Código de domicilio';
   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."IINGRMEN" IS 'Ingresos mensuales';
   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."IINGRANUAL" IS 'Ingresos anuales';
   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."FFECINI" IS 'Fecha de alta en la póliza';
   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."FFECFIN" IS 'FFECFIN';
   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."CTIPCONTRATO" IS 'TIPO DE CONTRATO LABORAL, DETVALORES 800088';
   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."CSITLABORAL" IS 'SITUACION LABORAL, DETVALORES 800087';
   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."CSUPFILTRO" IS 'La figura ha pasado ''ASNEF'', ''0''- No ''1''-Si, default 0';
   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."CUSUARI" IS 'Usuario modificación';
   COMMENT ON COLUMN "AXIS"."HISINQUIAVAL"."FMODIF" IS 'Fecha modificación';
   COMMENT ON TABLE "AXIS"."HISINQUIAVAL"  IS 'Historico Inquilinos y Avalistas';
  GRANT UPDATE ON "AXIS"."HISINQUIAVAL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISINQUIAVAL" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HISINQUIAVAL" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HISINQUIAVAL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISINQUIAVAL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HISINQUIAVAL" TO "PROGRAMADORESCSI";
