--------------------------------------------------------
--  DDL for Table HISPERLOPD_CONTACTOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."HISPERLOPD_CONTACTOS" 
   (	"SPERSON" NUMBER(10,0), 
	"CAGENTE" NUMBER, 
	"CMODCON" NUMBER, 
	"NORDEN" NUMBER(5,0), 
	"CTIPCON" NUMBER(2,0), 
	"TCOMCON" VARCHAR2(40 BYTE), 
	"TVALCON" VARCHAR2(100 BYTE), 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FMOVIMI" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FUSUMOD" DATE, 
	"COBLIGA" NUMBER(1,0) DEFAULT 0, 
	"NUM_LOPD" NUMBER, 
	"FLOPD" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HISPERLOPD_CONTACTOS"."SPERSON" IS 'Secuencia unica de identificacion de una persona';
   COMMENT ON COLUMN "AXIS"."HISPERLOPD_CONTACTOS"."CAGENTE" IS 'Código agente';
   COMMENT ON COLUMN "AXIS"."HISPERLOPD_CONTACTOS"."CMODCON" IS 'Secuencia modo contacto';
   COMMENT ON COLUMN "AXIS"."HISPERLOPD_CONTACTOS"."NORDEN" IS 'Número de orden del histórico';
   COMMENT ON COLUMN "AXIS"."HISPERLOPD_CONTACTOS"."CTIPCON" IS 'Código tipo contacto';
   COMMENT ON COLUMN "AXIS"."HISPERLOPD_CONTACTOS"."TCOMCON" IS 'Especificación del medio';
   COMMENT ON COLUMN "AXIS"."HISPERLOPD_CONTACTOS"."TVALCON" IS 'Valor contacto';
   COMMENT ON COLUMN "AXIS"."HISPERLOPD_CONTACTOS"."CUSUARI" IS 'Código usuario creación registro';
   COMMENT ON COLUMN "AXIS"."HISPERLOPD_CONTACTOS"."FMOVIMI" IS 'Fecha creación registro';
   COMMENT ON COLUMN "AXIS"."HISPERLOPD_CONTACTOS"."CUSUMOD" IS 'Código usuario modificación';
   COMMENT ON COLUMN "AXIS"."HISPERLOPD_CONTACTOS"."FUSUMOD" IS 'Fecha modificación registro';
   COMMENT ON COLUMN "AXIS"."HISPERLOPD_CONTACTOS"."COBLIGA" IS 'Codigo de contaco único (Si: 1, No: 0)';
   COMMENT ON COLUMN "AXIS"."HISPERLOPD_CONTACTOS"."NUM_LOPD" IS 'Número de orden de histórico';
   COMMENT ON COLUMN "AXIS"."HISPERLOPD_CONTACTOS"."FLOPD" IS 'Fecha de traspaso a las tablas PERLOPD';
   COMMENT ON TABLE "AXIS"."HISPERLOPD_CONTACTOS"  IS 'Tabla histórico contactos de la persona';
  GRANT UPDATE ON "AXIS"."HISPERLOPD_CONTACTOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISPERLOPD_CONTACTOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HISPERLOPD_CONTACTOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HISPERLOPD_CONTACTOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISPERLOPD_CONTACTOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HISPERLOPD_CONTACTOS" TO "PROGRAMADORESCSI";
