--------------------------------------------------------
--  DDL for Table HISPER_NACIONALIDADES
--------------------------------------------------------

  CREATE TABLE "AXIS"."HISPER_NACIONALIDADES" 
   (	"SPERSON" NUMBER(10,0), 
	"CAGENTE" NUMBER, 
	"CPAIS" NUMBER(3,0), 
	"CDEFECTO" NUMBER(1,0), 
	"FMOVIMI" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HISPER_NACIONALIDADES"."SPERSON" IS 'Identificador único de persona';
   COMMENT ON COLUMN "AXIS"."HISPER_NACIONALIDADES"."CAGENTE" IS 'Identificador único de agente';
   COMMENT ON COLUMN "AXIS"."HISPER_NACIONALIDADES"."CPAIS" IS 'Código de pías';
   COMMENT ON COLUMN "AXIS"."HISPER_NACIONALIDADES"."CDEFECTO" IS 'Indica si la es la nacionalidad por defecto de la persona (0/1) -> (Si/No). (VF 108)';
   COMMENT ON COLUMN "AXIS"."HISPER_NACIONALIDADES"."FMOVIMI" IS 'Fecha de modificación';
   COMMENT ON COLUMN "AXIS"."HISPER_NACIONALIDADES"."CUSUALT" IS 'ususario de modificación';
  GRANT UPDATE ON "AXIS"."HISPER_NACIONALIDADES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISPER_NACIONALIDADES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HISPER_NACIONALIDADES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HISPER_NACIONALIDADES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISPER_NACIONALIDADES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HISPER_NACIONALIDADES" TO "PROGRAMADORESCSI";
