--------------------------------------------------------
--  DDL for Table HISPER_DOCUMENTOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."HISPER_DOCUMENTOS" 
   (	"SPERSON" NUMBER(10,0), 
	"CAGENTE" NUMBER, 
	"IDDOCGEDOX" NUMBER(10,0), 
	"FCADUCA" DATE, 
	"TOBSERVA" VARCHAR2(1000 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FMOVIMI" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FUSUMOD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HISPER_DOCUMENTOS"."SPERSON" IS 'Secuencia única de identificación de una persona';
   COMMENT ON COLUMN "AXIS"."HISPER_DOCUMENTOS"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."HISPER_DOCUMENTOS"."IDDOCGEDOX" IS 'Identificador del documento GEDOX';
   COMMENT ON COLUMN "AXIS"."HISPER_DOCUMENTOS"."FCADUCA" IS 'Fecha de caducidad del documento';
   COMMENT ON COLUMN "AXIS"."HISPER_DOCUMENTOS"."TOBSERVA" IS 'Observaciones';
   COMMENT ON COLUMN "AXIS"."HISPER_DOCUMENTOS"."CUSUALT" IS 'Código usuario alta del registro original';
   COMMENT ON COLUMN "AXIS"."HISPER_DOCUMENTOS"."FALTA" IS 'Fecha de alta del registro original';
   COMMENT ON COLUMN "AXIS"."HISPER_DOCUMENTOS"."CUSUARI" IS 'Código usuario modificación del registro original';
   COMMENT ON COLUMN "AXIS"."HISPER_DOCUMENTOS"."FMOVIMI" IS 'Fecha modificación del registro original';
   COMMENT ON COLUMN "AXIS"."HISPER_DOCUMENTOS"."CUSUMOD" IS 'Código usuario modificación del registro';
   COMMENT ON COLUMN "AXIS"."HISPER_DOCUMENTOS"."FUSUMOD" IS 'Fecha de modificación del registro';
   COMMENT ON TABLE "AXIS"."HISPER_DOCUMENTOS"  IS 'Tabla histórica de documentos de la persona';
  GRANT UPDATE ON "AXIS"."HISPER_DOCUMENTOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISPER_DOCUMENTOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HISPER_DOCUMENTOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HISPER_DOCUMENTOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISPER_DOCUMENTOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HISPER_DOCUMENTOS" TO "PROGRAMADORESCSI";
