--------------------------------------------------------
--  DDL for Table HISREEMBOLSOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."HISREEMBOLSOS" 
   (	"NREEMB" NUMBER(8,0), 
	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"CGARANT" NUMBER(6,0), 
	"AGR_SALUD" VARCHAR2(20 BYTE), 
	"SPERSON" NUMBER(10,0), 
	"CESTADO" NUMBER(2,0), 
	"FESTADO" DATE, 
	"TOBSERV" VARCHAR2(2000 BYTE), 
	"CBANCAR" VARCHAR2(50 BYTE), 
	"CTIPBAN" NUMBER, 
	"FALTA" DATE, 
	"CUSUALTA" VARCHAR2(20 BYTE), 
	"CORIGEN" NUMBER(2,0), 
	"FECHA" DATE, 
	"USUARIO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HISREEMBOLSOS"."NREEMB" IS 'Nº de reembolso';
   COMMENT ON COLUMN "AXIS"."HISREEMBOLSOS"."SSEGURO" IS 'Id. Del seguro';
   COMMENT ON COLUMN "AXIS"."HISREEMBOLSOS"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."HISREEMBOLSOS"."CGARANT" IS 'Código de garantia';
   COMMENT ON COLUMN "AXIS"."HISREEMBOLSOS"."AGR_SALUD" IS 'Agrupación de producto. Parproducto AGR_SALUD';
   COMMENT ON COLUMN "AXIS"."HISREEMBOLSOS"."CESTADO" IS 'Valor fijo "Estado del reembolso".
                                              0- Gestión oficinas.
                                              1- Gestión compañía.
                                              2- Aceptado.
                                              3- Transferido.
                                              4- Anulado';
   COMMENT ON COLUMN "AXIS"."HISREEMBOLSOS"."FESTADO" IS 'Fecha estado';
   COMMENT ON COLUMN "AXIS"."HISREEMBOLSOS"."TOBSERV" IS 'Obervaciones';
   COMMENT ON COLUMN "AXIS"."HISREEMBOLSOS"."CBANCAR" IS 'Cuenta de abono del reembolso';
   COMMENT ON COLUMN "AXIS"."HISREEMBOLSOS"."CTIPBAN" IS 'Tipo de cuenta bancaria';
   COMMENT ON COLUMN "AXIS"."HISREEMBOLSOS"."FALTA" IS 'Fecha alta';
   COMMENT ON COLUMN "AXIS"."HISREEMBOLSOS"."CUSUALTA" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."HISREEMBOLSOS"."CORIGEN" IS 'Valor Fijo "Origen": 0- Automático 1- Manual';
  GRANT UPDATE ON "AXIS"."HISREEMBOLSOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISREEMBOLSOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HISREEMBOLSOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HISREEMBOLSOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISREEMBOLSOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HISREEMBOLSOS" TO "PROGRAMADORESCSI";
