--------------------------------------------------------
--  DDL for Table HISRECIBOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."HISRECIBOS" 
   (	"SHISREC" NUMBER(9,0), 
	"NRECIBO" NUMBER, 
	"CCOBBAN" NUMBER(3,0), 
	"CESTAUX" NUMBER(2,0), 
	"CESTIMP" NUMBER(2,0), 
	"CBANCAR" VARCHAR2(50 BYTE), 
	"CGESCOB" NUMBER(1,0), 
	"CTIPREC" NUMBER(2,0), 
	"FMODBAN" DATE, 
	"FMODIF" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"CTIPBAN" NUMBER(3,0), 
	"NCUOTAR" NUMBER(3,0), 
	"CGESCAR" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HISRECIBOS"."SHISREC" IS 'Número de histórico (secuencia: SRECHIS)';
   COMMENT ON COLUMN "AXIS"."HISRECIBOS"."NRECIBO" IS 'Número de recibo.';
   COMMENT ON COLUMN "AXIS"."HISRECIBOS"."CCOBBAN" IS 'Código de cobrador bancario';
   COMMENT ON COLUMN "AXIS"."HISRECIBOS"."CESTAUX" IS 'Código subestado recibo';
   COMMENT ON COLUMN "AXIS"."HISRECIBOS"."CESTIMP" IS 'Estado impresión recibo, CVALOR:75';
   COMMENT ON COLUMN "AXIS"."HISRECIBOS"."CBANCAR" IS 'Código bancario';
   COMMENT ON COLUMN "AXIS"."HISRECIBOS"."CTIPREC" IS 'Tipo de recibo, CVALOR:8 (migración extornos ALN)';
   COMMENT ON COLUMN "AXIS"."HISRECIBOS"."FMODBAN" IS 'Fecha modificación cod. bancario. (si no hay cambio NULO)';
   COMMENT ON COLUMN "AXIS"."HISRECIBOS"."FMODIF" IS 'Fecha de modificación.';
   COMMENT ON COLUMN "AXIS"."HISRECIBOS"."CUSUMOD" IS 'Usuario de modificación.';
   COMMENT ON COLUMN "AXIS"."HISRECIBOS"."CTIPBAN" IS 'Tipo de cuenta ( iban o cuenta bancaria). [tabla maestra: TIPOS_CUENTA]';
   COMMENT ON COLUMN "AXIS"."HISRECIBOS"."NCUOTAR" IS 'Número cuotas de tarjeta';
   COMMENT ON COLUMN "AXIS"."HISRECIBOS"."CGESCAR" IS 'Indica si la gesti¿n de cartera se realiz¿ por OUTSOURCING (2) o DIRECTA(1) (8001111)';
   COMMENT ON TABLE "AXIS"."HISRECIBOS"  IS 'Histórico recibos';
  GRANT UPDATE ON "AXIS"."HISRECIBOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISRECIBOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HISRECIBOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HISRECIBOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISRECIBOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HISRECIBOS" TO "PROGRAMADORESCSI";
