--------------------------------------------------------
--  DDL for Table HISTAUTORIZACIONES
--------------------------------------------------------

  CREATE TABLE "AXIS"."HISTAUTORIZACIONES" 
   (	"SHISTAUT" NUMBER(11,0), 
	"SAUTPSR" NUMBER(11,0), 
	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"CUSUPET" VARCHAR2(20 BYTE), 
	"FPETICI" DATE, 
	"TMSGPET" VARCHAR2(500 BYTE), 
	"CPERFEXG" NUMBER(4,0), 
	"CUSUAUT" VARCHAR2(20 BYTE), 
	"FAUTORI" DATE, 
	"TMSGAUT" VARCHAR2(500 BYTE), 
	"SSOLICIT" NUMBER(8,0), 
	"F_TRAHIS" DATE, 
	"CESTAUT" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HISTAUTORIZACIONES"."SHISTAUT" IS 'Secuencia (PK) DETAUTORIZACIONES';
   COMMENT ON COLUMN "AXIS"."HISTAUTORIZACIONES"."SAUTPSR" IS 'Secuencia (PK) AUTORIZACIONES';
   COMMENT ON COLUMN "AXIS"."HISTAUTORIZACIONES"."SSEGURO" IS 'Clave de SEGUROS';
   COMMENT ON COLUMN "AXIS"."HISTAUTORIZACIONES"."NRIESGO" IS 'Numero de Riesgo';
   COMMENT ON COLUMN "AXIS"."HISTAUTORIZACIONES"."NMOVIMI" IS 'Numero de Movimiento del Seguro';
   COMMENT ON COLUMN "AXIS"."HISTAUTORIZACIONES"."CUSUPET" IS 'Usuario del Mov. que ha quedado pendiente';
   COMMENT ON COLUMN "AXIS"."HISTAUTORIZACIONES"."FPETICI" IS 'Fecha en la que el Movimiento ha quedado pendiente';
   COMMENT ON COLUMN "AXIS"."HISTAUTORIZACIONES"."TMSGPET" IS 'Mensaje opcional del Usuario';
   COMMENT ON COLUMN "AXIS"."HISTAUTORIZACIONES"."CPERFEXG" IS 'Perfil';
   COMMENT ON COLUMN "AXIS"."HISTAUTORIZACIONES"."CUSUAUT" IS 'Usuario autorizador';
   COMMENT ON COLUMN "AXIS"."HISTAUTORIZACIONES"."FAUTORI" IS 'Fecha de modificacion por parte del autorizacion';
   COMMENT ON COLUMN "AXIS"."HISTAUTORIZACIONES"."TMSGAUT" IS 'Mensaje del Usuario autorizador';
   COMMENT ON COLUMN "AXIS"."HISTAUTORIZACIONES"."SSOLICIT" IS 'Código perfil necesario';
   COMMENT ON COLUMN "AXIS"."HISTAUTORIZACIONES"."F_TRAHIS" IS 'Fecha traspaso a historico';
   COMMENT ON TABLE "AXIS"."HISTAUTORIZACIONES"  IS 'Cabecera de DETAutorizaciones';
  GRANT UPDATE ON "AXIS"."HISTAUTORIZACIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISTAUTORIZACIONES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HISTAUTORIZACIONES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HISTAUTORIZACIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISTAUTORIZACIONES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HISTAUTORIZACIONES" TO "PROGRAMADORESCSI";
