--------------------------------------------------------
--  DDL for Table HISTOMADORES
--------------------------------------------------------

  CREATE TABLE "AXIS"."HISTOMADORES" 
   (	"SSEGURO" NUMBER, 
	"SPERSON" NUMBER(10,0), 
	"NMOVIMI" NUMBER(4,0), 
	"NORDTOM" NUMBER(2,0), 
	"CDOMICI" NUMBER, 
	"CEXISTEPAGADOR" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HISTOMADORES"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente.';
   COMMENT ON COLUMN "AXIS"."HISTOMADORES"."SPERSON" IS 'Identificador único de la Personas.';
   COMMENT ON COLUMN "AXIS"."HISTOMADORES"."NMOVIMI" IS 'Número de movimiento.';
   COMMENT ON COLUMN "AXIS"."HISTOMADORES"."NORDTOM" IS 'Orden de los diferentes tomadores, 0 = Principal (Correo, ...).';
   COMMENT ON COLUMN "AXIS"."HISTOMADORES"."CDOMICI" IS 'Código de domicilio.';
   COMMENT ON COLUMN "AXIS"."HISTOMADORES"."CEXISTEPAGADOR" IS 'Indica si existe un pagador del recibo distinto del tomador (0=No 1=Si)';
   COMMENT ON TABLE "AXIS"."HISTOMADORES"  IS 'Histórico de tomadores.';
  GRANT UPDATE ON "AXIS"."HISTOMADORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISTOMADORES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HISTOMADORES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HISTOMADORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISTOMADORES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HISTOMADORES" TO "PROGRAMADORESCSI";
