--------------------------------------------------------
--  DDL for Table HISVINCULACIONES
--------------------------------------------------------

  CREATE TABLE "AXIS"."HISVINCULACIONES" 
   (	"SHISVIN" NUMBER(9,0), 
	"SPERSON" NUMBER(10,0), 
	"CVINCLO" NUMBER(4,0), 
	"FDESDE" DATE, 
	"FHASTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HISVINCULACIONES"."SHISVIN" IS 'Número de histórico';
   COMMENT ON COLUMN "AXIS"."HISVINCULACIONES"."SPERSON" IS 'Identificador único de las Personas';
   COMMENT ON COLUMN "AXIS"."HISVINCULACIONES"."CVINCLO" IS 'Código vínculo';
   COMMENT ON COLUMN "AXIS"."HISVINCULACIONES"."FDESDE" IS 'Inicio periodo de vigencia';
   COMMENT ON COLUMN "AXIS"."HISVINCULACIONES"."FHASTA" IS 'fin periodo de vigencia';
   COMMENT ON COLUMN "AXIS"."HISVINCULACIONES"."CUSUMOD" IS 'Usuario modificación';
   COMMENT ON TABLE "AXIS"."HISVINCULACIONES"  IS 'Histórico de vinculaciones';
  GRANT UPDATE ON "AXIS"."HISVINCULACIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISVINCULACIONES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HISVINCULACIONES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HISVINCULACIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISVINCULACIONES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HISVINCULACIONES" TO "PROGRAMADORESCSI";
