--------------------------------------------------------
--  DDL for Table HISZONIF
--------------------------------------------------------

  CREATE TABLE "AXIS"."HISZONIF" 
   (	"SZONIFH" NUMBER(6,0), 
	"SZONIF" NUMBER(4,0), 
	"FZONIFI" DATE, 
	"FZONIFF" DATE, 
	"FZONIFA" DATE, 
	"CZONIFT" NUMBER(2,0), 
	"CZONIFE" NUMBER(2,0), 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FMODIF" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."HISZONIF"."SZONIFH" IS 'Identificador histórico zonificación';
   COMMENT ON COLUMN "AXIS"."HISZONIF"."SZONIF" IS 'Identificador zonificación';
   COMMENT ON COLUMN "AXIS"."HISZONIF"."FZONIFI" IS 'Fecha inicio vigencia zonificación';
   COMMENT ON COLUMN "AXIS"."HISZONIF"."FZONIFF" IS 'Fecha fin vigencia zonificación';
   COMMENT ON COLUMN "AXIS"."HISZONIF"."FZONIFA" IS 'Fecha activación zonificación';
   COMMENT ON COLUMN "AXIS"."HISZONIF"."CZONIFT" IS 'Tipo de zonas';
   COMMENT ON COLUMN "AXIS"."HISZONIF"."CZONIFE" IS 'Estado histórico zonificación';
   COMMENT ON COLUMN "AXIS"."HISZONIF"."FALTA" IS 'Fecha alta';
   COMMENT ON COLUMN "AXIS"."HISZONIF"."CUSUALT" IS 'Usuario alta';
   COMMENT ON COLUMN "AXIS"."HISZONIF"."FMODIF" IS 'Fecha modificación';
   COMMENT ON COLUMN "AXIS"."HISZONIF"."CUSUMOD" IS 'Usuario modificación';
   COMMENT ON TABLE "AXIS"."HISZONIF"  IS 'Histórico de zonificaciones';
  GRANT UPDATE ON "AXIS"."HISZONIF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISZONIF" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."HISZONIF" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."HISZONIF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."HISZONIF" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."HISZONIF" TO "PROGRAMADORESCSI";
