--------------------------------------------------------
--  DDL for Table IBNER_PREVIO
--------------------------------------------------------

  CREATE TABLE "AXIS"."IBNER_PREVIO" 
   (	"CEMPRES" NUMBER(2,0), 
	"FCALCUL" DATE, 
	"SPROCES" NUMBER, 
	"CRAMO" NUMBER(8,0), 
	"IIBNER" NUMBER DEFAULT 0, 
	"PRATIO" NUMBER(5,2) DEFAULT 0, 
	"CERROR" NUMBER(2,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."IBNER_PREVIO"."CEMPRES" IS 'Código de la Empresa';
   COMMENT ON COLUMN "AXIS"."IBNER_PREVIO"."FCALCUL" IS 'Fecha del cálculo';
   COMMENT ON COLUMN "AXIS"."IBNER_PREVIO"."SPROCES" IS 'Código del Proceso';
   COMMENT ON COLUMN "AXIS"."IBNER_PREVIO"."CRAMO" IS 'Código del Ramo';
   COMMENT ON COLUMN "AXIS"."IBNER_PREVIO"."IIBNER" IS 'Importe IBNER';
   COMMENT ON COLUMN "AXIS"."IBNER_PREVIO"."PRATIO" IS 'Porcentaje de desviación según el cálculo de la provisión de los últimos 5 años';
   COMMENT ON COLUMN "AXIS"."IBNER_PREVIO"."CERROR" IS 'Código del error';
   COMMENT ON TABLE "AXIS"."IBNER_PREVIO"  IS 'Tabla de IBNER_PREVIO (Provisión complementaria a la IBNR_RAM_PREVIO)';
  GRANT UPDATE ON "AXIS"."IBNER_PREVIO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."IBNER_PREVIO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."IBNER_PREVIO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."IBNER_PREVIO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."IBNER_PREVIO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."IBNER_PREVIO" TO "PROGRAMADORESCSI";
