--------------------------------------------------------
--  DDL for Table ICD_DECLINA_UNDW
--------------------------------------------------------

  CREATE TABLE "AXIS"."ICD_DECLINA_UNDW" 
   (	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER(4,0), 
	"CINDEX" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ICD_DECLINA_UNDW"."SSEGURO" IS 'Identificador del seguro.';
   COMMENT ON COLUMN "AXIS"."ICD_DECLINA_UNDW"."NMOVIMI" IS 'Numero de movimiento relacionado.';
   COMMENT ON COLUMN "AXIS"."ICD_DECLINA_UNDW"."CINDEX" IS 'Indice de la enfermedad.';
  GRANT UPDATE ON "AXIS"."ICD_DECLINA_UNDW" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ICD_DECLINA_UNDW" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ICD_DECLINA_UNDW" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ICD_DECLINA_UNDW" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ICD_DECLINA_UNDW" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ICD_DECLINA_UNDW" TO "PROGRAMADORESCSI";
