--------------------------------------------------------
--  DDL for Table INDICADORES_CIAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."INDICADORES_CIAS" 
   (	"CCOMPANI" NUMBER, 
	"CTIPIND" NUMBER, 
	"NVALOR" NUMBER DEFAULT 0, 
	"FINIVIG" DATE, 
	"FFINVIG" DATE, 
	"CENVIOSAP" NUMBER(1,0) DEFAULT 1, 
	"CAPLICA" NUMBER(1,0) DEFAULT 0, 
	"FFALTA" DATE, 
	"FBAJA" DATE, 
	"CUSUALTA" VARCHAR2(20 BYTE), 
	"CUSUMOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INDICADORES_CIAS"."CCOMPANI" IS 'Código de la compañía';
   COMMENT ON COLUMN "AXIS"."INDICADORES_CIAS"."CTIPIND" IS 'Código del tipo de indicador';
   COMMENT ON COLUMN "AXIS"."INDICADORES_CIAS"."NVALOR" IS 'Valor del indicador';
   COMMENT ON COLUMN "AXIS"."INDICADORES_CIAS"."FINIVIG" IS 'Fecha de inicio de vigencia del indicador';
   COMMENT ON COLUMN "AXIS"."INDICADORES_CIAS"."FFINVIG" IS 'Fecha de fin de vigencia del indicador';
   COMMENT ON COLUMN "AXIS"."INDICADORES_CIAS"."CENVIOSAP" IS 'Código que indica si el indicador debe viajar a SAP o no. (0:No viaja, 1:Viaja)';
   COMMENT ON COLUMN "AXIS"."INDICADORES_CIAS"."CAPLICA" IS 'DV. 17001';
   COMMENT ON COLUMN "AXIS"."INDICADORES_CIAS"."FFALTA" IS 'Fecha alta';
   COMMENT ON COLUMN "AXIS"."INDICADORES_CIAS"."FBAJA" IS 'Fecha modificación';
   COMMENT ON COLUMN "AXIS"."INDICADORES_CIAS"."CUSUALTA" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."INDICADORES_CIAS"."CUSUMOD" IS 'Usuario de modificación';
   COMMENT ON TABLE "AXIS"."INDICADORES_CIAS"  IS 'Relación de indicadores SAP con compañías';
  GRANT UPDATE ON "AXIS"."INDICADORES_CIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INDICADORES_CIAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INDICADORES_CIAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INDICADORES_CIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INDICADORES_CIAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INDICADORES_CIAS" TO "PROGRAMADORESCSI";
