--------------------------------------------------------
--  DDL for Table INT_SERVICIOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_SERVICIOS" 
   (	"CINTERF" VARCHAR2(4 BYTE), 
	"NINTERF" VARCHAR2(25 BYTE), 
	"CMAPEAD_OUT" VARCHAR2(5 BYTE), 
	"CMAPEAD_IN" VARCHAR2(5 BYTE), 
	"TINTERF" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_SERVICIOS"."CINTERF" IS 'Codigo del servicio';
   COMMENT ON COLUMN "AXIS"."INT_SERVICIOS"."NINTERF" IS 'Nombre del servicio';
   COMMENT ON COLUMN "AXIS"."INT_SERVICIOS"."CMAPEAD_OUT" IS 'Código del mapeador que genera el xml de salida para este servicio';
   COMMENT ON COLUMN "AXIS"."INT_SERVICIOS"."CMAPEAD_IN" IS 'Código del mapeador que carga el xml de entradapara este servicio';
   COMMENT ON COLUMN "AXIS"."INT_SERVICIOS"."TINTERF" IS 'Descripción del servicio';
  GRANT UPDATE ON "AXIS"."INT_SERVICIOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_SERVICIOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_SERVICIOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_SERVICIOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_SERVICIOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_SERVICIOS" TO "PROGRAMADORESCSI";
