--------------------------------------------------------
--  DDL for Table INT_CONTROL_ERRORES
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_CONTROL_ERRORES" 
   (	"SERROR" NUMBER(12,0), 
	"FECHA" DATE, 
	"NOM_INT" VARCHAR2(50 BYTE), 
	"CTIPERR" NUMBER(1,0), 
	"T_ERROR" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_CONTROL_ERRORES"."SERROR" IS 'Orden en el que se insertan los registros';
   COMMENT ON COLUMN "AXIS"."INT_CONTROL_ERRORES"."FECHA" IS 'Fecha en la que se hace la insercion';
   COMMENT ON COLUMN "AXIS"."INT_CONTROL_ERRORES"."NOM_INT" IS 'Nombre de la interfase';
   COMMENT ON COLUMN "AXIS"."INT_CONTROL_ERRORES"."CTIPERR" IS 'Tipo inserción: 0-Aviso-traza, 1-Incidencia, 2-Control de error';
   COMMENT ON COLUMN "AXIS"."INT_CONTROL_ERRORES"."T_ERROR" IS 'Descripcion del error';
  GRANT UPDATE ON "AXIS"."INT_CONTROL_ERRORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_CONTROL_ERRORES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_CONTROL_ERRORES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_CONTROL_ERRORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_CONTROL_ERRORES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_CONTROL_ERRORES" TO "PROGRAMADORESCSI";
