--------------------------------------------------------
--  DDL for Table INT_RECIBOS_ASEFA
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_RECIBOS_ASEFA" 
   (	"SINTERF" NUMBER, 
	"CMAPEAD" VARCHAR2(5 BYTE), 
	"SMAPEAD" NUMBER, 
	"NLINEA" NUMBER(6,0), 
	"RAMO" NUMBER(2,0), 
	"ANYO" NUMBER(4,0), 
	"POLIZA" NUMBER(6,0), 
	"CERTIFICADO" NUMBER(5,0), 
	"RECIBO" NUMBER(6,0), 
	"PRIMA" NUMBER, 
	"RECARGO" NUMBER, 
	"IMPUESTOS" NUMBER, 
	"INDICADORRECIBOEXTORNO" VARCHAR2(1 BYTE), 
	"FECHAPASOEXIGIBLE" VARCHAR2(8 BYTE), 
	"FECHAEFECTO" VARCHAR2(8 BYTE), 
	"TIPORECIBO" VARCHAR2(1 BYTE), 
	"COMISIONLIQUIDACION" NUMBER, 
	"PORCENTAJECOMISION" NUMBER(6,2), 
	"RESERVADO_1" VARCHAR2(1 BYTE), 
	"COMISIONASIGNADA" NUMBER, 
	"ESTADORECIBO" VARCHAR2(1 BYTE), 
	"FECHAVENCIMIENTO" VARCHAR2(8 BYTE), 
	"FECHAESTADO" VARCHAR2(8 BYTE), 
	"NUMEROCLIENTE" VARCHAR2(5 BYTE), 
	"GRUPOCLIENTE" VARCHAR2(2 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DNICIF" VARCHAR2(9 BYTE), 
	"TIPODOCUMENTO" VARCHAR2(1 BYTE), 
	"NOMBREASEGURADO" VARCHAR2(50 BYTE), 
	"DNICIFASEGURADO" VARCHAR2(9 BYTE), 
	"TIPODOCUMENTOASEGURADO" VARCHAR2(1 BYTE), 
	"BANCO" VARCHAR2(4 BYTE), 
	"SUCURSAL" VARCHAR2(4 BYTE), 
	"CUENTABANCARIA" VARCHAR2(10 BYTE), 
	"TIPO_OPER" VARCHAR2(10 BYTE), 
	"CRECCIA" VARCHAR2(50 BYTE), 
	"NCARGA" NUMBER, 
	"PROCESO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."SINTERF" IS 'Secuencia para la interfaz';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."CMAPEAD" IS 'Código del mapeador';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."SMAPEAD" IS 'Secuencia del mapeador';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."NLINEA" IS 'Número de linea';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."RAMO" IS 'Número de Ramo';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."ANYO" IS 'Año de la Póliza';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."POLIZA" IS 'Número de la Póliza';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."CERTIFICADO" IS 'Número de Certificado';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."RECIBO" IS 'Número de Recibo';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."PRIMA" IS 'Prima del Recibo';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."RECARGO" IS 'Recargo del Recibo';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."IMPUESTOS" IS 'Impuestos del Recibo';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."INDICADORRECIBOEXTORNO" IS 'Indicador del Recibo';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."FECHAPASOEXIGIBLE" IS 'Fecha Pagos Exigible';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."FECHAEFECTO" IS 'Fecha Efecto del Recibo';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."TIPORECIBO" IS 'Tipo de Recibo';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."COMISIONLIQUIDACION" IS 'Comisión del Recibo';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."PORCENTAJECOMISION" IS 'Porcentaje de Comisión';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."RESERVADO_1" IS 'Campo Reservado';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."COMISIONASIGNADA" IS 'Comisión Asignada';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."ESTADORECIBO" IS 'Estado del Recibo';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."FECHAVENCIMIENTO" IS 'Fecha vencimiento del Recibo';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."FECHAESTADO" IS 'Fecha estado del Recibo';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."NUMEROCLIENTE" IS 'Número del Cliente';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."GRUPOCLIENTE" IS 'Grupo del Cliente';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."NOMBRE" IS 'Nombre del Cliente';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."DNICIF" IS 'Identificador del cliente';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."TIPODOCUMENTO" IS 'Tipo de Identificador';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."NOMBREASEGURADO" IS 'Nombre del Asegurado';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."DNICIFASEGURADO" IS 'Identificador del Asegurado';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."TIPODOCUMENTOASEGURADO" IS 'Tipo Identificador del Asegurado';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."BANCO" IS 'Banco';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."SUCURSAL" IS 'Sucursal';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."CUENTABANCARIA" IS 'Cuenta Bancaria';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."TIPO_OPER" IS 'Tipo de operación';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."CRECCIA" IS 'Identificador de recibo de la Compñia';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."NCARGA" IS 'Número de Carga';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_ASEFA"."PROCESO" IS 'Id. proceso';
  GRANT UPDATE ON "AXIS"."INT_RECIBOS_ASEFA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_RECIBOS_ASEFA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_RECIBOS_ASEFA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_RECIBOS_ASEFA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_RECIBOS_ASEFA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_RECIBOS_ASEFA" TO "PROGRAMADORESCSI";
