--------------------------------------------------------
--  DDL for Table INT_POLIZAS_ALLIANZ
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_POLIZAS_ALLIANZ" 
   (	"SINTERF" NUMBER, 
	"CMAPEAD" VARCHAR2(5 BYTE), 
	"SMAPEAD" NUMBER, 
	"NLINEA" NUMBER(6,0), 
	"SUCURSAL" NUMBER(3,0), 
	"AGENTE" NUMBER, 
	"COLABORADOR" NUMBER(4,0), 
	"RAMO" NUMBER(4,0), 
	"POLIZA" NUMBER(9,0), 
	"APLICACION" NUMBER(5,0), 
	"NOM_TOMADOR" VARCHAR2(30 BYTE), 
	"DOM_TOMADOR" VARCHAR2(30 BYTE), 
	"CPOSTAL_TOMADOR" NUMBER(5,0), 
	"LOCALIDAD_TOMADOR" VARCHAR2(25 BYTE), 
	"TLF_TOMADOR" NUMBER(10,0), 
	"NIF_TOMADOR" VARCHAR2(9 BYTE), 
	"PROFESION_TOMADOR" VARCHAR2(2 BYTE), 
	"FH_NACIMIENTO_TOMADOR" VARCHAR2(10 BYTE), 
	"FH_CARNET_TOMADOR" VARCHAR2(10 BYTE), 
	"NOM_PROPIETARIO" VARCHAR2(30 BYTE), 
	"DOM_PROPIETARIO" VARCHAR2(30 BYTE), 
	"CPOSTAL_PROPIETARIO" NUMBER(5,0), 
	"LOCALIDAD_PROPIETARIO" VARCHAR2(25 BYTE), 
	"TLF_PROPIETARIO" NUMBER(10,0), 
	"NIF_PROPIETARIO" VARCHAR2(9 BYTE), 
	"PROFESION_PROPIETARIO" VARCHAR2(2 BYTE), 
	"FH_NACIMIENTO_PROPIETARIO" VARCHAR2(10 BYTE), 
	"FH_CARNET_PROPIETARIO" VARCHAR2(10 BYTE), 
	"FH_EMISION" VARCHAR2(10 BYTE), 
	"FH_EFECTO" VARCHAR2(10 BYTE), 
	"FH_VENCIMIENTO" VARCHAR2(10 BYTE), 
	"FH_ANULACION" VARCHAR2(10 BYTE), 
	"DURACION" VARCHAR2(6 BYTE), 
	"FORMA_DE_PAGO" VARCHAR2(13 BYTE), 
	"NOM_BANCO" VARCHAR2(30 BYTE), 
	"COD_BANCO" NUMBER(4,0), 
	"OFIC_BANCO" NUMBER(4,0), 
	"DIG_CONTROL" NUMBER(2,0), 
	"CTA_BANCO" NUMBER(10,0), 
	"TIPO" VARCHAR2(9 BYTE), 
	"RIESGO" VARCHAR2(59 BYTE), 
	"COD_SUBRAMO_S1" NUMBER(4,0), 
	"PRIMA_NETA_S1" NUMBER, 
	"COD_SUBRAMO_S2" NUMBER(4,0), 
	"PRIMA_NETA_S2" NUMBER, 
	"COD_SUBRAMO_S3" NUMBER(4,0), 
	"PRIMA_NETA_S3" NUMBER, 
	"DESC_COBER_C1" VARCHAR2(15 BYTE), 
	"VALOR_COBER_C1" NUMBER, 
	"DESC_COBER_C2" VARCHAR2(15 BYTE), 
	"VALOR_COBER_C2" NUMBER, 
	"DESC_COBER_C3" VARCHAR2(15 BYTE), 
	"VALOR_COBER_C3" NUMBER, 
	"DESC_COBER_C4" VARCHAR2(15 BYTE), 
	"VALOR_COBER_C4" NUMBER, 
	"DESC_COBER_C5" VARCHAR2(15 BYTE), 
	"VALOR_COBER_C5" NUMBER, 
	"DESC_COBER_C6" VARCHAR2(15 BYTE), 
	"VALOR_COBER_C6" NUMBER, 
	"DESC_COBER_C7" VARCHAR2(15 BYTE), 
	"VALOR_COBER_C7" NUMBER, 
	"DESC_COBER_C8" VARCHAR2(15 BYTE), 
	"VALOR_COBER_C8" NUMBER, 
	"POLIZA_REEMP" NUMBER(9,0), 
	"APLICACION_REEMP" NUMBER(5,0), 
	"NCARGA" NUMBER, 
	"TIPO_OPER" VARCHAR2(4 BYTE), 
	"PROCESO" NUMBER(6,0), 
	"IBAN" VARCHAR2(24 BYTE), 
	"BIC" VARCHAR2(11 BYTE), 
	"AUTORIZACION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."SINTERF" IS 'Secuencia para la interfaz';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."CMAPEAD" IS 'Código de map de carga';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."SMAPEAD" IS 'Secuencia de interfaz de carga';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."NLINEA" IS 'Línea del registro del fichero de carga';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."SUCURSAL" IS 'Código de sucursal';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."AGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."COLABORADOR" IS 'Código de colaborador';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."RAMO" IS 'Código de ramo. Corresponde a la actividad';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."POLIZA" IS 'Nº póliza compañia';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."APLICACION" IS 'Código de aplicacion de carga';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."NOM_TOMADOR" IS 'Nombre tomador de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."DOM_TOMADOR" IS 'Domicilio tomador de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."CPOSTAL_TOMADOR" IS 'Código postal tomador de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."LOCALIDAD_TOMADOR" IS 'Código localidad tomador de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."TLF_TOMADOR" IS 'Teléfono tomador de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."NIF_TOMADOR" IS 'NIF tomador de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."PROFESION_TOMADOR" IS 'Código profesión tomador de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."FH_NACIMIENTO_TOMADOR" IS 'Fecha nacimiento tomador de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."FH_CARNET_TOMADOR" IS 'Fecha carnet tomador de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."NOM_PROPIETARIO" IS 'Nombre propietario de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."DOM_PROPIETARIO" IS 'Domicilio propietario de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."CPOSTAL_PROPIETARIO" IS 'Código postal propietario de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."LOCALIDAD_PROPIETARIO" IS 'Código localidad propietario de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."TLF_PROPIETARIO" IS 'Teléfono propietario de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."NIF_PROPIETARIO" IS 'NIF propietario de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."PROFESION_PROPIETARIO" IS 'Código profesión propietario de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."FH_NACIMIENTO_PROPIETARIO" IS 'Fecha nacimiento propietario de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."FH_CARNET_PROPIETARIO" IS 'Fecha carnet propietario de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."FH_EMISION" IS 'Fecha emisión de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."FH_EFECTO" IS 'Fecha efecto de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."FH_VENCIMIENTO" IS 'Fecha vto. de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."FH_ANULACION" IS 'Fecha anulación de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."DURACION" IS 'Duración de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."FORMA_DE_PAGO" IS 'Forma de pago de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."NOM_BANCO" IS 'Nombre del banco domic. póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."COD_BANCO" IS 'Código del banco domic. póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."OFIC_BANCO" IS 'Oficina del banco domic. póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."DIG_CONTROL" IS 'Digito de control cta. banco domic. póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."CTA_BANCO" IS 'Cta. banco domic. póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."TIPO" IS 'Desc. ramo póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."RIESGO" IS 'Desc. riesgo póliza';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."COD_SUBRAMO_S1" IS 'Código subramo s1';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."PRIMA_NETA_S1" IS 'Prima subramo s1';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."COD_SUBRAMO_S2" IS 'Código subramo s2';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."PRIMA_NETA_S2" IS 'Prima subramo s2';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."COD_SUBRAMO_S3" IS 'Código subramo s3';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."PRIMA_NETA_S3" IS 'Prima subramo s3';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."DESC_COBER_C1" IS 'Desc cobertura c1';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."VALOR_COBER_C1" IS 'Valor cobertura c1';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."DESC_COBER_C2" IS 'Desc cobertura c2';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."VALOR_COBER_C2" IS 'Valor cobertura c2';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."DESC_COBER_C3" IS 'Desc cobertura c3';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."VALOR_COBER_C3" IS 'Valor cobertura c3';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."DESC_COBER_C4" IS 'Desc cobertura c4';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."VALOR_COBER_C4" IS 'Valor cobertura c4';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."DESC_COBER_C5" IS 'Desc cobertura c5';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."VALOR_COBER_C5" IS 'Valor cobertura c5';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."DESC_COBER_C6" IS 'Desc cobertura c6';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."VALOR_COBER_C6" IS 'Valor cobertura c6';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."DESC_COBER_C7" IS 'Desc cobertura c7';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."VALOR_COBER_C7" IS 'Valor cobertura c7';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."DESC_COBER_C8" IS 'Desc cobertura c8';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."VALOR_COBER_C8" IS 'Valor cobertura c8';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."POLIZA_REEMP" IS 'Poliza reemplazo';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."APLICACION_REEMP" IS 'Aplicación reemplazo';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."NCARGA" IS 'Nº carga';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."TIPO_OPER" IS 'Campo calculado tipo operación a realizar.';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."PROCESO" IS 'Id. proceso';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."IBAN" IS 'Codigo IBAN';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."BIC" IS 'Codigo BIC';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_ALLIANZ"."AUTORIZACION" IS 'Codigo Autorizacion';
   COMMENT ON TABLE "AXIS"."INT_POLIZAS_ALLIANZ"  IS 'Origen datos cargas pólizas Allianz';
  GRANT UPDATE ON "AXIS"."INT_POLIZAS_ALLIANZ" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_POLIZAS_ALLIANZ" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_POLIZAS_ALLIANZ" TO "PROGRAMADORESCSI";
  GRANT INSERT ON "AXIS"."INT_POLIZAS_ALLIANZ" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_POLIZAS_ALLIANZ" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_POLIZAS_ALLIANZ" TO "CONF_DWH";
