--------------------------------------------------------
--  DDL for Table INT_SINIESTROS_ASEFA
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_SINIESTROS_ASEFA" 
   (	"SINTERF" NUMBER, 
	"CMAPEAD" VARCHAR2(5 BYTE), 
	"SMAPEAD" NUMBER, 
	"NLINEA" NUMBER(6,0), 
	"RAMO" NUMBER(2,0), 
	"ANYO" NUMBER(4,0), 
	"POLIZA" NUMBER(6,0), 
	"CERTIFICADO" NUMBER(5,0), 
	"ANYOSINIESTRO" NUMBER(4,0), 
	"NSINIESTRO" NUMBER(6,0), 
	"FECHAAPERTURA" VARCHAR2(8 BYTE), 
	"FECHACIERRE" VARCHAR2(8 BYTE), 
	"RESERVADO_1" VARCHAR2(1 BYTE), 
	"ESTADOSINIESTRO" VARCHAR2(1 BYTE), 
	"TOTALPROVISIONES" NUMBER, 
	"TOTALPAGOS" NUMBER, 
	"TOTALRECOBROS" NUMBER, 
	"TIPO_OPER" VARCHAR2(10 BYTE), 
	"CSINCIA" VARCHAR2(50 BYTE), 
	"NCARGA" NUMBER, 
	"PROCESO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."SINTERF" IS 'Secuencia para la interfaz';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."CMAPEAD" IS 'Código del mapeador';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."SMAPEAD" IS 'Secuencia del mapeador';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."NLINEA" IS 'Número de linea';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."RAMO" IS 'Número de Ramo';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."ANYO" IS 'Año de la Póliza';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."POLIZA" IS 'Número de la Póliza';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."CERTIFICADO" IS 'Número de Certificado';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."ANYOSINIESTRO" IS 'Año del Siniestro';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."NSINIESTRO" IS 'Número del Siniestro';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."FECHAAPERTURA" IS 'Fecha de Apertura del Siniestro';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."FECHACIERRE" IS 'Fecha de Cierre del Siniestro';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."RESERVADO_1" IS 'Campo Reservado';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."ESTADOSINIESTRO" IS 'Estado del Siniestro';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."TOTALPROVISIONES" IS 'Importe total de Provisiones';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."TOTALPAGOS" IS 'Importe total de Pagos';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."TOTALRECOBROS" IS 'Importe total de Recobros';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."TIPO_OPER" IS 'Tipo de Operación';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."CSINCIA" IS 'Código del Siniestro de la Compañia';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."NCARGA" IS 'Número de Carga';
   COMMENT ON COLUMN "AXIS"."INT_SINIESTROS_ASEFA"."PROCESO" IS 'Id. proceso';
   COMMENT ON TABLE "AXIS"."INT_SINIESTROS_ASEFA"  IS 'Tabla para cargar los Sineistros enviados por ASEFA';
  GRANT UPDATE ON "AXIS"."INT_SINIESTROS_ASEFA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_SINIESTROS_ASEFA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_SINIESTROS_ASEFA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_SINIESTROS_ASEFA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_SINIESTROS_ASEFA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_SINIESTROS_ASEFA" TO "PROGRAMADORESCSI";
