--------------------------------------------------------
--  DDL for Table INT_BCO_HELM_RESPNOTIFS
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_BCO_HELM_RESPNOTIFS" 
   (	"SINTERF" NUMBER, 
	"NLINEA" NUMBER, 
	"CFECENVI" VARCHAR2(200 BYTE), 
	"CNUTTITU" VARCHAR2(200 BYTE), 
	"CNUMPROC" VARCHAR2(200 BYTE), 
	"CCONSENV" VARCHAR2(200 BYTE), 
	"CNOMTITU" VARCHAR2(200 BYTE), 
	"CCODIBCO" VARCHAR2(200 BYTE), 
	"CTIPOCTA" VARCHAR2(200 BYTE), 
	"CNUMECTA" VARCHAR2(200 BYTE), 
	"CTIPMATRI" VARCHAR2(200 BYTE), 
	"CNITLIBE" VARCHAR2(200 BYTE), 
	"CCODIERR" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_BCO_HELM_RESPNOTIFS"."CFECENVI" IS 'Fecha de notificación del resultado de la prenotificación';
   COMMENT ON COLUMN "AXIS"."INT_BCO_HELM_RESPNOTIFS"."CNUTTITU" IS 'Nit del Titular Cuenta a Prenotificar';
   COMMENT ON COLUMN "AXIS"."INT_BCO_HELM_RESPNOTIFS"."CNUMPROC" IS 'Numero de Proceso';
   COMMENT ON COLUMN "AXIS"."INT_BCO_HELM_RESPNOTIFS"."CCONSENV" IS 'Numero de Recibo';
   COMMENT ON COLUMN "AXIS"."INT_BCO_HELM_RESPNOTIFS"."CNOMTITU" IS 'Nombre Titular Cuenta a Prenotificar';
   COMMENT ON COLUMN "AXIS"."INT_BCO_HELM_RESPNOTIFS"."CCODIBCO" IS 'Código de Banco ';
   COMMENT ON COLUMN "AXIS"."INT_BCO_HELM_RESPNOTIFS"."CTIPOCTA" IS 'Tipo de Cuenta';
   COMMENT ON COLUMN "AXIS"."INT_BCO_HELM_RESPNOTIFS"."CNUMECTA" IS 'Numero Cuenta ';
   COMMENT ON COLUMN "AXIS"."INT_BCO_HELM_RESPNOTIFS"."CTIPMATRI" IS 'Tipo de Matricula';
   COMMENT ON COLUMN "AXIS"."INT_BCO_HELM_RESPNOTIFS"."CNITLIBE" IS 'Nit Liberty';
   COMMENT ON COLUMN "AXIS"."INT_BCO_HELM_RESPNOTIFS"."CCODIERR" IS 'Código de Error';
   COMMENT ON TABLE "AXIS"."INT_BCO_HELM_RESPNOTIFS"  IS 'Almacenamiento de las respuestas de las notificaciones (de domiciliaciones) efectuadas por el Banco HELM';
  GRANT UPDATE ON "AXIS"."INT_BCO_HELM_RESPNOTIFS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_BCO_HELM_RESPNOTIFS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_BCO_HELM_RESPNOTIFS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_BCO_HELM_RESPNOTIFS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_BCO_HELM_RESPNOTIFS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_BCO_HELM_RESPNOTIFS" TO "PROGRAMADORESCSI";
