--------------------------------------------------------
--  DDL for Table INT_HOSTB2B
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_HOSTB2B" 
   (	"EMPRESA" VARCHAR2(100 BYTE), 
	"CINTERF" VARCHAR2(4 BYTE), 
	"ACTIVO" VARCHAR2(1 BYTE), 
	"PROTOCOLO" VARCHAR2(20 BYTE), 
	"URL" VARCHAR2(500 BYTE), 
	"SSL" VARCHAR2(2 BYTE), 
	"METODO" VARCHAR2(10 BYTE), 
	"HTTPVERSION" VARCHAR2(10 BYTE), 
	"CONTENTTYPE" VARCHAR2(100 BYTE), 
	"SOAPACTION" VARCHAR2(50 BYTE), 
	"USERAUTHENT" VARCHAR2(20 BYTE), 
	"PASSAUTHENT" VARCHAR2(20 BYTE), 
	"TESCAPE" VARCHAR2(20 BYTE), 
	"NTIMEOUT" NUMBER(4,0), 
	"VERNS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_HOSTB2B"."EMPRESA" IS 'Empresa con la que se mantien la comunicación';
   COMMENT ON COLUMN "AXIS"."INT_HOSTB2B"."CINTERF" IS 'Código del servicio';
   COMMENT ON COLUMN "AXIS"."INT_HOSTB2B"."ACTIVO" IS 'Indica si la comunicación está activa o si está bloqueada';
   COMMENT ON COLUMN "AXIS"."INT_HOSTB2B"."PROTOCOLO" IS 'Protocolo usado en la comunicación (SOAP,...)';
   COMMENT ON COLUMN "AXIS"."INT_HOSTB2B"."URL" IS 'Url a la que se envía';
   COMMENT ON COLUMN "AXIS"."INT_HOSTB2B"."SSL" IS 'Servidor seguro (1.-Sí, 0.-No)';
   COMMENT ON COLUMN "AXIS"."INT_HOSTB2B"."METODO" IS 'Post o Get';
   COMMENT ON COLUMN "AXIS"."INT_HOSTB2B"."HTTPVERSION" IS 'Versión de http';
   COMMENT ON COLUMN "AXIS"."INT_HOSTB2B"."CONTENTTYPE" IS 'Tipo del contenido';
   COMMENT ON COLUMN "AXIS"."INT_HOSTB2B"."SOAPACTION" IS 'Acción en el caso de usar protocolo SOAP';
   COMMENT ON COLUMN "AXIS"."INT_HOSTB2B"."USERAUTHENT" IS 'Usuario con el que nos conectamos';
   COMMENT ON COLUMN "AXIS"."INT_HOSTB2B"."PASSAUTHENT" IS 'Password para la conexión';
   COMMENT ON COLUMN "AXIS"."INT_HOSTB2B"."NTIMEOUT" IS 'Time Out en segundos';
   COMMENT ON COLUMN "AXIS"."INT_HOSTB2B"."VERNS" IS 'Versión del Namespace del xml.';
  GRANT UPDATE ON "AXIS"."INT_HOSTB2B" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_HOSTB2B" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_HOSTB2B" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_HOSTB2B" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_HOSTB2B" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_HOSTB2B" TO "PROGRAMADORESCSI";
