--------------------------------------------------------
--  DDL for Table INT_CARGA_GENERICOCARTERA
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_CARGA_GENERICOCARTERA" 
   (	"PROCESO" NUMBER, 
	"NLINEA" NUMBER(9,0), 
	"NCARGA" NUMBER, 
	"TIPO_OPER" VARCHAR2(10 BYTE), 
	"TIPOREGISTRO" VARCHAR2(10 BYTE), 
	"CAMPO01" VARCHAR2(4000 BYTE), 
	"CAMPO02" VARCHAR2(4000 BYTE), 
	"CAMPO03" VARCHAR2(4000 BYTE), 
	"CAMPO04" VARCHAR2(4000 BYTE), 
	"CAMPO05" VARCHAR2(4000 BYTE), 
	"CAMPO06" VARCHAR2(4000 BYTE), 
	"CAMPO07" VARCHAR2(4000 BYTE), 
	"CAMPO08" VARCHAR2(4000 BYTE), 
	"CAMPO09" VARCHAR2(4000 BYTE), 
	"CAMPO10" VARCHAR2(4000 BYTE), 
	"CAMPO11" VARCHAR2(4000 BYTE), 
	"CAMPO12" VARCHAR2(4000 BYTE), 
	"CAMPO13" VARCHAR2(4000 BYTE), 
	"CAMPO14" VARCHAR2(4000 BYTE), 
	"CAMPO15" VARCHAR2(4000 BYTE), 
	"CAMPO16" VARCHAR2(4000 BYTE), 
	"CAMPO17" VARCHAR2(4000 BYTE), 
	"CAMPO18" VARCHAR2(4000 BYTE), 
	"CAMPO19" VARCHAR2(4000 BYTE), 
	"CAMPO20" VARCHAR2(4000 BYTE), 
	"CAMPO21" VARCHAR2(4000 BYTE), 
	"CAMPO22" VARCHAR2(4000 BYTE), 
	"CAMPO23" VARCHAR2(4000 BYTE), 
	"CAMPO24" VARCHAR2(4000 BYTE), 
	"CAMPO25" VARCHAR2(4000 BYTE), 
	"CAMPO26" VARCHAR2(4000 BYTE), 
	"CAMPO27" VARCHAR2(4000 BYTE), 
	"CAMPO28" VARCHAR2(4000 BYTE), 
	"CAMPO29" VARCHAR2(4000 BYTE), 
	"CAMPO30" VARCHAR2(4000 BYTE), 
	"CAMPO31" VARCHAR2(4000 BYTE), 
	"CAMPO32" VARCHAR2(4000 BYTE), 
	"CAMPO33" VARCHAR2(4000 BYTE), 
	"CAMPO34" VARCHAR2(4000 BYTE), 
	"CAMPO35" VARCHAR2(4000 BYTE), 
	"CAMPO36" VARCHAR2(4000 BYTE), 
	"CAMPO37" VARCHAR2(4000 BYTE), 
	"CAMPO38" VARCHAR2(4000 BYTE), 
	"CAMPO39" VARCHAR2(4000 BYTE), 
	"CAMPO40" VARCHAR2(4000 BYTE), 
	"CAMPO41" VARCHAR2(4000 BYTE), 
	"CAMPO42" VARCHAR2(4000 BYTE), 
	"CAMPO43" VARCHAR2(4000 BYTE), 
	"CAMPO44" VARCHAR2(4000 BYTE), 
	"CAMPO45" VARCHAR2(4000 BYTE), 
	"CAMPO46" VARCHAR2(4000 BYTE), 
	"CAMPO47" VARCHAR2(4000 BYTE), 
	"CAMPO48" VARCHAR2(4000 BYTE), 
	"CAMPO49" VARCHAR2(4000 BYTE), 
	"CAMPO50" VARCHAR2(4000 BYTE), 
	"CAMPO51" VARCHAR2(4000 BYTE), 
	"CAMPO52" VARCHAR2(4000 BYTE), 
	"CAMPO53" VARCHAR2(4000 BYTE), 
	"CAMPO54" VARCHAR2(4000 BYTE), 
	"CAMPO55" VARCHAR2(4000 BYTE), 
	"CAMPO56" VARCHAR2(4000 BYTE), 
	"CAMPO57" VARCHAR2(4000 BYTE), 
	"CAMPO58" VARCHAR2(4000 BYTE), 
	"CAMPO59" VARCHAR2(4000 BYTE), 
	"CAMPO60" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."PROCESO" IS 'Id. proceso';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."NLINEA" IS 'N¿mero linea carga fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."NCARGA" IS 'N¿mero carga asociada';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."TIPO_OPER" IS 'Tipo de operaci¿n a realizas Alta/baja/modificaci¿n';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."TIPOREGISTRO" IS 'Tipo registro a procesar';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO01" IS 'Campo 01 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO02" IS 'Campo 02 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO03" IS 'Campo 03 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO04" IS 'Campo 04 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO05" IS 'Campo 05 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO06" IS 'Campo 06 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO07" IS 'Campo 07 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO08" IS 'Campo 08 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO09" IS 'Campo 09 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO10" IS 'Campo 10 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO11" IS 'Campo 11 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO12" IS 'Campo 12 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO13" IS 'Campo 13 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO14" IS 'Campo 14 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO15" IS 'Campo 15 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO16" IS 'Campo 16 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO17" IS 'Campo 17 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO18" IS 'Campo 18 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO19" IS 'Campo 19 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO20" IS 'Campo 20 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO21" IS 'Campo 21 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO22" IS 'Campo 22 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO23" IS 'Campo 23 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO24" IS 'Campo 24 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO25" IS 'Campo 25 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO26" IS 'Campo 26 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO27" IS 'Campo 27 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO28" IS 'Campo 28 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO29" IS 'Campo 29 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO30" IS 'Campo 30 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO31" IS 'Campo 31 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO32" IS 'Campo 32 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO33" IS 'Campo 33 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO34" IS 'Campo 34 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO35" IS 'Campo 35 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO36" IS 'Campo 36 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO37" IS 'Campo 37 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO38" IS 'Campo 38 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO39" IS 'Campo 39 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO40" IS 'Campo 40 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO41" IS 'Campo 41 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO42" IS 'Campo 42 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO43" IS 'Campo 43 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO44" IS 'Campo 44 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO45" IS 'Campo 45 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO46" IS 'Campo 46 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO47" IS 'Campo 47 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO48" IS 'Campo 48 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO49" IS 'Campo 49 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO50" IS 'Campo 50 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO51" IS 'Campo 51 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO52" IS 'Campo 52 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO53" IS 'Campo 53 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO54" IS 'Campo 54 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO55" IS 'Campo 55 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO56" IS 'Campo 56 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO57" IS 'Campo 57 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO58" IS 'Campo 58 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO59" IS 'Campo 59 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_GENERICOCARTERA"."CAMPO60" IS 'Campo 60 con datos del fichero';
   COMMENT ON TABLE "AXIS"."INT_CARGA_GENERICOCARTERA"  IS 'Interface carga datos genericos.';
  GRANT UPDATE ON "AXIS"."INT_CARGA_GENERICOCARTERA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_CARGA_GENERICOCARTERA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_CARGA_GENERICOCARTERA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_CARGA_GENERICOCARTERA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_CARGA_GENERICOCARTERA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_CARGA_GENERICOCARTERA" TO "PROGRAMADORESCSI";
