--------------------------------------------------------
--  DDL for Table INT_FIN_PAIS_RIESGO
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_FIN_PAIS_RIESGO" 
   (	"SPROCES" NUMBER, 
	"NLINEA" NUMBER, 
	"NCARGA" NUMBER, 
	"CPAIS" NUMBER, 
	"NCALPRO" NUMBER, 
	"NPFISCAL" NUMBER, 
	"NLROJA" NUMBER, 
	"NLNEGRA" NUMBER, 
	"NLGRISO" NUMBER, 
	"NLGRIS" NUMBER, 
	"NLGAFI" NUMBER, 
	"CRATIN1" VARCHAR2(10 BYTE), 
	"CRATIN2" VARCHAR2(10 BYTE), 
	"CRATIN3" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_FIN_PAIS_RIESGO"."SPROCES" IS 'Numero de proceso';
   COMMENT ON COLUMN "AXIS"."INT_FIN_PAIS_RIESGO"."NLINEA" IS 'Numero l¿nea fichero';
   COMMENT ON COLUMN "AXIS"."INT_FIN_PAIS_RIESGO"."NCARGA" IS 'Carga';
   COMMENT ON COLUMN "AXIS"."INT_FIN_PAIS_RIESGO"."CPAIS" IS 'Pa¿s';
   COMMENT ON COLUMN "AXIS"."INT_FIN_PAIS_RIESGO"."NCALPRO" IS 'Calificaci¿n Propia';
   COMMENT ON COLUMN "AXIS"."INT_FIN_PAIS_RIESGO"."NPFISCAL" IS 'Para¿so Fiscal';
   COMMENT ON COLUMN "AXIS"."INT_FIN_PAIS_RIESGO"."NLROJA" IS 'Lista Roja';
   COMMENT ON COLUMN "AXIS"."INT_FIN_PAIS_RIESGO"."NLNEGRA" IS 'Lista Negra';
   COMMENT ON COLUMN "AXIS"."INT_FIN_PAIS_RIESGO"."NLGRISO" IS 'Lista Gris Oscurecida';
   COMMENT ON COLUMN "AXIS"."INT_FIN_PAIS_RIESGO"."NLGRIS" IS 'Lista Gris';
   COMMENT ON COLUMN "AXIS"."INT_FIN_PAIS_RIESGO"."NLGAFI" IS 'Lista GAFI';
   COMMENT ON COLUMN "AXIS"."INT_FIN_PAIS_RIESGO"."CRATIN1" IS 'Rating Moddys';
   COMMENT ON COLUMN "AXIS"."INT_FIN_PAIS_RIESGO"."CRATIN2" IS 'Rating SP';
   COMMENT ON COLUMN "AXIS"."INT_FIN_PAIS_RIESGO"."CRATIN3" IS 'Rating FITCH';
  GRANT UPDATE ON "AXIS"."INT_FIN_PAIS_RIESGO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_FIN_PAIS_RIESGO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_FIN_PAIS_RIESGO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_FIN_PAIS_RIESGO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_FIN_PAIS_RIESGO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_FIN_PAIS_RIESGO" TO "PROGRAMADORESCSI";
