--------------------------------------------------------
--  DDL for Table INT_BCO_ACH_RESPNOTIFS
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_BCO_ACH_RESPNOTIFS" 
   (	"SINTERF" NUMBER, 
	"NLINEA" NUMBER, 
	"CRECAUDO" VARCHAR2(200 BYTE), 
	"CDESTINA" VARCHAR2(200 BYTE), 
	"CDESTINO" VARCHAR2(200 BYTE), 
	"CNUMECTA" VARCHAR2(200 BYTE), 
	"CTIPOCTA" VARCHAR2(200 BYTE), 
	"CCODENTI" VARCHAR2(200 BYTE), 
	"CNOMENTI" VARCHAR2(200 BYTE), 
	"CTIPTRAN" VARCHAR2(200 BYTE), 
	"CFDEBITO" VARCHAR2(200 BYTE), 
	"CFMAPLIC" VARCHAR2(200 BYTE), 
	"CCODIEAN" VARCHAR2(200 BYTE), 
	"CREFERE1" VARCHAR2(200 BYTE), 
	"CDESCRIP" VARCHAR2(200 BYTE), 
	"CVALORDB" VARCHAR2(200 BYTE), 
	"CESTADO" VARCHAR2(200 BYTE), 
	"CRECHAZO" VARCHAR2(200 BYTE), 
	"CCAUSALR" VARCHAR2(200 BYTE), 
	"CCOMPROB" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."SINTERF" IS 'Num. IFS';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."NLINEA" IS 'Núm. Línea';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CRECAUDO" IS 'Cuenta recaudadora';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CDESTINA" IS 'Destinatario';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CDESTINO" IS 'NIT Destinatario';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CNUMECTA" IS 'Cuenta Destino';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CTIPOCTA" IS 'Tipo de cuenta';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CCODENTI" IS 'Cod. Entidad Destino';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CNOMENTI" IS 'Nombre Entidad Destino';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CTIPTRAN" IS 'Tipo Transacción';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CFDEBITO" IS 'Fecha del débito';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CFMAPLIC" IS 'Forma Aplicación';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CCODIEAN" IS 'EAN 13';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CREFERE1" IS 'REferencia 1';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CDESCRIP" IS 'Descripción';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CVALORDB" IS 'Valor a debitar';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CESTADO" IS 'Estado';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CRECHAZO" IS 'Código causa rechazo';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CCAUSALR" IS 'Concepto de rechazo';
   COMMENT ON COLUMN "AXIS"."INT_BCO_ACH_RESPNOTIFS"."CCOMPROB" IS 'Número comprobante';
   COMMENT ON TABLE "AXIS"."INT_BCO_ACH_RESPNOTIFS"  IS 'Almacenamiento de las respuestas de las notificaciones (de domiciliaciones) efectuadas por el Banco ACH';
  GRANT UPDATE ON "AXIS"."INT_BCO_ACH_RESPNOTIFS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_BCO_ACH_RESPNOTIFS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_BCO_ACH_RESPNOTIFS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_BCO_ACH_RESPNOTIFS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_BCO_ACH_RESPNOTIFS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_BCO_ACH_RESPNOTIFS" TO "PROGRAMADORESCSI";
