--------------------------------------------------------
--  DDL for Table INT_CARGA_INFORMACOL
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_CARGA_INFORMACOL" 
   (	"PROCESO" NUMBER, 
	"NLINEA" NUMBER(9,0), 
	"NCARGA" NUMBER, 
	"TIPO_OPER" VARCHAR2(10 BYTE), 
	"NIT" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(4000 BYTE), 
	"TIPOSOCIEDAD" VARCHAR2(4000 BYTE), 
	"REPRELEGAL" VARCHAR2(4000 BYTE), 
	"REVFISCAL" VARCHAR2(4000 BYTE), 
	"ESTEMPRESA" VARCHAR2(4000 BYTE), 
	"OBJSOCIAL" VARCHAR2(4000 BYTE), 
	"FECHACONS" VARCHAR2(4000 BYTE), 
	"VIGSOCIEDAD" VARCHAR2(4000 BYTE), 
	"LIMREPLEGAL" VARCHAR2(4000 BYTE), 
	"INCJUDICIAL" VARCHAR2(4000 BYTE), 
	"NOMACCIONISTA1" VARCHAR2(4000 BYTE), 
	"NOMACCIONISTA2" VARCHAR2(4000 BYTE), 
	"NOMACCIONISTA3" VARCHAR2(4000 BYTE), 
	"NOMACCIONISTA4" VARCHAR2(4000 BYTE), 
	"NITACCIONISTA1" VARCHAR2(4000 BYTE), 
	"NITACCIONISTA2" VARCHAR2(4000 BYTE), 
	"NITACCIONISTA3" VARCHAR2(4000 BYTE), 
	"NITACCIONISTA4" VARCHAR2(4000 BYTE), 
	"PARTACCIONISTA1" VARCHAR2(4000 BYTE), 
	"PARTACCIONISTA2" VARCHAR2(4000 BYTE), 
	"PARTACCIONISTA3" VARCHAR2(4000 BYTE), 
	"PARTACCIONISTA4" VARCHAR2(4000 BYTE), 
	"CIIU" VARCHAR2(4000 BYTE), 
	"FUENTEINF" VARCHAR2(4000 BYTE), 
	"MONEDA" VARCHAR2(4000 BYTE), 
	"VALMILES" VARCHAR2(4000 BYTE), 
	"FECESTFINAN" VARCHAR2(4000 BYTE), 
	"VENTAS" VARCHAR2(4000 BYTE), 
	"VENTASPERANT" VARCHAR2(4000 BYTE), 
	"COSTOVENTAS" VARCHAR2(4000 BYTE), 
	"GASTOSADM" VARCHAR2(4000 BYTE), 
	"UTLOPERACIONAL" VARCHAR2(4000 BYTE), 
	"GASTOSFINAN" VARCHAR2(4000 BYTE), 
	"RESULTANTIMP" VARCHAR2(4000 BYTE), 
	"UTLNETA" VARCHAR2(4000 BYTE), 
	"INVENTARIO" VARCHAR2(4000 BYTE), 
	"CARTCLIENTE" VARCHAR2(4000 BYTE), 
	"ACTCORRIENTE" VARCHAR2(4000 BYTE), 
	"TOTACTNOCORRIENTE" VARCHAR2(4000 BYTE), 
	"PROPPLANEQUIPO" VARCHAR2(4000 BYTE), 
	"OTROSACTIVOS" VARCHAR2(4000 BYTE), 
	"ACTIVOTOTAL" VARCHAR2(4000 BYTE), 
	"OBLIGFINANCP" VARCHAR2(4000 BYTE), 
	"PROVEEDORESCP" VARCHAR2(4000 BYTE), 
	"ANTICIPOCP" VARCHAR2(4000 BYTE), 
	"PASCORRIENTE" VARCHAR2(4000 BYTE), 
	"OBLIGFINANLP" VARCHAR2(4000 BYTE), 
	"ANTICIPOLP" VARCHAR2(4000 BYTE), 
	"TOTPASCORRIENTE" VARCHAR2(4000 BYTE), 
	"PASTOTAL" VARCHAR2(4000 BYTE), 
	"PATRIPERANT" VARCHAR2(4000 BYTE), 
	"PATRIANOACT" VARCHAR2(4000 BYTE), 
	"CAPSOCIAL" VARCHAR2(4000 BYTE), 
	"PRICOLACC" VARCHAR2(4000 BYTE), 
	"INVSUPLCAP" VARCHAR2(4000 BYTE), 
	"RESLEGAL" VARCHAR2(4000 BYTE), 
	"RESOCASIONAL" VARCHAR2(4000 BYTE), 
	"RESEJERANT" VARCHAR2(4000 BYTE), 
	"VALORIZACION" VARCHAR2(4000 BYTE), 
	"FECCAMCOMERCIO" VARCHAR2(4000 BYTE), 
	"FOTRUT" VARCHAR2(4000 BYTE), 
	"FECRUT" VARCHAR2(4000 BYTE), 
	"FOTCEDULA" VARCHAR2(4000 BYTE), 
	"FECEXPCEDULA" VARCHAR2(4000 BYTE), 
	"CIUEXPCEDULA" VARCHAR2(4000 BYTE), 
	"FECCORDECLRENTA" VARCHAR2(4000 BYTE), 
	"PATRILIQUIDO" VARCHAR2(4000 BYTE), 
	"RENLIQGRAV" VARCHAR2(4000 BYTE), 
	"ORIGENCARGA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."PROCESO" IS 'Id. proceso';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."NLINEA" IS 'N¿mero linea carga fichero';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."NCARGA" IS 'N¿mero carga asociada';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."TIPO_OPER" IS 'Tipo de operaci¿n a realizas Alta/baja/modificaci¿n';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."NIT" IS 'NIT';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."NOMBRE" IS 'Nombre';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."TIPOSOCIEDAD" IS 'TIPO DE SOCIEDAD';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."REPRELEGAL" IS 'Representante Legal.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."REVFISCAL" IS 'Revisor Fiscal';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."ESTEMPRESA" IS 'Estado de la empresa';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."OBJSOCIAL" IS 'OBJETO SOCIAL';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."FECHACONS" IS 'Fecha de Constituci¿n.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."VIGSOCIEDAD" IS 'vigencia de la sociedad';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."LIMREPLEGAL" IS 'Limitaciones Rep Legal.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."INCJUDICIAL" IS 'Incidentes Judiciales';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."NOMACCIONISTA1" IS 'Nombre accionista 1.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."NOMACCIONISTA2" IS 'Nombre accionista 2.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."NOMACCIONISTA3" IS 'Nombre accionista 3.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."NOMACCIONISTA4" IS 'Nombre accionista 4.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."NITACCIONISTA1" IS 'Nit. Accionista 1.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."NITACCIONISTA2" IS 'Nit. Accionista 2.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."NITACCIONISTA3" IS 'Nit. Accionista 3.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."NITACCIONISTA4" IS 'Nit. Accionista 4.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."PARTACCIONISTA1" IS '% Part accionista 1.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."PARTACCIONISTA2" IS '% Part accionista 2.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."PARTACCIONISTA3" IS '% Part accionista 3.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."PARTACCIONISTA4" IS '% Part accionista 4.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."CIIU" IS 'N¿mero del C.I.I.U';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."FUENTEINF" IS 'FUENTE INF.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."MONEDA" IS 'MONEDA.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."VALMILES" IS 'VALORES EN MILES.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."FECESTFINAN" IS 'fecha Estados Financieros (dd-mm-aaaa)';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."VENTAS" IS 'Ventas.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."VENTASPERANT" IS 'Ventas Periodo Anterior.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."COSTOVENTAS" IS 'Costo Ventas.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."GASTOSADM" IS 'Gastos Administrativos';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."UTLOPERACIONAL" IS 'Utilidad Operacional.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."GASTOSFINAN" IS 'Gastos financieros (P Y G)';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."RESULTANTIMP" IS 'Resultados antes de impuestos (P Y G).';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."UTLNETA" IS 'Utilidad Neta.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."INVENTARIO" IS 'Inventario';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."CARTCLIENTE" IS 'Cartera Cliente.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."ACTCORRIENTE" IS 'Activo Corriente.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."TOTACTNOCORRIENTE" IS 'Total Activo no Corriente';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."PROPPLANEQUIPO" IS 'Propiedad planta y equipo';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."OTROSACTIVOS" IS 'OTROS ACTIVOS ';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."ACTIVOTOTAL" IS 'Activo Total.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."OBLIGFINANCP" IS 'Obligaciones financieras corto plazo.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."PROVEEDORESCP" IS 'Proveedores Corto Plazo.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."ANTICIPOCP" IS 'Anticipos corto Plazo.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."PASCORRIENTE" IS 'Pasivo Corriente.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."OBLIGFINANLP" IS 'Obligaciones financieras largo plazo.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."ANTICIPOLP" IS 'Anticipos largo Plazo';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."TOTPASCORRIENTE" IS 'Total pasivo no corriente.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."PASTOTAL" IS 'Pasivo Total.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."PATRIPERANT" IS 'Patrimonio Periodo Anterior.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."PATRIANOACT" IS 'Patrimonio a¿o act (Bce).';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."CAPSOCIAL" IS 'Capital Social.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."PRICOLACC" IS 'Prima en colocaci¿n de acciones.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."INVSUPLCAP" IS 'Inversi¿n suplementaria al capital asignado.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."RESLEGAL" IS 'Reservas legal.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."RESOCASIONAL" IS 'Reservas ocasionales';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."RESEJERANT" IS 'Resultado Ejercicio Anteriores.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."VALORIZACION" IS 'Valorizaciones.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."FECCAMCOMERCIO" IS 'Fecha camara de comercio';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."FOTRUT" IS 'Fotocopia Rut';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."FECRUT" IS 'Fecha Rut';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."FOTCEDULA" IS 'Fotocopia cedula';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."FECEXPCEDULA" IS 'Fecha de expedici¿n cedula.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."CIUEXPCEDULA" IS 'Ciudad de expedicion cedula';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."FECCORDECLRENTA" IS 'Fecha corte Declaraci¿n Renta.';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."PATRILIQUIDO" IS 'Patrimonio liquido';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."RENLIQGRAV" IS 'renta liquida gravable';
   COMMENT ON COLUMN "AXIS"."INT_CARGA_INFORMACOL"."ORIGENCARGA" IS 'Origen de carga ARC(Archivo plano) WBS(Web Service)';
   COMMENT ON TABLE "AXIS"."INT_CARGA_INFORMACOL"  IS 'Interface carga datos informa Colombia.';
  GRANT UPDATE ON "AXIS"."INT_CARGA_INFORMACOL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_CARGA_INFORMACOL" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_CARGA_INFORMACOL" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_CARGA_INFORMACOL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_CARGA_INFORMACOL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_CARGA_INFORMACOL" TO "PROGRAMADORESCSI";
