--------------------------------------------------------
--  DDL for Table INT_POLIZAS_CNP_INV
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_POLIZAS_CNP_INV" 
   (	"SINTERF" NUMBER, 
	"CMAPEAD" VARCHAR2(5 BYTE), 
	"SMAPEAD" NUMBER, 
	"NLINEA" NUMBER(6,0), 
	"CAMPO01" VARCHAR2(100 BYTE), 
	"CAMPO02" VARCHAR2(100 BYTE), 
	"CAMPO03" VARCHAR2(100 BYTE), 
	"CAMPO04" VARCHAR2(100 BYTE), 
	"CAMPO05" VARCHAR2(100 BYTE), 
	"CAMPO06" VARCHAR2(100 BYTE), 
	"CAMPO07" VARCHAR2(100 BYTE), 
	"CAMPO08" VARCHAR2(100 BYTE), 
	"CAMPO09" VARCHAR2(100 BYTE), 
	"CAMPO10" VARCHAR2(100 BYTE), 
	"CAMPO11" VARCHAR2(100 BYTE), 
	"CAMPO12" VARCHAR2(100 BYTE), 
	"CAMPO13" VARCHAR2(100 BYTE), 
	"CAMPO14" VARCHAR2(100 BYTE), 
	"CAMPO15" VARCHAR2(100 BYTE), 
	"CAMPO16" VARCHAR2(100 BYTE), 
	"CAMPO17" VARCHAR2(100 BYTE), 
	"CAMPO18" VARCHAR2(100 BYTE), 
	"CAMPO19" VARCHAR2(100 BYTE), 
	"CAMPO20" VARCHAR2(100 BYTE), 
	"CAMPO21" VARCHAR2(100 BYTE), 
	"CAMPO22" VARCHAR2(100 BYTE), 
	"CAMPO23" VARCHAR2(100 BYTE), 
	"CAMPO24" VARCHAR2(100 BYTE), 
	"CAMPO25" VARCHAR2(100 BYTE), 
	"CAMPO26" VARCHAR2(100 BYTE), 
	"CAMPO27" VARCHAR2(100 BYTE), 
	"CAMPO28" VARCHAR2(100 BYTE), 
	"CAMPO29" VARCHAR2(100 BYTE), 
	"CAMPO30" VARCHAR2(100 BYTE), 
	"CAMPO31" VARCHAR2(100 BYTE), 
	"NCARGA" NUMBER, 
	"PROCESO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."SINTERF" IS 'Secuencia para la interfaz';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CMAPEAD" IS 'Código map carga fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."SMAPEAD" IS 'Secuencia carga map';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."NLINEA" IS 'Número linea carga fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO01" IS 'Campo 01 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO02" IS 'Campo 02 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO03" IS 'Campo 03 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO04" IS 'Campo 04 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO05" IS 'Campo 05 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO06" IS 'Campo 06 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO07" IS 'Campo 07 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO08" IS 'Campo 08 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO09" IS 'Campo 09 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO10" IS 'Campo 10 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO11" IS 'Campo 11 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO12" IS 'Campo 12 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO13" IS 'Campo 13 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO14" IS 'Campo 14 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO15" IS 'Campo 15 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO16" IS 'Campo 16 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO17" IS 'Campo 17 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO18" IS 'Campo 18 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO19" IS 'Campo 19 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO20" IS 'Campo 20 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO21" IS 'Campo 21 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO22" IS 'Campo 22 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO23" IS 'Campo 23 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO24" IS 'Campo 24 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO25" IS 'Campo 25 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO26" IS 'Campo 26 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO27" IS 'Campo 27 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO28" IS 'Campo 28 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO29" IS 'Campo 29 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO30" IS 'Campo 30 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."CAMPO31" IS 'Campo 31 con datos del fichero';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."NCARGA" IS 'Número carga asociada';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_CNP_INV"."PROCESO" IS 'Id. proceso';
   COMMENT ON TABLE "AXIS"."INT_POLIZAS_CNP_INV"  IS 'Interface carga pólizas CNP.';
  GRANT UPDATE ON "AXIS"."INT_POLIZAS_CNP_INV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_POLIZAS_CNP_INV" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_POLIZAS_CNP_INV" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_POLIZAS_CNP_INV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_POLIZAS_CNP_INV" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_POLIZAS_CNP_INV" TO "PROGRAMADORESCSI";
