--------------------------------------------------------
--  DDL for Table INT_REPARTO_CTACTES
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_REPARTO_CTACTES" 
   (	"SPROCES" NUMBER, 
	"CAGENTE" NUMBER, 
	"CEMPRES" NUMBER(2,0), 
	"NRECIBO" NUMBER, 
	"CGARANT" NUMBER(4,0), 
	"CCONCTA" NUMBER(2,0), 
	"IIMPORT" NUMBER, 
	"IIMPORT_MONPOL" NUMBER, 
	"FCAMBIO" DATE, 
	"PREPARTO" NUMBER(15,12), 
	"IIMPORTREP" NUMBER, 
	"IIMPORTREP_MONPOL" NUMBER, 
	"SEXTRAC" NUMBER, 
	"SSEGURO" NUMBER, 
	"CTIPREG" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_REPARTO_CTACTES"."SPROCES" IS 'sproces de la liquidación (tabla ctactes)';
   COMMENT ON COLUMN "AXIS"."INT_REPARTO_CTACTES"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."INT_REPARTO_CTACTES"."CEMPRES" IS 'Código de empresa';
   COMMENT ON COLUMN "AXIS"."INT_REPARTO_CTACTES"."NRECIBO" IS 'Número de recibo';
   COMMENT ON COLUMN "AXIS"."INT_REPARTO_CTACTES"."CGARANT" IS 'Código de garantía';
   COMMENT ON COLUMN "AXIS"."INT_REPARTO_CTACTES"."CCONCTA" IS 'Código concepto cta. corriente';
   COMMENT ON COLUMN "AXIS"."INT_REPARTO_CTACTES"."IIMPORT" IS 'Importe de la cta. corriente a repartir';
   COMMENT ON COLUMN "AXIS"."INT_REPARTO_CTACTES"."IIMPORT_MONPOL" IS 'Importe de la cta. corriente a repartir en la moneda de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_REPARTO_CTACTES"."FCAMBIO" IS 'Fecha de cambio';
   COMMENT ON COLUMN "AXIS"."INT_REPARTO_CTACTES"."PREPARTO" IS 'Porcentage de reparto';
   COMMENT ON COLUMN "AXIS"."INT_REPARTO_CTACTES"."IIMPORTREP" IS 'Importe de la cta. corriente repartido';
   COMMENT ON COLUMN "AXIS"."INT_REPARTO_CTACTES"."IIMPORTREP_MONPOL" IS 'Importe de la cta. corriente repartido en la moneda de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_REPARTO_CTACTES"."SSEGURO" IS 'Código de la póliza';
   COMMENT ON COLUMN "AXIS"."INT_REPARTO_CTACTES"."CTIPREG" IS 'Tipo de registro : Automático, Manual';
   COMMENT ON TABLE "AXIS"."INT_REPARTO_CTACTES"  IS 'Tabla de interfaz con los repartos de la tabla ctactes';
  GRANT UPDATE ON "AXIS"."INT_REPARTO_CTACTES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_REPARTO_CTACTES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_REPARTO_CTACTES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_REPARTO_CTACTES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_REPARTO_CTACTES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_REPARTO_CTACTES" TO "PROGRAMADORESCSI";
