--------------------------------------------------------
--  DDL for Table INT_POLIZAS_DKV
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_POLIZAS_DKV" 
   (	"SINTERF" NUMBER, 
	"CMAPEAD" VARCHAR2(5 BYTE), 
	"SMAPEAD" NUMBER, 
	"NLINEA" NUMBER(6,0), 
	"CPOLCIA" VARCHAR2(50 BYTE), 
	"TIPO_OPER" VARCHAR2(4 BYTE), 
	"SUCURSAL_DKV" NUMBER(3,0), 
	"OFICINA_DKV" NUMBER(2,0), 
	"RAMO_DKV" NUMBER(3,0), 
	"NUM_POLIZA_DKV" NUMBER(5,0), 
	"ORDEN_POLIZA" NUMBER(5,0), 
	"NUM_ASEGURADOS" NUMBER(5,0), 
	"DIA_EFECTO" NUMBER(2,0), 
	"MES_EFECTO" NUMBER(2,0), 
	"ANYO_EFECTO" NUMBER(4,0), 
	"DIA_VENCMTO" NUMBER(2,0), 
	"MES_VENCMTO" NUMBER(2,0), 
	"ANYO_VENCMTO" NUMBER(4,0), 
	"N_SUPLEMENTO" NUMBER(2,0), 
	"DIA_SUPLEMENTO" NUMBER(2,0), 
	"MES_SUPLEMENTO" NUMBER(2,0), 
	"ANYO_SUPLEMENTO" NUMBER(4,0), 
	"MOTIVO_BAJA" VARCHAR2(1 BYTE), 
	"DIA_BAJA" NUMBER(2,0), 
	"MES_BAJA" NUMBER(2,0), 
	"ANYO_BAJA" NUMBER(4,0), 
	"NOMBRE_TOMADOR" VARCHAR2(30 BYTE), 
	"DNI_TOMADOR" VARCHAR2(9 BYTE), 
	"TELEFONO" NUMBER(9,0), 
	"DOMICILIO" VARCHAR2(34 BYTE), 
	"COD_POSTAL" NUMBER(5,0), 
	"LOCALIDAD" VARCHAR2(20 BYTE), 
	"BANCO_DE_COBRO" NUMBER(4,0), 
	"AGENCIA_BANCO_DE_COBRO" NUMBER(4,0), 
	"DIGITOS_CONTROL_CTA_COBRO" NUMBER(2,0), 
	"CTA_CTE_DE_COBRO" NUMBER(10,0), 
	"CLAVE_DE_RIESGO" VARCHAR2(4 BYTE), 
	"PERIODO_DE_COBRO" VARCHAR2(1 BYTE), 
	"CODIGO_DE_COBRO" NUMBER(1,0), 
	"AG_GESTORA_SUC_OFI" NUMBER(5,0), 
	"AG_GESTORA_NUM" NUMBER(5,0), 
	"CAPITAL_GARANTIA_01" NUMBER, 
	"CAPITAL_GARANTIA_02" NUMBER, 
	"CAPITAL_GARANTIA_03" NUMBER, 
	"CAPITAL_GARANTIA_04" NUMBER, 
	"CAPITAL_GARANTIA_05" NUMBER, 
	"CAPITAL_GARANTIA_06" NUMBER, 
	"CAPITAL_GARANTIA_07" NUMBER, 
	"CAPITAL_GARANTIA_08" NUMBER, 
	"CAPITAL_GARANTIA_09" NUMBER, 
	"CAPITAL_GARANTIA_10" NUMBER, 
	"IMPORTE_PRIMA_NETA_ANUAL" NUMBER, 
	"IMPORTE_TASAS_ANUAL" NUMBER, 
	"IMPORTE_CONSORCIO_ANUAL" NUMBER, 
	"IMPORTE_PRIMA_TOTAL_ANUAL" NUMBER, 
	"IMPORTE_PRIMA_NETA_RECIBO" NUMBER, 
	"IMPORTE_TASAS_RECIBO" NUMBER, 
	"IMPORTE_PRIMA_TOTAL_RECIBO" NUMBER, 
	"OFICINA_BANCARIA" NUMBER(4,0), 
	"NCARGA" NUMBER, 
	"PROCESO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_DKV"."SINTERF" IS 'Secuencia para la interfaz';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_DKV"."CPOLCIA" IS 'Campo calculado n¿mero p¿liza cia.';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_DKV"."TIPO_OPER" IS 'Campo calculado tipo operaci¿n a realizar.';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_DKV"."NCARGA" IS 'N¿mero carga.';
   COMMENT ON COLUMN "AXIS"."INT_POLIZAS_DKV"."PROCESO" IS 'Id. proceso';
  GRANT UPDATE ON "AXIS"."INT_POLIZAS_DKV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_POLIZAS_DKV" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_POLIZAS_DKV" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_POLIZAS_DKV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_POLIZAS_DKV" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_POLIZAS_DKV" TO "PROGRAMADORESCSI";
