--------------------------------------------------------
--  DDL for Table INT_FILAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_FILAS" 
   (	"NFILA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON TABLE "AXIS"."INT_FILAS"  IS 'Tabla utilizada para crear filas desde un registro plano';
  GRANT UPDATE ON "AXIS"."INT_FILAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_FILAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_FILAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_FILAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_FILAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_FILAS" TO "PROGRAMADORESCSI";
