--------------------------------------------------------
--  DDL for Table INT_RECIBOS_DKV
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_RECIBOS_DKV" 
   (	"SINTERF" NUMBER, 
	"CMAPEAD" VARCHAR2(5 BYTE), 
	"SMAPEAD" NUMBER, 
	"NLINEA" NUMBER(6,0), 
	"CRECCIA" VARCHAR2(50 BYTE), 
	"TIPO_OPER" VARCHAR2(8 BYTE), 
	"SUCURSAL_DKV" NUMBER(3,0), 
	"OFICINA_DKV" NUMBER(2,0), 
	"RAMO_DKV" NUMBER(3,0), 
	"NUM_POLIZA_DKV" NUMBER(5,0), 
	"ORDEN_POLIZA_DKV" NUMBER(5,0), 
	"ORDEN_RECIBO" NUMBER(2,0), 
	"DIA_EFECTO_RBO" NUMBER(2,0), 
	"MES_EFECTO_RBO" NUMBER(2,0), 
	"ANYO_EFECTO_RBO" NUMBER(4,0), 
	"DIA_VTO_RBO" NUMBER(2,0), 
	"MES_VTO_RBO" NUMBER(2,0), 
	"ANYO_VTO_RBO" NUMBER(4,0), 
	"NOMBRE_TOMADOR" VARCHAR2(30 BYTE), 
	"DNI_TOMADOR" VARCHAR2(9 BYTE), 
	"AG_GESTORA_SUC_OFI" NUMBER(5,0), 
	"AG_GESTORA_NUM" NUMBER(5,0), 
	"MES_LIQUIDACION" NUMBER(2,0), 
	"ANYO_LIQUIDACION" NUMBER(4,0), 
	"IMPORTE_PRIMA_NETA" NUMBER, 
	"IMPORTE_TASAS" NUMBER, 
	"IMPORTE_CONSORCIO" NUMBER, 
	"IMPORTE_TALONES_SALUD" NUMBER, 
	"IMPORTE_PRIMA_TOTAL" NUMBER, 
	"IMPORTE_COMISION" NUMBER, 
	"PERIODO_DE_COBRO" VARCHAR2(1 BYTE), 
	"CODIGO_DE_COBRO" NUMBER(1,0), 
	"ESTADO_DE_RECIBO" NUMBER(1,0), 
	"TIPO_DE_COMISION" VARCHAR2(1 BYTE), 
	"BANCO_DE_COBRO" NUMBER(4,0), 
	"AGENCIA_BANCO_DE_COBRO" NUMBER(4,0), 
	"DIGITOS_CONTROL_CTA_COBRO" NUMBER(2,0), 
	"CTA_CTE_DE_COBRO" NUMBER(10,0), 
	"NUMERO_DE_RECIBO" NUMBER(7,0), 
	"NCARGA" NUMBER, 
	"PROCESO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_DKV"."SINTERF" IS 'Secuencia para la interfaz';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_DKV"."CRECCIA" IS 'Campo calculado n¿mero recibo cia.';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_DKV"."TIPO_OPER" IS 'Campo calculado tipo operaci¿n a realizar.';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_DKV"."NCARGA" IS 'N¿mero carga.';
   COMMENT ON COLUMN "AXIS"."INT_RECIBOS_DKV"."PROCESO" IS 'Id. proceso';
  GRANT UPDATE ON "AXIS"."INT_RECIBOS_DKV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_RECIBOS_DKV" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_RECIBOS_DKV" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_RECIBOS_DKV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_RECIBOS_DKV" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_RECIBOS_DKV" TO "PROGRAMADORESCSI";
