--------------------------------------------------------
--  DDL for Table INT_SERVICIOS_FORMATO
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_SERVICIOS_FORMATO" 
   (	"CINTERF" VARCHAR2(4 BYTE), 
	"CFORMATO" VARCHAR2(5 BYTE), 
	"SECUENCIA" VARCHAR2(1 BYTE), 
	"RPCENTROORIGEN" NUMBER(1,0), 
	"RPFEOPERACION" NUMBER(1,0), 
	"RPPOSICIONAMIENTO" VARCHAR2(10 BYTE), 
	"TINTERF" VARCHAR2(250 BYTE), 
	"IDCONSULTA" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_SERVICIOS_FORMATO"."CINTERF" IS 'Formato del servicio';
   COMMENT ON COLUMN "AXIS"."INT_SERVICIOS_FORMATO"."SECUENCIA" IS 'Valor que debe enviarse en este elemento de la cabecera del mensaje de peticion a BM';
   COMMENT ON COLUMN "AXIS"."INT_SERVICIOS_FORMATO"."RPCENTROORIGEN" IS 'Indica si existe el tag RpCentroOrigen en el mensaje de peticion a BM';
   COMMENT ON COLUMN "AXIS"."INT_SERVICIOS_FORMATO"."RPFEOPERACION" IS 'Indica si existe el tag RpFeOperacion en el mensaje de peticion a BM';
   COMMENT ON COLUMN "AXIS"."INT_SERVICIOS_FORMATO"."RPPOSICIONAMIENTO" IS 'Indica si deben seguir recuperandose datos hasta el final y con que formato (<>''0''), no (''0'') o si no aplica (null)';
   COMMENT ON COLUMN "AXIS"."INT_SERVICIOS_FORMATO"."TINTERF" IS 'Descripción del formato del servicio';
   COMMENT ON COLUMN "AXIS"."INT_SERVICIOS_FORMATO"."IDCONSULTA" IS 'Identificador de la consulta que permite mapear el resultado de la interfaz a una visiualización por pantalla';
  GRANT UPDATE ON "AXIS"."INT_SERVICIOS_FORMATO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_SERVICIOS_FORMATO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_SERVICIOS_FORMATO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_SERVICIOS_FORMATO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_SERVICIOS_FORMATO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_SERVICIOS_FORMATO" TO "PROGRAMADORESCSI";
