--------------------------------------------------------
--  DDL for Table INT_LIST_CORTE_PROD_EXT
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_LIST_CORTE_PROD_EXT" 
   (	"NCTA" VARCHAR2(50 BYTE), 
	"FCTA" DATE, 
	"CODCIA" NUMBER, 
	"SIGLA" VARCHAR2(20 BYTE), 
	"NPOLIZA" NUMBER, 
	"NCERTIF" NUMBER, 
	"FCERTIF" DATE, 
	"CODCLIE" NUMBER, 
	"CODCLIE2" VARCHAR2(20 BYTE), 
	"VIGDESDE" DATE, 
	"VIGHASTA" DATE, 
	"VPRIMA" NUMBER, 
	"VGASTOS" NUMBER, 
	"PORIVA" NUMBER, 
	"IVA1" NUMBER, 
	"PORICA" NUMBER, 
	"VICA" NUMBER, 
	"PORCOMI" NUMBER, 
	"COMISION" NUMBER, 
	"IVA2" NUMBER, 
	"VTOTAL" NUMBER, 
	"CESTADO" VARCHAR2(20 BYTE), 
	"FECESTA" DATE, 
	"NPLACA" VARCHAR2(50 BYTE), 
	"PORPARTI" NUMBER, 
	"FECVENCE" DATE, 
	"FECINTER" DATE, 
	"TOMADOR" VARCHAR2(20 BYTE), 
	"ASEGURADO" VARCHAR2(20 BYTE), 
	"NOMASEGU" VARCHAR2(20 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "TABEXT"
      ACCESS PARAMETERS
      ( records delimited by 0X'0D0A'
   discardfile 'dis_INT_CARGA_GENERICO_EXT_%a_%p.dis'
   badfile 'bad_INT_CARGA_GENERICO_EXT_%a_%p.bad'
   logfile 'log_INT_CARGA_GENERICO_EXT_%a_%p.log'
   fields terminated by '|' OPTIONALLY ENCLOSED BY '"'
   MISSING FIELD VALUES ARE NULL
   REJECT ROWS WITH ALL NULL FIELDS
   (    NCTA
			, FCTA DATE  MASK "DDMMYYYY"
			, CODCIA
			, SIGLA
			, NPOLIZA
			, NCERTIF
			, FCERTIF DATE  MASK "DDMMYYYY"
			, CODCLIE
			, CODCLIE2
			, VIGDESDE DATE  MASK "DDMMYYYY"
			, VIGHASTA DATE  MASK "DDMMYYYY"
			, VPRIMA
			, VGASTOS
			, PORIVA
			, IVA1
			, PORICA
			, VICA
			, PORCOMI
			, COMISION
			, IVA2
			, VTOTAL
			, CESTADO
			, FECESTA DATE  MASK "DDMMYYYY"
			, NPLACA
			, PORPARTI
			, FECVENCE DATE  MASK "DDMMYYYY"
			, FECINTER DATE  MASK "DDMMYYYY"
			, TOMADOR
			, ASEGURADO
			, NOMASEGU
		)
	                       )
      LOCATION
       ( "TABEXT":'PRUEBA_PROD_118_CONF_V.csv'
       )
    );
  GRANT SELECT ON "AXIS"."INT_LIST_CORTE_PROD_EXT" TO "PROGRAMADORESCSI";
  GRANT SELECT ON "AXIS"."INT_LIST_CORTE_PROD_EXT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_LIST_CORTE_PROD_EXT" TO "CONF_DWH";
