--------------------------------------------------------
--  DDL for Table INT_FACTURAS_AGENTES
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_FACTURAS_AGENTES" 
   (	"SPROCES" NUMBER, 
	"NLINEA" NUMBER, 
	"CEMPRES" NUMBER, 
	"CAGENTE" NUMBER, 
	"NRECIBO" NUMBER, 
	"FCOBRO" DATE, 
	"CORTECUENTA" NUMBER, 
	"CMONEDA" NUMBER, 
	"ITOTALR" NUMBER, 
	"ICOMISION" NUMBER, 
	"IVA" NUMBER, 
	"IRETEFUENTE" NUMBER, 
	"IRETEIVA" NUMBER, 
	"IRETEICA" NUMBER, 
	"NLIQMEN" NUMBER, 
	"NLIQLIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."SPROCES" IS 'Identificador de proceso. PROCESOSCAB';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."NLINEA" IS 'Número de línea';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."CEMPRES" IS 'Código de empresa (para informar la liquidación que se incluyo - LIQUIDALIN)';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."CAGENTE" IS 'Código del agente';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."NRECIBO" IS 'Número del recibo';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."FCOBRO" IS 'Fecha de cobro del recibo';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."CORTECUENTA" IS '0-Sin corte de cuenta, 1-Con corte de cuenta (autoliquidado), Nulo-Lo que tenga el agente por defecto';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."CMONEDA" IS 'Código de la moneda (1-Euros, 6-Dólares, 8-Pesos)';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."ITOTALR" IS 'Importe total del recibo';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."ICOMISION" IS 'Importe de la comisión';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."IVA" IS 'Importe del IVA';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."IRETEFUENTE" IS 'Importe de Retención en la Fuente';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."IRETEIVA" IS 'Importe de Retención en el IVA';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."IRETEICA" IS 'Importe de Retención en el ICA';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."NLIQMEN" IS 'Número de liquidación (para informar la liquidación que se incluyo - LIQUIDALIN)';
   COMMENT ON COLUMN "AXIS"."INT_FACTURAS_AGENTES"."NLIQLIN" IS 'Número de liquidación (para informar la liquidación que se incluyo - LIQUIDALIN)';
   COMMENT ON TABLE "AXIS"."INT_FACTURAS_AGENTES"  IS 'Cargas automáticas de la información de las facturas de agentes (mediadores)';
  GRANT UPDATE ON "AXIS"."INT_FACTURAS_AGENTES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_FACTURAS_AGENTES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_FACTURAS_AGENTES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_FACTURAS_AGENTES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_FACTURAS_AGENTES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_FACTURAS_AGENTES" TO "PROGRAMADORESCSI";
