--------------------------------------------------------
--  DDL for Table INT_REPORT_DATA
--------------------------------------------------------

  CREATE TABLE "AXIS"."INT_REPORT_DATA" 
   (	"ID" NUMBER, 
	"DESCRIPCION" VARCHAR2(30 BYTE), 
	"NORDEN" NUMBER, 
	"V01" VARCHAR2(100 BYTE), 
	"V02" VARCHAR2(100 BYTE), 
	"V03" VARCHAR2(100 BYTE), 
	"V04" VARCHAR2(100 BYTE), 
	"V05" VARCHAR2(100 BYTE), 
	"V06" VARCHAR2(100 BYTE), 
	"V07" VARCHAR2(100 BYTE), 
	"V08" VARCHAR2(100 BYTE), 
	"V09" VARCHAR2(100 BYTE), 
	"V10" VARCHAR2(100 BYTE), 
	"V11" VARCHAR2(100 BYTE), 
	"V12" VARCHAR2(100 BYTE), 
	"V13" VARCHAR2(100 BYTE), 
	"V14" VARCHAR2(100 BYTE), 
	"V15" VARCHAR2(100 BYTE), 
	"V16" VARCHAR2(100 BYTE), 
	"V17" VARCHAR2(100 BYTE), 
	"V18" VARCHAR2(100 BYTE), 
	"V19" VARCHAR2(100 BYTE), 
	"V20" VARCHAR2(100 BYTE), 
	"N01" NUMBER, 
	"N02" NUMBER, 
	"N03" NUMBER, 
	"N04" NUMBER, 
	"N05" NUMBER, 
	"N06" NUMBER, 
	"N07" NUMBER, 
	"N08" NUMBER, 
	"N09" NUMBER, 
	"N10" NUMBER, 
	"N11" NUMBER, 
	"N12" NUMBER, 
	"N13" NUMBER, 
	"N14" NUMBER, 
	"N15" NUMBER, 
	"N16" NUMBER, 
	"N17" NUMBER, 
	"N18" NUMBER, 
	"N19" NUMBER, 
	"N20" NUMBER, 
	"D01" DATE, 
	"D02" DATE, 
	"D03" DATE, 
	"D04" DATE, 
	"D05" DATE, 
	"C01" VARCHAR2(1024 BYTE), 
	"C02" VARCHAR2(1024 BYTE), 
	"C03" VARCHAR2(1024 BYTE), 
	"C04" VARCHAR2(1024 BYTE), 
	"C05" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INT_REPORT_DATA"."ID" IS 'identificador de cuadro a reportear - debe ser unico';
   COMMENT ON COLUMN "AXIS"."INT_REPORT_DATA"."DESCRIPCION" IS 'Descripción del listado identificado por el ID';
   COMMENT ON COLUMN "AXIS"."INT_REPORT_DATA"."NORDEN" IS 'Numérico para poder ordenar los datos';
   COMMENT ON COLUMN "AXIS"."INT_REPORT_DATA"."V01" IS 'Valor 01..20 VARCHAR2 de 100';
   COMMENT ON COLUMN "AXIS"."INT_REPORT_DATA"."N01" IS 'Valor 01..20 NUMBER';
   COMMENT ON COLUMN "AXIS"."INT_REPORT_DATA"."D01" IS 'Valor 01..5 DATE';
   COMMENT ON COLUMN "AXIS"."INT_REPORT_DATA"."C01" IS 'Valor 01..5 VARCHAR2 de 1024';
   COMMENT ON TABLE "AXIS"."INT_REPORT_DATA"  IS 'Tabla temporal de AXISCONNECT para guardar registros de listados';
  GRANT UPDATE ON "AXIS"."INT_REPORT_DATA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_REPORT_DATA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INT_REPORT_DATA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INT_REPORT_DATA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INT_REPORT_DATA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INT_REPORT_DATA" TO "PROGRAMADORESCSI";
