--------------------------------------------------------
--  DDL for Table INTERFAZ_DATECSA
--------------------------------------------------------

  CREATE TABLE "AXIS"."INTERFAZ_DATECSA" 
   (	"CODIGO" NUMBER, 
	"NOMBRE" VARCHAR2(1000 BYTE), 
	"EXTENSION" VARCHAR2(1000 BYTE), 
	"META_DATA" VARCHAR2(1000 BYTE), 
	"ESTADO_PROC" VARCHAR2(1000 BYTE), 
	"ERROR" VARCHAR2(1000 BYTE), 
	"FINICIO_PROC" TIMESTAMP (6), 
	"FFIN_PROC" TIMESTAMP (6), 
	"ID_GEDOX" NUMBER, 
	"ID_SPROCES" NUMBER, 
	"INSDATE" DATE DEFAULT SYSDATE, 
	"ADJUNTO" VARCHAR2(1000 BYTE), 
	"UPPERNAME" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INTERFAZ_DATECSA"."CODIGO" IS 'C¿digo del archivo';
   COMMENT ON COLUMN "AXIS"."INTERFAZ_DATECSA"."NOMBRE" IS 'Nombre del archivo a subir';
   COMMENT ON COLUMN "AXIS"."INTERFAZ_DATECSA"."EXTENSION" IS 'Extensi¿n del archivo';
   COMMENT ON COLUMN "AXIS"."INTERFAZ_DATECSA"."META_DATA" IS 'Meta data del archivo a subir';
   COMMENT ON COLUMN "AXIS"."INTERFAZ_DATECSA"."ESTADO_PROC" IS 'Estado del proceso ( ok, ko, procesando )';
   COMMENT ON COLUMN "AXIS"."INTERFAZ_DATECSA"."ERROR" IS 'Error del proceso';
   COMMENT ON COLUMN "AXIS"."INTERFAZ_DATECSA"."FINICIO_PROC" IS 'Fecha inicio del proceso';
   COMMENT ON COLUMN "AXIS"."INTERFAZ_DATECSA"."FFIN_PROC" IS 'Fecha fin proceso';
   COMMENT ON COLUMN "AXIS"."INTERFAZ_DATECSA"."ID_GEDOX" IS 'Id documento subido al gedox';
   COMMENT ON COLUMN "AXIS"."INTERFAZ_DATECSA"."ID_SPROCES" IS 'Id proceso que ha realizado la carga';
   COMMENT ON COLUMN "AXIS"."INTERFAZ_DATECSA"."INSDATE" IS 'Fecha creaci¿n del registro';
   COMMENT ON TABLE "AXIS"."INTERFAZ_DATECSA"  IS 'Interface con el fichero DATECSA';
  GRANT UPDATE ON "AXIS"."INTERFAZ_DATECSA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INTERFAZ_DATECSA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INTERFAZ_DATECSA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INTERFAZ_DATECSA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INTERFAZ_DATECSA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INTERFAZ_DATECSA" TO "PROGRAMADORESCSI";
