--------------------------------------------------------
--  DDL for Table INTERTECGAR
--------------------------------------------------------

  CREATE TABLE "AXIS"."INTERTECGAR" 
   (	"NCODINT" NUMBER(6,0), 
	"SPRODUC" NUMBER(6,0), 
	"CACTIVI" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INTERTECGAR"."NCODINT" IS 'CÓDIGO IDENTIFICATIVO ÚNICO';
   COMMENT ON COLUMN "AXIS"."INTERTECGAR"."SPRODUC" IS 'IDENTIFICATIVO ÚNICO DEL PRODUCTO';
   COMMENT ON COLUMN "AXIS"."INTERTECGAR"."CACTIVI" IS 'IDENTIFICADOR ÚNICO DE LA ACTIVIDAD';
   COMMENT ON COLUMN "AXIS"."INTERTECGAR"."CGARANT" IS 'IDENTIFICADOR ÚNICO DE LA GARANTÍA';
   COMMENT ON TABLE "AXIS"."INTERTECGAR"  IS 'INTERÉS TÉCNICO ASOCIADO AL PRODUCTO,ACTIVIDAD Y GARANTÍA';
  GRANT UPDATE ON "AXIS"."INTERTECGAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INTERTECGAR" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INTERTECGAR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INTERTECGAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INTERTECGAR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INTERTECGAR" TO "PROGRAMADORESCSI";
