--------------------------------------------------------
--  DDL for Table INTPROGAR
--------------------------------------------------------

  CREATE TABLE "AXIS"."INTPROGAR" 
   (	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CACTIVI" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0), 
	"FINI" DATE, 
	"FFIN" DATE, 
	"CREF" NUMBER(2,0), 
	"CINTREF" NUMBER(3,0), 
	"PDIF" NUMBER(5,2) DEFAULT 0, 
	"PINTTEC" NUMBER(5,2), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIF" DATE, 
	"PMAX" NUMBER(5,2), 
	"PMIN" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."INTPROGAR"."FINI" IS 'Fecha Inicio Vigencia';
   COMMENT ON COLUMN "AXIS"."INTPROGAR"."FFIN" IS 'Fecha Fin Vigencia';
   COMMENT ON COLUMN "AXIS"."INTPROGAR"."CREF" IS 'Valores Posibles: 0-Porcentaje, 1-Referenciado';
   COMMENT ON COLUMN "AXIS"."INTPROGAR"."CINTREF" IS 'Código Interés Referenciado (Si CREF=1 y obligatorio); Debe existir en la tabla INTREF';
   COMMENT ON COLUMN "AXIS"."INTPROGAR"."PDIF" IS 'Diferencial de interes (Si CREF=1)';
   COMMENT ON COLUMN "AXIS"."INTPROGAR"."PINTTEC" IS 'Porcentaje de Interés Técnico (Si CREF=0)';
   COMMENT ON COLUMN "AXIS"."INTPROGAR"."CUSUALT" IS 'Código Usuario de alta del registro';
   COMMENT ON COLUMN "AXIS"."INTPROGAR"."FALTA" IS 'Fecha de Alta';
   COMMENT ON COLUMN "AXIS"."INTPROGAR"."CUSUMOD" IS 'Código usuario que modifica el registro';
   COMMENT ON COLUMN "AXIS"."INTPROGAR"."FMODIF" IS 'Fecha de Modificación';
   COMMENT ON TABLE "AXIS"."INTPROGAR"  IS 'Interés Técnico';
  GRANT UPDATE ON "AXIS"."INTPROGAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INTPROGAR" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."INTPROGAR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."INTPROGAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."INTPROGAR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."INTPROGAR" TO "PROGRAMADORESCSI";
