--------------------------------------------------------
--  DDL for Table IR_PERMITEINSPECCION
--------------------------------------------------------

  CREATE TABLE "AXIS"."IR_PERMITEINSPECCION" 
   (	"CEMPRES" NUMBER(2,0), 
	"SPRODUC" NUMBER, 
	"CAGENTE" NUMBER, 
	"CTIPIDE" NUMBER, 
	"NNUMIDE" VARCHAR2(50 BYTE), 
	"NPOLIZA" NUMBER, 
	"NCERTIF" NUMBER, 
	"PERMITEINSPEC" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."IR_PERMITEINSPECCION"."CEMPRES" IS 'Código de la empresa';
   COMMENT ON COLUMN "AXIS"."IR_PERMITEINSPECCION"."SPRODUC" IS 'Producte pel qual es permet inspecció(0 indica que es permet per tots els productes)';
   COMMENT ON COLUMN "AXIS"."IR_PERMITEINSPECCION"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."IR_PERMITEINSPECCION"."CTIPIDE" IS 'Código tipo documento';
   COMMENT ON COLUMN "AXIS"."IR_PERMITEINSPECCION"."NNUMIDE" IS 'Número documento';
   COMMENT ON COLUMN "AXIS"."IR_PERMITEINSPECCION"."NPOLIZA" IS 'Número póliza';
   COMMENT ON COLUMN "AXIS"."IR_PERMITEINSPECCION"."NCERTIF" IS 'Número certificado';
   COMMENT ON COLUMN "AXIS"."IR_PERMITEINSPECCION"."PERMITEINSPEC" IS 'Opció al realitzar l''acció';
   COMMENT ON TABLE "AXIS"."IR_PERMITEINSPECCION"  IS 'Parametrizamos por producto si estamos excempto de realizar inspección';
  GRANT UPDATE ON "AXIS"."IR_PERMITEINSPECCION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."IR_PERMITEINSPECCION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."IR_PERMITEINSPECCION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."IR_PERMITEINSPECCION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."IR_PERMITEINSPECCION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."IR_PERMITEINSPECCION" TO "PROGRAMADORESCSI";
