--------------------------------------------------------
--  DDL for Table JOB_INTERVALOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."JOB_INTERVALOS" 
   (	"CINTERVALO" NUMBER(4,0), 
	"SLITERA" NUMBER(8,0), 
	"VALOR" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."JOB_INTERVALOS"."CINTERVALO" IS 'Código de intervalo';
   COMMENT ON COLUMN "AXIS"."JOB_INTERVALOS"."SLITERA" IS 'Codigo literal de descripcion';
   COMMENT ON COLUMN "AXIS"."JOB_INTERVALOS"."VALOR" IS 'Valor del intervalo.';
   COMMENT ON TABLE "AXIS"."JOB_INTERVALOS"  IS 'Almacena los intervalos que se pueden ejecutar en un job';
  GRANT UPDATE ON "AXIS"."JOB_INTERVALOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."JOB_INTERVALOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."JOB_INTERVALOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."JOB_INTERVALOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."JOB_INTERVALOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."JOB_INTERVALOS" TO "PROGRAMADORESCSI";
