--------------------------------------------------------
--  DDL for Table JOB_DESCPROCES
--------------------------------------------------------

  CREATE TABLE "AXIS"."JOB_DESCPROCES" 
   (	"CPROCES" NUMBER, 
	"CIDIOMA" NUMBER, 
	"TPROCES" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."JOB_DESCPROCES"."CPROCES" IS 'Código proceso';
   COMMENT ON COLUMN "AXIS"."JOB_DESCPROCES"."CIDIOMA" IS 'Código idioma descripción';
   COMMENT ON COLUMN "AXIS"."JOB_DESCPROCES"."TPROCES" IS 'Descripción del proceso';
   COMMENT ON TABLE "AXIS"."JOB_DESCPROCES"  IS 'Tabla descripción procesos por job';
  GRANT UPDATE ON "AXIS"."JOB_DESCPROCES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."JOB_DESCPROCES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."JOB_DESCPROCES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."JOB_DESCPROCES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."JOB_DESCPROCES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."JOB_DESCPROCES" TO "PROGRAMADORESCSI";
