--------------------------------------------------------
--  DDL for Table LANZAR_INFORMES
--------------------------------------------------------

  CREATE TABLE "AXIS"."LANZAR_INFORMES" 
   (	"SINTERF" NUMBER, 
	"CMAP" VARCHAR2(50 BYTE), 
	"CEMPRES" NUMBER(2,0), 
	"CEXPORT" VARCHAR2(10 BYTE), 
	"CESTADO" NUMBER(2,0), 
	"TERROR" VARCHAR2(2000 BYTE), 
	"TFICHERO" VARCHAR2(500 BYTE), 
	"CUSER" VARCHAR2(50 BYTE), 
	"SLITERA" NUMBER(8,0), 
	"FINI" DATE, 
	"FFIN" DATE, 
	"CBATCH" NUMBER(2,0) DEFAULT 0, 
	"CEMAIL" VARCHAR2(150 BYTE), 
	"CESTENVIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."LANZAR_INFORMES"."SINTERF" IS 'Sequencial de la ejecución';
   COMMENT ON COLUMN "AXIS"."LANZAR_INFORMES"."CMAP" IS 'Map a lanzar';
   COMMENT ON COLUMN "AXIS"."LANZAR_INFORMES"."CEMPRES" IS 'Empresa';
   COMMENT ON COLUMN "AXIS"."LANZAR_INFORMES"."CEXPORT" IS 'Formato a generar';
   COMMENT ON COLUMN "AXIS"."LANZAR_INFORMES"."CESTADO" IS 'Estado de la generación 0.-Ok, 1.-Pendiente, 99.-Error';
   COMMENT ON COLUMN "AXIS"."LANZAR_INFORMES"."TERROR" IS 'Error proporcionado por axisconnect';
   COMMENT ON COLUMN "AXIS"."LANZAR_INFORMES"."TFICHERO" IS 'Ruta del fichero generado';
   COMMENT ON COLUMN "AXIS"."LANZAR_INFORMES"."CUSER" IS 'Usuario que ha realizado la petición';
   COMMENT ON COLUMN "AXIS"."LANZAR_INFORMES"."SLITERA" IS 'Literal del parámetro';
   COMMENT ON COLUMN "AXIS"."LANZAR_INFORMES"."FINI" IS 'Fecha de la petición';
   COMMENT ON COLUMN "AXIS"."LANZAR_INFORMES"."FFIN" IS 'Fecha en que termina la generación';
   COMMENT ON COLUMN "AXIS"."LANZAR_INFORMES"."CBATCH" IS 'Tipo de generación 0.-Online, 1.-Batch';
   COMMENT ON COLUMN "AXIS"."LANZAR_INFORMES"."CEMAIL" IS 'Dirección de correo electrónico';
   COMMENT ON COLUMN "AXIS"."LANZAR_INFORMES"."CESTENVIO" IS '0.-OK 1-KO';
   COMMENT ON TABLE "AXIS"."LANZAR_INFORMES"  IS 'Informes a generar';
  GRANT UPDATE ON "AXIS"."LANZAR_INFORMES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."LANZAR_INFORMES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."LANZAR_INFORMES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."LANZAR_INFORMES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."LANZAR_INFORMES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."LANZAR_INFORMES" TO "PROGRAMADORESCSI";
