--------------------------------------------------------
--  DDL for Table LIQUIDACAB
--------------------------------------------------------

  CREATE TABLE "AXIS"."LIQUIDACAB" 
   (	"CAGENTE" NUMBER, 
	"NLIQMEN" NUMBER(10,0), 
	"FLIQUID" DATE, 
	"FMOVIMI" DATE, 
	"FCONTAB" DATE, 
	"CEMPRES" NUMBER(2,0), 
	"SPROLIQ" NUMBER, 
	"NTALON" NUMBER(10,0), 
	"CCTATALON" VARCHAR2(20 BYTE), 
	"FINGTALON" DATE, 
	"CTIPOLIQ" NUMBER(2,0), 
	"CESTADO" NUMBER(3,0), 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FCOBRO" DATE, 
	"CTOTALLIQ" NUMBER(3,0), 
	"IIMPORTE" NUMBER, 
	"CESTAUTOLIQ" NUMBER, 
	"IDIFGLOBAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."NLIQMEN" IS 'Número de  liquidación';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."FLIQUID" IS 'Fecha de liquidación';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."FMOVIMI" IS 'Fecha del movimiento';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."FCONTAB" IS 'Fecha de contabilidad de la liquidación';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."CEMPRES" IS 'Código de la empresa';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."SPROLIQ" IS 'Sproces de la liquidación';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."NTALON" IS 'Número de talón';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."CTIPOLIQ" IS 'Tipo de liquidación Vf.:1038';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."CESTADO" IS 'Estado de la liquidación Vf.: 933';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."CUSUARI" IS 'Usuario que realiza la liquidación';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."FCOBRO" IS 'Fecha de cobro';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."CTOTALLIQ" IS 'Tipo de liquidación, por liquido o por el total';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."IIMPORTE" IS 'Importe autoliquidación';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."CESTAUTOLIQ" IS 'Estado de autoliquidación. detvalores 32001';
   COMMENT ON COLUMN "AXIS"."LIQUIDACAB"."IDIFGLOBAL" IS 'Diferencia de autoliquidación que no va por recibo';
   COMMENT ON TABLE "AXIS"."LIQUIDACAB"  IS 'Tabla para registrar la cabecera de la liquidación';
  GRANT UPDATE ON "AXIS"."LIQUIDACAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."LIQUIDACAB" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."LIQUIDACAB" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."LIQUIDACAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."LIQUIDACAB" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."LIQUIDACAB" TO "PROGRAMADORESCSI";
