--------------------------------------------------------
--  DDL for Table LIQUIDAREAXL_AUX
--------------------------------------------------------

  CREATE TABLE "AXIS"."LIQUIDAREAXL_AUX" 
   (	"NSINIES" VARCHAR2(14 BYTE), 
	"FSINIES" DATE, 
	"FCIERRE" DATE, 
	"SPROCES" NUMBER, 
	"SCONTRA" NUMBER(6,0), 
	"NVERSIO" NUMBER(2,0), 
	"CTRAMO" NUMBER(2,0), 
	"CCOMPANI" NUMBER(3,0), 
	"ITOTEXP" NUMBER, 
	"ITOTIND" NUMBER, 
	"ICUOREA" NUMBER, 
	"IPAGREA" NUMBER, 
	"ILIQREA" NUMBER, 
	"IRESERV" NUMBER, 
	"IRESIND" NUMBER, 
	"ITOTREA" NUMBER, 
	"IRESREA" NUMBER, 
	"ILIMIND" NUMBER, 
	"PCUOREA" NUMBER(8,5), 
	"PCUOTOT" NUMBER(8,5), 
	"ILIQNET" NUMBER, 
	"IRESNET" NUMBER, 
	"IRESGAS" NUMBER, 
	"ICUOREA_MONCON" NUMBER, 
	"ILIMIND_MONCON" NUMBER, 
	"ILIQNET_MONCON" NUMBER, 
	"ILIQREA_MONCON" NUMBER, 
	"IPAGREA_MONCON" NUMBER, 
	"IRESERV_MONCON" NUMBER, 
	"IRESGAS_MONCON" NUMBER, 
	"IRESIND_MONCON" NUMBER, 
	"IRESNET_MONCON" NUMBER, 
	"IRESREA_MONCON" NUMBER, 
	"ITOTEXP_MONCON" NUMBER, 
	"ITOTIND_MONCON" NUMBER, 
	"ITOTREA_MONCON" NUMBER, 
	"IRESINDEM" NUMBER, 
	"IRESINTER" NUMBER, 
	"IRESADMIN" NUMBER, 
	"IRESINDEM_MONCON" NUMBER, 
	"IRESINTER_MONCON" NUMBER, 
	"IRESADMIN_MONCON" NUMBER, 
	"CEVENTO" VARCHAR2(20 BYTE), 
	"NID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."NSINIES" IS 'Numero de expediente';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."FSINIES" IS 'Fecha siniestro (F_REASE de HIST_EXPDTE_MES)';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."FCIERRE" IS 'Fecha cierre';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."SPROCES" IS 'Secuencia proceso cierre';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."SCONTRA" IS 'Secuencia Identificadora del Contrato';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."NVERSIO" IS 'Numero version contrato reas.';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."CTRAMO" IS 'Codigo del tramo';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."CCOMPANI" IS 'Codigo de compa?ia';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."ITOTEXP" IS 'Total pagos expediente';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."ITOTIND" IS 'Total pagos expediente indexados';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."ICUOREA" IS 'Importe cuota reaseguro';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IPAGREA" IS 'Importe pagado reaseguro (suma liquidaciones anteriores)';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."ILIQREA" IS 'Importe liquidacion reaseguro';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESERV" IS 'Importe reservas';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESIND" IS 'Importe reservas indexado';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."ITOTREA" IS 'Importe total reaseguro';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESREA" IS 'Importe reserva reaseguro';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."ILIMIND" IS 'Importe limite indexado (ponderado)';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."ILIQNET" IS 'Importe liquidacion neta';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESNET" IS 'importe reserva neta';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESGAS" IS 'Importe reservas Gastos (ctipres=3 )';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."ICUOREA_MONCON" IS 'Contravalor de ICUOREA en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."ILIMIND_MONCON" IS 'Contravalor de ILIMIND en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."ILIQNET_MONCON" IS 'Contravalor de ILIQNET en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."ILIQREA_MONCON" IS 'Contravalor de ILIQREA en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IPAGREA_MONCON" IS 'Contravalor de IPAGREA en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESERV_MONCON" IS 'Contravalor de IRESERV en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESGAS_MONCON" IS 'Contravalor de IRESGAS en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESIND_MONCON" IS 'Contravalor de IRESIND en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESNET_MONCON" IS 'Contravalor de IRESNET en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESREA_MONCON" IS 'Contravalor de IRESREA en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."ITOTEXP_MONCON" IS 'Contravalor de ITOTEXP en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."ITOTIND_MONCON" IS 'Contravalor de ITOTIND en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."ITOTREA_MONCON" IS 'Contravalor de ITOTREA en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESINDEM" IS 'Importe Reserva Indemnizatoria (ctipres = 1)';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESINTER" IS 'Importe Reserva Intereses (ctipres = 2)';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESADMIN" IS 'Importe Reserva Administración (ctipres = 4)';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESINDEM_MONCON" IS 'Contravalor de IRESINDEM en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESINTER_MONCON" IS 'Contravalor de IRESINTER en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."IRESADMIN_MONCON" IS 'Contravalor de IRESADMIN en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."LIQUIDAREAXL_AUX"."CEVENTO" IS 'Código de evento';
   COMMENT ON TABLE "AXIS"."LIQUIDAREAXL_AUX"  IS 'Liquidacion de reaseguro XL (tabla auxiliar)';
  GRANT UPDATE ON "AXIS"."LIQUIDAREAXL_AUX" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."LIQUIDAREAXL_AUX" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."LIQUIDAREAXL_AUX" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."LIQUIDAREAXL_AUX" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."LIQUIDAREAXL_AUX" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."LIQUIDAREAXL_AUX" TO "PROGRAMADORESCSI";
