--------------------------------------------------------
--  DDL for Table MANDATOS_GESTION
--------------------------------------------------------

  CREATE TABLE "AXIS"."MANDATOS_GESTION" 
   (	"CAVISO" NUMBER, 
	"NUMFOLIO" NUMBER, 
	"FACCION" DATE, 
	"CUSUACCION" VARCHAR2(30 BYTE), 
	"ACCION" NUMBER, 
	"MOTRECHAZO" NUMBER, 
	"FPROXAVISO" DATE, 
	"COMENTARIO" VARCHAR2(2000 BYTE), 
	"SMANDOC_RECHAZO" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MANDATOS_GESTION"."CAVISO" IS 'Secuencial de aviso';
   COMMENT ON COLUMN "AXIS"."MANDATOS_GESTION"."NUMFOLIO" IS 'Número de folio (código de mandato de la compañía RSA)';
   COMMENT ON COLUMN "AXIS"."MANDATOS_GESTION"."FACCION" IS 'Fecha de acción';
   COMMENT ON COLUMN "AXIS"."MANDATOS_GESTION"."CUSUACCION" IS 'Usuario que realiza la acción';
   COMMENT ON COLUMN "AXIS"."MANDATOS_GESTION"."ACCION" IS 'Código Acción DETVALORES: 487';
   COMMENT ON COLUMN "AXIS"."MANDATOS_GESTION"."MOTRECHAZO" IS 'Motivo de rechazo DETVALORES: 488';
   COMMENT ON COLUMN "AXIS"."MANDATOS_GESTION"."FPROXAVISO" IS 'Fecha próximo aviso';
   COMMENT ON COLUMN "AXIS"."MANDATOS_GESTION"."COMENTARIO" IS 'Comentario';
   COMMENT ON COLUMN "AXIS"."MANDATOS_GESTION"."SMANDOC_RECHAZO" IS 'Secuencia documento rechazo';
   COMMENT ON TABLE "AXIS"."MANDATOS_GESTION"  IS 'Gestiones que se han realizado en un mandato';
  GRANT UPDATE ON "AXIS"."MANDATOS_GESTION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MANDATOS_GESTION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MANDATOS_GESTION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MANDATOS_GESTION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MANDATOS_GESTION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MANDATOS_GESTION" TO "PROGRAMADORESCSI";
