--------------------------------------------------------
--  DDL for Table MAP_DETALLE
--------------------------------------------------------

  CREATE TABLE "AXIS"."MAP_DETALLE" 
   (	"CMAPEAD" VARCHAR2(5 BYTE), 
	"NORDEN" NUMBER(4,0), 
	"NPOSICION" NUMBER(7,0), 
	"NLONGITUD" NUMBER(4,0), 
	"TTAG" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MAP_DETALLE"."CMAPEAD" IS 'Código del mapeador';
   COMMENT ON COLUMN "AXIS"."MAP_DETALLE"."NORDEN" IS 'Orden del campo en el fichero';
   COMMENT ON COLUMN "AXIS"."MAP_DETALLE"."NPOSICION" IS 'Posición en la que empieza el campo dentro del fichero si el fichero es de tipo 1';
   COMMENT ON COLUMN "AXIS"."MAP_DETALLE"."NLONGITUD" IS 'Longitud del campo en el fichero si este es de tipo 1';
   COMMENT ON COLUMN "AXIS"."MAP_DETALLE"."TTAG" IS 'Nombre del elemento del que se está buscando el valor para insertar';
  GRANT UPDATE ON "AXIS"."MAP_DETALLE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MAP_DETALLE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MAP_DETALLE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MAP_DETALLE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MAP_DETALLE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MAP_DETALLE" TO "PROGRAMADORESCSI";
