--------------------------------------------------------
--  DDL for Table MAP_CONDICION
--------------------------------------------------------

  CREATE TABLE "AXIS"."MAP_CONDICION" 
   (	"NCONDICION" NUMBER(8,0), 
	"TVALCOND" VARCHAR2(50 BYTE), 
	"NPOSCOND" NUMBER(7,0), 
	"NLONGCOND" NUMBER(4,0), 
	"NORDCOND" NUMBER(4,0), 
	"CTABLA" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MAP_CONDICION"."NCONDICION" IS 'Número de condición de línea';
   COMMENT ON COLUMN "AXIS"."MAP_CONDICION"."TVALCOND" IS 'Valor que debe cumplir la condición';
   COMMENT ON COLUMN "AXIS"."MAP_CONDICION"."NPOSCOND" IS 'Posición en la linia de parámetros del valor a cumplir';
   COMMENT ON COLUMN "AXIS"."MAP_CONDICION"."NLONGCOND" IS 'Longitud en la linia de parámetros del valor a cumplir';
   COMMENT ON COLUMN "AXIS"."MAP_CONDICION"."NORDCOND" IS 'Orden del campo en la tabla MAP_DETALLE';
   COMMENT ON COLUMN "AXIS"."MAP_CONDICION"."CTABLA" IS 'Tabla que contendrá la select que retornará el valor que debe compararse con tvalcon para ver si se cumple o no la condición';
  GRANT UPDATE ON "AXIS"."MAP_CONDICION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MAP_CONDICION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MAP_CONDICION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MAP_CONDICION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MAP_CONDICION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MAP_CONDICION" TO "PROGRAMADORESCSI";
