--------------------------------------------------------
--  DDL for Table MENU_DESROLMEN
--------------------------------------------------------

  CREATE TABLE "AXIS"."MENU_DESROLMEN" 
   (	"CROLMEN" VARCHAR2(20 BYTE), 
	"CIDIOMA" NUMBER(2,0), 
	"TROLMEN" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MENU_DESROLMEN"."CROLMEN" IS 'NombreID del Role';
   COMMENT ON COLUMN "AXIS"."MENU_DESROLMEN"."CIDIOMA" IS 'Idioma de la descripción';
   COMMENT ON COLUMN "AXIS"."MENU_DESROLMEN"."TROLMEN" IS 'Descripción del Role';
   COMMENT ON TABLE "AXIS"."MENU_DESROLMEN"  IS 'Descripción de los Roles de Usuario';
  GRANT UPDATE ON "AXIS"."MENU_DESROLMEN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MENU_DESROLMEN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MENU_DESROLMEN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MENU_DESROLMEN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MENU_DESROLMEN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MENU_DESROLMEN" TO "PROGRAMADORESCSI";
