--------------------------------------------------------
--  DDL for Table MENU_URL
--------------------------------------------------------

  CREATE TABLE "AXIS"."MENU_URL" 
   (	"CEMPRES" NUMBER(8,0), 
	"CMENU" NUMBER(8,0), 
	"TURL" VARCHAR2(500 BYTE), 
	"CVISTA" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."MENU_URL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MENU_URL" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MENU_URL" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MENU_URL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MENU_URL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MENU_URL" TO "PROGRAMADORESCSI";
