--------------------------------------------------------
--  DDL for Table MIG_CARGAS_TAB_AXIS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_CARGAS_TAB_AXIS" 
   (	"NCARGA" NUMBER, 
	"NTAB" NUMBER, 
	"NTABAXIS" NUMBER, 
	"TTABAXIS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_CARGAS_TAB_AXIS"."NCARGA" IS 'Número Carga';
   COMMENT ON COLUMN "AXIS"."MIG_CARGAS_TAB_AXIS"."NTAB" IS 'Numero tabla MIG';
   COMMENT ON COLUMN "AXIS"."MIG_CARGAS_TAB_AXIS"."NTABAXIS" IS 'Numero tabla AXIS';
   COMMENT ON COLUMN "AXIS"."MIG_CARGAS_TAB_AXIS"."TTABAXIS" IS 'Nombre tabla AXIS';
   COMMENT ON TABLE "AXIS"."MIG_CARGAS_TAB_AXIS"  IS 'Tabla Migración Cargas de MIG a AXIS';
  GRANT UPDATE ON "AXIS"."MIG_CARGAS_TAB_AXIS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_CARGAS_TAB_AXIS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_CARGAS_TAB_AXIS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_CARGAS_TAB_AXIS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_CARGAS_TAB_AXIS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_CARGAS_TAB_AXIS" TO "PROGRAMADORESCSI";
