--------------------------------------------------------
--  DDL for Table MIG_FIN_PARINDICADORES
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_FIN_PARINDICADORES" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"FECHA_EST_FIN" DATE, 
	"VT_PER_ANT" NUMBER, 
	"VENTAS" NUMBER, 
	"COSTO_VT" NUMBER, 
	"GASTO_ADM" NUMBER, 
	"UTIL_OPERAC" NUMBER, 
	"GASTO_FIN" NUMBER, 
	"RES_ANT_IMP" NUMBER, 
	"UTIL_NETA" NUMBER, 
	"INVENT" NUMBER, 
	"CARTE_CLIE" NUMBER, 
	"ACT_CORR" NUMBER, 
	"PROP_PLNT_EQP" NUMBER, 
	"TOT_ACT_NO_CORR" NUMBER, 
	"ACT_TOTAL" NUMBER, 
	"O_FIN_CORTO_PLAZO" VARCHAR2(2000 BYTE), 
	"PROVEE_CORTO_PLAZO" VARCHAR2(2000 BYTE), 
	"ATC_CORTO_PLAZO" NUMBER, 
	"PAS_CORR" VARCHAR2(2000 BYTE), 
	"O_FIN_LARGO_PLAZO" VARCHAR2(2000 BYTE), 
	"ATC_LARGO_PLAZO" NUMBER, 
	"PAS_NO_CORR" NUMBER, 
	"PAS_TOTAL" NUMBER, 
	"PATRI_PERI_ANT" NUMBER, 
	"PATRI_ANO_ACTUAL" NUMBER, 
	"RESV_LEGAL" NUMBER, 
	"CAP_SOCIAL" NUMBER, 
	"RES_EJER_ANT" NUMBER, 
	"PRIMA_ACCION" NUMBER, 
	"RESV_OCASI" NUMBER, 
	"VALORIZA" NUMBER, 
	"ASIGNADO" NUMBER, 
	"FUENTE_INFORMACION" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."MIG_PK" IS 'Clave ¿nica de MIG_FINPAR_INDICADORES';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."MIG_FK" IS 'Clave externa para MIG_FIN_INDICADORES';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."FECHA_EST_FIN" IS 'Fecha estados Financieros';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."VT_PER_ANT" IS 'Ventas Periodo Anterior';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."VENTAS" IS 'Ventas';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."COSTO_VT" IS 'Costo Ventas';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."GASTO_ADM" IS 'Gastos Administrativos';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."UTIL_OPERAC" IS 'Utilidad Operacional';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."GASTO_FIN" IS 'Gastos Financieros (P y G)';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."RES_ANT_IMP" IS 'Resultado antes de impuestos (P y G)';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."UTIL_NETA" IS 'Utilidad Neta';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."INVENT" IS 'Inventarios';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."CARTE_CLIE" IS 'Cartera Cliente';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."ACT_CORR" IS 'Activo Corriente';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."PROP_PLNT_EQP" IS 'Propiedad Planta y equipo';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."TOT_ACT_NO_CORR" IS 'Total Activo no corriente';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."ACT_TOTAL" IS 'Activo Total';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."O_FIN_CORTO_PLAZO" IS 'Obligaciones financieras corto plazo';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."PROVEE_CORTO_PLAZO" IS 'Proveedores Corto Plazo';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."ATC_CORTO_PLAZO" IS 'Anticipos corto Plazo';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."PAS_CORR" IS 'Pasivo Corriente';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."O_FIN_LARGO_PLAZO" IS 'Obligaciones financieras largo plazo';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."ATC_LARGO_PLAZO" IS 'Anticipos largo Plazo';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."PAS_NO_CORR" IS 'Total pasivo no corriente';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."PAS_TOTAL" IS 'Pasivo total';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."PATRI_PERI_ANT" IS 'Patrimonio periodo anterior';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."PATRI_ANO_ACTUAL" IS 'Patrimonio a¿o actual (BCE)';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."RESV_LEGAL" IS 'Reserva legal';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."CAP_SOCIAL" IS 'Capital Social';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."RES_EJER_ANT" IS 'Resultado Ejercicios Anteriores';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."PRIMA_ACCION" IS 'Prima en colocaci¿n de acciones';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."RESV_OCASI" IS 'Reservas ocasionales';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."VALORIZA" IS 'Valorizaciones';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."ASIGNADO" IS 'Inversi¿n suplementaria al capital asignado';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_PARINDICADORES"."FUENTE_INFORMACION" IS 'Fuente de Información (Cifin, BPR, Supersociedades)';
   COMMENT ON TABLE "AXIS"."MIG_FIN_PARINDICADORES"  IS 'Fichero con los datos de parámetros de indicadores de la ficha financiera.';
  GRANT UPDATE ON "AXIS"."MIG_FIN_PARINDICADORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_FIN_PARINDICADORES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_FIN_PARINDICADORES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_FIN_PARINDICADORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_FIN_PARINDICADORES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_FIN_PARINDICADORES" TO "PROGRAMADORESCSI";
