--------------------------------------------------------
--  DDL for Table MIG_GESTORAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_GESTORAS" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"MIG_FK2" VARCHAR2(50 BYTE), 
	"NNUMIDE" VARCHAR2(13 BYTE), 
	"TNOMGES" VARCHAR2(60 BYTE), 
	"CCODGES" NUMBER, 
	"CCODDEP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_GESTORAS"."NCARGA" IS 'Número de carga';
   COMMENT ON COLUMN "AXIS"."MIG_GESTORAS"."CESTMIG" IS 'Estado del registro';
   COMMENT ON COLUMN "AXIS"."MIG_GESTORAS"."MIG_PK" IS 'Código de la DGS';
   COMMENT ON COLUMN "AXIS"."MIG_GESTORAS"."MIG_FK" IS 'Clave externa MIG_DEPOSITARIAS DEPDGS';
   COMMENT ON COLUMN "AXIS"."MIG_GESTORAS"."MIG_FK2" IS 'Clave externa MIG_PERSONAS';
   COMMENT ON COLUMN "AXIS"."MIG_GESTORAS"."NNUMIDE" IS 'Identificador de la persona';
   COMMENT ON COLUMN "AXIS"."MIG_GESTORAS"."TNOMGES" IS 'Descripción de la Gestora';
   COMMENT ON COLUMN "AXIS"."MIG_GESTORAS"."CCODGES" IS 'Código de la Gestora (Interno)';
   COMMENT ON COLUMN "AXIS"."MIG_GESTORAS"."CCODDEP" IS 'Código de la Depositaria (Interno)';
   COMMENT ON TABLE "AXIS"."MIG_GESTORAS"  IS 'Tabla de Migración';
  GRANT UPDATE ON "AXIS"."MIG_GESTORAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_GESTORAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_GESTORAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_GESTORAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_GESTORAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_GESTORAS" TO "PROGRAMADORESCSI";
