--------------------------------------------------------
--  DDL for Table MIG_PSU_RETENIDAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_PSU_RETENIDAS" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"SSEGURO" NUMBER DEFAULT 0, 
	"FMOVIMI" DATE, 
	"CMOTRET" NUMBER(4,0), 
	"CUSURET" VARCHAR2(20 BYTE), 
	"FFECRET" DATE, 
	"CUSUAUT" VARCHAR2(20 BYTE), 
	"FFECAUT" DATE, 
	"OBSERV" VARCHAR2(4000 BYTE), 
	"CDETMOTREC" NUMBER(6,0), 
	"POSTPPER" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"PERPOST" NUMBER DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_PSU_RETENIDAS"."NCARGA" IS 'Número de carga';
   COMMENT ON COLUMN "AXIS"."MIG_PSU_RETENIDAS"."CESTMIG" IS 'Estado del registro valor inicial 1';
   COMMENT ON COLUMN "AXIS"."MIG_PSU_RETENIDAS"."MIG_PK" IS 'Clave única de MIG_PSU_RETENIDAS';
   COMMENT ON COLUMN "AXIS"."MIG_PSU_RETENIDAS"."MIG_FK" IS 'Clave externa para tabla (MIG_MOVSEGURO)';
   COMMENT ON COLUMN "AXIS"."MIG_PSU_RETENIDAS"."SSEGURO" IS 'Identificativo Seguros';
   COMMENT ON COLUMN "AXIS"."MIG_PSU_RETENIDAS"."FMOVIMI" IS 'Fecha Movseguro';
   COMMENT ON COLUMN "AXIS"."MIG_PSU_RETENIDAS"."CMOTRET" IS '0 = Autorizada, 1 = Pendiente Continuar,
                                              2 = Pendiente Autorizar, 3 = Bloqueada,
                                              4 = Rechazada, 5 = No Aplica por Cambio';
   COMMENT ON COLUMN "AXIS"."MIG_PSU_RETENIDAS"."CUSURET" IS 'Usuario grabador';
   COMMENT ON COLUMN "AXIS"."MIG_PSU_RETENIDAS"."FFECRET" IS 'Fecha retención';
   COMMENT ON COLUMN "AXIS"."MIG_PSU_RETENIDAS"."CUSUAUT" IS 'Usuario autoriza/rechaza';
   COMMENT ON COLUMN "AXIS"."MIG_PSU_RETENIDAS"."FFECAUT" IS 'Fecha autorización/rechazo';
   COMMENT ON COLUMN "AXIS"."MIG_PSU_RETENIDAS"."OBSERV" IS 'Observaciones';
   COMMENT ON COLUMN "AXIS"."MIG_PSU_RETENIDAS"."CDETMOTREC" IS 'Código de Motmovseg';
   COMMENT ON COLUMN "AXIS"."MIG_PSU_RETENIDAS"."POSTPPER" IS 'Periodo pospuesto de la propuesta V.F. 8001026.';
   COMMENT ON TABLE "AXIS"."MIG_PSU_RETENIDAS"  IS 'TAbla intermedia de migración de cabecera de los Controles PSU por póliza';
  GRANT UPDATE ON "AXIS"."MIG_PSU_RETENIDAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_PSU_RETENIDAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_PSU_RETENIDAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_PSU_RETENIDAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_PSU_RETENIDAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_PSU_RETENIDAS" TO "PROGRAMADORESCSI";
