--------------------------------------------------------
--  DDL for Table MIG_PREGUNSEGTAB
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_PREGUNSEGTAB" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0) DEFAULT 0, 
	"SSEGURO" NUMBER, 
	"CPREGUN" NUMBER(4,0), 
	"FILA" NUMBER, 
	"COLUMNA" VARCHAR2(50 BYTE), 
	"CRESPUE" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_PREGUNSEGTAB"."NCARGA" IS 'Número de carga';
   COMMENT ON COLUMN "AXIS"."MIG_PREGUNSEGTAB"."CESTMIG" IS 'Estado del registro';
   COMMENT ON COLUMN "AXIS"."MIG_PREGUNSEGTAB"."MIG_PK" IS 'Clave única de MIG_PREGUNSEG';
   COMMENT ON COLUMN "AXIS"."MIG_PREGUNSEGTAB"."MIG_FK" IS 'Clave externa para la póliza (MIG_SEGUROS)';
   COMMENT ON COLUMN "AXIS"."MIG_PREGUNSEGTAB"."NRIESGO" IS 'Número de riesgo, si NULL pregunta a nivel de póliza';
   COMMENT ON COLUMN "AXIS"."MIG_PREGUNSEGTAB"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."MIG_PREGUNSEGTAB"."SSEGURO" IS 'Número de secuencia de seguro, valor=0, lo calcula el proceso de migración';
   COMMENT ON COLUMN "AXIS"."MIG_PREGUNSEGTAB"."CPREGUN" IS 'Código Pregunta';
   COMMENT ON COLUMN "AXIS"."MIG_PREGUNSEGTAB"."FILA" IS 'Linea del desglose';
   COMMENT ON COLUMN "AXIS"."MIG_PREGUNSEGTAB"."COLUMNA" IS 'Identificador de la columna';
   COMMENT ON COLUMN "AXIS"."MIG_PREGUNSEGTAB"."CRESPUE" IS 'Valor de la respuesta';
   COMMENT ON TABLE "AXIS"."MIG_PREGUNSEGTAB"  IS 'Tabla Intermedia migración Preguntas de tipo tabla';
  GRANT UPDATE ON "AXIS"."MIG_PREGUNSEGTAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_PREGUNSEGTAB" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_PREGUNSEGTAB" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_PREGUNSEGTAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_PREGUNSEGTAB" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_PREGUNSEGTAB" TO "PROGRAMADORESCSI";
