--------------------------------------------------------
--  DDL for Table MIG_DETSARLATF_ACT
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_DETSARLATF_ACT" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"MIG_FK2" VARCHAR2(50 BYTE), 
	"CTIPOPROD" NUMBER, 
	"CIDNUMPROD" VARCHAR2(150 BYTE), 
	"TENTIDAD" VARCHAR2(150 BYTE), 
	"CMONTO" VARCHAR2(150 BYTE), 
	"CCIUDAD" NUMBER, 
	"CPAIS" NUMBER, 
	"CMONEDA" VARCHAR2(150 BYTE), 
	"SCPAIS" VARCHAR2(150 BYTE), 
	"STDEPB" VARCHAR2(150 BYTE), 
	"SCCIUDAD" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_DETSARLATF_ACT"."MIG_PK" IS 'Clave ¿nica de MIG_DETSARLATF_ACT';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLATF_ACT"."MIG_FK" IS 'Clave externa para MIG_DATSARLAFT';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLATF_ACT"."MIG_FK2" IS 'Clave externa para MIG_PERSONAS';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLATF_ACT"."CTIPOPROD" IS 'Tipo Producto';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLATF_ACT"."CIDNUMPROD" IS 'N¿mero de producto';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLATF_ACT"."TENTIDAD" IS 'Entidad';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLATF_ACT"."CMONTO" IS 'Monto';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLATF_ACT"."CCIUDAD" IS 'Ciudad';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLATF_ACT"."CPAIS" IS 'Pa¿s';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLATF_ACT"."CMONEDA" IS 'Moneda';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLATF_ACT"."SCPAIS" IS 'Pais';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLATF_ACT"."STDEPB" IS 'Departamento';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLATF_ACT"."SCCIUDAD" IS 'Ciudad';
  GRANT UPDATE ON "AXIS"."MIG_DETSARLATF_ACT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_DETSARLATF_ACT" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_DETSARLATF_ACT" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_DETSARLATF_ACT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_DETSARLATF_ACT" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_DETSARLATF_ACT" TO "PROGRAMADORESCSI";
