--------------------------------------------------------
--  DDL for Table MIG_LIQUIDACAB
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_LIQUIDACAB" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"CAGENTE" NUMBER, 
	"NLIQMEN" NUMBER(4,0), 
	"FLIQUID" DATE, 
	"FMOVIMI" DATE, 
	"CTIPOLIQ" NUMBER(2,0), 
	"CESTADO" NUMBER(3,0), 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FCOBRO" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_LIQUIDACAB"."MIG_PK" IS 'Clave ¿nica de MIG_LIQUIDACAB';
   COMMENT ON COLUMN "AXIS"."MIG_LIQUIDACAB"."CAGENTE" IS 'C¿digo de agente';
   COMMENT ON COLUMN "AXIS"."MIG_LIQUIDACAB"."NLIQMEN" IS 'N¿mero de  liquidaci¿n';
   COMMENT ON COLUMN "AXIS"."MIG_LIQUIDACAB"."FLIQUID" IS 'Fecha de liquidaci¿n';
   COMMENT ON COLUMN "AXIS"."MIG_LIQUIDACAB"."FMOVIMI" IS 'Fecha del movimiento';
   COMMENT ON COLUMN "AXIS"."MIG_LIQUIDACAB"."CTIPOLIQ" IS 'Tipo de liquidaci¿n (0 Real - 1 Previo)';
   COMMENT ON COLUMN "AXIS"."MIG_LIQUIDACAB"."CESTADO" IS 'Estado de la liquidaci¿n (1-Liquidado, 2-Liquidado importe, 3-Liquidada comisi¿n)';
   COMMENT ON COLUMN "AXIS"."MIG_LIQUIDACAB"."CUSUARI" IS 'Usuario que realiza la liquidaci¿n';
   COMMENT ON COLUMN "AXIS"."MIG_LIQUIDACAB"."FCOBRO" IS 'Fecha de cobro';
  GRANT UPDATE ON "AXIS"."MIG_LIQUIDACAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_LIQUIDACAB" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_LIQUIDACAB" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_LIQUIDACAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_LIQUIDACAB" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_LIQUIDACAB" TO "PROGRAMADORESCSI";
