--------------------------------------------------------
--  DDL for Table MIG_FIN_GENERAL
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_FIN_GENERAL" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"SFINANCI" NUMBER, 
	"TDESCRIP" VARCHAR2(2000 BYTE), 
	"FCCOMER" DATE, 
	"CFOTORUT" NUMBER, 
	"FRUT" DATE, 
	"TTITULO" VARCHAR2(2000 BYTE), 
	"CFOTOCED" NUMBER, 
	"FEXPICED" DATE, 
	"CPAIS" NUMBER, 
	"CPROVIN" NUMBER, 
	"CPOBLAC" NUMBER, 
	"TINFOAD" VARCHAR2(2000 BYTE), 
	"CCIIU" NUMBER, 
	"CTIPSOCI" NUMBER, 
	"CESTSOC" NUMBER, 
	"TOBJSOC" VARCHAR2(2000 BYTE), 
	"TEXPERI" VARCHAR2(3000 BYTE), 
	"FCONSTI" DATE, 
	"TVIGENC" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."MIG_PK" IS 'Clave ¿nica de MIG_FIN_GENERAL';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."MIG_FK" IS 'Clave externa para MIG_PERSONAS';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."SFINANCI" IS 'C¿digo ficha financiera (Si es nula se calcula de manera autom¿tica)';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."TDESCRIP" IS 'Descripci¿n de la ficha financiera';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."FCCOMER" IS 'Fecha c¿mara de comercio';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."CFOTORUT" IS 'Tiene fotocopia del RUT 0=No, 1=Si';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."FRUT" IS 'Fecha RUT';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."TTITULO" IS 'T¿tulo Obtenido';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."CFOTOCED" IS 'Tiene fotocopia de la cedula 0=No, 1=Si';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."FEXPICED" IS 'Fecha de expedici¿n de la cedula';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."CPAIS" IS 'Pa¿s';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."CPROVIN" IS 'Departamento';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."CPOBLAC" IS 'municipio';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."TINFOAD" IS 'Informaci¿n variada';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."CCIIU" IS 'C¿digo CIIU - Actividad econ¿mica V.F. 8001072';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."CTIPSOCI" IS 'Tipo Sociedad V.F. 8001073';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."CESTSOC" IS 'Estado de la sociedad V.F. 8001074';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."TOBJSOC" IS 'Objeto social';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."TEXPERI" IS 'Experiencia';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."FCONSTI" IS 'Fecha de constituci¿n';
   COMMENT ON COLUMN "AXIS"."MIG_FIN_GENERAL"."TVIGENC" IS 'Vigencia de la sociedad';
  GRANT UPDATE ON "AXIS"."MIG_FIN_GENERAL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_FIN_GENERAL" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_FIN_GENERAL" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_FIN_GENERAL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_FIN_GENERAL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_FIN_GENERAL" TO "PROGRAMADORESCSI";
