--------------------------------------------------------
--  DDL for Table MIG_MOVRECIBO
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_MOVRECIBO" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"NRECIBO" NUMBER, 
	"SMOVREC" NUMBER, 
	"CESTREC" NUMBER(1,0), 
	"FMOVINI" DATE, 
	"FMOVFIN" DATE, 
	"FEFEADM" DATE, 
	"FMOVDIA" DATE, 
	"CMOTMOV" NUMBER(3,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_MOVRECIBO"."NCARGA" IS 'N¿mero de carga';
   COMMENT ON COLUMN "AXIS"."MIG_MOVRECIBO"."CESTMIG" IS 'Estado del registro';
   COMMENT ON COLUMN "AXIS"."MIG_MOVRECIBO"."MIG_PK" IS 'Clave ¿nica de MIG_MOVRECIBO';
   COMMENT ON COLUMN "AXIS"."MIG_MOVRECIBO"."MIG_FK" IS 'Clave externa para el recibo (MIG_RECIBOS)';
   COMMENT ON COLUMN "AXIS"."MIG_MOVRECIBO"."CESTREC" IS 'Estado Recibo 0-Pendiente,1-cobrado,2-anulado';
   COMMENT ON COLUMN "AXIS"."MIG_MOVRECIBO"."FMOVINI" IS 'Fecha inicial del movimiento';
   COMMENT ON COLUMN "AXIS"."MIG_MOVRECIBO"."FMOVFIN" IS 'Fecha final del movimiento';
   COMMENT ON COLUMN "AXIS"."MIG_MOVRECIBO"."FEFEADM" IS 'Fecha efecto del movimiento a nivel administrativo';
   COMMENT ON COLUMN "AXIS"."MIG_MOVRECIBO"."CMOTMOV" IS 'Codigo motivo movimiento';
   COMMENT ON TABLE "AXIS"."MIG_MOVRECIBO"  IS 'Tabla Intermedia migraci¿n movimientos de Recibos';
  GRANT UPDATE ON "AXIS"."MIG_MOVRECIBO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_MOVRECIBO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_MOVRECIBO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_MOVRECIBO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_MOVRECIBO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_MOVRECIBO" TO "PROGRAMADORESCSI";
