--------------------------------------------------------
--  DDL for Table MIG_VALIDACION
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_VALIDACION" 
   (	"SPRODUC" NUMBER(6,0), 
	"NORDEN" NUMBER(4,0), 
	"TVALIDACION" VARCHAR2(4000 BYTE), 
	"PANTALLA" VARCHAR2(100 BYTE), 
	"TINFO" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_VALIDACION"."SPRODUC" IS 'Número de carga';
   COMMENT ON COLUMN "AXIS"."MIG_VALIDACION"."NORDEN" IS 'Orden en que se ejecutarán las validaciones';
   COMMENT ON COLUMN "AXIS"."MIG_VALIDACION"."TVALIDACION" IS 'Función a ejecutar';
   COMMENT ON COLUMN "AXIS"."MIG_VALIDACION"."PANTALLA" IS 'Pantallas donde se ejecuta la validación';
   COMMENT ON COLUMN "AXIS"."MIG_VALIDACION"."TINFO" IS 'Información sobre la función que se realiza';
   COMMENT ON TABLE "AXIS"."MIG_VALIDACION"  IS 'Tabla de configuración de validaciones en migración';
  GRANT UPDATE ON "AXIS"."MIG_VALIDACION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_VALIDACION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_VALIDACION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_VALIDACION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_VALIDACION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_VALIDACION" TO "PROGRAMADORESCSI";
