--------------------------------------------------------
--  DDL for Table MIG_DIRECCIONES
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_DIRECCIONES" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"SPERSON" NUMBER(10,0), 
	"CAGENTE" NUMBER, 
	"CDOMICI" NUMBER, 
	"CPOSTAL" VARCHAR2(30 BYTE), 
	"CPROVIN" NUMBER, 
	"CPOBLAC" NUMBER, 
	"CSIGLAS" NUMBER(2,0), 
	"TNOMVIA" VARCHAR2(200 BYTE), 
	"NNUMVIA" NUMBER(5,0), 
	"TCOMPLE" VARCHAR2(100 BYTE), 
	"CTIPDIR" NUMBER(2,0), 
	"CVIAVP" NUMBER(2,0), 
	"CLITVP" NUMBER(2,0), 
	"CBISVP" NUMBER(2,0), 
	"CORVP" NUMBER(2,0), 
	"NVIAADCO" NUMBER(5,0), 
	"CLITCO" NUMBER(2,0), 
	"CORCO" NUMBER(2,0), 
	"NPLACACO" NUMBER(5,0), 
	"COR2CO" NUMBER(2,0), 
	"CDET1IA" NUMBER(2,0), 
	"TNUM1IA" VARCHAR2(100 BYTE), 
	"CDET2IA" NUMBER(2,0), 
	"TNUM2IA" VARCHAR2(100 BYTE), 
	"CDET3IA" NUMBER(2,0), 
	"TNUM3IA" VARCHAR2(100 BYTE), 
	"LOCALIDAD" VARCHAR2(3000 BYTE), 
	"PROCESO" NUMBER, 
	"TNUMTEL" VARCHAR2(20 BYTE), 
	"TNUMFAX" VARCHAR2(20 BYTE), 
	"TNUMMOV" VARCHAR2(20 BYTE), 
	"TEMAIL" VARCHAR2(100 BYTE), 
	"TALIAS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."SPERSON" IS 'Número de secuencia de persona, valor=0, lo calcula el proceso de migración';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."CDOMICI" IS 'Código de domicilio';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."CPOSTAL" IS 'Código postal';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."CPROVIN" IS 'Código de Provincia';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."CPOBLAC" IS 'Código de Población';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."CVIAVP" IS 'Código de via predio - via principal';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."CLITVP" IS 'Código de literal predio - via principal';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."CBISVP" IS 'Código BIS predio - via principal';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."CORVP" IS 'Código orientación predio - via principal';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."NVIAADCO" IS 'Número de via adyacente predio - coordenada';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."CLITCO" IS 'Código de literal predio - coordenada';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."CORCO" IS 'Código orientación predio - coordenada';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."NPLACACO" IS 'Número consecutivo placa predio - ccordenada';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."COR2CO" IS 'Código orientación predio 2 - coordenada';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."CDET1IA" IS 'Código detalle 1 - información adicional';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."TNUM1IA" IS 'Número predio 1 - informacion adicional';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."CDET2IA" IS 'Código detalle 2 - información adicional';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."TNUM2IA" IS 'Número predio 2 - informacion adicional';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."CDET3IA" IS 'Código detalle 3 - información adicional';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."TNUM3IA" IS 'Número predio 3 - informacion adicional';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."LOCALIDAD" IS 'Localidad';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."PROCESO" IS 'Id.Proceso que ha cargado';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."TNUMTEL" IS 'N¿mero de tel¿fono';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."TNUMFAX" IS 'N¿mero de fax';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."TNUMMOV" IS 'N¿mero de m¿vil';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."TEMAIL" IS 'Email';
   COMMENT ON COLUMN "AXIS"."MIG_DIRECCIONES"."TALIAS" IS 'Alias de la direcci¿n';
   COMMENT ON TABLE "AXIS"."MIG_DIRECCIONES"  IS 'Tabla para la migración de direcciones';
  GRANT UPDATE ON "AXIS"."MIG_DIRECCIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_DIRECCIONES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_DIRECCIONES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_DIRECCIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_DIRECCIONES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_DIRECCIONES" TO "PROGRAMADORESCSI";
