--------------------------------------------------------
--  DDL for Table MIG_REEMPLAZOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_REEMPLAZOS" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"SSEGURO" NUMBER, 
	"SREEMPL" NUMBER, 
	"FMOVDIA" DATE, 
	"CUSUARIO" VARCHAR2(20 BYTE), 
	"CAGENTE" NUMBER, 
	"CTIPO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_REEMPLAZOS"."NCARGA" IS 'Número de carga';
   COMMENT ON COLUMN "AXIS"."MIG_REEMPLAZOS"."CESTMIG" IS 'Estado del registro valor inicial 1';
   COMMENT ON COLUMN "AXIS"."MIG_REEMPLAZOS"."SSEGURO" IS 'Identificador de póliza nueva';
   COMMENT ON COLUMN "AXIS"."MIG_REEMPLAZOS"."SREEMPL" IS 'Identificador de póliza reemplazada';
   COMMENT ON COLUMN "AXIS"."MIG_REEMPLAZOS"."FMOVDIA" IS 'Fecha del movimiento';
   COMMENT ON COLUMN "AXIS"."MIG_REEMPLAZOS"."CUSUARIO" IS 'Código de usuario';
   COMMENT ON COLUMN "AXIS"."MIG_REEMPLAZOS"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."MIG_REEMPLAZOS"."CTIPO" IS 'Tipo de reemplazo (1 - reemplazo, 2 - póliza prorrogada, 3 - póliza saldada';
   COMMENT ON TABLE "AXIS"."MIG_REEMPLAZOS"  IS 'Tabla Intermedia migración de pólizas reemplazadas';
  GRANT UPDATE ON "AXIS"."MIG_REEMPLAZOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_REEMPLAZOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_REEMPLAZOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_REEMPLAZOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_REEMPLAZOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_REEMPLAZOS" TO "PROGRAMADORESCSI";
