--------------------------------------------------------
--  DDL for Table MIG_CTGAR_CODEUDOR
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_CTGAR_CODEUDOR" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"MIG_FK2" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_CTGAR_CODEUDOR"."MIG_PK" IS 'Clave ¿nica de MIG_CTGAR_CODEUDOR';
   COMMENT ON COLUMN "AXIS"."MIG_CTGAR_CODEUDOR"."MIG_FK" IS 'Clave externa para MIG_CTGAR_CONTRAGARANTIA';
   COMMENT ON COLUMN "AXIS"."MIG_CTGAR_CODEUDOR"."MIG_FK2" IS 'Clave externa para MIG_PERSONAS';
  GRANT INSERT ON "AXIS"."MIG_CTGAR_CODEUDOR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_CTGAR_CODEUDOR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_CTGAR_CODEUDOR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_CTGAR_CODEUDOR" TO "PROGRAMADORESCSI";
  GRANT UPDATE ON "AXIS"."MIG_CTGAR_CODEUDOR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_CTGAR_CODEUDOR" TO "R_AXIS";
