--------------------------------------------------------
--  DDL for Table MIG_DETSARLAFT_REC
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_DETSARLAFT_REC" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"MIG_FK2" VARCHAR2(50 BYTE), 
	"CANIO" NUMBER, 
	"CRAMO" NUMBER, 
	"TCOMPANIA" VARCHAR2(150 BYTE), 
	"CVALOR" VARCHAR2(150 BYTE), 
	"TRESULTADO" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_DETSARLAFT_REC"."MIG_PK" IS 'Clave ¿nica de MIG_DETSARLAFT_REC';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLAFT_REC"."MIG_FK" IS 'Clave externa para MIG_DATSARLAFT';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLAFT_REC"."MIG_FK2" IS 'Clave externa para MIG_PERSONAS';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLAFT_REC"."CANIO" IS 'A¿o';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLAFT_REC"."CRAMO" IS 'Ramo';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLAFT_REC"."TCOMPANIA" IS 'CompaC1ia';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLAFT_REC"."CVALOR" IS 'Valor';
   COMMENT ON COLUMN "AXIS"."MIG_DETSARLAFT_REC"."TRESULTADO" IS 'Resultado';
  GRANT UPDATE ON "AXIS"."MIG_DETSARLAFT_REC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_DETSARLAFT_REC" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_DETSARLAFT_REC" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_DETSARLAFT_REC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_DETSARLAFT_REC" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_DETSARLAFT_REC" TO "PROGRAMADORESCSI";
