--------------------------------------------------------
--  DDL for Table MIG_SIN_TRAMITA_VALPRETENSION
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"MIG_FK2" VARCHAR2(50 BYTE), 
	"NORDEN" NUMBER(3,0), 
	"CGARANT" NUMBER(4,0), 
	"IPRETEN" NUMBER, 
	"FBAJA" DATE, 
	"FMODIFI" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION"."MIG_PK" IS 'Clave ¿nica de MIG_SIN_TRAMITA_VALPRETENSION';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION"."MIG_FK" IS 'Clave externa de MIG_SIN_SINIESTRO';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION"."MIG_FK2" IS 'Clave externa de MIG_SIN_TRAMITA_JUDICIAL';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION"."NORDEN" IS 'Numero Orden Proceso';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION"."CGARANT" IS 'C¿digo de garant¿a';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION"."IPRETEN" IS 'Importe de pretensi¿n';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION"."FBAJA" IS 'Fecha Baja Registro';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION"."FMODIFI" IS 'Fecha Creaci¿n/Modificaci¿n';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION"."CUSUALT" IS 'C¿digo Usuario Alta';
  GRANT UPDATE ON "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_SIN_TRAMITA_VALPRETENSION" TO "PROGRAMADORESCSI";
