--------------------------------------------------------
--  DDL for Table MIG_SIN_PROF_ESTADOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_SIN_PROF_ESTADOS" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"PROCESO" NUMBER, 
	"SPROFES" NUMBER(8,0), 
	"CESTADO" NUMBER, 
	"FESTADO" DATE, 
	"CMOTBAJ" NUMBER, 
	"TOBSERV" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_ESTADOS"."PROCESO" IS 'Id. Proceso que ha cargado';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_ESTADOS"."SPROFES" IS 'Codigo de profesional';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_ESTADOS"."CESTADO" IS '1-Activo 2-Inactivo 3-Baja';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_ESTADOS"."FESTADO" IS 'Fecha estado';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_ESTADOS"."CMOTBAJ" IS 'Motivo baja. VF 737';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_ESTADOS"."TOBSERV" IS 'Observaciones estado';
  GRANT UPDATE ON "AXIS"."MIG_SIN_PROF_ESTADOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_SIN_PROF_ESTADOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_SIN_PROF_ESTADOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_SIN_PROF_ESTADOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_SIN_PROF_ESTADOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_SIN_PROF_ESTADOS" TO "PROGRAMADORESCSI";
