BEGIN
  PAC_SKIP_ORA.P_COMPROVADROP('MIG_TRAMOS_UAT','TABLE');
END;
/
create table MIG_TRAMOS_UAT
(
  mig_pk         VARCHAR2(50),
  mig_fk         VARCHAR2(50),
  nversio        NUMBER(2),
  scontra        NUMBER(6),
  ctramo         NUMBER(5),
  itottra        NUMBER,
  nplenos        NUMBER(6),
  cfrebor        NUMBER(2),
  plocal         NUMBER(5,2),
  ixlprio        NUMBER,
  ixlexce        NUMBER,
  pslprio        NUMBER(5),
  pslexce        NUMBER(5),
  ncesion        NUMBER(6),
  fultbor        DATE,
  imaxplo        NUMBER,
  norden         NUMBER(5),
  nsegcon        NUMBER(6),
  nsegver        NUMBER(2),
  iminxl         NUMBER,
  idepxl         NUMBER,
  nctrxl         NUMBER(6),
  nverxl         NUMBER(2),
  ptasaxl        NUMBER(6),
  ipmd           NUMBER,
  cfrepmd        NUMBER(2),
  caplixl        NUMBER(1),
  plimgas        NUMBER(5),
  pliminx        NUMBER(5),
  idaa           NUMBER,
  ilaa           NUMBER,
  ctprimaxl      NUMBER(1),
  iprimafijaxl   NUMBER,
  iprimaestimada NUMBER,
  caplictasaxl   NUMBER(1),
  ctiptasaxl     NUMBER(1),
  ctramotasaxl   NUMBER(5),
  pctpdxl        NUMBER(5),
  cforpagpdxl    NUMBER(1),
  pctminxl       NUMBER(5),
  pctpb          NUMBER(5),
  nanyosloss     NUMBER(2),
  closscorridor  NUMBER(5),
  ccappedratio   NUMBER(5),
  crepos         NUMBER(5),
  ibonorec       NUMBER,
  impaviso       NUMBER,
  impcontado     NUMBER,
  pctcontado     NUMBER(5),
  pctgastos      NUMBER(5),
  ptasaajuste    NUMBER(5),
  icapcoaseg     NUMBER,
  preest         NUMBER,
  icostofijo     NUMBER,
  pcomisinterm   NUMBER,
  narrastrecont  NUMBER,
  ptramo         NUMBER,
  piprio         NUMBER
);
/