--------------------------------------------------------
--  DDL for Table MIG_GESCARTAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_GESCARTAS" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"SGESCARTA" NUMBER(8,0), 
	"CTIPCAR" NUMBER(2,0), 
	"SSEGURO" NUMBER, 
	"SPERSON" NUMBER(10,0), 
	"CGARANT" NUMBER(6,0), 
	"NRECIBO" NUMBER, 
	"FSOLICI" DATE, 
	"USUSOL" VARCHAR2(30 BYTE), 
	"FIMPRES" DATE, 
	"USUIMP" VARCHAR2(30 BYTE), 
	"CESTADO" NUMBER(2,0), 
	"NIMPRES" NUMBER(3,0) DEFAULT 0, 
	"CIMPRIMIR" VARCHAR2(30 BYTE), 
	"SCARAGR" NUMBER(6,0), 
	"NRESUL" NUMBER(6,0), 
	"SDEVOLU" NUMBER(6,0), 
	"SMOVREC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."NCARGA" IS 'Número de carga';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."CESTMIG" IS 'Estado del registro valor inicial 1';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."MIG_PK" IS 'Clave única de MIG_AGENSEGU';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."MIG_FK" IS 'Clave externa para la póliza (MIG_SEGUROS)';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."SGESCARTA" IS 'Secuencia de carta a imprimir';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."CTIPCAR" IS 'Tipo de carta';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."SSEGURO" IS 'Póliza';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."SPERSON" IS 'Persona a quien va dirigido el documento ( Tomador / riesgo )';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."CGARANT" IS 'Garantia';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."NRECIBO" IS 'Recibo';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."FSOLICI" IS 'Fecha solicitud de impresión';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."USUSOL" IS 'Usuario que solicita el documento';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."FIMPRES" IS 'Fecha de impresión del documento';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."USUIMP" IS 'Usuario que imprime el documento';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."CESTADO" IS 'Estado del documento Vf: 904';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."NIMPRES" IS 'Número de impresiones realizadas';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."CIMPRIMIR" IS 'Un 1 indica que el documento se va a imprimir';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."SCARAGR" IS 'Secuencia de agrupación de cartas';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."NRESUL" IS 'Resultado de la última impresión';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."SDEVOLU" IS 'Identificar de la devolución (si procede)';
   COMMENT ON COLUMN "AXIS"."MIG_GESCARTAS"."SMOVREC" IS 'Secuencial del movimiento del recibo';
   COMMENT ON TABLE "AXIS"."MIG_GESCARTAS"  IS 'Gestión de cartas a imprimir';
  GRANT UPDATE ON "AXIS"."MIG_GESCARTAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_GESCARTAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_GESCARTAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_GESCARTAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_GESCARTAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_GESCARTAS" TO "PROGRAMADORESCSI";
