--------------------------------------------------------
--  DDL for Table MIG_GARANDETCAP
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_GARANDETCAP" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"CGARANT" NUMBER(4,0), 
	"NMOVIMI" NUMBER(4,0), 
	"NORDEN" NUMBER(4,0), 
	"CCONCEPTO" NUMBER(4,0), 
	"TDESCRIP" VARCHAR2(100 BYTE), 
	"ICAPITAL" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_GARANDETCAP"."NCARGA" IS 'Número de carga';
   COMMENT ON COLUMN "AXIS"."MIG_GARANDETCAP"."CESTMIG" IS 'Estado del registro';
   COMMENT ON COLUMN "AXIS"."MIG_GARANDETCAP"."MIG_PK" IS 'Clave única (PK)';
   COMMENT ON COLUMN "AXIS"."MIG_GARANDETCAP"."MIG_FK" IS 'Clave externa (FK)';
   COMMENT ON COLUMN "AXIS"."MIG_GARANDETCAP"."SSEGURO" IS 'Identificador de la póliza';
   COMMENT ON COLUMN "AXIS"."MIG_GARANDETCAP"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."MIG_GARANDETCAP"."CGARANT" IS 'Código de la garantía';
   COMMENT ON COLUMN "AXIS"."MIG_GARANDETCAP"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."MIG_GARANDETCAP"."NORDEN" IS 'Número orden de detalle';
   COMMENT ON COLUMN "AXIS"."MIG_GARANDETCAP"."CCONCEPTO" IS 'Concepto del Desglose, puede ser nulo';
   COMMENT ON COLUMN "AXIS"."MIG_GARANDETCAP"."TDESCRIP" IS 'Descripción detalle';
   COMMENT ON COLUMN "AXIS"."MIG_GARANDETCAP"."ICAPITAL" IS 'Importe detalle';
   COMMENT ON TABLE "AXIS"."MIG_GARANDETCAP"  IS 'Contiene los detalles de los capitales de las garantias.';
  GRANT UPDATE ON "AXIS"."MIG_GARANDETCAP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_GARANDETCAP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_GARANDETCAP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_GARANDETCAP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_GARANDETCAP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_GARANDETCAP" TO "PROGRAMADORESCSI";
