--------------------------------------------------------
--  DDL for Table MIG_GARANSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_GARANSEG" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"CGARANT" NUMBER(4,0), 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"SSEGURO" NUMBER, 
	"FINIEFE" DATE, 
	"ICAPITAL" NUMBER, 
	"PRECARG" NUMBER(6,2), 
	"IEXTRAP" NUMBER(19,12), 
	"IPRIANU" NUMBER, 
	"FFINEFE" DATE, 
	"IRECARG" NUMBER, 
	"IPRITAR" NUMBER, 
	"FALTA" DATE, 
	"CREVALI" NUMBER(2,0), 
	"PREVALI" NUMBER(8,5), 
	"IREVALI" NUMBER, 
	"NMOVIMA" NUMBER(4,0), 
	"PDTOCOM" NUMBER(6,2), 
	"IDTOCOM" NUMBER, 
	"ITOTANU" NUMBER, 
	"PDTOTEC" NUMBER(6,2), 
	"PRECCOM" NUMBER(6,2), 
	"IDTOTEC" NUMBER, 
	"IRECCOM" NUMBER, 
	"FINIVIG" DATE, 
	"FFINVIG" DATE, 
	"CCOBPRIMA" NUMBER, 
	"IPRIDEV" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."NCARGA" IS 'Número de carga';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."CESTMIG" IS 'Estado del registro valor inicial 1';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."MIG_PK" IS 'Clave única de MIG_GARANSEG';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."MIG_FK" IS 'Clave externa para la póliza (MIG_SEGUROS)';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."CGARANT" IS 'Código Garantia';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."SSEGURO" IS 'Número de secuencia de seguro, valor=0, lo calcula el proceso de migración';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."FINIEFE" IS 'fecha inicio de efecto';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."ICAPITAL" IS 'Importe garantía';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."PRECARG" IS 'Porcentaje de recargo';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."IEXTRAP" IS 'Extraprima';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."IPRIANU" IS 'Importe prima manual';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."FFINEFE" IS 'Fecha fin de efecto';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."IRECARG" IS 'Importe del recargo';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."IPRITAR" IS 'Importe tarifa';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."FALTA" IS 'Fecha en que se dio de alta la Garantía';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."CREVALI" IS 'Código Revalorización VF 62';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."PREVALI" IS 'Porcentaje de revalorizacion';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."IREVALI" IS 'Importe de revalorizacion';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."NMOVIMA" IS 'Número de movimiento de alta';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."PDTOCOM" IS 'Porcentaje descuento comercial';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."IDTOCOM" IS 'Importe descuento comercial';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."ITOTANU" IS 'Total prima anualizada';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."PDTOTEC" IS 'Porcentaje descuento técnico';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."PRECCOM" IS 'Porcentaje recargo comercial';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."IDTOTEC" IS 'Importe descuento técnico';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."IRECCOM" IS 'Importe recargo comercial';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."FINIVIG" IS 'Fecha inicio vigencia cobertura';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."FFINVIG" IS 'Fecha fin vigencia cobertura';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."CCOBPRIMA" IS 'Cobra Prima';
   COMMENT ON COLUMN "AXIS"."MIG_GARANSEG"."IPRIDEV" IS 'Prima Devengada';
   COMMENT ON TABLE "AXIS"."MIG_GARANSEG"  IS 'Tabla Intermedia migración Garantias';
  GRANT UPDATE ON "AXIS"."MIG_GARANSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_GARANSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_GARANSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_GARANSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_GARANSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_GARANSEG" TO "PROGRAMADORESCSI";
