--------------------------------------------------------
--  DDL for Table MIG_SINIESTROS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_SINIESTROS" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"NSINIES" NUMBER(8,0), 
	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FSINIES" DATE, 
	"FNOTIFI" DATE, 
	"CESTSIN" NUMBER(2,0), 
	"TSINIES" VARCHAR2(500 BYTE), 
	"CCAUEST" NUMBER(4,0), 
	"CCAUSIN" NUMBER(4,0), 
	"NSINREF" NUMBER(8,0), 
	"IPROMES" NUMBER, 
	"IPRO31D" NUMBER, 
	"FESTSIN" DATE, 
	"IPROANT" NUMBER, 
	"NSINCOA" VARCHAR2(16 BYTE), 
	"NCUACOA" NUMBER(2,0), 
	"FENTRAD" DATE, 
	"CCONSOR" NUMBER(1,0), 
	"SEVENTO" NUMBER(6,0), 
	"CORIGEN" NUMBER(2,0), 
	"CREFINT" VARCHAR2(50 BYTE), 
	"CRAMO" NUMBER(8,0), 
	"CTRAINT" VARCHAR2(20 BYTE), 
	"CTRAEXT" VARCHAR2(20 BYTE), 
	"CDELEGA" NUMBER, 
	"CMOTSIN" NUMBER(4,0), 
	"CTIPCOA" NUMBER(1,0), 
	"CCULPAB" NUMBER(1,0), 
	"CUNIMIX" NUMBER(1,0), 
	"CASETA" NUMBER(1,0), 
	"CIDEASC" NUMBER(1,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"NMOVIMI" NUMBER(4,0), 
	"CINTJUD" NUMBER(2,0), 
	"CTCAUSIN" NUMBER(1,0), 
	"CORGJUD" NUMBER(2,0), 
	"NORGJUD" NUMBER(3,0), 
	"TREFJUD" VARCHAR2(20 BYTE), 
	"CPROJUD" NUMBER(5,0), 
	"CPOBLJUD" NUMBER(5,0), 
	"CPAISJUD" NUMBER(3,0), 
	"CPOSTJUD" VARCHAR2(30 BYTE), 
	"CDIRJUD" VARCHAR2(30 BYTE), 
	"CINTAUT" NUMBER(2,0), 
	"FCOMCOR" DATE, 
	"CAGUA" NUMBER(1,0), 
	"NSUBEST" NUMBER(3,0), 
	"NASEGUR" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."NCARGA" IS 'Número de carga';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CESTMIG" IS 'Estado del registro';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."MIG_PK" IS 'Clave única de MIG_SINIESTROS';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."MIG_FK" IS 'Clave externa para el seguro (MIG_SEGUROS)';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."NSINIES" IS 'Número de siniestro, si nulo lo calcula el proceso de migración';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."SSEGURO" IS 'Número seguro, valor 0 lo calcula el proceso de migración';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CUSUARI" IS 'Abridor';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."FSINIES" IS 'Fecha del siniestro';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."FNOTIFI" IS 'Fecha de notificación';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CESTSIN" IS 'Estado del siniestro.';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."TSINIES" IS 'Desc. Siniestro';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CCAUEST" IS 'Código causa del estado';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CCAUSIN" IS 'Código causa siniestro';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."NSINREF" IS 'Ref. a otro siniestro para temas de listado ( No se utiliza )';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."IPROMES" IS 'Importe de la provision del mes anterior ( No se utiliza )';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."IPRO31D" IS 'Importe de la provisión a 31 de diciembre ( No se utiliza )';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."FESTSIN" IS 'Fecha del último cambio de estado';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."IPROANT" IS 'Importe de la provisión mes anterior';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."NSINCOA" IS 'Núm. del siniestro para la empresa COA';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."NCUACOA" IS 'Cuadro de coaseguro a aplicar';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."FENTRAD" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CCONSOR" IS 'Codigo consorcio ( No se utiliza )';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."SEVENTO" IS 'Agrupación de siniestros posterior a su creacion (No se utiliza)';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CORIGEN" IS '(No se utiliza)';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CREFINT" IS 'Ref. del siniestro. Alternativa a NSINIES configurable por instalacion';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CRAMO" IS 'Id del ramo';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CTRAINT" IS 'Gestor principal';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CTRAEXT" IS 'Id tramitador externo';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CDELEGA" IS 'Delegación del seguro en la fecha del siniestro';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CMOTSIN" IS 'Código motivo siniestro';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CTIPCOA" IS 'Tipo de COA sel seguro en el momento del siniestro';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CCULPAB" IS 'Culpabilidad:0,Indeterminada.1,Asegurado.2,Contrario.3,Contradictorio';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CUNIMIX" IS 'Incluido en el convenio de Unidades mixtas';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CASETA" IS 'Incluido en el convenio de ASETA ( Daños en los inmuebles de la autopista )';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."CIDEASC" IS 'Incluido en el convenio CIDE/ASCIDE ( Colision de vehiculos 1 a 1';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."NMOVIMI" IS 'Número de movimiento de la póliza que "provoca" el siniestro (si lo hay)';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."NSUBEST" IS 'Numero de SubEstado';
   COMMENT ON COLUMN "AXIS"."MIG_SINIESTROS"."NASEGUR" IS 'Número de asegurado. Sólo se utilizará en productos a 2 cabezas.';
   COMMENT ON TABLE "AXIS"."MIG_SINIESTROS"  IS 'Tabla Intermedia migración de Siniestros';
  GRANT UPDATE ON "AXIS"."MIG_SINIESTROS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_SINIESTROS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_SINIESTROS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_SINIESTROS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_SINIESTROS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_SINIESTROS" TO "PROGRAMADORESCSI";
