--------------------------------------------------------
--  DDL for Table MIG_SIN_PROF_CCC
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_SIN_PROF_CCC" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"PROCESO" NUMBER, 
	"SPROFES" NUMBER(8,0), 
	"CNORDEN" NUMBER, 
	"CRAMO" NUMBER, 
	"SPRODUC" NUMBER, 
	"CACTIVI" NUMBER, 
	"CTIPBAN" NUMBER(3,0), 
	"CBANCAR" VARCHAR2(50 BYTE), 
	"FBAJA" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_CCC"."PROCESO" IS 'Id. Proceso que ha cargado';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_CCC"."SPROFES" IS 'Codigo de profesional';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_CCC"."CNORDEN" IS 'Codigo unico consecutivo que identifica el registro';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_CCC"."CRAMO" IS 'Codigo de ramo';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_CCC"."SPRODUC" IS 'Clave de PRODUCTOS';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_CCC"."CACTIVI" IS 'Codigo de actividad';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_CCC"."CTIPBAN" IS 'Tipo de cuenta ( iban o cuenta bancaria). [tabla maestra: TIPOS_CUENTA]';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_CCC"."CBANCAR" IS 'Cuenta bancaria';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_PROF_CCC"."FBAJA" IS 'Fecha de baja';
  GRANT UPDATE ON "AXIS"."MIG_SIN_PROF_CCC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_SIN_PROF_CCC" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_SIN_PROF_CCC" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_SIN_PROF_CCC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_SIN_PROF_CCC" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_SIN_PROF_CCC" TO "PROGRAMADORESCSI";
