--------------------------------------------------------
--  DDL for Table MIG_PER_AGR_MARCAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_PER_AGR_MARCAS" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"CMARCA" VARCHAR2(10 BYTE), 
	"CTIPO" NUMBER, 
	"CTOMADOR" NUMBER, 
	"CCONSORCIO" NUMBER, 
	"CASEGURADO" NUMBER, 
	"CCODEUDOR" NUMBER, 
	"CBENEF" NUMBER, 
	"CACCIONISTA" NUMBER, 
	"CINTERMED" NUMBER, 
	"CREPRESEN" NUMBER, 
	"CAPODERADO" NUMBER, 
	"CPAGADOR" NUMBER, 
	"TOBSEVA" VARCHAR2(2000 BYTE), 
	"NMOVIMI" NUMBER, 
	"CPROVEEDOR" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."MIG_PK" IS 'Clave ¿nica de MIG_PER_AGR_MARCAS';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."MIG_FK" IS 'Clave externa para MIG_PERSONAS';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."CMARCA" IS 'C¿digo de marca';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."CTIPO" IS 'Tipo marca (0 Manual ¿ 1 Autom¿tica)';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."CTOMADOR" IS 'Marca Tomador (0 Inactivo / 1 Activo)';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."CCONSORCIO" IS 'Marca Consorcio (0 Inactivo / 1 Activo)';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."CASEGURADO" IS 'Marca Asegurado (0 Inactivo / 1 Activo)';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."CCODEUDOR" IS 'Marca Codeudor (0 Inactivo / 1 Activo)';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."CBENEF" IS 'Marca Beneficiario (0 Inactivo / 1 Activo)';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."CACCIONISTA" IS 'Marca Accionista (0 Inactivo / 1 Activo)';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."CINTERMED" IS 'Marca Intermediario (0 Inactivo / 1 Activo)';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."CREPRESEN" IS 'Marca Representante legal (0 Inactivo / 1 Activo)';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."CAPODERADO" IS 'Marca Apoderado (0 Inactivo / 1 Activo)';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."CPAGADOR" IS 'Marca Pagador (0 Inactivo / 1 Activo)';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."TOBSEVA" IS 'Observaciones';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."NMOVIMI" IS 'Secuencia histórica de movimientos';
   COMMENT ON COLUMN "AXIS"."MIG_PER_AGR_MARCAS"."CPROVEEDOR" IS 'Marca Proveedor (0 Inactivo / 1 Activo)';
  GRANT UPDATE ON "AXIS"."MIG_PER_AGR_MARCAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_PER_AGR_MARCAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_PER_AGR_MARCAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_PER_AGR_MARCAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_PER_AGR_MARCAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_PER_AGR_MARCAS" TO "PROGRAMADORESCSI";
