--------------------------------------------------------
--  DDL for Table MIG_PAGOGARANTIA
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_PAGOGARANTIA" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"CGARANT" NUMBER(4,0), 
	"SIDEPAG" NUMBER(8,0), 
	"ISINRET" NUMBER, 
	"FPERINI" DATE, 
	"FPERFIN" DATE, 
	"IIMPIVA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_PAGOGARANTIA"."NCARGA" IS 'Número de carga';
   COMMENT ON COLUMN "AXIS"."MIG_PAGOGARANTIA"."CESTMIG" IS 'Estado del registro';
   COMMENT ON COLUMN "AXIS"."MIG_PAGOGARANTIA"."MIG_PK" IS 'Clave única de MIG_PAGOGARANTIA';
   COMMENT ON COLUMN "AXIS"."MIG_PAGOGARANTIA"."MIG_FK" IS 'Clave externa para el pago (MIG_PAGOSINI)';
  GRANT UPDATE ON "AXIS"."MIG_PAGOGARANTIA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_PAGOGARANTIA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_PAGOGARANTIA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_PAGOGARANTIA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_PAGOGARANTIA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_PAGOGARANTIA" TO "PROGRAMADORESCSI";
