--------------------------------------------------------
--  DDL for Table MIG_RIESGOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_RIESGOS" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"MIG_FK2" VARCHAR2(50 BYTE), 
	"NRIESGO" NUMBER(6,0), 
	"SSEGURO" NUMBER, 
	"NMOVIMA" NUMBER(4,0), 
	"FEFECTO" DATE, 
	"SPERSON" NUMBER(10,0), 
	"NMOVIMB" NUMBER(4,0), 
	"FANULAC" DATE, 
	"TNATRIE" VARCHAR2(300 BYTE), 
	"PDTOCOM" NUMBER(6,2), 
	"PRECARG" NUMBER(6,2), 
	"PDTOTEC" NUMBER(6,2), 
	"PRECCOM" NUMBER(6,2), 
	"TDESCRIE" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" 
 LOB ("TDESCRIE") STORE AS SECUREFILE (
  TABLESPACE "AXIS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."NCARGA" IS 'N¿mero de carga';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."CESTMIG" IS 'Estado del registro';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."MIG_PK" IS 'Clave ¿nica de MIG_RIESGOS';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."MIG_FK" IS 'Clave externa para el asegurado (MIG_PERSONAS)';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."MIG_FK2" IS 'Clave externa para la p¿liza (MIG_SEGUROS)';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."NRIESGO" IS 'N¿mero de riesgo';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."SSEGURO" IS 'N¿mero de secuencia de seguro, valor=0, lo calcula el proceso de migraci¿n';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."NMOVIMA" IS 'N¿mero de movimiento (Alta)';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."FEFECTO" IS 'Fecha de efecto';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."SPERSON" IS 'N¿mero de secuencia de personas, valor=0, lo calcula el proceso de migraci¿n';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."NMOVIMB" IS 'N¿mero de movimiento (Baja)';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."FANULAC" IS 'Fecha de anulaci¿n';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."TNATRIE" IS 'Naturaleza del Riesgo';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."PDTOCOM" IS 'Porcentaje descuento comercial';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."PRECARG" IS 'Porcentaje recargo t¿cnico';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."PDTOTEC" IS 'Porcentaje descuento t¿cnico';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."PRECCOM" IS 'Porcentaje recargo comercial';
   COMMENT ON COLUMN "AXIS"."MIG_RIESGOS"."TDESCRIE" IS 'Detalle del riesgo';
   COMMENT ON TABLE "AXIS"."MIG_RIESGOS"  IS 'Tabla Intermedia migraci¿n Riesgos';
  GRANT UPDATE ON "AXIS"."MIG_RIESGOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_RIESGOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_RIESGOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_RIESGOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_RIESGOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_RIESGOS" TO "PROGRAMADORESCSI";
