--------------------------------------------------------
--  DDL for Table MIG_BUREAU_BS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_BUREAU_BS" 
   (	"MIG_PK" VARCHAR2(50 BYTE), 
	"SBUREAU" NUMBER, 
	"NMOVIMI" NUMBER, 
	"CANULADA" NUMBER, 
	"CTIPO" NUMBER, 
	"NSUPLEM" NUMBER, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIF" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;
  GRANT DELETE ON "AXIS"."MIG_BUREAU_BS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_BUREAU_BS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_BUREAU_BS" TO "R_AXIS";
  GRANT UPDATE ON "AXIS"."MIG_BUREAU_BS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_BUREAU_BS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_BUREAU_BS" TO "PROGRAMADORESCSI";
