--------------------------------------------------------
--  DDL for Table MIG_BENESPSEG_BS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_BENESPSEG_BS" 
   (	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"MIG_FK2" VARCHAR2(50 BYTE), 
	"NBENEF" NUMBER(3,0), 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0), 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FMOVIMI" DATE, 
	"CESTADO" NUMBER(2,0), 
	"TIPO_DE_BENEFICIARIO" NUMBER(2,0), 
	"PARENTESCO" NUMBER(2,0), 
	"PORCENTAJE" NUMBER(5,2), 
	"SUCREA" VARCHAR2(20 BYTE), 
	"FECHAING" DATE, 
	"MODULO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;
  GRANT DELETE ON "AXIS"."MIG_BENESPSEG_BS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_BENESPSEG_BS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_BENESPSEG_BS" TO "R_AXIS";
  GRANT UPDATE ON "AXIS"."MIG_BENESPSEG_BS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_BENESPSEG_BS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_BENESPSEG_BS" TO "PROGRAMADORESCSI";
