--------------------------------------------------------
--  DDL for Table MIG_SIN_TRAMITA_PAGO_BS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_SIN_TRAMITA_PAGO_BS" 
   (	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"MIG_FK2" VARCHAR2(50 BYTE), 
	"NTRAMIT" NUMBER(3,0), 
	"CTIPDES" NUMBER(2,0), 
	"CTIPPAG" NUMBER(1,0), 
	"CCONPAG" NUMBER(2,0), 
	"CCAUIND" NUMBER(3,0), 
	"CFORPAG" NUMBER(2,0), 
	"FORDPAG" DATE, 
	"CTIPBAN" NUMBER(3,0), 
	"CBANCAR" VARCHAR2(50 BYTE), 
	"CMONRES" VARCHAR2(3 BYTE), 
	"ISINRET" NUMBER, 
	"IRETENC" NUMBER, 
	"IIVA" NUMBER, 
	"ISUPLID" NUMBER, 
	"IFRANQ" NUMBER, 
	"IRESRCM" NUMBER, 
	"IRESRED" NUMBER, 
	"CMONPAG" VARCHAR2(3 BYTE), 
	"ISINRETPAG" NUMBER, 
	"IRETENCPAG" NUMBER, 
	"IIVAPAG" NUMBER, 
	"ISUPLIDPAG" NUMBER, 
	"IFRANQPAG" NUMBER, 
	"IRESRCMPAG" NUMBER, 
	"IRESREDPAG" NUMBER, 
	"FCAMBIO" DATE, 
	"NFACREF" VARCHAR2(100 BYTE), 
	"FFACREF" DATE, 
	"CTRANSFER" NUMBER(1,0), 
	"CULTPAG" NUMBER(1,0), 
	"IRETEIVA" NUMBER, 
	"IRETEICA" NUMBER, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"SUCREA" VARCHAR2(20 BYTE), 
	"FECHAING" DATE, 
	"MODULO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;
  GRANT DELETE ON "AXIS"."MIG_SIN_TRAMITA_PAGO_BS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_SIN_TRAMITA_PAGO_BS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_SIN_TRAMITA_PAGO_BS" TO "R_AXIS";
  GRANT UPDATE ON "AXIS"."MIG_SIN_TRAMITA_PAGO_BS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_SIN_TRAMITA_PAGO_BS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_SIN_TRAMITA_PAGO_BS" TO "PROGRAMADORESCSI";
