--------------------------------------------------------
--  DDL for Table MIG_AGE_CORRETAJE
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_AGE_CORRETAJE" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER(4,0), 
	"NORDAGE" NUMBER(2,0), 
	"CAGENTE" NUMBER, 
	"PCOMISI" NUMBER(5,2), 
	"PPARTICI" NUMBER(5,2), 
	"ISLIDER" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_AGE_CORRETAJE"."NCARGA" IS 'Número de carga';
   COMMENT ON COLUMN "AXIS"."MIG_AGE_CORRETAJE"."CESTMIG" IS 'Estado del registro valor inicial 1';
   COMMENT ON COLUMN "AXIS"."MIG_AGE_CORRETAJE"."MIG_PK" IS 'Clave única de MIG_AGE_CORRETAJE';
   COMMENT ON COLUMN "AXIS"."MIG_AGE_CORRETAJE"."MIG_FK" IS 'Clave externa para la póliza (MIG_SEGUROS)';
   COMMENT ON COLUMN "AXIS"."MIG_AGE_CORRETAJE"."SSEGURO" IS 'Número de secuencia de seguro, valor=0, lo calcula el proceso de migración';
   COMMENT ON COLUMN "AXIS"."MIG_AGE_CORRETAJE"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."MIG_AGE_CORRETAJE"."NORDAGE" IS 'Orden de aparación de agente';
   COMMENT ON COLUMN "AXIS"."MIG_AGE_CORRETAJE"."CAGENTE" IS 'Código de agente intermediario';
   COMMENT ON COLUMN "AXIS"."MIG_AGE_CORRETAJE"."PCOMISI" IS 'Porcentaje de comisión';
   COMMENT ON COLUMN "AXIS"."MIG_AGE_CORRETAJE"."PPARTICI" IS 'Porcentaje de participación';
   COMMENT ON COLUMN "AXIS"."MIG_AGE_CORRETAJE"."ISLIDER" IS 'Indica si es el Líder del corretaje. 0 --> No  1 --> Sí';
   COMMENT ON TABLE "AXIS"."MIG_AGE_CORRETAJE"  IS 'Tabla Intermedia migración de co-corretaje';
  GRANT UPDATE ON "AXIS"."MIG_AGE_CORRETAJE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_AGE_CORRETAJE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_AGE_CORRETAJE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_AGE_CORRETAJE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_AGE_CORRETAJE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_AGE_CORRETAJE" TO "PROGRAMADORESCSI";
