--------------------------------------------------------
--  DDL for Table MIG_SIN_TRAMITA_PAGO_GAR_BS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_SIN_TRAMITA_PAGO_GAR_BS" 
   (	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"CTIPRES" NUMBER(2,0), 
	"NMOVRES" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0), 
	"FPERINI" DATE, 
	"FPERFIN" DATE, 
	"CMONRES" VARCHAR2(3 BYTE), 
	"ISINRET" NUMBER, 
	"IRETENC" NUMBER, 
	"IIVA" NUMBER, 
	"ISUPLID" NUMBER, 
	"IFRANQ" NUMBER, 
	"IRESRCM" NUMBER, 
	"IRESRED" NUMBER, 
	"CMONPAG" VARCHAR2(3 BYTE), 
	"ISINRETPAG" NUMBER, 
	"IIVAPAG" NUMBER, 
	"ISUPLIDPAG" NUMBER, 
	"IRETENCPAG" NUMBER, 
	"IFRANQPAG" NUMBER, 
	"IRESRCMPAG" NUMBER, 
	"IRESREDPAG" NUMBER, 
	"FCAMBIO" DATE, 
	"PRETENC" NUMBER(6,3), 
	"PIVA" NUMBER(6,3), 
	"IRETEIVA" NUMBER, 
	"PRETEIVA" NUMBER(3,0), 
	"CAPLFRA" NUMBER(1,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"SUCREA" VARCHAR2(20 BYTE), 
	"FECHAING" DATE, 
	"MODULO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;
  GRANT DELETE ON "AXIS"."MIG_SIN_TRAMITA_PAGO_GAR_BS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_SIN_TRAMITA_PAGO_GAR_BS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_SIN_TRAMITA_PAGO_GAR_BS" TO "R_AXIS";
  GRANT UPDATE ON "AXIS"."MIG_SIN_TRAMITA_PAGO_GAR_BS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_SIN_TRAMITA_PAGO_GAR_BS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_SIN_TRAMITA_PAGO_GAR_BS" TO "PROGRAMADORESCSI";
