--------------------------------------------------------
--  DDL for Table MIG_COMPANIAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_COMPANIAS" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"CCOMPANI" NUMBER, 
	"TCOMPANI" VARCHAR2(60 BYTE), 
	"CTIPCOM" NUMBER(2,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_COMPANIAS"."MIG_PK" IS 'Clave ¿nica de MIG_COMPANIAS';
   COMMENT ON COLUMN "AXIS"."MIG_COMPANIAS"."MIG_FK" IS 'Clave externa para MIG_PERSONAS';
   COMMENT ON COLUMN "AXIS"."MIG_COMPANIAS"."CCOMPANI" IS 'C¿digo de compa¿¿a  (Si es NULO se obtiene un c¿digo)';
   COMMENT ON COLUMN "AXIS"."MIG_COMPANIAS"."TCOMPANI" IS 'Descripci¿n de la compa¿¿a';
   COMMENT ON COLUMN "AXIS"."MIG_COMPANIAS"."CTIPCOM" IS 'Tipo de compa¿¿a VF:800102';
  GRANT UPDATE ON "AXIS"."MIG_COMPANIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_COMPANIAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_COMPANIAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_COMPANIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_COMPANIAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_COMPANIAS" TO "PROGRAMADORESCSI";
