--------------------------------------------------------
--  DDL for Table MIG_COMPANIAS_BS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_COMPANIAS_BS" 
   (	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"CCOMPANI" NUMBER, 
	"TCOMPANI" VARCHAR2(60 BYTE), 
	"CTIPCOM" NUMBER(2,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;
  GRANT DELETE ON "AXIS"."MIG_COMPANIAS_BS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_COMPANIAS_BS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_COMPANIAS_BS" TO "R_AXIS";
  GRANT UPDATE ON "AXIS"."MIG_COMPANIAS_BS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_COMPANIAS_BS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_COMPANIAS_BS" TO "PROGRAMADORESCSI";
