--------------------------------------------------------
--  DDL for Table MIG_DETPRIMAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_DETPRIMAS" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"CGARANT" NUMBER(4,0), 
	"NMOVIMI" NUMBER(4,0), 
	"FINIEFE" DATE, 
	"CCAMPO" VARCHAR2(8 BYTE), 
	"CCONCEP" VARCHAR2(8 BYTE), 
	"ICONCEP" NUMBER, 
	"ICONCEP2" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_DETPRIMAS"."NCARGA" IS 'Número de carga';
   COMMENT ON COLUMN "AXIS"."MIG_DETPRIMAS"."CESTMIG" IS 'Estado del registro';
   COMMENT ON COLUMN "AXIS"."MIG_DETPRIMAS"."MIG_PK" IS 'Clave única (PK)';
   COMMENT ON COLUMN "AXIS"."MIG_DETPRIMAS"."MIG_FK" IS 'Clave externa (FK)';
   COMMENT ON COLUMN "AXIS"."MIG_DETPRIMAS"."SSEGURO" IS 'Identificador de la póliza';
   COMMENT ON COLUMN "AXIS"."MIG_DETPRIMAS"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."MIG_DETPRIMAS"."CGARANT" IS 'Código de la garantía';
   COMMENT ON COLUMN "AXIS"."MIG_DETPRIMAS"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."MIG_DETPRIMAS"."FINIEFE" IS 'Fecha efecto movimiento';
   COMMENT ON COLUMN "AXIS"."MIG_DETPRIMAS"."CCAMPO" IS 'Codigo del campo (tabla GARANFORMULA)';
   COMMENT ON COLUMN "AXIS"."MIG_DETPRIMAS"."CCONCEP" IS 'Subconcepto (tabla CODCAMPO)';
   COMMENT ON COLUMN "AXIS"."MIG_DETPRIMAS"."ICONCEP" IS 'Importe del concepto';
   COMMENT ON COLUMN "AXIS"."MIG_DETPRIMAS"."ICONCEP2" IS 'Importe de la aplicación del concepto';
   COMMENT ON TABLE "AXIS"."MIG_DETPRIMAS"  IS 'Contiene todos los valores de los subconceptos (subcampos) que forman parte de un campo de GARANFORMULA a nivel de producto (detalle de MIG_GARANSEG).';
  GRANT UPDATE ON "AXIS"."MIG_DETPRIMAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_DETPRIMAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_DETPRIMAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_DETPRIMAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_DETPRIMAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_DETPRIMAS" TO "PROGRAMADORESCSI";
