--------------------------------------------------------
--  DDL for Table MIG_SIN_TRAMITA_JUD_DETPER
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER" 
   (	"NCARGA" NUMBER, 
	"CESTMIG" NUMBER, 
	"MIG_PK" VARCHAR2(50 BYTE), 
	"MIG_FK" VARCHAR2(50 BYTE), 
	"MIG_FK2" VARCHAR2(50 BYTE), 
	"NORDEN" NUMBER(3,0), 
	"NROL" NUMBER(3,0), 
	"NPERSONA" NUMBER(3,0), 
	"NTIPPER" NUMBER(8,0), 
	"NNUMIDE" VARCHAR2(50 BYTE), 
	"TNOMBRE" VARCHAR2(200 BYTE), 
	"IIMPORTE" NUMBER(19,2), 
	"FBAJA" DATE, 
	"FMODIFI" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER"."MIG_PK" IS 'Clave ¿nica de MIG_SIN_TRAMITA_JUD_DETPER';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER"."MIG_FK" IS 'Clave externa de MIG_SIN_SINIESTRO';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER"."MIG_FK2" IS 'Clave externa de MIG_SIN_TRAMITA_JUDICIAL';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER"."NORDEN" IS 'Numero Orden Proceso';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER"."NROL" IS 'Rol de persona (1 - Demandados/ 2 - Beneficiarios) ';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER"."NPERSONA" IS 'N¿mero de persona.';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER"."NTIPPER" IS 'Tipo Persona (VF 8001099 Cuando rol sea Beneficiarios) - (VF 800067 cuando rol de persona demandados)';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER"."NNUMIDE" IS 'N¿mero de Censo/Pasaporte de la persona';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER"."TNOMBRE" IS 'Nombre de la persona';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER"."IIMPORTE" IS 'Importe a pagar';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER"."FBAJA" IS 'Fecha Baja Registro';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER"."FMODIFI" IS 'Fecha Creaci¿n/Modificaci¿n';
   COMMENT ON COLUMN "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER"."CUSUALT" IS 'C¿digo Usuario Alta';
  GRANT UPDATE ON "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_SIN_TRAMITA_JUD_DETPER" TO "PROGRAMADORESCSI";
