--------------------------------------------------------
--  DDL for Table MIG_PERSONAS_BS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIG_PERSONAS_BS" 
   (	"MIG_PK" VARCHAR2(50 BYTE), 
	"SNIP" VARCHAR2(15 BYTE), 
	"CTIPIDE" NUMBER(3,0), 
	"NNUMIDE" VARCHAR2(14 BYTE), 
	"CESTPER" NUMBER(2,0), 
	"CPERTIP" NUMBER(3,0), 
	"FULTMOD" DATE, 
	"SWPUBLI" NUMBER(1,0), 
	"CSEXPER" NUMBER(1,0), 
	"FNACIMI" DATE, 
	"CAGENTE" NUMBER, 
	"TAPELLI1" VARCHAR2(200 BYTE), 
	"TAPELLI2" VARCHAR2(60 BYTE), 
	"TNOMBRE" VARCHAR2(60 BYTE), 
	"TNOMBRE2" VARCHAR2(60 BYTE), 
	"CESTCIV" NUMBER(2,0), 
	"CPAIS" NUMBER(5,0), 
	"CPROFES" VARCHAR2(5 BYTE), 
	"CNACIO" NUMBER(3,0), 
	"CTIPBAN" NUMBER(3,0), 
	"CBANCAR" VARCHAR2(34 BYTE), 
	"CIDIOMA" NUMBER(2,0), 
	"TDIGITOIDE" CHAR(1 BYTE), 
	"FDEFUNC" DATE, 
	"SUCREA" VARCHAR2(20 BYTE), 
	"FECHAING" DATE, 
	"MODULO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;
  GRANT DELETE ON "AXIS"."MIG_PERSONAS_BS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIG_PERSONAS_BS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_PERSONAS_BS" TO "R_AXIS";
  GRANT UPDATE ON "AXIS"."MIG_PERSONAS_BS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIG_PERSONAS_BS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIG_PERSONAS_BS" TO "PROGRAMADORESCSI";
