--------------------------------------------------------
--  DDL for Table MIGPERSONAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MIGPERSONAS" 
   (	"SISTEMA" VARCHAR2(2 BYTE), 
	"CODI_AUXILIAR" VARCHAR2(2 BYTE), 
	"CODI_ORIGEN" VARCHAR2(15 BYTE), 
	"APLICA" NUMBER(4,0), 
	"PRODUCTE" VARCHAR2(4 BYTE), 
	"NIF" VARCHAR2(12 BYTE), 
	"TIPNIF" NUMBER(1,0), 
	"SEXE" NUMBER(1,0), 
	"IDIOMA" NUMBER(2,0), 
	"COGNOM" VARCHAR2(40 BYTE), 
	"NOM" VARCHAR2(40 BYTE), 
	"DNAIXA" DATE, 
	"PRENEDOR" VARCHAR2(1 BYTE), 
	"DANUL" DATE, 
	"SOE" VARCHAR2(15 BYTE), 
	"NOMTOT" VARCHAR2(120 BYTE), 
	"OBSERVA" VARCHAR2(100 BYTE), 
	"CBANCAR" VARCHAR2(50 BYTE), 
	"SPERSON" NUMBER(10,0), 
	"CTIPBAN" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MIGPERSONAS"."CTIPBAN" IS 'Tipo de cuenta ( iban o cuenta bancaria). [tabla maestra: TIPOS_CUENTA]';
  GRANT UPDATE ON "AXIS"."MIGPERSONAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIGPERSONAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MIGPERSONAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MIGPERSONAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MIGPERSONAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MIGPERSONAS" TO "PROGRAMADORESCSI";
