--------------------------------------------------------
--  DDL for Table MODELOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MODELOS" 
   (	"CMODELO" NUMBER(2,0), 
	"TMODELO" VARCHAR2(40 BYTE), 
	"CCARGO" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MODELOS"."CMODELO" IS 'Código de modelo';
   COMMENT ON COLUMN "AXIS"."MODELOS"."TMODELO" IS 'Descripción del modelo';
   COMMENT ON COLUMN "AXIS"."MODELOS"."CCARGO" IS 'Tipo de cargo que debe firmar la carta';
  GRANT UPDATE ON "AXIS"."MODELOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MODELOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MODELOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MODELOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MODELOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MODELOS" TO "PROGRAMADORESCSI";
