--------------------------------------------------------
--  DDL for Table MOV_PRESTAMOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MOV_PRESTAMOS" 
   (	"SMOVPRES" NUMBER, 
	"CTAPRES" VARCHAR2(50 BYTE), 
	"FALTA" DATE, 
	"CESTADO" NUMBER, 
	"CESTANT" NUMBER, 
	"FMOVINI" DATE, 
	"FMOVFIN" DATE, 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FMOVDIA" DATE, 
	"FCONTAB" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MOV_PRESTAMOS"."SMOVPRES" IS 'Secuencia de movimiento del préstamo';
   COMMENT ON COLUMN "AXIS"."MOV_PRESTAMOS"."CTAPRES" IS 'Identificador del préstamo';
   COMMENT ON COLUMN "AXIS"."MOV_PRESTAMOS"."FALTA" IS 'Fecha de alta del préstamo';
   COMMENT ON COLUMN "AXIS"."MOV_PRESTAMOS"."CESTADO" IS 'Estado actual del préstamo';
   COMMENT ON COLUMN "AXIS"."MOV_PRESTAMOS"."CESTANT" IS 'Estado anterior del préstamo';
   COMMENT ON COLUMN "AXIS"."MOV_PRESTAMOS"."FMOVINI" IS 'Fecha inicio de vigencia';
   COMMENT ON COLUMN "AXIS"."MOV_PRESTAMOS"."FMOVFIN" IS 'Fecha fin de vigencia';
   COMMENT ON COLUMN "AXIS"."MOV_PRESTAMOS"."CUSUARI" IS 'Usuario que realiza el movimiento';
   COMMENT ON COLUMN "AXIS"."MOV_PRESTAMOS"."FMOVDIA" IS 'Fecha del movimiento';
   COMMENT ON COLUMN "AXIS"."MOV_PRESTAMOS"."FCONTAB" IS 'Fecha de contabilidad';
   COMMENT ON TABLE "AXIS"."MOV_PRESTAMOS"  IS 'Movimientos de préstamos';
  GRANT UPDATE ON "AXIS"."MOV_PRESTAMOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MOV_PRESTAMOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MOV_PRESTAMOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MOV_PRESTAMOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MOV_PRESTAMOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MOV_PRESTAMOS" TO "PROGRAMADORESCSI";
