--------------------------------------------------------
--  DDL for Table MOV_COBFALL_DGS
--------------------------------------------------------

  CREATE TABLE "AXIS"."MOV_COBFALL_DGS" 
   (	"SPRODUC" NUMBER(6,0), 
	"CMOTMOV" NUMBER(3,0), 
	"CTIPENV" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MOV_COBFALL_DGS"."CTIPENV" IS '1 - Altas, 2 - Alta Asegurado, 3 - Modificaciones, 4 - Bajas, 5 - Baja Asegurado';
   COMMENT ON TABLE "AXIS"."MOV_COBFALL_DGS"  IS 'Movimientos por productos a enviar a la DGS';
  GRANT UPDATE ON "AXIS"."MOV_COBFALL_DGS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MOV_COBFALL_DGS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MOV_COBFALL_DGS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MOV_COBFALL_DGS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MOV_COBFALL_DGS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MOV_COBFALL_DGS" TO "PROGRAMADORESCSI";
