--------------------------------------------------------
--  DDL for Table MOVPAGREN
--------------------------------------------------------

  CREATE TABLE "AXIS"."MOVPAGREN" 
   (	"SRECREN" NUMBER(8,0), 
	"SMOVPAG" NUMBER(6,0), 
	"CESTREC" NUMBER(1,0), 
	"FMOVINI" DATE, 
	"FMOVFIN" DATE, 
	"FEFECTO" DATE, 
	"FCONTAB" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MOVPAGREN"."SRECREN" IS 'Secuencia de SRECREN (Recibos de Rentas)';
   COMMENT ON COLUMN "AXIS"."MOVPAGREN"."SMOVPAG" IS 'Secuencia de SMOVPAG (Movimientos de los Pagos)';
   COMMENT ON COLUMN "AXIS"."MOVPAGREN"."CESTREC" IS '(0,5):0-Pte pago, 1-Pagado, 2-Anulado, 3-Pte de extorno, 4-Extornado, 5-Bloqueada';
   COMMENT ON COLUMN "AXIS"."MOVPAGREN"."FMOVINI" IS 'Fecha inicio del movimiento del recibo';
   COMMENT ON COLUMN "AXIS"."MOVPAGREN"."FMOVFIN" IS 'Fecha fin del movimiento del recibo';
   COMMENT ON COLUMN "AXIS"."MOVPAGREN"."FEFECTO" IS 'Fecha de Efecto del recibo (puede ir cambiando)';
   COMMENT ON COLUMN "AXIS"."MOVPAGREN"."FCONTAB" IS 'Fecha Contabilidad';
   COMMENT ON TABLE "AXIS"."MOVPAGREN"  IS 'Registrará los Movimientos de los Recibos de Pago de las Rentas';
  GRANT UPDATE ON "AXIS"."MOVPAGREN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MOVPAGREN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MOVPAGREN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MOVPAGREN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MOVPAGREN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MOVPAGREN" TO "PROGRAMADORESCSI";
