--------------------------------------------------------
--  DDL for Table MOVPAGOS_CTATEC_REA
--------------------------------------------------------

  CREATE TABLE "AXIS"."MOVPAGOS_CTATEC_REA" 
   (	"SMOVPAGREA" NUMBER(10,0), 
	"SPAGREA" NUMBER(10,0), 
	"CEMPRES" NUMBER(2,0), 
	"CCOMPANI" NUMBER(3,0), 
	"SPRODUC" NUMBER(6,0), 
	"IIMPORTE" NUMBER(15,2), 
	"IIMPORTE_MONCON" NUMBER(15,2), 
	"CESTANT" NUMBER, 
	"CESTADO" NUMBER, 
	"FALTA" DATE, 
	"FLIQUIDA" DATE, 
	"FCONTAB" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."MOVPAGOS_CTATEC_REA"."SMOVPAGREA" IS 'Secuencia del movimiento del pago Reaseguro.';
   COMMENT ON COLUMN "AXIS"."MOVPAGOS_CTATEC_REA"."SPAGREA" IS 'Secuencia del pago Reaseguro.';
   COMMENT ON COLUMN "AXIS"."MOVPAGOS_CTATEC_REA"."CEMPRES" IS 'Empresa';
   COMMENT ON COLUMN "AXIS"."MOVPAGOS_CTATEC_REA"."CCOMPANI" IS 'Código compañía reaseguradora';
   COMMENT ON COLUMN "AXIS"."MOVPAGOS_CTATEC_REA"."SPRODUC" IS 'Identificador de proceso';
   COMMENT ON COLUMN "AXIS"."MOVPAGOS_CTATEC_REA"."IIMPORTE" IS 'Importe del pago';
   COMMENT ON COLUMN "AXIS"."MOVPAGOS_CTATEC_REA"."IIMPORTE_MONCON" IS 'Importe del pago moneda contabilidad';
   COMMENT ON COLUMN "AXIS"."MOVPAGOS_CTATEC_REA"."CESTANT" IS 'Estado anterior del pago. 0:Pendiente, 1:Pagado. VF. 249';
   COMMENT ON COLUMN "AXIS"."MOVPAGOS_CTATEC_REA"."CESTADO" IS 'Estado del pago. 0:Pendiente, 1:Pagado. VF. 249';
   COMMENT ON COLUMN "AXIS"."MOVPAGOS_CTATEC_REA"."FALTA" IS 'Fecha de alta del registro en la tabla';
   COMMENT ON COLUMN "AXIS"."MOVPAGOS_CTATEC_REA"."FLIQUIDA" IS 'Fecha en la que se liquido el pago  ';
   COMMENT ON COLUMN "AXIS"."MOVPAGOS_CTATEC_REA"."FCONTAB" IS 'Fecha contable';
   COMMENT ON TABLE "AXIS"."MOVPAGOS_CTATEC_REA"  IS 'Tabla historica de registros de movimientos de pago';
  GRANT UPDATE ON "AXIS"."MOVPAGOS_CTATEC_REA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MOVPAGOS_CTATEC_REA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MOVPAGOS_CTATEC_REA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MOVPAGOS_CTATEC_REA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MOVPAGOS_CTATEC_REA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MOVPAGOS_CTATEC_REA" TO "PROGRAMADORESCSI";
