--------------------------------------------------------
--  DDL for Table MOVRECIBO_TMP
--------------------------------------------------------

  CREATE TABLE "AXIS"."MOVRECIBO_TMP" 
   (	"SMOVREC" NUMBER, 
	"NRECIBO" NUMBER, 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"SMOVAGR" NUMBER(8,0), 
	"CESTREC" NUMBER(1,0), 
	"CESTANT" NUMBER(1,0), 
	"FMOVINI" DATE, 
	"FMOVFIN" DATE, 
	"FCONTAB" DATE, 
	"FMOVDIA" DATE, 
	"CMOTMOV" NUMBER(3,0), 
	"CCOBBAN" NUMBER(3,0), 
	"CDELEGA" NUMBER, 
	"CTIPCOB" NUMBER(3,0), 
	"FEFEADM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."MOVRECIBO_TMP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MOVRECIBO_TMP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."MOVRECIBO_TMP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."MOVRECIBO_TMP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."MOVRECIBO_TMP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."MOVRECIBO_TMP" TO "PROGRAMADORESCSI";
