--------------------------------------------------------
--  DDL for Table NOTIFICACIONES
--------------------------------------------------------

  CREATE TABLE "AXIS"."NOTIFICACIONES" 
   (	"NRECIBO" NUMBER, 
	"SPROCES" NUMBER, 
	"CCOBBAN" NUMBER(3,0), 
	"CEMPRES" NUMBER(2,0), 
	"FEFECTO" DATE, 
	"TSUFIJO" VARCHAR2(4 BYTE), 
	"CDOMENT" NUMBER(4,0), 
	"CDOMSUC" NUMBER(4,0), 
	"SMOVREC" NUMBER, 
	"CERROR" NUMBER(8,0), 
	"CAGENTE" NUMBER, 
	"CAGRPRO" NUMBER(2,0), 
	"CCOMPANI" NUMBER(3,0), 
	"CTIPEMP" NUMBER(2,0), 
	"SSEGURO" NUMBER, 
	"CTIPREC" NUMBER(2,0), 
	"CBANCAR" VARCHAR2(50 BYTE), 
	"NMOVIMI" NUMBER(4,0), 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"PGASINT" NUMBER(9,6), 
	"PGASEXT" NUMBER(9,6), 
	"CFECCOB" NUMBER(1,0), 
	"FEFECREC" DATE, 
	"CTIPBAN" NUMBER(3,0), 
	"IDNOTIF" NUMBER(10,0), 
	"CNOTEST" NUMBER(1,0), 
	"CNOTERR" VARCHAR2(4 BYTE), 
	"TFILEENV" VARCHAR2(50 BYTE), 
	"TFILEDEV" VARCHAR2(50 BYTE), 
	"FFILEDEV" DATE, 
	"FDEBITO" DATE, 
	"IDNOTIF2" VARCHAR2(100 BYTE), 
	"CTIPCC" NUMBER(2,0), 
	"CTIPIDE" NUMBER(3,0), 
	"NNUMIDE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."NRECIBO" IS 'Número de recibo.';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."SPROCES" IS 'Proceso';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CCOBBAN" IS 'Código de cobrador bancario';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CEMPRES" IS 'Empresa';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."FEFECTO" IS 'Fecha remesa (lote)';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."TSUFIJO" IS 'Sufijo ordenante en el soporte';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."SMOVREC" IS 'Realmente contiene el valor de SPERSON';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CERROR" IS 'Código de error';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CAGRPRO" IS 'Agrupación de producto';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CCOMPANI" IS 'Compañía aseguradora';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CTIPEMP" IS 'Tipo de empresa';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."SSEGURO" IS 'Número de seguro';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CTIPREC" IS 'Tipo de recibo';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CBANCAR" IS 'Cuenta bancària';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."NMOVIMI" IS 'Num.movimiento de seguro';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CRAMO" IS 'Código de ramo';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CMODALI" IS 'Código de modalida';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CTIPSEG" IS 'Código de tiposeguro';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CCOLECT" IS 'Código de colectividad';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CTIPBAN" IS 'Tipo de cuenta ( iban o cuenta bancaria). [tabla maestra: TIPOS_CUENTA]';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."IDNOTIF" IS 'Id de la notificación';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CNOTEST" IS 'Estado devuelto de la notificación, (0-> OK, 1->Error). Para saber respuesta bancaria añadir "AND TFILEDEV IS NOT NULL" --> El "cnotest" también regitra errores si mientras el proceso de notificaciones se produjo algún error.';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CNOTERR" IS 'Error devuelto de la notificación (si CNOTEST=0-->KO)';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."TFILEENV" IS 'Nombre del fichero envíado al banco';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."TFILEDEV" IS 'Nombre del fichero recibido del banco';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."FFILEDEV" IS 'Fecha de carga del fichero recibido del banco';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."FDEBITO" IS 'Nombre de debito informada por el banco';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."IDNOTIF2" IS 'Id. por el que identificamos la notificación. Código de matrícula que se envía al banco (varchar -> para que conserve el formato exacto). Esta referencia se captura en RECFION en el campo "Referencia Código de Usuario';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CTIPCC" IS 'Tipo de cuenta';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."CTIPIDE" IS 'Tipo de identificador';
   COMMENT ON COLUMN "AXIS"."NOTIFICACIONES"."NNUMIDE" IS 'Número de identificación';
   COMMENT ON TABLE "AXIS"."NOTIFICACIONES"  IS 'Prenotificaciones requeridas por algunos bancos de COLOMBIA antes de las domiciliaciones...copia de DOMICILIACIONES';
  GRANT UPDATE ON "AXIS"."NOTIFICACIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."NOTIFICACIONES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."NOTIFICACIONES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."NOTIFICACIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."NOTIFICACIONES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."NOTIFICACIONES" TO "PROGRAMADORESCSI";
