--------------------------------------------------------
--  DDL for Table NOTIBAJAGAR
--------------------------------------------------------

  CREATE TABLE "AXIS"."NOTIBAJAGAR" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"CGARANT" NUMBER(4,0), 
	"NMOVIMI" NUMBER(4,0), 
	"FINIEFE" DATE, 
	"NMOVIMA" NUMBER(4,0), 
	"NMOVIMB" NUMBER(4,0), 
	"CNOTIBAJA" NUMBER(3,0), 
	"CMOTMOV" NUMBER(3,0), 
	"FANULAC" DATE, 
	"CREHAB" NUMBER(1,0), 
	"NMOVREHAB" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."NOTIBAJAGAR"."SSEGURO" IS 'Número de seguro';
   COMMENT ON COLUMN "AXIS"."NOTIBAJAGAR"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."NOTIBAJAGAR"."CGARANT" IS 'Código de garantía';
   COMMENT ON COLUMN "AXIS"."NOTIBAJAGAR"."NMOVIMI" IS 'Número de último movimiento de alta';
   COMMENT ON COLUMN "AXIS"."NOTIBAJAGAR"."FINIEFE" IS 'Fecha efecto último movimiento de alta';
   COMMENT ON COLUMN "AXIS"."NOTIBAJAGAR"."NMOVIMA" IS 'Número de movimiento de alta (el 1º)';
   COMMENT ON COLUMN "AXIS"."NOTIBAJAGAR"."NMOVIMB" IS 'Número de movimiento de baja';
   COMMENT ON COLUMN "AXIS"."NOTIBAJAGAR"."CNOTIBAJA" IS 'Código de notificación de baja.Valor 844';
   COMMENT ON COLUMN "AXIS"."NOTIBAJAGAR"."CMOTMOV" IS 'Motivo de movimiento de la anulación';
   COMMENT ON COLUMN "AXIS"."NOTIBAJAGAR"."FANULAC" IS 'Fecha en la que se anula la garantía';
   COMMENT ON COLUMN "AXIS"."NOTIBAJAGAR"."CREHAB" IS 'Garantia rehabilitada (0-No, 1-Si)';
   COMMENT ON COLUMN "AXIS"."NOTIBAJAGAR"."NMOVREHAB" IS 'moviment de rehabilitació';
   COMMENT ON TABLE "AXIS"."NOTIBAJAGAR"  IS 'Notificación de baja de una garantía';
  GRANT UPDATE ON "AXIS"."NOTIBAJAGAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."NOTIBAJAGAR" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."NOTIBAJAGAR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."NOTIBAJAGAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."NOTIBAJAGAR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."NOTIBAJAGAR" TO "PROGRAMADORESCSI";
