--------------------------------------------------------
--  DDL for Table NOVISITA
--------------------------------------------------------

  CREATE TABLE "AXIS"."NOVISITA" 
   (	"FNOVISI" DATE, 
	"SPERSON" NUMBER(10,0), 
	"TOBSERV" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."NOVISITA"."FNOVISI" IS 'Fecha de ausencia';
   COMMENT ON COLUMN "AXIS"."NOVISITA"."SPERSON" IS 'Identificador único de la Personas';
   COMMENT ON COLUMN "AXIS"."NOVISITA"."TOBSERV" IS 'Observaciones';
  GRANT UPDATE ON "AXIS"."NOVISITA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."NOVISITA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."NOVISITA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."NOVISITA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."NOVISITA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."NOVISITA" TO "PROGRAMADORESCSI";
