--------------------------------------------------------
--  DDL for Table NUMEROS
--------------------------------------------------------

  CREATE TABLE "AXIS"."NUMEROS" 
   (	"CIDIOMA" NUMBER(2,0), 
	"CNUMERO" NUMBER(10,0), 
	"TDESCRI" VARCHAR2(15 BYTE), 
	"TDESCPL" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."NUMEROS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."NUMEROS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."NUMEROS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."NUMEROS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."NUMEROS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."NUMEROS" TO "PROGRAMADORESCSI";
