--------------------------------------------------------
--  DDL for Table PAGOS_CTATEC_REA
--------------------------------------------------------

  CREATE TABLE "AXIS"."PAGOS_CTATEC_REA" 
   (	"SPAGREA" NUMBER(10,0), 
	"CEMPRES" NUMBER(2,0), 
	"CCOMPANI" NUMBER(3,0), 
	"CCORRED" NUMBER(4,0), 
	"SPRODUC" NUMBER(6,0), 
	"IIMPORTE" NUMBER, 
	"CESTADO" NUMBER(1,0), 
	"FLIQUIDA" DATE, 
	"CUSUARIO" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CFORPAG" NUMBER(1,0), 
	"CTIPOPAG" NUMBER(1,0), 
	"NREMESA" NUMBER(10,0), 
	"FTRANS" DATE, 
	"CTIPBAN" NUMBER(3,0), 
	"CBANCAR" VARCHAR2(50 BYTE), 
	"SPROCES" NUMBER, 
	"IIMPORTE_MONCON" NUMBER, 
	"FCAMBIO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."SPAGREA" IS 'Secuencia del pago Reaseguro.';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."CEMPRES" IS 'Empresa';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."CCOMPANI" IS 'Código compañía reaseguradora';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."CCORRED" IS 'Código de Corredor/Broker';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."SPRODUC" IS 'Identificador de proceso';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."IIMPORTE" IS 'Importe del pago';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."CESTADO" IS 'Estado del pago. 0:Pendiente, 1:Pagado. VF. 249';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."FLIQUIDA" IS 'Fecha en la que se liquido el pago  ';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."CUSUARIO" IS 'usuario que realiza de alta del pago';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."CFORPAG" IS 'Forma de pago de la comisión. 1.Metálico, 2:Transferencia';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."CTIPOPAG" IS 'Tipo de pago. 1: Debe(+) /2: Haber (-)';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."NREMESA" IS 'Si la forma de pago es por transferencia el número de remesa al que pertenece';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."FTRANS" IS 'Si la forma de pago es por transferencia la fecha de la transferencia  ';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."CTIPBAN" IS 'Tipo de cuenta ( IBAN o Cuenta Bancaria). [TABLA MAESTRA: TIPOS_CUENTA]';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."CBANCAR" IS 'CCC según Consejo Superior Bancario';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."IIMPORTE_MONCON" IS 'Importe del pago moneda contabilidad';
   COMMENT ON COLUMN "AXIS"."PAGOS_CTATEC_REA"."FCAMBIO" IS 'Fecha empleada para el calculo de los contravalores';
   COMMENT ON TABLE "AXIS"."PAGOS_CTATEC_REA"  IS 'Liquidación Pagos Cuenta técnica Reaseguro';
  GRANT UPDATE ON "AXIS"."PAGOS_CTATEC_REA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PAGOS_CTATEC_REA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PAGOS_CTATEC_REA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PAGOS_CTATEC_REA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PAGOS_CTATEC_REA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PAGOS_CTATEC_REA" TO "PROGRAMADORESCSI";
