--------------------------------------------------------
--  DDL for Table PAR_REGLAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."PAR_REGLAS" 
   (	"REGLA" NUMBER(6,0), 
	"DENOMINACION" VARCHAR2(40 BYTE), 
	"PERFIL_AUTORIZACION" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."PAR_REGLAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PAR_REGLAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PAR_REGLAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PAR_REGLAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PAR_REGLAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PAR_REGLAS" TO "PROGRAMADORESCSI";
