--------------------------------------------------------
--  DDL for Table PAR_ASOCIACIONES_COND
--------------------------------------------------------

  CREATE TABLE "AXIS"."PAR_ASOCIACIONES_COND" 
   (	"ASOCIACION" NUMBER(6,0), 
	"REGLA" NUMBER(6,0), 
	"DESCRIPCION" VARCHAR2(80 BYTE), 
	"PERFIL_EXIGIBLE" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PAR_ASOCIACIONES_COND"."ASOCIACION" IS 'Código de asociación';
   COMMENT ON COLUMN "AXIS"."PAR_ASOCIACIONES_COND"."REGLA" IS 'Código de regla';
   COMMENT ON COLUMN "AXIS"."PAR_ASOCIACIONES_COND"."DESCRIPCION" IS 'Descripción de la asociación de reglas';
   COMMENT ON TABLE "AXIS"."PAR_ASOCIACIONES_COND"  IS 'Definición de las posibles asociaciones de reglas';
  GRANT UPDATE ON "AXIS"."PAR_ASOCIACIONES_COND" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PAR_ASOCIACIONES_COND" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PAR_ASOCIACIONES_COND" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PAR_ASOCIACIONES_COND" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PAR_ASOCIACIONES_COND" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PAR_ASOCIACIONES_COND" TO "PROGRAMADORESCSI";
