--------------------------------------------------------
--  DDL for Table PARENTESCOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."PARENTESCOS" 
   (	"SPERSON1" NUMBER(10,0), 
	"CPAREN1" NUMBER(2,0), 
	"SPERSON2" NUMBER(10,0), 
	"CPAREN2" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PARENTESCOS"."SPERSON1" IS 'Código persona del parentesco 1.';
   COMMENT ON COLUMN "AXIS"."PARENTESCOS"."CPAREN1" IS 'Código del parentesco 1.';
   COMMENT ON COLUMN "AXIS"."PARENTESCOS"."SPERSON2" IS 'Código persona del parentesco 2.';
   COMMENT ON COLUMN "AXIS"."PARENTESCOS"."CPAREN2" IS 'Código parentesco del Parentesco 2.';
   COMMENT ON TABLE "AXIS"."PARENTESCOS"  IS 'Relaciones de parentescos entre personas';
  GRANT UPDATE ON "AXIS"."PARENTESCOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PARENTESCOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PARENTESCOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PARENTESCOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PARENTESCOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PARENTESCOS" TO "PROGRAMADORESCSI";
