--------------------------------------------------------
--  DDL for Table PAREMPRESAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."PAREMPRESAS" 
   (	"CEMPRES" NUMBER(2,0), 
	"CPARAM" VARCHAR2(20 BYTE), 
	"NVALPAR" NUMBER(8,0), 
	"TVALPAR" VARCHAR2(100 BYTE), 
	"FVALPAR" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PAREMPRESAS"."CEMPRES" IS 'Código de empresa';
   COMMENT ON COLUMN "AXIS"."PAREMPRESAS"."CPARAM" IS 'Código de parámetro';
   COMMENT ON COLUMN "AXIS"."PAREMPRESAS"."NVALPAR" IS 'Valor numérico del parámetro o de la lista de valores de DETPARAM';
   COMMENT ON COLUMN "AXIS"."PAREMPRESAS"."TVALPAR" IS 'Valor Texto del parámetro';
   COMMENT ON COLUMN "AXIS"."PAREMPRESAS"."FVALPAR" IS 'Valor fecha del parámetro';
  GRANT UPDATE ON "AXIS"."PAREMPRESAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PAREMPRESAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PAREMPRESAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PAREMPRESAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PAREMPRESAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PAREMPRESAS" TO "PROGRAMADORESCSI";
