--------------------------------------------------------
--  DDL for Table PARGARANPRO
--------------------------------------------------------

  CREATE TABLE "AXIS"."PARGARANPRO" 
   (	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CACTIVI" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0), 
	"CPARGAR" VARCHAR2(20 BYTE), 
	"CVALPAR" NUMBER(8,0), 
	"SPRODUC" NUMBER(6,0), 
	"TVALPAR" VARCHAR2(50 BYTE), 
	"FVALPAR" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PARGARANPRO"."SPRODUC" IS 'Identificador del producto';
   COMMENT ON COLUMN "AXIS"."PARGARANPRO"."TVALPAR" IS 'Valor Texto del parámetro';
   COMMENT ON COLUMN "AXIS"."PARGARANPRO"."FVALPAR" IS 'Valor Fecha del parámetro';
  GRANT UPDATE ON "AXIS"."PARGARANPRO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PARGARANPRO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PARGARANPRO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PARGARANPRO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PARGARANPRO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PARGARANPRO" TO "PROGRAMADORESCSI";
