--------------------------------------------------------
--  DDL for Table PARMS_SUPLEMENTOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."PARMS_SUPLEMENTOS" 
   (	"SESION" NUMBER(6,0), 
	"PARAMETRO" VARCHAR2(30 BYTE), 
	"VALOR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PARMS_SUPLEMENTOS"."SESION" IS 'Código único de sessión';
   COMMENT ON COLUMN "AXIS"."PARMS_SUPLEMENTOS"."PARAMETRO" IS 'Código de parámetro';
   COMMENT ON TABLE "AXIS"."PARMS_SUPLEMENTOS"  IS 'Valores temporales de los parametros para fómrulas';
  GRANT UPDATE ON "AXIS"."PARMS_SUPLEMENTOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PARMS_SUPLEMENTOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PARMS_SUPLEMENTOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PARMS_SUPLEMENTOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PARMS_SUPLEMENTOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PARMS_SUPLEMENTOS" TO "PROGRAMADORESCSI";
