--------------------------------------------------------
--  DDL for Table PARMENU
--------------------------------------------------------

  CREATE TABLE "AXIS"."PARMENU" 
   (	"NLITERAL" NUMBER(8,0), 
	"TLABEL" VARCHAR2(100 BYTE), 
	"CMENU" NUMBER(6,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PARMENU"."NLITERAL" IS 'Numero de literal del texto del menu';
   COMMENT ON COLUMN "AXIS"."PARMENU"."TLABEL" IS 'Nombre del item del menu';
   COMMENT ON COLUMN "AXIS"."PARMENU"."CMENU" IS 'Id del menu';
   COMMENT ON COLUMN "AXIS"."PARMENU"."CUSUALT" IS 'Usuario que da de alta la opción del menú';
   COMMENT ON COLUMN "AXIS"."PARMENU"."FALTA" IS 'Fecha de alta del Registro';
   COMMENT ON COLUMN "AXIS"."PARMENU"."CUSUMOD" IS 'Usuario que modifica el registro';
   COMMENT ON COLUMN "AXIS"."PARMENU"."FMODIFI" IS 'Fecha de moficiación del registro';
   COMMENT ON TABLE "AXIS"."PARMENU"  IS 'Tabla de literales del menu';
  GRANT UPDATE ON "AXIS"."PARMENU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PARMENU" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PARMENU" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PARMENU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PARMENU" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PARMENU" TO "PROGRAMADORESCSI";
