--------------------------------------------------------
--  DDL for Table PARPGGBVAREXT_POLIZA
--------------------------------------------------------

  CREATE TABLE "AXIS"."PARPGGBVAREXT_POLIZA" 
   (	"SSEGURO" NUMBER, 
	"FINICIO" DATE, 
	"FFIN" DATE, 
	"IINTPRI" NUMBER(9,6), 
	"IEXTPRI" NUMBER(9,6), 
	"IINTPRIS" NUMBER(9,6), 
	"IEXTPRIS" NUMBER(9,6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."PARPGGBVAREXT_POLIZA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PARPGGBVAREXT_POLIZA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PARPGGBVAREXT_POLIZA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PARPGGBVAREXT_POLIZA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PARPGGBVAREXT_POLIZA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PARPGGBVAREXT_POLIZA" TO "PROGRAMADORESCSI";
