--------------------------------------------------------
--  DDL for Table PARTRASPRESC
--------------------------------------------------------

  CREATE TABLE "AXIS"."PARTRASPRESC" 
   (	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CTIPMOV" NUMBER(1,0), 
	"CCODFON" NUMBER(3,0), 
	"FINICIO" DATE, 
	"FFIN" DATE, 
	"NCARCIA" NUMBER(2,0), 
	"NMAXANO" NUMBER(3,0), 
	"NGRAANO" NUMBER(2,0), 
	"IIMPPEN" NUMBER(8,2), 
	"CDIVISA" NUMBER(2,0), 
	"PPENAL" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PARTRASPRESC"."CRAMO" IS 'Código de ramo';
   COMMENT ON COLUMN "AXIS"."PARTRASPRESC"."CMODALI" IS 'Código de modalidad';
   COMMENT ON COLUMN "AXIS"."PARTRASPRESC"."CTIPSEG" IS 'Código de tipo de seguro';
   COMMENT ON COLUMN "AXIS"."PARTRASPRESC"."CCOLECT" IS 'Código de colectividad';
   COMMENT ON COLUMN "AXIS"."PARTRASPRESC"."CTIPMOV" IS 'Tipo de movimiento (1=traspasos, 2=rescates parciales,3=totales)';
   COMMENT ON COLUMN "AXIS"."PARTRASPRESC"."CCODFON" IS 'Código de fondo';
   COMMENT ON COLUMN "AXIS"."PARTRASPRESC"."FINICIO" IS 'Fecha de inicio';
   COMMENT ON COLUMN "AXIS"."PARTRASPRESC"."FFIN" IS 'Fecha de finalización';
   COMMENT ON COLUMN "AXIS"."PARTRASPRESC"."NCARCIA" IS 'Número de meses durante los que no se podrán hacer traspasos';
   COMMENT ON COLUMN "AXIS"."PARTRASPRESC"."NMAXANO" IS 'Número máximo de operaciones anuales';
   COMMENT ON COLUMN "AXIS"."PARTRASPRESC"."NGRAANO" IS 'Número de operaciones gratuitas anuales';
   COMMENT ON COLUMN "AXIS"."PARTRASPRESC"."IIMPPEN" IS 'Importe de penalización de las no gratuitas';
   COMMENT ON COLUMN "AXIS"."PARTRASPRESC"."CDIVISA" IS 'Código de la divisa';
   COMMENT ON COLUMN "AXIS"."PARTRASPRESC"."PPENAL" IS '% de penalización de las no gratuitas';
   COMMENT ON TABLE "AXIS"."PARTRASPRESC"  IS 'Almacena parámetros referentes a traspasos / rescates parciales / rescates totales';
  GRANT UPDATE ON "AXIS"."PARTRASPRESC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PARTRASPRESC" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PARTRASPRESC" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PARTRASPRESC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PARTRASPRESC" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PARTRASPRESC" TO "PROGRAMADORESCSI";
