--------------------------------------------------------
--  DDL for Table PAY_TEMPO
--------------------------------------------------------

  CREATE TABLE "AXIS"."PAY_TEMPO" 
   (	"SEQTEMPO" NUMBER, 
	"NPOLIZA" VARCHAR2(50 BYTE), 
	"SSEGURO" NUMBER, 
	"TNOMBRE" VARCHAR2(50 BYTE), 
	"SPERSON" NUMBER, 
	"ITOTPRI" VARCHAR2(50 BYTE), 
	"CDEBHAB" VARCHAR2(20 BYTE), 
	"SEQID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PAY_TEMPO"."SEQTEMPO" IS 'Identificador de pago';
   COMMENT ON COLUMN "AXIS"."PAY_TEMPO"."NPOLIZA" IS 'Numero de la poliza';
   COMMENT ON COLUMN "AXIS"."PAY_TEMPO"."SSEGURO" IS 'Numero del seguro asignado';
   COMMENT ON COLUMN "AXIS"."PAY_TEMPO"."TNOMBRE" IS 'Nombre del pagador';
   COMMENT ON COLUMN "AXIS"."PAY_TEMPO"."SPERSON" IS 'Codigo del pagador';
   COMMENT ON COLUMN "AXIS"."PAY_TEMPO"."ITOTPRI" IS 'Monto a pagar';
   COMMENT ON COLUMN "AXIS"."PAY_TEMPO"."CDEBHAB" IS 'Destino debito o credito';
   COMMENT ON COLUMN "AXIS"."PAY_TEMPO"."SEQID" IS 'Identificador de la transacciòn(seqmovecash)';
  GRANT UPDATE ON "AXIS"."PAY_TEMPO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PAY_TEMPO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PAY_TEMPO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PAY_TEMPO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PAY_TEMPO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PAY_TEMPO" TO "PROGRAMADORESCSI";
