--------------------------------------------------------
--  DDL for Table PBEX_PREVIO
--------------------------------------------------------

  CREATE TABLE "AXIS"."PBEX_PREVIO" 
   (	"CEMPRES" NUMBER(2,0), 
	"FCALCUL" DATE, 
	"SPROCES" NUMBER, 
	"CRAMDGS" NUMBER(4,0), 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"SSEGURO" NUMBER, 
	"CGARANT" NUMBER(4,0), 
	"IVALACT" NUMBER, 
	"ICAPGAR" NUMBER, 
	"IPROMAT" NUMBER, 
	"CERROR" NUMBER(2,0), 
	"NRIESGO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PBEX_PREVIO"."CEMPRES" IS 'Empresa';
   COMMENT ON COLUMN "AXIS"."PBEX_PREVIO"."FCALCUL" IS 'Fecha cálculo';
   COMMENT ON COLUMN "AXIS"."PBEX_PREVIO"."SPROCES" IS 'Número de proceso';
   COMMENT ON COLUMN "AXIS"."PBEX_PREVIO"."CRAMDGS" IS 'Ramos DGS';
   COMMENT ON COLUMN "AXIS"."PBEX_PREVIO"."CRAMO" IS 'Ramo';
   COMMENT ON COLUMN "AXIS"."PBEX_PREVIO"."CMODALI" IS 'Modali';
   COMMENT ON COLUMN "AXIS"."PBEX_PREVIO"."CTIPSEG" IS 'Tipo de Seguro';
   COMMENT ON COLUMN "AXIS"."PBEX_PREVIO"."CCOLECT" IS 'Seguro';
   COMMENT ON COLUMN "AXIS"."PBEX_PREVIO"."CGARANT" IS 'Garantía';
   COMMENT ON COLUMN "AXIS"."PBEX_PREVIO"."IVALACT" IS 'Valor PB';
   COMMENT ON COLUMN "AXIS"."PBEX_PREVIO"."ICAPGAR" IS 'No se usa de momento';
   COMMENT ON COLUMN "AXIS"."PBEX_PREVIO"."IPROMAT" IS 'No se usa de momento';
   COMMENT ON COLUMN "AXIS"."PBEX_PREVIO"."CERROR" IS 'Código de posible error';
   COMMENT ON COLUMN "AXIS"."PBEX_PREVIO"."NRIESGO" IS 'Riesgo';
   COMMENT ON TABLE "AXIS"."PBEX_PREVIO"  IS 'Tabla de PBs';
  GRANT UPDATE ON "AXIS"."PBEX_PREVIO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PBEX_PREVIO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PBEX_PREVIO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PBEX_PREVIO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PBEX_PREVIO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PBEX_PREVIO" TO "PROGRAMADORESCSI";
