--------------------------------------------------------
--  DDL for Table PDS_SUPL_ORDEN_FORM
--------------------------------------------------------

  CREATE TABLE "AXIS"."PDS_SUPL_ORDEN_FORM" 
   (	"CCONFIG" VARCHAR2(50 BYTE), 
	"NORDEN" NUMBER, 
	"TFORM" VARCHAR2(50 BYTE), 
	"TFORM_SIG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PDS_SUPL_ORDEN_FORM"."CCONFIG" IS 'Id. de la configuració (form+mode+motiu+prod)';
   COMMENT ON COLUMN "AXIS"."PDS_SUPL_ORDEN_FORM"."NORDEN" IS 'Orden de ejecucuión';
   COMMENT ON COLUMN "AXIS"."PDS_SUPL_ORDEN_FORM"."TFORM" IS 'Form que hace la llamada';
   COMMENT ON COLUMN "AXIS"."PDS_SUPL_ORDEN_FORM"."TFORM_SIG" IS 'Form que hay que ejecutar';
   COMMENT ON TABLE "AXIS"."PDS_SUPL_ORDEN_FORM"  IS 'configuarción del orden de ejecución de formularios una vez realizado un suplemento';
  GRANT UPDATE ON "AXIS"."PDS_SUPL_ORDEN_FORM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_SUPL_ORDEN_FORM" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PDS_SUPL_ORDEN_FORM" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PDS_SUPL_ORDEN_FORM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_SUPL_ORDEN_FORM" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PDS_SUPL_ORDEN_FORM" TO "PROGRAMADORESCSI";
