--------------------------------------------------------
--  DDL for Table PDS_SUPL_FORM
--------------------------------------------------------

  CREATE TABLE "AXIS"."PDS_SUPL_FORM" 
   (	"CCONFIG" VARCHAR2(50 BYTE), 
	"TFORM" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PDS_SUPL_FORM"."CCONFIG" IS 'Id. de la configuració del suplement';
   COMMENT ON COLUMN "AXIS"."PDS_SUPL_FORM"."TFORM" IS 'Formulario al que se visita para hacer el suplemento';
   COMMENT ON TABLE "AXIS"."PDS_SUPL_FORM"  IS 'Tabla de formularios relacionados con un suplemento ';
  GRANT UPDATE ON "AXIS"."PDS_SUPL_FORM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_SUPL_FORM" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PDS_SUPL_FORM" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PDS_SUPL_FORM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_SUPL_FORM" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PDS_SUPL_FORM" TO "PROGRAMADORESCSI";
