--------------------------------------------------------
--  DDL for Table PDS_COD_SUPLEM
--------------------------------------------------------

  CREATE TABLE "AXIS"."PDS_COD_SUPLEM" 
   (	"CCONSUPL" VARCHAR2(50 BYTE), 
	"TCONSUPL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PDS_COD_SUPLEM"."CCONSUPL" IS 'Id. de la config de suplementos';
   COMMENT ON COLUMN "AXIS"."PDS_COD_SUPLEM"."TCONSUPL" IS 'Descripcion de la config de suplementos';
   COMMENT ON TABLE "AXIS"."PDS_COD_SUPLEM"  IS 'Configuración de las acciones a realizar';
  GRANT UPDATE ON "AXIS"."PDS_COD_SUPLEM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_COD_SUPLEM" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PDS_COD_SUPLEM" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PDS_COD_SUPLEM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_COD_SUPLEM" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PDS_COD_SUPLEM" TO "PROGRAMADORESCSI";
