--------------------------------------------------------
--  DDL for Table PDS_SUPL_CAMPOS_FORM_VALOR_DET
--------------------------------------------------------

  CREATE TABLE "AXIS"."PDS_SUPL_CAMPOS_FORM_VALOR_DET" 
   (	"TCAMPO" VARCHAR2(50 BYTE), 
	"TPROPERTY" VARCHAR2(50 BYTE), 
	"CCONFIG" VARCHAR2(50 BYTE), 
	"TFORM" VARCHAR2(50 BYTE), 
	"TVALOR" VARCHAR2(50 BYTE), 
	"IDSELECT" NUMBER, 
	"TVALUE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PDS_SUPL_CAMPOS_FORM_VALOR_DET"."CCONFIG" IS 'Id. de la configuració (form+mode+motiu+prod)';
   COMMENT ON COLUMN "AXIS"."PDS_SUPL_CAMPOS_FORM_VALOR_DET"."TVALOR" IS 'Valor que tiene que tener el campo';
  GRANT UPDATE ON "AXIS"."PDS_SUPL_CAMPOS_FORM_VALOR_DET" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_SUPL_CAMPOS_FORM_VALOR_DET" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PDS_SUPL_CAMPOS_FORM_VALOR_DET" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PDS_SUPL_CAMPOS_FORM_VALOR_DET" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_SUPL_CAMPOS_FORM_VALOR_DET" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PDS_SUPL_CAMPOS_FORM_VALOR_DET" TO "PROGRAMADORESCSI";
