--------------------------------------------------------
--  DDL for Table PDS_CODWIZARD
--------------------------------------------------------

  CREATE TABLE "AXIS"."PDS_CODWIZARD" 
   (	"CINSTALAC" VARCHAR2(30 BYTE) DEFAULT 'TERMINAL', 
	"SPRODUC" NUMBER, 
	"CMODO" VARCHAR2(20 BYTE), 
	"FORM_ACT" VARCHAR2(30 BYTE), 
	"FORM_ANT" VARCHAR2(30 BYTE), 
	"FORM_SIG" VARCHAR2(30 BYTE), 
	"CSITUAC" VARCHAR2(1 BYTE), 
	"NITERACIO" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PDS_CODWIZARD"."CINSTALAC" IS 'Configuración';
   COMMENT ON COLUMN "AXIS"."PDS_CODWIZARD"."SPRODUC" IS 'Identificador del producto';
   COMMENT ON COLUMN "AXIS"."PDS_CODWIZARD"."CMODO" IS 'Modo de uso, introducción';
   COMMENT ON COLUMN "AXIS"."PDS_CODWIZARD"."FORM_ACT" IS 'Formulario actual';
   COMMENT ON COLUMN "AXIS"."PDS_CODWIZARD"."FORM_ANT" IS 'Formulario anterior';
   COMMENT ON COLUMN "AXIS"."PDS_CODWIZARD"."FORM_SIG" IS 'Formulario siguiente';
   COMMENT ON COLUMN "AXIS"."PDS_CODWIZARD"."CSITUAC" IS 'Situación P.- Primer, U.- útimo, O.-otros situación intermedia';
   COMMENT ON COLUMN "AXIS"."PDS_CODWIZARD"."NITERACIO" IS 'Número de iteraciones del form,0 infinitas.';
  GRANT UPDATE ON "AXIS"."PDS_CODWIZARD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_CODWIZARD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PDS_CODWIZARD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PDS_CODWIZARD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_CODWIZARD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PDS_CODWIZARD" TO "PROGRAMADORESCSI";
