--------------------------------------------------------
--  DDL for Table PDS_ESTSIGFORM
--------------------------------------------------------

  CREATE TABLE "AXIS"."PDS_ESTSIGFORM" 
   (	"SSEGURO" NUMBER, 
	"TFORM" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PDS_ESTSIGFORM"."SSEGURO" IS 'sseguro de la tabla EST que está haciendo suplmento';
   COMMENT ON COLUMN "AXIS"."PDS_ESTSIGFORM"."TFORM" IS 'Formularios a los que tiene que ir para finalizar correctamente el supl.';
   COMMENT ON TABLE "AXIS"."PDS_ESTSIGFORM"  IS 'Tabla de navegación de formularios en suple';
  GRANT UPDATE ON "AXIS"."PDS_ESTSIGFORM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_ESTSIGFORM" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PDS_ESTSIGFORM" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PDS_ESTSIGFORM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_ESTSIGFORM" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PDS_ESTSIGFORM" TO "PROGRAMADORESCSI";
