--------------------------------------------------------
--  DDL for Table PDS_ESTSEGUROSUPL
--------------------------------------------------------

  CREATE TABLE "AXIS"."PDS_ESTSEGUROSUPL" 
   (	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER(3,0), 
	"CMOTMOV" NUMBER(3,0), 
	"FSUPLEM" DATE, 
	"CESTADO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PDS_ESTSEGUROSUPL"."SSEGURO" IS 'Id. del seguro tablas EST';
   COMMENT ON COLUMN "AXIS"."PDS_ESTSEGUROSUPL"."NMOVIMI" IS 'numero de movimiento';
   COMMENT ON COLUMN "AXIS"."PDS_ESTSEGUROSUPL"."CMOTMOV" IS 'Motivo de suplemento';
   COMMENT ON COLUMN "AXIS"."PDS_ESTSEGUROSUPL"."FSUPLEM" IS 'Fecha del suplemento';
   COMMENT ON COLUMN "AXIS"."PDS_ESTSEGUROSUPL"."CESTADO" IS 'Estado : 0, acción posible,X acción realizable, F:acción imcompatible con las hechas';
   COMMENT ON TABLE "AXIS"."PDS_ESTSEGUROSUPL"  IS 'Suplementos por seguro';
  GRANT UPDATE ON "AXIS"."PDS_ESTSEGUROSUPL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_ESTSEGUROSUPL" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PDS_ESTSEGUROSUPL" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PDS_ESTSEGUROSUPL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_ESTSEGUROSUPL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PDS_ESTSEGUROSUPL" TO "PROGRAMADORESCSI";
