--------------------------------------------------------
--  DDL for Table PDS_SUPL_CAMPOS_FORM
--------------------------------------------------------

  CREATE TABLE "AXIS"."PDS_SUPL_CAMPOS_FORM" 
   (	"CCONFIG" VARCHAR2(50 BYTE), 
	"TFORM" VARCHAR2(50 BYTE), 
	"TCAMPO" VARCHAR2(50 BYTE), 
	"TPROPERTY" VARCHAR2(50 BYTE), 
	"TVALUE" VARCHAR2(50 BYTE), 
	"NORDEN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PDS_SUPL_CAMPOS_FORM"."CCONFIG" IS 'Id. de la configuració (form+mode+motiu+prod)';
   COMMENT ON COLUMN "AXIS"."PDS_SUPL_CAMPOS_FORM"."TFORM" IS 'Formulario a modificar';
   COMMENT ON COLUMN "AXIS"."PDS_SUPL_CAMPOS_FORM"."TCAMPO" IS 'Campo del form a modificar';
   COMMENT ON COLUMN "AXIS"."PDS_SUPL_CAMPOS_FORM"."TPROPERTY" IS 'Propiedad a modificar';
   COMMENT ON COLUMN "AXIS"."PDS_SUPL_CAMPOS_FORM"."TVALUE" IS 'Valor de la propiedad a modificar';
   COMMENT ON TABLE "AXIS"."PDS_SUPL_CAMPOS_FORM"  IS 'Tabla de configuración de los campos de un formulario despues de realizar un suplemento';
  GRANT UPDATE ON "AXIS"."PDS_SUPL_CAMPOS_FORM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_SUPL_CAMPOS_FORM" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PDS_SUPL_CAMPOS_FORM" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PDS_SUPL_CAMPOS_FORM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PDS_SUPL_CAMPOS_FORM" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PDS_SUPL_CAMPOS_FORM" TO "PROGRAMADORESCSI";
