--------------------------------------------------------
--  DDL for Table PER_IDENTIFICADOR
--------------------------------------------------------

  CREATE TABLE "AXIS"."PER_IDENTIFICADOR" 
   (	"SPERSON" NUMBER(10,0), 
	"CAGENTE" NUMBER, 
	"CTIPIDE" NUMBER(3,0), 
	"NNUMIDE" VARCHAR2(50 BYTE), 
	"SWIDEPRI" NUMBER(1,0), 
	"FEMISIO" DATE, 
	"FCADUCA" DATE, 
	"CPAISEXP" NUMBER(5,0), 
	"CDEPARTEXP" NUMBER(10,0), 
	"CCIUDADEXP" NUMBER(5,0), 
	"FECHADEXP" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PER_IDENTIFICADOR"."SPERSON" IS 'Identificador de Persona';
   COMMENT ON COLUMN "AXIS"."PER_IDENTIFICADOR"."CTIPIDE" IS 'Código del tipo de identificador (v.f. 672)';
   COMMENT ON COLUMN "AXIS"."PER_IDENTIFICADOR"."NNUMIDE" IS 'Número de Identificador';
   COMMENT ON COLUMN "AXIS"."PER_IDENTIFICADOR"."SWIDEPRI" IS 'Indica si el identificador es el principal';
   COMMENT ON COLUMN "AXIS"."PER_IDENTIFICADOR"."FEMISIO" IS 'Fecha de emisión';
   COMMENT ON COLUMN "AXIS"."PER_IDENTIFICADOR"."FCADUCA" IS 'Fecha de caducidad';
   COMMENT ON COLUMN "AXIS"."PER_IDENTIFICADOR"."CPAISEXP" IS 'Pais de Expedicion';
   COMMENT ON COLUMN "AXIS"."PER_IDENTIFICADOR"."CDEPARTEXP" IS 'Departamenteo de Expedicion';
   COMMENT ON COLUMN "AXIS"."PER_IDENTIFICADOR"."CCIUDADEXP" IS 'Ciudad de Expedicion';
   COMMENT ON COLUMN "AXIS"."PER_IDENTIFICADOR"."FECHADEXP" IS 'Fecha de Expedicion';
   COMMENT ON TABLE "AXIS"."PER_IDENTIFICADOR"  IS 'Tabla que guarda los diferentes identificadores que puede tener una persona';
  GRANT UPDATE ON "AXIS"."PER_IDENTIFICADOR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PER_IDENTIFICADOR" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PER_IDENTIFICADOR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PER_IDENTIFICADOR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PER_IDENTIFICADOR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PER_IDENTIFICADOR" TO "PROGRAMADORESCSI";
