--------------------------------------------------------
--  DDL for Table PER_CIIU
--------------------------------------------------------

  CREATE TABLE "AXIS"."PER_CIIU" 
   (	"CCIIU" NUMBER(6,0), 
	"CIDIOMA" NUMBER(8,0), 
	"TCIIU" VARCHAR2(500 BYTE), 
	"NCALRIE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PER_CIIU"."CCIIU" IS 'Codigo de CIIU';
   COMMENT ON COLUMN "AXIS"."PER_CIIU"."CIDIOMA" IS 'Codigo del IDIOMA';
   COMMENT ON COLUMN "AXIS"."PER_CIIU"."TCIIU" IS 'Titul CIIU';
   COMMENT ON COLUMN "AXIS"."PER_CIIU"."NCALRIE" IS 'Calificaci¿n de Riesgo LA/FT';
  GRANT UPDATE ON "AXIS"."PER_CIIU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PER_CIIU" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PER_CIIU" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PER_CIIU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PER_CIIU" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PER_CIIU" TO "PROGRAMADORESCSI";
