--------------------------------------------------------
--  DDL for Table PERLOPD_PERSONAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."PERLOPD_PERSONAS" 
   (	"SPERSON" NUMBER(10,0), 
	"NNUMIDE" VARCHAR2(50 BYTE), 
	"NORDIDE" NUMBER(2,0), 
	"CTIPIDE" NUMBER(3,0), 
	"CSEXPER" NUMBER(1,0), 
	"FNACIMI" DATE, 
	"CESTPER" NUMBER(2,0) DEFAULT 0, 
	"FJUBILA" DATE, 
	"CUSUARI" VARCHAR2(20 BYTE), 
	"FMOVIMI" DATE, 
	"CMUTUALISTA" NUMBER(1,0) DEFAULT 0, 
	"FDEFUNC" DATE, 
	"NUM_LOPD" NUMBER, 
	"FLOPD" DATE, 
	"CTIPPER" NUMBER(3,0), 
	"SNIP" VARCHAR2(15 BYTE), 
	"TDIGITOIDE" VARCHAR2(1 BYTE), 
	"SWPUBLI" NUMBER, 
	"CAGENTE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."SPERSON" IS 'Secuencia unica de identificacion de una persona';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."NNUMIDE" IS 'Numero de Censo/Pasaporte de la persona';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."NORDIDE" IS 'Numero orden para posibles Censos/Pasaportes repetidos.';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."CTIPIDE" IS 'Tipo de identificación persona ( V.F. 672.  NIf, pasaporte, etc.';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."CSEXPER" IS 'Sexo de la persona';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."FNACIMI" IS 'Fecha de Nacimiento de la persona';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."CESTPER" IS 'Estado de la persona (V.F. 13)';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."FJUBILA" IS 'Fecha de Jubilacion de la persona';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."CUSUARI" IS 'Código usuario modificación registro';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."FMOVIMI" IS 'Fecha modificación registro';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."CMUTUALISTA" IS 'Indica si es mutualista o no. 0.- No es mutualista, 1.- Sí es mutualista';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."FDEFUNC" IS 'Fecha de Defunción';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."NUM_LOPD" IS 'Número de orden de histórico';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."FLOPD" IS 'Fecha de traspaso a las tablas PERLOPD';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."CTIPPER" IS 'Tipo de persona. Física o Jurídica (V.F. 85)';
   COMMENT ON COLUMN "AXIS"."PERLOPD_PERSONAS"."CAGENTE" IS 'Código del agente';
   COMMENT ON TABLE "AXIS"."PERLOPD_PERSONAS"  IS 'Tabla Maestra de información de personas';
  GRANT UPDATE ON "AXIS"."PERLOPD_PERSONAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PERLOPD_PERSONAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PERLOPD_PERSONAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PERLOPD_PERSONAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PERLOPD_PERSONAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PERLOPD_PERSONAS" TO "PROGRAMADORESCSI";
