--------------------------------------------------------
--  DDL for Table PERLOPD_IDENTIFICADOR
--------------------------------------------------------

  CREATE TABLE "AXIS"."PERLOPD_IDENTIFICADOR" 
   (	"SPERSON" NUMBER(10,0), 
	"CAGENTE" NUMBER, 
	"CTIPIDE" NUMBER(3,0), 
	"NNUMIDE" VARCHAR2(50 BYTE), 
	"SWIDEPRI" NUMBER(1,0), 
	"FEMISIO" DATE, 
	"FCADUCA" DATE, 
	"NUM_LOPD" NUMBER, 
	"FLOPD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PERLOPD_IDENTIFICADOR"."SPERSON" IS 'Identificador de Persona';
   COMMENT ON COLUMN "AXIS"."PERLOPD_IDENTIFICADOR"."CTIPIDE" IS 'Código del tipo de identificador (v.f. 672)';
   COMMENT ON COLUMN "AXIS"."PERLOPD_IDENTIFICADOR"."NNUMIDE" IS 'Número de Identificador';
   COMMENT ON COLUMN "AXIS"."PERLOPD_IDENTIFICADOR"."SWIDEPRI" IS 'Indica si el identificador es el principal';
   COMMENT ON COLUMN "AXIS"."PERLOPD_IDENTIFICADOR"."FEMISIO" IS 'Fecha de emisión';
   COMMENT ON COLUMN "AXIS"."PERLOPD_IDENTIFICADOR"."FCADUCA" IS 'Fecha de caducidad';
   COMMENT ON COLUMN "AXIS"."PERLOPD_IDENTIFICADOR"."NUM_LOPD" IS 'Número de orden de histórico';
   COMMENT ON COLUMN "AXIS"."PERLOPD_IDENTIFICADOR"."FLOPD" IS 'Fecha de traspaso a las tablas PERLOPD';
   COMMENT ON TABLE "AXIS"."PERLOPD_IDENTIFICADOR"  IS 'Tabla que guarda los diferentes identificadores que puede tener una persona';
  GRANT UPDATE ON "AXIS"."PERLOPD_IDENTIFICADOR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PERLOPD_IDENTIFICADOR" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PERLOPD_IDENTIFICADOR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PERLOPD_IDENTIFICADOR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PERLOPD_IDENTIFICADOR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PERLOPD_IDENTIFICADOR" TO "PROGRAMADORESCSI";
