--------------------------------------------------------
--  DDL for Table PERSONAS_ULK
--------------------------------------------------------

  CREATE TABLE "AXIS"."PERSONAS_ULK" 
   (	"SPERSON" NUMBER(10,0), 
	"CPERHOS" NUMBER(7,0), 
	"CNIFHOS" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PERSONAS_ULK"."SPERSON" IS 'Número de secuencia de persona';
   COMMENT ON COLUMN "AXIS"."PERSONAS_ULK"."CPERHOS" IS 'Número de persona en el HOST';
   COMMENT ON COLUMN "AXIS"."PERSONAS_ULK"."CNIFHOS" IS 'Código de NIF en el HOST';
  GRANT UPDATE ON "AXIS"."PERSONAS_ULK" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PERSONAS_ULK" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PERSONAS_ULK" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PERSONAS_ULK" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PERSONAS_ULK" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PERSONAS_ULK" TO "PROGRAMADORESCSI";
