--------------------------------------------------------
--  DDL for Table PILA_CUMULOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."PILA_CUMULOS" 
   (	"PILAPK" NUMBER(12,0), 
	"SSEGURO" NUMBER, 
	"FECHA" DATE, 
	"TPRODUCTO" VARCHAR2(10 BYTE), 
	"CMONEDA" NUMBER(1,0), 
	"SPERSON1" NUMBER(10,0), 
	"SPERSON2" NUMBER(10,0), 
	"UNIDADES" NUMBER, 
	"IMPORTES" NUMBER, 
	"FECHA_ENVIO" DATE, 
	"MOTIVO" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."PILA_CUMULOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PILA_CUMULOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PILA_CUMULOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PILA_CUMULOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PILA_CUMULOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PILA_CUMULOS" TO "PROGRAMADORESCSI";
