--------------------------------------------------------
--  DDL for Table PLANILLAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."PLANILLAS" 
   (	"CMAP" VARCHAR2(50 BYTE), 
	"CRAMO" NUMBER(8,0), 
	"SPRODUC" NUMBER(6,0), 
	"FPLANILLA" DATE, 
	"CCOMPANI" NUMBER, 
	"COBSERVACIONES" VARCHAR2(500 BYTE), 
	"CONSECUTIVO" NUMBER, 
	"CMONEDA" NUMBER, 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PLANILLAS"."CMAP" IS 'Codigo de reporte';
   COMMENT ON COLUMN "AXIS"."PLANILLAS"."CRAMO" IS 'Codigo del ramo';
   COMMENT ON COLUMN "AXIS"."PLANILLAS"."SPRODUC" IS 'Codigo de producto';
   COMMENT ON COLUMN "AXIS"."PLANILLAS"."FPLANILLA" IS 'Fecha de la planilla';
   COMMENT ON COLUMN "AXIS"."PLANILLAS"."CCOMPANI" IS 'Codigo de compa¿¿ia';
   COMMENT ON COLUMN "AXIS"."PLANILLAS"."COBSERVACIONES" IS 'Observaciones';
   COMMENT ON COLUMN "AXIS"."PLANILLAS"."CONSECUTIVO" IS 'consecutivo de la planilla';
   COMMENT ON COLUMN "AXIS"."PLANILLAS"."FALTA" IS 'Fecha de alta del registro';
   COMMENT ON COLUMN "AXIS"."PLANILLAS"."CUSUALT" IS 'Usuario alta';
  GRANT UPDATE ON "AXIS"."PLANILLAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PLANILLAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PLANILLAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PLANILLAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PLANILLAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PLANILLAS" TO "PROGRAMADORESCSI";
