--------------------------------------------------------
--  DDL for Table PLANRENTAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."PLANRENTAS" 
   (	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER(4,0), 
	"FECHAINI" DATE, 
	"FECHAFIN" DATE, 
	"IMPORTERENTA" NUMBER, 
	"INTER1" NUMBER(5,3), 
	"INTER2" NUMBER(5,3), 
	"ESTADO" NUMBER, 
	"SRECREN" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PLANRENTAS"."SSEGURO" IS 'Clave del seguro.';
   COMMENT ON COLUMN "AXIS"."PLANRENTAS"."NMOVIMI" IS 'Clave del movimiento';
   COMMENT ON COLUMN "AXIS"."PLANRENTAS"."FECHAINI" IS 'Fecha inicio para el impote de la renta.';
   COMMENT ON COLUMN "AXIS"."PLANRENTAS"."FECHAFIN" IS 'Fecha final para el impote de la renta.';
   COMMENT ON COLUMN "AXIS"."PLANRENTAS"."IMPORTERENTA" IS 'Importe renta.';
   COMMENT ON COLUMN "AXIS"."PLANRENTAS"."INTER1" IS 'Interes 2 de LRC';
   COMMENT ON COLUMN "AXIS"."PLANRENTAS"."SRECREN" IS 'Clave de la tabla pagosrenta';
  GRANT UPDATE ON "AXIS"."PLANRENTAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PLANRENTAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PLANRENTAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PLANRENTAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PLANRENTAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PLANRENTAS" TO "PROGRAMADORESCSI";
