--------------------------------------------------------
--  DDL for Table PLANTIVALORES
--------------------------------------------------------

  CREATE TABLE "AXIS"."PLANTIVALORES" 
   (	"CCODPLAN" VARCHAR2(20 BYTE), 
	"CIDIOMA" NUMBER(2,0), 
	"IDFORMULA" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PLANTIVALORES"."CCODPLAN" IS 'Código de la plantilla';
   COMMENT ON COLUMN "AXIS"."PLANTIVALORES"."CIDIOMA" IS 'Idioma - No se utiliza . Octubre 2003 - JAMR';
   COMMENT ON COLUMN "AXIS"."PLANTIVALORES"."IDFORMULA" IS 'Formula asociada';
   COMMENT ON TABLE "AXIS"."PLANTIVALORES"  IS 'Campos, formulas asociados a la plantillas';
  GRANT UPDATE ON "AXIS"."PLANTIVALORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PLANTIVALORES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PLANTIVALORES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PLANTIVALORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PLANTIVALORES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PLANTIVALORES" TO "PROGRAMADORESCSI";
