--------------------------------------------------------
--  DDL for Table PLANFISCAL
--------------------------------------------------------

  CREATE TABLE "AXIS"."PLANFISCAL" 
   (	"SSEGURO" NUMBER, 
	"NANO" NUMBER(4,0), 
	"DERECHOS" NUMBER, 
	"APORPROM" NUMBER, 
	"APORSP" NUMBER, 
	"APORPARTI" NUMBER, 
	"RETENCION" NUMBER, 
	"INETO" NUMBER, 
	"IRESRED" NUMBER, 
	"IRESRCM" NUMBER, 
	"RENTANETA_REN" NUMBER, 
	"IRESRCM_REN" NUMBER, 
	"RETENCION_REN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PLANFISCAL"."SSEGURO" IS 'Id. del seugro.';
   COMMENT ON COLUMN "AXIS"."PLANFISCAL"."NANO" IS 'Año';
   COMMENT ON COLUMN "AXIS"."PLANFISCAL"."DERECHOS" IS 'Importe Derechos consolidados anuales';
   COMMENT ON COLUMN "AXIS"."PLANFISCAL"."APORPROM" IS 'Importe Aportaciones promotor anuales';
   COMMENT ON COLUMN "AXIS"."PLANFISCAL"."APORSP" IS 'Importe Aportaciones servicios pasados anuales';
   COMMENT ON COLUMN "AXIS"."PLANFISCAL"."APORPARTI" IS 'Importe Aportaciones partícipe anual';
   COMMENT ON COLUMN "AXIS"."PLANFISCAL"."RETENCION" IS 'Importe Retención anual';
  GRANT UPDATE ON "AXIS"."PLANFISCAL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PLANFISCAL" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PLANFISCAL" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PLANFISCAL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PLANFISCAL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PLANFISCAL" TO "PROGRAMADORESCSI";
