--------------------------------------------------------
--  DDL for Table PLANTILLAS_SINIES_PAGO
--------------------------------------------------------

  CREATE TABLE "AXIS"."PLANTILLAS_SINIES_PAGO" 
   (	"CCODPLAN" VARCHAR2(20 BYTE), 
	"SPRODUC" NUMBER(6,0), 
	"CCAUSIN" NUMBER(4,0), 
	"CMOTSIN" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PLANTILLAS_SINIES_PAGO"."CCODPLAN" IS 'Id de la plantilla';
   COMMENT ON COLUMN "AXIS"."PLANTILLAS_SINIES_PAGO"."SPRODUC" IS 'Secuencia del producto';
   COMMENT ON COLUMN "AXIS"."PLANTILLAS_SINIES_PAGO"."CCAUSIN" IS 'ID Causa del Siniestro';
   COMMENT ON COLUMN "AXIS"."PLANTILLAS_SINIES_PAGO"."CMOTSIN" IS 'ID Motivo del Siniestro';
   COMMENT ON TABLE "AXIS"."PLANTILLAS_SINIES_PAGO"  IS 'Tipos de plantillas para siniestros que se llaman desde pantalla Java';
  GRANT UPDATE ON "AXIS"."PLANTILLAS_SINIES_PAGO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PLANTILLAS_SINIES_PAGO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PLANTILLAS_SINIES_PAGO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PLANTILLAS_SINIES_PAGO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PLANTILLAS_SINIES_PAGO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PLANTILLAS_SINIES_PAGO" TO "PROGRAMADORESCSI";
