--------------------------------------------------------
--  DDL for Table PLANTIPARAMETROS
--------------------------------------------------------

  CREATE TABLE "AXIS"."PLANTIPARAMETROS" 
   (	"CCODPLAN" VARCHAR2(20 BYTE), 
	"CPARAMETRO" VARCHAR2(30 BYTE), 
	"VALOR" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PLANTIPARAMETROS"."CCODPLAN" IS 'Código de la plantilla';
   COMMENT ON COLUMN "AXIS"."PLANTIPARAMETROS"."CPARAMETRO" IS 'Parámetro que debe estar dentro de la consulta de codiplantillas';
   COMMENT ON COLUMN "AXIS"."PLANTIPARAMETROS"."VALOR" IS 'Valor asociado al parametro';
   COMMENT ON TABLE "AXIS"."PLANTIPARAMETROS"  IS 'Valores asociados a los parametros de las plantillas';
  GRANT UPDATE ON "AXIS"."PLANTIPARAMETROS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PLANTIPARAMETROS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PLANTIPARAMETROS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PLANTIPARAMETROS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PLANTIPARAMETROS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PLANTIPARAMETROS" TO "PROGRAMADORESCSI";
