--------------------------------------------------------
--  DDL for Table POBLACIONES
--------------------------------------------------------

  CREATE TABLE "AXIS"."POBLACIONES" 
   (	"CPROVIN" NUMBER, 
	"CPOBLAC" NUMBER, 
	"TPOBLAC" VARCHAR2(50 BYTE), 
	"CPOBINE" NUMBER(5,0), 
	"CCOMARCAS" NUMBER, 
	"CMUNCOR" NUMBER(10,0), 
	"CFUENTE" NUMBER(1,0), 
	"TMUNBUS" VARCHAR2(100 BYTE), 
	"CVALMUN" NUMBER(1,0), 
	"NPUNDEP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."POBLACIONES"."CPROVIN" IS 'Codigo de Provincia';
   COMMENT ON COLUMN "AXIS"."POBLACIONES"."CPOBLAC" IS 'Código de Población';
   COMMENT ON COLUMN "AXIS"."POBLACIONES"."TPOBLAC" IS 'Nombre de la Poblacion';
   COMMENT ON COLUMN "AXIS"."POBLACIONES"."CPOBINE" IS 'Codigo poblacion INE';
   COMMENT ON COLUMN "AXIS"."POBLACIONES"."CCOMARCAS" IS 'Codigo de comarca.';
   COMMENT ON COLUMN "AXIS"."POBLACIONES"."CMUNCOR" IS 'Código de la Población según Correos';
   COMMENT ON COLUMN "AXIS"."POBLACIONES"."CFUENTE" IS 'Indica la fuente de procedencia (TeleAtlas, Correos, Manual, etc)';
   COMMENT ON COLUMN "AXIS"."POBLACIONES"."TMUNBUS" IS 'Descripción optimizada para búsquedas';
   COMMENT ON COLUMN "AXIS"."POBLACIONES"."CVALMUN" IS 'Indica si la población está confirmada';
   COMMENT ON COLUMN "AXIS"."POBLACIONES"."NPUNDEP" IS 'Puntaje depto';
   COMMENT ON TABLE "AXIS"."POBLACIONES"  IS 'Tabla Maestra Poblaciones';
  GRANT UPDATE ON "AXIS"."POBLACIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."POBLACIONES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."POBLACIONES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."POBLACIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."POBLACIONES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."POBLACIONES" TO "PROGRAMADORESCSI";
