--------------------------------------------------------
--  DDL for Table PORCENJURIDICA
--------------------------------------------------------

  CREATE TABLE "AXIS"."PORCENJURIDICA" 
   (	"CGARANT" NUMBER(4,0), 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"ANYO" NUMBER(4,0), 
	"PCESION" NUMBER(5,2), 
	"PRETENC" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."PORCENJURIDICA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PORCENJURIDICA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PORCENJURIDICA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PORCENJURIDICA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PORCENJURIDICA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PORCENJURIDICA" TO "PROGRAMADORESCSI";
