--------------------------------------------------------
--  DDL for Table POS_SAL_BONIFICACION
--------------------------------------------------------

  CREATE TABLE "AXIS"."POS_SAL_BONIFICACION" 
   (	"CRAMO" NUMBER, 
	"CTIPFIG" NUMBER, 
	"PBONIFICA" NUMBER(5,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."POS_SAL_BONIFICACION"."CRAMO" IS 'Identificador del ramo';
   COMMENT ON COLUMN "AXIS"."POS_SAL_BONIFICACION"."CTIPFIG" IS 'Tipo de figura comercial';
   COMMENT ON COLUMN "AXIS"."POS_SAL_BONIFICACION"."PBONIFICA" IS 'Porcentaje de bonificación sobre el salario';
   COMMENT ON TABLE "AXIS"."POS_SAL_BONIFICACION"  IS 'Tabla de porcentajes de bonificación sobre los salarios en Positiva';
  GRANT UPDATE ON "AXIS"."POS_SAL_BONIFICACION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."POS_SAL_BONIFICACION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."POS_SAL_BONIFICACION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."POS_SAL_BONIFICACION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."POS_SAL_BONIFICACION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."POS_SAL_BONIFICACION" TO "PROGRAMADORESCSI";
