--------------------------------------------------------
--  DDL for Table POS_SAL_DETALLE
--------------------------------------------------------

  CREATE TABLE "AXIS"."POS_SAL_DETALLE" 
   (	"CODIGO" VARCHAR2(20 BYTE), 
	"IDOBJETO" NUMBER, 
	"CRAMO" NUMBER, 
	"IIMPORTE" NUMBER, 
	"CAGENTE" NUMBER, 
	"CAGEORI" NUMBER, 
	"SPROCES" NUMBER, 
	"FCIERRE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."POS_SAL_DETALLE"."CODIGO" IS 'Código del detalle';
   COMMENT ON COLUMN "AXIS"."POS_SAL_DETALLE"."IDOBJETO" IS 'Identificador del objeto';
   COMMENT ON COLUMN "AXIS"."POS_SAL_DETALLE"."CRAMO" IS 'Código de ramo';
   COMMENT ON COLUMN "AXIS"."POS_SAL_DETALLE"."IIMPORTE" IS 'Importe';
   COMMENT ON COLUMN "AXIS"."POS_SAL_DETALLE"."CAGENTE" IS 'Código del agente';
   COMMENT ON COLUMN "AXIS"."POS_SAL_DETALLE"."CAGEORI" IS 'Código de agente original';
   COMMENT ON COLUMN "AXIS"."POS_SAL_DETALLE"."SPROCES" IS 'Código de proceso';
   COMMENT ON COLUMN "AXIS"."POS_SAL_DETALLE"."FCIERRE" IS 'Fecha de cierre';
   COMMENT ON TABLE "AXIS"."POS_SAL_DETALLE"  IS 'Tabla con el detalle de importes ';
  GRANT UPDATE ON "AXIS"."POS_SAL_DETALLE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."POS_SAL_DETALLE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."POS_SAL_DETALLE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."POS_SAL_DETALLE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."POS_SAL_DETALLE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."POS_SAL_DETALLE" TO "PROGRAMADORESCSI";
