--------------------------------------------------------
--  DDL for Table PPA_TEMP
--------------------------------------------------------

  CREATE TABLE "AXIS"."PPA_TEMP" 
   (	"SPERSON" NUMBER(10,0), 
	"NNUMNIF" VARCHAR2(50 BYTE), 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"DIREC" VARCHAR2(80 BYTE), 
	"CP" VARCHAR2(5 BYTE), 
	"POBLAC" VARCHAR2(80 BYTE), 
	"IAPORP" NUMBER, 
	"PFISCAL" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PPA_TEMP"."PFISCAL" IS 'Any Fiscal';
  GRANT UPDATE ON "AXIS"."PPA_TEMP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PPA_TEMP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PPA_TEMP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PPA_TEMP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PPA_TEMP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PPA_TEMP" TO "PROGRAMADORESCSI";
