--------------------------------------------------------
--  DDL for Table PREGUNPOLSEGTAB
--------------------------------------------------------

  CREATE TABLE "AXIS"."PREGUNPOLSEGTAB" 
   (	"SSEGURO" NUMBER, 
	"CPREGUN" NUMBER(4,0), 
	"NMOVIMI" NUMBER(4,0), 
	"NLINEA" NUMBER, 
	"CCOLUMNA" VARCHAR2(50 BYTE), 
	"TVALOR" VARCHAR2(250 BYTE), 
	"FVALOR" DATE, 
	"NVALOR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PREGUNPOLSEGTAB"."SSEGURO" IS 'Código del seguro';
   COMMENT ON COLUMN "AXIS"."PREGUNPOLSEGTAB"."CPREGUN" IS 'Código de la pregunta';
   COMMENT ON COLUMN "AXIS"."PREGUNPOLSEGTAB"."NMOVIMI" IS 'Movimiento póliza';
   COMMENT ON COLUMN "AXIS"."PREGUNPOLSEGTAB"."NLINEA" IS 'Linea del desglose';
   COMMENT ON COLUMN "AXIS"."PREGUNPOLSEGTAB"."CCOLUMNA" IS 'Identificador de la columna';
   COMMENT ON COLUMN "AXIS"."PREGUNPOLSEGTAB"."TVALOR" IS 'Respuesta columna(texto)';
   COMMENT ON COLUMN "AXIS"."PREGUNPOLSEGTAB"."FVALOR" IS 'Respuesta columna(Fecha)';
   COMMENT ON COLUMN "AXIS"."PREGUNPOLSEGTAB"."NVALOR" IS 'Respuesta columna(numerico)';
   COMMENT ON TABLE "AXIS"."PREGUNPOLSEGTAB"  IS 'Tabla respuestas de las columnas de las preguntas en formato tabla';
  GRANT UPDATE ON "AXIS"."PREGUNPOLSEGTAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PREGUNPOLSEGTAB" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PREGUNPOLSEGTAB" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PREGUNPOLSEGTAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PREGUNPOLSEGTAB" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PREGUNPOLSEGTAB" TO "PROGRAMADORESCSI";
