--------------------------------------------------------
--  DDL for Table PREGUNPOLCAR
--------------------------------------------------------

  CREATE TABLE "AXIS"."PREGUNPOLCAR" 
   (	"SSEGURO" NUMBER, 
	"CPREGUN" NUMBER(4,0), 
	"CRESPUE" FLOAT(126), 
	"NMOVIMI" NUMBER(4,0), 
	"SPROCES" NUMBER, 
	"TRESPUE" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PREGUNPOLCAR"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente.';
   COMMENT ON COLUMN "AXIS"."PREGUNPOLCAR"."CPREGUN" IS 'Código de la pregunta';
   COMMENT ON COLUMN "AXIS"."PREGUNPOLCAR"."CRESPUE" IS 'Código respuesta';
   COMMENT ON COLUMN "AXIS"."PREGUNPOLCAR"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."PREGUNPOLCAR"."SPROCES" IS 'Código del proceso';
   COMMENT ON TABLE "AXIS"."PREGUNPOLCAR"  IS 'Preguntas asociadas a un seguro';
  GRANT SELECT ON "AXIS"."PREGUNPOLCAR" TO "PROGRAMADORESCSI";
  GRANT UPDATE ON "AXIS"."PREGUNPOLCAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PREGUNPOLCAR" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PREGUNPOLCAR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PREGUNPOLCAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PREGUNPOLCAR" TO "CONF_DWH";
