--------------------------------------------------------
--  DDL for Table PREGUNCARTAB
--------------------------------------------------------

  CREATE TABLE "AXIS"."PREGUNCARTAB" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"CPREGUN" NUMBER(4,0), 
	"NMOVIMI" NUMBER(4,0), 
	"SPROCES" NUMBER, 
	"NLINEA" NUMBER, 
	"CCOLUMNA" VARCHAR2(50 BYTE), 
	"TVALOR" VARCHAR2(250 BYTE), 
	"FVALOR" DATE, 
	"NVALOR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PREGUNCARTAB"."SSEGURO" IS 'Código del seguro';
   COMMENT ON COLUMN "AXIS"."PREGUNCARTAB"."NRIESGO" IS 'nº Riesgo de la póliza';
   COMMENT ON COLUMN "AXIS"."PREGUNCARTAB"."CPREGUN" IS 'Código de la pregunta';
   COMMENT ON COLUMN "AXIS"."PREGUNCARTAB"."NMOVIMI" IS 'Movimiento póliza';
   COMMENT ON COLUMN "AXIS"."PREGUNCARTAB"."SPROCES" IS 'Código del proceso';
   COMMENT ON COLUMN "AXIS"."PREGUNCARTAB"."NLINEA" IS 'Linea del desglose';
   COMMENT ON COLUMN "AXIS"."PREGUNCARTAB"."CCOLUMNA" IS 'Identificador de la columna';
   COMMENT ON COLUMN "AXIS"."PREGUNCARTAB"."TVALOR" IS 'Respuesta columna(texto)';
   COMMENT ON COLUMN "AXIS"."PREGUNCARTAB"."FVALOR" IS 'Respuesta columna(Fecha)';
   COMMENT ON COLUMN "AXIS"."PREGUNCARTAB"."NVALOR" IS 'Respuesta columna(numerico)';
   COMMENT ON TABLE "AXIS"."PREGUNCARTAB"  IS 'Tabla respuestas de las columnas de las preguntas en formato tabla';
  GRANT UPDATE ON "AXIS"."PREGUNCARTAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PREGUNCARTAB" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PREGUNCARTAB" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PREGUNCARTAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PREGUNCARTAB" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PREGUNCARTAB" TO "PROGRAMADORESCSI";
