--------------------------------------------------------
--  DDL for Table PREGUNTAB_COLUM_DESLISTA
--------------------------------------------------------

  CREATE TABLE "AXIS"."PREGUNTAB_COLUM_DESLISTA" 
   (	"CPREGUN" NUMBER(4,0), 
	"COLUMNA" VARCHAR2(100 BYTE), 
	"CLISTA" NUMBER(10,0), 
	"CIDIOMA" NUMBER, 
	"TLISTA" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."PREGUNTAB_COLUM_DESLISTA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PREGUNTAB_COLUM_DESLISTA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PREGUNTAB_COLUM_DESLISTA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PREGUNTAB_COLUM_DESLISTA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PREGUNTAB_COLUM_DESLISTA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PREGUNTAB_COLUM_DESLISTA" TO "PROGRAMADORESCSI";
