--------------------------------------------------------
--  DDL for Table PREGUNGARANSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."PREGUNGARANSEG" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"CGARANT" NUMBER(4,0), 
	"NMOVIMI" NUMBER(4,0), 
	"CPREGUN" NUMBER(4,0), 
	"CRESPUE" FLOAT(126), 
	"NMOVIMA" NUMBER(4,0) DEFAULT 1, 
	"FINIEFE" DATE, 
	"TRESPUE" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PREGUNGARANSEG"."SSEGURO" IS 'Código Seguro';
   COMMENT ON COLUMN "AXIS"."PREGUNGARANSEG"."NRIESGO" IS 'Número Riesgo';
   COMMENT ON COLUMN "AXIS"."PREGUNGARANSEG"."CGARANT" IS 'Código Garantía';
   COMMENT ON COLUMN "AXIS"."PREGUNGARANSEG"."NMOVIMI" IS 'Número Movimiento';
   COMMENT ON COLUMN "AXIS"."PREGUNGARANSEG"."CPREGUN" IS 'Código Pregunta';
   COMMENT ON COLUMN "AXIS"."PREGUNGARANSEG"."CRESPUE" IS 'Valor respuesta';
   COMMENT ON COLUMN "AXIS"."PREGUNGARANSEG"."NMOVIMA" IS 'Número de movimiento de alta';
   COMMENT ON COLUMN "AXIS"."PREGUNGARANSEG"."FINIEFE" IS 'Fecha efecto del movimiento';
   COMMENT ON COLUMN "AXIS"."PREGUNGARANSEG"."TRESPUE" IS 'Descripción respuesta tipo texto';
   COMMENT ON TABLE "AXIS"."PREGUNGARANSEG"  IS 'Respuesta de las preguntas a nivel de garantía';
  GRANT UPDATE ON "AXIS"."PREGUNGARANSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PREGUNGARANSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PREGUNGARANSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PREGUNGARANSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PREGUNGARANSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PREGUNGARANSEG" TO "PROGRAMADORESCSI";
