--------------------------------------------------------
--  DDL for Table PRESTAMOPROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."PRESTAMOPROD" 
   (	"SPRODUC" NUMBER(6,0), 
	"CFORPAG" NUMBER(2,0), 
	"CINTERES" NUMBER(6,0), 
	"CINTDEMO" NUMBER(6,0), 
	"NMESDUR" NUMBER(3,0), 
	"CTIPAMORT" NUMBER(1,0), 
	"CTIPPRES" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PRESTAMOPROD"."SPRODUC" IS 'Identificador del producto';
   COMMENT ON COLUMN "AXIS"."PRESTAMOPROD"."CFORPAG" IS 'Código de forma de pago';
   COMMENT ON COLUMN "AXIS"."PRESTAMOPROD"."CINTERES" IS 'Código de la formula GFI con la que se obtienen los intereses';
   COMMENT ON COLUMN "AXIS"."PRESTAMOPROD"."CINTDEMO" IS 'Código de la formula GFI con la que se obtienen los intereses de mora';
   COMMENT ON COLUMN "AXIS"."PRESTAMOPROD"."NMESDUR" IS 'Duración del préstamo en meses';
   COMMENT ON COLUMN "AXIS"."PRESTAMOPROD"."CTIPAMORT" IS 'Tipo de amortización 1.- cuotas iguales, 2.- amortizaciones constantes';
   COMMENT ON COLUMN "AXIS"."PRESTAMOPROD"."CTIPPRES" IS 'Tipo de préstamo (VF. 712)';
   COMMENT ON TABLE "AXIS"."PRESTAMOPROD"  IS 'Características préstamos por producto';
  GRANT UPDATE ON "AXIS"."PRESTAMOPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRESTAMOPROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PRESTAMOPROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PRESTAMOPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRESTAMOPROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PRESTAMOPROD" TO "PROGRAMADORESCSI";
