--------------------------------------------------------
--  DDL for Table PRESTCAPITALES
--------------------------------------------------------

  CREATE TABLE "AXIS"."PRESTCAPITALES" 
   (	"CTAPRES" VARCHAR2(50 BYTE), 
	"FINICAP" DATE, 
	"FFINCAP" DATE, 
	"ICAPITAL" NUMBER, 
	"FVENCIM" DATE, 
	"FMOVIMI" DATE, 
	"FALTA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PRESTCAPITALES"."CTAPRES" IS 'Código del préstamo';
   COMMENT ON COLUMN "AXIS"."PRESTCAPITALES"."FINICAP" IS 'Fecha inicio del efecto';
   COMMENT ON COLUMN "AXIS"."PRESTCAPITALES"."FFINCAP" IS 'Fecha final del efecto';
   COMMENT ON COLUMN "AXIS"."PRESTCAPITALES"."ICAPITAL" IS 'Capital total del préstamo';
   COMMENT ON COLUMN "AXIS"."PRESTCAPITALES"."FVENCIM" IS 'Fecha de vencimiento del préstamo';
   COMMENT ON COLUMN "AXIS"."PRESTCAPITALES"."FMOVIMI" IS 'Día en que se inserta el registro';
   COMMENT ON COLUMN "AXIS"."PRESTCAPITALES"."FALTA" IS 'Fecha de alta del préstamo';
   COMMENT ON TABLE "AXIS"."PRESTCAPITALES"  IS 'Capitales de los préstamos';
  GRANT UPDATE ON "AXIS"."PRESTCAPITALES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRESTCAPITALES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PRESTCAPITALES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PRESTCAPITALES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRESTCAPITALES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PRESTCAPITALES" TO "PROGRAMADORESCSI";
