--------------------------------------------------------
--  DDL for Table PRESTAMOMOVPAGO
--------------------------------------------------------

  CREATE TABLE "AXIS"."PRESTAMOMOVPAGO" 
   (	"CTAPRES" VARCHAR2(50 BYTE), 
	"NPAGO" NUMBER(6,0), 
	"NMOVPAG" NUMBER(4,0), 
	"CESTPAG" NUMBER(1,0), 
	"FEFEPAG" DATE, 
	"CESTVAL" NUMBER(1,0), 
	"FCONTAB" DATE, 
	"SPROCES" NUMBER, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CESTPAGANT" NUMBER(1,0), 
	"CSUBPAG" NUMBER(1,0), 
	"CSUBPAGANT" NUMBER(1,0), 
	"FMOVINI" DATE, 
	"FMOVFIN" DATE, 
	"FMOVDIA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."CTAPRES" IS 'Id. del préstamo';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."NPAGO" IS 'Id. del Pago';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."NMOVPAG" IS 'Número Movimiento Pago';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."CESTPAG" IS 'Código Estado Pago. VALORES=3';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."FEFEPAG" IS 'Fecha Efecto Pago';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."CESTVAL" IS 'Código Estado Validación Pago. VALORES=324';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."FCONTAB" IS 'Fecha Contabilidad';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."SPROCES" IS 'Secuencia Proceso';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."CUSUALT" IS 'Código Usuario Alta';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."FALTA" IS 'Fecha Alta';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."CESTPAGANT" IS 'Código Estado Pago anterior';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."CSUBPAG" IS 'Código Subestado Pago. VALORES=1051';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."CSUBPAGANT" IS 'Código Subestado Pago anterior';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."FMOVINI" IS 'Fecha inicial movimiento';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."FMOVFIN" IS 'Fecha final movimiento';
   COMMENT ON COLUMN "AXIS"."PRESTAMOMOVPAGO"."FMOVDIA" IS 'Fecha del movimiento';
   COMMENT ON TABLE "AXIS"."PRESTAMOMOVPAGO"  IS 'Movimientos Pagos Prestamos';
  GRANT UPDATE ON "AXIS"."PRESTAMOMOVPAGO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRESTAMOMOVPAGO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PRESTAMOMOVPAGO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PRESTAMOMOVPAGO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRESTAMOMOVPAGO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PRESTAMOMOVPAGO" TO "PROGRAMADORESCSI";
