--------------------------------------------------------
--  DDL for Table PRESUPUESTO
--------------------------------------------------------

  CREATE TABLE "AXIS"."PRESUPUESTO" 
   (	"CZONA" NUMBER(6,0), 
	"CPARPRO" VARCHAR2(20 BYTE), 
	"CVALPAR" NUMBER(8,0), 
	"FCIERRE" DATE, 
	"CTIPIMP" NUMBER(1,0), 
	"IPRESUP" NUMBER, 
	"NUMPOL" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PRESUPUESTO"."CZONA" IS 'Código de zona (0-Si no hay)';
   COMMENT ON COLUMN "AXIS"."PRESUPUESTO"."CPARPRO" IS 'NEGOCI_ACT1 /NEGOCI_ACT2';
   COMMENT ON COLUMN "AXIS"."PRESUPUESTO"."CVALPAR" IS 'Valor del param.';
   COMMENT ON COLUMN "AXIS"."PRESUPUESTO"."FCIERRE" IS 'Fecha de cierre del presupuesto';
   COMMENT ON COLUMN "AXIS"."PRESUPUESTO"."CTIPIMP" IS 'Np, suplem, cartera (vf := 906)';
   COMMENT ON COLUMN "AXIS"."PRESUPUESTO"."IPRESUP" IS 'Importe del presupuesto';
   COMMENT ON COLUMN "AXIS"."PRESUPUESTO"."NUMPOL" IS 'Núm de pólizas previstas';
   COMMENT ON TABLE "AXIS"."PRESUPUESTO"  IS 'Presupuesto para la actividad ';
  GRANT UPDATE ON "AXIS"."PRESUPUESTO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRESUPUESTO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PRESUPUESTO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PRESUPUESTO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRESUPUESTO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PRESUPUESTO" TO "PROGRAMADORESCSI";
