--------------------------------------------------------
--  DDL for Table PROCESEXT
--------------------------------------------------------

  CREATE TABLE "AXIS"."PROCESEXT" 
   (	"SPERSON" NUMBER(10,0), 
	"CACTPRO" NUMBER(3,0), 
	"FPROCES" DATE, 
	"TFICHER" VARCHAR2(20 BYTE), 
	"CESTADO" NUMBER(3,0), 
	"TDESCRI" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT INSERT ON "AXIS"."PROCESEXT" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PROCESEXT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PROCESEXT" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PROCESEXT" TO "PROGRAMADORESCSI";
  GRANT UPDATE ON "AXIS"."PROCESEXT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PROCESEXT" TO "R_AXIS";
