--------------------------------------------------------
--  DDL for Table PRODCTACARGO
--------------------------------------------------------

  CREATE TABLE "AXIS"."PRODCTACARGO" 
   (	"SPRODUC" NUMBER(6,0), 
	"CCONCEP" NUMBER(3,0), 
	"CCOBBAN" NUMBER(3,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PRODCTACARGO"."SPRODUC" IS 'Código del producto, si es el generico ponemos un 0';
   COMMENT ON COLUMN "AXIS"."PRODCTACARGO"."CCONCEP" IS 'Valor 701, si es generico ponemos un 0';
   COMMENT ON COLUMN "AXIS"."PRODCTACARGO"."CCOBBAN" IS 'Cobrador bancario';
   COMMENT ON COLUMN "AXIS"."PRODCTACARGO"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."PRODCTACARGO"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."PRODCTACARGO"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."PRODCTACARGO"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON TABLE "AXIS"."PRODCTACARGO"  IS 'Cuentas de cargo por producto y concepto para transferencias';
  GRANT UPDATE ON "AXIS"."PRODCTACARGO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRODCTACARGO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PRODCTACARGO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PRODCTACARGO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRODCTACARGO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PRODCTACARGO" TO "PROGRAMADORESCSI";
