--------------------------------------------------------
--  DDL for Table PRODPARTICIPACION_AGENTE
--------------------------------------------------------

  CREATE TABLE "AXIS"."PRODPARTICIPACION_AGENTE" 
   (	"CAGENTE" NUMBER, 
	"SPRODUC" NUMBER(6,0), 
	"CACTIVI" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PRODPARTICIPACION_AGENTE"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."PRODPARTICIPACION_AGENTE"."SPRODUC" IS 'Código del producto';
   COMMENT ON COLUMN "AXIS"."PRODPARTICIPACION_AGENTE"."CACTIVI" IS 'Código de la actividad';
   COMMENT ON TABLE "AXIS"."PRODPARTICIPACION_AGENTE"  IS 'Productos para la participación de utilidades para el agente';
  GRANT UPDATE ON "AXIS"."PRODPARTICIPACION_AGENTE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRODPARTICIPACION_AGENTE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PRODPARTICIPACION_AGENTE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PRODPARTICIPACION_AGENTE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRODPARTICIPACION_AGENTE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PRODPARTICIPACION_AGENTE" TO "PROGRAMADORESCSI";
