--------------------------------------------------------
--  DDL for Table PRODAGRUPA_ANTIGUEDAD
--------------------------------------------------------

  CREATE TABLE "AXIS"."PRODAGRUPA_ANTIGUEDAD" 
   (	"CAGRUPA" NUMBER(3,0), 
	"SPRODUC" NUMBER(6,0), 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PRODAGRUPA_ANTIGUEDAD"."CAGRUPA" IS 'Código de la agrupación';
   COMMENT ON COLUMN "AXIS"."PRODAGRUPA_ANTIGUEDAD"."SPRODUC" IS 'Código del producto';
   COMMENT ON COLUMN "AXIS"."PRODAGRUPA_ANTIGUEDAD"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."PRODAGRUPA_ANTIGUEDAD"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."PRODAGRUPA_ANTIGUEDAD"."FMODIFI" IS 'Fecha de modificación';
   COMMENT ON COLUMN "AXIS"."PRODAGRUPA_ANTIGUEDAD"."CUSUMOD" IS 'Usuario de modificación';
   COMMENT ON TABLE "AXIS"."PRODAGRUPA_ANTIGUEDAD"  IS 'Agrupación por producto para la antigüedad por persona (tabla PER_ANTIGUEDAD)';
  GRANT UPDATE ON "AXIS"."PRODAGRUPA_ANTIGUEDAD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRODAGRUPA_ANTIGUEDAD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PRODAGRUPA_ANTIGUEDAD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PRODAGRUPA_ANTIGUEDAD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PRODAGRUPA_ANTIGUEDAD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PRODAGRUPA_ANTIGUEDAD" TO "PROGRAMADORESCSI";
