--------------------------------------------------------
--  DDL for Table PROFESIONPROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."PROFESIONPROD" 
   (	"CEMPRES" NUMBER(2,0), 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CACTIVI" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0), 
	"CGRUPPRO" NUMBER(4,0), 
	"CPROFES" NUMBER(6,0), 
	"PRECARG" NUMBER(6,2), 
	"IEXTRAP" NUMBER(19,12), 
	"CRETEN" CHAR(1 BYTE), 
	"FFECINI" DATE, 
	"FFECFIN" DATE, 
	"CGRURIES" NUMBER(2,0), 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."CEMPRES" IS 'Código de Empresa';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."CRAMO" IS 'Código ramo';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."CMODALI" IS 'Código modalidad';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."CTIPSEG" IS 'Código tipo de seguro';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."CCOLECT" IS 'Código de colectividad';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."CACTIVI" IS 'Código actividad';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."CGARANT" IS 'Código de garantía';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."CGRUPPRO" IS 'Grupo de profesiones';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."CPROFES" IS 'Profesión';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."PRECARG" IS 'Sobreprima';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."IEXTRAP" IS 'Extraprima';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."CRETEN" IS '¿Se retiene la póliza? (S=Si, N=No, R=Rechazar, F=Necesidad Facultativo)';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."FFECINI" IS 'Fecha inicio vigéncia';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."FFECFIN" IS 'Fecha fin vigéncia';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."CGRURIES" IS 'Código de Grupo de riesgo';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."PROFESIONPROD"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON TABLE "AXIS"."PROFESIONPROD"  IS 'Profesiones por producto, actividad y garantía';
  GRANT UPDATE ON "AXIS"."PROFESIONPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PROFESIONPROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PROFESIONPROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PROFESIONPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PROFESIONPROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PROFESIONPROD" TO "PROGRAMADORESCSI";
