--------------------------------------------------------
--  DDL for Table PROFESZONA
--------------------------------------------------------

  CREATE TABLE "AXIS"."PROFESZONA" 
   (	"CACTPRO" NUMBER(2,0), 
	"SPERSON" NUMBER(10,0), 
	"SZONA" NUMBER(7,0), 
	"SZONIF" NUMBER(4,0), 
	"CZONA" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON TABLE "AXIS"."PROFESZONA"  IS 'Assignació de profesionals a zones';
  GRANT UPDATE ON "AXIS"."PROFESZONA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PROFESZONA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PROFESZONA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PROFESZONA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PROFESZONA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PROFESZONA" TO "PROGRAMADORESCSI";
