--------------------------------------------------------
--  DDL for Table PROMOCIONPROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."PROMOCIONPROD" 
   (	"CPROMOC" NUMBER(2,0), 
	"SPRODUC" NUMBER(6,0), 
	"CFORMULA" NUMBER(6,0), 
	"CGARANT" NUMBER(4,0), 
	"FINICIO" DATE, 
	"FFINAL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PROMOCIONPROD"."CPROMOC" IS 'Código de Promoción';
   COMMENT ON COLUMN "AXIS"."PROMOCIONPROD"."SPRODUC" IS 'Código del Producto';
   COMMENT ON COLUMN "AXIS"."PROMOCIONPROD"."CFORMULA" IS 'Código de la Fórmula SGT';
   COMMENT ON COLUMN "AXIS"."PROMOCIONPROD"."CGARANT" IS 'Código de la Garantia';
   COMMENT ON COLUMN "AXIS"."PROMOCIONPROD"."FINICIO" IS 'Fecha inicio de la promoción';
   COMMENT ON COLUMN "AXIS"."PROMOCIONPROD"."FFINAL" IS 'Fecha fin de la promoción';
   COMMENT ON TABLE "AXIS"."PROMOCIONPROD"  IS 'Fórmulas asociadas a la promoción por producto o garantia';
  GRANT UPDATE ON "AXIS"."PROMOCIONPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PROMOCIONPROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PROMOCIONPROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PROMOCIONPROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PROMOCIONPROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PROMOCIONPROD" TO "PROGRAMADORESCSI";
