--------------------------------------------------------
--  DDL for Table PROVMAT_NMOVIMI_CONF
--------------------------------------------------------

  CREATE TABLE "AXIS"."PROVMAT_NMOVIMI_CONF" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER, 
	"CGARANT" NUMBER, 
	"NMOVIMI" NUMBER, 
	"FINIEFE" DATE, 
	"SPROCES" NUMBER, 
	"IPROVRES" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PROVMAT_NMOVIMI_CONF"."SSEGURO" IS 'Identificador de seguro';
   COMMENT ON COLUMN "AXIS"."PROVMAT_NMOVIMI_CONF"."NRIESGO" IS 'Identificador de riesgo';
   COMMENT ON COLUMN "AXIS"."PROVMAT_NMOVIMI_CONF"."CGARANT" IS 'C¿digo de garant¿a';
   COMMENT ON COLUMN "AXIS"."PROVMAT_NMOVIMI_CONF"."NMOVIMI" IS 'N¿mero de movimiento';
   COMMENT ON COLUMN "AXIS"."PROVMAT_NMOVIMI_CONF"."FINIEFE" IS 'Fecha efecto del movimiento';
   COMMENT ON COLUMN "AXIS"."PROVMAT_NMOVIMI_CONF"."SPROCES" IS 'Identificador de proceso de lanzamiento';
   COMMENT ON COLUMN "AXIS"."PROVMAT_NMOVIMI_CONF"."IPROVRES" IS 'Reserva IPROVRES del movimiento';
   COMMENT ON TABLE "AXIS"."PROVMAT_NMOVIMI_CONF"  IS 'Reservas seg¿n movimientos';
  GRANT UPDATE ON "AXIS"."PROVMAT_NMOVIMI_CONF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PROVMAT_NMOVIMI_CONF" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PROVMAT_NMOVIMI_CONF" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PROVMAT_NMOVIMI_CONF" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PROVMAT_NMOVIMI_CONF" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PROVMAT_NMOVIMI_CONF" TO "PROGRAMADORESCSI";
