--------------------------------------------------------
--  DDL for Table PROVISIONES
--------------------------------------------------------

  CREATE TABLE "AXIS"."PROVISIONES" 
   (	"SSEGURO" NUMBER, 
	"FPROVIS" DATE, 
	"IPROVIS" NUMBER, 
	"CTIPPRO" NUMBER(1,0), 
	"NRIESGO" NUMBER(6,0), 
	"CGARANT" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PROVISIONES"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente.';
   COMMENT ON COLUMN "AXIS"."PROVISIONES"."FPROVIS" IS 'Fecha';
   COMMENT ON COLUMN "AXIS"."PROVISIONES"."IPROVIS" IS 'Importe provisión';
  GRANT UPDATE ON "AXIS"."PROVISIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PROVISIONES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PROVISIONES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PROVISIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PROVISIONES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PROVISIONES" TO "PROGRAMADORESCSI";
