--------------------------------------------------------
--  DDL for Table PROVMAT
--------------------------------------------------------

  CREATE TABLE "AXIS"."PROVMAT" 
   (	"CEMPRES" NUMBER(2,0), 
	"FCALCUL" DATE, 
	"SPROCES" NUMBER, 
	"CRAMDGS" NUMBER(4,0), 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"SSEGURO" NUMBER, 
	"CGARANT" NUMBER(4,0), 
	"CPROVIS" NUMBER(2,0), 
	"IPRIINI" NUMBER, 
	"IVALACT" NUMBER, 
	"ICAPGAR" NUMBER, 
	"IPROMAT" NUMBER, 
	"CERROR" NUMBER(2,0), 
	"NRIESGO" NUMBER(6,0), 
	"IPRIINI_MONCON" NUMBER, 
	"IVALACT_MONCON" NUMBER, 
	"ICAPGAR_MONCON" NUMBER, 
	"IPROMAT_MONCON" NUMBER, 
	"FCAMBIO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PROVMAT"."IPRIINI_MONCON" IS 'Contravalor de IPRIINI en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."PROVMAT"."IVALACT_MONCON" IS 'Contravalor de IVALACT en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."PROVMAT"."ICAPGAR_MONCON" IS 'Contravalor de ICAPGAR en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."PROVMAT"."IPROMAT_MONCON" IS 'Contravalor de IPROMAT en la moneda de la contabilidad';
   COMMENT ON COLUMN "AXIS"."PROVMAT"."FCAMBIO" IS 'Fecha empleada para el cálculo de los contravalores';
  GRANT UPDATE ON "AXIS"."PROVMAT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PROVMAT" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PROVMAT" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PROVMAT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PROVMAT" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PROVMAT" TO "PROGRAMADORESCSI";
