--------------------------------------------------------
--  DDL for Table PSU_USUAGRU
--------------------------------------------------------

  CREATE TABLE "AXIS"."PSU_USUAGRU" 
   (	"CUSUARI" VARCHAR2(20 BYTE), 
	"CUSUAGRU" VARCHAR2(4 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PSU_USUAGRU"."CUSUARI" IS 'Código del Usuario';
   COMMENT ON COLUMN "AXIS"."PSU_USUAGRU"."CUSUAGRU" IS 'Código de la agrupación';
   COMMENT ON TABLE "AXIS"."PSU_USUAGRU"  IS 'Asociación Usuarios con sus Agrupaciones';
  GRANT UPDATE ON "AXIS"."PSU_USUAGRU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PSU_USUAGRU" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PSU_USUAGRU" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PSU_USUAGRU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PSU_USUAGRU" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PSU_USUAGRU" TO "PROGRAMADORESCSI";
