--------------------------------------------------------
--  DDL for Table PSU_DESUSUAGRU
--------------------------------------------------------

  CREATE TABLE "AXIS"."PSU_DESUSUAGRU" 
   (	"CUSUAGRU" VARCHAR2(4 BYTE), 
	"CIDIOMA" NUMBER(2,0), 
	"TUSUAGRU" VARCHAR2(50 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PSU_DESUSUAGRU"."CUSUAGRU" IS 'Código de la agrupación';
   COMMENT ON COLUMN "AXIS"."PSU_DESUSUAGRU"."CIDIOMA" IS 'Código de Idioma';
   COMMENT ON COLUMN "AXIS"."PSU_DESUSUAGRU"."TUSUAGRU" IS 'Descripción de al Agrupación';
   COMMENT ON COLUMN "AXIS"."PSU_DESUSUAGRU"."CUSUALT" IS 'Usuario creación';
   COMMENT ON COLUMN "AXIS"."PSU_DESUSUAGRU"."FALTA" IS 'Fecha creación';
   COMMENT ON COLUMN "AXIS"."PSU_DESUSUAGRU"."CUSUMOD" IS 'Usuario Modificación';
   COMMENT ON COLUMN "AXIS"."PSU_DESUSUAGRU"."FMODIFI" IS 'Fecha Modificación';
   COMMENT ON TABLE "AXIS"."PSU_DESUSUAGRU"  IS 'Descripción Agrupaciones de Usuarios para Controles';
  GRANT UPDATE ON "AXIS"."PSU_DESUSUAGRU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PSU_DESUSUAGRU" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PSU_DESUSUAGRU" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PSU_DESUSUAGRU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PSU_DESUSUAGRU" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PSU_DESUSUAGRU" TO "PROGRAMADORESCSI";
