--------------------------------------------------------
--  DDL for Table PTPPLP_PREVIO
--------------------------------------------------------

  CREATE TABLE "AXIS"."PTPPLP_PREVIO" 
   (	"CEMPRES" NUMBER(2,0), 
	"FCALCUL" DATE, 
	"SPROCES" NUMBER, 
	"CRAMDGS" NUMBER(4,0), 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"SSEGURO" NUMBER, 
	"NSINIES" VARCHAR2(14 BYTE), 
	"IPPLPSD" NUMBER, 
	"IPPLPRC" NUMBER, 
	"CERROR" NUMBER(2,0), 
	"IVALBRUTO" NUMBER, 
	"IVALPAGO" NUMBER, 
	"IPPL" NUMBER DEFAULT 0, 
	"IPPP" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PTPPLP_PREVIO"."IPPL" IS 'Importe de provisión pendiente de liquidar';
   COMMENT ON COLUMN "AXIS"."PTPPLP_PREVIO"."IPPP" IS 'Importe de provisión pendiente de pagar';
  GRANT UPDATE ON "AXIS"."PTPPLP_PREVIO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PTPPLP_PREVIO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PTPPLP_PREVIO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PTPPLP_PREVIO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PTPPLP_PREVIO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PTPPLP_PREVIO" TO "PROGRAMADORESCSI";
