--------------------------------------------------------
--  DDL for Table PTPPLP_CIA
--------------------------------------------------------

  CREATE TABLE "AXIS"."PTPPLP_CIA" 
   (	"SPROCES" NUMBER, 
	"CEMPRES" NUMBER(2,0), 
	"FCIERRE" DATE, 
	"SCONTRA" NUMBER(6,0), 
	"NVERSIO" NUMBER(2,0), 
	"CCOMPANI" NUMBER(4,0), 
	"NSINIES" VARCHAR2(14 BYTE), 
	"CGARANT" NUMBER(4,0), 
	"IPPLPRC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PTPPLP_CIA"."SPROCES" IS 'Sequencia del procés';
   COMMENT ON COLUMN "AXIS"."PTPPLP_CIA"."CEMPRES" IS 'Codi empresa';
   COMMENT ON COLUMN "AXIS"."PTPPLP_CIA"."FCIERRE" IS 'Data del tancament';
   COMMENT ON COLUMN "AXIS"."PTPPLP_CIA"."SCONTRA" IS 'Contracte de reassegurança';
   COMMENT ON COLUMN "AXIS"."PTPPLP_CIA"."NVERSIO" IS 'Versio del contracte de reassegurança';
   COMMENT ON COLUMN "AXIS"."PTPPLP_CIA"."CCOMPANI" IS 'Companyia reasseguradora';
   COMMENT ON COLUMN "AXIS"."PTPPLP_CIA"."IPPLPRC" IS 'Import provisió de sinistre de reassegurança';
   COMMENT ON TABLE "AXIS"."PTPPLP_CIA"  IS 'Taula on guardarem la provisió de sinistres de reassegurança';
  GRANT UPDATE ON "AXIS"."PTPPLP_CIA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PTPPLP_CIA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PTPPLP_CIA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PTPPLP_CIA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PTPPLP_CIA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PTPPLP_CIA" TO "PROGRAMADORESCSI";
