--------------------------------------------------------
--  DDL for Table PTPPLPGAR_PREVIO
--------------------------------------------------------

  CREATE TABLE "AXIS"."PTPPLPGAR_PREVIO" 
   (	"CEMPRES" NUMBER(2,0), 
	"FCALCUL" DATE, 
	"SPROCES" NUMBER, 
	"CRAMDGS" NUMBER(4,0), 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"SSEGURO" NUMBER, 
	"NSINIES" VARCHAR2(14 BYTE), 
	"IPPLPSD" NUMBER, 
	"IPPLPRC" NUMBER, 
	"CERROR" NUMBER(2,0), 
	"IVALBRUTO" NUMBER, 
	"IVALPAGO" NUMBER, 
	"IPPL" NUMBER, 
	"IPPP" NUMBER, 
	"CGARANT" NUMBER(4,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."CEMPRES" IS 'Código empresa';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."FCALCUL" IS 'Fecha de calculo';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."SPROCES" IS 'Código proceso generador';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."CRAMDGS" IS 'Código ramo DGS';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."CRAMO" IS 'Código ramo';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."CMODALI" IS 'Código modalidad';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."CTIPSEG" IS 'Código tipo de seguro';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."CCOLECT" IS 'Código de colectividad';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."SSEGURO" IS 'Número consecutivo de seguro';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."NSINIES" IS 'Número Siniestro';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."IPPLPSD" IS 'Importe de directo';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."IPPLPRC" IS 'Importe cedido';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."CERROR" IS 'Código error';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."IPPL" IS 'Importe de provisión pendiente de liquidar';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."IPPP" IS 'Importe de provisión pendiente de pagar';
   COMMENT ON COLUMN "AXIS"."PTPPLPGAR_PREVIO"."CGARANT" IS 'Código de garantía';
  GRANT UPDATE ON "AXIS"."PTPPLPGAR_PREVIO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PTPPLPGAR_PREVIO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."PTPPLPGAR_PREVIO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."PTPPLPGAR_PREVIO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PTPPLPGAR_PREVIO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PTPPLPGAR_PREVIO" TO "PROGRAMADORESCSI";
