--------------------------------------------------------
--  DDL for Table RAMOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."RAMOS" 
   (	"CIDIOMA" NUMBER(2,0), 
	"CRAMO" NUMBER(8,0), 
	"TRAMO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."RAMOS"."CIDIOMA" IS 'Código de Idioma';
   COMMENT ON COLUMN "AXIS"."RAMOS"."CRAMO" IS 'Código ramo';
   COMMENT ON COLUMN "AXIS"."RAMOS"."TRAMO" IS 'Descripción de ramo';
  GRANT UPDATE ON "AXIS"."RAMOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RAMOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."RAMOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."RAMOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RAMOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."RAMOS" TO "PROGRAMADORESCSI";
