--------------------------------------------------------
--  DDL for Table READEPOSITOAUX
--------------------------------------------------------

  CREATE TABLE "AXIS"."READEPOSITOAUX" 
   (	"CCOMPANI" NUMBER(3,0), 
	"NVERSIO" NUMBER(2,0), 
	"SCONTRA" NUMBER(6,0), 
	"CTRAMO" NUMBER(2,0), 
	"SPROCES" NUMBER, 
	"SCESREA" NUMBER(8,0), 
	"CEMPRES" NUMBER(2,0), 
	"FCIERRE" DATE, 
	"SPRODUC" NUMBER(6,0), 
	"SSEGURO" NUMBER, 
	"NPOLIZA" NUMBER, 
	"NCERTIF" NUMBER, 
	"NSINIES" NUMBER, 
	"CAGENTE" NUMBER, 
	"PPARTICI" NUMBER(6,2), 
	"CCOMPAPR" NUMBER(3,0), 
	"ICESION" NUMBER, 
	"PRESERV" NUMBER(6,2), 
	"IRESERV" NUMBER, 
	"ICESION_MONCON" NUMBER, 
	"IRESERV_MONCON" NUMBER, 
	"PINTERESDEP" NUMBER(6,2), 
	"IINTERDEP" NUMBER, 
	"IINTERDEP_MONCON" NUMBER, 
	"PIMPINT" NUMBER(6,2), 
	"IIMPINT" NUMBER, 
	"IIMPINT_MONCON" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."CCOMPANI" IS 'Código de compañía';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."NVERSIO" IS 'Número de versión';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."SCONTRA" IS 'Código del contrato';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."CTRAMO" IS 'Código del tramo';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."SPROCES" IS 'Código del proceso';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."SCESREA" IS 'Secuencia de la cesión del reaseguro';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."CEMPRES" IS 'Código de empresa';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."FCIERRE" IS 'Fecha de cierre';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."SPRODUC" IS 'Secuencia del producto';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."SSEGURO" IS 'Código de seguro';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."NPOLIZA" IS 'Número de póliza';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."NCERTIF" IS 'Número de certificado para pólizas colectivas';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."NSINIES" IS 'Número de siniestro';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."CAGENTE" IS 'Código del agente';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."PPARTICI" IS 'Porcentaje de participación del agente en la póliza';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."CCOMPAPR" IS 'Código compañía propia (CCOMPANI de SEGUROS)';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."ICESION" IS 'Importe de la cesión por agente';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."PRESERV" IS 'Porcentaje que se aplica a la cesión para calcular la reserva';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."IRESERV" IS 'Importe de la reserva';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."ICESION_MONCON" IS 'Importe de la cesión por agente en la moneda contable';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."IRESERV_MONCON" IS 'Importe de la reserva en la moneda contable';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."PINTERESDEP" IS 'Porcentaje de interés sobre el depósito de la reserva';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."IINTERDEP" IS 'Importe del interés sobre el depósito de la reserva';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."IINTERDEP_MONCON" IS 'Importe del interés sobre el depósito en la moneda contable';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."PIMPINT" IS 'Porcentaje del impuesto sobre los intereses del depósito';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."IIMPINT" IS 'Importe del impuesto sobre los intereses del depósito';
   COMMENT ON COLUMN "AXIS"."READEPOSITOAUX"."IIMPINT_MONCON" IS 'Importe del impuesto sobre los intereses del depósito en la moneda contable';
  GRANT SELECT ON "AXIS"."READEPOSITOAUX" TO "PROGRAMADORESCSI";
  GRANT DELETE ON "AXIS"."READEPOSITOAUX" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."READEPOSITOAUX" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."READEPOSITOAUX" TO "R_AXIS";
  GRANT UPDATE ON "AXIS"."READEPOSITOAUX" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."READEPOSITOAUX" TO "CONF_DWH";
