--------------------------------------------------------
--  DDL for Table REAFORMULA
--------------------------------------------------------

  CREATE TABLE "AXIS"."REAFORMULA" 
   (	"SCONTRA" NUMBER(6,0), 
	"NVERSIO" NUMBER(2,0), 
	"CGARANT" NUMBER(4,0), 
	"CCAMPO" VARCHAR2(8 BYTE), 
	"CLAVE" NUMBER(6,0), 
	"SPRODUC" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."REAFORMULA"."SCONTRA" IS 'Código de contrato';
   COMMENT ON COLUMN "AXIS"."REAFORMULA"."NVERSIO" IS 'Número de versión del contrato';
   COMMENT ON COLUMN "AXIS"."REAFORMULA"."CGARANT" IS 'Código de garantia';
   COMMENT ON COLUMN "AXIS"."REAFORMULA"."CCAMPO" IS 'Código de campo (prima reas/capital reas/...)';
   COMMENT ON COLUMN "AXIS"."REAFORMULA"."CLAVE" IS 'Código de fórmula';
   COMMENT ON COLUMN "AXIS"."REAFORMULA"."SPRODUC" IS 'Código de la secuencia del producto (Si es nulo = todos)';
   COMMENT ON TABLE "AXIS"."REAFORMULA"  IS 'Relación de contratos de reaseguro con fórmulas SGT';
  GRANT UPDATE ON "AXIS"."REAFORMULA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REAFORMULA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."REAFORMULA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."REAFORMULA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REAFORMULA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."REAFORMULA" TO "PROGRAMADORESCSI";
