--------------------------------------------------------
--  DDL for Table REARIESGOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."REARIESGOS" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"FREAINI" DATE, 
	"CGARANT" NUMBER(4,0), 
	"SCUMULO" NUMBER(6,0), 
	"SCONTRA" NUMBER(6,0), 
	"FREAFIN" DATE, 
	"NVERSIO" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."REARIESGOS"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente.';
   COMMENT ON COLUMN "AXIS"."REARIESGOS"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."REARIESGOS"."FREAINI" IS 'Fecha inicio reaseguro';
   COMMENT ON COLUMN "AXIS"."REARIESGOS"."CGARANT" IS 'Código de garantía';
   COMMENT ON COLUMN "AXIS"."REARIESGOS"."SCUMULO" IS 'Identificador de un cúmulo';
   COMMENT ON COLUMN "AXIS"."REARIESGOS"."FREAFIN" IS 'Fecha fin reaseguro';
  GRANT UPDATE ON "AXIS"."REARIESGOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REARIESGOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."REARIESGOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."REARIESGOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REARIESGOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."REARIESGOS" TO "PROGRAMADORESCSI";
