--------------------------------------------------------
--  DDL for Table REASEGEMI
--------------------------------------------------------

  CREATE TABLE "AXIS"."REASEGEMI" 
   (	"SREAEMI" NUMBER(8,0), 
	"SSEGURO" NUMBER, 
	"NRECIBO" NUMBER, 
	"NFACTOR" NUMBER, 
	"FEFECTE" DATE, 
	"FVENCIM" DATE, 
	"FCIERRE" DATE, 
	"FGENERA" DATE, 
	"CMOTCES" NUMBER(1,0), 
	"SPROCES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."REASEGEMI"."SREAEMI" IS 'Clave primaria';
   COMMENT ON COLUMN "AXIS"."REASEGEMI"."SSEGURO" IS 'Numero de seguro';
   COMMENT ON COLUMN "AXIS"."REASEGEMI"."NFACTOR" IS 'Factor de prorrateo aplicado';
   COMMENT ON COLUMN "AXIS"."REASEGEMI"."FEFECTE" IS 'Fecha efecto del recibo';
   COMMENT ON COLUMN "AXIS"."REASEGEMI"."FVENCIM" IS 'Fecha vencimiento del recibo';
   COMMENT ON COLUMN "AXIS"."REASEGEMI"."FCIERRE" IS 'Fecha cierre reaseguro';
   COMMENT ON COLUMN "AXIS"."REASEGEMI"."FGENERA" IS 'Fecha generación del recibo';
   COMMENT ON COLUMN "AXIS"."REASEGEMI"."CMOTCES" IS 'Motivo cesión 1-Emisión, 2-Anulación';
  GRANT UPDATE ON "AXIS"."REASEGEMI" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REASEGEMI" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."REASEGEMI" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."REASEGEMI" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REASEGEMI" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."REASEGEMI" TO "PROGRAMADORESCSI";
