--------------------------------------------------------
--  DDL for Table RECEXTORNADOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."RECEXTORNADOS" 
   (	"NRECIBO" NUMBER, 
	"NEXTORNO" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."RECEXTORNADOS"."NRECIBO" IS 'Número de recibo de extorno';
   COMMENT ON COLUMN "AXIS"."RECEXTORNADOS"."NEXTORNO" IS 'Número de recibo relacionado';
  GRANT UPDATE ON "AXIS"."RECEXTORNADOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RECEXTORNADOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."RECEXTORNADOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."RECEXTORNADOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RECEXTORNADOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."RECEXTORNADOS" TO "PROGRAMADORESCSI";
