--------------------------------------------------------
--  DDL for Table RECIBO_DOCUMENTOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."RECIBO_DOCUMENTOS" 
   (	"NRECIBO" NUMBER, 
	"NDOCUME" NUMBER(6,0), 
	"NIMPRESIONES" NUMBER(6,0), 
	"IDDOC" NUMBER(10,0), 
	"TUSER" VARCHAR2(30 BYTE), 
	"FDATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."RECIBO_DOCUMENTOS"."NRECIBO" IS 'Número Recibo';
   COMMENT ON COLUMN "AXIS"."RECIBO_DOCUMENTOS"."NDOCUME" IS 'Número Documento Recibo';
   COMMENT ON COLUMN "AXIS"."RECIBO_DOCUMENTOS"."NIMPRESIONES" IS 'Número de reimpresiones del recibo';
   COMMENT ON COLUMN "AXIS"."RECIBO_DOCUMENTOS"."IDDOC" IS 'ID de Gedox del documento';
   COMMENT ON COLUMN "AXIS"."RECIBO_DOCUMENTOS"."TUSER" IS 'Usuario que crea el documento';
   COMMENT ON COLUMN "AXIS"."RECIBO_DOCUMENTOS"."FDATE" IS 'Fecha en que se crea el documento';
   COMMENT ON TABLE "AXIS"."RECIBO_DOCUMENTOS"  IS 'Duplicados de recibo';
  GRANT UPDATE ON "AXIS"."RECIBO_DOCUMENTOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RECIBO_DOCUMENTOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."RECIBO_DOCUMENTOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."RECIBO_DOCUMENTOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RECIBO_DOCUMENTOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."RECIBO_DOCUMENTOS" TO "PROGRAMADORESCSI";
