--------------------------------------------------------
--  DDL for Table REEMBSINCES
--------------------------------------------------------

  CREATE TABLE "AXIS"."REEMBSINCES" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"CGARANT" NUMBER(6,0), 
	"NREEMB" NUMBER(8,0), 
	"NFACT" NUMBER(8,0), 
	"NLINEA" NUMBER(4,0), 
	"FEFECTO" DATE, 
	"IPAGO" NUMBER, 
	"FGENERA" DATE, 
	"CREVISI" NUMBER(1,0), 
	"FREVISI" DATE, 
	"CUSUARI" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."REEMBSINCES"."SSEGURO" IS 'Id. del seguro';
   COMMENT ON COLUMN "AXIS"."REEMBSINCES"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."REEMBSINCES"."CGARANT" IS 'Código de garantía';
   COMMENT ON COLUMN "AXIS"."REEMBSINCES"."NREEMB" IS 'Nº de reembolso';
   COMMENT ON COLUMN "AXIS"."REEMBSINCES"."NFACT" IS 'Nº de factura interno';
   COMMENT ON COLUMN "AXIS"."REEMBSINCES"."NLINEA" IS 'Nº de línea';
   COMMENT ON COLUMN "AXIS"."REEMBSINCES"."FEFECTO" IS 'Fecha de efecto';
   COMMENT ON COLUMN "AXIS"."REEMBSINCES"."IPAGO" IS 'Importe a pagar (aceptado)';
   COMMENT ON COLUMN "AXIS"."REEMBSINCES"."FGENERA" IS 'Fecha de creación';
   COMMENT ON COLUMN "AXIS"."REEMBSINCES"."CREVISI" IS '1 Pendiente de revisar; 2 Revisado';
   COMMENT ON COLUMN "AXIS"."REEMBSINCES"."FREVISI" IS 'Fecha de revisión';
   COMMENT ON COLUMN "AXIS"."REEMBSINCES"."CUSUARI" IS 'Usuario revisión';
   COMMENT ON TABLE "AXIS"."REEMBSINCES"  IS 'Control de cesiones de reembolsos';
  GRANT UPDATE ON "AXIS"."REEMBSINCES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REEMBSINCES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."REEMBSINCES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."REEMBSINCES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REEMBSINCES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."REEMBSINCES" TO "PROGRAMADORESCSI";
