--------------------------------------------------------
--  DDL for Table REEMB_SINIESTRALIDAD
--------------------------------------------------------

  CREATE TABLE "AXIS"."REEMB_SINIESTRALIDAD" 
   (	"SPROCES" NUMBER, 
	"SSEGURO" NUMBER, 
	"NPOLIZA" NUMBER, 
	"NCERTIF" NUMBER, 
	"TNOM_COL" VARCHAR2(200 BYTE), 
	"SPRODUC" NUMBER(6,0), 
	"TPRODUCTO" VARCHAR2(34 BYTE), 
	"FEFECTO" DATE, 
	"TNOMBRE" VARCHAR2(200 BYTE), 
	"ITOT80_TOT" NUMBER, 
	"IPAG_TOT" NUMBER, 
	"IEXTRA_TOT" NUMBER, 
	"ICOMP_TOT" NUMBER, 
	"IPREST_TOT" NUMBER, 
	"PRATIO_TOT" NUMBER, 
	"ITOT80_ACT" NUMBER, 
	"IPAG_ACT" NUMBER, 
	"IEXTRA_ACT" NUMBER, 
	"ICOMP_ACT" NUMBER, 
	"IPREST_ACT" NUMBER, 
	"PRATIO_ACT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."SPROCES" IS 'Número de proceso';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."SSEGURO" IS 'Sequence SEGUROS';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."NPOLIZA" IS 'numero de poliza';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."NCERTIF" IS 'numero de certificado';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."TNOM_COL" IS 'Nombre colectivo';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."SPRODUC" IS 'Sequence Procutos';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."TPRODUCTO" IS 'Nombre producto';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."FEFECTO" IS 'Efecto riesgo';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."TNOMBRE" IS 'Nombre Tomador';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."ITOT80_TOT" IS 'Importe primas total';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."IPAG_TOT" IS 'Importe pagos reembolso complemento CASS total';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."IEXTRA_TOT" IS 'Importe pagos importe extra total';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."ICOMP_TOT" IS 'Importe pagos reembolso complemento factura total';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."IPREST_TOT" IS 'Importe total prestaciones';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."PRATIO_TOT" IS 'Ratio total';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."ITOT80_ACT" IS 'Importe primas año actual';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."IPAG_ACT" IS 'Importe pagos reembolso complemento CASS año en curso';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."IEXTRA_ACT" IS 'Importe pagos importe extra año en curso';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."ICOMP_ACT" IS 'Importe pagos reembolso complemento factura año en curso';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."IPREST_ACT" IS 'Importe prestaciones año actual';
   COMMENT ON COLUMN "AXIS"."REEMB_SINIESTRALIDAD"."PRATIO_ACT" IS 'Ratio año actual';
   COMMENT ON TABLE "AXIS"."REEMB_SINIESTRALIDAD"  IS 'Tabla para el listado de SINIESTRALIDAD';
  GRANT UPDATE ON "AXIS"."REEMB_SINIESTRALIDAD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REEMB_SINIESTRALIDAD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."REEMB_SINIESTRALIDAD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."REEMB_SINIESTRALIDAD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REEMB_SINIESTRALIDAD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."REEMB_SINIESTRALIDAD" TO "PROGRAMADORESCSI";
