--------------------------------------------------------
--  DDL for Table REEXPRESIONES
--------------------------------------------------------

  CREATE TABLE "AXIS"."REEXPRESIONES" 
   (	"CEMPRES" NUMBER(2,0), 
	"SPROCES" NUMBER, 
	"TIPOREEXP" NUMBER, 
	"FREEXP" DATE, 
	"FINICIAL" DATE, 
	"SCONTRA" NUMBER(6,0), 
	"CCOMPANI" NUMBER(4,0), 
	"NVERSIO" NUMBER(2,0), 
	"CTRAMO" NUMBER(2,0), 
	"SPRODUC" NUMBER(6,0), 
	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER(4,0), 
	"TIPO" NUMBER(2,0), 
	"CMONORI" VARCHAR2(3 BYTE), 
	"IMP_MONORI" NUMBER, 
	"CMONDES" VARCHAR2(3 BYTE), 
	"IMP_MONDES_INI" NUMBER, 
	"IMP_MONDES_FIN" NUMBER, 
	"CMONCON" VARCHAR2(3 BYTE), 
	"IMP_MONCON_INI" NUMBER, 
	"IMP_MONCON_FIN" NUMBER, 
	"IMP_REEXP" NUMBER, 
	"FCREAC" DATE, 
	"USUCREA" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."CEMPRES" IS 'Codigo de Empresa';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."SPROCES" IS 'Sequencia del proceso';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."TIPOREEXP" IS 'Tipo de valor Reexpresado: 1-Movimiento seguro, 2-Saldo de Cierre, 3-Reembolso';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."FREEXP" IS 'Fecha en que se realiza la reexpresion';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."FINICIAL" IS 'Fecha base contra la que se hace la reexpresion';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."SCONTRA" IS 'Contrato de reaseguro';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."CCOMPANI" IS 'Compania reasseguradora';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."NVERSIO" IS 'Versi真n del Contrato';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."CTRAMO" IS 'C真digo del tramo';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."SPRODUC" IS 'Secuencia del producto';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."SSEGURO" IS 'Secuencia del seguro';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."NMOVIMI" IS 'N真mero del movimiento';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."TIPO" IS 'Tipo de reexpresi真n: 1-En Cierre, 2-En liquidaci真n';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."CMONORI" IS 'C真digo de la moneda de origen';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."IMP_MONORI" IS 'Importe en moneda original';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."CMONDES" IS 'C真digo de la moneda destino';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."IMP_MONDES_INI" IS 'Importe en moneda destino a fecha inicial';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."IMP_MONDES_FIN" IS 'Importe en moneda destino a fecha final';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."CMONCON" IS 'C真digo de la moneda contable';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."IMP_MONCON_INI" IS 'Importe en moneda contable a fecha inicial';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."IMP_MONCON_FIN" IS 'Importe en moneda contable a fecha final';
   COMMENT ON COLUMN "AXIS"."REEXPRESIONES"."IMP_REEXP" IS 'Importe reexpresado en Moneda Contable';
   COMMENT ON TABLE "AXIS"."REEXPRESIONES"  IS 'Tabla que guarda la reexpresi真n de un saldo en la moneda original y en moneda contable.';
  GRANT UPDATE ON "AXIS"."REEXPRESIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REEXPRESIONES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."REEXPRESIONES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."REEXPRESIONES" TO "R_AXIS";
  GRANT UPDATE ON "AXIS"."REEXPRESIONES" TO PUBLIC;
  GRANT SELECT ON "AXIS"."REEXPRESIONES" TO PUBLIC;
  GRANT INSERT ON "AXIS"."REEXPRESIONES" TO PUBLIC;
  GRANT DELETE ON "AXIS"."REEXPRESIONES" TO PUBLIC;
  GRANT SELECT ON "AXIS"."REEXPRESIONES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."REEXPRESIONES" TO "PROGRAMADORESCSI";
