--------------------------------------------------------
--  DDL for Table REGALOSPROM
--------------------------------------------------------

  CREATE TABLE "AXIS"."REGALOSPROM" 
   (	"CPROMOC" NUMBER(2,0), 
	"CREGALO" NUMBER(2,0), 
	"FINICIO" DATE, 
	"FFINAL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."REGALOSPROM"."CPROMOC" IS 'Código de la promoción';
   COMMENT ON COLUMN "AXIS"."REGALOSPROM"."CREGALO" IS 'Código del regalo';
   COMMENT ON COLUMN "AXIS"."REGALOSPROM"."FINICIO" IS 'Fecha inicio validez del regalo';
   COMMENT ON COLUMN "AXIS"."REGALOSPROM"."FFINAL" IS 'Fecha fin validez del regalo';
   COMMENT ON TABLE "AXIS"."REGALOSPROM"  IS 'Regalos que existen en una promoción';
  GRANT UPDATE ON "AXIS"."REGALOSPROM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REGALOSPROM" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."REGALOSPROM" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."REGALOSPROM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REGALOSPROM" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."REGALOSPROM" TO "PROGRAMADORESCSI";
