--------------------------------------------------------
--  DDL for Table RELACIONPAREN
--------------------------------------------------------

  CREATE TABLE "AXIS"."RELACIONPAREN" 
   (	"CPAREN1" NUMBER(2,0), 
	"CPAREN2" NUMBER(2,0), 
	"CRELACION" NUMBER(2,0), 
	"CGRADO" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."RELACIONPAREN"."CPAREN1" IS 'Código parentesco del Tomador.';
   COMMENT ON COLUMN "AXIS"."RELACIONPAREN"."CPAREN2" IS 'Código parentesco del Riesgo.';
   COMMENT ON COLUMN "AXIS"."RELACIONPAREN"."CRELACION" IS 'Tipo de Relación.(LABORAL, FAMILIAR , etc.) CVALOR = 874';
   COMMENT ON COLUMN "AXIS"."RELACIONPAREN"."CGRADO" IS 'Grado de parentesco. (Primer grado, Segundo grado , etc.). DETVALOR = 866';
   COMMENT ON TABLE "AXIS"."RELACIONPAREN"  IS 'Relaciones de parentescos';
  GRANT UPDATE ON "AXIS"."RELACIONPAREN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RELACIONPAREN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."RELACIONPAREN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."RELACIONPAREN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RELACIONPAREN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."RELACIONPAREN" TO "PROGRAMADORESCSI";
