--------------------------------------------------------
--  DDL for Table RELFONDEP
--------------------------------------------------------

  CREATE TABLE "AXIS"."RELFONDEP" 
   (	"CCODFON" NUMBER(6,0), 
	"CCODDEP" NUMBER(4,0), 
	"CTIPBAN" NUMBER(3,0), 
	"CBANCAR" VARCHAR2(50 BYTE), 
	"CTRASP" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."RELFONDEP"."CCODFON" IS 'Código del Fondo';
   COMMENT ON COLUMN "AXIS"."RELFONDEP"."CCODDEP" IS 'Nombre de la Depositaria';
   COMMENT ON COLUMN "AXIS"."RELFONDEP"."CTIPBAN" IS 'Tipo de cuenta';
   COMMENT ON COLUMN "AXIS"."RELFONDEP"."CBANCAR" IS 'Cuenta bancaria';
   COMMENT ON COLUMN "AXIS"."RELFONDEP"."CTRASP" IS 'Identifica Si/No la CBANCAR és la que usem pels traspassos';
   COMMENT ON TABLE "AXIS"."RELFONDEP"  IS 'Relación entre Fondos y Depositarias';
  GRANT UPDATE ON "AXIS"."RELFONDEP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RELFONDEP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."RELFONDEP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."RELFONDEP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RELFONDEP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."RELFONDEP" TO "PROGRAMADORESCSI";
