--------------------------------------------------------
--  DDL for Table REMUNERACION_CANAL_POL
--------------------------------------------------------

  CREATE TABLE "AXIS"."REMUNERACION_CANAL_POL" 
   (	"SREMCANAL" NUMBER(6,0), 
	"SSEGURO" NUMBER, 
	"CAGEPROM" NUMBER, 
	"SPROCES" NUMBER, 
	"CTIPO" NUMBER(1,0), 
	"IMPORTE" NUMBER, 
	"CTIPPER" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."REMUNERACION_CANAL_POL"."SREMCANAL" IS 'Id. de la Remuneración';
   COMMENT ON COLUMN "AXIS"."REMUNERACION_CANAL_POL"."SSEGURO" IS 'Id. del seguro';
   COMMENT ON COLUMN "AXIS"."REMUNERACION_CANAL_POL"."CAGEPROM" IS 'Código del Gestor/Vicepresidente/Gerente/Director/Promotor/Coordinador';
   COMMENT ON COLUMN "AXIS"."REMUNERACION_CANAL_POL"."SPROCES" IS 'Id. del proceso';
   COMMENT ON COLUMN "AXIS"."REMUNERACION_CANAL_POL"."CTIPO" IS 'Tipo de Póliza (1 - Nueva, 2 - Renovacion)';
   COMMENT ON COLUMN "AXIS"."REMUNERACION_CANAL_POL"."IMPORTE" IS 'Valor de la póliza';
   COMMENT ON COLUMN "AXIS"."REMUNERACION_CANAL_POL"."CTIPPER" IS 'Tipo de Persona (1-Promotor,  2-Gestor, 3-Vicepresidente, 4-Gerente, 5-Director, 6-Coordinador)';
   COMMENT ON TABLE "AXIS"."REMUNERACION_CANAL_POL"  IS 'Tabla para registrar las pólizas que participan en la remuneración del canal';
  GRANT UPDATE ON "AXIS"."REMUNERACION_CANAL_POL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REMUNERACION_CANAL_POL" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."REMUNERACION_CANAL_POL" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."REMUNERACION_CANAL_POL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REMUNERACION_CANAL_POL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."REMUNERACION_CANAL_POL" TO "PROGRAMADORESCSI";
