--------------------------------------------------------
--  DDL for Table REPOSICIONES_DET
--------------------------------------------------------

  CREATE TABLE "AXIS"."REPOSICIONES_DET" 
   (	"CCODIGO" NUMBER(5,0), 
	"NORDEN" NUMBER(3,0), 
	"ICAPACIDAD" NUMBER(14,3), 
	"PTASA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."REPOSICIONES_DET"."CCODIGO" IS 'Código de reposición';
   COMMENT ON COLUMN "AXIS"."REPOSICIONES_DET"."NORDEN" IS 'Orden (Indica el orden de los tramos)';
   COMMENT ON COLUMN "AXIS"."REPOSICIONES_DET"."ICAPACIDAD" IS 'Capacidad';
   COMMENT ON COLUMN "AXIS"."REPOSICIONES_DET"."PTASA" IS 'Tasa';
   COMMENT ON TABLE "AXIS"."REPOSICIONES_DET"  IS 'Tramos de una reposición';
  GRANT UPDATE ON "AXIS"."REPOSICIONES_DET" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REPOSICIONES_DET" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."REPOSICIONES_DET" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."REPOSICIONES_DET" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."REPOSICIONES_DET" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."REPOSICIONES_DET" TO "PROGRAMADORESCSI";
