--------------------------------------------------------
--  DDL for Table RESCATE_VENTANA
--------------------------------------------------------

  CREATE TABLE "AXIS"."RESCATE_VENTANA" 
   (	"CEMPRES" NUMBER, 
	"SPRODUC" NUMBER, 
	"FSOLICI" DATE, 
	"FVALORACION" DATE, 
	"ISFVALORACION" NUMBER, 
	"FACTIVOS" DATE, 
	"ISFACTIVO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."RESCATE_VENTANA"."CEMPRES" IS 'Empresa';
   COMMENT ON COLUMN "AXIS"."RESCATE_VENTANA"."SPRODUC" IS 'Codigo Producto';
   COMMENT ON COLUMN "AXIS"."RESCATE_VENTANA"."FSOLICI" IS 'Fecha de solicitud';
   COMMENT ON COLUMN "AXIS"."RESCATE_VENTANA"."FVALORACION" IS 'Fecha de valoracion';
   COMMENT ON COLUMN "AXIS"."RESCATE_VENTANA"."ISFVALORACION" IS 'Campo que indica si se ha realizado la valoracion de rescates. 0 o null no, 1 si se ha realizado';
   COMMENT ON COLUMN "AXIS"."RESCATE_VENTANA"."FACTIVOS" IS 'Fecha de acivos afectos (pagos)';
   COMMENT ON COLUMN "AXIS"."RESCATE_VENTANA"."ISFACTIVO" IS 'Campo que indica si se ha realizado el pago de rescates';
   COMMENT ON TABLE "AXIS"."RESCATE_VENTANA"  IS 'Rescates por ventanas de liquidez. Solo para productos indexados';
  GRANT UPDATE ON "AXIS"."RESCATE_VENTANA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RESCATE_VENTANA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."RESCATE_VENTANA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."RESCATE_VENTANA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RESCATE_VENTANA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."RESCATE_VENTANA" TO "PROGRAMADORESCSI";
