--------------------------------------------------------
--  DDL for Table RETENCIONES
--------------------------------------------------------

  CREATE TABLE "AXIS"."RETENCIONES" 
   (	"CRETENC" NUMBER(2,0), 
	"FINIVIG" DATE, 
	"PRETENC" NUMBER(5,2), 
	"FFINVIG" DATE, 
	"CTIPIND" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."RETENCIONES"."CRETENC" IS 'Código de retención';
   COMMENT ON COLUMN "AXIS"."RETENCIONES"."FINIVIG" IS 'Fecha inicio vigencia';
   COMMENT ON COLUMN "AXIS"."RETENCIONES"."PRETENC" IS 'Porcentaje de retención';
   COMMENT ON COLUMN "AXIS"."RETENCIONES"."FFINVIG" IS 'Fecha fin vigencia';
   COMMENT ON COLUMN "AXIS"."RETENCIONES"."CTIPIND" IS 'C¿digo del tipo de indicador';
  GRANT UPDATE ON "AXIS"."RETENCIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RETENCIONES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."RETENCIONES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."RETENCIONES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RETENCIONES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."RETENCIONES" TO "PROGRAMADORESCSI";
