--------------------------------------------------------
--  DDL for Table RIE_HIS_RIESGO
--------------------------------------------------------

  CREATE TABLE "AXIS"."RIE_HIS_RIESGO" 
   (	"SPERSON" NUMBER, 
	"NRIESGO" NUMBER, 
	"NMOVIMI" NUMBER, 
	"SFINANCI" NUMBER, 
	"MONTO" NUMBER, 
	"FEFECTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."RIE_HIS_RIESGO"."SPERSON" IS 'Identificador de la persona';
   COMMENT ON COLUMN "AXIS"."RIE_HIS_RIESGO"."NRIESGO" IS 'Nivel de riesgo calculado';
   COMMENT ON COLUMN "AXIS"."RIE_HIS_RIESGO"."NMOVIMI" IS 'Movimiento del calculo del riesgo';
   COMMENT ON COLUMN "AXIS"."RIE_HIS_RIESGO"."SFINANCI" IS 'Identificador ficha financiera';
   COMMENT ON COLUMN "AXIS"."RIE_HIS_RIESGO"."MONTO" IS 'Monto a financiar';
   COMMENT ON COLUMN "AXIS"."RIE_HIS_RIESGO"."FEFECTO" IS 'Fecha de efecto';
  GRANT UPDATE ON "AXIS"."RIE_HIS_RIESGO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RIE_HIS_RIESGO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."RIE_HIS_RIESGO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."RIE_HIS_RIESGO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RIE_HIS_RIESGO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."RIE_HIS_RIESGO" TO "PROGRAMADORESCSI";
