--------------------------------------------------------
--  DDL for Table RIESGOS_IR_ORDENES
--------------------------------------------------------

  CREATE TABLE "AXIS"."RIESGOS_IR_ORDENES" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"CEMPRES" NUMBER(5,0), 
	"SORDEN" NUMBER, 
	"CNUEVA" NUMBER(1,0), 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE), 
	"SINTERF1" NUMBER, 
	"SINTERF2" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."RIESGOS_IR_ORDENES"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente';
   COMMENT ON COLUMN "AXIS"."RIESGOS_IR_ORDENES"."NRIESGO" IS 'Número de riesgo';
   COMMENT ON COLUMN "AXIS"."RIESGOS_IR_ORDENES"."NMOVIMI" IS 'Número de movimiento';
   COMMENT ON COLUMN "AXIS"."RIESGOS_IR_ORDENES"."CEMPRES" IS 'Código de empresa';
   COMMENT ON COLUMN "AXIS"."RIESGOS_IR_ORDENES"."SORDEN" IS 'Número consecutivo de orden de inspección asignado automáticamente';
   COMMENT ON COLUMN "AXIS"."RIESGOS_IR_ORDENES"."CNUEVA" IS 'Indica si la orden es nueva para este seguro o no (1-0)';
   COMMENT ON COLUMN "AXIS"."RIESGOS_IR_ORDENES"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."RIESGOS_IR_ORDENES"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."RIESGOS_IR_ORDENES"."FMODIFI" IS 'Fecha de modificacion';
   COMMENT ON COLUMN "AXIS"."RIESGOS_IR_ORDENES"."CUSUMOD" IS 'Usuario de modificacion';
   COMMENT ON TABLE "AXIS"."RIESGOS_IR_ORDENES"  IS 'Tabla de datos de inspección de riesgo del riesgo';
  GRANT UPDATE ON "AXIS"."RIESGOS_IR_ORDENES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RIESGOS_IR_ORDENES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."RIESGOS_IR_ORDENES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."RIESGOS_IR_ORDENES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RIESGOS_IR_ORDENES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."RIESGOS_IR_ORDENES" TO "PROGRAMADORESCSI";
