--------------------------------------------------------
--  DDL for Table RIESGO_DEFECTO
--------------------------------------------------------

  CREATE TABLE "AXIS"."RIESGO_DEFECTO" 
   (	"CEMPRES" NUMBER(2,0), 
	"SPRODUC" NUMBER(6,0) DEFAULT 0, 
	"CACTIVI" NUMBER(4,0) DEFAULT 0, 
	"COBJASE" NUMBER(2,0), 
	"SPERSON" NUMBER(10,0), 
	"TDOMICI" VARCHAR2(60 BYTE), 
	"CPAIS" NUMBER(3,0), 
	"CPROVIN" NUMBER, 
	"CPOBLAC" NUMBER, 
	"CPOSTAL" VARCHAR2(30 BYTE), 
	"TNATRIE" VARCHAR2(300 BYTE), 
	"CVERSION" VARCHAR2(11 BYTE), 
	"CMODELO" VARCHAR2(3 BYTE), 
	"CMARCA" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."RIESGO_DEFECTO"."CEMPRES" IS 'Código de Empresa';
   COMMENT ON COLUMN "AXIS"."RIESGO_DEFECTO"."SPRODUC" IS 'Código de Producto';
   COMMENT ON COLUMN "AXIS"."RIESGO_DEFECTO"."CACTIVI" IS 'Código de Actividad';
   COMMENT ON COLUMN "AXIS"."RIESGO_DEFECTO"."COBJASE" IS 'Código de objeto asegurado';
   COMMENT ON COLUMN "AXIS"."RIESGO_DEFECTO"."SPERSON" IS 'Código de Persona';
   COMMENT ON COLUMN "AXIS"."RIESGO_DEFECTO"."TDOMICI" IS 'Domicilio';
   COMMENT ON COLUMN "AXIS"."RIESGO_DEFECTO"."CPAIS" IS 'Código de País';
   COMMENT ON COLUMN "AXIS"."RIESGO_DEFECTO"."CPROVIN" IS 'Código de Provincia';
   COMMENT ON COLUMN "AXIS"."RIESGO_DEFECTO"."CPOBLAC" IS 'Código de Población';
   COMMENT ON COLUMN "AXIS"."RIESGO_DEFECTO"."TNATRIE" IS 'Naturaleza del riesgo';
   COMMENT ON TABLE "AXIS"."RIESGO_DEFECTO"  IS 'Riesgos por defecto';
  GRANT SELECT ON "AXIS"."RIESGO_DEFECTO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."RIESGO_DEFECTO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."RIESGO_DEFECTO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RIESGO_DEFECTO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."RIESGO_DEFECTO" TO "PROGRAMADORESCSI";
  GRANT UPDATE ON "AXIS"."RIESGO_DEFECTO" TO "R_AXIS";
