--------------------------------------------------------
--  DDL for Table RTN_RECRETORNO
--------------------------------------------------------

  CREATE TABLE "AXIS"."RTN_RECRETORNO" 
   (	"NRECIBO" NUMBER, 
	"NRECRETORNO" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."RTN_RECRETORNO"."NRECIBO" IS 'Número de Recibo';
   COMMENT ON COLUMN "AXIS"."RTN_RECRETORNO"."NRECRETORNO" IS 'Número del Retorno';
   COMMENT ON TABLE "AXIS"."RTN_RECRETORNO"  IS 'Tabla que relaciona Recibos con Retornos.';
  GRANT UPDATE ON "AXIS"."RTN_RECRETORNO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RTN_RECRETORNO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."RTN_RECRETORNO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."RTN_RECRETORNO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RTN_RECRETORNO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."RTN_RECRETORNO" TO "PROGRAMADORESCSI";
