--------------------------------------------------------
--  DDL for Table RTN_MNTBENEFCONVENIO
--------------------------------------------------------

  CREATE TABLE "AXIS"."RTN_MNTBENEFCONVENIO" 
   (	"IDCONVENIO" NUMBER(6,0), 
	"SPERSON" NUMBER(10,0), 
	"PRETORNO" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."RTN_MNTBENEFCONVENIO"."IDCONVENIO" IS 'Identificador del convenio';
   COMMENT ON COLUMN "AXIS"."RTN_MNTBENEFCONVENIO"."SPERSON" IS 'Identificador de la persona beneficiaria del retorno';
   COMMENT ON COLUMN "AXIS"."RTN_MNTBENEFCONVENIO"."PRETORNO" IS 'Porcentaje de retorno del beneficiario';
   COMMENT ON TABLE "AXIS"."RTN_MNTBENEFCONVENIO"  IS 'Parametrización personas beneficiarias que participan en el convenio.';
  GRANT UPDATE ON "AXIS"."RTN_MNTBENEFCONVENIO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RTN_MNTBENEFCONVENIO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."RTN_MNTBENEFCONVENIO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."RTN_MNTBENEFCONVENIO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."RTN_MNTBENEFCONVENIO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."RTN_MNTBENEFCONVENIO" TO "PROGRAMADORESCSI";
