--------------------------------------------------------
--  DDL for Table SCORE_GENERAL
--------------------------------------------------------

  CREATE TABLE "AXIS"."SCORE_GENERAL" 
   (	"SPERSON" NUMBER(10,0), 
	"FCALCUL" DATE, 
	"NFACCLI" NUMBER, 
	"NFACJUR" NUMBER, 
	"NFACPRO" NUMBER, 
	"NFACCAL" NUMBER, 
	"NSCOTOT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SCORE_GENERAL"."SPERSON" IS 'Identificador persona';
   COMMENT ON COLUMN "AXIS"."SCORE_GENERAL"."FCALCUL" IS 'Fecha Calculo.';
   COMMENT ON COLUMN "AXIS"."SCORE_GENERAL"."NFACCLI" IS 'FACTOR CLIENTE';
   COMMENT ON COLUMN "AXIS"."SCORE_GENERAL"."NFACJUR" IS 'FACTOR JURISDICCION';
   COMMENT ON COLUMN "AXIS"."SCORE_GENERAL"."NFACPRO" IS 'Factor Producto';
   COMMENT ON COLUMN "AXIS"."SCORE_GENERAL"."NFACCAL" IS 'FACTOR CANAL';
   COMMENT ON COLUMN "AXIS"."SCORE_GENERAL"."NSCOTOT" IS 'Scoring Total';
  GRANT UPDATE ON "AXIS"."SCORE_GENERAL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SCORE_GENERAL" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SCORE_GENERAL" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SCORE_GENERAL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SCORE_GENERAL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SCORE_GENERAL" TO "PROGRAMADORESCSI";
