--------------------------------------------------------
--  DDL for Table SEG_ASECCARGO
--------------------------------------------------------

  CREATE TABLE "AXIS"."SEG_ASECCARGO" 
   (	"SSEGURO" NUMBER, 
	"SPERSON" NUMBER(10,0), 
	"NCTACOR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SEG_ASECCARGO"."SSEGURO" IS 'Clave interna del seguro';
   COMMENT ON COLUMN "AXIS"."SEG_ASECCARGO"."SPERSON" IS 'Clave interna de la persona';
   COMMENT ON COLUMN "AXIS"."SEG_ASECCARGO"."NCTACOR" IS 'Cta de Abono';
   COMMENT ON TABLE "AXIS"."SEG_ASECCARGO"  IS 'Contiene la Cta Abono por poliza/asegurado para Prestaciones';
  GRANT UPDATE ON "AXIS"."SEG_ASECCARGO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEG_ASECCARGO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SEG_ASECCARGO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SEG_ASECCARGO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEG_ASECCARGO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEG_ASECCARGO" TO "PROGRAMADORESCSI";
