--------------------------------------------------------
--  DDL for Table SEGCARTERA
--------------------------------------------------------

  CREATE TABLE "AXIS"."SEGCARTERA" 
   (	"SPROCES" NUMBER, 
	"SSEGURO" NUMBER, 
	"FCARPRO" DATE, 
	"FCARANU" DATE, 
	"FCARANT" DATE, 
	"NANUALI" NUMBER(2,0), 
	"NFRACCI" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS"  ENABLE ROW MOVEMENT ;

   COMMENT ON COLUMN "AXIS"."SEGCARTERA"."FCARPRO" IS 'Fecha de próximo recibo';
   COMMENT ON COLUMN "AXIS"."SEGCARTERA"."FCARANU" IS 'Fecha de cartera anual';
   COMMENT ON COLUMN "AXIS"."SEGCARTERA"."FCARANT" IS 'Fecha de cartera anterior';
   COMMENT ON COLUMN "AXIS"."SEGCARTERA"."NANUALI" IS 'Anualidad';
   COMMENT ON COLUMN "AXIS"."SEGCARTERA"."NFRACCI" IS 'Fracción';
  GRANT UPDATE ON "AXIS"."SEGCARTERA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEGCARTERA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SEGCARTERA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SEGCARTERA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEGCARTERA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEGCARTERA" TO "PROGRAMADORESCSI";
