--------------------------------------------------------
--  DDL for Table SEGDISIN2
--------------------------------------------------------

  CREATE TABLE "AXIS"."SEGDISIN2" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"FINICIO" DATE, 
	"FFIN" DATE, 
	"CCESTA" NUMBER(3,0), 
	"PDISTREC" NUMBER(9,6), 
	"PDISTUNI" NUMBER(9,6), 
	"PDISTEXT" NUMBER(9,6), 
	"CMODABO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SEGDISIN2"."CMODABO" IS 'Modo de abono de dividendos y bonos Detvalores(xxx) ';
  GRANT UPDATE ON "AXIS"."SEGDISIN2" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEGDISIN2" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SEGDISIN2" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SEGDISIN2" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEGDISIN2" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEGDISIN2" TO "PROGRAMADORESCSI";
