--------------------------------------------------------
--  DDL for Table SEGUROSREDCOM
--------------------------------------------------------

  CREATE TABLE "AXIS"."SEGUROSREDCOM" 
   (	"CTIPAGE" NUMBER(2,0), 
	"NNIVEL" NUMBER(3,0), 
	"CEMPRES" NUMBER(2,0), 
	"CAGENTE" NUMBER, 
	"SSEGURO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SEGUROSREDCOM"."CTIPAGE" IS 'Tipo de Agente';
   COMMENT ON COLUMN "AXIS"."SEGUROSREDCOM"."NNIVEL" IS 'Nivel que ocupa en la Red Cial.';
   COMMENT ON COLUMN "AXIS"."SEGUROSREDCOM"."CEMPRES" IS 'Código de Empresa';
   COMMENT ON COLUMN "AXIS"."SEGUROSREDCOM"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."SEGUROSREDCOM"."SSEGURO" IS 'Número consecutivo de seguro asignado automáticamente.';
  GRANT UPDATE ON "AXIS"."SEGUROSREDCOM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEGUROSREDCOM" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SEGUROSREDCOM" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SEGUROSREDCOM" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEGUROSREDCOM" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEGUROSREDCOM" TO "PROGRAMADORESCSI";
