--------------------------------------------------------
--  DDL for Table SEGUROS_FCARPRO
--------------------------------------------------------

  CREATE TABLE "AXIS"."SEGUROS_FCARPRO" 
   (	"SSEGURO" NUMBER, 
	"CMODALI" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CASEGUR" NUMBER(2,0), 
	"CAGENTE" NUMBER, 
	"CRAMO" NUMBER(8,0), 
	"NPOLIZA" NUMBER, 
	"NCERTIF" NUMBER, 
	"NSUPLEM" NUMBER(4,0), 
	"FEFECTO" DATE, 
	"CREAFAC" NUMBER(1,0), 
	"CTARMAN" NUMBER(1,0), 
	"COBJASE" NUMBER(2,0), 
	"CTIPREB" NUMBER(1,0), 
	"CACTIVI" NUMBER(4,0), 
	"CCOBBAN" NUMBER(3,0), 
	"CTIPCOA" NUMBER(1,0), 
	"CTIPREA" NUMBER(1,0), 
	"CRECMAN" NUMBER(1,0), 
	"CRECCOB" NUMBER(1,0), 
	"CTIPCOM" NUMBER(2,0), 
	"FVENCIM" DATE, 
	"FEMISIO" DATE, 
	"FANULAC" DATE, 
	"FCANCEL" DATE, 
	"CSITUAC" NUMBER(2,0), 
	"CBANCAR" VARCHAR2(50 BYTE), 
	"CTIPCOL" NUMBER(1,0), 
	"FCARANT" DATE, 
	"FCARPRO" DATE, 
	"FCARANU" DATE, 
	"CDURACI" NUMBER(1,0), 
	"NDURACI" NUMBER(5,2), 
	"NANUALI" NUMBER(2,0), 
	"IPRIANU" NUMBER, 
	"CIDIOMA" NUMBER(2,0), 
	"NFRACCI" NUMBER(2,0), 
	"CFORPAG" NUMBER(2,0), 
	"PDTOORD" NUMBER(5,2), 
	"NRENOVA" NUMBER(4,0), 
	"CRECFRA" NUMBER(1,0), 
	"TASEGUR" VARCHAR2(300 BYTE), 
	"CRETENI" NUMBER(1,0), 
	"NDURCOB" NUMBER(2,0), 
	"SCIACOA" NUMBER(6,0), 
	"PPARCOA" NUMBER(5,2), 
	"NPOLCOA" VARCHAR2(10 BYTE), 
	"NSUPCOA" VARCHAR2(6 BYTE), 
	"TNATRIE" VARCHAR2(300 BYTE), 
	"PDTOCOM" NUMBER(5,2), 
	"PREVALI" NUMBER(5,2), 
	"IREVALI" NUMBER, 
	"NCUACOA" NUMBER(2,0), 
	"NEDAMED" NUMBER(2,0), 
	"CREVALI" NUMBER(2,0), 
	"CEMPRES" NUMBER(2,0), 
	"CAGRPRO" NUMBER(2,0), 
	"NSOLICI" NUMBER(8,0), 
	"FIMPSOL" DATE, 
	"SPRODUC" NUMBER(6,0), 
	"CCOMPANI" NUMBER(3,0), 
	"INTPRES" NUMBER(9,6), 
	"NMESCOB" NUMBER(2,0), 
	"CNOTIBAJA" NUMBER(3,0), 
	"CCARTERA" NUMBER(1,0), 
	"NPARBEN" NUMBER(1,0), 
	"NBNS" NUMBER(1,0), 
	"CTRAMO" NUMBER(6,0), 
	"CINDEXT" NUMBER(1,0), 
	"PDISPRI" NUMBER(5,2), 
	"IDISPRI" NUMBER(5,2), 
	"CIMPASE" NUMBER(1,0), 
	"CAGENCORR" VARCHAR2(30 BYTE), 
	"CTIPBAN" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SEGUROS_FCARPRO"."CTIPBAN" IS 'Tipo de cuenta ( iban o cuenta bancaria). [tabla maestra: TIPOS_CUENTA]';
  GRANT UPDATE ON "AXIS"."SEGUROS_FCARPRO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEGUROS_FCARPRO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SEGUROS_FCARPRO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SEGUROS_FCARPRO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEGUROS_FCARPRO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEGUROS_FCARPRO" TO "PROGRAMADORESCSI";
