--------------------------------------------------------
--  DDL for Table SGT_SUBTABS_DES
--------------------------------------------------------

  CREATE TABLE "AXIS"."SGT_SUBTABS_DES" 
   (	"CEMPRES" NUMBER(5,0), 
	"CSUBTABLA" NUMBER(9,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TSUBTABLA" VARCHAR2(200 BYTE), 
	"TCLA1" VARCHAR2(200 BYTE), 
	"TCLA2" VARCHAR2(200 BYTE), 
	"TCLA3" VARCHAR2(200 BYTE), 
	"TCLA4" VARCHAR2(200 BYTE), 
	"TCLA5" VARCHAR2(200 BYTE), 
	"TCLA6" VARCHAR2(200 BYTE), 
	"TCLA7" VARCHAR2(200 BYTE), 
	"TCLA8" VARCHAR2(200 BYTE), 
	"TVAL1" VARCHAR2(200 BYTE), 
	"TVAL2" VARCHAR2(200 BYTE), 
	"TVAL3" VARCHAR2(200 BYTE), 
	"TVAL4" VARCHAR2(200 BYTE), 
	"TVAL5" VARCHAR2(200 BYTE), 
	"TVAL6" VARCHAR2(200 BYTE), 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE), 
	"TCLA9" VARCHAR2(200 BYTE), 
	"TCLA10" VARCHAR2(200 BYTE), 
	"TVAL7" VARCHAR2(200 BYTE), 
	"TVAL8" VARCHAR2(200 BYTE), 
	"TVAL9" VARCHAR2(200 BYTE), 
	"TVAL10" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."CEMPRES" IS 'Código de empresa';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."CSUBTABLA" IS 'Código de subtabla';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."CIDIOMA" IS 'Código de idioma';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TSUBTABLA" IS 'Descripción de la subtabla';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TCLA1" IS 'Descripción de la clave 1';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TCLA2" IS 'Descripción de la clave 2';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TCLA3" IS 'Descripción de la clave 3';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TCLA4" IS 'Descripción de la clave 4';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TCLA5" IS 'Descripción de la clave 5';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TCLA6" IS 'Descripción de la clave 6';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TCLA7" IS 'Descripción de la clave 7';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TCLA8" IS 'Descripción de la clave 8';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TVAL1" IS 'Descripción del valor 1';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TVAL2" IS 'Descripción del valor 2';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TVAL3" IS 'Descripción del valor 3';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TVAL4" IS 'Descripción del valor 4';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TVAL5" IS 'Descripción del valor 5';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TVAL6" IS 'Descripción del valor 6';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."FMODIFI" IS 'Fecha de modificación';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."CUSUMOD" IS 'Usuario de modificación';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TCLA9" IS 'Clave9';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TCLA10" IS 'Clave 10';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TVAL7" IS 'Descripció del valor 7';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TVAL8" IS 'Descripció del valor 8';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TVAL9" IS 'Descripció del valor 9';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_DES"."TVAL10" IS 'Descripció del valor 10';
   COMMENT ON TABLE "AXIS"."SGT_SUBTABS_DES"  IS 'Descripciones Subtablas SGT';
  GRANT UPDATE ON "AXIS"."SGT_SUBTABS_DES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SGT_SUBTABS_DES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SGT_SUBTABS_DES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SGT_SUBTABS_DES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SGT_SUBTABS_DES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SGT_SUBTABS_DES" TO "PROGRAMADORESCSI";
