--------------------------------------------------------
--  DDL for Table SGT_SUBTABS_VER
--------------------------------------------------------

  CREATE TABLE "AXIS"."SGT_SUBTABS_VER" 
   (	"CEMPRES" NUMBER(5,0), 
	"CSUBTABLA" NUMBER(9,0), 
	"FEFECTO" DATE, 
	"CVERSUBT" NUMBER(9,0), 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_VER"."CEMPRES" IS 'Código de empresa';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_VER"."CSUBTABLA" IS 'Código de subtabla';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_VER"."FEFECTO" IS 'Fecha inicio de efecto de la versión';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_VER"."CVERSUBT" IS 'Versión de datos de la subtabla';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_VER"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_VER"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_VER"."FMODIFI" IS 'Fecha de modificación';
   COMMENT ON COLUMN "AXIS"."SGT_SUBTABS_VER"."CUSUMOD" IS 'Usuario de modificación';
   COMMENT ON TABLE "AXIS"."SGT_SUBTABS_VER"  IS 'Versiones de datos de las Subtablas SGT';
  GRANT UPDATE ON "AXIS"."SGT_SUBTABS_VER" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SGT_SUBTABS_VER" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SGT_SUBTABS_VER" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SGT_SUBTABS_VER" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SGT_SUBTABS_VER" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SGT_SUBTABS_VER" TO "PROGRAMADORESCSI";
