--------------------------------------------------------
--  DDL for Table SIMBOLCONMU_2CAB
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIMBOLCONMU_2CAB" 
   (	"CTABLA" NUMBER(2,0), 
	"PINTTEC" NUMBER(9,6), 
	"NEDAD1" NUMBER(5,0), 
	"CSEXO1" NUMBER(2,0), 
	"NEDAD2" NUMBER(5,0), 
	"CSEXO2" NUMBER(2,0), 
	"NXY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIMBOLCONMU_2CAB"."CTABLA" IS 'Código de tabla de mortalidad';
   COMMENT ON COLUMN "AXIS"."SIMBOLCONMU_2CAB"."PINTTEC" IS '% de interés técnico';
   COMMENT ON COLUMN "AXIS"."SIMBOLCONMU_2CAB"."NEDAD1" IS 'Edad asegurado 1';
   COMMENT ON COLUMN "AXIS"."SIMBOLCONMU_2CAB"."CSEXO1" IS 'Sexo asegurado 1';
   COMMENT ON COLUMN "AXIS"."SIMBOLCONMU_2CAB"."NEDAD2" IS 'Edad asegurado 2';
   COMMENT ON COLUMN "AXIS"."SIMBOLCONMU_2CAB"."CSEXO2" IS 'Sexo asegurado 2';
   COMMENT ON COLUMN "AXIS"."SIMBOLCONMU_2CAB"."NXY" IS 'Símbolo nxy';
   COMMENT ON TABLE "AXIS"."SIMBOLCONMU_2CAB"  IS 'Tabla con los símbolos de conmutación para pproductos a 2 cabezas';
  GRANT UPDATE ON "AXIS"."SIMBOLCONMU_2CAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIMBOLCONMU_2CAB" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIMBOLCONMU_2CAB" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIMBOLCONMU_2CAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIMBOLCONMU_2CAB" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIMBOLCONMU_2CAB" TO "PROGRAMADORESCSI";
