--------------------------------------------------------
--  DDL for Table SIMBOLCONMU
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIMBOLCONMU" 
   (	"CTABLA" NUMBER(2,0), 
	"PINTTEC" NUMBER(9,6), 
	"NEDAD" NUMBER(5,0), 
	"QX" NUMBER, 
	"LX" NUMBER, 
	"LXA" NUMBER, 
	"DX" NUMBER, 
	"DXA" NUMBER, 
	"NX" NUMBER, 
	"NXA" NUMBER, 
	"SX" NUMBER, 
	"MX" NUMBER, 
	"RX" NUMBER, 
	"CX" NUMBER, 
	"CXA" NUMBER, 
	"IX" NUMBER, 
	"TPXA" NUMBER, 
	"QY" NUMBER, 
	"LY" NUMBER, 
	"LYA" NUMBER, 
	"DY" NUMBER, 
	"DYA" NUMBER, 
	"NY" NUMBER, 
	"NYA" NUMBER, 
	"SY" NUMBER, 
	"MY" NUMBER, 
	"RY" NUMBER, 
	"CY" NUMBER, 
	"CYA" NUMBER, 
	"IY" NUMBER, 
	"TPYA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."SIMBOLCONMU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIMBOLCONMU" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIMBOLCONMU" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIMBOLCONMU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIMBOLCONMU" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIMBOLCONMU" TO "PROGRAMADORESCSI";
