--------------------------------------------------------
--  DDL for Table SIMULAPP
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIMULAPP" 
   (	"SESION" NUMBER, 
	"NOMBRE1" VARCHAR2(100 BYTE), 
	"NOMBRE2" VARCHAR2(100 BYTE), 
	"FNACIMI1" DATE, 
	"FNACIMI2" DATE, 
	"SEXO1" NUMBER, 
	"SEXO2" NUMBER, 
	"FJUBILA" DATE, 
	"EDADJUBILA" NUMBER, 
	"PINTERCAP" NUMBER(5,2), 
	"PINTERREN" NUMBER(5,2), 
	"PREVAL" NUMBER(5,2), 
	"DURANOS" NUMBER, 
	"DURMESES" NUMBER, 
	"PERIODICA" NUMBER, 
	"EXTRA" NUMBER, 
	"CAPESTIMA" NUMBER, 
	"APORREA" NUMBER, 
	"RENTAVIT" NUMBER, 
	"PREVER" NUMBER(5,2), 
	"RENTAREV" NUMBER(5,2), 
	"PERCIERTO" NUMBER(2,0), 
	"SSEGURO" NUMBER, 
	"DERECHOS" NUMBER, 
	"FVALORA" DATE, 
	"FCONTIN" DATE, 
	"NCONTIN" NUMBER(1,0), 
	"FINICIOFIS" DATE, 
	"PRETEN" NUMBER, 
	"IRETEN" NUMBER, 
	"MESES" NUMBER, 
	"IREDUC" NUMBER, 
	"IBASE" NUMBER, 
	"IRETENCAP" NUMBER, 
	"PRETENCAP" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIMULAPP"."SESION" IS 'Número de sesión';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."NOMBRE1" IS 'Nombre del primer titular';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."NOMBRE2" IS 'Nombre del segundo titular';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."FNACIMI1" IS 'F.Nacimiento primer titular';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."FNACIMI2" IS 'F.Nacimiento segundo titular';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."SEXO1" IS 'Sexo primer titular';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."SEXO2" IS 'Sexo sgundo titular';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."FJUBILA" IS 'Fecha de jubilación primer titular';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."EDADJUBILA" IS 'Edad jubilación primer titular';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."PINTERCAP" IS '% Interes capital';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."PINTERREN" IS '% interes renta';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."PREVAL" IS '% revalorización';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."DURANOS" IS 'Duración años';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."DURMESES" IS 'duración meses';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."PERIODICA" IS 'Importe aportación periódica';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."EXTRA" IS 'Importe aportacion extra';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."CAPESTIMA" IS 'Capitl estimado';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."APORREA" IS 'Aportaciones reales';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."RENTAVIT" IS 'Importe renta vitalicia';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."PREVER" IS 'Reversión';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."RENTAREV" IS '% Renta';
   COMMENT ON COLUMN "AXIS"."SIMULAPP"."PERCIERTO" IS 'Periodo cierto';
   COMMENT ON TABLE "AXIS"."SIMULAPP"  IS 'Datos de la simulación de planes de pensiones';
  GRANT UPDATE ON "AXIS"."SIMULAPP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIMULAPP" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIMULAPP" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIMULAPP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIMULAPP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIMULAPP" TO "PROGRAMADORESCSI";
