--------------------------------------------------------
--  DDL for Table SIN_TRAMITA_PRERESERVA
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_TRAMITA_PRERESERVA" 
   (	"NSINIES" VARCHAR2(14 BYTE), 
	"NTRAMIT" NUMBER(4,0), 
	"FRESERVA" DATE, 
	"PRETENC" NUMBER(5,2), 
	"IPENALI" NUMBER, 
	"CTIPCAL" NUMBER(1,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PRERESERVA"."NSINIES" IS 'Identificador del siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PRERESERVA"."NTRAMIT" IS 'Número de la tramitación';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PRERESERVA"."FRESERVA" IS 'Fecha que se debe utilizar en los cálculos';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PRERESERVA"."PRETENC" IS 'Porcentaje de retención a aplicar';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PRERESERVA"."IPENALI" IS 'Importe a aplicar como penalización';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PRERESERVA"."CTIPCAL" IS 'Tipo de cálculo de la reserva. Detvalores(8000943)';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PRERESERVA"."CUSUALT" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PRERESERVA"."FALTA" IS 'Fecha de modificación';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PRERESERVA"."CUSUMOD" IS 'Usuario de modificación';
   COMMENT ON TABLE "AXIS"."SIN_TRAMITA_PRERESERVA"  IS 'Tramitación de rereservas de siniestros';
  GRANT UPDATE ON "AXIS"."SIN_TRAMITA_PRERESERVA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_PRERESERVA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_TRAMITA_PRERESERVA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_TRAMITA_PRERESERVA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_PRERESERVA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_PRERESERVA" TO "PROGRAMADORESCSI";
