--------------------------------------------------------
--  DDL for Table SIN_PROF_INDICADORES
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_PROF_INDICADORES" 
   (	"SPROFES" NUMBER, 
	"CTIPIND" NUMBER, 
	"FALTA" DATE, 
	"CUSUALTA" VARCHAR2(20 BYTE), 
	"CUSUMOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_PROF_INDICADORES"."SPROFES" IS 'Código profesional (SIN_PROF_PROFESIONALES)';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_INDICADORES"."CTIPIND" IS 'Indicador (TIPOS_INDICADORES)';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_INDICADORES"."FALTA" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_INDICADORES"."CUSUALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_INDICADORES"."CUSUMOD" IS 'Usuario de modificacion';
   COMMENT ON TABLE "AXIS"."SIN_PROF_INDICADORES"  IS 'Indicadores SAP para calculo de impuestos';
  GRANT UPDATE ON "AXIS"."SIN_PROF_INDICADORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PROF_INDICADORES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_PROF_INDICADORES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_PROF_INDICADORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PROF_INDICADORES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_PROF_INDICADORES" TO "PROGRAMADORESCSI";
