--------------------------------------------------------
--  DDL for Table SIN_PROF_DOC_LOPD
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_PROF_DOC_LOPD" 
   (	"SPROFES" NUMBER(8,0), 
	"NORDDOC" NUMBER, 
	"IDDOCGX" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_PROF_DOC_LOPD"."SPROFES" IS 'Sequencial. Codigo de profesional';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_DOC_LOPD"."NORDDOC" IS 'Secuencial unico';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_DOC_LOPD"."IDDOCGX" IS 'Clave GEDOX';
   COMMENT ON TABLE "AXIS"."SIN_PROF_DOC_LOPD"  IS 'Documentación asociada';
  GRANT UPDATE ON "AXIS"."SIN_PROF_DOC_LOPD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PROF_DOC_LOPD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_PROF_DOC_LOPD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_PROF_DOC_LOPD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PROF_DOC_LOPD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_PROF_DOC_LOPD" TO "PROGRAMADORESCSI";
