--------------------------------------------------------
--  DDL for Table SIN_TRAMITA_DETDIRECCION
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_TRAMITA_DETDIRECCION" 
   (	"NSINIES" VARCHAR2(14 BYTE), 
	"NTRAMIT" NUMBER(4,0), 
	"SPERSON" NUMBER(10,0), 
	"CSIGLAS" NUMBER(2,0), 
	"TNOMVIA" VARCHAR2(200 BYTE), 
	"NNUMVIA" NUMBER(5,0), 
	"TCOMPLE" VARCHAR2(100 BYTE), 
	"TDIREC" VARCHAR2(100 BYTE), 
	"CPAIS" NUMBER(3,0), 
	"CPROVIN" NUMBER, 
	"CPOBLAC" NUMBER, 
	"CPOSTAL" VARCHAR2(30 BYTE), 
	"TTRAMITA" VARCHAR2(500 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"CCIUDAD" NUMBER(5,0), 
	"FGISX" FLOAT(126), 
	"FGISY" FLOAT(126), 
	"FGISZ" FLOAT(126), 
	"CVALIDA" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."NSINIES" IS 'Número Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."NTRAMIT" IS 'Número Tramitación Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."SPERSON" IS 'Secuencia Persona Propietario';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."CSIGLAS" IS 'Código Tipo Vía';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."TNOMVIA" IS 'Nombre Vía';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."NNUMVIA" IS 'Número Vía';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."TCOMPLE" IS 'Datos Complementarios';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."TDIREC" IS 'Dirección no normalizada';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."CPAIS" IS 'Código País';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."CPROVIN" IS 'Código Provincia';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."CPOBLAC" IS 'Código Población';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."CPOSTAL" IS 'Código Postal';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."TTRAMITA" IS 'Descripción Tramitación';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."CUSUALT" IS 'Código Usuario Alta';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."FALTA" IS 'Fecha Alta';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."CUSUMOD" IS 'Código Usuario Modificación';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."FMODIFI" IS 'Fecha Modificación';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."CCIUDAD" IS 'Código ciudad para chile';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."FGISX" IS 'Coordenada GIS X (GPS)';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."FGISY" IS 'Coordenada GIS Y (GPS)';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."FGISZ" IS 'Coordenada GIS Z (GPS)';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETDIRECCION"."CVALIDA" IS 'Código validación dirección. Valor fijo 1006';
   COMMENT ON TABLE "AXIS"."SIN_TRAMITA_DETDIRECCION"  IS 'Detalle Tramitacion Dirección';
  GRANT UPDATE ON "AXIS"."SIN_TRAMITA_DETDIRECCION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_DETDIRECCION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_TRAMITA_DETDIRECCION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_TRAMITA_DETDIRECCION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_DETDIRECCION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_DETDIRECCION" TO "PROGRAMADORESCSI";
