--------------------------------------------------------
--  DDL for Table SIN_CONPAG_PROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_CONPAG_PROD" 
   (	"CCONPAG" NUMBER, 
	"SPRODUC" NUMBER, 
	"CUSUALT" VARCHAR2(30 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(30 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_CONPAG_PROD"."CCONPAG" IS 'Concepto de pago. VF 803 ';
   COMMENT ON COLUMN "AXIS"."SIN_CONPAG_PROD"."SPRODUC" IS 'Clave de productos';
   COMMENT ON COLUMN "AXIS"."SIN_CONPAG_PROD"."CUSUALT" IS 'Usuario que crea el registro';
   COMMENT ON COLUMN "AXIS"."SIN_CONPAG_PROD"."FALTA" IS 'Fecha en que se crea el registro';
   COMMENT ON COLUMN "AXIS"."SIN_CONPAG_PROD"."CUSUMOD" IS 'Usuario que modifica crea el registro';
   COMMENT ON COLUMN "AXIS"."SIN_CONPAG_PROD"."FMODIFI" IS 'Fecha en que se modifica el registro';
   COMMENT ON TABLE "AXIS"."SIN_CONPAG_PROD"  IS 'Conceptos de pago permitidos por producto';
  GRANT UPDATE ON "AXIS"."SIN_CONPAG_PROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_CONPAG_PROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_CONPAG_PROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_CONPAG_PROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_CONPAG_PROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_CONPAG_PROD" TO "PROGRAMADORESCSI";
