--------------------------------------------------------
--  DDL for Table SIN_RES_CONCEPTO
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_RES_CONCEPTO" 
   (	"CCONCEP" NUMBER, 
	"CTIPRES" NUMBER, 
	"CTIPGAS" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_RES_CONCEPTO"."CCONCEP" IS 'Agrupacion fiscal. VF 1096';
   COMMENT ON COLUMN "AXIS"."SIN_RES_CONCEPTO"."CTIPRES" IS 'Tipo de reserva. VF 322';
   COMMENT ON COLUMN "AXIS"."SIN_RES_CONCEPTO"."CTIPGAS" IS 'Tipo de gasto (solo para reserva de gastos) VF ';
   COMMENT ON TABLE "AXIS"."SIN_RES_CONCEPTO"  IS 'Relaciona los conceptos de Area Fiscal con un tipo de Reserva';
  GRANT UPDATE ON "AXIS"."SIN_RES_CONCEPTO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_RES_CONCEPTO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_RES_CONCEPTO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_RES_CONCEPTO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_RES_CONCEPTO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_RES_CONCEPTO" TO "PROGRAMADORESCSI";
