--------------------------------------------------------
--  DDL for Table SIN_PLANTILLAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_PLANTILLAS" 
   (	"CCODPLAN" VARCHAR2(20 BYTE), 
	"CCAMPO" VARCHAR2(20 BYTE), 
	"TDESCRIP" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_PLANTILLAS"."CCODPLAN" IS 'Código de plantilla';
   COMMENT ON COLUMN "AXIS"."SIN_PLANTILLAS"."CCAMPO" IS 'Nombre del campo';
   COMMENT ON COLUMN "AXIS"."SIN_PLANTILLAS"."TDESCRIP" IS 'Descripción del contenido del campo';
  GRANT UPDATE ON "AXIS"."SIN_PLANTILLAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PLANTILLAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_PLANTILLAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_PLANTILLAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PLANTILLAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_PLANTILLAS" TO "PROGRAMADORESCSI";
