--------------------------------------------------------
--  DDL for Table SIN_TARIFAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_TARIFAS" 
   (	"STARIFA" NUMBER, 
	"TDESCRI" VARCHAR2(200 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_TARIFAS"."STARIFA" IS 'Secuencial unico';
   COMMENT ON COLUMN "AXIS"."SIN_TARIFAS"."TDESCRI" IS 'Descripcion';
   COMMENT ON TABLE "AXIS"."SIN_TARIFAS"  IS 'Tarifas profesionales';
  GRANT UPDATE ON "AXIS"."SIN_TARIFAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TARIFAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_TARIFAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_TARIFAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TARIFAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_TARIFAS" TO "PROGRAMADORESCSI";
