--------------------------------------------------------
--  DDL for Table SIN_PROD_TRAMITE
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_PROD_TRAMITE" 
   (	"CTRAMTE" NUMBER, 
	"SPRODUC" NUMBER(6,0), 
	"CACTIVI" NUMBER(4,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"CTRAMIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_PROD_TRAMITE"."CTRAMTE" IS 'Código Trámite';
   COMMENT ON COLUMN "AXIS"."SIN_PROD_TRAMITE"."SPRODUC" IS 'Código Producto';
   COMMENT ON COLUMN "AXIS"."SIN_PROD_TRAMITE"."CACTIVI" IS 'Código Actividad';
   COMMENT ON COLUMN "AXIS"."SIN_PROD_TRAMITE"."CUSUALT" IS 'Código Usuario Alta';
   COMMENT ON COLUMN "AXIS"."SIN_PROD_TRAMITE"."FALTA" IS 'Fecha Alta';
   COMMENT ON COLUMN "AXIS"."SIN_PROD_TRAMITE"."CUSUMOD" IS 'Código Usuario Modificación';
   COMMENT ON COLUMN "AXIS"."SIN_PROD_TRAMITE"."FMODIFI" IS 'Fecha Modificación';
   COMMENT ON COLUMN "AXIS"."SIN_PROD_TRAMITE"."CTRAMIT" IS 'Crear automaticamente una tramitacion de este tipo en alta de tramite';
   COMMENT ON TABLE "AXIS"."SIN_PROD_TRAMITE"  IS 'Trámites por producto';
  GRANT UPDATE ON "AXIS"."SIN_PROD_TRAMITE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PROD_TRAMITE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_PROD_TRAMITE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_PROD_TRAMITE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PROD_TRAMITE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_PROD_TRAMITE" TO "PROGRAMADORESCSI";
