--------------------------------------------------------
--  DDL for Table SIN_GAR_PERMITIDAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_GAR_PERMITIDAS" 
   (	"SPRODUC" NUMBER, 
	"CACTIVI" NUMBER, 
	"CTRAMIT" NUMBER, 
	"CGARANT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_GAR_PERMITIDAS"."SPRODUC" IS 'Clave de producto';
   COMMENT ON COLUMN "AXIS"."SIN_GAR_PERMITIDAS"."CACTIVI" IS 'Actividad';
   COMMENT ON COLUMN "AXIS"."SIN_GAR_PERMITIDAS"."CTRAMIT" IS 'Tipo de tramitacion';
   COMMENT ON COLUMN "AXIS"."SIN_GAR_PERMITIDAS"."CGARANT" IS 'Garantia permitida';
   COMMENT ON TABLE "AXIS"."SIN_GAR_PERMITIDAS"  IS 'Garantias permitidas en alta de reservas para un tipo de tramitacion';
  GRANT UPDATE ON "AXIS"."SIN_GAR_PERMITIDAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_GAR_PERMITIDAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_GAR_PERMITIDAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_GAR_PERMITIDAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_GAR_PERMITIDAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_GAR_PERMITIDAS" TO "PROGRAMADORESCSI";
