--------------------------------------------------------
--  DDL for Table SIN_PARGES_TIP_GESTION
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_PARGES_TIP_GESTION" 
   (	"CTIPREG" NUMBER(8,0), 
	"CTIPGES" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_PARGES_TIP_GESTION"."CTIPREG" IS 'Tipo Registro Gestion. VF 721';
   COMMENT ON COLUMN "AXIS"."SIN_PARGES_TIP_GESTION"."CTIPGES" IS 'Tipo Gestion. VF 722';
   COMMENT ON TABLE "AXIS"."SIN_PARGES_TIP_GESTION"  IS 'Tipificacion Gestiones (Gasto sanitario, peritajes, autos, etc)';
  GRANT UPDATE ON "AXIS"."SIN_PARGES_TIP_GESTION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PARGES_TIP_GESTION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_PARGES_TIP_GESTION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_PARGES_TIP_GESTION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PARGES_TIP_GESTION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_PARGES_TIP_GESTION" TO "PROGRAMADORESCSI";
