--------------------------------------------------------
--  DDL for Table SIN_TRAMITA_PROFESIONAL
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_TRAMITA_PROFESIONAL" 
   (	"NSINIES" VARCHAR2(14 BYTE), 
	"NTRAMIT" NUMBER(4,0), 
	"NLOCALI" NUMBER(3,0), 
	"SPERSON" NUMBER(10,0), 
	"CACTPRO" NUMBER(4,0), 
	"FINIVIG" DATE, 
	"FFINVIG" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PROFESIONAL"."NSINIES" IS 'Número Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PROFESIONAL"."NTRAMIT" IS 'Número Tramitación Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PROFESIONAL"."NLOCALI" IS 'Número Localización Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PROFESIONAL"."SPERSON" IS 'Secuencia Persona';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PROFESIONAL"."CACTPRO" IS 'Código Actividad Profesional';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PROFESIONAL"."FINIVIG" IS 'Fecha Inicio Vigencia';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PROFESIONAL"."FFINVIG" IS 'Fecha Fin Vigencia';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PROFESIONAL"."CUSUALT" IS 'Código Usuario Alta';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PROFESIONAL"."FALTA" IS 'Fecha Alta';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PROFESIONAL"."CUSUMOD" IS 'Código Usuario Modificación';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PROFESIONAL"."FMODIFI" IS 'Fecha Modificación';
   COMMENT ON TABLE "AXIS"."SIN_TRAMITA_PROFESIONAL"  IS 'Profesionales por Tramitación Siniestro';
  GRANT UPDATE ON "AXIS"."SIN_TRAMITA_PROFESIONAL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_PROFESIONAL" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_TRAMITA_PROFESIONAL" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_TRAMITA_PROFESIONAL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_PROFESIONAL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_PROFESIONAL" TO "PROGRAMADORESCSI";
