--------------------------------------------------------
--  DDL for Table SIN_TRAMITA_PAGO_CONTRATO
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_TRAMITA_PAGO_CONTRATO" 
   (	"SIDEPAG" NUMBER, 
	"CDP" VARCHAR2(10 BYTE), 
	"POSPRES" VARCHAR2(14 BYTE), 
	"CRP" VARCHAR2(10 BYTE), 
	"POSCRP" VARCHAR2(3 BYTE), 
	"CONTRATO" VARCHAR2(8 BYTE), 
	"CGESTOR" VARCHAR2(16 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PAGO_CONTRATO"."SIDEPAG" IS 'Identificador del pago';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PAGO_CONTRATO"."CDP" IS 'Nº de CDP asociado a la posición del CRP';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PAGO_CONTRATO"."POSPRES" IS 'Posición presupuestaria';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PAGO_CONTRATO"."CRP" IS 'Número del CRP a consumir';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PAGO_CONTRATO"."POSCRP" IS 'Posición del CRP a consumir';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PAGO_CONTRATO"."CONTRATO" IS 'Contrato asociado al CRP';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_PAGO_CONTRATO"."CGESTOR" IS 'Centro Gestor';
   COMMENT ON TABLE "AXIS"."SIN_TRAMITA_PAGO_CONTRATO"  IS 'Información del contrato que se envía en pagos';
  GRANT UPDATE ON "AXIS"."SIN_TRAMITA_PAGO_CONTRATO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_PAGO_CONTRATO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_TRAMITA_PAGO_CONTRATO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_TRAMITA_PAGO_CONTRATO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_PAGO_CONTRATO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_PAGO_CONTRATO" TO "PROGRAMADORESCSI";
