--------------------------------------------------------
--  DDL for Table SIN_TRAMITA_RESERVADET
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_TRAMITA_RESERVADET" 
   (	"NSINIES" VARCHAR2(14 BYTE), 
	"IDRES" NUMBER, 
	"NMOVRES" NUMBER(4,0), 
	"NMOVRESDET" NUMBER, 
	"CMONRES" VARCHAR2(3 BYTE), 
	"CREEXPRESION" NUMBER, 
	"CTRASPASO" NUMBER, 
	"ISALRES" NUMBER, 
	"ISALRESAANT" NUMBER, 
	"ISALRESAACT" NUMBER, 
	"ICONSTRES" NUMBER, 
	"IAUMENRES" NUMBER, 
	"ILIBERARES" NUMBER, 
	"IDISMIRES" NUMBER, 
	"FCAMBIO" DATE, 
	"ISALRES_MONCIA" NUMBER, 
	"ISALRESAANT_MONCIA" NUMBER, 
	"ISALRESAACT_MONCIA" NUMBER, 
	"ICONSTRES_MONCIA" NUMBER, 
	"IAUMENRES_MONCIA" NUMBER, 
	"ILIBERARES_MONCIA" NUMBER, 
	"IDISMIRES_MONCIA" NUMBER, 
	"CUSUALTA" VARCHAR2(32 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(32 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."NSINIES" IS 'N¿mero Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."IDRES" IS 'Identificador de reserva dentro de un siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."NMOVRES" IS 'N¿mero movimiento reserva';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."NMOVRESDET" IS 'N¿mero movimiento reserva detalle';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."CMONRES" IS 'C¿digo Moneda Reserva';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."CREEXPRESION" IS 'Indica si es re-expresi¿n o no';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."CTRASPASO" IS 'Indica si el movimiento es un traspaso de saldo en el cierre anual';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."ISALRES" IS 'Saldo de la reserva';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."ISALRESAANT" IS 'Saldo de la reserva del a¿o anterior';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."ISALRESAACT" IS 'Saldo de la reserva del a¿o actual';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."ICONSTRES" IS 'Importe de la constituci¿n de la reserva';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."IAUMENRES" IS 'Importe del aumento de la reserva';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."ILIBERARES" IS 'Importe liberaci¿n de la reserva (disminuci¿n de la reserva del a¿o anterior)';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."IDISMIRES" IS 'Importe disminuci¿n de la reserva del a¿o actual';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."FCAMBIO" IS 'Fecha empleada para el c¿lculo de los contravalores';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."ISALRES_MONCIA" IS 'Saldo de la reserva (Moneda de la compa¿¿a)';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."ISALRESAANT_MONCIA" IS 'Saldo de la reserva del a¿o anterior (Moneda de la compa¿¿a)';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."ISALRESAACT_MONCIA" IS 'Saldo de la reserva del a¿o actual (Moneda de la compa¿¿a)';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."ICONSTRES_MONCIA" IS 'Importe de la constituci¿n de la reserva (Moneda de la compa¿¿a)';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."IAUMENRES_MONCIA" IS 'Importe del aumento de la reserva (Moneda de la compa¿¿a)';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."ILIBERARES_MONCIA" IS 'Importe liberaci¿n de la reserva (disminuci¿n de la reserva del a¿o anterior) (Moneda de la compa¿¿a)';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."IDISMIRES_MONCIA" IS 'Importe disminuci¿n de la reserva del a¿o actual (Moneda de la compa¿¿a)';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."CUSUALTA" IS 'Usuario de alta';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."CUSUMOD" IS 'Usuario de modificaci¿n';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_RESERVADET"."FMODIFI" IS 'Fecha modificaci¿n';
  GRANT UPDATE ON "AXIS"."SIN_TRAMITA_RESERVADET" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_RESERVADET" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_TRAMITA_RESERVADET" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_TRAMITA_RESERVADET" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_RESERVADET" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_RESERVADET" TO "PROGRAMADORESCSI";
