--------------------------------------------------------
--  DDL for Table SIN_PROF_CONV_ESTADOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_PROF_CONV_ESTADOS" 
   (	"SCONVEN" NUMBER, 
	"CESTADO" NUMBER, 
	"FESTADO" DATE, 
	"CMOTBAJ" NUMBER, 
	"TOBSERV" VARCHAR2(100 BYTE), 
	"CANULAD" NUMBER, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUBAJ" VARCHAR2(20 BYTE), 
	"FBAJA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_PROF_CONV_ESTADOS"."SCONVEN" IS 'Codigo de convenio';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_CONV_ESTADOS"."CESTADO" IS 'Código estado (valor fijo 742)';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_CONV_ESTADOS"."FESTADO" IS 'Fecha inicio estado';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_CONV_ESTADOS"."TOBSERV" IS 'Observaciones';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_CONV_ESTADOS"."CANULAD" IS 'Anulado 0-No 1-Si';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_CONV_ESTADOS"."CUSUALT" IS 'Usuario que da de altaFecha de alta';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_CONV_ESTADOS"."FALTA" IS 'Fecha de alta';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_CONV_ESTADOS"."CUSUBAJ" IS 'Usuario que elimina';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_CONV_ESTADOS"."FBAJA" IS 'Fecha de baja';
   COMMENT ON TABLE "AXIS"."SIN_PROF_CONV_ESTADOS"  IS 'Estado del convenio del profesional';
  GRANT UPDATE ON "AXIS"."SIN_PROF_CONV_ESTADOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PROF_CONV_ESTADOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_PROF_CONV_ESTADOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_PROF_CONV_ESTADOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PROF_CONV_ESTADOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_PROF_CONV_ESTADOS" TO "PROGRAMADORESCSI";
