--------------------------------------------------------
--  DDL for Table SIN_DESEVENTO
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_DESEVENTO" 
   (	"CEVENTO" VARCHAR2(20 BYTE), 
	"CIDIOMA" NUMBER(2,0), 
	"TTITEVE" VARCHAR2(60 BYTE), 
	"TEVENTO" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_DESEVENTO"."CEVENTO" IS 'Código Tramitación';
   COMMENT ON COLUMN "AXIS"."SIN_DESEVENTO"."CIDIOMA" IS 'Código Idioma';
   COMMENT ON COLUMN "AXIS"."SIN_DESEVENTO"."TTITEVE" IS 'Título Evento';
   COMMENT ON COLUMN "AXIS"."SIN_DESEVENTO"."TEVENTO" IS 'Descripción Evento';
   COMMENT ON TABLE "AXIS"."SIN_DESEVENTO"  IS 'Descripciones Eventos Siniestros';
  GRANT UPDATE ON "AXIS"."SIN_DESEVENTO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_DESEVENTO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_DESEVENTO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_DESEVENTO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_DESEVENTO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_DESEVENTO" TO "PROGRAMADORESCSI";
