--------------------------------------------------------
--  DDL for Table SIN_TRAMITA_DETGESTION
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_TRAMITA_DETGESTION" 
   (	"SGESTIO" NUMBER(10,0), 
	"NDETGES" NUMBER(2,0), 
	"SSERVIC" NUMBER(10,0), 
	"NCANTID" NUMBER(3,0), 
	"CUNIMED" NUMBER(8,0), 
	"NVALSER" NUMBER, 
	"ITOTAL" NUMBER, 
	"CCODMON" VARCHAR2(3 BYTE), 
	"FCAMBIO" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CNOCARG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETGESTION"."SGESTIO" IS 'Clave de la tabla SIN_TRAMITA_GESTION';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETGESTION"."NDETGES" IS 'Numero de linea';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETGESTION"."SSERVIC" IS 'Codigo de servicio';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETGESTION"."NCANTID" IS 'Cantidad';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETGESTION"."CUNIMED" IS 'Unidad de medida. VF 734';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETGESTION"."NVALSER" IS 'Valor unitario';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETGESTION"."ITOTAL" IS 'Importe total';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETGESTION"."CCODMON" IS 'Codigo moneda';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETGESTION"."FCAMBIO" IS 'Fecha de cambio';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETGESTION"."CNOCARG" IS '0 = Sin cargo; 1 = Precio normal';
   COMMENT ON TABLE "AXIS"."SIN_TRAMITA_DETGESTION"  IS 'Detalle de servicios de una gestion';
  GRANT UPDATE ON "AXIS"."SIN_TRAMITA_DETGESTION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_DETGESTION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_TRAMITA_DETGESTION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_TRAMITA_DETGESTION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_DETGESTION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_DETGESTION" TO "PROGRAMADORESCSI";
