--------------------------------------------------------
--  DDL for Table SIN_PARGES_TRAMITACION
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_PARGES_TRAMITACION" 
   (	"CTIPTRA" NUMBER(4,0), 
	"CTIPREG" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_PARGES_TRAMITACION"."CTIPTRA" IS 'Tipo de tramitacion';
   COMMENT ON COLUMN "AXIS"."SIN_PARGES_TRAMITACION"."CTIPREG" IS 'Tipo de registro de gestion. VF 721';
   COMMENT ON TABLE "AXIS"."SIN_PARGES_TRAMITACION"  IS 'Tipos de registro permitidos segun tipo de tramitacion';
  GRANT UPDATE ON "AXIS"."SIN_PARGES_TRAMITACION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PARGES_TRAMITACION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_PARGES_TRAMITACION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_PARGES_TRAMITACION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PARGES_TRAMITACION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_PARGES_TRAMITACION" TO "PROGRAMADORESCSI";
