--------------------------------------------------------
--  DDL for Table SIN_DET_CAUSA_MOTIVO
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_DET_CAUSA_MOTIVO" 
   (	"SCAUMOT" NUMBER(8,0), 
	"CTIPDES" NUMBER(2,0), 
	"CMODFIS" NUMBER(3,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"CPAGAUT" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_DET_CAUSA_MOTIVO"."SCAUMOT" IS 'Secuencia Causa/Motivo';
   COMMENT ON COLUMN "AXIS"."SIN_DET_CAUSA_MOTIVO"."CTIPDES" IS 'Código Tipo Destinatario';
   COMMENT ON COLUMN "AXIS"."SIN_DET_CAUSA_MOTIVO"."CMODFIS" IS 'Código Modelo Fiscal Hacienda V.F. 320';
   COMMENT ON COLUMN "AXIS"."SIN_DET_CAUSA_MOTIVO"."CUSUALT" IS 'Código Usuario Alta';
   COMMENT ON COLUMN "AXIS"."SIN_DET_CAUSA_MOTIVO"."FALTA" IS 'Fecha Alta';
   COMMENT ON COLUMN "AXIS"."SIN_DET_CAUSA_MOTIVO"."CUSUMOD" IS 'Código Usuario Modificación';
   COMMENT ON COLUMN "AXIS"."SIN_DET_CAUSA_MOTIVO"."FMODIFI" IS 'Fecha Modificación';
   COMMENT ON COLUMN "AXIS"."SIN_DET_CAUSA_MOTIVO"."CPAGAUT" IS 'Pagos automáticos 1=Sí, 0 ó NULL = No';
   COMMENT ON TABLE "AXIS"."SIN_DET_CAUSA_MOTIVO"  IS 'Detalle Causas y Motivos de siniestros por producto, actividad y garantía';
  GRANT UPDATE ON "AXIS"."SIN_DET_CAUSA_MOTIVO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_DET_CAUSA_MOTIVO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_DET_CAUSA_MOTIVO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_DET_CAUSA_MOTIVO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_DET_CAUSA_MOTIVO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_DET_CAUSA_MOTIVO" TO "PROGRAMADORESCSI";
