--------------------------------------------------------
--  DDL for Table SIN_SINIESTRO_REFERENCIAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_SINIESTRO_REFERENCIAS" 
   (	"SREFEXT" NUMBER(6,0), 
	"NSINIES" VARCHAR2(14 BYTE), 
	"CTIPREF" NUMBER(2,0), 
	"TREFEXT" VARCHAR2(50 BYTE), 
	"FREFINI" DATE, 
	"FREFFIN" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_SINIESTRO_REFERENCIAS"."SREFEXT" IS 'Secuencia Referencias Externas';
   COMMENT ON COLUMN "AXIS"."SIN_SINIESTRO_REFERENCIAS"."NSINIES" IS 'Número Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_SINIESTRO_REFERENCIAS"."CTIPREF" IS 'Código Tipo de Referencia VF 800022';
   COMMENT ON COLUMN "AXIS"."SIN_SINIESTRO_REFERENCIAS"."TREFEXT" IS 'Referencia Externa';
   COMMENT ON COLUMN "AXIS"."SIN_SINIESTRO_REFERENCIAS"."FREFINI" IS 'Fecha inicio referencia';
   COMMENT ON COLUMN "AXIS"."SIN_SINIESTRO_REFERENCIAS"."FREFFIN" IS 'Fecha fin referencia';
   COMMENT ON COLUMN "AXIS"."SIN_SINIESTRO_REFERENCIAS"."CUSUALT" IS 'Usuario Alta';
   COMMENT ON COLUMN "AXIS"."SIN_SINIESTRO_REFERENCIAS"."FALTA" IS 'Fecha Alta';
   COMMENT ON COLUMN "AXIS"."SIN_SINIESTRO_REFERENCIAS"."CUSUMOD" IS 'Usuario Modificación';
   COMMENT ON COLUMN "AXIS"."SIN_SINIESTRO_REFERENCIAS"."FMODIFI" IS 'Fecha Modificación';
   COMMENT ON TABLE "AXIS"."SIN_SINIESTRO_REFERENCIAS"  IS 'Referencias Externas Para Siniestros';
  GRANT UPDATE ON "AXIS"."SIN_SINIESTRO_REFERENCIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_SINIESTRO_REFERENCIAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_SINIESTRO_REFERENCIAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_SINIESTRO_REFERENCIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_SINIESTRO_REFERENCIAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_SINIESTRO_REFERENCIAS" TO "PROGRAMADORESCSI";
