--------------------------------------------------------
--  DDL for Table SIN_PROF_ZONAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_PROF_ZONAS" 
   (	"SPROFES" NUMBER, 
	"CNORDZN" NUMBER, 
	"CTPZONA" NUMBER, 
	"CPAIS" NUMBER, 
	"CPROVIN" NUMBER, 
	"CPOBLAC" NUMBER, 
	"CPOSINI" NUMBER, 
	"CPOSFIN" NUMBER, 
	"FDESDE" DATE, 
	"FHASTA" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_PROF_ZONAS"."SPROFES" IS 'Clave de profesional';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_ZONAS"."CNORDZN" IS 'Codigo unico consecutivo';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_ZONAS"."CTPZONA" IS 'Tipo de zona. VF 728';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_ZONAS"."CPAIS" IS 'Codigo pais';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_ZONAS"."CPROVIN" IS 'Codigo provincia';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_ZONAS"."CPOBLAC" IS 'Codigo poblacion';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_ZONAS"."CPOSINI" IS 'Cod Postal desde';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_ZONAS"."CPOSFIN" IS 'Cod Postal hasta';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_ZONAS"."FDESDE" IS 'Fecha inicio vigor';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_ZONAS"."FHASTA" IS 'Fecha fin vigor';
   COMMENT ON TABLE "AXIS"."SIN_PROF_ZONAS"  IS 'Zonas asignadas a un profesional';
  GRANT UPDATE ON "AXIS"."SIN_PROF_ZONAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PROF_ZONAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_PROF_ZONAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_PROF_ZONAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PROF_ZONAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_PROF_ZONAS" TO "PROGRAMADORESCSI";
