--------------------------------------------------------
--  DDL for Table SIN_TRAMITA_DETVEHICULO
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_TRAMITA_DETVEHICULO" 
   (	"NSINIES" VARCHAR2(14 BYTE), 
	"NTRAMIT" NUMBER(4,0), 
	"SPERCON" NUMBER(10,0), 
	"CESTPER" NUMBER(2,0), 
	"CTIPCAR" VARCHAR2(4 BYTE), 
	"FCARNET" DATE, 
	"CTIPCON" NUMBER(2,0), 
	"CALCOHOL" NUMBER(1,0), 
	"CTIPMAT" NUMBER(6,0), 
	"CMATRIC" VARCHAR2(12 BYTE), 
	"CMARCA" VARCHAR2(5 BYTE), 
	"SMODELO" NUMBER(8,0), 
	"CVERSION" VARCHAR2(11 BYTE), 
	"TTRAMITA" VARCHAR2(500 BYTE), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"NANYO" NUMBER(4,0), 
	"CODMOTOR" VARCHAR2(100 BYTE), 
	"CCHASIS" VARCHAR2(100 BYTE), 
	"NBASTID" VARCHAR2(20 BYTE), 
	"CCILINDRAJE" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."NSINIES" IS 'Número Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."NTRAMIT" IS 'Número Tramitación Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."SPERCON" IS 'Secuencia Persona Conductor/Propietario';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."CESTPER" IS 'Código Estado Persona';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."CTIPCAR" IS 'Código Tipo Permiso Conducir';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."FCARNET" IS 'Fecha Permiso Conducir';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."CTIPCON" IS 'Código Tipo Conductor';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."CALCOHOL" IS 'Indicador Alcoholemia';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."CTIPMAT" IS 'Código Tipo Matrícula';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."CMATRIC" IS 'Código Matrícula';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."CMARCA" IS 'Código Marca Vehículo';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."SMODELO" IS 'Secuencia Modelo Vehículo';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."CVERSION" IS 'Código Versión Vehículo';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."TTRAMITA" IS 'Descripción Tramitación';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."CUSUALT" IS 'Código Usuario Alta';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."FALTA" IS 'Fecha Alta';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."CUSUMOD" IS 'Código Usuario Modificación';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."FMODIFI" IS 'Fecha Modificación';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."NANYO" IS 'Año modelo del vehículo';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."CODMOTOR" IS 'Código motor';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."CCHASIS" IS 'Código chasis';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."NBASTID" IS 'Número bastidor';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_DETVEHICULO"."CCILINDRAJE" IS 'Cilindraje';
   COMMENT ON TABLE "AXIS"."SIN_TRAMITA_DETVEHICULO"  IS 'Detalle Tramitacion Conductor/Vehículo';
  GRANT UPDATE ON "AXIS"."SIN_TRAMITA_DETVEHICULO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_DETVEHICULO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_TRAMITA_DETVEHICULO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_TRAMITA_DETVEHICULO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_DETVEHICULO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_DETVEHICULO" TO "PROGRAMADORESCSI";
