--------------------------------------------------------
--  DDL for Table SIN_DESTRAMITACION
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_DESTRAMITACION" 
   (	"CTRAMIT" NUMBER(4,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TTRAMIT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_DESTRAMITACION"."CTRAMIT" IS 'Código Tramitación';
   COMMENT ON COLUMN "AXIS"."SIN_DESTRAMITACION"."CIDIOMA" IS 'Código Idioma';
   COMMENT ON COLUMN "AXIS"."SIN_DESTRAMITACION"."TTRAMIT" IS 'Descripción Tramitación';
   COMMENT ON TABLE "AXIS"."SIN_DESTRAMITACION"  IS 'Descripción Tramitaciones de Siniestro';
  GRANT UPDATE ON "AXIS"."SIN_DESTRAMITACION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_DESTRAMITACION" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_DESTRAMITACION" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_DESTRAMITACION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_DESTRAMITACION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_DESTRAMITACION" TO "PROGRAMADORESCSI";
