--------------------------------------------------------
--  DDL for Table SIN_CODMOTCAU
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_CODMOTCAU" 
   (	"CCAUSIN" NUMBER(4,0), 
	"CMOTSIN" NUMBER(4,0), 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE, 
	"CNOPERIT" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_CODMOTCAU"."CCAUSIN" IS 'Código Causa Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_CODMOTCAU"."CMOTSIN" IS 'Código Motivo Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_CODMOTCAU"."CUSUALT" IS 'Código Usuario Alta';
   COMMENT ON COLUMN "AXIS"."SIN_CODMOTCAU"."FALTA" IS 'Fecha Alta';
   COMMENT ON COLUMN "AXIS"."SIN_CODMOTCAU"."CUSUMOD" IS 'Código Usuario Modificación';
   COMMENT ON COLUMN "AXIS"."SIN_CODMOTCAU"."FMODIFI" IS 'Fecha Modificación';
   COMMENT ON COLUMN "AXIS"."SIN_CODMOTCAU"."CNOPERIT" IS 'No solicitar automaticamente peritaje al abrir siniestro';
   COMMENT ON TABLE "AXIS"."SIN_CODMOTCAU"  IS 'Motivos de Causas de Siniestro';
  GRANT UPDATE ON "AXIS"."SIN_CODMOTCAU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_CODMOTCAU" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_CODMOTCAU" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_CODMOTCAU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_CODMOTCAU" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_CODMOTCAU" TO "PROGRAMADORESCSI";
