--------------------------------------------------------
--  DDL for Table SIN_PROF_APUNTES
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_PROF_APUNTES" 
   (	"CEVENTO" VARCHAR2(20 BYTE), 
	"SLITTIT" NUMBER(8,0), 
	"SLITBOD" NUMBER(8,0), 
	"CTIPAGE" NUMBER(1,0), 
	"CTPDEST" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_PROF_APUNTES"."CEVENTO" IS 'Codigo de evento';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_APUNTES"."SLITTIT" IS 'Literal titulo apunte';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_APUNTES"."SLITBOD" IS 'Literal cuerpo apunte';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_APUNTES"."CTIPAGE" IS 'Tipo de agenda. 1-Agenda siniestro 2-Agenda usuario';
   COMMENT ON COLUMN "AXIS"."SIN_PROF_APUNTES"."CTPDEST" IS 'Tipo destinatario. 1-Profesional 2-Tramitador 3-Taller';
   COMMENT ON TABLE "AXIS"."SIN_PROF_APUNTES"  IS 'Apuntes automaticos en agenda';
  GRANT UPDATE ON "AXIS"."SIN_PROF_APUNTES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PROF_APUNTES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_PROF_APUNTES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_PROF_APUNTES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PROF_APUNTES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_PROF_APUNTES" TO "PROGRAMADORESCSI";
