--------------------------------------------------------
--  DDL for Table SIN_DESMOTRESCCAU
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_DESMOTRESCCAU" 
   (	"SPRODUC" NUMBER(6,0), 
	"CCAUSIN" NUMBER(4,0), 
	"CMOTRESC" NUMBER(4,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TMOTRESC" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_DESMOTRESCCAU"."SPRODUC" IS 'Código de Producto';
   COMMENT ON COLUMN "AXIS"."SIN_DESMOTRESCCAU"."CCAUSIN" IS 'Código Causa Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_DESMOTRESCCAU"."CMOTRESC" IS 'Código Motivo Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_DESMOTRESCCAU"."CIDIOMA" IS 'Código Idioma';
   COMMENT ON COLUMN "AXIS"."SIN_DESMOTRESCCAU"."TMOTRESC" IS 'Descripción Motivo Siniestro';
   COMMENT ON TABLE "AXIS"."SIN_DESMOTRESCCAU"  IS 'Descripción Motivos de Rescate de Siniestro';
  GRANT UPDATE ON "AXIS"."SIN_DESMOTRESCCAU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_DESMOTRESCCAU" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_DESMOTRESCCAU" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_DESMOTRESCCAU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_DESMOTRESCCAU" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_DESMOTRESCCAU" TO "PROGRAMADORESCSI";
