--------------------------------------------------------
--  DDL for Table SIN_DEFRAUDADORES
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_DEFRAUDADORES" 
   (	"NSINIES" VARCHAR2(14 BYTE), 
	"NDEFRAU" NUMBER(6,0), 
	"SPERSON" NUMBER(10,0), 
	"CTIPROL" NUMBER(13,0), 
	"FINIEFE" DATE, 
	"FFINEFE" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_DEFRAUDADORES"."NSINIES" IS 'Número de siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_DEFRAUDADORES"."NDEFRAU" IS 'Número de defraudador';
   COMMENT ON COLUMN "AXIS"."SIN_DEFRAUDADORES"."SPERSON" IS 'Secuencia unica de identificación de una persona';
   COMMENT ON COLUMN "AXIS"."SIN_DEFRAUDADORES"."CTIPROL" IS 'Rol del defraudador en el siniestro (V.F. = 800084)';
   COMMENT ON COLUMN "AXIS"."SIN_DEFRAUDADORES"."FINIEFE" IS 'Fecha de Inicio';
   COMMENT ON COLUMN "AXIS"."SIN_DEFRAUDADORES"."FFINEFE" IS 'Fecha de Fin';
   COMMENT ON COLUMN "AXIS"."SIN_DEFRAUDADORES"."CUSUALT" IS 'Código usuario alta del registro';
   COMMENT ON COLUMN "AXIS"."SIN_DEFRAUDADORES"."FALTA" IS 'Fecha de alta del registro';
   COMMENT ON TABLE "AXIS"."SIN_DEFRAUDADORES"  IS 'Defraudadores de Siniestros';
  GRANT UPDATE ON "AXIS"."SIN_DEFRAUDADORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_DEFRAUDADORES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_DEFRAUDADORES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_DEFRAUDADORES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_DEFRAUDADORES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_DEFRAUDADORES" TO "PROGRAMADORESCSI";
