--------------------------------------------------------
--  DDL for Table SIN_TRAMITA_MOVIMIENTO
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_TRAMITA_MOVIMIENTO" 
   (	"NSINIES" VARCHAR2(14 BYTE), 
	"NTRAMIT" NUMBER(4,0), 
	"NMOVTRA" NUMBER(3,0), 
	"CUNITRA" VARCHAR2(4 BYTE), 
	"CTRAMITAD" VARCHAR2(4 BYTE), 
	"CESTTRA" NUMBER(3,0), 
	"CSUBTRA" NUMBER(2,0), 
	"FESTTRA" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"FALTA" DATE, 
	"CCAUEST" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_MOVIMIENTO"."NSINIES" IS 'Número Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_MOVIMIENTO"."NTRAMIT" IS 'Número Tramitación Siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_MOVIMIENTO"."NMOVTRA" IS 'Número Movimiento Tramitación';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_MOVIMIENTO"."CUNITRA" IS 'Código Unidad Tramitación';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_MOVIMIENTO"."CTRAMITAD" IS 'Código Tramitador';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_MOVIMIENTO"."CESTTRA" IS 'Código Estado Tramitación';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_MOVIMIENTO"."CSUBTRA" IS 'Código Subestado Tramitación';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_MOVIMIENTO"."FESTTRA" IS 'Fecha Estado Tramitación';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_MOVIMIENTO"."CUSUALT" IS 'Código Usuario Alta';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_MOVIMIENTO"."FALTA" IS 'Fecha Alta';
   COMMENT ON COLUMN "AXIS"."SIN_TRAMITA_MOVIMIENTO"."CCAUEST" IS 'Causa movimiento/cambio de estado';
   COMMENT ON TABLE "AXIS"."SIN_TRAMITA_MOVIMIENTO"  IS 'Movimientos Tramitación Siniestro';
  GRANT UPDATE ON "AXIS"."SIN_TRAMITA_MOVIMIENTO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_MOVIMIENTO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_TRAMITA_MOVIMIENTO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_TRAMITA_MOVIMIENTO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_MOVIMIENTO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_TRAMITA_MOVIMIENTO" TO "PROGRAMADORESCSI";
