--------------------------------------------------------
--  DDL for Table SIN_DESTIPTRAMITADOR
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_DESTIPTRAMITADOR" 
   (	"CTIPTRAMIT" NUMBER(6,0), 
	"CIDIOMA" NUMBER(2,0), 
	"TTIPTRAMIT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_DESTIPTRAMITADOR"."CTIPTRAMIT" IS 'Código Tipo Tramitador';
   COMMENT ON COLUMN "AXIS"."SIN_DESTIPTRAMITADOR"."CIDIOMA" IS 'Código Idioma';
   COMMENT ON COLUMN "AXIS"."SIN_DESTIPTRAMITADOR"."TTIPTRAMIT" IS 'Descripción Tipo Tramitador';
   COMMENT ON TABLE "AXIS"."SIN_DESTIPTRAMITADOR"  IS 'Descripción Tipo Tramitador';
  GRANT UPDATE ON "AXIS"."SIN_DESTIPTRAMITADOR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_DESTIPTRAMITADOR" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_DESTIPTRAMITADOR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_DESTIPTRAMITADOR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_DESTIPTRAMITADOR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_DESTIPTRAMITADOR" TO "PROGRAMADORESCSI";
