--------------------------------------------------------
--  DDL for Table SIN_PLANTILLAS_CAMPO
--------------------------------------------------------

  CREATE TABLE "AXIS"."SIN_PLANTILLAS_CAMPO" 
   (	"NSINIES" VARCHAR2(14 BYTE), 
	"CCODPLAN" VARCHAR2(20 BYTE), 
	"NDOCUME" NUMBER, 
	"CCAMPO" VARCHAR2(20 BYTE), 
	"TCAMPO" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SIN_PLANTILLAS_CAMPO"."NSINIES" IS 'Número de siniestro';
   COMMENT ON COLUMN "AXIS"."SIN_PLANTILLAS_CAMPO"."CCODPLAN" IS 'Código de plantilla';
   COMMENT ON COLUMN "AXIS"."SIN_PLANTILLAS_CAMPO"."NDOCUME" IS 'Número de documento';
   COMMENT ON COLUMN "AXIS"."SIN_PLANTILLAS_CAMPO"."CCAMPO" IS 'Nombre del campo';
   COMMENT ON COLUMN "AXIS"."SIN_PLANTILLAS_CAMPO"."TCAMPO" IS 'Contenido del campo';
  GRANT UPDATE ON "AXIS"."SIN_PLANTILLAS_CAMPO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PLANTILLAS_CAMPO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SIN_PLANTILLAS_CAMPO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SIN_PLANTILLAS_CAMPO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIN_PLANTILLAS_CAMPO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIN_PLANTILLAS_CAMPO" TO "PROGRAMADORESCSI";
