--------------------------------------------------------
--  DDL for Table SINIESIT
--------------------------------------------------------

  CREATE TABLE "AXIS"."SINIESIT" 
   (	"NSINIES" NUMBER(8,0), 
	"FBAJA" DATE, 
	"FBAHOSPI" DATE, 
	"FALHOSPI" DATE, 
	"FALTA" DATE, 
	"NCAREN" NUMBER(3,0), 
	"NMOVAGE" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SINIESIT"."NMOVAGE" IS 'movimiento de agrupacion';
  GRANT UPDATE ON "AXIS"."SINIESIT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SINIESIT" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SINIESIT" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SINIESIT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SINIESIT" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SINIESIT" TO "PROGRAMADORESCSI";
