--------------------------------------------------------
--  DDL for Table SOLINTERTECSEG
--------------------------------------------------------

  CREATE TABLE "AXIS"."SOLINTERTECSEG" 
   (	"SSOLICIT" NUMBER(6,0), 
	"FEFEMOV" DATE, 
	"NMOVIMI" NUMBER(4,0), 
	"FMOVDIA" DATE, 
	"PINTTEC" NUMBER(7,2), 
	"NDESDE" NUMBER DEFAULT 0, 
	"NHASTA" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SOLINTERTECSEG"."SSOLICIT" IS 'Identificador del seguro';
   COMMENT ON COLUMN "AXIS"."SOLINTERTECSEG"."FEFEMOV" IS 'Fecha efecto de movimiento. Es la fecha que se utilizará para averiguar el interés';
   COMMENT ON COLUMN "AXIS"."SOLINTERTECSEG"."NMOVIMI" IS 'Número de Movimiento de la Póliza (alta o renovación)';
   COMMENT ON COLUMN "AXIS"."SOLINTERTECSEG"."FMOVDIA" IS 'Fecha día que se hace el movimiento';
   COMMENT ON COLUMN "AXIS"."SOLINTERTECSEG"."PINTTEC" IS 'Porcentaje de interés técnico';
   COMMENT ON TABLE "AXIS"."SOLINTERTECSEG"  IS 'Interés Ténico asociado a la Póliza. Se graba cada movimiento en el cual se asigna interés (alta y renovación)';
  GRANT UPDATE ON "AXIS"."SOLINTERTECSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SOLINTERTECSEG" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SOLINTERTECSEG" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SOLINTERTECSEG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SOLINTERTECSEG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SOLINTERTECSEG" TO "PROGRAMADORESCSI";
