--------------------------------------------------------
--  DDL for Table SOLPRESTCUADRO
--------------------------------------------------------

  CREATE TABLE "AXIS"."SOLPRESTCUADRO" 
   (	"SSOLICI" NUMBER(8,0), 
	"FVENCIM" DATE, 
	"ICAPITAL" NUMBER, 
	"ICAPEND" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SOLPRESTCUADRO"."SSOLICI" IS 'Código de la solicitud';
   COMMENT ON COLUMN "AXIS"."SOLPRESTCUADRO"."FVENCIM" IS 'Fecha venciento de la cuota';
   COMMENT ON COLUMN "AXIS"."SOLPRESTCUADRO"."ICAPITAL" IS 'Capital amortizado';
   COMMENT ON COLUMN "AXIS"."SOLPRESTCUADRO"."ICAPEND" IS 'Capital pendiente';
   COMMENT ON TABLE "AXIS"."SOLPRESTCUADRO"  IS 'Cuadro de amortización para la solicitud';
  GRANT UPDATE ON "AXIS"."SOLPRESTCUADRO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SOLPRESTCUADRO" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SOLPRESTCUADRO" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SOLPRESTCUADRO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SOLPRESTCUADRO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SOLPRESTCUADRO" TO "PROGRAMADORESCSI";
