--------------------------------------------------------
--  DDL for Table SOLPRESTAMOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."SOLPRESTAMOS" 
   (	"SSOLICI" NUMBER(8,0), 
	"ICAPITAL" NUMBER, 
	"FVENCIM" DATE, 
	"PPORCEN" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SOLPRESTAMOS"."SSOLICI" IS 'Código de la solicitud';
   COMMENT ON COLUMN "AXIS"."SOLPRESTAMOS"."ICAPITAL" IS 'Capital amortizado';
   COMMENT ON COLUMN "AXIS"."SOLPRESTAMOS"."FVENCIM" IS 'Fecha venciento de la cuota';
   COMMENT ON COLUMN "AXIS"."SOLPRESTAMOS"."PPORCEN" IS 'Porcentaje';
   COMMENT ON TABLE "AXIS"."SOLPRESTAMOS"  IS 'Cuadro de amortización para la solicitud';
  GRANT UPDATE ON "AXIS"."SOLPRESTAMOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SOLPRESTAMOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SOLPRESTAMOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SOLPRESTAMOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SOLPRESTAMOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SOLPRESTAMOS" TO "PROGRAMADORESCSI";
