--------------------------------------------------------
--  DDL for Table SOPORTEARP_AGENTE
--------------------------------------------------------

  CREATE TABLE "AXIS"."SOPORTEARP_AGENTE" 
   (	"CAGENTE" NUMBER, 
	"IIMPORTE" NUMBER, 
	"FINIVIG" DATE, 
	"FFINVIG" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SOPORTEARP_AGENTE"."CAGENTE" IS 'Código de agente';
   COMMENT ON COLUMN "AXIS"."SOPORTEARP_AGENTE"."IIMPORTE" IS 'Importe que se le asigna a algunas ADN''s por dar soporte administrativo';
   COMMENT ON COLUMN "AXIS"."SOPORTEARP_AGENTE"."FINIVIG" IS 'Fecha inicio vigencia';
   COMMENT ON COLUMN "AXIS"."SOPORTEARP_AGENTE"."FFINVIG" IS 'Fecha fin vigencia';
   COMMENT ON TABLE "AXIS"."SOPORTEARP_AGENTE"  IS 'Valor del Soporte por ARP';
  GRANT UPDATE ON "AXIS"."SOPORTEARP_AGENTE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SOPORTEARP_AGENTE" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."SOPORTEARP_AGENTE" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SOPORTEARP_AGENTE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SOPORTEARP_AGENTE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SOPORTEARP_AGENTE" TO "PROGRAMADORESCSI";
