--------------------------------------------------------
--  DDL for Table SUC_PPPC_RESU
--------------------------------------------------------

  CREATE TABLE "AXIS"."SUC_PPPC_RESU" 
   (	"SUCURSAL" NUMBER, 
	"SPROCES" NUMBER, 
	"PERIODO" VARCHAR2(8 BYTE), 
	"FECHA_PER" DATE, 
	"IPPPC" NUMBER, 
	"IPPPC_AN_ANT" NUMBER, 
	"IPPPC_AMPL" NUMBER, 
	"IPPPC_DISM" NUMBER, 
	"IPPPC_LIBE" NUMBER, 
	"IPPPC_CON_D" NUMBER, 
	"USUARIO" VARCHAR2(30 BYTE), 
	"FECHA_PROC" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."SUC_PPPC_RESU"."SUCURSAL" IS 'Sucursal';
   COMMENT ON COLUMN "AXIS"."SUC_PPPC_RESU"."SPROCES" IS 'Numero de proceso';
   COMMENT ON COLUMN "AXIS"."SUC_PPPC_RESU"."PERIODO" IS 'Perido de Cierre DD/YYYY';
   COMMENT ON COLUMN "AXIS"."SUC_PPPC_RESU"."FECHA_PER" IS 'Fecha de periodo';
   COMMENT ON COLUMN "AXIS"."SUC_PPPC_RESU"."IPPPC" IS 'Valor de la provision del periodo';
   COMMENT ON COLUMN "AXIS"."SUC_PPPC_RESU"."IPPPC_AN_ANT" IS 'Valor de Provision Año Anterior';
   COMMENT ON COLUMN "AXIS"."SUC_PPPC_RESU"."IPPPC_AMPL" IS 'Valor de Provision Ampliacion';
   COMMENT ON COLUMN "AXIS"."SUC_PPPC_RESU"."IPPPC_DISM" IS 'Valor de Provision Disminucion';
   COMMENT ON COLUMN "AXIS"."SUC_PPPC_RESU"."IPPPC_LIBE" IS 'Valor de Provision Liberacion';
   COMMENT ON COLUMN "AXIS"."SUC_PPPC_RESU"."IPPPC_CON_D" IS 'Valor de Provision Debe';
   COMMENT ON COLUMN "AXIS"."SUC_PPPC_RESU"."USUARIO" IS 'Usuario del proceso';
   COMMENT ON COLUMN "AXIS"."SUC_PPPC_RESU"."FECHA_PROC" IS 'Fecha del proceso';
  GRANT INSERT ON "AXIS"."SUC_PPPC_RESU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SUC_PPPC_RESU" TO "R_AXIS";
  GRANT UPDATE ON "AXIS"."SUC_PPPC_RESU" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."SUC_PPPC_RESU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SUC_PPPC_RESU" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SUC_PPPC_RESU" TO "PROGRAMADORESCSI";
