--------------------------------------------------------
--  DDL for Table TAB_TEMPORALES
--------------------------------------------------------

  CREATE TABLE "AXIS"."TAB_TEMPORALES" 
   (	"TTABLA" VARCHAR2(80 BYTE), 
	"TWHERE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TAB_TEMPORALES"."TTABLA" IS 'Nombre de la tabla temporal';
   COMMENT ON COLUMN "AXIS"."TAB_TEMPORALES"."TWHERE" IS 'Condicion where de la tabla temporal';
   COMMENT ON TABLE "AXIS"."TAB_TEMPORALES"  IS 'Tablas temporales que se borraran en el proceso nocturno';
  GRANT UPDATE ON "AXIS"."TAB_TEMPORALES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TAB_TEMPORALES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TAB_TEMPORALES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TAB_TEMPORALES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TAB_TEMPORALES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TAB_TEMPORALES" TO "PROGRAMADORESCSI";
