--------------------------------------------------------
--  DDL for Table TABVALCES
--------------------------------------------------------

  CREATE TABLE "AXIS"."TABVALCES" 
   (	"CCESTA" NUMBER(3,0), 
	"FVALOR" DATE, 
	"NPARACT" NUMBER(15,6), 
	"IUNIACT" NUMBER, 
	"IVALACT" NUMBER, 
	"NPARASI" NUMBER(15,6), 
	"IGASTOS" NUMBER(15,6), 
	"IPATRIMONIO" NUMBER(14,3), 
	"IUNIACTCMP" NUMBER, 
	"IUNIACTVTASHW" NUMBER, 
	"IUNIACTCMPSHW" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TABVALCES"."IPATRIMONIO" IS 'Valor total del fondo';
   COMMENT ON COLUMN "AXIS"."TABVALCES"."IUNIACTCMP" IS 'Valor de compra';
   COMMENT ON COLUMN "AXIS"."TABVALCES"."IUNIACTVTASHW" IS 'Valor de venta de la shadow';
   COMMENT ON COLUMN "AXIS"."TABVALCES"."IUNIACTCMPSHW" IS 'Valor de compra de la shadow';
  GRANT UPDATE ON "AXIS"."TABVALCES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TABVALCES" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TABVALCES" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TABVALCES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TABVALCES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TABVALCES" TO "PROGRAMADORESCSI";
