--------------------------------------------------------
--  DDL for Table TARIFAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."TARIFAS" 
   (	"CTARIFA" NUMBER(5,0), 
	"NCOLUMN" NUMBER(4,0), 
	"NFILA" NUMBER(4,0), 
	"IATRIBU" NUMBER(19,12)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TARIFAS"."CTARIFA" IS 'Código de tarifa';
   COMMENT ON COLUMN "AXIS"."TARIFAS"."NCOLUMN" IS 'Columna';
   COMMENT ON COLUMN "AXIS"."TARIFAS"."NFILA" IS 'Fila';
   COMMENT ON COLUMN "AXIS"."TARIFAS"."IATRIBU" IS 'Importe del atributo';
  GRANT UPDATE ON "AXIS"."TARIFAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TARIFAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TARIFAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TARIFAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TARIFAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TARIFAS" TO "PROGRAMADORESCSI";
