--------------------------------------------------------
--  DDL for Table TBESTFILASTABLA
--------------------------------------------------------

  CREATE TABLE "AXIS"."TBESTFILASTABLA" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"STABLA" NUMBER(8,0), 
	"NFILA" NUMBER(5,0), 
	"TVALOR" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TBESTFILASTABLA"."SSEGURO" IS 'Código de seguro';
   COMMENT ON COLUMN "AXIS"."TBESTFILASTABLA"."NRIESGO" IS 'Código de riesgo';
   COMMENT ON COLUMN "AXIS"."TBESTFILASTABLA"."NMOVIMI" IS 'Código de movimiento';
   COMMENT ON COLUMN "AXIS"."TBESTFILASTABLA"."STABLA" IS 'Código de la tabla';
   COMMENT ON COLUMN "AXIS"."TBESTFILASTABLA"."NFILA" IS 'Número de la fila';
   COMMENT ON COLUMN "AXIS"."TBESTFILASTABLA"."TVALOR" IS 'Descripción del suplemento para la fila';
   COMMENT ON TABLE "AXIS"."TBESTFILASTABLA"  IS 'Contiene el suplemento adquirido para cada fila en función de seguro,riesgo y movimiento (tabla intermedia)';
  GRANT UPDATE ON "AXIS"."TBESTFILASTABLA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TBESTFILASTABLA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TBESTFILASTABLA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TBESTFILASTABLA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TBESTFILASTABLA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TBESTFILASTABLA" TO "PROGRAMADORESCSI";
