--------------------------------------------------------
--  DDL for Table TBSEGDETTABLA
--------------------------------------------------------

  CREATE TABLE "AXIS"."TBSEGDETTABLA" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER(6,0), 
	"NMOVIMI" NUMBER(4,0), 
	"STABLA" NUMBER(8,0), 
	"NUSERFILA" NUMBER(5,0), 
	"CVALOR" NUMBER(2,0), 
	"NVALOR" FLOAT(126), 
	"TVALOR" VARCHAR2(100 BYTE), 
	"DVALOR" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TBSEGDETTABLA"."SSEGURO" IS 'Código de seguro';
   COMMENT ON COLUMN "AXIS"."TBSEGDETTABLA"."NRIESGO" IS 'Código de riesgo';
   COMMENT ON COLUMN "AXIS"."TBSEGDETTABLA"."NMOVIMI" IS 'Código de movimiento';
   COMMENT ON COLUMN "AXIS"."TBSEGDETTABLA"."STABLA" IS 'Código de la tabla';
   COMMENT ON COLUMN "AXIS"."TBSEGDETTABLA"."NUSERFILA" IS 'Número de orden de la fila';
   COMMENT ON COLUMN "AXIS"."TBSEGDETTABLA"."CVALOR" IS 'Código de la columna';
   COMMENT ON COLUMN "AXIS"."TBSEGDETTABLA"."NVALOR" IS 'Valor de la fila-columna si es de tipo numerico';
   COMMENT ON COLUMN "AXIS"."TBSEGDETTABLA"."TVALOR" IS 'Valor de la fila-columna si es de tipo texto';
   COMMENT ON COLUMN "AXIS"."TBSEGDETTABLA"."DVALOR" IS 'Valor de la fila-columna si es de tipo fecha';
   COMMENT ON TABLE "AXIS"."TBSEGDETTABLA"  IS 'Detalle de la tabla( valor de sus filas para cada columna) en función de seguro,riesgo y movimiento';
  GRANT UPDATE ON "AXIS"."TBSEGDETTABLA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TBSEGDETTABLA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TBSEGDETTABLA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TBSEGDETTABLA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TBSEGDETTABLA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TBSEGDETTABLA" TO "PROGRAMADORESCSI";
