--------------------------------------------------------
--  DDL for Table TBVIGENCIATABLA
--------------------------------------------------------

  CREATE TABLE "AXIS"."TBVIGENCIATABLA" 
   (	"STABLA" NUMBER(8,0), 
	"CTABLA" NUMBER(5,0), 
	"FDESDE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TBVIGENCIATABLA"."STABLA" IS 'Código de secuéncia de la tabla';
   COMMENT ON COLUMN "AXIS"."TBVIGENCIATABLA"."CTABLA" IS 'Código de la columna de la tabla';
   COMMENT ON COLUMN "AXIS"."TBVIGENCIATABLA"."FDESDE" IS 'Fecha de vigencia de la tabla';
   COMMENT ON TABLE "AXIS"."TBVIGENCIATABLA"  IS 'Contiene el identificador de la tabla en función de la fecha de creación de la tabla';
  GRANT UPDATE ON "AXIS"."TBVIGENCIATABLA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TBVIGENCIATABLA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TBVIGENCIATABLA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TBVIGENCIATABLA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TBVIGENCIATABLA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TBVIGENCIATABLA" TO "PROGRAMADORESCSI";
