--------------------------------------------------------
--  DDL for Table TDC234_OUT
--------------------------------------------------------

  CREATE TABLE "AXIS"."TDC234_OUT" 
   (	"STDC234OUT" NUMBER(10,0), 
	"FENVIO" DATE, 
	"NFICHERO" NUMBER(1,0), 
	"TFICHERO" VARCHAR2(60 BYTE), 
	"STRAS" NUMBER(8,0), 
	"SSEGURO" NUMBER, 
	"CESTADO" NUMBER(1,0), 
	"STDC" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TDC234_OUT"."STDC234OUT" IS 'Secuencia de la tabla';
   COMMENT ON COLUMN "AXIS"."TDC234_OUT"."FENVIO" IS 'Fecha Envío';
   COMMENT ON COLUMN "AXIS"."TDC234_OUT"."NFICHERO" IS 'Número del fichero';
   COMMENT ON COLUMN "AXIS"."TDC234_OUT"."TFICHERO" IS 'Nombre del fichero';
   COMMENT ON COLUMN "AXIS"."TDC234_OUT"."STRAS" IS 'Identificador del traspaso';
   COMMENT ON COLUMN "AXIS"."TDC234_OUT"."SSEGURO" IS 'Identificador de la póliza';
   COMMENT ON COLUMN "AXIS"."TDC234_OUT"."CESTADO" IS 'Estado del traspaso';
   COMMENT ON COLUMN "AXIS"."TDC234_OUT"."STDC" IS 'Identificador del traspaso en TDC234';
  GRANT UPDATE ON "AXIS"."TDC234_OUT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TDC234_OUT" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TDC234_OUT" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TDC234_OUT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TDC234_OUT" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TDC234_OUT" TO "PROGRAMADORESCSI";
