--------------------------------------------------------
--  DDL for Table TDC234
--------------------------------------------------------

  CREATE TABLE "AXIS"."TDC234" 
   (	"STDC" NUMBER(8,0), 
	"FGENERA" DATE, 
	"CFICHERO" VARCHAR2(50 BYTE), 
	"CESTADO" NUMBER(1,0), 
	"CREF" VARCHAR2(13 BYTE), 
	"CCODPLA" NUMBER(6,0), 
	"SSEGURO" NUMBER, 
	"STRAS" NUMBER(8,0), 
	"NMOTIU" NUMBER(3,0), 
	"FVALMOV" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TDC234"."STDC" IS 'Secuencia de TDC234';
   COMMENT ON COLUMN "AXIS"."TDC234"."FGENERA" IS 'Fecha Carga del Fichero';
   COMMENT ON COLUMN "AXIS"."TDC234"."CFICHERO" IS 'Nombre del Fichero';
   COMMENT ON COLUMN "AXIS"."TDC234"."CREF" IS 'Referencia';
   COMMENT ON COLUMN "AXIS"."TDC234"."SSEGURO" IS 'Contrato asociado al traspaso';
   COMMENT ON COLUMN "AXIS"."TDC234"."STRAS" IS 'Clave de TRASPLAINOUT';
   COMMENT ON TABLE "AXIS"."TDC234"  IS 'Cabecera registro TDC234 Entrada';
  GRANT UPDATE ON "AXIS"."TDC234" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TDC234" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TDC234" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TDC234" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TDC234" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TDC234" TO "PROGRAMADORESCSI";
