--------------------------------------------------------
--  DDL for Table TIPOS_CUENTA
--------------------------------------------------------

  CREATE TABLE "AXIS"."TIPOS_CUENTA" 
   (	"CTIPBAN" NUMBER(3,0), 
	"NORDEN" NUMBER(1,0), 
	"LONGITUD" NUMBER(2,0), 
	"FORMATO" VARCHAR2(50 BYTE), 
	"POS_ENTIDAD" NUMBER(2,0), 
	"LONG_ENTIDAD" NUMBER(2,0), 
	"CTIPCC" NUMBER(2,0), 
	"CBANCO" NUMBER(4,0), 
	"PREFIJO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TIPOS_CUENTA"."CTIPBAN" IS 'Tipo de cuenta ( iban o cuenta bancaria). [tabla maestra: TIPOS_CUENTA]';
   COMMENT ON COLUMN "AXIS"."TIPOS_CUENTA"."NORDEN" IS 'Orden de aparición en listas de valores';
   COMMENT ON COLUMN "AXIS"."TIPOS_CUENTA"."POS_ENTIDAD" IS 'En que posición empieza el código de entidad del banco';
   COMMENT ON COLUMN "AXIS"."TIPOS_CUENTA"."LONG_ENTIDAD" IS 'Que longitud tiene el código de entidad del banco';
   COMMENT ON COLUMN "AXIS"."TIPOS_CUENTA"."CTIPCC" IS 'Que tipo de cuenta és VF.800049';
   COMMENT ON COLUMN "AXIS"."TIPOS_CUENTA"."CBANCO" IS 'Código de Banco';
   COMMENT ON COLUMN "AXIS"."TIPOS_CUENTA"."PREFIJO" IS 'Prefijo por el que deberá comenzar el número de cuenta o tarjeta. :NÚMERO_CUENTA(sin código banco) LIKE PREFIJO||''%''';
   COMMENT ON TABLE "AXIS"."TIPOS_CUENTA"  IS 'Tipos o formatos de cuentas CCC';
  GRANT UPDATE ON "AXIS"."TIPOS_CUENTA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TIPOS_CUENTA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TIPOS_CUENTA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TIPOS_CUENTA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TIPOS_CUENTA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TIPOS_CUENTA" TO "PROGRAMADORESCSI";
