--------------------------------------------------------
--  DDL for Table TIPOSCARTA
--------------------------------------------------------

  CREATE TABLE "AXIS"."TIPOSCARTA" 
   (	"CTIPCAR" NUMBER(4,0), 
	"CMODELO" NUMBER(2,0), 
	"CBLOQUE" NUMBER(4,0), 
	"CAGRUP" NUMBER(3,0), 
	"CMAPEAD" VARCHAR2(5 BYTE), 
	"TREPORT" VARCHAR2(15 BYTE), 
	"CCODPLAN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TIPOSCARTA"."CTIPCAR" IS 'Codigo de tipo de carta';
   COMMENT ON COLUMN "AXIS"."TIPOSCARTA"."CMODELO" IS 'Codigo de modelo';
   COMMENT ON COLUMN "AXIS"."TIPOSCARTA"."CBLOQUE" IS 'Codigo de bloque';
   COMMENT ON COLUMN "AXIS"."TIPOSCARTA"."CAGRUP" IS 'Código agrupación en base a DETVALORES(catribu)';
   COMMENT ON COLUMN "AXIS"."TIPOSCARTA"."CMAPEAD" IS 'Código del MAP asociado a esta carta';
   COMMENT ON COLUMN "AXIS"."TIPOSCARTA"."TREPORT" IS 'Código de Report a ejecutar';
   COMMENT ON TABLE "AXIS"."TIPOSCARTA"  IS 'Tabla maestra de tipologias de carta que se vincularan a modelos';
  GRANT UPDATE ON "AXIS"."TIPOSCARTA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TIPOSCARTA" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TIPOSCARTA" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TIPOSCARTA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TIPOSCARTA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TIPOSCARTA" TO "PROGRAMADORESCSI";
