--------------------------------------------------------
--  DDL for Table TIPOSVIAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."TIPOSVIAS" 
   (	"CTIPVIA" NUMBER(3,0), 
	"TTIPOVIA" VARCHAR2(50 BYTE), 
	"CSIGLAS" VARCHAR2(50 BYTE), 
	"CFUENTE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TIPOSVIAS"."CTIPVIA" IS 'Id Tipo de Vía';
   COMMENT ON COLUMN "AXIS"."TIPOSVIAS"."TTIPOVIA" IS 'Descripción del tipo de vía';
   COMMENT ON COLUMN "AXIS"."TIPOSVIAS"."CSIGLAS" IS 'Siglas del tipo de vía';
   COMMENT ON COLUMN "AXIS"."TIPOSVIAS"."CFUENTE" IS 'Indica la fuente de procedencia (TeleAtlas, Correos, Manual, etc)';
   COMMENT ON TABLE "AXIS"."TIPOSVIAS"  IS 'Tipos de Vía (o Calle)';
  GRANT UPDATE ON "AXIS"."TIPOSVIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TIPOSVIAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TIPOSVIAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TIPOSVIAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TIPOSVIAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TIPOSVIAS" TO "PROGRAMADORESCSI";
