--------------------------------------------------------
--  DDL for Table TMP_JOURNAL_PERS
--------------------------------------------------------

  CREATE TABLE "AXIS"."TMP_JOURNAL_PERS" 
   (	"NNUMLIN" NUMBER(6,0), 
	"DIA" DATE, 
	"PRODUCTE" VARCHAR2(2 BYTE), 
	"POLISSA_INI" VARCHAR2(15 BYTE), 
	"OPERACIO" VARCHAR2(1 BYTE), 
	"NORDEN" NUMBER(2,0), 
	"CPERHOS" NUMBER(7,0), 
	"CNIFHOS" VARCHAR2(13 BYTE), 
	"NNUMNIF" VARCHAR2(50 BYTE), 
	"FNACIMI" DATE, 
	"CSEXPER" NUMBER(1,0), 
	"SSEGURO" NUMBER, 
	"SPERSON" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."TMP_JOURNAL_PERS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TMP_JOURNAL_PERS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TMP_JOURNAL_PERS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TMP_JOURNAL_PERS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TMP_JOURNAL_PERS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TMP_JOURNAL_PERS" TO "PROGRAMADORESCSI";
