--------------------------------------------------------
--  DDL for Table TMP_CARTERAUX
--------------------------------------------------------

  CREATE TABLE "AXIS"."TMP_CARTERAUX" 
   (	"SPROCAR" NUMBER(9,0), 
	"SPRODUC" NUMBER(6,0), 
	"CESTADO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TMP_CARTERAUX"."SPROCAR" IS 'Identificador del proceso de cartera';
   COMMENT ON COLUMN "AXIS"."TMP_CARTERAUX"."SPRODUC" IS 'Identificador del producto';
   COMMENT ON COLUMN "AXIS"."TMP_CARTERAUX"."CESTADO" IS 'Estado de seleccion : 1. Si el producto ha sido seleccionado, 0 .- si el producto no ha sido seleccionado';
  GRANT UPDATE ON "AXIS"."TMP_CARTERAUX" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TMP_CARTERAUX" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TMP_CARTERAUX" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TMP_CARTERAUX" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TMP_CARTERAUX" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TMP_CARTERAUX" TO "PROGRAMADORESCSI";
