--------------------------------------------------------
--  DDL for Table TMP_TRASPASOS_ULK
--------------------------------------------------------

  CREATE TABLE "AXIS"."TMP_TRASPASOS_ULK" 
   (	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER(4,0), 
	"FEFECTO" DATE, 
	"FVALMOV" DATE, 
	"CCESTA" NUMBER(3,0), 
	"NUNIDAD" NUMBER(15,6), 
	"IIMPORT" NUMBER(15,6), 
	"PPORFIN" NUMBER(5,2), 
	"IIMPFIN" NUMBER(15,6), 
	"CESTADO" VARCHAR2(1 BYTE), 
	"IIMPPEN" NUMBER, 
	"PPORPEN" NUMBER(12,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."TMP_TRASPASOS_ULK" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TMP_TRASPASOS_ULK" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TMP_TRASPASOS_ULK" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TMP_TRASPASOS_ULK" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TMP_TRASPASOS_ULK" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TMP_TRASPASOS_ULK" TO "PROGRAMADORESCSI";
