--------------------------------------------------------
--  DDL for Table TMP_TARJETAS_CASER_CORR
--------------------------------------------------------

  CREATE TABLE "AXIS"."TMP_TARJETAS_CASER_CORR" 
   (	"STMPCASER" NUMBER(10,0), 
	"PRODUCTE" NUMBER, 
	"POLISSA_INI" VARCHAR2(15 BYTE), 
	"NRIESGO" NUMBER(6,0), 
	"NTARJETA" VARCHAR2(16 BYTE), 
	"FVENCIM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TMP_TARJETAS_CASER_CORR"."STMPCASER" IS 'Clau primària';
   COMMENT ON COLUMN "AXIS"."TMP_TARJETAS_CASER_CORR"."PRODUCTE" IS 'Producte CESGRUP';
   COMMENT ON COLUMN "AXIS"."TMP_TARJETAS_CASER_CORR"."POLISSA_INI" IS 'Número de pòlissa CESGRUP';
   COMMENT ON COLUMN "AXIS"."TMP_TARJETAS_CASER_CORR"."NRIESGO" IS 'Número de risc';
   COMMENT ON COLUMN "AXIS"."TMP_TARJETAS_CASER_CORR"."NTARJETA" IS 'Número de targeta';
   COMMENT ON COLUMN "AXIS"."TMP_TARJETAS_CASER_CORR"."FVENCIM" IS 'Data Venciment';
   COMMENT ON TABLE "AXIS"."TMP_TARJETAS_CASER_CORR"  IS 'Taula temporal per la renovació de targetes (ALBOR)';
  GRANT UPDATE ON "AXIS"."TMP_TARJETAS_CASER_CORR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TMP_TARJETAS_CASER_CORR" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TMP_TARJETAS_CASER_CORR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TMP_TARJETAS_CASER_CORR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TMP_TARJETAS_CASER_CORR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TMP_TARJETAS_CASER_CORR" TO "PROGRAMADORESCSI";
