--------------------------------------------------------
--  DDL for Table TPR_MONEDAS
--------------------------------------------------------

  CREATE TABLE "AXIS"."TPR_MONEDAS" 
   (	"SPRODUC" NUMBER(6,0), 
	"CMONCTR" VARCHAR2(3 BYTE), 
	"FINIVIG" DATE, 
	"FFINVIG" DATE, 
	"BDEFECTO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TPR_MONEDAS"."SPRODUC" IS 'Secuencial Producto';
   COMMENT ON COLUMN "AXIS"."TPR_MONEDAS"."CMONCTR" IS 'Código Moneda';
   COMMENT ON COLUMN "AXIS"."TPR_MONEDAS"."FINIVIG" IS 'Fecha Inicio Vigencia';
   COMMENT ON COLUMN "AXIS"."TPR_MONEDAS"."FFINVIG" IS 'Fecha Fin Vigencia';
   COMMENT ON COLUMN "AXIS"."TPR_MONEDAS"."BDEFECTO" IS 'Indicador valor por defecto';
   COMMENT ON TABLE "AXIS"."TPR_MONEDAS"  IS 'Tabla Monedas por Producto';
  GRANT UPDATE ON "AXIS"."TPR_MONEDAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TPR_MONEDAS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TPR_MONEDAS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TPR_MONEDAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TPR_MONEDAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TPR_MONEDAS" TO "PROGRAMADORESCSI";
