--------------------------------------------------------
--  DDL for Table TRAMOSREGUL
--------------------------------------------------------

  CREATE TABLE "AXIS"."TRAMOSREGUL" 
   (	"SSEGURO" NUMBER, 
	"NRIESGO" NUMBER, 
	"NMOVIMI" NUMBER, 
	"CGARANT" NUMBER, 
	"NMOVIMIORG" NUMBER, 
	"FECINI" DATE, 
	"FECFIN" DATE, 
	"CTIPO" NUMBER, 
	"IPRIANUORG" NUMBER, 
	"IPRIANUFIN" NUMBER, 
	"ICAPITALORG" NUMBER, 
	"ICAPITALFIN" NUMBER, 
	"IIMPRECIBO" NUMBER, 
	"FINIORIGAR" DATE, 
	"FFINORIGAR" DATE, 
	"FALTA" DATE, 
	"CUSUALT" VARCHAR2(20 BYTE), 
	"CUSUMOD" VARCHAR2(20 BYTE), 
	"FMODIFI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."SSEGURO" IS 'Identificador de poliza (SEGUROS)';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."NRIESGO" IS 'Nro de riesgo (RIESGOS)';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."NMOVIMI" IS 'Nro de movimiento actual (MOVSEGURO)';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."CGARANT" IS 'Codigo garantía (GARANSEG)';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."NMOVIMIORG" IS 'Nro de movimiento origen(MOVSEGURO)';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."FECINI" IS 'Fecha inicio del tramo';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."FECFIN" IS 'Fecha fin del tramo';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."CTIPO" IS 'Tipo de movimiento (1-suplemento/2-regularización)';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."IPRIANUORG" IS 'Prima anual mvto origen';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."IPRIANUFIN" IS 'Prima anual mvto actual';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."ICAPITALORG" IS 'Capital mvto origen';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."ICAPITALFIN" IS 'Capital mvto final';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."IIMPRECIBO" IS 'Importe para el recibo';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."FINIORIGAR" IS 'Fecha inicio Original de la garantía';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."FFINORIGAR" IS 'Fecha final Original de la garantía';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."FALTA" IS 'Fecha Alta';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."CUSUALT" IS 'Usuario Alta';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."CUSUMOD" IS 'Usuario Modificación';
   COMMENT ON COLUMN "AXIS"."TRAMOSREGUL"."FMODIFI" IS 'Fecha Modificación';
   COMMENT ON TABLE "AXIS"."TRAMOSREGUL"  IS 'Tramos de regularización';
  GRANT UPDATE ON "AXIS"."TRAMOSREGUL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TRAMOSREGUL" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TRAMOSREGUL" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TRAMOSREGUL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TRAMOSREGUL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TRAMOSREGUL" TO "PROGRAMADORESCSI";
