--------------------------------------------------------
--  DDL for Table TRASPLABLOQ
--------------------------------------------------------

  CREATE TABLE "AXIS"."TRASPLABLOQ" 
   (	"STRAS" NUMBER(8,0), 
	"NBLOQ" NUMBER(4,0), 
	"TAUTORIT" VARCHAR2(35 BYTE), 
	"TDEMANDA" VARCHAR2(27 BYTE), 
	"FCOMUNIC" DATE, 
	"SSEGURO" NUMBER, 
	"FINICIO" DATE, 
	"CMOTMOV" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."TRASPLABLOQ"."STRAS" IS 'Clau primària de traspassos';
   COMMENT ON COLUMN "AXIS"."TRASPLABLOQ"."NBLOQ" IS 'Num. de bloqueig';
   COMMENT ON COLUMN "AXIS"."TRASPLABLOQ"."TAUTORIT" IS 'Autoritat que decreta l''embargament';
   COMMENT ON COLUMN "AXIS"."TRASPLABLOQ"."TDEMANDA" IS 'Identificació de la demanda';
   COMMENT ON COLUMN "AXIS"."TRASPLABLOQ"."FCOMUNIC" IS 'Data comunicació de l''embargament';
   COMMENT ON COLUMN "AXIS"."TRASPLABLOQ"."SSEGURO" IS 'Código del seguro';
   COMMENT ON COLUMN "AXIS"."TRASPLABLOQ"."FINICIO" IS 'Fecha de inicio del bloqueo o la pignoración';
   COMMENT ON COLUMN "AXIS"."TRASPLABLOQ"."CMOTMOV" IS 'Motivo del movimiento que corresponde al tipo de bloqueo ( 261.- Pignoracion, 262.- Bloqueo, 263.- Despignoracion, 264.- Desbloqueo )';
   COMMENT ON TABLE "AXIS"."TRASPLABLOQ"  IS 'Tabla Bloqueos';
  GRANT UPDATE ON "AXIS"."TRASPLABLOQ" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TRASPLABLOQ" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."TRASPLABLOQ" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."TRASPLABLOQ" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."TRASPLABLOQ" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."TRASPLABLOQ" TO "PROGRAMADORESCSI";
