--------------------------------------------------------
--  DDL for Table ULRETEN
--------------------------------------------------------

  CREATE TABLE "AXIS"."ULRETEN" 
   (	"SSEGURO" NUMBER, 
	"NMOVIMI" NUMBER(4,0), 
	"FRESCAT" DATE, 
	"CRESCAT" NUMBER(2,0), 
	"NSINIES" NUMBER(8,0), 
	"IRESCAT" NUMBER, 
	"IIMPRED" NUMBER, 
	"IRETEN" NUMBER, 
	"NORDEN" NUMBER(4,0), 
	"IPRIMA" NUMBER, 
	"IPRIRCM" NUMBER, 
	"IPRINET" NUMBER, 
	"IPRIRED" NUMBER, 
	"IPRIRES" NUMBER, 
	"IRESRCM" NUMBER, 
	"IRESRET" NUMBER, 
	"IRESRED" NUMBER, 
	"CPROCES" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."ULRETEN"."IRESCAT" IS 'Importe del rescate (le faltará restar la retención IRETEN)';
   COMMENT ON COLUMN "AXIS"."ULRETEN"."IIMPRED" IS 'Base de la Retención. Rendimiento ya reducido sobre el que se aplica la retención (1ª y 2ª Reducción hecha)';
   COMMENT ON COLUMN "AXIS"."ULRETEN"."IRETEN" IS 'Importe Retenido';
   COMMENT ON COLUMN "AXIS"."ULRETEN"."IRESRCM" IS 'Rendimiento bruto antes de reducciones';
   COMMENT ON COLUMN "AXIS"."ULRETEN"."IRESRED" IS 'Rendimiento reducido por antigüedad (1ª Reducción hecha)';
  GRANT UPDATE ON "AXIS"."ULRETEN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ULRETEN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."ULRETEN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."ULRETEN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."ULRETEN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."ULRETEN" TO "PROGRAMADORESCSI";
