--------------------------------------------------------
--  DDL for Table USU_DATOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."USU_DATOS" 
   (	"CUSUARI" VARCHAR2(20 BYTE), 
	"TINICIA" VARCHAR2(4 BYTE), 
	"CAREA" VARCHAR2(4 BYTE), 
	"CDEPT" VARCHAR2(4 BYTE), 
	"MAIL" VARCHAR2(40 BYTE), 
	"CCARGO" VARCHAR2(4 BYTE), 
	"CLUGAR" VARCHAR2(3 BYTE), 
	"NPORTAL" NUMBER(1,0), 
	"CACTIVO" VARCHAR2(1 BYTE), 
	"FCADPASSW" DATE, 
	"CTRAMIT" VARCHAR2(4 BYTE), 
	"CTIPTRA" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."USU_DATOS"."CUSUARI" IS 'CODIGO USUARIO';
   COMMENT ON COLUMN "AXIS"."USU_DATOS"."TINICIA" IS 'INICIALES IDENTIFICATIVAS';
   COMMENT ON COLUMN "AXIS"."USU_DATOS"."CAREA" IS 'Código de área a la que pertenece el usuario';
   COMMENT ON COLUMN "AXIS"."USU_DATOS"."CDEPT" IS 'Código de departamento a la que pertenece el usuario';
   COMMENT ON COLUMN "AXIS"."USU_DATOS"."MAIL" IS 'Dirección E_Mail del Usuario';
   COMMENT ON COLUMN "AXIS"."USU_DATOS"."CCARGO" IS 'Código del cargo que ocupa';
   COMMENT ON COLUMN "AXIS"."USU_DATOS"."CLUGAR" IS 'LUGAR DE TRABAJO DEL EMPLEADO';
   COMMENT ON COLUMN "AXIS"."USU_DATOS"."NPORTAL" IS 'Indicador de acceso al portal corporativo';
   COMMENT ON COLUMN "AXIS"."USU_DATOS"."CACTIVO" IS 'SI ESTA ACTIVADO O NO Y LOS MOTIVOS';
   COMMENT ON COLUMN "AXIS"."USU_DATOS"."FCADPASSW" IS 'FECHA QUE DEBE CAMBIAR EL PASSWORD';
   COMMENT ON COLUMN "AXIS"."USU_DATOS"."CTRAMIT" IS 'Código tramitador principal';
   COMMENT ON COLUMN "AXIS"."USU_DATOS"."CTIPTRA" IS 'Código tipo tramitador';
   COMMENT ON TABLE "AXIS"."USU_DATOS"  IS 'DATOS ADICIONALES USUARIOS';
  GRANT UPDATE ON "AXIS"."USU_DATOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."USU_DATOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."USU_DATOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."USU_DATOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."USU_DATOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."USU_DATOS" TO "PROGRAMADORESCSI";
