--------------------------------------------------------
--  DDL for Table VALORASINITRAMI
--------------------------------------------------------

  CREATE TABLE "AXIS"."VALORASINITRAMI" 
   (	"NSINIES" NUMBER(8,0), 
	"NTRAMIT" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0), 
	"NVALORA" NUMBER(2,0), 
	"FVALORA" DATE, 
	"IVALORA" NUMBER, 
	"FPERINI" DATE, 
	"FPERFIN" DATE, 
	"CTIPVAL" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."VALORASINITRAMI"."NSINIES" IS 'Numero de siniestro';
   COMMENT ON COLUMN "AXIS"."VALORASINITRAMI"."NTRAMIT" IS 'Numero de tramitacion';
   COMMENT ON COLUMN "AXIS"."VALORASINITRAMI"."CGARANT" IS 'Codigo de garantia';
   COMMENT ON COLUMN "AXIS"."VALORASINITRAMI"."NVALORA" IS 'Id de la valoracion para cada garantia';
   COMMENT ON COLUMN "AXIS"."VALORASINITRAMI"."FVALORA" IS 'Fecha de valoracion';
   COMMENT ON COLUMN "AXIS"."VALORASINITRAMI"."IVALORA" IS 'Importe de valoracion';
   COMMENT ON COLUMN "AXIS"."VALORASINITRAMI"."FPERINI" IS 'Fecha inicio periodo de baja';
   COMMENT ON COLUMN "AXIS"."VALORASINITRAMI"."FPERFIN" IS 'Fecha fin periodo de baja';
   COMMENT ON TABLE "AXIS"."VALORASINITRAMI"  IS 'Valoraciones por garantia/tramitacion/siniestro';
  GRANT UPDATE ON "AXIS"."VALORASINITRAMI" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."VALORASINITRAMI" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."VALORASINITRAMI" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."VALORASINITRAMI" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."VALORASINITRAMI" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."VALORASINITRAMI" TO "PROGRAMADORESCSI";
