--------------------------------------------------------
--  DDL for Table VDETRECIBOS_MONPOL
--------------------------------------------------------

  CREATE TABLE "AXIS"."VDETRECIBOS_MONPOL" 
   (	"NRECIBO" NUMBER, 
	"IPRINET" NUMBER, 
	"IRECEXT" NUMBER, 
	"ICONSOR" NUMBER, 
	"IRECCON" NUMBER, 
	"IIPS" NUMBER, 
	"IDGS" NUMBER, 
	"IARBITR" NUMBER, 
	"IFNG" NUMBER, 
	"IRECFRA" NUMBER, 
	"IDTOTEC" NUMBER, 
	"IDTOCOM" NUMBER, 
	"ICOMBRU" NUMBER, 
	"ICOMRET" NUMBER, 
	"IDTOOM" NUMBER, 
	"IPRIDEV" NUMBER, 
	"ITOTPRI" NUMBER, 
	"ITOTDTO" NUMBER, 
	"ITOTCON" NUMBER, 
	"ITOTIMP" NUMBER, 
	"ITOTALR" NUMBER, 
	"IDERREG" NUMBER, 
	"ITOTREC" NUMBER, 
	"ICOMDEV" NUMBER, 
	"IRETDEV" NUMBER, 
	"ICEDNET" NUMBER, 
	"ICEDREX" NUMBER, 
	"ICEDCON" NUMBER, 
	"ICEDRCO" NUMBER, 
	"ICEDIPS" NUMBER, 
	"ICEDDGS" NUMBER, 
	"ICEDARB" NUMBER, 
	"ICEDFNG" NUMBER, 
	"ICEDRFR" NUMBER, 
	"ICEDDTE" NUMBER, 
	"ICEDDCO" NUMBER, 
	"ICEDCBR" NUMBER, 
	"ICEDCRT" NUMBER, 
	"ICEDDOM" NUMBER, 
	"ICEDPDV" NUMBER, 
	"ICEDREG" NUMBER, 
	"ICEDCDV" NUMBER, 
	"ICEDRDV" NUMBER, 
	"IT1PRI" NUMBER, 
	"IT1DTO" NUMBER, 
	"IT1CON" NUMBER, 
	"IT1IMP" NUMBER, 
	"IT1REC" NUMBER, 
	"IT1TOTR" NUMBER, 
	"IT2PRI" NUMBER, 
	"IT2DTO" NUMBER, 
	"IT2CON" NUMBER, 
	"IT2IMP" NUMBER, 
	"IT2REC" NUMBER, 
	"IT2TOTR" NUMBER, 
	"ICOMCIA" NUMBER, 
	"ICOMBRUI" NUMBER, 
	"ICOMRETI" NUMBER, 
	"ICOMDEVI" NUMBER, 
	"ICOMDRTI" NUMBER, 
	"ICOMBRUC" NUMBER, 
	"ICOMRETC" NUMBER, 
	"ICOMDEVC" NUMBER, 
	"ICOMDRTC" NUMBER, 
	"IOCOREC" NUMBER, 
	"IIMP_1" NUMBER, 
	"IIMP_2" NUMBER, 
	"IIMP_3" NUMBER, 
	"IIMP_4" NUMBER, 
	"ICONVOLEODUCTO" NUMBER(15,2), 
	"IIMP_5" NUMBER, 
	"IIMP_6" NUMBER, 
	"IIMP_7" NUMBER, 
	"IIMP_8" NUMBER, 
	"IIMP_9" NUMBER, 
	"IIMP_10" NUMBER, 
	"IIMP_11" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."NRECIBO" IS 'Número de recibo.';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IPRINET" IS 'Prima Neta';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IRECEXT" IS 'Recergo Externo';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."ICONSOR" IS 'Consorcio';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IRECCON" IS 'Recargo Consorcio';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IIPS" IS 'Impuesto IPS';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IDGS" IS 'Impuesto CLEA/DGS';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IARBITR" IS 'Arbitrios (bomberos, ...)';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IFNG" IS 'Impuesto FNG';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IRECFRA" IS 'Recargo Fraccionamiento';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IDTOTEC" IS 'Dto. Técnico';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IDTOCOM" IS 'Dto. Comercial';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."ICOMBRU" IS 'Comisión bruta';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."ICOMRET" IS 'Retención s/Comisión';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IDTOOM" IS 'Dto. Orden Ministerial';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IPRIDEV" IS 'Prima Devengada';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."ITOTPRI" IS 'Total Prima Neta';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."ITOTDTO" IS 'Total Descuentos';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."ITOTCON" IS 'Total Consorcio';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."ITOTIMP" IS 'Total Impuestos y Arbitrios';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."ITOTALR" IS 'TOTAL RECIBO';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."ICOMCIA" IS 'Importe de la comisión de la compañía';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IOCOREC" IS 'Importe otros conceptos recargo';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IIMP_1" IS 'Impuesto relacionado con el concepto 32';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IIMP_2" IS 'Impuesto relacionado con el concepto 40';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IIMP_3" IS 'Impuesto relacionado con el concepto 41';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IIMP_4" IS 'Impuesto relacionado con el concepto 42';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."ICONVOLEODUCTO" IS 'Importe sobrecomisiòn convenio';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IIMP_5" IS 'Importe IVA sobre comisi¿n - cedido';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IIMP_6" IS 'Importe Retenci¿n en la fuente sobre comisi¿n - cedido';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IIMP_7" IS 'Importe Retenci¿n por ICA sobre comisi¿n - cedido';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IIMP_8" IS 'Retenci¿n por IVA sobre comisi¿n - cedido';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IIMP_9" IS 'Retención en la fuente sobre comisión';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IIMP_10" IS 'Retención por IVA sobre comisión';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOS_MONPOL"."IIMP_11" IS 'Retención por ICA sobre comisión';
   COMMENT ON TABLE "AXIS"."VDETRECIBOS_MONPOL"  IS 'Contravalores de la tabla VDETRECIBOS en la moneda a nivel de póliza (por defecto será la de la empresa)';
  GRANT UPDATE ON "AXIS"."VDETRECIBOS_MONPOL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."VDETRECIBOS_MONPOL" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."VDETRECIBOS_MONPOL" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."VDETRECIBOS_MONPOL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."VDETRECIBOS_MONPOL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."VDETRECIBOS_MONPOL" TO "PROGRAMADORESCSI";
