--------------------------------------------------------
--  DDL for Table VDETRECIBOSCAR
--------------------------------------------------------

  CREATE TABLE "AXIS"."VDETRECIBOSCAR" 
   (	"SPROCES" NUMBER, 
	"NRECIBO" NUMBER, 
	"IPRINET" NUMBER, 
	"IRECEXT" NUMBER, 
	"ICONSOR" NUMBER, 
	"IRECCON" NUMBER, 
	"IIPS" NUMBER, 
	"IDGS" NUMBER, 
	"IARBITR" NUMBER, 
	"IFNG" NUMBER, 
	"IRECFRA" NUMBER, 
	"IDTOTEC" NUMBER, 
	"IDTOCOM" NUMBER, 
	"ICOMBRU" NUMBER, 
	"ICOMRET" NUMBER, 
	"IDTOOM" NUMBER, 
	"IPRIDEV" NUMBER, 
	"ITOTPRI" NUMBER, 
	"ITOTDTO" NUMBER, 
	"ITOTCON" NUMBER, 
	"ITOTIMP" NUMBER, 
	"ITOTALR" NUMBER, 
	"IDERREG" NUMBER, 
	"ITOTREC" NUMBER, 
	"ICOMDEV" NUMBER, 
	"IRETDEV" NUMBER, 
	"ICEDNET" NUMBER, 
	"ICEDREX" NUMBER, 
	"ICEDCON" NUMBER, 
	"ICEDRCO" NUMBER, 
	"ICEDIPS" NUMBER, 
	"ICEDDGS" NUMBER, 
	"ICEDARB" NUMBER, 
	"ICEDFNG" NUMBER, 
	"ICEDRFR" NUMBER, 
	"ICEDDTE" NUMBER, 
	"ICEDDCO" NUMBER, 
	"ICEDCBR" NUMBER, 
	"ICEDCRT" NUMBER, 
	"ICEDDOM" NUMBER, 
	"ICEDPDV" NUMBER, 
	"ICEDREG" NUMBER, 
	"ICEDCDV" NUMBER, 
	"ICEDRDV" NUMBER, 
	"IT1PRI" NUMBER, 
	"IT1DTO" NUMBER, 
	"IT1CON" NUMBER, 
	"IT1IMP" NUMBER, 
	"IT1REC" NUMBER, 
	"IT1TOTR" NUMBER, 
	"IT2PRI" NUMBER, 
	"IT2DTO" NUMBER, 
	"IT2CON" NUMBER, 
	"IT2IMP" NUMBER, 
	"IT2REC" NUMBER, 
	"IT2TOTR" NUMBER, 
	"ICOMCIA" NUMBER, 
	"ICOMBRUI" NUMBER, 
	"ICOMRETI" NUMBER, 
	"ICOMDEVI" NUMBER, 
	"ICOMDRTI" NUMBER, 
	"ICOMBRUC" NUMBER, 
	"ICOMRETC" NUMBER, 
	"ICOMDEVC" NUMBER, 
	"ICOMDRTC" NUMBER, 
	"IOCOREC" NUMBER, 
	"IIMP_1" NUMBER, 
	"IIMP_2" NUMBER, 
	"IIMP_3" NUMBER, 
	"IIMP_4" NUMBER, 
	"ICONVOLEODUCTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."VDETRECIBOSCAR"."ICOMCIA" IS 'Import de la comissió de la compañía';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOSCAR"."IOCOREC" IS 'Importe otros conceptos recargo';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOSCAR"."IIMP_1" IS 'Impuesto relacionado con el concepto 32';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOSCAR"."IIMP_2" IS 'Impuesto relacionado con el concepto 40';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOSCAR"."IIMP_3" IS 'Impuesto relacionado con el concepto 41';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOSCAR"."IIMP_4" IS 'Impuesto relacionado con el concepto 42';
   COMMENT ON COLUMN "AXIS"."VDETRECIBOSCAR"."ICONVOLEODUCTO" IS 'Importe sobrecomisión convenio';
  GRANT SELECT ON "AXIS"."VDETRECIBOSCAR" TO "PROGRAMADORESCSI";
  GRANT SELECT ON "AXIS"."VDETRECIBOSCAR" TO "CONF_DWH";
  GRANT UPDATE ON "AXIS"."VDETRECIBOSCAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."VDETRECIBOSCAR" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."VDETRECIBOSCAR" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."VDETRECIBOSCAR" TO "R_AXIS";
