--------------------------------------------------------
--  DDL for Table VINCULACIONES_PROD
--------------------------------------------------------

  CREATE TABLE "AXIS"."VINCULACIONES_PROD" 
   (	"CVINCLO" NUMBER(4,0), 
	"CRAMO" NUMBER(8,0), 
	"CMODALI" NUMBER(2,0), 
	"CTIPSEG" NUMBER(2,0), 
	"CCOLECT" NUMBER(2,0), 
	"CACTIVI" NUMBER(4,0), 
	"CGARANT" NUMBER(4,0), 
	"TIPO_DESCUENTO" NUMBER(3,0), 
	"DESCUENTO" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;
  GRANT UPDATE ON "AXIS"."VINCULACIONES_PROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."VINCULACIONES_PROD" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."VINCULACIONES_PROD" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."VINCULACIONES_PROD" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."VINCULACIONES_PROD" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."VINCULACIONES_PROD" TO "PROGRAMADORESCSI";
