--------------------------------------------------------
--  DDL for Table VINCULOS
--------------------------------------------------------

  CREATE TABLE "AXIS"."VINCULOS" 
   (	"CIDIOMA" NUMBER(2,0), 
	"CVINCLO" NUMBER(4,0), 
	"TVINCLO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."VINCULOS"."CIDIOMA" IS 'Código de Idioma';
   COMMENT ON COLUMN "AXIS"."VINCULOS"."CVINCLO" IS 'Código vínculo';
   COMMENT ON COLUMN "AXIS"."VINCULOS"."TVINCLO" IS 'Descripción del vínculo';
  GRANT UPDATE ON "AXIS"."VINCULOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."VINCULOS" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."VINCULOS" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."VINCULOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."VINCULOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."VINCULOS" TO "PROGRAMADORESCSI";
