--------------------------------------------------------
--  DDL for Table WEB_TOKEN
--------------------------------------------------------

  CREATE TABLE "AXIS"."WEB_TOKEN" 
   (	"TTOKEN" VARCHAR2(3000 BYTE), 
	"FALTA" DATE, 
	"FMODIF" DATE, 
	"TCONCEPTO" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "AXIS" ;

   COMMENT ON COLUMN "AXIS"."WEB_TOKEN"."TTOKEN" IS 'Identificador del token';
   COMMENT ON COLUMN "AXIS"."WEB_TOKEN"."FALTA" IS 'Fecha de creación';
   COMMENT ON COLUMN "AXIS"."WEB_TOKEN"."FMODIF" IS 'Fecha de modificación';
   COMMENT ON COLUMN "AXIS"."WEB_TOKEN"."TCONCEPTO" IS 'Concepto';
   COMMENT ON TABLE "AXIS"."WEB_TOKEN"  IS 'Tabla con los token';
  GRANT UPDATE ON "AXIS"."WEB_TOKEN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."WEB_TOKEN" TO "R_AXIS";
  GRANT INSERT ON "AXIS"."WEB_TOKEN" TO "R_AXIS";
  GRANT DELETE ON "AXIS"."WEB_TOKEN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."WEB_TOKEN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."WEB_TOKEN" TO "PROGRAMADORESCSI";
