/* Inserción literal para lista desplegable */
INSERT INTO AXIS_CODLITERALES (SLITERA,CLITERA) values (997,3);
INSERT INTO axis_literales (cidioma, slitera, tlitera) VALUES (1, 997, 'Formato USF');
INSERT INTO axis_literales (cidioma, slitera, tlitera) VALUES (2, 997, 'Formato USF');
INSERT INTO axis_literales (cidioma, slitera, tlitera) VALUES (8, 997, 'Formato USF');

Insert into CFG_LANZAR_INFORMES (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,SLITERA,LPARAMS,GENERA_REPORT,CCFGFORM,LEXPORT,CTIPO,CGENREC,CAREA) 
values (24,'AXISLIST003','Formato_USF_','GENERAL',0,997,null,1,'GENERAL','PDF',1,0,2);

Insert into CFG_LANZAR_INFORMES_PARAMS (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,CCFGFORM,TPARAM,NORDER,SLITERA,CTIPO,NOTNULL,LVALOR) 
values (24,'AXISLIST003','Formato_USF_','GENERAL',0,'GENERAL','PNSOLICI',1,9000875,1,1,null);
Insert into CFG_LANZAR_INFORMES_PARAMS (CEMPRES,CFORM,CMAP,TEVENTO,SPRODUC,CCFGFORM,TPARAM,NORDER,SLITERA,CTIPO,NOTNULL,LVALOR) 
values (24,'AXISLIST003','Formato_USF_','GENERAL',0,'GENERAL','PNMOVIMI',2,9001954,1,1,null);

Insert into DET_LANZAR_INFORMES (CEMPRES,CMAP,CIDIOMA,TDESCRIP,CINFORME)
values (24,'Formato_USF_',1,'Formato USF','CONF_USF.jasper');
Insert into DET_LANZAR_INFORMES (CEMPRES,CMAP,CIDIOMA,TDESCRIP,CINFORME)
values (24,'Formato_USF_',2,'Formato USF','CONF_USF.jasper');
Insert into DET_LANZAR_INFORMES (CEMPRES,CMAP,CIDIOMA,TDESCRIP,CINFORME)
values (24,'Formato_USF_',8,'Formato USF','CONF_USF.jasper');

COMMIT;
/
