ALTER TABLE fin_indicadores
ADD (
  TCONCEPC_TMP CLOB,
  TCONCEPS_TMP CLOB,
  TCBUREA_TMP CLOB,
  TCOTROS_TMP CLOB
);

UPDATE fin_indicadores fin 
SET TCONCEPC_TMP=TCONCEPC,
  TCONCEPS_TMP=TCONCEPS,
  TCBUREA_TMP=TCBUREA,
  TCOTROS_TMP=TCOTROS;
  
COMMIT;

ALTER TABLE fin_indicadores DROP (
TCONCEPC,TCONCEPS,TCBUREA,TCOTROS);

ALTER TABLE fin_indicadores RENAME COLUMN TCONCEPC_TMP TO TCONCEPC;
ALTER TABLE fin_indicadores RENAME COLUMN TCONCEPS_TMP TO TCONCEPS;
ALTER TABLE fin_indicadores RENAME COLUMN TCBUREA_TMP TO TCBUREA;
ALTER TABLE fin_indicadores RENAME COLUMN TCOTROS_TMP TO TCOTROS;

COMMIT;
