--------------------------------------------------------
--  DDL for Sequence CODDEPOSITARIAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."CODDEPOSITARIAS_SEQ"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."CODDEPOSITARIAS_SEQ" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."CODDEPOSITARIAS_SEQ" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."CODDEPOSITARIAS_SEQ" TO "PROGRAMADORESCSI";
