--------------------------------------------------------
--  DDL for Sequence EXTILT02_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."EXTILT02_SEQ"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 0 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."EXTILT02_SEQ" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."EXTILT02_SEQ" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."EXTILT02_SEQ" TO "PROGRAMADORESCSI";
