--------------------------------------------------------
--  DDL for Sequence GCA_SALFAVCLI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."GCA_SALFAVCLI_SEQ"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 40 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."GCA_SALFAVCLI_SEQ" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."GCA_SALFAVCLI_SEQ" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."GCA_SALFAVCLI_SEQ" TO "PROGRAMADORESCSI";
