--------------------------------------------------------
--  DDL for Sequence PAR_CONDS_REGLAS
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."PAR_CONDS_REGLAS"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."PAR_CONDS_REGLAS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."PAR_CONDS_REGLAS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."PAR_CONDS_REGLAS" TO "PROGRAMADORESCSI";
