--------------------------------------------------------
--  DDL for Sequence S_FSTML_DATOS
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."S_FSTML_DATOS"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."S_FSTML_DATOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."S_FSTML_DATOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."S_FSTML_DATOS" TO "PROGRAMADORESCSI";
