--------------------------------------------------------
--  DDL for Sequence SAGENDA
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SAGENDA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 6308 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SAGENDA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SAGENDA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SAGENDA" TO "PROGRAMADORESCSI";
