--------------------------------------------------------
--  DDL for Sequence SCARAGR
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SCARAGR"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 6335 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SCARAGR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SCARAGR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SCARAGR" TO "PROGRAMADORESCSI";
