--------------------------------------------------------
--  DDL for Sequence SCLAGEN
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SCLAGEN"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 8013 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SCLAGEN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SCLAGEN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SCLAGEN" TO "PROGRAMADORESCSI";
