--------------------------------------------------------
--  DDL for Sequence SCLABEN
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SCLABEN"  MINVALUE 13 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 8000 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SCLABEN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SCLABEN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SCLABEN" TO "PROGRAMADORESCSI";
