--------------------------------------------------------
--  DDL for Sequence SCOMREA
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SCOMREA"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 800003 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SCOMREA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SCOMREA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SCOMREA" TO "PROGRAMADORESCSI";
