--------------------------------------------------------
--  DDL for Sequence SCTAPRES
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SCTAPRES"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 717 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SCTAPRES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SCTAPRES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SCTAPRES" TO "PROGRAMADORESCSI";
