--------------------------------------------------------
--  DDL for Sequence SCUMULO
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SCUMULO"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1772 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SCUMULO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SCUMULO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SCUMULO" TO "PROGRAMADORESCSI";
