--------------------------------------------------------
--  DDL for Sequence SDETALLE_LCOL
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SDETALLE_LCOL"  MINVALUE 0 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 4000856802 NOCACHE  NOORDER  CYCLE   ;
  GRANT SELECT ON "AXIS"."SDETALLE_LCOL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SDETALLE_LCOL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SDETALLE_LCOL" TO "PROGRAMADORESCSI";
