--------------------------------------------------------
--  DDL for Sequence SEQ_MANDATOS
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SEQ_MANDATOS"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SEQ_MANDATOS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEQ_MANDATOS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEQ_MANDATOS" TO "PROGRAMADORESCSI";
