--------------------------------------------------------
--  DDL for Sequence SEQ_CONT_ALN_01
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SEQ_CONT_ALN_01"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 100000000 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SEQ_CONT_ALN_01" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEQ_CONT_ALN_01" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEQ_CONT_ALN_01" TO "PROGRAMADORESCSI";
