--------------------------------------------------------
--  DDL for Sequence SEQ_CONT_07
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SEQ_CONT_07"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 700000000 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SEQ_CONT_07" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEQ_CONT_07" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEQ_CONT_07" TO "PROGRAMADORESCSI";
