--------------------------------------------------------
--  DDL for Sequence SEQ_DOMI_SEPA_PAGO_DETALLE
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SEQ_DOMI_SEPA_PAGO_DETALLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 100 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SEQ_DOMI_SEPA_PAGO_DETALLE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEQ_DOMI_SEPA_PAGO_DETALLE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEQ_DOMI_SEPA_PAGO_DETALLE" TO "PROGRAMADORESCSI";
