--------------------------------------------------------
--  DDL for Sequence SEQ_BUREAU
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SEQ_BUREAU"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 648 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SEQ_BUREAU" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEQ_BUREAU" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEQ_BUREAU" TO "PROGRAMADORESCSI";
