--------------------------------------------------------
--  DDL for Sequence SEQ_DOMI_SEPA
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SEQ_DOMI_SEPA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 100 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SEQ_DOMI_SEPA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEQ_DOMI_SEPA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEQ_DOMI_SEPA" TO "PROGRAMADORESCSI";
