--------------------------------------------------------
--  DDL for Sequence SEQ_COMCONVENIOS_SCOMCONV
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SEQ_COMCONVENIOS_SCOMCONV"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SEQ_COMCONVENIOS_SCOMCONV" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEQ_COMCONVENIOS_SCOMCONV" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEQ_COMCONVENIOS_SCOMCONV" TO "PROGRAMADORESCSI";
