--------------------------------------------------------
--  DDL for Sequence SEQ_CONS_JREPS
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SEQ_CONS_JREPS"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SEQ_CONS_JREPS" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEQ_CONS_JREPS" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEQ_CONS_JREPS" TO "PROGRAMADORESCSI";
