--------------------------------------------------------
--  DDL for Sequence SEQ_SREFEXT
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SEQ_SREFEXT"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SEQ_SREFEXT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEQ_SREFEXT" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEQ_SREFEXT" TO "PROGRAMADORESCSI";
