--------------------------------------------------------
--  DDL for Sequence SEQ_SSTDC234OUT
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SEQ_SSTDC234OUT"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SEQ_SSTDC234OUT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEQ_SSTDC234OUT" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEQ_SSTDC234OUT" TO "PROGRAMADORESCSI";
