--------------------------------------------------------
--  DDL for Sequence SEQLOGCORREO
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SEQLOGCORREO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 37 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SEQLOGCORREO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEQLOGCORREO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEQLOGCORREO" TO "PROGRAMADORESCSI";
