--------------------------------------------------------
--  DDL for Sequence SEQMOVECASH
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SEQMOVECASH"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1001 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SEQMOVECASH" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEQMOVECASH" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEQMOVECASH" TO "PROGRAMADORESCSI";
