--------------------------------------------------------
--  DDL for Sequence SEXTMOVREC
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SEXTMOVREC"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 0 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SEXTMOVREC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SEXTMOVREC" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SEXTMOVREC" TO "PROGRAMADORESCSI";
