--------------------------------------------------------
--  DDL for Sequence SFICPROCES
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SFICPROCES"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SFICPROCES" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SFICPROCES" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SFICPROCES" TO "PROGRAMADORESCSI";
