--------------------------------------------------------
--  DDL for Sequence SGESTIO
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SGESTIO"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 344 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SGESTIO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SGESTIO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SGESTIO" TO "PROGRAMADORESCSI";
