--------------------------------------------------------
--  DDL for Sequence SHISDOMICILIACIONES_CAB
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SHISDOMICILIACIONES_CAB"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 870 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SHISDOMICILIACIONES_CAB" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SHISDOMICILIACIONES_CAB" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SHISDOMICILIACIONES_CAB" TO "PROGRAMADORESCSI";
