--------------------------------------------------------
--  DDL for Sequence SHISDETR
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SHISDETR"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SHISDETR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SHISDETR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SHISDETR" TO "PROGRAMADORESCSI";
