--------------------------------------------------------
--  DDL for Sequence SHISVIN
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SHISVIN"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SHISVIN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SHISVIN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SHISVIN" TO "PROGRAMADORESCSI";
