--------------------------------------------------------
--  DDL for Sequence SIDCTTO_TRAMO_PRODUCTO
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SIDCTTO_TRAMO_PRODUCTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SIDCTTO_TRAMO_PRODUCTO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIDCTTO_TRAMO_PRODUCTO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIDCTTO_TRAMO_PRODUCTO" TO "PROGRAMADORESCSI";
