--------------------------------------------------------
--  DDL for Sequence SIDPORCEN_TRAMO_CTTO
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SIDPORCEN_TRAMO_CTTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SIDPORCEN_TRAMO_CTTO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIDPORCEN_TRAMO_CTTO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIDPORCEN_TRAMO_CTTO" TO "PROGRAMADORESCSI";
