--------------------------------------------------------
--  DDL for Sequence SIDTRAMO_SIN_BONO
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SIDTRAMO_SIN_BONO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SIDTRAMO_SIN_BONO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIDTRAMO_SIN_BONO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIDTRAMO_SIN_BONO" TO "PROGRAMADORESCSI";
