--------------------------------------------------------
--  DDL for Sequence SIDVERSION
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SIDVERSION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SIDVERSION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIDVERSION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIDVERSION" TO "PROGRAMADORESCSI";
