--------------------------------------------------------
--  DDL for Sequence SIDVERSGAR
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SIDVERSGAR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SIDVERSGAR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SIDVERSGAR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SIDVERSGAR" TO "PROGRAMADORESCSI";
