--------------------------------------------------------
--  DDL for Sequence SMANCONT
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SMANCONT"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2993 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SMANCONT" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SMANCONT" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SMANCONT" TO "PROGRAMADORESCSI";
