--------------------------------------------------------
--  DDL for Sequence SMODCON
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SMODCON"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 800003 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SMODCON" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SMODCON" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SMODCON" TO "PROGRAMADORESCSI";
