--------------------------------------------------------
--  DDL for Sequence SMOVCOA
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SMOVCOA"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 18050 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SMOVCOA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SMOVCOA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SMOVCOA" TO "PROGRAMADORESCSI";
