--------------------------------------------------------
--  DDL for Sequence SMOVPAGCOA
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SMOVPAGCOA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 124 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SMOVPAGCOA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SMOVPAGCOA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SMOVPAGCOA" TO "PROGRAMADORESCSI";
