--------------------------------------------------------
--  DDL for Sequence SMOVPAGREA
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SMOVPAGREA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SMOVPAGREA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SMOVPAGREA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SMOVPAGREA" TO "PROGRAMADORESCSI";
