--------------------------------------------------------
--  DDL for Sequence SNCARGA
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SNCARGA"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 17442 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SNCARGA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SNCARGA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SNCARGA" TO "PROGRAMADORESCSI";
