--------------------------------------------------------
--  DDL for Sequence SNIP
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SNIP"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 36284 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SNIP" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SNIP" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SNIP" TO "PROGRAMADORESCSI";
