--------------------------------------------------------
--  DDL for Sequence SPAGCOA
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SPAGCOA"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 141 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SPAGCOA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SPAGCOA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SPAGCOA" TO "PROGRAMADORESCSI";
