--------------------------------------------------------
--  DDL for Sequence SPRESTAPLAN
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SPRESTAPLAN"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SPRESTAPLAN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SPRESTAPLAN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SPRESTAPLAN" TO "PROGRAMADORESCSI";
