--------------------------------------------------------
--  DDL for Sequence SRASTRO
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SRASTRO"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1964948 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SRASTRO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SRASTRO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SRASTRO" TO "PROGRAMADORESCSI";
