--------------------------------------------------------
--  DDL for Sequence SRECREN
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SRECREN"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SRECREN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SRECREN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SRECREN" TO "PROGRAMADORESCSI";
