--------------------------------------------------------
--  DDL for Sequence SREMCANAL
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SREMCANAL"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 32 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SREMCANAL" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SREMCANAL" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SREMCANAL" TO "PROGRAMADORESCSI";
