--------------------------------------------------------
--  DDL for Sequence SREMESA
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SREMESA"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SREMESA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SREMESA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SREMESA" TO "PROGRAMADORESCSI";
