--------------------------------------------------------
--  DDL for Sequence SREMESA_PREVIO_LRE
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SREMESA_PREVIO_LRE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SREMESA_PREVIO_LRE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SREMESA_PREVIO_LRE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SREMESA_PREVIO_LRE" TO "PROGRAMADORESCSI";
