--------------------------------------------------------
--  DDL for Sequence SSACTIVO
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SSACTIVO"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SSACTIVO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SSACTIVO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SSACTIVO" TO "PROGRAMADORESCSI";
