--------------------------------------------------------
--  DDL for Sequence SSDTEXTOLIBRE
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SSDTEXTOLIBRE"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SSDTEXTOLIBRE" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SSDTEXTOLIBRE" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SSDTEXTOLIBRE" TO "PROGRAMADORESCSI";
