--------------------------------------------------------
--  DDL for Sequence SSEQLOGMIG2
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SSEQLOGMIG2"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2950427 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SSEQLOGMIG2" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SSEQLOGMIG2" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SSEQLOGMIG2" TO "PROGRAMADORESCSI";
