--------------------------------------------------------
--  DDL for Sequence SSEQLOGMIG
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SSEQLOGMIG"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 204253 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SSEQLOGMIG" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SSEQLOGMIG" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SSEQLOGMIG" TO "PROGRAMADORESCSI";
