--------------------------------------------------------
--  DDL for Sequence SSIMULA
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SSIMULA"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SSIMULA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SSIMULA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SSIMULA" TO "PROGRAMADORESCSI";
