--------------------------------------------------------
--  DDL for Sequence STALONA
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."STALONA"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 0 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."STALONA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."STALONA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."STALONA" TO "PROGRAMADORESCSI";
