--------------------------------------------------------
--  DDL for Sequence STMPPAGREN
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."STMPPAGREN"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 344 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."STMPPAGREN" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."STMPPAGREN" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."STMPPAGREN" TO "PROGRAMADORESCSI";
