--------------------------------------------------------
--  DDL for Sequence STMPCASER_CORR
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."STMPCASER_CORR"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 0 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."STMPCASER_CORR" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."STMPCASER_CORR" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."STMPCASER_CORR" TO "PROGRAMADORESCSI";
