--------------------------------------------------------
--  DDL for Sequence STMPPER1
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."STMPPER1"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 0 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."STMPPER1" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."STMPPER1" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."STMPPER1" TO "PROGRAMADORESCSI";
