--------------------------------------------------------
--  DDL for Sequence SVEHICULO
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SVEHICULO"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SVEHICULO" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SVEHICULO" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SVEHICULO" TO "PROGRAMADORESCSI";
