--------------------------------------------------------
--  DDL for Sequence SVERSION
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SVERSION"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SVERSION" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SVERSION" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SVERSION" TO "PROGRAMADORESCSI";
