--------------------------------------------------------
--  DDL for Sequence SVISITA
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."SVISITA"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 0 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."SVISITA" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."SVISITA" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."SVISITA" TO "PROGRAMADORESCSI";
