--------------------------------------------------------
--  DDL for Sequence UNICUENTA_SEC
--------------------------------------------------------

   CREATE SEQUENCE  "AXIS"."UNICUENTA_SEC"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 0 NOCACHE  NOORDER  NOCYCLE   ;
  GRANT SELECT ON "AXIS"."UNICUENTA_SEC" TO "R_AXIS";
  GRANT SELECT ON "AXIS"."UNICUENTA_SEC" TO "CONF_DWH";
  GRANT SELECT ON "AXIS"."UNICUENTA_SEC" TO "PROGRAMADORESCSI";
