-- Unable to render TYPE DDL for object AXIS.SYS_PLSQL_652D2CF4_DUMMY_1 with DBMS_METADATA attempting internal generator.
CREATE TYPE        AXIS.SYS_PLSQL_652D2CF4_DUMMY_1 as table of number;
  GRANT EXECUTE ON "AXIS"."SYS_PLSQL_652D2CF4_DUMMY_1" TO "PROGRAMADORESCSI";
  GRANT EXECUTE ON "AXIS"."SYS_PLSQL_652D2CF4_DUMMY_1" TO "R_AXIS";
