--------------------------------------------------------
--  DDL for Type T_IAX_TARIFICABENEFICIARIOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_TARIFICABENEFICIARIOS" AS TABLE OF ob_iax_tarificabeneficiario;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_TARIFICABENEFICIARIOS" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_TARIFICABENEFICIARIOS" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_TARIFICABENEFICIARIOS" TO "PROGRAMADORESCSI";
