--------------------------------------------------------
--  DDL for Type T_IAX_PRODPREGUNTAS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_PRODPREGUNTAS" AS TABLE OF OB_IAX_PRODPREGUNTAS;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_PRODPREGUNTAS" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_PRODPREGUNTAS" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_PRODPREGUNTAS" TO "PROGRAMADORESCSI";
