--------------------------------------------------------
--  DDL for Type T_IAX_PRODGARANTIAS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_PRODGARANTIAS" AS TABLE OF OB_IAX_PRODGARANTIAS;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_PRODGARANTIAS" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_PRODGARANTIAS" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_PRODGARANTIAS" TO "PROGRAMADORESCSI";
