--------------------------------------------------------
--  DDL for Type T_IAX_PRODGARANPROCAP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_PRODGARANPROCAP" AS TABLE OF OB_IAX_PRODGARANPROCAP;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_PRODGARANPROCAP" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_PRODGARANPROCAP" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_PRODGARANPROCAP" TO "PROGRAMADORESCSI";
