--------------------------------------------------------
--  DDL for Type T_IAXPAR_GARANPROCAP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAXPAR_GARANPROCAP" AS TABLE OF OB_IAXPAR_GARANPROCAP;

/

  GRANT EXECUTE ON "AXIS"."T_IAXPAR_GARANPROCAP" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAXPAR_GARANPROCAP" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAXPAR_GARANPROCAP" TO "PROGRAMADORESCSI";
