--------------------------------------------------------
--  DDL for Type T_IAX_PRODDURPERIODO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_PRODDURPERIODO" AS TABLE OF OB_IAX_PRODDURPERIODO;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_PRODDURPERIODO" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_PRODDURPERIODO" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_PRODDURPERIODO" TO "PROGRAMADORESCSI";
