--------------------------------------------------------
--  DDL for Type T_IAX_INTERTECPROD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_INTERTECPROD" AS TABLE OF OB_IAX_INTERTECPROD;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_INTERTECPROD" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_INTERTECPROD" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_INTERTECPROD" TO "PROGRAMADORESCSI";
