--------------------------------------------------------
--  DDL for Type T_IAX_SIN_T_VALPRETENSION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_SIN_T_VALPRETENSION" AS TABLE OF OB_IAX_SIN_T_VALPRETENSION;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_SIN_T_VALPRETENSION" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_SIN_T_VALPRETENSION" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_SIN_T_VALPRETENSION" TO "PROGRAMADORESCSI";
