--------------------------------------------------------
--  DDL for Type T_IAX_PRODCUMGARAN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_PRODCUMGARAN" AS TABLE OF OB_IAX_PRODCUMGARAN;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_PRODCUMGARAN" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_PRODCUMGARAN" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_PRODCUMGARAN" TO "PROGRAMADORESCSI";
