--------------------------------------------------------
--  DDL for Type T_IAX_DETMOVSEGURO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_DETMOVSEGURO" AS TABLE OF OB_IAX_DETMOVSEGURO;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_DETMOVSEGURO" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_DETMOVSEGURO" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_DETMOVSEGURO" TO "PROGRAMADORESCSI";
