--------------------------------------------------------
--  DDL for Type T_IAX_DIR_CODPOSTALES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_DIR_CODPOSTALES" AS TABLE OF OB_IAX_DIR_CODPOSTALES;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_DIR_CODPOSTALES" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_DIR_CODPOSTALES" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_DIR_CODPOSTALES" TO "PROGRAMADORESCSI";
