--------------------------------------------------------
--  DDL for Type T_IAX_AUTDISPOSITIVOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_AUTDISPOSITIVOS" AS TABLE OF OB_IAX_AUTDISPOSITIVOS

/

  GRANT EXECUTE ON "AXIS"."T_IAX_AUTDISPOSITIVOS" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_AUTDISPOSITIVOS" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_AUTDISPOSITIVOS" TO "PROGRAMADORESCSI";
