--------------------------------------------------------
--  DDL for Type T_IAX_SIN_TRAMITA_MOVGESTION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_SIN_TRAMITA_MOVGESTION" AS TABLE OF ob_iax_sin_tramita_movgestion;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_SIN_TRAMITA_MOVGESTION" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_SIN_TRAMITA_MOVGESTION" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_SIN_TRAMITA_MOVGESTION" TO "PROGRAMADORESCSI";
