--------------------------------------------------------
--  DDL for Type T_IAX_SIN_TRAMITA_JUDICIAL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_SIN_TRAMITA_JUDICIAL" AS TABLE OF OB_IAX_SIN_TRAMITA_JUDICIAL;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_SIN_TRAMITA_JUDICIAL" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_SIN_TRAMITA_JUDICIAL" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_SIN_TRAMITA_JUDICIAL" TO "PROGRAMADORESCSI";
