--------------------------------------------------------
--  DDL for Type T_IAX_DIR_PORTALESDIRECCIONES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_DIR_PORTALESDIRECCIONES" AS TABLE OF ob_iax_dir_portalesdirecciones;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_DIR_PORTALESDIRECCIONES" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_DIR_PORTALESDIRECCIONES" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_DIR_PORTALESDIRECCIONES" TO "PROGRAMADORESCSI";
