--------------------------------------------------------
--  DDL for Type T_IAX_REDCOMERCIAL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_REDCOMERCIAL" AS TABLE OF OB_IAX_REDCOMERCIAL;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_REDCOMERCIAL" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_REDCOMERCIAL" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_REDCOMERCIAL" TO "PROGRAMADORESCSI";
