--------------------------------------------------------
--  DDL for Type T_IAX_PER_DIRECCIONES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AXIS"."T_IAX_PER_DIRECCIONES" AS TABLE OF OB_IAX_PER_DIRECCIONES;

/

  GRANT EXECUTE ON "AXIS"."T_IAX_PER_DIRECCIONES" TO "R_AXIS";
  GRANT EXECUTE ON "AXIS"."T_IAX_PER_DIRECCIONES" TO "CONF_DWH";
  GRANT EXECUTE ON "AXIS"."T_IAX_PER_DIRECCIONES" TO "PROGRAMADORESCSI";
