UPDATE AGD_GRUPOS SET TDESC='Área de Reclamos' where cgrupo='SI00' and cidioma=8 and cempres=24;
delete from AGD_GRUPOS where CEMPRES='24' and CGRUPO='JU00' and CIDIOMA='8' and CSUBGRUP='JU00';
INSERT INTO "AGD_GRUPOS" (CEMPRES, CGRUPO, CIDIOMA, TDESC, CSUBGRUP) VALUES ('24', 'JU00', '8', 'Área de Procesos Judiciales', 'JU00');

DELETE FROM AGD_GRUPOS WHERE CEMPRES=24 AND CGRUPO='TODOS' AND CIDIOMA=8 AND TDESC='TODOS';
Insert into AGD_GRUPOS (CEMPRES,CGRUPO,CIDIOMA,TDESC,TMAIL,CSUBGRUP) values (24,'TODOS',8,'TODOS',null,'TODOS');
delete from usuarios where cusuari in ('CARODRIGUEZ','EPEREZC','PVANEGAS');
Insert into USUARIOS (CUSUARI,CIDIOMA,CEMPRES,TUSUNOM,TPCPATH,CDELEGA,CPROVIN,CPOBLAC,CVISTAS,CWEB,REPSERVER,EJECUCION,SPERSON,FBAJA,CTIPUSU,CAGECOB,COPCION,TPWD,FALTA,CUSUBBDD,CAUTLOG,CEMPLEADO,CTERMINAL,CUSUBAJA,CTERMFISIC,CISLOGGED,FLOGIN,CNSESIONES,CVISPUBLI,CBLOQUEO,FBLOQUEO,MAIL_USU,TELFUSU,UNIDEPT,CATEGPROF,NDEBUG) values ('CARODRIGUEZ',8,24,'CARLOS DANIEL RODRIGUEZ','C:/',19000,null,null,null,null,null,0,4056447,null,2,null,0,'744A7ED212D68DA658C114F0AE61DA6603BE1C8DC52B2FB413B2D12B909E7097',to_date('19-DEC-19','DD-MON-RR'),null,null,null,null,null,null,0,null,0,1,null,null,'carodriguez@confianza.com.co',null,null,null,1);
Insert into USUARIOS (CUSUARI,CIDIOMA,CEMPRES,TUSUNOM,TPCPATH,CDELEGA,CPROVIN,CPOBLAC,CVISTAS,CWEB,REPSERVER,EJECUCION,SPERSON,FBAJA,CTIPUSU,CAGECOB,COPCION,TPWD,FALTA,CUSUBBDD,CAUTLOG,CEMPLEADO,CTERMINAL,CUSUBAJA,CTERMFISIC,CISLOGGED,FLOGIN,CNSESIONES,CVISPUBLI,CBLOQUEO,FBLOQUEO,MAIL_USU,TELFUSU,UNIDEPT,CATEGPROF,NDEBUG) values ('EPEREZC',8,24,'ELIZABETH PEREZ','C:/',19000,null,null,null,null,null,0,4056448,null,2,null,0,'3DE5FA3503160CFA771D4C6FE9AAC52529F676266C8E9885639DF06DF42B7E9A',to_date('19-DEC-19','DD-MON-RR'),null,null,null,null,null,null,0,null,0,1,null,null,'eperezc@confianza.com.co',null,null,null,1);
Insert into USUARIOS (CUSUARI,CIDIOMA,CEMPRES,TUSUNOM,TPCPATH,CDELEGA,CPROVIN,CPOBLAC,CVISTAS,CWEB,REPSERVER,EJECUCION,SPERSON,FBAJA,CTIPUSU,CAGECOB,COPCION,TPWD,FALTA,CUSUBBDD,CAUTLOG,CEMPLEADO,CTERMINAL,CUSUBAJA,CTERMFISIC,CISLOGGED,FLOGIN,CNSESIONES,CVISPUBLI,CBLOQUEO,FBLOQUEO,MAIL_USU,TELFUSU,UNIDEPT,CATEGPROF,NDEBUG) values ('PVANEGAS',8,24,'SILVANA VANEGAS','C:/',19000,null,null,null,null,null,0,4056444,null,2,null,0,'1C5F1C3E442CE7DF5C9001BE4C6004A16709F0A08C00F5898EDF5393A894C175',to_date('19-DEC-19','DD-MON-RR'),null,null,null,null,null,null,0,null,0,1,null,null,'anderlike2@hotmail.com',null,null,null,1);


UPDATE SIN_CODTRAMITADOR SET  CUSUARI = 'GNAVAS' WHERE CTRAMITAD = 'T507';
UPDATE SIN_CODTRAMITADOR SET  CUSUARI = 'JMENDOZA' WHERE CTRAMITAD = 'T502';
UPDATE SIN_CODTRAMITADOR SET  CUSUARI = 'JVISBAL' WHERE CTRAMITAD = 'T804';
UPDATE SIN_CODTRAMITADOR SET  CUSUARI = 'NTOUS' WHERE CTRAMITAD = 'T803';

UPDATE SIN_CODTRAMITADOR SET  CUSUARI = 'CARODRIGUEZ' WHERE CTRAMITAD = 'T515';
UPDATE SIN_CODTRAMITADOR SET  CUSUARI = 'EPEREZC' WHERE CTRAMITAD = 'T516';
UPDATE SIN_CODTRAMITADOR SET  CUSUARI = 'PVANEGAS' WHERE CTRAMITAD = 'T511';

DELETE FROM agd_grupos_usu;
Insert into AGD_GRUPOS_USU (CEMPRES,CGRUPO,CUSUARIO,FALTA,CUSUALT,FMODIFI,CUSUMOD) 
select DISTINCT SIN_CODTRAMITADOR.CEMPRES,/*CGRUPO,*/
             DECODE(CTRAMITPAD,'RE01','SI00',CTRAMITPAD),
             CUSUARI,to_date(agd_grupos_usu.FALTA,'DD-MON-RR'),'AXIS',to_date(agd_grupos_usu.FMODIFI,'DD-MON-RR'),'AXIS00' 
             from SIN_CODTRAMITADOR join SIN_REDTRAMITADOR using(ctramitad) 
             LEFT JOIN agd_grupos_usu on cusuari=cusuario
             WHERE
             cusuari   in
             ('EARIAS','CAVARGAS','CARODRIGUEZ','CLAUDIAGARCIA','AXIS_CONF','EPEREZC','FPARRA','ICARDONA','JPENA','LBMURCIA','MBUITRAGO','NMONCAYO','PGARCIA','ECHEVERR','PVANEGAS'
             ,'DGARCIA','JJGONZALEZ','MCRUZ','MOSORIOGUALTEROS','RORDONEZ'
             ,'GGARCIA','MGUTIERREZ','RCASTRO'
             ,'JGONZALEZ'
             ,'GNAVAS','JMENDOZA','JVISBAL','NTOUS'
             );
commit;