--------------------------------PUNTO 21-------------------------------------------------
   DELETE FROM DETVALORES  WHERE CVALOR = 21 AND CATRIBU='45';
   DELETE FROM AXIS_LITERALES WHERE SLITERA= 89907043;
   DELETE FROM AXIS_CODLITERALES WHERE SLITERA= 89907043;

   INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('21', '8', '45', 'Conclusiones');
   INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('21', '2', '45', 'Conclusiones');
   INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('21', '1', '45', 'Conclusiones');
     
   INSERT INTO AXIS_CODLITERALES (SLITERA, CLITERA) VALUES ( 89907043, 2);
   INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (1, 89907043, 'Ya existe una nota de conclusion');
   INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (2, 89907043, 'Ja hi ha una nota de cloenda');
   INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES (8, 89907043, 'Ya existe una nota de conclusion');
   
   ALTER TABLE AGD_OBSERVACIONES  MODIFY (TOBS VARCHAR2(3500 BYTE) );
   
    --------------------------------FIN 21-------------------------------------------------
	
	--------------------------------PUNTO 11-------------------------------------------------------
	
   DELETE FROM CFG_FORM_PROPERTY WHERE CFORM = 'AXISSIN026' AND CITEM = 'CINFORM';
   DELETE FROM CFG_FORM_PROPERTY WHERE CFORM = 'AXISSIN026' AND CITEM = 'TTCAUSIN';
   DELETE FROM CFG_FORM_PROPERTY WHERE CFORM = 'AXISSIN026' AND CITEM = 'TTRAMIT';
   INSERT INTO CFG_FORM_PROPERTY  (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES (24, 555, 'AXISSIN026', 'TTRAMIT', 1, 0);
   INSERT INTO CFG_FORM_PROPERTY  (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES (24, 555, 'AXISSIN026', 'CINFORM', 1, 0);
   INSERT INTO CFG_FORM_PROPERTY  (CEMPRES, CIDCFG, CFORM, CITEM, CPRPTY, CVALUE) VALUES (24, 555, 'AXISSIN026', 'TTCAUSIN', 1, 0);
   
   -------------------------FIN PUNTO 11---------------------------------------------------------------------------
   
   ----------------------------------PUNTO 12----------------------------------------------------------------------
   DELETE FROM DETVALORES  WHERE CVALOR = 319;
   DELETE FROM DETVALORES  WHERE CVALOR = 321;


	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,1,0,'Prenedor');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,1,1,'Assegurat');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,1,2,'Propietari');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,1,3,'Conductor');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,1,4,'Altres');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,1,5,'Mediador/Agent');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,1,6,'Centreasistencial');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,1,7,'TercerAfectad');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,1,10,'Beneficiario');

	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,	2,	0,	'Tomador');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,	2,	1,	'Asegurado');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,	2,	4,	'Otros');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,	2,	5,	'Mediador/Agente');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,	2,	6,	'Centro Ssistencial');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,	2,	10,	'Beneficiario');

	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,	8,	0,	'Tomador');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,	8,	1,	'Asegurado');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,	8,	4,	'Otros');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,	8,	5,	'Mediador/Agente');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,	8,	6,	'Centro Asistencial');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(319,	8,	10,	'Beneficiario');

	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,1,	0,	'Persona');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,1,	1,	'Telèfon');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,1,	2,	'Mediador');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,1,	5,	'Document');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,1,	6,	'WEB');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,1,	7,	'Terceros Afectados');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,1,	9,	'Junta directiva');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,1,	10,	'Vicepresidencia técnica');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,1,	11,	'Ingeniería');

	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,2,	0,	'Persona');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,2,	1,	'Telèfon');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,2,	2,	'Mediador');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,2,	5,	'Document');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,2,	6,	'WEB');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,2,	7,	'Terceros- Afectados');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,2,	9,	'Junta directiva');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,2,	10,	'Vicepresidencia técnica');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,2,	11,	'Ingeniería');

	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,8,	0,	'Centro de contacto');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,8,	1,	'Asegurado');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,8,	2,	'Interventoria');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,8,	5,	'Documento');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,8,	6,	'Notificaciones');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,8,	7,	'Terceros Afectados');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,8,	9,	'Junta directiva');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,8,	10,	'Vicepresidencia técnica');
	INSERT INTO DETVALORES(CVALOR,CIDIOMA,CATRIBU,TATRIBU)VALUES(321,8,	11,	'Ingeniería');

----------------------------FIN PUNTO 12 --------------------------------------------------------------------------
---------------------------PUNTO 13 -------------------------------------------------------------------------------

     DELETE FROM DETVALORES   WHERE CVALOR = 8002018 AND CATRIBU='7';

    INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8002018', '8', '7', 'Factible'); 
    INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8002018', '2', '7', 'Factible'); 
    INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8002018', '1', '7', 'Factible'); 
	
	-- MAXIMA PERDIDA PROBABLE--
  
   DELETE FROM AXIS_LITERALES  WHERE SLITERA = 89906303;
   DELETE FROM DETVALORES  WHERE CVALOR = 8002019 AND CATRIBU=6;
   
  INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES ('1', '89906303', 'Alta / Mod. MPP CONT CAUSA');
  INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES ('2', '89906303', 'Alta / Mod. MPP CONT CAUSA');
  INSERT INTO AXIS_LITERALES (CIDIOMA, SLITERA, TLITERA) VALUES ('8', '89906303', 'Alta / Mod. MPP CONT CAUSA');
  
  INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8002019', '1', '6', 'Deficiente Evaluación de riesgo/ Suscripción');
  INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8002019', '2', '6', 'Deficient Avaluació de risc / Subscripció');
  INSERT INTO DETVALORES (CVALOR, CIDIOMA, CATRIBU, TATRIBU) VALUES ('8002019', '8', '6', 'Deficiente Evaluación de riesgo/ Suscripción');
	
----------------------------FIN PUNTO 13-----------------------------------------------------------------------
----------------------------FIN PUNTO 17 ------------------------------------------------
DELETE FROM cfg_form_property WHERE cform ='AXISSIN006' AND citem='BT_SIN_MAXPP' AND CIDCFG=777 AND CPRPTY=1 AND CVALUE=0;
DELETE FROM cfg_form_property WHERE cform ='AXISSIN006' AND citem='BT_SIN_MAXPP' AND CIDCFG=783 AND CPRPTY=1 AND CVALUE=0;
DELETE FROM cfg_form_property WHERE cform ='AXISSIN006' AND citem='BT_SIN_MAXPP' AND CIDCFG=800 AND CPRPTY=1 AND CVALUE=0;

DELETE FROM cfg_form_property WHERE cform ='AXISSIN006' AND citem='BT_SIN_NUEVO_TRAM_APOYO' AND CIDCFG=777 AND CPRPTY=1 AND CVALUE=0;
DELETE FROM cfg_form_property WHERE cform ='AXISSIN006' AND citem='BT_SIN_NUEVO_TRAM_APOYO' AND CIDCFG=783 AND CPRPTY=1 AND CVALUE=0;


INSERT INTO  cfg_form_property (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) VALUES(24,777,'AXISSIN006','BT_SIN_NUEVO_TRAM_APOYO',1,0);
INSERT INTO  cfg_form_property (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) VALUES(24,783,'AXISSIN006','BT_SIN_NUEVO_TRAM_APOYO',1,0);

INSERT INTO  cfg_form_property (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) VALUES(24,777,'AXISSIN006','BT_SIN_MAXPP',1,0);
INSERT INTO  cfg_form_property (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) VALUES(24,783,'AXISSIN006','BT_SIN_MAXPP',1,0);
INSERT INTO  cfg_form_property (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) VALUES(24,800,'AXISSIN006','BT_SIN_MAXPP',1,0);
-------------------------FIN PUNTO 22-----------------------------------------------
---------------PUNTO 23 EXCEL DE VARIOS ITEMS----------------------------------------------

--LITERAL REPORTE JUDICIAL COL20
UPDATE cfg_lanzar_informes_params SET SLITERA=9000908 WHERE  cform='AXISLIST003' AND CMAP='procesos judiciales' AND TPARAM='NO_DE_REDICADO';

-- ESTABILIDAD DE USUARIOS---
DELETE FROM AGD_GRUPOS_USU WHERE CUSUARIO='JPENA';
DELETE FROM AGD_GRUPOS_USU WHERE CUSUARIO='JGONZALEZ';
UPDATE agd_grupos_usu SET CUSUARIO='MBUITRAGO' WHERE CUSUARIO= 'BUITRAGOM';
INSERT INTO AGD_GRUPOS_USU VALUES(24,	'SI00',	'JPENA',	SYSDATE	,'AXIS'	,NULL,	NULL);
INSERT INTO AGD_GRUPOS_USU VALUES(24,	'SI00',	'JGONZALEZ',	SYSDATE	,'AXIS'	,NULL,	NULL);

--------------FIN PUNTO 23------------------------------------------------
-------------------------------AJUSTE DE USUARIOS-----------------------------------------


DELETE FROM cfg_form_property WHERE cform ='AXISSIN006' AND citem='BT_SIN_NUEVO_AGD_AGENDA' AND CIDCFG=783 AND CPRPTY=1 AND CVALUE=0;
DELETE FROM cfg_form_property WHERE cform ='AXISSIN006' AND citem='BT_SIN_NUEVO_AGD_AGENDA' AND CIDCFG=777 AND CPRPTY=1 AND CVALUE=0;

INSERT INTO  cfg_form_property (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) VALUES(24,777,'AXISSIN006','BT_SIN_NUEVO_AGD_AGENDA',1,0);
INSERT INTO  cfg_form_property (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) VALUES(24,783,'AXISSIN006','BT_SIN_NUEVO_AGD_AGENDA',1,0);


DELETE FROM cfg_form_property WHERE cform ='AXISSIN006' AND citem='BT_SIN_NUEVO_AGD_TRAM' AND CIDCFG=783 AND CPRPTY=1 AND CVALUE=0;
DELETE FROM cfg_form_property WHERE cform ='AXISSIN006' AND citem='BT_SIN_NUEVO_AGD_TRAM' AND CIDCFG=777 AND CPRPTY=1 AND CVALUE=0;

INSERT INTO  cfg_form_property (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) VALUES(24,777,'AXISSIN006','BT_SIN_NUEVO_AGD_TRAM',1,0);
INSERT INTO  cfg_form_property (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) VALUES(24,783,'AXISSIN006','BT_SIN_NUEVO_AGD_TRAM',1,0);

DELETE FROM cfg_form_property WHERE cform ='AXISSIN006' AND citem='BT_SIN_NUEVO_TRAM_PJ' AND CIDCFG=783 AND CPRPTY=1 AND CVALUE=0;
DELETE FROM cfg_form_property WHERE cform ='AXISSIN006' AND citem='BT_SIN_NUEVO_TRAM_PJ' AND CIDCFG=777 AND CPRPTY=1 AND CVALUE=0;


INSERT INTO  cfg_form_property (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) VALUES(24,777,'AXISSIN006','BT_SIN_NUEVO_TRAM_PJ',1,0);
INSERT INTO  cfg_form_property (CEMPRES,CIDCFG,CFORM,CITEM,CPRPTY,CVALUE) VALUES(24,783,'AXISSIN006','BT_SIN_NUEVO_TRAM_PJ',1,0);



--- PENDIENTE A VALIDAR
 UPDATE USUARIOS SET FBAJA=NULL WHERE CUSUARI='MCRUZ';
 UPDATE USUARIOS SET FBAJA=NULL WHERE CUSUARI='CLAUDIAGARCIA';
 UPDATE USUARIOS SET FBAJA=NULL WHERE CUSUARI='EARIAS';
 UPDATE USUARIOS SET FBAJA=NULL WHERE CUSUARI='DGARCIA';
 UPDATE USUARIOS SET FBAJA=NULL WHERE CUSUARI='EARIAS';
 UPDATE USUARIOS SET FBAJA=NULL WHERE CUSUARI='JPENA';
 UPDATE USUARIOS SET FBAJA=NULL WHERE CUSUARI='MOSORIOGUALTEROS';
   COMMIT;