/*Grants tabla y sinonimo para CON_HOMOLOGA_OSIAX*/
GRANT DELETE, INSERT, UPDATE, SELECT ON AXIS.CON_HOMOLOGA_OSIAX TO R_AXIS;
CREATE OR REPLACE SYNONYM AXIS00.CON_HOMOLOGA_OSIAX FOR AXIS.CON_HOMOLOGA_OSIAX;
/